### ISSUE TITLE
HELP! Black screen, audio playing.

### ISSUE THREAD

**Issue by Mindvelopers** [clappr/clappr#1000]
**OS**: Windows 10

**Clappr Version**: 0.2.25

Sometimes this player dont reproduce the video, but audio keep working.

As you see: All black, no media-control, nothing.
https://i.gyazo.com/efb9847e42dab177915f6d17ede9e4b7.png

I'm working with m3u8 files
Console: 
https://gyazo.com/ec70be48093d33e29f820a845fea603f

It is in Portuguese, but I think this plugin is from brazilian guys xD
https://gyazo.com/ae3c6865b6b5e0270851c9af21bf7d04

**Comment by leandromoreira** [comment]
Can you? 

1. Re-test it using this source http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 ?
2. Re-test with your url using this http://dailymotion.github.io/hls.js/demo/ ?
3. can you turn on the logs
```javascript
Clappr.Log.setLevel(Clappr.Log.LEVEL_DEBUG)
```

**Comment by thiagopnts** [comment]
1000th issue 🎉

**Comment by leandromoreira** [comment]
- 1000 issues (47 opened)
- 2831 commits
- 183 releases
- 37 contributors

**Comment by Mindvelopers** [comment]
I think this is the "mediasource" error.
But this just happens for some people and just some times.
Now everything works fine, but this happens a lot of times with live stream.

**Comment by leandromoreira** [comment]
@Mindvelopers maybe this could be related to the hls stream generated by your end point.

**Comment by cthulhubird** [comment]
Hi
I'm experiencing same issue right now, but have more info on it.
According to my tests it's happening when stream has 'mp2' audio codec and 'mpeg2video' video codec. But with vlc these streams plaing just fine.

Clappr Version: 0.2.85
Browser: Firefox 59.0.1 / SRWare Iron 63.0.3300.0 (Developer Build) (Debian 9)

link to reproduce: http://66.70.182.154:25461/live/test_user/test_user/11001.m3u8

clappr debug log: 
`[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][Container] container:mediacontrol:disable
[debug][Core] core:containers:created
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][Container] container:dvr false
[debug][MediaControl] mediacontrol:hide MediaControl
[debug][Container] container:mediacontrol:hide
[debug][MediaControl] mediacontrol:containerchanged
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][Events] 1:resize 
Object { width: "300px", height: "300px" }
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][Events] 1:resize 
Object { width: 300, height: 300 }
[debug][Container] container:mouseenter
[debug][hls] playback:ready hls
[debug][Container] container:ready Container
[debug][Core] core:ready
[debug][Player] ready
[debug][Container] container:volume 100 Container
[debug][Player] volumeupdate 100
[debug][Container] container:volume 100 Container
[debug][Player] volumeupdate 100
[debug][hls] playback:play:intent
[debug][hls] playback:buffering hls
[debug][Container] container:state:buffering Container
[debug][hls] playback:levels:available 
Array [ {…} ]
[debug][hls] playback:levels:switch:end
[debug][hls] playback:level:switch 
Object { url: […], details: undefined, loadError: 0, fragmentError: false, urlId: 0, level: 0 }
[debug][hls] playback:highdefinitionupdate false
[debug][Container] container:highdefinitionupdate false
[debug][hls] playback:bitrate 
Object { height: undefined, width: undefined, bandwidth: undefined, bitrate: undefined, level: 0 }
[debug][Container] container:bitrate 
Object { height: undefined, width: undefined, bandwidth: undefined, bitrate: undefined, level: 0 }
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][MediaControl] mediacontrol:playing
[debug][MediaControl] mediacontrol:rendered
[debug][Container] container:mouseleave
[debug][hls] playback:fragment:loaded 
Object { payload: ArrayBuffer, frag: {…}, stats: {…}, networkDetails: XMLHttpRequest }
[debug][hls] playback:loadedmetadata 
Object { duration: 60.639979, data: loadedmetadata }
[debug][Container] container:loadedmetadata 
Object { duration: 60.639979, data: loadedmetadata }
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:seeked
[debug][Container] container:seeked Container
[debug][hls] playback:bufferfull hls
[debug][Container] container:state:bufferfull Container
[debug][hls] playback:play
[debug][Container] container:play Container
[debug][Container] container:mediacontrol:enable
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:playing
[debug][Player] play
[debug][MediaControl] mediacontrol:hide MediaControl
[debug][Container] container:mediacontrol:hide
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][Container] container:mouseenter
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][Container] container:mouseleave
[debug][MediaControl] mediacontrol:mousemove:seekbar 
Object { originalEvent: mousemove, isTrusted: true, preventDefault: name(), isDefaultPrevented: returnFalse(), stopImmediatePropagation: name(), isImmediatePropagationStopped: returnFalse(), stopPropagation: name(), isPropagationStopped: returnFalse(), initMouseEvent: initMouseEvent(), getModifierState: getModifierState(), … }
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:mousemove:seekbar 
Object { originalEvent: mousemove, isTrusted: true, preventDefault: name(), isDefaultPrevented: returnFalse(), stopImmediatePropagation: name(), isImmediatePropagationStopped: returnFalse(), stopPropagation: name(), isPropagationStopped: returnFalse(), initMouseEvent: initMouseEvent(), getModifierState: getModifierState(), … }
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:mouseleave:seekbar 
Object { originalEvent: mouseout, isTrusted: true, preventDefault: name(), isDefaultPrevented: returnFalse(), stopImmediatePropagation: name(), isImmediatePropagationStopped: returnFalse(), stopPropagation: name(), isPropagationStopped: returnFalse(), initMouseEvent: initMouseEvent(), getModifierState: getModifierState(), … }
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][Container] container:stats:report 
Object { startupTime: 7082, rebuffers: 1, rebufferingTime: 0, watchingTime: 5002, level: 0 }
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][hls] playback:stop
[debug][Container] container:stop
[debug][Container] container:mediacontrol:disable
[debug][MediaControl] mediacontrol:hide MediaControl
[debug][Container] container:mediacontrol:hide
[debug][Container] container:stats:report 
Object { startupTime: 7082, rebuffers: 1, rebufferingTime: 0, watchingTime: 5364, level: 0 }
[debug][MediaControl] mediacontrol:notplaying
[debug][Player] stop 6.0045200000000065
[debug][Container] container:mouseenter
[debug][hls] playback:pause
[debug][Container] container:pause Container
[debug][MediaControl] mediacontrol:notplaying
[debug][Player] pause
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate`

**Comment by leandromoreira** [comment]
Can you try to follow the [troubleshooting](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues)? (mostly the checking of your stream healthy, it's problably this kind of problem)
