### ISSUE TITLE
Keyboard handler exposed to the outside world

### ISSUE THREAD

**Issue by iongion** [clappr/clappr#1009]
Can you make it so that **_Kibo_** is available to the outside word ?

Currently I am using a tiny and beautiful library called **MouseTrap** from [this link](https://github.com/ccampbell/mousetrap), but investigating a little inside Clappr, I found the Kibo module, while it is not as flexible as MouseTrap, it does the job and will offer the possibility to not need any other libraries when creating Clappr plugins.

**Comment by leandromoreira** [comment]
I think this is fair and solid! thoughts @clappr/core ?

**Comment by towerz** [comment]
@leandromoreira that would be cool. 👍
