### ISSUE TITLE
Handling network errors loading manifests and fragments

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1012]
Hello,

I'm trying to handle errors during load of network manifest or fragments but can't find a proper way to do it with onError event or PLAYBACK_ERROR. I tested it with non-existent manifest URL and it seems that network error does not trigger corresponding event because of trying to perform startLoad hls.js method:
```
[warn][hlsjs: trying to recover from network error, evt hlsError, data [object Object] ]
[log] > startLoad
[warn] > cannot start loading as manifest not parsed yet
```
Even more in general how can I implement fallback sources strategy of playing? Lets say I have one URL with ABR HLS manifest that should be initially loaded and the second URL (even with other mime type) that should be used if HLS playback was broken initially or while playing.

With regards, Andrey.

**Comment by leandromoreira** [comment]
@waster I think we already do that https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L142 and you can fine tune for more tries https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L51

**Comment by waster** [comment]
Yes, as I see it retries two times with 404 by default for now, but then stopped with `cannot start loading as manifest not parsed yet` in startLoad method and did not throw any error to handle.

**Comment by leandromoreira** [comment]
@waster ohh that's something we need to check, also [hls.js just released a new version](https://github.com/dailymotion/hls.js/releases/tag/v0.5.33) with some fixes regarding the error recover.

**Comment by waster** [comment]
Hellp, any news about that issue?

**Comment by leandromoreira** [comment]
@waster can you build from master and test it again?

**Comment by waster** [comment]
Tested with the current master. Unfortunately problem still remains. I added the following code to the player config :

```
events: {
       onError: function() { console.log("Error"); }
}
```

And tried to load non-existent 404 manifest. Still no error event after two retries and console messages are:

```
[log] > startLoad
[warn] > cannot start loading as manifest not parsed yet
```

**Comment by leandromoreira** [comment]
Thanks @waster I'm gonna take a look at this later.

**Comment by leandromoreira** [comment]
I confirmed @waster I [opened an issue on hls.js](https://github.com/dailymotion/hls.js/issues/491) to see if this is intentional or not.

**Comment by waster** [comment]
Hello @leandromoreira , I tested it with current clappr and it seems that onError event is not triggering still with the same hlsjs warn. BTW, Is it posible to display different messages for different errors via clappr API?

**Comment by leandromoreira** [comment]
@waster we wont fix that, this is [an issue on hls.js](https://github.com/dailymotion/hls.js/issues/491).

>  Is it posible to display different messages for different errors via clappr API?

You can create a plugin to show your own errors, you then listen to PLAYER_ERROR and show them at the screen, we already do that when we can't play a given playback https://github.com/clappr/clappr/blob/master/src/playbacks/no_op/no_op.js

**Comment by waster** [comment]
@leandromoreira did you close this bug because it will be automatically fixed when corresponding hls.js 491 issue corrected?

**Comment by leandromoreira** [comment]
@waster yes :D I also referenced some nice peeps that would able to work around that.

Is it okay to close this one?

**Comment by waster** [comment]
@leandromoreira ah, sure, we can close this for now. I hope hls.js will fix that issue soon.
