### ISSUE TITLE
Playback plugins are not respecting the order of preference

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#1013]
Go to cdn.clappr.io and type:

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  plugins: [Clappr.HLS],
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

player.on(Clappr.Events.PLAYER_PAUSE, function(){
  alert(player.core.getCurrentPlayback().name)
})
```

Pause and you'll see "html5_video" instead of "hls"

**Comment by towerz** [comment]
@leandromoreira the problem is not actually the playback priority. If you change the playback to `Clappr.FlasHLS` instead, it will override the playback properly.

The problem is related to an explicit check in the HLS playback `canPlay` method:
```javascript
return !!(HLSJS.isSupported() && isHls && !Browser.isSafari)
```
Removing the `!Browser.isSafari` would fix this behavior, but I don't recommend since the HLS playback does not behave well on Safari.

**Comment by thalleshmm** [comment]
@towerz Am I doing something wrong? I tested on both Chrome and Firefox, and they were able to use the Flash playback. In Safari though, playback is still HTML.

![captura de tela 2016-06-01 as 09 18 47](https://cloud.githubusercontent.com/assets/6493006/15709248/158a5648-27da-11e6-9e14-9b842f23d2a9.png)

OSX 10.11.3 (15D21)
Safari 9.0.3 (11601.4.4)

**Comment by towerz** [comment]
@thalleshmm Could you share the URL you have used on your test? I tried doing the same with @leandromoreira's sample and it worked correctly for me.
```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  plugins: [Clappr.FlasHLS],
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

player.on(Clappr.Events.PLAYER_PAUSE, function(){
  alert(player.core.getCurrentPlayback().name)
})
```

**Comment by thalleshmm** [comment]
@towerz I'm using 'http://streaming50.sitehosting.com.br:1935/thalles/thalles/playlist.m3u8?DVR'.

That doesn't seem to be the problem, anyway. I've also tried with the default sample on the CDN, and I just tried copying the code you just posted.

![captura de tela 2016-06-01 as 16 08 04](https://cloud.githubusercontent.com/assets/6493006/15722430/19841d80-2814-11e6-8107-dc3dcfba2a63.png)

I just tried in another Mac, and it works perfectly. Probably something to do with my Flash Plugin, I imagine. =)

**Comment by towerz** [comment]
@thalleshmm the FlasHLS playback checks whether or not the Flash plugin is installed. Could you try running this on your Safari javascript console?
```javascript
navigator.mimeTypes && navigator.mimeTypes['application/x-shockwave-flash'] !== undefined && navigator.mimeTypes['application/x-shockwave-flash'].enabledPlugin
```

**Comment by thalleshmm** [comment]
@towerz it wasn't installed. I'm sorry, my bad, I failed to notice it. Once I installed Adobe's Flash Player, FlasHLS was able to detect it and ran.
