### ISSUE TITLE
Stream keeps loading. 

### ISSUE THREAD

**Issue by Mordinoid** [clappr/clappr#1016]
**Browser**:  Chrome Version 50.0.2661.102(or any), Firefox Version 46.0.1(or any),

**OS**: Windows 7,8,10

**Clappr Version**: Can`t see which one is it. :/ But should be latest.

**Steps to reproduce**:

* Click on play button
* It just loads and nothing happens.

 Hello. Sorry for my english in advance. I tried to find a solution of my problem, but it was nowhere to be found. I am using your player on my website to play m3u8 files. 
 It used to work without any problems, but now it just keeps loading.

 Here is a code I use, which was made for me:

```
<head>
<script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
</head>

<body>
<div id="player"></div>
  <script>
    var player = new Clappr.Player({source: "http://msk3.peers.tv/streaming/multimania/16/tvrec/playlist.m3u8", parentId: "#player"});
  </script>
</body>
```

 I tried to use it on http://cdn.clappr.io/ but it seems there is something wrong with code.

http://banktv.at.ua/publ/filmovye/tv_1000_megahit_hd_smotret_online/5-1-0-61 
Here is an example of page. It`s in russian(sorry) but the play button is international. :]

 Thanks in advance, and sorry for being stupid. 
Best regards. Ekaterina.

**Comment by leandromoreira** [comment]
Hi @Mordinoid try to use the previous version, it seems we have [a bug happening with the latest](https://github.com/clappr/clappr/issues/1015).
```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/0.2.52/clappr.min.js"></script>
```

**Comment by Mordinoid** [comment]
Thank you so much, it worked! I`ll be closing this now.
