### ISSUE TITLE
how to seek player

### ISSUE THREAD

**Issue by dakora1310** [clappr/clappr#1018]
Hello, pls help me.
I load  new source and then I need seek video to 2 minutes.
My code
loadSours: function (sources) {
       seconds = 120;
       this.camControl.load( sources ); 
       this.camControl.seek(seconds);
       this.camControl.play();
}

But seek does not work

**Comment by leandromoreira** [comment]
@dakora1310 I think you can use `autoSeekFromUrl: true` and then `/?t=100`
