### ISSUE TITLE
Cant load M3U8 just on clappr

### ISSUE THREAD

**Issue by Mindvelopers** [clappr/clappr#1021]
I'm using Clappr because it's amazing, but a problem occurred when I finally got my streaming servers and tried to live stream :(
http://i.imgur.com/NtP0pJa.png

As you can see I cant play it :( I tried on flowplayer, video.js and jwplayer and it works nice...

My clappr config:
```
var player = new Clappr.Player({
			source: "http://*******:1935/share/kmjnhgt/playlist.m3u8",
			parentId: "#liveStream",
			hideVolumeBar: true,
			autoPlay: 1,
			audioOnly: false,
			disableVideoTagContextMenu:  0,	
			plugins: {
				'core': [LevelSelector],				
			},
			levelSelectorConfig: {
				title: 'Quality',
				labels: {
					5: '4k',
					4: '2k',
					3: '1080p', 
					2: '720p',
					1: '480p',
					0: '360p',
				},
				initialState: 0
			},					
			width: "640px",
			height: "370px"
});
```

**Comment by leandromoreira** [comment]
Can you:
* check your [cors headers at your servers](https://github.com/clappr/clappr/issues/703)
* try to run it on [hls.js demo page](http://dailymotion.github.io/hls.js/demo/)
* try to run it on [flashls. demo page](http://www.flashls.org/latest/examples/chromeless/)

[Very often these kinds of error](https://github.com/clappr/clappr/issues/990) are related to your input (rtmp, upd ...) or the generated output (hls)

**Comment by Mindvelopers** [comment]
Tried everything you send.
It works on every flash player, but not on hls.js player's.
Could this problem be on my server? need to activate something to work on html5? I'm using wowza...

**Comment by leandromoreira** [comment]
@Mindvelopers it could be:
* try to use `$ mediainfo file.ts` over one .ts file of this stream (the links I provided show you how)
* check if you enabled CORS headers at your server `$ curl -v http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 >> /dev/null` check if the output has something like:

Access-Control-Allow-Origin: *

**Comment by Mindvelopers** [comment]
Hi, the CORS were enabled, but the problem was on the Access-Control-Allow-Origin: * xD
Thanks a Lot! How can I buy you a beer?
