### ISSUE TITLE
Problems loading HLS streamed by Adobe FMS 5 in Chrome

### ISSUE THREAD

**Issue by samcarmex** [clappr/clappr#1026]
Chrome 51.0.2704.84 m (64-bit)
Windows 7 64 Bit
Clappr Version: 0.2.25
1. Stream a HLS livestream from an instance of Adobe Media Server 5
2. Attempt to play .m3u8 source inside Clappr in Chrome browser

Obviously the stream is expected to buffer and play without break. Instead, Chrome loads the initial few seconds of the live stream, plays it, freezes, then buffers infinitely without anything further being played. When inspecting, I can see the .m3u8 being fetched but the new .ts files aren't being loaded & played. I have tried a separate stream encoded with Wowza and everything works fine in Clappr. It's just to do with how Adobe Media Server 5 encodes the live stream (and how Clappr then reads that stream).

This issue was reproduced at http://cdn.clappr.io/ & same problem. When using other players/plugins, the same .m3u8 plays without a hitch. For instance, when playing in Grind Player with OMSF HLS plugin, it loads completely fine. 

See test player here:
http://trnsmt.tv/admincpanel/testoclappr.html

**Comment by samcarmex** [comment]
To add to above - I have since linked to previous Clappr build 0.2.52 and it works perfectly on desktop. 
I've seen a couple of mentions of possibly this same bug so feel free to close if the issue is already well known.  

Lastly, accessing this test player on an Android device (Nexus 5, Chrome), I can audibly hear the segments overlapping/glitching. What can be causing this? What sort of buffer rules should be present in the options?

**Comment by leandromoreira** [comment]
It's already know :) thanks a lot! 

> I can audibly hear the segments overlapping/glitching. What can be causing this? What sort of buffer rules should be present in the options?

I'd for you to go to our [troubleshooting guide](TROUBLESHOOTING.md), very often these glitching/overlapping are related either to your input or segmentation (mostly PTS) and some cases, mostly for mobile, some devices might behave very different from other similar device :(

**Comment by leandromoreira** [comment]
The troubleshooting is in another branch https://github.com/clappr/clappr/blob/split_readme/TROUBLESHOOTING.md (yet to be merged)

**Comment by kungfu315** [comment]
and, icon play and icon loading center not working, no show when stop. test in chrome 64 bit win 10. firefox is ok.

See test player here:
http://trnsmt.tv/admincpanel/testoclappr.html

**Comment by samcarmex** [comment]
The main source (m3u8) is a live stream between 8.00 - 14.00 GMT. Outside of those hours we would like the player to fall back to audio stream (has been added to that test player as another source). However, when the live .m3u8 is not available, the player tries to buffer infinitely and never falls back to the audio source. Have I configured the sources wrong or is this a bug?

**Comment by kungfu315** [comment]
i try live .m3u8 http://125.235.29.16/livetv/keeng.m3u8 but icon play center no show when stop

**Comment by leandromoreira** [comment]
@samcarmex 
> However, when the live .m3u8 is not available, the player tries to buffer infinitely and never falls back to the audio source. Have I configured the sources wrong or is this a bug?

How are you setting this up?

**Comment by samcarmex** [comment]
@leandromoreira 

See test player source - is that correct or do I need to use some sort of plugin to have it fall back?
http://trnsmt.tv/admincpanel/testoclappr.html

**Comment by leandromoreira** [comment]
@samcarmex ohh I think you're doing right but the way Clappr works is different than what you expect, the [fallback plugin](https://github.com/clappr/clappr/blob/master/src/plugins/sources.js) works as in video tag, you inform some and Clappr will chose the first that works.

In your case you'll probably need to listen to [PLAYER_ERROR](http://clappr.github.io/classes/Events.html#event_PLAYER_ERROR) and then `load` another source.
