### ISSUE TITLE
Cant play live from adobe encoder just on clappr

### ISSUE THREAD

**Issue by widestreamio** [clappr/clappr#1029]
I have a live stream service. And all works fine, but, it has one problem.
I can play things streamed by xsplit, but not by adobe encoder.
It's like a strange thing, and, unfortunately, I cant find any answer for this :/

I'm using wowza (paid), here some prints of my configuration.
http://i.imgur.com/WQZLbfy.png
http://i.imgur.com/k31df5d.png

Log message:
http://i.imgur.com/RNsTnxZ.png

Works fine on jwplayer and video.js
I checked a lot of user issues here. like #1021 #1010 
tested on http://cdn.clappr.io/
Searched on docs.

**Comment by leandromoreira** [comment]
@widestreamio usually these errors are related to your configs on segmentation (the server that will generate hls/dash) or the input (rtmp/udp) I'd say go to [troubleshooting](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md) very often this is related to missaligned PTS or even lack of keyframes (or misconfigured keyframes)

**Comment by widestreamio** [comment]
Do you stream with adobe flash live encoder?
Do you know some website that I can test live streaming with clappr?

**Comment by leandromoreira** [comment]
@widestreamio
1) Yes, we use lots of encoder one of them being http://www.adobe.com/br/products/flash-media-encoder.html you might double check your configs http://help.adobe.com/en_US/FlashMediaLiveEncoder/3.1/Using/WS5b3ccc516d4fbf351e63e3d11c104babd5-7fe0.html  I'd also would suggest https://obsproject.com/
2) I don't know if I understood you but you can test clappr at http://cdn.clappr.io/

**Comment by widestreamio** [comment]
1) nothing on the configs.
2) i was talking about a website that I can live stream, but one with clappr.
I am persisting on clappr, because I made 6 different designs with clappr, it was a lot of work. :/
Is there another place that I can talk with you and after, post the resolution here?

**Comment by me-vlad** [comment]
@widestreamio  please try to disable low-latency stream option in your wowza app config.

**Comment by leandromoreira** [comment]
@widestreamio I don't know if I really understood again but https://streamroot.readme.io/docs/clappr is working with clappr.

Do you want a page to show the player? do you want a service to stream live? (like wowza or amazon?)

**Comment by widestreamio** [comment]
@me-vlad Tested! But nothing happens :(
@leandromoreira What I want is something like twitch, that I can stream with adobe encoder and see if the problem is on my server, or the player can't read some codecs, well, can this be something about codecs?

**Comment by leandromoreira** [comment]
@widestreamio as I said to you we use clappr as our live player (for hls) and that's okay, https://streamroot.readme.io/docs/clappr offers what you want, I think Azure and Amazon too both you'll spent a little amount of money. But you'll be able to test. Or if you are skilled with docker you can use this solution https://github.com/brocaar/nginx-rtmp-dockerfile

**Comment by widestreamio** [comment]
I dont know how to use that streamroot :O
A friend of mine told me this is a codec problem, can it be?

**Comment by leandromoreira** [comment]
@widestreamio yes, it could be, but there are tons of details behind this "issue" that's why I point you to https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md guide you can try to read the guide from streamroot I think they can help you.

**Comment by widestreamio** [comment]
The problem is, i'm out of time xD, is it really possible to make this work on hls.js/clappr, should I continue trying?
I tested everything on troubleshooting, works on flashhls, but not on hls.js :(

**Comment by leandromoreira** [comment]
@widestreamio yes several companies are using hls.js :) I searched this http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/live-streaming-wowza.html

**Comment by widestreamio** [comment]
How can I get in contact with you? It's difficult to explain by comments.
I can find an answer and post it here later.

**Comment by widestreamio** [comment]
@leandromoreira This is fixed, but I found another problem, sometimes, the player doesn't start... it just dont load the video... and the log says nothing, what can this be?

**Comment by leandromoreira** [comment]
@widestreamio are you still facing the problem above? if yes follow [the steps to open an issue](https://github.com/clappr/clappr/blob/master/doc/BEFORE_OPEN_AN_ISSUE.md), thanks :)
