### ISSUE TITLE
Feature Request - way to update gaAccount after player is declared?

### ISSUE THREAD

**Issue by ibreakstuff93** [clappr/clappr#1031]
Would you consider adding a way to update gaAccount info, after the player has been declared?

Similar to for example player.load('some_url');

but instead:

player.gaAccount('ga_accountid');

It would really help on a project i'm working on :)

**Comment by leandromoreira** [comment]
@ibreakstuff93 we're reworking the GA plugin :D but I think you can already do that if you use the `player.configure({source: 'newurl', gaAccount: 'blablalba'})` method
