### ISSUE TITLE
Failure to seek to any frame but a keyframe in MOV files.

### ISSUE THREAD

**Issue by SYugel** [clappr/clappr#1032]
**Browser**: Chrome Version  51.0.2704.84 (64-bit)

**OS**: MAC OSX 10.9.4

**Clappr Version**: 0.2.47 

**Steps to reproduce**:
- Load an MOV file into the clappr player.
- Then attempt to seek to a specific location in the file either using the scrub bar or calling the seek command on the player directly.
- I was expecting the player to seek to that exact time in the file, but instead it attempts to seek but actually takes you back to the nearest keyframe before the frame you try to seek too.

I was successfully able to reproduce the issue at http://cdn.clappr.io.

[bugContent.zip](https://github.com/clappr/clappr/files/321368/bugContent.zip)

I have attached a zipped directory that includes an mov video file with timecode burned in that contains a keyframe roughly every four seconds.  Also included is a csv file created using ffprobe to inspect the frames in the included mov file.  This csv shows the time in seconds the frame occurs and the type of frame.

**Comment by leandromoreira** [comment]
@SYugel when you try to do the same using only the video tag does it works as expected?

**Comment by SYugel** [comment]
@leandromoreira 
It does work as expected when you play the video in the video tag. I have included a link to a codepen that shows the behavior.  However you will have to serve the video contained in the bugContent.zip above using an apache server to see it.

If you then attempt to seek to a time in the video it correctly seeks to that time.  You can use the frames.csv file also contained in the bugContent.zip to see frames and times in seconds for each frame in the mov.  
http://codepen.io/anon/pen/vKgByE?editors=1011

**Comment by leandromoreira** [comment]
Thanks I'll check this later!

**Comment by joaopaulovieira** [comment]
Hi @SYugel , i tested with the file you sent (thanks for that! /õ/) and could not reproduce the behavior. The problem still persist?

**Comment by SYugel** [comment]
Hey @joaopaulovieira I confirmed this seems to no longer be an issue.
