### ISSUE TITLE
Get current playing fragment sequence number

### ISSUE THREAD

**Issue by mkozlov1** [clappr/clappr#1043]
Hi.

How to get a current playing fragment sequence number?

**Comment by leandromoreira** [comment]
We're using hls.js as base to play hls therefore you can subscribe to [`Hls.Events.FRAG_LOADED`](https://github.com/dailymotion/hls.js/blob/master/API.md#runtime-events):

```javascript
// frag ={
//   duration: 10,
//   level: 3,
//   sn: 35,
//   start: 30,
//   url: 'http://fragURL.com'
// }
```

player.core.getCurrentPlayback().on(Clappr.Events.PLAYBACK_FRAGMENT_LOADED, function(frag) {
console.log(frag.sn)
});

**Comment by mkozlov1** [comment]
Clappr.Events.PLAYBACK_FRAGMENT_LOADED fired on fragment loading, not on fragment play.

![frags](https://cloud.githubusercontent.com/assets/5320093/16333290/28b05188-3a03-11e6-95a6-b8b160471b96.PNG)

**Comment by leandromoreira** [comment]
@mkozlov1 you're right, looking at the hls.js API:

  - `Hls.Events.FRAG_LOADED`  - fired when a fragment loading is completed
    -  data: { frag : fragment object, payload : fragment payload, stats : { trequest, tfirst, tload, length}}
  - `Hls.Events.FRAG_PARSING_INIT_SEGMENT` - fired when Init Segment has been extracted from fragment
    -  data: { id: demuxer id, moov : moov MP4 box, codecs : codecs found while parsing fragment}
  - `Hls.Events.FRAG_PARSING_METADATA`  - fired when parsing id3 is completed
      -  data: { id: demuxer id, samples : [ id3 pes - pts and dts timestamp are relative, values are in seconds]}
  - `Hls.Events.FRAG_PARSING_DATA`  - fired when moof/mdat have been extracted from fragment
    -  data: { id: demuxer id, moof : moof MP4 box, mdat : mdat MP4 box, startPTS : PTS of first sample, endPTS : PTS of last sample, startDTS : DTS of first sample, endDTS : DTS of last sample, type : stream type (audio or video), nb : number of samples}
  - `Hls.Events.FRAG_PARSED`  - fired when fragment parsing is completed
    -  data: { id: demuxer id}
  - `Hls.Events.FRAG_BUFFERED`  - fired when fragment remuxed MP4 boxes have all been appended into SourceBuffer
    -  data: { id: demuxer id, frag : fragment object, stats : { trequest, tfirst, tload, tparsed, tbuffered, length} }
  - `Hls.Events.FRAG_CHANGED`  - fired when fragment matching with current video position is changing
    -  data: { frag : fragment object }
  - `Hls.Events.FPS_DROP` - triggered when FPS drop in last monitoring period is higher than given threshold
    -  data: { curentDropped : nb of dropped frames in last monitoring period, currentDecoded : nb of decoded frames in last monitoring period, totalDropped : total dropped frames on this video element }

I think you can use either `FRAG_BUFFERED` or `FRAG_CHANGED`:

```javascript
player.core.getCurrentPlayback()._hls.on('hlsFragChanged', function(frag) {
  console.log(frag.sn)
});
```

**Comment by mkozlov1** [comment]
Greate, frag_changed is that what i need.

But proper code is
player.core.getCurrentPlayback()._hls.on('hlsFragChanged', function(event, object) {
  console.log(object.frag.sn);
});

**Comment by leandromoreira** [comment]
lol @mkozlov1 I'll close this one, okay?

**Comment by mkozlov1** [comment]
@leandromoreira yep!
