### ISSUE TITLE
DRM and HLS-AES support

### ISSUE THREAD

**Issue by paunadeu** [clappr/clappr#1051]
Hello,
It's any plan to implement a DRM and HLS-AES support? Our content provider (Mediapro) require it for a sports broadcasting. 

BuyDRM, Verimatrix or EZDRM is most used and are welcome. 

If any developer can develop this we can speak for sponsor this function.

Regards.

**Comment by leandromoreira** [comment]
@paunadeu we use hls.js as a playback for HLS and it supports `AES-128 decryption (AES-128 mode)` not DRM though. Maybe @mangui might be interested, anyway I think you should open this ticket at https://github.com/dailymotion/hls.js maybe someone can take this!

**Comment by paunadeu** [comment]
Ticket opened at HLS.js project. Thank you Leandro for your quick answer. 
BTW, have you example of integration of AES-128 with Clappr?
We are using Clappr in a IPTV Application that's used by a hundreds persons.

Best regards,
Pau.

**Comment by leandromoreira** [comment]
> BTW, have you example of integration of AES-128 with Clappr?

I think you can just enable on your server and that's it! No need to extra config.

**Comment by matheusrufca** [comment]
@paunadeu Hello Pau, did you succeed on playing DRM protected streaming on Clappr?

**Comment by leandromoreira** [comment]
@matheusrufca are you asking in regard of hls streaming or DASH?

**Comment by matheusrufca** [comment]
@leandromoreira Better if HLS. I'm testing Clappr on SmartTVs (Tizen, WebOS) and Clappr had better results playing HLS over DASH.

**Comment by leandromoreira** [comment]
@matheusrufca for HLS I think you're going to wait, there is an [open ticket](https://github.com/video-dev/hls.js/issues/510) for this though.
