### ISSUE TITLE
events not working if m3u8  file dont have end tag ["#EXT-X-ENDLIST"]

### ISSUE THREAD

**Issue by siddhesharolkar** [clappr/clappr#1052]
HI, I am trying to implement network error handling.
I tried with :
player.listenTo(player, Clappr.Events.PLAYER_ERROR, function() { console.log("ERROR!") });
player.listenTo(player, Clappr.Events.PLAYBACK_ERROR, function() { console.log("playeback ERROR!") });
container.on(Clappr.Events.CONTAINER_ERROR, function() { alert('$$==>CONTAINER_ERROR'); });

but none of this working for me.
I am playing m3u8 file which is dynamically increasing.
In my case end tag is missing in m3u8 file.
So is it possible to get all these event without closing tag in m3u8 file?
Can you please help me out in this.....

**Comment by leandromoreira** [comment]
@siddhesharolkar can you explain what kind of errors are you expecting to catch from `PLAYER_ERROR` ? What steps you followed to raise a error?

**Comment by siddhesharolkar** [comment]
Hi leandromoreira,

Thanks for quick response.
I have downloaded clappr.js version - 0.2.56.
I have created sample HTML file : 

[play.txt](https://github.com/clappr/clappr/files/337048/play.txt)


When i run this file i am able to get only "Inside PLAYER_PLAY event!" in console.
I have tried by putting invalid file source, still no error handled like 404.
I tried with editing .m3u8 file with invalid path for .ts files

**Comment by leandromoreira** [comment]
@siddhesharolkar for some of the errors we'll try to recover (for instance 404) [there is an open issue about this problem.](https://github.com/clappr/clappr/issues/1012)

Abou the events you can:

```javascript
// listen to player events within the player component

//via constructor (more reliable for once time event) 
var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
events: {
      onReady: () => console.log('ready'),
//      onResize: Events.PLAYER_RESIZE,
 //     onPlay: Events.PLAYER_PLAY,
  //    onPause: Events.PLAYER_PAUSE,
  //    onStop: Events.PLAYER_STOP,
  //    onEnded: Events.PLAYER_ENDED,
   //   onSeek: Events.PLAYER_SEEK,
   //   onError: Events.PLAYER_ERROR,
 //     onTimeUpdate: Events.PLAYER_TIMEUPDATE,
   //   onVolumeUpdate: Events.PLAYER_VOLUMEUPDATE
    }
});


//pos constructor
player.on(Clappr.Events.PLAYER_ENDED, () => console.log(''))
// listen to player events within the container component
var container = player.core.getCurrentContainer()
container.on(Clappr.Events.CONTAINER_ENDED, () => console.log(''))
// listen to player events within the playback component
var playback = container.playback
playback.on(Clappr.Events.PLAYBACK_ENDED, () => console.log(''))
```

**Comment by siddhesharolkar** [comment]
Hi Leandro,
Thanks for your help. I am able to add temporary solution for this issue. 
I really appreciate for your valuable help. Thanks once again.
