### ISSUE TITLE
handle error, failover m3u8

### ISSUE THREAD

**Issue by ewwink** [clappr/clappr#1053]
can clappr failover to another .m3u8 when first source error?

**Comment by leandromoreira** [comment]
@ewwink you can do that by your own listening the `PLAYER_ERROR` event.

**Comment by paunadeu** [comment]
To another m3u8 or another source. It's good to implement. Can I try to implement like a param in constructor and do a pull request? Or only Leandro can to this?

**Comment by ewwink** [comment]
@leandromoreira how to do that?

```
<div id="player"></div>
<script>
var player = new Clappr.Player(
{
  source: "http://example.com/bad.m3u8",
  parentId: "#player",
  autoPlay: false
});

// need to play this
player.on(Clappr.Events.PLAYER_ERROR, function() {
  player.source = "http://example.com/good.m3u8";
  player.play();
});
</script>
```
I also tried below but still not work
```
<script>
var player = new Clappr.Player(
{
  source: ["http://example.com/bad.m3u8", "http://example.com/good.m3u8"],
  parentId: "#player",
  autoPlay: false
});
</script>
```

**Comment by ewwink** [comment]
I think `Clappr.Events.PLAYER_ERROR` will not fired if the server return other than HTTP 200 status code because there is no exception handler (`xhr.onerror`) in `function loadInternal()` and the script will be halted.

is `_events2.default.ERROR` linked to `Clappr.Events.PLAYER_ERROR` ?

**Comment by ewwink** [comment]
found temporary solution

```
var retry = 1;
var player = new Clappr.Player({
  source: "http://example.com/bad.m3u8",
  parentId: "#player",
  autoPlay: false,

  hlsjsConfig: {
    xhrSetup: function(xhr, url) {
      xhr.onerror = function() {
        if(retry === 1) {
          retry++;
          console.log("error: do second try");
        }
        else {
          console.log("Playing failover");
          player.destroy();
          player = new Clappr.Player({
            source: "http://example.com/good.m3u8",
            parentId: "#player",
            autoPlay: true
          });
        }
      }
    }
  }

});
```

**Comment by leandromoreira** [comment]
@ewwink some of the network failures are not being handled correctly I already opened an issue on https://github.com/dailymotion/hls.js/issues/491

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/issues/1012

**Comment by ewwink** [comment]
OK thank you very much.
