### ISSUE TITLE
Unable to Play Video When Image/Logo Clicked

### ISSUE THREAD

**Issue by marcoczen** [clappr/clappr#1055]
Guys, I am new to clappr.

A. I am looking to have a mp4 video play when a logo is clicked in a jquery dialog box.

My code is as as follow;
`<div id="player">`
  `<a id="clapprplayer" style="display:block;width:470px;height:280px" ><img src="logo-video.png" /a> ` 

              <script>
               var player = new Clappr.Player({source:"<?php echo $moviesrc ?>", 
                  parentId: "#clapprplayer",
                  width: '470px',
                 height: '280px',
                  loop: true,
                  hideMediaControl: false
               });
            </script>

         </div>  `

This code is not working. What am i doing wrong ?  
![clappr](https://cloud.githubusercontent.com/assets/20210990/16462337/5e3a437c-3e63-11e6-9b7b-c84df443ea33.png)

B. Another issue is , when i put the path to the file directly into the source ( movie.mp4),
the video can play. But i add it in programmatically via php ( source:"<?php echo $moviesrc ?>")  - it says "Your Browser Dos Not Support Playback of this Video".

What am i doing wrong?

**Clappr Version**: 0.2.57
**OS**: OpenSuse 13.1
**Browser**:  Firefox 46.0.1

**Comment by leandromoreira** [comment]
> I am looking to have a mp4 video play when a logo is clicked in a jquery dialog box

I think you could just use a `poster` instead.

```html
<html>
  <head>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
  </head>
  <body>
    <div id="player"></div>
    <script>
      var player = new Clappr.Player({
            source: "<?php echo $moviesrc ?>", 
            parentId: "#player",
            poster: "/logo-video.png"
      });
    </script>
   </body>
</html>
```

The second error screen (`"Your browser does not support the playback of this video"`) usually happens when you pass a invalid `source`.

**Comment by marcoczen** [comment]
Thank you leandromoreira .

I try now with the poster option.
Also,

Can the source parameter below accept a php code,i.e. a dynamic source  ?

source: "<?php echo $moviesrc ?>",

**Comment by leandromoreira** [comment]
@marcoczen you can mount the way you want, I think the problem relies on your php rendering, what's the browser final code? can you open the page and copy and paste the final page (the one accessed through the page on browser).

**Comment by leandromoreira** [comment]
if your browser outputs this `source:"<?php echo $moviesrc ?>",` it'll never work, since it's not valid html or js!

**Comment by marcoczen** [comment]
Leandro,

This is the html code from Firefox -> View Page Source;


`div id="webplayers">`
        
```
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>   
 <div id="clapprplayer"></div>            
  <script>
    var player = new Clappr.Player({
     source:"http://testserver.testdomain.net:8008/show_video.php?file_id=20160625-001529-55692404", 
     parentId: "#clapprplayer",
     width: '470px',
     height: '280px',
     loop: true,
     poster: "images/logo-video3.png",
     hideMediaControl: false
    });
</script>    
```
</div>

**Comment by leandromoreira** [comment]
Clappr needs hints to know what playback it'll use, you either can pass a source with an extension (http://example.com/example.mp4...) or you can hint by providing an extra parameter [`mimeType`](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#add-mimetype-for-extension-less-url).

```javascript
    var player = new Clappr.Player({
     source:"http://testserver.testdomain.net:8008/show_video.php?file_id=20160625-001529-55692404", 
     mimeType: "video/mp4",
     parentId: "#clapprplayer",
     width: '470px',
     height: '280px',
     loop: true,
     poster: "images/logo-video3.png",
     hideMediaControl: false
    });
```

**Comment by marcoczen** [comment]
Holy crap that worked !!! There is no more that error message " "Your browser does not support the playback of this video" ..

**Comment by leandromoreira** [comment]
Great, can I close this one @marcoczen ?

**Comment by marcoczen** [comment]
Now, i can see the "images/logo-video3.png" with 3 dots in the centre.
And when i click that image, the clappr  player appears and the video can play.

![clappr3](https://cloud.githubusercontent.com/assets/20210990/16464360/67bacb0c-3e6c-11e6-937a-f57d2cbbcf7c.png)

**Comment by marcoczen** [comment]
The autoloop plays fine. Only when i fullscreen, the player disappears

**Comment by leandromoreira** [comment]
@marcoczen you can customize and [instrument the default player with some config options](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md), you can also check if any [external plugin](https://github.com/clappr/clappr/blob/master/doc/EXTERNAL_PLUGINS.md) servers to you also checks if you read the [troubleshooting](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md).

> The autoloop plays fine. Only when i fullscreen, the player disappears

This is (maybe) a [new issue](https://github.com/clappr/clappr/blob/master/doc/BEFORE_OPEN_AN_ISSUE.md), for that create a new issue with all the details but I refrain please read the [troubleshooting](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md) first.

**Comment by marcoczen** [comment]
Ok thanx a lot
