### ISSUE TITLE
Clicking FullScreen at bottom right of clappr player causes Video to DISAPPEAR but Audio  is still playing

### ISSUE THREAD

**Issue by marcoczen** [clappr/clappr#1056]
Guys,

1. Thanks to @leandromoreira i managed to get clappr playing on our web app.
2. The issue now is that as the video is playing , when we click the bottom right fullscreen button, the clappy player / video disappears but the audio is still playing. 
3. I have closed all my open windows to see if the clappy player had gone to any rear window but that is not the case.
4. I have taken 3 screenshots which i am attaching here that shows the before, during , post  stages.

before:
![clappr00](https://cloud.githubusercontent.com/assets/20210990/16466545/20e5128c-3e76-11e6-9652-37e803a4d98e.png)

during:

after i click full screen ( note the clapper player has disappeared ):

![clappr03](https://cloud.githubusercontent.com/assets/20210990/16466566/2d3d0558-3e76-11e6-94a4-c9a331c78229.png)

 I have enabled  Clappr.Log.setLevel(0) as below;

```
<script>
            Clappr.Log.setLevel(0);
            var player = new Clappr.Player({
              source:"<?php echo $clapprplayersrc ?>", 
              mimeType: "video/mp4",
              parentId: "#clapprplayer",
              width: '470px',
              height: '290px',
              loop: true,
              poster: "images/logo-video3.png",
              hideMediaControl: false
            });
          </script>
```

And this shows in Firebug ( [debug][t] 1:resize Object { width=874,  height=0} );

```
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:fullscreen MediaControl
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][Container] container:fullscreen Container
[debug][t] 1:resize Object { width=874,  height=0}
[debug][Container] container:stats:report Object { startupTime=0,  rebuffers=0,  rebufferingTime=0,  more...}
[debug][Container] container:stats:report Object { startupTime=0,  rebuffers=0,  rebufferingTime=0,  more...}
[debug][Container] container:stats:report Object { startupTime=0,  rebuffers=0,  rebufferingTime=0,  more...}

```

My system information;

**Browser**: Firefox v 46.0.1
**OS**: openSuse 13.1 
**Clappr Version**: 0.2.57 - must be latest , downloaded today
**Apache**:2.4x
**php**:5.4x

Expected behaviour - FullScreen when  i click the full screen button on the bottom right

Do i need to pass an additional parameter to enable full screen functionality ?
My current snippet is;

```
<div id="clapprplayer"></div>            
          <script>
            Clappr.Log.setLevel(0);
            var player = new Clappr.Player({
              source:"<?php echo $clapprplayersrc ?>", 
              mimeType: "video/mp4",
              parentId: "#clapprplayer",
              width: '470px',
              height: '290px',
              loop: true,
              poster: "images/logo-video3.png",
              hideMediaControl: false
            });
          </script>
```

**Comment by marcoczen** [comment]
Update: if you the http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 as source the problem still persists - i.e., click the full screen button, the video disappears but audio is till playing.

**Comment by leandromoreira** [comment]
@marcoczen I'm sorry but I could not reproduce this at our CDN http://cdn.clappr.io/?src=http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 I tested with Chrome Version 51.0.2704.106 and Firefox 47 both using MacOSX

**Comment by marcoczen** [comment]
Hi Leandro...

1. Browser     -> Desktop. The web app is for desktops primarily.
2. Access URL -> U mean if i can click on the link above ? Yes.
3. Any idea about  Firebug ( [debug][t] 1:resize Object { width=874, height=0} );

**Comment by leandromoreira** [comment]
> 1:resize Object { width=874, height=0} )

That's the problem when you resized for fullscreen you just set height to 0. 

> Access URL -> U mean if i can click on the link above ? Yes.

I can't reproduce that here.

**Comment by marcoczen** [comment]
So is there any css trick to override the height ? The video must still be playing bcos you can hear the audio...

**Comment by leandromoreira** [comment]
I really can't say to you, I mean when I go to http://cdn.clappr.io/?src=http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8  using firefox it works so I think it must be something on your code, maybe iframe issue (if you're using iframes) or even a css that doing that (by js)...

**Comment by marcoczen** [comment]
Leandro,

1. IFrames - Yes, iframes is being used.
2. CSS / JS - Is there anything i can do to ensure clappr css or js has the priority ?

**Comment by leandromoreira** [comment]
@marcoczen you might need to check the iframe fullscreen options and restrictions http://www.allowfullscreen.com/iframe there are tons of other options.

**Comment by marcoczen** [comment]
Leandro,

I clicked into the iframe (  on the jquery DialogBox ) and was able to get the player to go full screen ( not full fullscreen to the edge of the monitor )  but about an inch away ... So this confirms its an iframe problem ?

**Comment by leandromoreira** [comment]
@marcoczen I really don't know, this should work.
```html
<iframe allowfullscreen src="http://cdn.clappr.io">
</iframe>
```

**Comment by marcoczen** [comment]
Leandro ...

IT WORKED ....  Adding allowfullscreen to the iframe tag allowed the fullscreen to work properly ...

THANKS !!!! PLS ADD THE TAG "wontfix-butiwillstillgetittoworkfor you"

**Comment by marcoczen** [comment]
Is there a paypal account we can make a contribution too ?
:-)

**Comment by enbplas11** [comment]
I can do fullscreen on a iframe without using the tag allowfullscreen inside the iframe.

What I need is this:

<Iframe src = "http://cdn.clappr.io">
</ Iframe>

I'm using the version clappr-0.2.58

I need your help

**Comment by enbplas11** [comment]
I can do fullscreen on a iframe without using the tag allowfullscreen inside the iframe.

What I need is this:

`<Iframe src = "http://cdn.clappr.io">
</ Iframe>`

I'm using the version clappr-0.2.58

I need your help

**Comment by asheroto** [comment]
> ```
> allowfullscreen 
> ```

For some reason the clappy player controls for full screen do not show up in Firefox mobile unless you add this.  Thanks!
