### ISSUE TITLE
Getting buffer progress in chunks

### ISSUE THREAD

**Issue by tobiasandersen** [clappr/clappr#1065]
On the [hlsjs demo page](http://dailymotion.github.io/hls.js/demo/), buffering is shown in chunks, like this:
![buffer-progress](https://cloud.githubusercontent.com/assets/3599069/16589411/534891a2-42d3-11e6-923b-4e897ca85b58.png)
I want to implement this in clappr, but when looking at `player.progress ` I only get an object with: `{ start, current, total }`. I would expect an array, looking something like this: `[ { start, end}, { start, end }, ... ]`. Am I looking at the wrong place or is this not currently possible?

**Comment by towerz** [comment]
@tobiasandersen currently this is not possible, the progress event filters the buffer containing the current position.

I'll mark this as a enhancement, so we can think of a better way to provide these buffer positions.

**Comment by towerz** [comment]
@tobiasandersen 2f7fc506ea683b5d79ee23201561a5658597285d and 8648f25bffad2983fa62a4702b827d4943f7b9ac added a second parameter to HTML5 based-playbacks to include an array of these buffered segments.

You can now use do something like this:
```javascript
player.getCurrentPlayback().on(Clappr.Events.PLAYBACK_PROGRESS, function(progress, buffered) {
  // progress is the same object to keep compatibility: { start, current, total }
  // buffered is an array in the format: [{start, end}, {start, end}, ...]
}
```

**Comment by tobiasandersen** [comment]
Great, thank you!
