### ISSUE TITLE
How to use Multiple Plugins

### ISSUE THREAD

**Issue by Sarabveer** [clappr/clappr#1071]
**Browser**: Chrome/51.0.2704.103

**OS**: Windows 8.1 Pro x64

**Clappr Version**: 0.2.58

How do I use multiple plugins?

I currently have this:
```
plugins: [ChromecastPlugin, ClapprPIPPlugin],
```

But how can I add:
```
plugins: {
    'core': [LevelSelector]
}
```

There is nothing documented on using multiple plugins.

**Comment by leandromoreira** [comment]
@Sarabveer you can just add this new one to the list, we dropped the key array config to a simple array. aka.

```javascript
 [ChromecastPlugin, ClapprPIPPlugin, LevelSelector],
```

**Comment by Sarabveer** [comment]
hmm, doesnt seem to be working

**Comment by leandromoreira** [comment]
@Sarabveer it should be working, please let us know if there are errors/bugs though.

**Comment by Sarabveer** [comment]
For some reason, it stops the chromecast icon from showing, and the level selector never shows up. How can I enable debug mode on Clappr.

**Comment by leandromoreira** [comment]
@Sarabveer so LevelSelector is not working?

**Comment by Sarabveer** [comment]
Nope

**Comment by leandromoreira** [comment]
@Sarabveer doesn't the LevelSelector works with latest clappr?

**Comment by Sarabveer** [comment]
did for me me, even when i used cdn.clappr.io. Does it work on live HLS streams?

**Comment by leandromoreira** [comment]
it should!

**Comment by leandromoreira** [comment]
if that's the case open an issue on that plugin
