### ISSUE TITLE
Not work for googlevideo

### ISSUE THREAD

**Issue by giaule** [clappr/clappr#1074]
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<div id="film-player"></div>
    var playerElement = document.getElementById("film-player");
    var player = new Clappr.Player({
        source: "https://r6---sn-a5mlrn76.c.docs.google.com/videoplayback?requiressl=yes&id=a1f82da9e8bedfbb&itag=22&source=webdrive&ttl=transient&app=texmex&ip=118.69.189.130&ipbits=8&expire=1468313947&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,pl,requiressl,source,ttl&signature=764F967CA234BB42668637EA90A3D7DB4AC8F210.1FD6D08A489F840C013F199B308AB960130243BE&key=cms1&pl=21&redirect_counter=1&req_id=a40714e97662a3ee&cms_redirect=yes&mm=34&mn=sn-a5mlrn76&ms=ltu&mt=1468298343&mv=u&nh=IgpwcjAzLmhrZzAxKgkxMjcuMC4wLjE",

        width: '100%',
        height: '100%',
        autoSeekFromUrl: false,
        hideMediaControl: true,
        baseUrl: "/assets/plugins/clappr-master/dist",
        autoPlay: true,
        plugins: {
            playback: [Clappr.Flash]
        }
    });
    player.attachTo(playerElement)

Please help me

**Comment by leandromoreira** [comment]
Hi @giaule the source needs to be a valid video (being hls, mp4 among others) I tried to see the content of this video:

```bash
$ curl -vs https://r6---sn-a5mlrn76.c.docs.google.com/videoplayback\?requiressl\=yes\&id\=a1f82da9e8bedfbb\&itag\=22\&source\=webdrive\&ttl\=transient\&app\=texmex\&ip\=118.69.189.130\&ipbits\=8\&expire\=1468313947\&sparams\=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,pl,requiressl,source,ttl\&signature\=764F967CA234BB42668637EA90A3D7DB4AC8F210.1FD6D08A489F840C013F199B308AB960130243BE\&key\=cms1\&pl\=21\&redirect_counter\=1\&req_id\=a40714e97662a3ee\&cms_redirect\=yes\&mm\=34\&mn\=sn-a5mlrn76\&ms\=ltu\&mt\=1468298343\&mv\=u\&nh\=IgpwcjAzLmhrZzAxKgkxMjcuMC4wLjE > /dev/null
*   Trying 74.125.170.60...
* Connected to r6---sn-a5mlrn76.c.docs.google.com (74.125.170.60) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.c.docs.google.com
* Server certificate: Google Internet Authority G2
* Server certificate: GeoTrust Global CA
> GET /videoplayback?requiressl=yes&id=a1f82da9e8bedfbb&itag=22&source=webdrive&ttl=transient&app=texmex&ip=118.69.189.130&ipbits=8&expire=1468313947&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,pl,requiressl,source,ttl&signature=764F967CA234BB42668637EA90A3D7DB4AC8F210.1FD6D08A489F840C013F199B308AB960130243BE&key=cms1&pl=21&redirect_counter=1&req_id=a40714e97662a3ee&cms_redirect=yes&mm=34&mn=sn-a5mlrn76&ms=ltu&mt=1468298343&mv=u&nh=IgpwcjAzLmhrZzAxKgkxMjcuMC4wLjE HTTP/1.1
> Host: r6---sn-a5mlrn76.c.docs.google.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Last-Modified: Wed, 02 May 2007 10:26:10 GMT
< Content-Type: text/plain
< Content-Length: 0
< Connection: close
< X-Content-Type-Options: nosniff
< Date: Tue, 12 Jul 2016 13:19:15 GMT
< Server: gvs 1.0
<
* Closing connection 0
```

And I couldn't because it seems to be protected, anyway if the video is a valid but doesn't have a extension you need to inform clappr what is this video by using `mimeType: 'videomimetype'`, please be aware that `'videomimetype'` needs to be a valid known mime type (like: `'video/mp4'`)

If you are trying to play youtube videos on clappr you should use the [youtube plugin.](https://github.com/towerz/clappr-youtube-playback/)

**Comment by giaule** [comment]
Thanks support,

Because link form google allow by IP address, then you can't access file.

I had fixed, add  mimeType: "video/mp4" this is work.

Thanks support.
