### ISSUE TITLE
How to set cookies

### ISSUE THREAD

**Issue by Kornflexx** [clappr/clappr#1075]
Hi :),

I need to pass jsessionid cookie in the headers of the request.

I tried that:

`hlsjsConfig: {
    xhrSetup: (xhr) => {
         xhr.withCredentials = true;
         xhr.setRequestHeader('Cookie', "JSESSIONID=" + jsessionid);
    }
}`

But it doesn't work : 
> Refused to set unsafe header "Cookie" 

How can I perform this operation properly ?

**Comment by leandromoreira** [comment]
Hi @Kornflexx I think you can try to set the cookie (a special header) 👍 

```javascript
document.cookie = "JSESSIONID=" + jsessionid;
```

source: [mozilla cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)

**Comment by Kornflexx** [comment]
It doesn't seems to work :(.
I use clappr in a desktop web app (with electron: chrome engine embed)

**Comment by leandromoreira** [comment]
@Kornflexx maybe you need to figure out a way to set cookie within this electron engine. (how to send cookies, persist..)

**Comment by leandromoreira** [comment]
@Kornflexx  this might help you https://github.com/electron/electron/blob/master/docs/api/session.md

**Comment by Kornflexx** [comment]
Ok I used that: https://www.npmjs.com/package/electron-cookies
When I print document.cookie jsessionid is in it. But I still have the same issue (401 unauthorized from distant api).

**Comment by ewwink** [comment]
you can't send cookie header with xhr also electron run on `file:///` or `localhost` and you can only set cookie on the same domain,
