### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Kornflexx** [clappr/clappr#1087]
**Browser**: Electron, Chromium engine

**OS**: Windows 7

**Clappr Version**: 0.2.25

Hello again,

First at all : thank you for your work, really :+1: 

So I have have an annoying issue : when I stream a video (hls) few seconds later it's stop and the console give me an error: 

`Uncaught RangeError: Maximum call stack size exceeded`

The error message can show itself few seconds before the video stop. I run my app with webpack (1.13.1). 

Here is my use of clappr:

```
var options = {
        source: videoUrl,
        parentId: "#player",
        height: (containerWidth * (1/this.ratio)) + "px",
        width: "100%",
        hlsjsConfig: {
             xhrSetup: (xhr) => {
                   xhr.withCredentials = true;
             }
        }
};
this._player = new Clappr.Player(options);
```

I have'nt recursive call in my code.

Do you have any idea to fix that ?

**Comment by leandromoreira** [comment]
@Kornflexx does the log points to where this happened?

**Comment by Kornflexx** [comment]
The code is minified :/, it's point here : 

```
       {
            key: "readBits",
            value: function(t) {
                var e = Math.min(this.bitsAvailable, t)
                  , n = this.word >>> 32 - e;
                return t > 32 && o.logger.error("Cannot read more than 32 bits at a time"),
                this.bitsAvailable -= e,
                this.bitsAvailable > 0 ? this.word <<= e : this.bytesAvailable > 0 && this.loadWord(),
                e = t - e,
                e > 0 ? n << e | this.readBits(e) : n
            }
        },
```
