### ISSUE TITLE
Prevent player-poster from showing when Clappr.Events.PLAYBACK_ENDED

### ISSUE THREAD

**Issue by iongion** [clappr/clappr#1089]
Current behavior is that when `Clappr.Events.PLAYBACK_ENDED` happens, then this view replaces the video that was played:

![image](https://cloud.githubusercontent.com/assets/867609/16984540/e057ffee-4e7a-11e6-9791-45000a21fe72.png)

How can the player be told not to do this and just stay on the last frame ?

I have tried this:
```
          player.listenTo(
            playback,
            Clappr.Events.PLAYBACK_ENDED,
            () => {
              const poster = player.getPlugin('poster');
              poster.showPlayButton(false);
            }
          );
```

But nothing happens, the poster does not get removed.

**Comment by towerz** [comment]
@iongion currently there's no way to inform the poster to not show on video end.

I'm considering this an enhancement request so we can support this behavior.

**Comment by towerz** [comment]
@iongion I made a small change to the poster plugin to allow disabling this behavior, but only for video end.

You just have to add the following when embedding the player:
```javascript
new Clappr.Player({
  poster: {
    url: 'http://some.url/for/poster',
    showOnVideoEnd: false
  }
})
```
The default behavior when the flag is not set is to show the poster screen after the video end. Notice that the poster option can either be the poster url or an object with the url and other options.
