### ISSUE TITLE
RTMP is not supported by firefox

### ISSUE THREAD

**Issue by sarat1669** [clappr/clappr#1100]
**Browser**: Firefox Version 47.0

**OS**: Ubuntu 16.04

**Clappr Version**: 0.2.47

`<head>`
  `<script type="text/javascript" src="http://cdn.clappr.io/0.2.47/clappr.min.js"></script>`
  `<script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js"></script>`
`</head>`

`<body>`
`  <div id="player"></div>`
`  <script>`
`    var player = new Clappr.Player({`
`    	source: "XXXXXXX",`
`    	parentId: "#player",`
`    	autoPlay: true`
`    });`
`  </script>`
`</body>`

Removed the source intentionally. 

RTMP is working fine on chrome but not working on firefox. Which versions of clappr and rtmp support both firefox and chrome?
![clappr](https://cloud.githubusercontent.com/assets/11179580/17245446/23c3d2c8-55a4-11e6-9163-9bb1d366adc6.png)

**Comment by leandromoreira** [comment]
The error you're seeing is very often related to the lack of flash installed, @sarat1669 can you see the flash animation in this page http://www.adobe.com/software/flash/about/ while using FF47? 

Also, did you notice any error on console? last but least if this bug is confirmed it should be open at its original repo https://github.com/flavioribeiro/clappr-rtmp-plugin

**Comment by sarat1669** [comment]
Installing flash solved the issue. Thank you. I need some info. I am porting an application from hls.js to Clappr as I need to use rtmp streams along with hls. I used the following in my application
hls.abrController.lastfetchduration
hls.abrController.lastbw
Hls.Events.FRAG_CHANGED
Hls.Events.FRAG_LOADED
Hls.Events.ERROR
How can i access these through Clappr?

**Comment by leandromoreira** [comment]
Yes @sarat1669 although this is more of a work around,

```javascript
player.core.getCurrentContainer().getCurrentPlayback()._hls.on(HLSJS.Events.LEVEL_LOADED, (evt, data) => this._updatePlaybackType(evt, data))
```

**Comment by funkytaco** [comment]
So will Clappr always require Flash? Flash support is going away in most browsers...

**Comment by kslimani** [comment]
@funkytaco : Clappr does not require Flash by default. It is only required if you intend to use [RTMP external plugin](https://github.com/flavioribeiro/clappr-rtmp-plugin) in order to play a RTMP source.

**Comment by funkytaco** [comment]
Ah ok, thanks. I've noticed VXG player works without flash, but they use a Chrome plugin. 

https://github.com/videoexpertsgroup
https://www.videoexpertsgroup.com/chrome-media-player-plug-in/

Is there any way to do this with Clappr?

**Comment by leandromoreira** [comment]
Maybe if we use a library / playback that provides that !


http://blog.videojs.com/Video-js-4-2-0-released-RTMP-CSS-designer-and-stability/


https://github.com/yurydelendik/rtmp.js

**Comment by funkytaco** [comment]
Okay, thank you. I guess I will wait and see if RTMP will work without flash someday!
