### ISSUE TITLE
html5 playback complete stop

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1103]
Hello,

While playing HLS in Safari or other html5-playback devices I see that native method pause() is used to stop playing but native player is still downloading fragments and performing requests for the playlist while even changing tabs in browser. In some cases it is important to completely stop playing and solution is suggested on https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML5_audio_and_video

It may be worth to consider this option to complete stop of playing or clappr option for that?

Currently I can implement this with that snippet of code on stop player event:

```
if(player.core.getCurrentPlayback().name == 'html5_video') {
    var el = player.core.getCurrentPlayback().el;
    var sources = el.getElementsByTagName('source');
    console.log(sources.length);
    el.removeAttribute("src");
    for (var i=0; i<sources.length; i++) {
        sources[i].removeAttribute("src");
    }
    el.load();
};
```

**Comment by towerz** [comment]
Thanks for reporting, @waster. There are some concerns about removing the playback source on stop, since it's not reloaded on each play, but only on setup. This way the playback would need to reload the source if `play` is called again.

I'll check if there's a way to do that in a way that works correctly with the playback. I'll keep you posted on this.

**Comment by waster** [comment]
@towerz, great, it will be very useful. In our case we simply run stop->load->play sequence on each play action so I guess it's safe to remove playback src.

**Comment by kslimani** [comment]
Maybe add also a check on the mime/file type and apply only this behaviour for .m3u8 playlist and leave default behaviour for .mp4 "vod' files, etc.. ?
