### ISSUE TITLE
clappr doesn't set type attribute for source tag with mimeType specified in safari

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1104]
**Browser**: Safari 9.1.2
**OS**: OS X Yosemite 10.10.5
**Clappr Version**: cdn.clappr.io

**Steps to reproduce**:

* Run this code on cdn.clappr.io:
```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  height: 360,
  width: 640,
  audioOnly: true,
  playbackConfig: {
    crossorigin: 'use-credentials'
  }
});

player.attachTo(playerElement);
player.load({source: 'http://a.radio7.ru/getAudioStream?pp=cl&ps=chw&p2=il&pr=etqlqnx', mimeType: 'application/x-mpegURL'});
player.play();
```
* Expected `type="application/x-mpegURL"` for `<source>` tag in html5 playback generated player but it has `type="video/mp4"`.

Is it normal behavior?

With regards, Andrey.

**Comment by towerz** [comment]
@waster it's a bug indeed. I've already confirmed the problem. Thanks for reporting.
