### ISSUE TITLE
clappr with flashls playback does not start to play from js

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1105]
**Browser**: IE 11.0.9600.17105
**OS**: Windows 7
**Clappr Version**: cdn.clappr.io

**Steps to reproduce**:
- Run this code on cdn.clappr.io:

```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  height: 360,
  width: 640,
  audioOnly: true,
  flushLiveURLCache: true,
  hlsjsConfig: {
    xhrSetup: function(xhr, url) {
      xhr.withCredentials = true;
    }
    },
  playbackConfig: {
    crossorigin: 'use-credentials'
  }
});

player.attachTo(playerElement);
player.load({source: 'http://hls.02.ep.emgsound.ru/11/playlist.m3u8', mimeType: 'application/x-mpegURL'});
player.play();
```
- Expected start playing but it's not. I also noticed that if I enable always request from server option in developer network console then everything start playing because of 200 responses. But without this option with default browser cache enabled player stopped with 304 reponse on `http://cdn.clappr.io/latest/809981e5b09d5336c45d72d0869ada2a.swf?inline=1`

[This](http://www.flashls.org/latest/examples/chromeless/?src=http%3A%2F%2Fhls.02.ep.emgsound.ru%2F11%2Fplaylist.m3u8) link is playing well after click on "Load". 

With regards, Andrey.

**Comment by towerz** [comment]
@waster there seems to be an error on your source playlist. The 128kbps playlist is always empty:
```
curl 'http://hls.02.ep.emgsound.ru/11/playlist.m3u8'
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=128000,CODECS="mp4a.40.2"
http://hls.02.ep.emgsound.ru/11/128/playlist.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=64000,CODECS="mp4a.40.2"
http://hls.02.ep.emgsound.ru/11/64/playlist.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=32000,CODECS="mp4a.40.2"
http://hls.02.ep.emgsound.ru/11/32/playlist.m3u8
```
```
curl 'http://hls.02.ep.emgsound.ru/11/128/playlist.m3u8'
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3

```
The lower bitrate playlists are ok:
```
curl 'http://hls.02.ep.emgsound.ru/11/64/playlist.m3u8'
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:6928
#EXTINF:1.996911,
out6928.ts
#EXTINF:1.996922,
out6929.ts
#EXTINF:1.996911,
out6930.ts
#EXTINF:1.996922,
out6931.ts

```
Clappr preconfigures both hls.js and FlasHLS to autoselect the starting level. I believe the default is to use the first level listed on the master playlist. Since the first level playlist is empty, an error occurs and it's returned to Clappr as unrecoverable. That's why the player bails out. Perhaps there should be a default error screen to avoid staying in this broken state.

You can change this behavior by setting it to start from lowest level, using `startFromLevel: 0` for FlasHLS. Our hls.js implementation is missing this setting, but I'll add an enhancement issue to implement this for our next release.

Anyway, I think you should check why your highe

**Comment by waster** [comment]
@towerz  Hello, sorry for incorrect playlist. It's broken for now. Please try http://hls.01.radio7.emgsound.ru/13/playlist.m3u8

**Comment by leandromoreira** [comment]
@waster did you try to follow [the common steps to verify issues](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues)? If yes, post the details about the suggested tests.

**Comment by leandromoreira** [comment]
@waster I ran a very simple test against your stream and it failed: `

```
$ python hls-analyzer.py http://hls.01.radio7.emgsound.ru/13/playlist.m3u8
Master playlist. List of variants:
	Playlist: http://hls.01.radio7.emgsound.ru/13/128/playlist.m3u8, bw: 128
	Playlist: http://hls.01.radio7.emgsound.ru/13/64/playlist.m3u8, bw: 64
	Playlist: http://hls.01.radio7.emgsound.ru/13/32/playlist.m3u8, bw: 32

***** Analyzing variant (128) *****

	** Generic information **
	Version: 3
	Start Media sequence: 355
	Is Live: True
	Encrypted: False
	Number of segments: 6
	Downloading http://hls.01.radio7.emgsound.ru/13/128/out358.ts, Range: None
Traceback (most recent call last):
  File "hls-analyzer.py", line 155, in <module>
    analyze_variant(m3u8.load(playlist.absolute_uri), playlist.stream_info.bandwidth)
  File "hls-analyzer.py", line 56, in analyze_variant
    analyze_segment(variant.segments[i], i == start)
  File "hls-analyzer.py", line 116, in analyze_segment
    ts_parser.prepare()
  File "/Users/leandro.moreira/pp/hls-analyzer/ts_segment.py", line 33, in prepare
    self._readHeader()
  File "/Users/leandro.moreira/pp/hls-analyzer/ts_segment.py", line 97, in _readHeader
    self._processTSPacket(packet)
  File "/Users/leandro.moreira/pp/hls-analyzer/ts_segment.py", line 130, in _**processTSPacket
    track = self.tracks[pid]**
KeyError: 17
```

**Comment by leandromoreira** [comment]
@waster it seems that your **BANDWIDTH** is being wrongly informed,  the value is a decimal-integer of bits per second. (source: https://tools.ietf.org/html/draft-pantos-http-live-streaming-19)

```
   Its format is:

   #EXT-X-STREAM-INF:<attribute-list>
   <URI>

   The following attributes are defined:

      BANDWIDTH

      The value is a decimal-integer of bits per second.  It represents
      the peak segment bit rate of the Variant Stream.
```

**Comment by waster** [comment]
@leandromoreira sure I tried. Thanks for the bandwidth information we fill fix that. But for the `http://hls.01.radio7.emgsound.ru/13/128/playlist.m3u8` link it's failed too(may be because it's audio only) but I'm pretty sure this playlist is fine. Please correct me if I'm wrong:
```
$ curl http://hls.01.radio7.emgsound.ru/13/128/playlist.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:501
#EXTINF:4.992289,
out501.ts
#EXTINF:5.015511,
out502.ts
#EXTINF:4.992289,
out503.ts
#EXTINF:4.992289,
out504.ts
#EXTINF:5.015511,
out505.ts
#EXTINF:4.992289,
out506.ts
```

Here are results of the tests in **IE11** for that link.
* cdn.clappr.io

Please try this code to test:
```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  height: 360,
  width: 640,
  audioOnly: true,
  flushLiveURLCache: true,
  hlsjsConfig: {
    xhrSetup: function(xhr, url) {
      xhr.withCredentials = true;
    }
    },
  playbackConfig: {
    crossorigin: 'use-credentials'
  }
});

player.attachTo(playerElement);
player.stop();
player.load({source: 'http://hls.01.radio7.emgsound.ru/13/128/playlist.m3u8', mimeType: 'application/x-mpegURL'});
player.play();
```
Play failed by clicking "Run" one or more times (depends on if flashls swf is in browser cache).


* cors headers are fine:

```
Cache-Control	no-cache
Connection	keep-alive
Content-Encoding	gzip
Content-Type	application/vnd.apple.mpegurl
Date	Sun, 07 Aug 2016 17:11:30 GMT
Etag	W/"57a76bbe-f3"
Expires	Sun, 07 Aug 2016 17:11:29 GMT
Last-Modified	Sun, 07 Aug 2016 17:11:26 GMT
Server	nginx/1.10.0
Transfer-Encoding	chunked
access-control-allow-cred...	true
access-control-allow-orig...	http://cdn.clappr.io
access-control-expose-hea...	X-Current-Location
```
* hls.js demo page plays [this](http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2Fhls.01.radio7.emgsound.ru%2F13%2F128%2Fplaylist.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&levelCapping=-1&defaultAudioCodec=undefined) link fine in non IE11 browsers.

* flashls demo page plays [this](http://www.flashls.org/latest/examples/chromeless/?src=http%3A%2F%2Fhls.01.radio7.emgsound.ru%2F13%2F128%2Fplaylist.m3u8) link fine after clicking 'Load'

**Comment by leandromoreira** [comment]
@waster yes, it works if you try to play this source: `http://hls.01.radio7.emgsound.ru/13/128/playlist.m3u8` at cdn.clappr.io it'll work! I just tested.

**Comment by waster** [comment]
@leandromoreira correct, it works with clappr with hls.js playback, and on flashls test page. But it doesn't play on cdn.clappr.io with IE11 **if flashls swf is in browser cache already**. Waiting for your test results on IE11 if it's possible.

**Comment by towerz** [comment]
@waster perhaps you should only call play when the player is ready (listening to the `PLAYER_READY` event) or enabling `autoPlay`:
```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  height: 360,
  width: 640,
  audioOnly: true,
  autoPlay: true, // this will enable autoplay for all playbacks
  flushLiveURLCache: true,
  hlsjsConfig: {
    xhrSetup: function(xhr, url) {
      xhr.withCredentials = true;
    }
    },
  playbackConfig: {
    crossorigin: 'use-credentials'
  }
});

player.attachTo(playerElement);
player.stop();
player.load({source: 'http://hls.01.radio7.emgsound.ru/13/128/playlist.m3u8', mimeType: 'application/x-mpegURL'});
```
I tested this on a Windows 10 machine using either Edge and IE 11. This solution should work for both hls.js and FlasHLS playbacks.

**Comment by waster** [comment]
@towerz ah, I see, but what about calling load() and play() methods on click events? Should I bind  to click events then only after player was ready? For example: 
```
player = new Clappr.Player({
...
     events: {
          onReady: setupClickEvents;
     }
});
var setupClickEvents = function() {
    $('td.controls button.play').click(function(event) {
           this.player.play();
    });
...
}
```

**Comment by towerz** [comment]
@waster there's no problem with calling `load()` and `play()` on click events. The problem is that `load()` is an asynchronous operation, and if `autoPlay` is not set, calling `play` will only work when the player is ready. This event actually means that the playback was already configured and is ready to receive commands, like `play`.

If you are reusing the player, you have to be aware of this behavior. The snippet you posted is ok, but you should be aware that if you call `load`, the play click handler will only work when the player is ready.

Usually on Clappr the load times are very quick, lower than 100 ms, so you shouldn't worry about that, because it's unlikely that the user clicks the play button within this interval. Obviously this interval depends on how long the player will take to load its components and download other files like swf modules, etc. Just be aware of that when enabling/disabling the click handler and you should be ok.

A safer approach to your setup would be something like that:
```javascript
var player = new Clappr.Player({
  // ...
  events: {
    onReady: setupClickEvents
  }
});
var setupClickEvents = function() {
  $('td.controls button.play').click(function(event) {
    var playback = player.core.getCurrentPlayback()
    if (playback.isReady) {
      player.play()
    } else {
      playback.once(Clappr.Events.PLAYBACK_READY, function() {player.play() })
    }
  });
// ...
}
```
This way whenever an interaction occurs, it will either call `play()` immediately (if the player is ready) or wait for the playback to become ready.

We are reviewing the player states to be clearer regarding to how the player works when its methods are called.

**Comment by waster** [comment]
@towerz thanks for the suggested snippet, then where in `setupClickEvents` or other place should I place `load()` method to be sure that play will start only after load with flashls?

**Comment by waster** [comment]
So the main question how to correctly run load and play hls source on click event to avoid "race conditions" that can be reached as I understand on slow bandwidth and with flashls playback also?

**Comment by waster** [comment]
I also created [this](http://audioplayer.df6.ru/audio/testie.html) page to test. Is it a right way to run `load()` before `if (playback.isReady)` in your snippet?

**Comment by towerz** [comment]
@waster the way you implemented on the test page is right, but if you are always calling `load()` when the user clicks on the play button, why don't you embed the player with `autoPlay` set to `true`? There's no need to handle state this way, and the player would work as you expect.

About the `onReady` event, it seems you found a bug there. I'll check this out, thanks!

**Comment by waster** [comment]
@towerz thanks, It's very good hint to use autoplay, I'll check that. So I need to call load() method only on click event in this way. 
I'm curious, will it work for html5 playback on iPhone and other Apple-devices and if we clear `src` attributes as mentioned [here](https://github.com/clappr/clappr/issues/1103#issue-169017139) .

**Comment by towerz** [comment]
@waster technically it should work, since the call to load/play is being done inside an user interaction handler.

We are working on a way to minimize this issue, requiring only the first play to be called from within an interaction event handler.

**Comment by waster** [comment]
hm, I edited the test page as you suggested with `autoPlay: true` and `load()` by click and it seems that it does not work in FF.

**Comment by waster** [comment]
Also I checked test page above in quite old IE11 (11.0.9600.17105) and it does not work also. I see in the console: "flashready trigger - TypeError: Error #1009"

**Comment by waster** [comment]
It seems that even in that way something like race condition occurs because player starts to play in some moments, and failed sometimes on IE with "flashready trigger - TypeError: Error #1009". Please help to solve this issue.

**Comment by nesale** [comment]
Also in IE11, I get the same "error on event c10:flashready trigger - TypeError: Error #1009"

**Comment by towerz** [comment]
@waster @nesale this error #1009 is triggered from Flash itself. This error code is related to neither Clappr nor FlasHLS. This only means that there's a null reference error occurring within FlasHLS, but I can't reproduce on any of my test systems.

What Windows version are you using? Have you checked if Flash is up to date on your test setup?

**Comment by nesale** [comment]
@towerz Windows 7 Pro SP1, Flash 22.0.0.210,  IE 11.0.9600.18376
Provide access to the computer via teamviewer where the error persists.

**Comment by waster** [comment]
Here are screenshots with two errors and versions of IE and Adobe Flash:

![Error1009](http://i68.tinypic.com/29dh4x1.png)
![MaxReached](http://i67.tinypic.com/99dxdl.png)
![Versions](http://i65.tinypic.com/icp7o0.png)

#1009 error is seldom but sometimes even persist in FF if flashls playback is forced.

**Comment by waster** [comment]
@towerz Any news on this? Unfortunately, this issue stopped us to use clappr in the production mode and we have to embed flashls directly for IE11.

**Comment by towerz** [comment]
@waster I had no progress with this error yet. I could reproduce the error using a virtual machine from Microsoft with this version of IE on Win7. I still couldn't determine why sometimes the playback report as ready, while the javascript bridge to FlasHLS is absent.

I'm still trying to come with a workaround for IE11, but with no success yet.

**Comment by waster** [comment]
@towerz agree, and it's interesting that this problem can be reproduced also on different versions of IE11 and win7/win10.

**Comment by eeggenberger** [comment]
I think we're experiencing the same problem with the FlasHLS fallback on IE11 under Win7. Autoplay works, but as soon as we call `load()` from our code, the playback won't start in IE11, neither with autoplay enabled, nor by calling `play()`. The strange thing is, that as soon as I open the Developer Tools, everything works as expected.

I've setup this page as an example:
http://clappr.devel.techcast.com/index.html
If I open this page in the IE11 Win7 VM from modern.ie, the PLAYBACK_READY event is never fired (except for some very rare cases). With the Developer Tools active, the event is fired every time, and the playback starts as expected.

Pure autoplay works (http://clappr.devel.techcast.com/autoplay.html), but it stops working as soon as a call to `load()` is involved (http://clappr.devel.techcast.com/load.html).

We need to use `load()` as we're using Clappr for live streaming, and we have to play an intro video as long as the live stream isn't available. As soon as the live stream is available, we want to switch to it using `load()`. The only workaround I can currently think of, is to destroy the player and create a new instance with autoplay enabled. Not pretty, but might solve the problem for me.

**Comment by waster** [comment]
Yes, still the same problem and it prevents us to use clappr flashls playback in production and we have to inject flashls directly via <object> and it's really weird. My opinion is that this is a major bug that makes impossible to use clappr with flashls playback.

**Comment by kafeltz** [comment]
hey @eeggenberger @waster I have run your examples from `http://clappr.devel.techcast.com/index.html` and I could reproduce the problem. But to fix it is very simple.

I have removed the line:
`player.load({source: playlist, mimeType: 'application/x-mpegURL'});`
Because you have already set it in the config:

```
var settings = {
    source: playlist,  <------- HERE
    parentId: "#clappr_container",
    width: '100%',
    height: '100%',
    autoPlay: false,
    plugins: [Clappr.FlasHLS],
    //loop: true,
    disableVideoTagContextMenu: false,
};
```

I think there is an issue by init the **source** by init and the next line re-init it by **load** method.

Could you try it?

**Comment by eeggenberger** [comment]
@kafeltz, the call to `load()` causes the player to break, so of course removing it seems to resolve the problem, but it's still not possible to change the player's source once it has been initialized.

**Comment by eeggenberger** [comment]
I've passed `load()` an object because it was done this way in the examples above. I've changed that now, but the result is still the same. `load()` doesn't work in IE11 on Win7, unless you open the developer tools window. Then it suddenly works, which makes it hard to debug the problem.

**Comment by kafeltz** [comment]
I could not simulate the part "open developer tools and it works" for me, it continues not working even with opening dev tool.

I still think you cannot pass sources after you have already passed one.

**Comment by eeggenberger** [comment]
We're now working around this problem by destroying the player with `destroy()` and creating a new one in IE on Win7, and thus avoid using `load()`.

**Comment by waster** [comment]
@towerz, @leandromoreira can you please check that issue again? I guess it seems to work by destroying and recreating player after each start/stop, but in our case it can not be used because we have VAST plugin and need to load original src and play again after VAST preroll. We're also tried to investigate this issue but it's hard to debug because flashls playback works well with IE developer tools opened. Also I noticed that playback is not working if swf request (for flash playback) returns 304 cached response, can it be related?

**Comment by leandromoreira** [comment]
@waster is this related solely to flashls?

**Comment by waster** [comment]
@leandromoreira yes, the problem is related to flashls playback in IE only.

**Comment by kslimani** [comment]
@waster have you tried with autoplay to true as third argument in load() method ?

example :

```javascript
player.load('video.m3u8', null, true)
```

**Comment by waster** [comment]
@kslimani unfortunately it seems does not not work, for example we use this code in VAST plugin on ad ended:

```
this.listenToOnce(this.core.getCurrentPlayback(), Events.PLAYBACK_ENDED, () => {
...
   this.core.configure({autoPlay: true});
   this.core.load(this.originalSource);
}
```
And got this error on win10 in IE11:
```
INFO:_setupExternalCallers()...
INFO:_setupExternalCallers()
INFO:CromelessPlayer()
HLSEvents ready
_bootstrap
%c[error] color: #ff0000;font-weight: bold; font-size: 13px; error on event c16:flashready trigger - TypeError: Error #1009
```

**Comment by kslimani** [comment]
@waster this issue is quite old and therefore it is hard to track the current context.

Could you please close this issue and open a new one describing your current situation and problems ?
Also providing a test page or code sample to reproduce the issue may ease to help to fix your issue.

**Comment by waster** [comment]
Closed, new https://github.com/clappr/clappr/issues/1414 opened.
