### ISSUE TITLE
Add starting level parameter to HLS playback

### ISSUE THREAD

**Issue by towerz** [clappr/clappr#1107]
As reported on #1105, when the player loads a m3u8 playlist with the first listed level pointing to a broken/empty playlist, both hls.js and FlasHLS will bail out after reaching a maximum number of attempts.

When testing this behavior, I noticed we didn't add an option to set the starting level for the HLS playback. Since it's not listed on hls.js options, it cannot be set from `hlsjsConfig`, but instead (should be set directly on the hls instance)[https://github.com/dailymotion/hls.js/blob/master/API.md#hlsstartlevel].

We should normalize this into a `playback` option instead of adding it to `hlsjsConfig`, since it's not specific to hls.js and could be used for other playbacks, such as DASH implementations.

**Comment by waster** [comment]
It seems that sometimes flashls is also bailing out with max number of attemtps (e.g. in IE1) even if m3u8 is correct. I've noticed  that If "Always Refresh from Server" is turned off setting in Network tab of IE11 developer tools load() method works but in default mode with browser cache enabled `this.el.playerLoad` is always undefined.
