### ISSUE TITLE
HLS-AES, decryption Failed, Event/Notification

### ISSUE THREAD

**Issue by PreDeToR** [clappr/clappr#1120]
Hi Guys

Is there any way to pickup an event if fetching of the decryption key failed for any reason or if the decryption of the .ts file failed?

Regards

**Comment by leandromoreira** [comment]
@PreDeToR since we use hls.js I tell you to check if there is any integration about it. https://github.com/dailymotion/hls.js/blob/master/API.md

**Comment by leandromoreira** [comment]
@PreDeToR are you still facing this issue?

**Comment by PreDeToR** [comment]
@leandromoreira this is sorted now thanks
