### ISSUE TITLE
Encryption src flashls

### ISSUE THREAD

**Issue by enbplas11** [clappr/clappr#1125]
Hi @tjenkinson, @leandromoreira, @towerz , I have implemented a solution for encrypting the src and decrypts flashls is who I am using com.hurlant.CryptoCode, but the hacker broke my solution, Any solution that they can tell me?

Sample: http://www.ponlatv.com/player_clappr_encri_src.php
Source encryption: https://github.com/norman784/wsd-as3/blob/master/com/hurlant/crypto/CryptoCode.as

**Comment by kslimani** [comment]
hi @enbplas11 you may want to look for an .swf file obfuscator/encryption software. It is really easy to decompile .swf files and extract AS3 source code from it. In my opinion, change the encryption algorithm will change nothing for the hacker. (and even with obfuscator/encryption, a determined hacker will broke it anyway).
