### ISSUE TITLE
Add event listener to appended element on Media Control

### ISSUE THREAD

**Issue by thalleshmm** [clappr/clappr#1137]
Hello, everyone.

I was writting this plugin, where I append an element to the Media Control. I added a click listener to the element, but it wouldn't fire.

I don't know if there's a div above the controls, or a _ponter-event: none_ on some of the parents. Anyways...

I could work a way around though, but it ain't pretty. I added a class to the element, then I listened to clicks anywhere on the player, and I check if the target of the click contains the class I put on it.

```javascript
// ...
          this.core.$el.on('click', this.onMediaControlButtonClick.bind(this));
}

onMediaControlButtonClick : function(mouseEvent) {
            if(!mouseEvent.target.classList.contains('media-control-subtitle-toggler'))
                return;
          // ... handle it here
/// ...
```

Is there an official way to add a listener to an appended element? Thank you

**Comment by towerz** [comment]
Hi @thalleshmm, I would recommend you to do something like we do on some control plugins like [clappr-chromecast-plugin](https://github.com/clappr/clappr-chromecast-plugin). Just create a `UICorePlugin` with a click listener bound directly on its properties:
```javascript
class MyPlugin extends UICorePlugin {
  //...
  get events() {
    return {
      'click': 'click'
    }
  }
  function click() {
    // ... handle it here
  }
}
```
Please let me know if this works for you.

**Comment by thalleshmm** [comment]
Thank you @towerz. =)

It didn't work for me though. I'm not writing in ES2015. I must have done something wrong. It should be something like the code below, shouldn't it?

```javascript
Clappr.CorePlugin.extend({
        events :  {
            click : 'click',
        },
        click : function() {
            alert('yay, you clicked');
        },
})
```

**Comment by towerz** [comment]
@thalleshmm you can do the same without ES2015. The attribute notation is from ES5 standard. The code would look like this:
```javascript
Clappr.CorePlugin.extend({
  get events() {
    return { click: 'click' }
  },
  click: function() {
    alert('yay, you clicked!')
  }
})
```

**Comment by thalleshmm** [comment]
Didn't know the "get" thingy would work. Throught it was part of the ES2015 specs. I'll take a look at that and write u back. Thank you!
