### ISSUE TITLE
Problems with VOD m3u8 build on the fly

### ISSUE THREAD

**Issue by Al3x4nd3r** [clappr/clappr#1139]
Browser: Firefox 47.0
OS: Ubuntu 14.04.4 LTS
Clappr: 0.2.61

**Steps to reproduce**:
I am building a m3u8 playlist on the fly, so at the beginning of the transmission i don't have the complete playlist. To reduce the delay i send a incomplete VOD (#EXT-X-PLAYLIST-TYPE:VOD) playlist **without #EXT-X-ENDLIST** but the Clappr read this as a Live playlist and reconfigure to VOD when receive the complete playlist (with #EXT-X-ENDLIST). 

To reproduce, send a VOD playlist without #EXT-X-ENDLIST and after send the complementation playlist with #EXT-X-ENDLIST.
## I suggest to make two changes in the source code:

**file: src/playbacks/hls/hls.js line: 318**

change the method: 

```
 _updatePlaybackType(evt, data)
    this._playbackType = data.details.live ? Playback.LIVE : Playback.VOD
    this._fillLevels()
    this._onLevelUpdated(evt, data)
 }
```

to

```
 _updatePlaybackType(evt, data) {
     this._playbackType = (data.details.type === 'LIVE' ? Playback.LIVE : Playback.VOD)
     this._fillLevels()
     this._onLevelUpdated(evt, data)
 }
```

**file: node_modules/hls.js/lib/controller/stream-controller.js line: 788**

change the code 

```
// if live playlist, set start position to be fragment N-this.config.liveSyncDurationCount (usually 3)
if (newDetails.live) {
       var targetLatency = this.config.liveSyncDuration !== undefined ? this.config.liveSyncDuration : this.config.liveSyncDurationCount * newDetails.targetduration;
       this.startPosition = Math.max(0, sliding + duration - targetLatency);
} else {
         this.startPosition = 0;
}
```

to 

```
// if live playlist, set start position to be fragment N-this.config.liveSyncDurationCount (usually 3)
if (newDetails.type === 'LIVE') {
       var targetLatency = this.config.liveSyncDuration !== undefined ? this.config.liveSyncDuration : this.config.liveSyncDurationCount * newDetails.targetduration;
       this.startPosition = Math.max(0, sliding + duration - targetLatency);
} else {
         this.startPosition = 0;
}
```

**Comment by Al3x4nd3r** [comment]
_updatePlaybackType(evt, data) {
    this._playbackType = data.details.live ? Playback.LIVE : Playback.VOD
    this._fillLevels()
    this._onLevelUpdated(evt, data)
  }
```

**Comment by leandromoreira** [comment]
Thanks @Al3x4nd3r partially this can be done at Clappr but the last part should be done at https://github.com/dailymotion/hls.js

**Comment by Al3x4nd3r** [comment]
Thanks you, i open a issue at dailymotion for this: [https://github.com/dailymotion/hls.js/issues/668](https://github.com/dailymotion/hls.js/issues/668)

[]`s

**Comment by leandromoreira** [comment]
https://github.com/dailymotion/hls.js/issues/668
