### ISSUE TITLE
iOS 10 Problem

### ISSUE THREAD

**Issue by DKarakis** [clappr/clappr#1147]
**Browser**: Safari iOS

**OS**: iOS 10

**Clappr Version**: 0.2.63

**Steps to reproduce**:

* first step
```js
 var player = new Clappr.Player({
            source: "https://hls.***.com/ios/smil:live.smil/playlist.m3u8",
            parentId: "#player",
            autoPlay: true,
            width: '100%'
        });

```
* then second step
The system was working on iOS 9 perfectly but when I updated to iOS 10 it suddenly gives the error `No playable sources found`  and no error on the browser console.

Did you try to reproduce this issue at http://cdn.clappr.io/
I've tried on the cdn it worked perfectly.

![](http://i.imgur.com/sZZO45b.png)

**Comment by leandromoreira** [comment]
@DKarakis did you try to use http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 as `source` just to test?

**Comment by DKarakis** [comment]
@leandromoreira thank you for replying back. I solved the problem. It turned out to be I was failing while my security check. Nothing related with the product itself. Have a good day!
