### ISSUE TITLE
Write initial documentation

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#115]
We should describe how clappr is structured and how plugins works - showing the differences between container plugins, playback plugins and "global" ones.  Would be quite interesting to have at last one tutorial describing step-to-step how to write a mp3 player or a slideshow player.

We should also create a session like [nginx's 3rd party modules](http://wiki.nginx.org/3rdPartyModules) to store external modules like [bemtv p2phls plugin](https://github.com/bemtv/clappr-p2phls-plugin).

**Comment by chriswiggins** [comment]
What about something like an API.md document? To list all the javascript methods that can be called?

**Comment by thiagopnts** [comment]
This would be a great start @chriswiggins

**Comment by davidaurelio** [comment]
Hey there, I’d really like to use clappr and maybe contribute to development. Unfortunately, the lack of documentation makes everything beyond instantiating a player really hard and a guessing game.

Please invest some time to provide great documentation, that could really provide a kickstart for the project.

**Comment by thiagopnts** [comment]
@davidaurelio You're definitely right about this. I'll start to focus on this in the next days.

**Comment by bryfry** [comment]
+1

**Comment by tarkanlar** [comment]
+1

**Comment by snsxn** [comment]
+1

**Comment by deedos** [comment]
+1

**Comment by irongomme** [comment]
+1

**Comment by thiagopnts** [comment]
Following @chriswiggins idea, I started to draft an [API.md](https://github.com/clappr/clappr/blob/master/API.md) file. Feedbacks are welcome.

**Comment by leandromoreira** [comment]
We may use something similar to this http://leandromoreira.github.io/clappr-docs/classes/Player.html#method_constructor

**Comment by leandromoreira** [comment]
At Aug 9, 2014 @thiagopnts suggested yuidoc and we did it :facepunch: 

You already can [check the initial documentation](http://clappr.github.io/classes/Player.html), mostly covering the github's home page and thiago's API documentation.

We still need to better integrate this to our build but I think the first step was done. can we close this @flavioribeiro @thiagopnts @towerz @bernardocamilo @barbosa ?

**Comment by towerz** [comment]
Great job, @leandromoreira! :beers:

I'm ok with closing this one, now we can start moving towards tutorials and other kinds of documentation, as well as improving our test coverage.

**Comment by leandromoreira** [comment]
@chriswiggins @davidaurelio @bryfry @tarkanlar @snsxn @deedos @irongomme you can check the initial documentation at http://clappr.github.io/
