### ISSUE TITLE
Question: Is there a way to change audio pan?

### ISSUE THREAD

**Issue by NicholasAsimov** [clappr/clappr#1151]
Hello, I could find anything in the documentation so I decided to ask here. Is there a way to change between left and right audio channels in Clappr? By that I mean change audio pan so the left channel sounds in both ears, for example. I hope I made that clear.

Thanks in advance.

**Comment by leandromoreira** [comment]
@NicholasAsimov we don't have any official way of panning out the audio ( I saw that you can do that in [html5](http://stackoverflow.com/questions/20287890/audiocontext-panning-audio-of-playing-media) )

**Comment by NicholasAsimov** [comment]
Thanks, I will look into that.

**Comment by leandromoreira** [comment]
Feel free to do a PR 😄
