### ISSUE TITLE
Anyone had this before ERR_FILE_NOT_FOUND 38861cba61c66739c1452c3a71e39852.ttf

### ISSUE THREAD

**Issue by rootscript** [clappr/clappr#1153]
**Browser**: 
Chrome 53.0.2785.113
Node.js v6.5.0

**OS**:
Mac OS X 10.11.5

**Clappr Version**:
0.2.63

**Steps to reproduce**:
I'm using Electron 1.4.1, and installing clappr with `npm install clappr --save`.  
I'm using `var Clappr = require('clappr');` in my render.js

* first step
`npm start` to get `electron .` going,  but when I look at the console in Chrome devtools I see the `ERR_FILE_NOT_FOUND` regarding `38861cba61c66739c1452c3a71e39852.ttf`

Did you try to reproduce this issue at http://cdn.clappr.io/
No as I'm not src'ing the clappr.js, i'm installing with npm

`/38861cba61c66739c1452c3a71e39852.ttf:1 GET file:///38861cba61c66739c1452c3a71e39852.ttf net::ERR_FILE_NOT_FOUND`

**Comment by leandromoreira** [comment]
@rootscript try to instantiate it using: `baseUrl: 'http://cdn.clappr.io/latest'`

**Comment by rootscript** [comment]
@leandromoreira **Thank you**, that is correct & makes sense.

When using Clappr as a `node_module`, a user might expect that resource files like .ttf files would be **local**, and to be able to use Clappr in an **offline mode** (without errors).
Are there more resource files that a pulled from the net? or is this the only one?

Would be nice to have the option to `npm i clappr` with all resources local - Does that make sense to you?

**Comment by kslimani** [comment]
@rootscript if you are using node, the files you are looking for are in Clappr [dist](https://github.com/clappr/clappr/tree/master/dist) folder. You may have to copy theses "assets" files, for example, with your build script in your application bundle, and use the `baseUrl` Clappr property to point to correct folder. _(this property can be either an absolute or relative path/url)_.

**Comment by rootscript** [comment]
**@kslimani Thank you** - That makes sense  - Using **`baseUrl:`** with the files from  node_modules Clappr **dist**.  All seems quite obvious now, looking back :o)

**Comment by mohsinworld** [comment]
How to crack this website? bioscopelive.com

**Comment by banagale** [comment]
This stumped me for a bit. 

To fix this on create-react-app, just copy the `38861cba61c66739c1452c3a71e39852.ttf` file to the `/public/fonts` directory. Then make sure you set the `baseUrl:` option for clappr to the path of the deployed folder.

For example:

```
      let videoSrc = 'https://example.com/playlist.m3u8';
      let options = {
        baseUrl: '/staticfiles/frontend/compiled/fonts',
        source: videoSrc,
        parentId: '.player',
        height: '100%', width: '100%',
      };
      player = new Clappr.Player(options);
```

This seems to be the only odd-end for the npm use of clappr in create-react-app.  This has been set for some time, but I would recommend clappr's default configuration not require the use of this font, or to offer an option that makes the font automatically available to the web bundlind used by create-react-app.
