### ISSUE TITLE
Question : any reason there is no playback "seek" event ?

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr#1162]
As far i have dig in source code, the player seek event comes from container seek event which is trigger in container [seek()](https://github.com/clappr/clappr/blob/master/src/components/container/container.js#L302) method.

I am working on player event tracking plugins (Google Analytics, etc..) and this is problematic in some case, for example, iOS device in fullscreen where Clappr media controls cannot be rendered. (_seek event is never trigger_)

What about a `Events.PLAYBACK_SEEK` and a `Events.PLAYBACK_SEEKED` events ?

EDIT: by "problematic", i mean i can't rely on binding container events.

**Comment by joaopaulovieira** [comment]
I agree with you, @kslimani !
I will submit a pull request for that.
