### ISSUE TITLE
How to listen to the event when playback is triggered?

### ISSUE THREAD

**Issue by ibreakstuff93** [clappr/clappr#1166]
Could someone post an example of how to listen to the event which is when a user first clicks play or play() is called? Which is the best event to use for this, and how best to listen for it?

Thanks

**Comment by leandromoreira** [comment]
@ibreakstuff93 you can try to use [the event](https://github.com/clappr/clappr/blob/master/doc/API_EVENTS.md) at the constructor:

```javascript
var player = new Clappr.Player({
  // ... all the other configurations
  events: {
    onPlay: function() { console.log('it was played') } // Fired when player starts to play
  }
})
```

**Comment by ibreakstuff93** [comment]
Awesome @leandromoreira , and just to double check then, once video playback has begun, this sort of thing should be okay?


`player.listenTo(player, Clappr.Events.PLAYER_PLAY, function() { console.log("playing!") });`

**Comment by ibreakstuff93** [comment]
I think reading a little closer, to detect when a user presses the play button, or when player.play() is called, I need to use:

PLAYBACK_PLAY_INTENT

`player.on(Clappr.Events.PLAYBACK_PLAY_INTENT , function() { console.log("play initiated")});`

However, this isn't working for me in the 0.2.63 tag version?

Then, when video starts  playing, I can use:

PLAYER_PLAY

`player.listenTo(player, Clappr.Events.PLAYER_PLAY, function() { console.log("playing!") });`

which is currently working :) Could you tell me where i've gone wrong on the playback_play_intent?

**Comment by leandromoreira** [comment]
@ibreakstuff93 usually the [events](http://clappr.github.io/classes/Events.html) happens on the component they belong, for instance, `PLAYBACK_PLAY_INTENT` is fired on `playback` and when you're accessing the `player` instance you're not accessing the `playback`.

```javascript
player.core.getCurrentPlayback().on(Clappr.Events.PLAYBACK_PLAY_INTENT, function() { console.log('gangstar paradise') }

**Comment by ibreakstuff93** [comment]
@leandromoreira thank you! that's exactly what I was looking for and helps a lot!

:+1: and + :100: points for log message :-)
