### ISSUE TITLE
HLS stream becomes after while out of sync picture with sound.

### ISSUE THREAD

**Issue by PietroI** [clappr/clappr#1172]
**Browser**: Chrome 53.0.2785.143 (64-bit)

**OS**: OS X Sierra

This stream starts well synced but after 5-10 minutes becomes sound and picture out of sync.

Stream URL: http://86.110.233.68:1935/lifetv/lifetv.stream_360p/playlist.m3u8

issue reproduced at http://cdn.clappr.io/

**Comment by PietroI** [comment]
On the Safari it seems to be OK and probably it is some stream fault. Where can be a issue?

**Comment by leandromoreira** [comment]
@PietroI it can be in the stream (either the source of it or the hls itself), I'd recommend you to https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues

**Comment by Pmant** [comment]
Can confirm this. Jumping in the Timeline fixes it, so it's not a content error. However it's only ~0.5sec per 10 minutes video. Using Chrome 56 64bit Windows.

**Comment by leandromoreira** [comment]
@Pmant we're using clappr at production and we haven't noticed this. Can you test with this source http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 ?

**Comment by Pmant** [comment]
I couldn't notice any sync issues with your source, even so it's not easy to tell if there is 0.5s lag in this video. The source where I noticed it is a bit different since it is AES-128 encoded and and it is a single file using BYTERANGE requests.

```#EXTM3U
#EXT-X-VERSION:4
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:14
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="key.php"
#EXTINF:8.333333,
#EXT-X-BYTERANGE:609684@0
media.ts
#EXTINF:8.333333,
#EXT-X-BYTERANGE:406644@609696
media.ts
```

**Comment by leandromoreira** [comment]
@Pmant maybe it's something related this difference (`AES-128` and `byte-range`), can you try to do the same thing on this demo page http://dailymotion.github.io/hls.js/demo/ ?

**Comment by Pmant** [comment]
Yes it's definitly there with my source.

**Comment by leandromoreira** [comment]
@Pmant if you were able to reproduce this same issue at the hls.js demo we might need to open an issue there, @mangui might help us.
