### ISSUE TITLE
Question about Events

### ISSUE THREAD

**Issue by primoitt83** [clappr/clappr#1173]
Hello,

I'm trying to use PLAYER_PLAY and another event at same time.

Here's an example:

//1 - Player is playing
player1.on(Clappr.Events.PLAYER_PLAY, function() {    //GET teste.php  });

//2 - Monitoring if browser's tab was closed
window.addEventListener("beforeunload", function (e) {  //GET teste.php  }); 

Is it possible to put all together???

I need something like this:

If function 1 is running AND function 2 is active {  //GET teste.php  });

Thank you!!

     
_

**Comment by leandromoreira** [comment]
This plugin might help you https://github.com/leandromoreira/clappr-pause-tab-visibility/blob/master/index.js it pauses when user change tabs.

**Comment by primoitt83** [comment]
Amazing plugin @leandromoreira !!

Working perfectly on Firefox!!

Changing and closing tabs, even when closes all browser.

On Chrome is almost there. It doesn't detects when closes tab or browser.

**Comment by primoitt83** [comment]
hey @leandromoreira 

I found a limited solution for Chrome

Need a function for detect browser's name

      if (browserName=='Chrome'){
      	 window.onbeforeunload = function () {   
            /GET teste.php
         }
      }
But if the player is paused then tab closes, you will have two GET for same event. :(

You think is there a better solution?

**Comment by primoitt83** [comment]
Found a solution!!!

if (browserName=='Chrome'){
	
      	 window.onbeforeunload = function () {
      
	    if (player1.isPlaying()){

	    //GET teste.php

	    });
	    }
        }
      }

Working properly on Chrome now!!

**Comment by primoitt83** [comment]
hey @leandromoreira 

I have one last question about .isPlaying.

 This code works like a charm

 document.addEventListener('click', function () {
	  if (player1.isPlaying()){	    
		alert*(ok!!!);	    
	    }       
      });

Code below doesn't work

      if(window.performance.navigation.type  == 1){      
	  if (player1.isPlaying()){	    
		alert("ok!!!");
		console.log("ok!!!");   
        }
     }

Do i really need a function for is.Playing recogniser playing ??

Thanks again

**Comment by leandromoreira** [comment]
I'm afraid I didn't understand your question :( but you do need an instance of the player to check whether is playing or not.
