### ISSUE TITLE
Can not play HLS m3u8 from wowza media server

### ISSUE THREAD

**Issue by dinhkhaihtc** [clappr/clappr#1175]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 58.3.130, Firefox Version 3.5.6, IE 11)

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)

**Clappr Version**: 0.2.63

hello, I tried to experiment and it will not run. but with older versions 0.2.13 it runs smoothly (live stream hls with wowza media server from ipcamera). 
hope you can fix it.

**Comment by leandromoreira** [comment]
I'd tell you to try https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues
