### ISSUE TITLE
Is there are no way for display current viewers counter?

### ISSUE THREAD

**Issue by kgp700** [clappr/clappr#1248]
Hi.
Is there are no way for display current viewers counter?
That's useful for live streaming

**Comment by kslimani** [comment]
The player is not "aware" of current viewer count value, only the server is.

But if you have a "server-side" way to get this value, you can display it on player with a custom plugin.

**Comment by Niko78** [comment]
on my side I use wowza as streaming server and there is an url to get connections informations
I use the output to display value under the player with a refresh each 30 seconds
if a plugin existed to display it inside player (in the bar, on the left) that would be cool (with a personal refresh)

**Comment by kslimani** [comment]
Making a plugin doing this is very simple to accomplish.
For example, take a look at source code of [clappr-heading-plugin](https://github.com/la1tv/clappr-heading-plugin) : it is a very simple plugin which display video title over video.
Just use it as base skeleton, then : 
- adjust css to choose where you want to display user count
- add code to perform ajax request each N seconds to get data
- add a plugin option to configure ajax request interval in seconds
- add a plugin option to configure url where to perform ajax request
- add an optional plugin option to set a callback function which parse ajax request result and return text to display (or only user count)

There is probably more usefull options to add to plugin, but i think this yould be a good start 😄

**Comment by Niko78** [comment]
more this one : https://github.com/Metrakit/clappr-comment-plugin (to get info in seek bar)
but doesn't work for me
