### ISSUE TITLE
In fullscreen mode every rtmp streamed video looks a little bit pixelated

### ISSUE THREAD

**Issue by Aramblog** [clappr/clappr#1265]
Adobe Flash Player version: 24.0.0.186
OS: Windows 7 Professional 32 bit
Clappr version: 0.2.64 clappr.min.js
RTMP plugin date: Dec, 20, 2016, rtmp.min.js and RTMP.swf
My screen resolution: 1280x800
tested stream resolution: 640x360
I've also tested it at http://cdn.clappr.io/ and noticed the same pixelation effect
How to change this look to smooth in fullscreen mode? I've tested it on other players like Uppod, Strobe Media Playback and they enlarged rtmp streamed video smoothly (like a little bit blurry but without pixelation) in fullscreen mode. Thank you in advance.
CLAPPR DEMO
![demo](https://cloud.githubusercontent.com/assets/16438344/22193106/a6ccd0f4-e152-11e6-844b-91accf637dea.png)
STROBE MEDIA PLAYBACK DEMO
![strobe](https://cloud.githubusercontent.com/assets/16438344/22196336/44ef8930-e166-11e6-8343-817f8c854588.png)

**Comment by mangui** [comment]
you need to enable `video.smoothing = true` on `flash.media.Video` object

with OSMF, it needs to be enabled on

**Comment by flavioribeiro** [comment]
Thanks @Aramblog and @mangui. I thought we had smoothing `true` on `clappr-rtmp-plugin`. I'll close this one, let's address the progress on https://github.com/flavioribeiro/clappr-rtmp-plugin/issues/72.
