### ISSUE TITLE
How to link multi angle video/view multi angle video in Clappr video player

### ISSUE THREAD

**Issue by Night-Crawle** [clappr/clappr#1274]
Hi!,
I am very interesting with your plugin....I have tried to developed your plugin for multi angle view..
Do you have any idea..how it want to customize..html5 canvas/code..

**Sample demo**: http://tronevr.esy.es/final-preview/

Note: this is not Clappr player..But i want to customize, as this with your player...Can you help for that...
Thanks!
Dj

**Comment by leandromoreira** [comment]
Did you see this https://github.com/thiagopnts/clappr-video360/ ?

**Comment by Night-Crawle** [comment]
@leandromoreira ,
yes..I used..but not success yet... it stream source ,that used ,multiple camera...
I want make it as that player...
do you have suggestion,how i need to code?/ that.
also,post support question there:
link: https://github.com/thiagopnts/clappr-video360/issues/11
