### ISSUE TITLE
Clappr does not work (hls) on Opera 43, Midori 0.5.11 (Linux Mint Rosa)

### ISSUE THREAD

**Issue by fuzegit** [clappr/clappr#1279]
**Browser**: Opera 43, Midori 0.5.11

**OS**: Linux Mint Rosa

**Clappr Version**: 0.2.65

**Steps to reproduce**:

* init player from ajax page
* play any m3u8 file
* in console:

**Browser**: Opera 43
![02-08- _001](https://cloud.githubusercontent.com/assets/13233234/22756037/cf09d5d8-ee56-11e6-9aa6-9dde3d5f79f1.png)

**Debug in Opera 43**
![02-08- _003](https://cloud.githubusercontent.com/assets/13233234/22756697/fde40142-ee58-11e6-8d3b-afc0813c07f7.png)

**Browser**: Midori 0.5.11
![02-08- _002](https://cloud.githubusercontent.com/assets/13233234/22756036/cf0742b4-ee56-11e6-8022-a3c5479ed2f3.png)

**Comment by leandromoreira** [comment]
Did you follow the [common steps](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues) mostly did you try with a different video source like http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 ?

**Comment by fuzegit** [comment]
Yes, i tried different sources. Currently checked to mp4 files - is not working. And the browser console empty. This happens when a player start in the flash mode. In html5 mode, all works fine. And so it began after upgrading to Opera version 43.
Sorry for bad english :)

**Comment by leandromoreira** [comment]
@fuzegit okay, there was an issue where people were discussing about some problems with linux + some browsers, the problem though was mostly related to codec problems at browser. ;/

**Comment by leandromoreira** [comment]
I changed your title to say more specifically what the issue is about, do you agree?

**Comment by kslimani** [comment]
@fuzegit have you tried [this solution](http://forums.opera.com/discussion/1882370/opera-browser-does-not-play-twitter-videos-and-gifs-again#Item_17) ?

**Comment by fuzegit** [comment]
> I changed your title to say more specifically what the issue is about, do you agree?

Yes of course

> there was an issue where people were discussing some problems with Linux + some browsers, the problem though was mostly related to codec problems at the browser.

Yes, it codec problems at the browser. But player in flash mode not work. hls and mp4 too. 

> have you tried this solution ?
Not yet, but I'll try

@leandromoreira, @kslimani, thanks for answers.
