### ISSUE TITLE
width/height issue

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1281]
**Clappr Version**: https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

**Steps to reproduce**:

We try to configure the player with an auto size (auto or even %) but it doesn't work
it seems it works only with values in pixels

Most often players offer this possibility... is it cause we did it wrong ?
It misses ratio ?

 <script>
        var player = new Clappr.Player(
            {
                source: "xxxxxxx ",
                actualLiveTime: true,
                autoPlay: true,
                poster: 'yyyyyyy',
                parentId: "#player",
                width: '100%',
                height: 'auto'
...,

thanks

Nico

**Comment by kslimani** [comment]
That's right, Clappr default behaviour with width and height set to '100%' is to adjust size to parent container element. (AFAIK there is no auto-ratio feature yet)

As workaround, you should effectively set width and height to '100%' in player configuration and change size on parent container (for example using css media queries)

**Comment by brunjick** [comment]
Set `height` to `100%` and add event:
```js
```

**Comment by brunjick** [comment]
Set `height` to `100%` and add event:
```js
width: '400px', // anything you like
height: '100%',
events: {
  onReady: function () {
    const playerWidth = parseInt(this.playerInfo.computedSize.width)
    const parentElement = this.options.parentElement

    parentElement.style.height = (playerWidth * 0.5625) + 'px'
  }
}
```

**Comment by campones** [comment]
Hi

I have a similar issue. 
If I setup '100%' nothing appears. 
If I don't setup anything it put a value  like 
`<div data-player="" tabindex="9999" class="" style="width: 640px; height: 360px;">`
I do not know if this value is arbitrary or if this is the default size of the stream. 

example of my setup: 

```
<div id="video-container" class="video-container">
<script>
                        var player = new Clappr.Player({
                            plugins: [DashShakaPlayback],
                            autoPlay: true,
                            parentId: '#video-container',
                            source: 'https://...mpd',
                            shakaConfiguration: {
                                preferredAudioLanguage: 'fr-FR',
                                streaming: { rebufferingGoal: 15 },
                             width:  '100%',
                            height:  '100%',
                        });
                    </script>
</div>
```

CSS of the parent container 
parent container resizes dynamically to a 16/9 ratio and with videojs   it stretch the player to the element size automaticlally depending of the user's viewport size  

```
.video-container {
    position: relative;
    width: 100%;
    padding-bottom: 56.25%;
    overflow: hidden;
}
```

thank you
