### ISSUE TITLE
markers plugin conflict

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1282]
**Clappr Version**: https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

**Steps to reproduce**:

We use the player with 2 plugins : LevelSelector and ClapprMarkersPlugin
but when we use this last ClapprMarkersPlugin, it disables LevelSelector 

is it normal ?

Nico

**Comment by leandromoreira** [comment]
@Niko78 no, it shouldn't, we use it in production with dozens different plugins, does it shows any error message on console?

**Comment by Niko78** [comment]
my bad, it was not well implemented
