### ISSUE TITLE
managing stream failure

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1283]
**Clappr Version**: https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

**Steps to reproduce**:

We use the player in live+dvr and works well
The issue is when the stream fails for any reason (network...)
- we can see that player froze and tries to reconnect... but after few seconds/minutes it doesn't

we would espect 
1) instead of freezing video ... displayed poster image with a personnal message "we are trying to reconnect..." during 10s then test again to catch the flow
2) no limit in time to get stream back up... so player should continue to try to get it

thanks

Nico

**Comment by leandromoreira** [comment]
Maybe this is a duplicated issue https://github.com/clappr/clappr/issues/1225
