### ISSUE TITLE
Clappr and Ajax

### ISSUE THREAD

**Issue by primoitt83** [clappr/clappr#1288]
Hello guys,

I'm trying capture player events and send them to another server using an Ajax's GET.

The issue happens in a live HLS m3u8 when you hit the button STOP. Ajax is sending both PAUSE and STOP to server.

If you check the console and there's both PAUSE and STOP messages too. 

To be more clear it only happens using a live HLS  and Firefox 45 or greater. Chrome 34 or greater works fine.

If you remove ajax's code works ok

Sorry for my poor english

Thanks in advance

**Browser**: Firefox 45.3.0 ESR and Firefox 51

**OS**: Linux Ubuntu 16.04 LTS

**Clappr Version**:  0.2.65 (latest)

**Steps to reproduce**:

Just copy and paste the code below:

WITH AJAX

var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://wz-brasil1.comets.com.br/tvbaiana/aovivo/playlist.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

    player.on(Clappr.Events.PLAYER_PLAY, function() {
      
            $.ajax({
            async: false,
            url: 'https://cors-test.appspot.com/test',
            type: 'GET',
            data: 'supop'
            });         
        
            console.log("playing!");
                  
    });  

         // Se apertar o botão PAUSE
    player.on(Clappr.Events.PLAYER_PAUSE, function() {
            $.ajax({
            async: false,
            url: 'https://cors-test.appspot.com/test',
            type: 'GET',
            data: 'supop'
            });
   
            
            console.log("pause!");
      
            
      });
      
      // Se apertar o botão STOP
    player.on(Clappr.Events.PLAYER_STOP, function() {
            $.ajax({
            async: false,
            url: 'https://cors-test.appspot.com/test',
            type: 'GET',
            data: 'supop'
            });
   
            
            console.log("stop!");
      
            
      });

WITHOUT AJAX

var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://wz-brasil1.comets.com.br/tvbaiana/aovivo/playlist.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

    player.on(Clappr.Events.PLAYER_PLAY, function() {
      
        
            console.log("playing!");
                  
    });  

         // Se apertar o botão PAUSE
    player.on(Clappr.Events.PLAYER_PAUSE, function() {
   
            
            console.log("pause!");
      
            
      });
      
      // Se apertar o botão STOP
    player.on(Clappr.Events.PLAYER_STOP, function() {
   
            
            console.log("stop!");
      
            
      });

Did you try to reproduce this issue at http://cdn.clappr.io/

CDN is not working right now but it's possible to reproduce there.

**Comment by leandromoreira** [comment]
are you saying that when you added ajax it stopped working the way you were expecting?

**Comment by primoitt83** [comment]
Leandro,

Yeah. That's it

**Comment by leandromoreira** [comment]
can you do this request in a async way?

**Comment by primoitt83** [comment]
I'll attempt

**Comment by primoitt83** [comment]
It's working now! 

One last question

If the player is playing then there's a connection issues and it starts buffering.

This event shows me 2 x playing logs on console.

The first for pushing play and other for buffering.

Is it a normal behavior?

Thanks in advance

**Comment by leandromoreira** [comment]
I'm not sure if I understood you correctly but the player does buffering even with only 200 response from server.

**Comment by primoitt83** [comment]
Ok Thx again 👍
