### ISSUE TITLE
Events Api not working as function

### ISSUE THREAD

**Issue by churu88** [clappr/clappr#1292]
**Browser**: chrome (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)

**OS**: ios (ex: Mac OS 10.11.1, iOS9, android4.5)

**Clappr Version**: 0.2.25

**Steps to reproduce**:

I 'm trying to use events onPlay and some others: but the browser says it is not a function

lsd-eye-clappr.min.js:1 Uncaught TypeError: player.on is not a function
    at Analitics.initEvents (lsd-eye-clappr.min.js:1)
    at Analitics.init (lsd-eye-clappr.min.js:1)
    at new Analitics (lsd-eye-clappr.min.js:1)
    at lsd-eye-clappr.min.js:1

This is de code I'm using:

var eventHandler = new EventHandler();

var Analitics;
Analitics = function () {

    this.init = function () {
        this.initEvents();
    };

        player.on(Clappr.Events.PLAYER_READY, function (event) {
            console.log(event);
            eventHandler.readyEvent()
        });
   
        player.on(Clappr.Events.PLAYER_PLAY, function (event) {
            console.log(event);
            eventHandler.bufferingEvent()

**Comment by leandromoreira** [comment]
@churu88 I just wen to [cdn](http://clappr.io/demo/) and add this code and it works:

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  events: {
    "onPlay": function(){alert('play');}
  }
});

player.attachTo(playerElement);

```

Maybe it's something with your functions or clappr already triggered the events you were expecting thus use `events` in the constructor.
