### ISSUE TITLE
back or not on poster

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1293]
**Clappr Version**: last

when I watching a live stream then I stop the streaming server, I can see the player try to recover but sometimes it stops and displays my poster
it seems to be very random to get poster, sometimes I get only animation (without more success to recover when server is back up)

I caught debug when I fall on poster 
...
[debug][hls] playback:bufferfull hls  clappr.js:6785:91
[debug][Container] container:state:bufferfull Container  clappr.js:6785:91
[debug][hls] playback:pause  clappr.js:6785:91
[debug][Container] container:pause Container  clappr.js:6785:91
[debug][MediaControl] mediacontrol:notplaying  clappr.js:6785:91
[debug][e] pause  clappr.js:6785:91
[debug][hls] playback:ended hls  clappr.js:6785:91
[debug][Container] container:ended Object { options: Object, uniqueId: "o15", cid: "c7", $el: Object, el: <div.container.pointer-enabled>, i18n: Object, currentTime: 7362.017, volume: 100, playback: Object, settings: Object, 13 de plus… } Container  clappr.js:6785:91
[debug][Container] container:mediacontrol:disable  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 752, rebuffers: 2, rebufferingTime: 30142, watchingTime: -30074, height: 720, width: 1280, bandwidth: 1046000, bitrate: 1046000, level: 1 }  clappr.js:6785:91
[debug][MediaControl] mediacontrol:notplaying  clappr.js:6785:91
[debug][e] ended

any idea ?

**Comment by leandromoreira** [comment]
@Niko78 this log doesn't show any error =( did you observe any error level log?

**Comment by Niko78** [comment]
@leandromoreira sure I just did not display hls error message that are before that
my problem is to know why sometimes I get poster, and sometimes nope (more often player tries again and again and never back on stream)

will add errors tomorrow

**Comment by Niko78** [comment]
we can test together if you want... in private I can share with you the link
I sent you an email

**Comment by Niko78** [comment]
so when my streaming server stops and starts, this time I got player trying to recover without any success

...

[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:fragment:loaded Object { payload: ArrayBuffer, frag: Object, stats: Object }  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
GET 
XHR 
http://xxxxx/media_w554071250_b1046000_DVR_slfra_19192.ts [HTTP/1.1 200 OK 2097 ms]
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:fragment:loaded Object { payload: ArrayBuffer, frag: Object, stats: Object }  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 1, rebufferingTime: 0, watchingTime: 45005, height: 720, width: 1280, bandwidth: 1046000, bitrate: 1046000, level: 1 }  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][hls] playback:settingsupdate  clappr.js:6785:91
[debug][Container] container:settingsupdate  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 1, rebufferingTime: 0, watchingTime: 50003, height: 720, width: 1280, bandwidth: 1046000, bitrate: 1046000, level: 1 }  clappr.js:6785:91
[debug][Container] container:mouseenter  clappr.js:6785:91
[debug][Container] container:mouseleave  clappr.js:6785:91
[debug][MediaControl] mediacontrol:hide MediaControl  clappr.js:6785:91
[debug][Container] container:mediacontrol:hide  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 1, rebufferingTime: 0, watchingTime: 55003, height: 720, width: 1280, bandwidth: 1046000, bitrate: 1046000, level: 1 }  clappr.js:6785:91
[debug][Container] container:mouseenter  clappr.js:6785:91
[debug][Container] container:mouseleave  clappr.js:6785:91
[debug][MediaControl] mediacontrol:hide MediaControl  clappr.js:6785:91
[debug][Container] container:mediacontrol:hide  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 1, rebufferingTime: 0, watchingTime: 60002, height: 720, width: 1280, bandwidth: 1046000, bitrate: 1046000, level: 1 }  clappr.js:6785:91
[debug][hls] playback:levels:switch:end  clappr.js:6785:91
[debug][hls] playback:level:switch Object { level: 0 }  clappr.js:6785:91
[debug][hls] playback:highdefinitionupdate false  clappr.js:6785:91
[debug][Container] container:highdefinitionupdate false  clappr.js:6785:91
[debug][hls] playback:bitrate Object { height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:bitrate Object { height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
GET 
XHR 
http://xxxxx/media_w554071250_b546000_DVR_slfra_19192.ts [HTTP/1.1 200 OK 994 ms]
[debug][hls] playback:fragment:loaded Object { payload: ArrayBuffer, frag: Object, stats: Object }  clappr.js:6785:91
[debug][hls] playback:buffering hls  clappr.js:6785:91
[debug][Container] container:state:buffering Container  clappr.js:6785:91
[warn][hlsjs: non-fatal error occurred, evt hlsError, data [object Object] ]  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 1963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 6963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 11962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:mouseenter  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 16963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][MediaControl] mediacontrol:hide MediaControl  clappr.js:6785:91
[debug][Container] container:mediacontrol:hide  clappr.js:6785:91
[debug][Container] container:mouseleave  clappr.js:6785:91
[debug][MediaControl] mediacontrol:hide MediaControl  clappr.js:6785:91
[debug][Container] container:mediacontrol:hide  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 21962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 26963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 31963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 36964, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 41962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 46962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 51962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 56962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 61964, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 66962, watchingTime: 63039, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 71962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:mouseenter  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 76965, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:mouseleave  clappr.js:6785:91
[debug][MediaControl] mediacontrol:hide MediaControl  clappr.js:6785:91
[debug][Container] container:mediacontrol:hide  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 81962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 86963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 91963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 96962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 101963, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 106962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:mouseenter  clappr.js:6785:91
[debug][Container] container:mouseleave  clappr.js:6785:91
[debug][MediaControl] mediacontrol:hide MediaControl  clappr.js:6785:91
[debug][Container] container:mediacontrol:hide  clappr.js:6785:91
[debug][Container] container:mouseenter  clappr.js:6785:91
[debug][Container] container:mouseleave  clappr.js:6785:91
[debug][MediaControl] mediacontrol:hide MediaControl  clappr.js:6785:91
[debug][Container] container:mediacontrol:hide  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 111965, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 116969, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
[debug][Container] container:stats:report Object { startupTime: 3290, rebuffers: 2, rebufferingTime: 121962, watchingTime: 63040, height: 360, width: 640, bandwidth: 546000, bitrate: 546000, level: 0 }  clappr.js:6785:91
...
