### ISSUE TITLE
Bug with m3u8 URL with Token

### ISSUE THREAD

**Issue by mikhoul** [clappr/clappr#1297]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)

**OS**: 

Win7/64

**Clappr Version**: Latest on CDN

I need to pass a Token/Argument with m3u8 URL and it fail to take it.

Here's the URL I try: http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1487360627~exp=1487360717~acl=/i/tvago_1@410563/*~hmac=ed1b43b9dc58ecde70783302b2b2e6637afc3ae6f8fad35e50e0eb31e5fcd62e

**_N.B.:_** If you want to generate a **new valid token** just go here: http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729

Did you try to reproduce this issue at http://cdn.clappr.io/ ?
Yes

**Steps to reproduce:**

**1-**   Copy paste the URL generated here WITH the Token:  http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729
    **2-** Press the play button with the URL pasted at http://cdn.clappr.io/ 

**Result:** The Stream don't play sadly :cry: 

**N.B.1:** This stream is located in Canada if there is some geo restriction.

**N.B.2:** Work in Grind Player: http://osmfhls.kutu.ru/

Best Regards ! :octocat:

**Comment by leandromoreira** [comment]
Hi @mikhoul is there any error on console log? or network?

**Comment by flavioribeiro** [comment]
I couldn't reproduce this problem here:

![image](https://cloud.githubusercontent.com/assets/244265/23090059/9961d8be-f562-11e6-9415-76fbe2495583.png)

**Comment by mikhoul** [comment]
Thanks @flavioribeiro @flavioribeiro for the help.


I've setup a Jsbin to be sure we use the same code and resources:  http://jsbin.com/wuhiwa/edit?html,output


I tried both in Firefox and Chrome.

Here's a screenshot of the Chrome console:  http://i.imgur.com/ByS9BhV.png  The "problem seem to be in hls.js . 

Does I have the choice to use hls.js or Flashls ?

The Firefox console don't return the same message exactly that Chrome:

Screenshot with headers: http://i.imgur.com/cmjd8Gi.png

Console Dump below

```
00:22:28,930 GET 
http://output.jsbin.com/wuhiwa [HTTP/1.1 200 OK 87 ms]
00:22:28,934 La connexion avec http://output.jsbin.com/wuhiwa?0.6189157693207458 a été interrompue pendant le chargement de la page.  spike.js:232:9
00:22:29,803 GET 
https://cdn.jsdelivr.net/clappr/latest/clappr.min.js [HTTP/2.0 200 OK 29 ms]
00:22:29,810 GET 
http://static.jsbin.com/js/render/edit.js [HTTP/1.1 200 OK 19 ms]
00:22:29,813 GET 
http://static.jsbin.com/js/vendor/eventsource.js [HTTP/1.1 200 OK 17 ms]
00:22:29,814 GET 
http://static.jsbin.com/js/spike.js [HTTP/1.1 200 OK 19 ms]
00:22:30,343 GET 
http://static.jsbin.com/images/favicon.png [HTTP/1.1 200 OK 61 ms]
00:22:30,345 GET 
http://static.jsbin.com/css/edit.css [HTTP/1.1 200 OK 59 ms]
00:22:30,592 GET 
https://cdn.jsdelivr.net/clappr/latest/38861cba61c66739c1452c3a71e39852.ttf [HTTP/2.0 200 OK 165 ms]
00:22:30,845 GET 
XHR 
http://output.jsbin.com/wuhiwa [HTTP/1.1 200 OK 263179 ms]
00:22:35,346 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8 [HTTP/1.1 200 OK 14 ms]
00:22:35,377 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 12 ms]
00:22:35,560 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 13 ms]
00:22:35,594 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 14 ms]
00:22:35,716 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 14 ms]
00:22:35,788 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 14 ms]
00:22:35,899 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 15 ms]
00:22:35,956 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 14 ms]
00:22:36,068 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 13 ms]
00:22:36,136 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 13 ms]
00:22:36,195 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 15 ms]
00:22:36,221 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 12 ms]
00:22:36,298 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 13 ms]
00:22:36,341 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 12 ms]
00:22:36,413 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 20 ms]
00:22:36,467 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 13 ms]
00:22:36,606 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 14 ms]
00:22:36,664 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-p.m3u8 [HTTP/1.1 403 Forbidden 13 ms]
00:22:36,807 GET 
XHR 
http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/index_250_av-b.m3u8 [HTTP/1.1 403 Forbidden 13 ms]
00:22:36,802 [error][hlsjs: could not recover from error after maximum number of attempts, evt hlsError, data [object Object] ]  clappr.min.js:7:7247
00:32:10,309 GET 
XHR 
http://output.jsbin.com/wuhiwa [HTTP/1.1 200 OK]
```
Here's a screenshot of the Network tab: http://i.imgur.com/FUtdn1I.png

if you need more information just ask me ! 

I'd really appreciate your help ! 
Regards :octocat:

**Comment by mikhoul** [comment]
I've tried with the old **IExplorer 11** and here's a screenshot of the console messages: http://i.imgur.com/jkafPhj.png

I downloaded Opera portable and tried to see what will happen and strangely **_it work fine with Opera_**.

I need some help to find why it happen with Firefox, Chrome and IE at least, I don't have enough knowledge myself to resolve this problem alone.

Even tried with Firefox a brand new clean profile and same results. :disappointed:  

Regards ! :octocat:

**Comment by mikhoul** [comment]
> Hi @mikhoul is there any error on console log? or network?

@leandromoreira Could you help me to decipher the content of console logs ?


Regards ! :octocat:

**Comment by mikhoul** [comment]
@leandromoreira  @flavioribeiro  Nobody to help here ?

For me it work only in Opera, it don't work in Firefox or Chrome.

**Comment by mikhoul** [comment]
I tested with the FLASHLS plugin with the video.js demo to exclude a problem with the flashls plugin itself and it work fine in all browsers.

If you want to try it here: http://www.flashls.org/videojs/flash_demo.html

Regards :octocat:
