### ISSUE TITLE
Binding to HLS.js events?

### ISSUE THREAD

**Issue by Znuff** [clappr/clappr#1300]
Hello,

I can't seem to be able to figure out how to bind to HLS.js events. I'm interested in the network errors (like CONTENT_LENGTH_MISMATCH) and so on.

Clapper.Events doesn't seem to include the generic Hls.Events and I've been digging trough the code without success to find how to bind to these.

Any help?

**Comment by leandromoreira** [comment]
```javascript
player.core.getCurrentPlayback()._hls.on('hlsFragParsingMetadata', function(event, object) {...});
```
