### ISSUE TITLE
Some random videos not playing.

### ISSUE THREAD

**Issue by h4rpreet** [clappr/clappr#1301]
Hello, 

We run a video tube website and some users are reporting that they are not able to view videos, Videos just never load for them and it always keep on showing loading n loading animation. 

I myself checked those videos, it runs fine for me. I asked user to traceroute to our server and its also fine. And not all are having, its some few people.

So does anyone have any clue what to do ? I asked him his os and browser. 

Browser: Firefox Version 51.0.1 (32bit) / Chrome Version 56.0.2924.87
 
OS: Windows 10

I even asked that user to play  a video at cdn.clappr and he says it works without any issue. Please help me fix this issue. 

One example video: https://vidlox.tv/bq8urwq3eek7

Thanks.

**Comment by leandromoreira** [comment]
I tried the last video and it responded me `403`.

![screen shot 2017-02-21 at 2 04 57 pm](https://cloud.githubusercontent.com/assets/55913/23175627/cf9e9e38-f83e-11e6-8cc3-f2e5894130d7.png)

**Comment by h4rpreet** [comment]
I asked user to send his console screenshot and he gives me this: http://i.imgur.com/HN6YK1m.jpg

what should i do ? is it my server side issue or something in player ?

**Comment by h4rpreet** [comment]
Can you please try again and see if it works for you now ? we server guy did some changes. Also i really love clappr :D i wish i could contribute.

**Comment by leandromoreira** [comment]
it still raises 403, maybe it's a geolocated restrictrion.

**Comment by mikhoul** [comment]
@h4rpreet  It work also for me but I have a problem with another [Stream/URL](https://github.com/clappr/clappr/issues/1297) that for a strange reason that I don't understand work only in Opera,

Ask to a user to try with Opera Portable to see if it work ?    

Let me know if it work maybe it could be the "same" issue I have since other people are able to stream my problematic stream.

Regards :octocat:

**Comment by h4rpreet** [comment]
Hello, 

It seems we found the issue, Something like HLS ip check was showing 403. We disabled it and it runs fine now. 


Thanks.
