### ISSUE TITLE
live player: play button = grey rectangle

### ISSUE THREAD

**Issue by sstonemen** [clappr/clappr#1306]
On Chrome, Safari, Firefox...
Clappr versions from 12 month ago until today

When stream a file (Wowza > m3u8) the button bottom left in player show a white triangle that means 'play'. And while playback: two vertical rectangle that means 'pause'. OK.

**Problem:** But with a live stream (Wowza > m3u8) I only see a grey rectangle in place of this buttons. I can use it to start/pause the live stream, but it seems the graphic is missing.

I load the player from https://cdn.jsdelivr.net/clappr/latest/clappr.min.js but no other CSS or anything else. I miss something?

**Comment by kslimani** [comment]
In HLS live stream scenario, Clappr does not "pause" the video but "stop" it. I think the rectangle you see may be the "stop" icon (instead of "pause" icon in VOD scenario).

To ensure it is the case, i suggest you to take a screenshot.

**Comment by sstonemen** [comment]
lol... you are right!
Sorry.

btw: how can I customize controls?

**Comment by kslimani** [comment]
You can, for exemple, [use custom media controls](https://github.com/clappr/clappr/issues/839#issuecomment-206095423). More infos [here](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#control-bar-colors).

**Comment by sstonemen** [comment]
(Y) Thank you.
