### ISSUE TITLE
How do I support segmented media?

### ISSUE THREAD

**Issue by oyjcmyn** [clappr/clappr#1308]
How do I support segmented media?
E.g,
` source:[
       "http://img.ksbbs.com/asset/Mon_1605/0ec8cc80112a2d6.mp4",
       "http://mgcdn.videojj.com/CelebrityDetective-01_guigui.mp4"
       ],`
or 
`source:{ source: "http://img.ksbbs.com/asset/Mon_1605/0ec8cc80112a2d6.mp4",
        source:  "http://mgcdn.videojj.com/CelebrityDetective-01_guigui.mp4"
      },`
I want it to play the first MP4 immediately after playing the second MP4, the total playing time is the sum of two media time.
Multiple <video> tags are created in the HTML element。

**Comment by kslimani** [comment]
You may be interrested by [Clappr playlist plugin](https://github.com/towerz/clappr-playlist-plugin).

Check [test page](https://github.com/towerz/clappr-playlist-plugin/blob/master/public/index.html) for example usage.

**Comment by oyjcmyn** [comment]
Hi,
[Clappr-playlist-plugin](https://github.com/towerz/clappr-playlist-plugin) is no longer working properly.
[clappr-sequence-plugin](https://github.com/towerz/clappr-sequence-plugin) is also the same error.
The following program error occurred
```
Uncaught SyntaxError: Unexpected token import
Payer.php: 40 Uncaught ReferenceError: SequencePlugin is not defined
```
Is there any way to modify it?

**Comment by kslimani** [comment]
it seems it is because it is written is es6. And i see no es5 compiled dist.
You may need to compile it first or include babel in your bundle compilation.

**Comment by towerz** [comment]
Indeed, there's no compiled version for these plugins. I'll create an issue on these projects to release them allowing to use directly on the browser.

**Comment by oyjcmyn** [comment]
@towerz  Thank you, hope to be able to use it earlier.
