### ISSUE TITLE
Problem with mouse cursor in some videos...

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1310]
This video is rewindable:
http://etbvnogeo-lh.akamaihd.net/i/ETBEITBEUS_1@300391/master.m3u8

however when I put the mouse cursor over the video, it changes to a hand. This is annoying because when I click, the video pauses.
Is there any way to keep the classic mouse cursor (arrow) instead the hand?

This doesn't happen with non-rewinding videos, like this one: http://178.32.255.199:1935/live/hispantv/.m3u8

Thank you.

**Comment by kslimani** [comment]
Clappr has an internal [click_to_pause plugin](https://github.com/clappr/clappr/blob/master/src/plugins/click_to_pause/click_to_pause.js) which pause/start player if you click on video.

This may be related to your issue.

**Comment by hijuuijj** [comment]
All I want is to disable the "clicl_to_pause" feature. I don't understand why this feature is enabled for rewindable videos.
