### ISSUE TITLE
Does it support playing video videos? And not play m3u8 format.

### ISSUE THREAD

**Issue by oyjcmyn** [clappr/clappr#1311]
Does it support playing video videos? And not play m3u8 format.
Can play a complete video into multiple mp4 format, such as 1.mp4, 2.mp4, 3.mp4 ...
I do not want to have a playlist. 

You have recommended Clappr playlist plugin, but this i do not want it.

HTML e.g:
```
<div class="container pointer-enabled">
<video data-html5-video="" src="1.mp4" preload="metadata"></video>
<video data-html5-video="" src="2.mp4" preload="metadata"></video>
<video data-html5-video="" src="3.mp4" preload="metadata"></video>
</div>
```

**Comment by kslimani** [comment]
AFAIK, Clappr player does not handle this.

**Comment by towerz** [comment]
@oyjcmyn Clappr does not support having multiple playback instances in a single container like @kslimani replied.

You could use the [Clappr sequence plugin](https://github.com/towerz/clappr-sequence-plugin). It's a simple plugin that converts multiple `sources` to a sequence of `video` elements that are played in order.

This way you could just write:
```
new Clappr.Player({
  sources: ["1.mp4", "2.mp4", "3.mp4"]
  // ...
})
```
