### ISSUE TITLE
mkv files?

### ISSUE THREAD

**Issue by chovy** [clappr/clappr#1313]
can clappr play mkv files in the browser?

**Comment by kslimani** [comment]
It's a bit tricky, it depend on web browser capabilities and on the codecs used to encode video.
It *may* be possible to achieve mkv playback on Chrome browser if providing the proper mime type. (i have not tested).

**Comment by chovy** [comment]
can you give me an example?

**Comment by kslimani** [comment]
In your player configuration, you can specify a mime type using an object :

```javascript
var player = new Clappr.Player({
  source:  {
    source: 'path/to/file.mkv',
    mimeType: 'video/x-matroska'
  },
  // [...]
});

```

Please note i am not sure about mime type value. You may need to experiments other values.

**Comment by chovy** [comment]
Thank you!
