### ISSUE TITLE
Revisit autoplay on iOS

### ISSUE THREAD

**Issue by juiyout** [clappr/clappr#1314]
Previous wonfix: #404 

Please see: https://webkit.org/blog/6784/new-video-policies-for-ios/ (circa July, 2016)

Now that iOS 10 Safari relaxed `autoplay` policy per above blog post, how about we make clappr also autoplayable on iOS 10 Safari.

I have noticed that clappr does not use `<video>` tag for HLS on iOS 10 Safari. If we were to make clappr autoplayable on iOS 10 Safari, does it entail some major code change?

I'm ready to commit some time to knock this one off. If anyone could give some higher level overview, I might be able to get something going. Unless... it is already supported. (I was using clappr `0.2.65` on iOS 10.2.1 Safari with HLS, clappr did not autoplay.)

**Comment by kslimani** [comment]
> I have noticed that clappr does not use <video> tag for HLS on iOS 10 Safari. If we were to make clappr autoplayable on iOS 10 Safari, does it entail some major code change?

😕  AFAIK, Clappr use an HTML5 video element for HLS playback on iOS.

Have you tried to set `mute` option to true with `autoPlay` to true ? (i have no iOS device available to test until monday)

If this not work, it _should_ be easy to autoplay an HTML5 video on iOS if `mute` option is set to true. (_you are not the first person to ask such feature_).

**Comment by juiyout** [comment]
Ok I'm going to try that and report back soon.

**Comment by max80713** [comment]
I also encountered the same problem recently. I'll try @kslimani 's advise and report back if it works or not.

**Comment by max80713** [comment]
I've tried out @kslimani 's advice and I found that, first of all, `mute` option should be `muted` option.
And if I set both `muted` and `autoPlay` options to true or only `muted` option to true, clappr still doesn't autoplay. I guess that's because clappr mutes and autoplays the video by setting volume to 0 and calling `play()` on video element instead of just puts `muted` and `autoplay` attributes in the `video` tag(i.e `<video muted autoplay>`).
Does anyone have any idea?

**Comment by juiyout** [comment]
Confirmed that `<video>` tag is indeed there for iOS. My bad.

And yes, the option is called [muted](https://github.com/clappr/clappr/blob/0.2.65/src/components/player.js#L134). However, in [demo](http://clappr.io/demo/), it is called `mute`.

Nonetheless, setting clappr `muted` or `mute` to true doesn't apply muted attribute to `<video>` tag. It seems that original question stands. As iOS relaxed autoplay policy, shall clappr also lift the previous `wontfix` ruling and make autoPlay possible on iOS 10 Safari?
