### ISSUE TITLE
How to create mediacontrol template with custom buttons design but the same functionality

### ISSUE THREAD

**Issue by JILeXanDR** [clappr/clappr#1316]
**Clappr Version**: 0.2.25

This controls have to be located under video player not overlap it. Also I want to use plugins such as ClapprThumbnailsPlugin, ClapprMarkersPlugin, PlaybackRatePlugin. How to use them in my new template? As I said before I want to change only the design not functionality

**Comment by kslimani** [comment]
You can, for exemple, [use custom media controls](https://github.com/clappr/clappr/issues/839#issuecomment-206095423). More infos [here](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#control-bar-colors).
