### ISSUE TITLE
Can't play some M3U8 with Clappr...

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1323]
These M3U8 don't work with Clappr... why? there are no problems playing from [HLSPlayer.net](https://www.hlsplayer.net/):

http://80.250.191.10:1935/live/hlsstream343/.m3u8
http://aztecalive-lh.akamaihd.net/i/0oxnvzh8a_1@175671/master.m3u8
http://media3.crtvg.es/live/tvge_2/.m3u8
http://flash0.80670-live0.dna.qbrick.com:1935/80670-live0/murciatv/.m3u8
http://streaming2.mad.idec.net/rtvcnet/rtvcnet.drb.smil/Playlist.m3u8
http://tvgirona.dnssw.net:1935/live/Icontouch/.m3u8
http://cdns724ste0010.shooowit.net/lleidatvlive/live.smil/.m3u8
http://dsn6jqegjeixj.cloudfront.net/ondaazul-live/video/.m3u8
http://cast.streamingconnect.tv:1935/teletoledo/teletoledo/.m3u8
http://62.210.141.18:1935/directo/lancelot.television/.m3u8
http://live2.nice264.com:1935/niceLiveServer/_definst_/NTV_livenatvmb_MB_478/.m3u8
http://cast.streamingconnect.tv:1935/laregional/laregional/.m3u8
http://62.210.96.18:1935/canal45/canal45/.m3u8
http://212.104.160.156:1935/live/lebrijatv2/.m3u8
http://archlinux.frigola.cat:8080/mola/directe.m3u8
http://62.210.96.18:1935/esteponatv/esteponatv/.m3u8
http://streamer1.streamhost.org:1935/salive/GMIalfah/.m3u8

**Comment by kslimani** [comment]
It is maybe an issue with `hls.js` library, because these streams does not work also on [hls.js demo page](http://dailymotion.github.io/hls.js/demo/).

I recommend you to submit an issue [here](https://github.com/dailymotion/hls.js/issues).

**Comment by kslimani** [comment]
The third url is working for me in hls.js demo page and Clappr demo page. (_but not the first and second url_)

**Comment by hijuuijj** [comment]
I added some links more
