### ISSUE TITLE
Cannot pause at start of HLS live stream

### ISSUE THREAD

**Issue by TomBZombie** [clappr/clappr#1337]
**Browser**: Chrome 57.0.2987.98 (64-bit)

**OS**: Arch Linux

**Clappr Version**: 0.2.41

I am using Clappr for HLS streams, it works great (I have no idea how you got m3u8 ts streams to work in browser, I tried all kinds of things with the native `<video>` tag!) but there's a slight issue:  Which I believe is related to #871 , It's impossible to pause for a few minutes after the stream has started.

Steps to reproduce:

1. Start stream on server  e.g.

```
ffmpeg -i file.mp4 -g 60 -hls_time 3 -hls_list_size 50  -sn stream.m3u8
```

2. Quickly open up browser with clappr instance open. The stream appears as expected but the pause button won't appear for a few minutes.

I can see why seek doesn't work but is there no way to pause? Do I need to adjust the stream settings? E.g. larger chunk sizes or lists?

**Comment by kslimani** [comment]
@TomBZombie just a thought, have you tried to [customize hls_list_size](http://stackoverflow.com/questions/28980650/live-streaming-hls-via-ffmpeg-how-to-force-client-to-start-playing-from-the-beg)  value ?
