### ISSUE TITLE
How to show some error message on player ?

### ISSUE THREAD

**Issue by rohityadav876** [clappr/clappr#1340]
**Clappr Version**: 0.2.25

I am using **.m3u8** files in clappr, Everything is working fine, But I am unable to find How to deal with some errors. 
**Errors like :- 
1. Media Not found (404 Error) 
2. Bad Media Error 
3. Network failure** 

And How to set some custom message on player's screen.

1st Error In Detail: - In case I am putting some bad media in the **source: '{src}',** which is not available on the server so we got an Error in the Console 
**GET src.m3u8 404 (Not Found)**,

So how to show this message in the player's screen, Actually when we are getting this error then nothing happens only the spinner remains on the screen throughout the day.

**Comment by FDiskas** [comment]
```console.dir(Clappr.Events)```
You will get all events so grab one e.x. ```PLAYBACK_ERROR```
```
player.on(Clappr.Events.PLAYBACK_ERROR, function(error) {
      console.log(error);
    });
```

**Comment by hijuuijj** [comment]
I have the code:

`<script src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<div id="player"></div>
<script>var player = new Clappr.Player({
source: "http://www.stream.com/stream.m3u8",
parentId: "#player",
height: "100%",
width: "100%",
autoPlay: true,
});
</script>`

Where to add this code?

`player.on(Clappr.Events.PLAYBACK_ERROR, function(error) {
      console.log(error);
    });`

**Comment by leandromoreira** [comment]
```
<script>
var player = new Clappr.Player({ 
  source: "http://www.stream.com/stream.m3u8", 
  parentId: "#player", 
  height: "100%", 
  width: "100%", 
   autoPlay: true});

   player.on(Clappr.Events.PLAYBACK_ERROR, function(error) { console.log(error); });
</script> 
```

**Comment by kslimani** [comment]
@hijuuijj you can also use the `events` player configuration property to bind events.

Example : 
(_you can try this code on [demo page](http://clappr.io/demo/)_)

```javascript
var player = new Clappr.Player({ 
  parentId: "#player-wrapper", 
  height: 360,
  width: 640,
  autoPlay: true,
  source: 'http://clappr.io/bad_highline_url.m3u8',
  events: {
    onError: function (e) {
      console.log('Player Error:', e);
    }
  }
});
```

Also, more error handling examples are available in [documentation](https://github.com/clappr/clappr/blob/master/doc/PLAYER_ERRORS.md).
