### ISSUE TITLE
How can set custom headers in request?

### ISSUE THREAD

**Issue by mortegai** [clappr/clappr#1345]
I need send some custom HTTP headers in the request to media URI.

How can get it?

Thanks

**Comment by towerz** [comment]
@mortegai you can set some custom headers if you're using HLS. If you are using MP4 files directly, since we use the native HTML5 video tag, you won't be able to do this.

Could you please give some more details?

**Comment by mortegai** [comment]
Yes, it's for HLS. And in (#1075) I found how to do it: hlsjsConfig with xhrSetup and xhr.setRequestHeader. But is not valid for some header as Referer

**Comment by kslimani** [comment]
@mortegai  I don't think you can send `Referer` header with XHR. Have you tried [this trick](http://stackoverflow.com/questions/40063682/is-it-possible-to-set-referer-header-for-xhr-in-html-application) ?
