### ISSUE TITLE
How to get CC (Closed Caption) Support in Clappr JS 

### ISSUE THREAD

**Issue by rohityadv876** [clappr/clappr#1357]
As we know Clappr is built on HLS JS so can you please let us know how to get **CEA-708 captions** support in our videos. 

As I am getting: - 
If we try to use:- http://video-dev.github.io/hls.js/demo/ 
With:- https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 
Link then we got CC on player's control panel. 
But when I am using same link:- https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 on 
**https://clappr.io/demo/** 

Can anyone help me to resolve the issue? 

Is there is any plugin available to use? 
As now I am using https://github.com/JMVTechnology/Clappr-Subtitle Which parses .srt to CC and embed in the player but not working as expected So looking for native support.

**Comment by towerz** [comment]
The hls.js version used on Clappr was outdated, updating to 0.7.5 solved this issue.
