### ISSUE TITLE
Question: Will update hls.js to 0.7.5 version?

### ISSUE THREAD

**Issue by DiegoZurita** [clappr/clappr#1360]
Will update hls.js to 0.7.5 version?

**Comment by kslimani** [comment]
@leandromoreira i just realized that hls.js version in package.json is "^0.7.2" and the value in yarn.lock is "^0.6.17" (locked to "0.6.18").

Do you known if Greenkeeper bot can handle yarn.lock modification in pull requests ? (_if not it may be also a nice feature request_).

**Comment by leandromoreira** [comment]
@kslimani I don't know = / but we should keep the newest version on both case shouldn't we?

**Comment by kslimani** [comment]
maybe update the [bump](https://github.com/clappr/clappr/blob/master/bump) script to keep yarn.lock up to date at each release ?

**Comment by towerz** [comment]
@kslimani sure, we'll update the bump script to work with yarn.lock when we release the next version. I think we'll do it by tomorrow.

**Comment by DiegoZurita** [comment]
I just try update bump script on my fork to update yarn.lock (https://github.com/DiegoZurita/clappr/blob/master/bump), is something like that?
