### ISSUE TITLE
Disable the seekbar

### ISSUE THREAD

**Issue by gaalgergely** [clappr/clappr#1364]
**Browser**: Firefox

**OS**: Ubuntu

**Clappr Version**: latest downloadable

**Steps to reproduce**:

* added seekEnabled:false to the options
* I was expecting that the seekbar can not be used or hidden

Did you try to reproduce this issue at http://cdn.clappr.io/ yes

**Comment by kslimani** [comment]
AFAIK, there is (_currently_) no player option to disable mediacontrol seek bar. Where have you seen `seekEnabled` option ? (or are you asking a feature ?)

**Comment by gaalgergely** [comment]
I am reading the docs. Found something similar here:
https://github.com/clappr/clappr/commit/85f54f84a9b14853b49f1b327b1a724df55aff2a

**Comment by kslimani** [comment]
I see. I think that `container.settings.seekEnabled` is an internal only parameter which is automatically updated. (_and therefore you can't override it_).

The only way i found to disable seek bar was to create my own custom mediacontrols.

**Comment by gaalgergely** [comment]
Thanks for the response! How can i do that? Do you have a tutorial somewhere?

**Comment by kslimani** [comment]
There is no tutorial yet. But there is an example [here](https://github.com/clappr/clappr/issues/839#issuecomment-206095423). Additional infos also [here](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#control-bar-colors). And [here](https://github.com/kslimani/live-program-mediacontrol) some **experimental** tests i have done.

**Comment by gaalgergely** [comment]
Thank you!
