### ISSUE TITLE
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#1365]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Any mobile device

**Clappr Version**: 0.2.25
latest

**Steps to reproduce**:
* Open demo on mobile
* Hit the play button and wait until the video end.

Ir should change video source and do not stop the playback.

Demo: http://jsbin.com/coxofuyeni/1/edit?html,output
```
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.
```

**Comment by FDiskas** [comment]
Why on player options change the video element is re-rendered? 
So this is why user should hit the play button again.
https://github.com/clappr/clappr/blob/5b51269ac9b39981e036f1167c2a2f9e34e2b35c/src/plugins/poster/poster.js#L52

**Comment by kslimani** [comment]
@FDiskas this issue should be fixed in next Clappr release for mobile devices, using the `consent()` player method with `recycleVideo` html5 playback feature.

Take a look at #1319 for example usage. (_you can also perform tests with custom build using current master branch_).
