### ISSUE TITLE
piece of code doesn't work with 0.2.66

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1381]
**Clappr Version**: 0.2.66

since I upgraded clappr in 0.2.66 piece of my code did not work

var bufTime = 0;
    var z = 10;
    var timerId = setInterval(function () {
        if (player.buffering && player.isPlaying()) {
            bufTime += 1;
        } else if (!player.buffering && !player.isPlaying()) {
	    bufTime = 0;

        }

        console.log(bufTime);
        if (bufTime >= z) {
            console.log('bf > ' + z);
            bufTime = 0;
            console.log('live/dvr issue ?');
            document.getElementById("show").innerHTML = '<strong>Stream not available. Retry later.</strong>';
            player.stop();
        }
    }, 1000);

so before the upgrade when no stream available I had a message to warn me, I have also an other script to rewrite the "show" element that's why my script is in a loop (setinterval)

the issue is that at the first issue, script seems to work ok, I can see in console : 10 9 8 7 ... then 0... but being at 0 with the same state it should restart from 10 and it's not the case right now (worked before)

any idea ?

thanks

**Comment by kslimani** [comment]
@Niko78 i tested your code with Clappr version 0.2.66 and with current master and it is working for me.

By working, i mean the player is stopped after `bufTime` reached 10. (_i just commented the getElementById stuff which does not exists on my test page_).

**Comment by Niko78** [comment]
@kslimani yep but when it reaches 10 it should restart from 0 then reaches again 10, etc...
in my case now when it reaches 10, it stays after at 0

**Comment by kslimani** [comment]
@Niko78 from my understanding, if the player is stopped, then the `(!player.buffering && !player.isPlaying())` condition is true and the `bufTime` value is always set to 0.

**Comment by Niko78** [comment]
it worked before... so something has changed
how would you fix that ?

**Comment by kslimani** [comment]
You are correct, many things has changed with latest release. (_some bugs have been fixed and some library upgraded_)

Can you desbribe what you are trying to achieve ?

**Comment by kslimani** [comment]
BTW, if you are trying to handle HLS playlist load error, you may be interested by #1374 .

**Comment by Niko78** [comment]
I try to find a solution when stream fails (network, encoder, stream server...)

I have autostart at true, so when I display page, clappr tries to get the streams, when it fails, it retries few times then finish in "max recovery...".. but clappr player shows only background and not "play" button in that state, so if I want to recheck, I need to refresh the whole page

That's why in my script I detect failure/error and in this case, I force to stop player to get "play" button again

Then as I said before, I have an other script that displays information in "show" element each 30 s, the same where I put an error message ; so when failure I display message but 30s after I have an other info
that's why my script should restart counter to display 10 seconds after a message

Better would be for me to display a message inside player but I don't know how to.
And better again : display a message inside player with a counter (10 seconds) which retries by itself to get the stream, etc...

**Comment by Niko78** [comment]
@kslimani BTW, if you are trying to handle HLS playlist load error, you may be interested by #1374 .

=> it is already integrated in 0.2.66 ?

**Comment by kslimani** [comment]
@Niko78 pull request is not yet reviewed/merged in 0.2.66. You will need custom build to add this feature in the meantime.

**Comment by kslimani** [comment]
There is a little trick i often use to display an error message in player :

```javascript
// [...]
player.configure({
  source: 'player.error',
  playbackNotSupportedMessage: 'My error message'
});
```

**Comment by Niko78** [comment]
what I would like to see in clappr as an option : http://demos.flowplayer.org/api/live-check.html

**Comment by kslimani** [comment]
You can do the same with Clappr using `error` event.

```javascript
var player = new Clappr.Player({
  source: 'http://example.com/playlist.m3u8',
  events: {
    onError: function(e) {
      // Here handle player error
    }
  }
});
```

**Comment by Niko78** [comment]
great @kslimani 
I'm waiting new clappr build to test it

**Comment by kslimani** [comment]
@Niko78 you can already test it with mp4 format on current [demo page](http://clappr.io/demo/) by just copy/paste [this example](https://github.com/clappr/clappr/blob/master/doc/PLAYER_ERRORS.md#another-example).

**Comment by Niko78** [comment]
yep I already tested it ;-)
Now I'm trying to manage case when dvr is enable and live is broken
thanks

**Comment by kslimani** [comment]
For hlsjs playback it should work in next release. (fixed by #1374), or test with custom build.

**Comment by Niko78** [comment]
hmmm your code doesn't work well sorry
I tried to read an hls stream then shut my network... I just got bubble animation and not your code
try it

**Comment by kslimani** [comment]
For hlsjs playback, you have to test with current master branch. More precisely :

* clone the project
* install dependencies
* run the demo page locally with `npm run start`
* _(optionally) create custom build with `npm run build && npm run release`_

Then test example code snippet (_http://localhost:8080_).

**Comment by Niko78** [comment]
ok sorry for misunderstanding

**Comment by Niko78** [comment]
sorry to ask again but in your code, it starts by error message instead of trying to catch stream
I know it is as example but can you tell me how to do to try first to get the stream and if it fails ok display error message with the counter
thanks

**Comment by kslimani** [comment]
@Niko78 : of course it is 😄 !

Take a look at player `source` option : it is set to `http://clappr.io/bad_highline.mp4` which is a bad url which return a 404 error on purpose.
(_to immediately display error message to demonstrate error handling_).

Just change it by a "good" source url.

**Comment by Niko78** [comment]
arf sorry my bad :-(

**Comment by leandromoreira** [comment]
You can always use the clappr-stats to provide many of the metrics you're trying to calcalute.
