### ISSUE TITLE
export using the `modules` attribute

### ISSUE THREAD

**Issue by contra** [clappr/clappr#1383]
Here is an example of what this looks like on another project: https://github.com/uber/deck.gl/blob/master/package.json#L16-L17

By adding this attribute in the `package.json` you enable modern browsers/node/webpack to do code splitting, which drastically reduces the size of the output by only including exactly what is being used.

Here is what `clappr` looks like right now (code splitting disabled, because the `main` in the package.json is the pre-compiled file):
<img width="913" alt="screen shot 2017-05-02 at 11 26 59 am" src="https://cloud.githubusercontent.com/assets/425716/25625435/7f85fe00-2f2a-11e7-8af4-950339cb8150.png">

For somebody who is just using the player and supporting a few video types, this is a pretty huge amount of unused code.

I think for this project it would be as simple as adding `module: "src/index.js"` to enable webpack/rollup/whatever users to code split - happy to send a PR.

**Comment by kslimani** [comment]
I am curious about this. However, I lack knowledge about this `module` field in package.json and i failed to find any detailed documentation about this. (_only [this page](https://github.com/rollup/rollup/wiki/pkg.module) seems relevant_).

@contra are you sure adding the `module` field is enough ? does it not require also to build/compile an es6 "dist" version of Clappr ?

**Comment by contra** [comment]
@kslimani Yeah, you point the module attribute to the source and the user's build system will figure out how to make it work (compile using the dependency babelrc, etc.)

**Comment by contra** [comment]
You should be able to point it at the source unless you have any custom babel plugins that need running.

deck.gl, for example has one plugin that they run first: https://github.com/uber/deck.gl/blob/master/package.json#L26

**Comment by kslimani** [comment]
I see. Then they also build an es6 dist version of their modules.
it may be required to do the same to be compliant as Clappr build use babel plugins and webpack loader which transform, for example, css to be loaded as module. (_i lack the knowledge about this. Clappr core should have a better answer for this issue_)

**Comment by contra** [comment]
@kslimani Webpack will handle all of that stuff based on the top-level user config. The way webpack deals with this is to treat a dependency with a `module` attribute as if it was a member of your own source code - compiling it with babel, loading linked css files, etc.

**Comment by kslimani** [comment]
So, if i understand well, if you import Clappr as an external dependency in your project, webpack will use es6 code instead of importing Clappr as an es2015 module ?

**Comment by leandromoreira** [comment]
@thiagopnts is working to shrink the final size and also he, @towerz and @tjenkinson knows a lot about this!! 🥇

**Comment by thiagopnts** [comment]
nice, this makes a lot of sense!
I added this to #1395, with this + not requiring all plugins in the `Loader` we should have a pretty smaller bundle

**Comment by leandromoreira** [comment]
Also, @contra feel free to send a PR quoting https://github.com/clappr/clappr/issues/1395 @thiagopnts is also doing an amazing job toward this direction.

**Comment by contra** [comment]
Keep it open.

**Comment by towerz** [comment]
That's really weird, it shouldn't be marked as stale since you bumped the issue. I'll try to check why this happened.

**Comment by contra** [comment]
Keep it open please.

**Comment by leandromoreira** [comment]
Keep it open.

**Comment by contra** [comment]
Keep it open.

Also FWIW - I made a quick attempt at doing this, there was some complexity with the clappr babel build setup that wasn't working right for me so I wasn't able to get it into a PR-able state.

**Comment by leandromoreira** [comment]
Keep it open.

**Comment by leandromoreira** [comment]
keep it open

**Comment by leandromoreira** [comment]
keep it open

**Comment by towerz** [comment]
This should keep it open. I'm testing whether keeping the source reference as the module entry point would work correctly. Webpack doesn't provide an easy way of working with this, and Rollup doesn't help with built-in assets, so I'm experimenting with some solutions.

The actual solution for that would be after we split the project into its core components and the optional components/plugins, which should help with packaging and exporting separately each part. Perhaps this way we can choose using Rollup for most of the projects and Webpack only when we need packaged assets.

**Comment by joaopaulovieira** [comment]
As @towerz commented, it was decided to divide the project into other smaller components ([clappr-core](https://github.com/clappr/clappr-core) and [clappr-plugins](https://github.com/clappr/clappr-plugins)) to achieve the objective of this issue. (More details in the [0.4.0 changelog](https://github.com/clappr/clappr/releases/tag/0.4.0))
