### ISSUE TITLE
Problem with two players

### ISSUE THREAD

**Issue by danicho** [clappr/clappr#1390]
I have a problem. When I insert two players into an accordion in wordpress, players appear together

http://bit.ly/2qPAcJC

Thanks

**Comment by leandromoreira** [comment]
Are you using a different container for each player instance? Can you paste the mark up here?

**Comment by danicho** [comment]
I am a newbie and I speak Spanish, I hope you understand me.
Apply google translate. I am using the following code.
I want one player to be in one section and the other to the next section

<head>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
</head>
<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({source: "http://xxxx.xxxxxxx/xxxxxx/x/xxxxx.m3u8", parentId: "#player", poster: 'http://xxxxx.xx/play2.png'}); 
  </script>

 Thanks

**Comment by leandromoreira** [comment]
@danicho you must have the two divs with differents `parentId`.  

```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<script> 
var player1 = new Clappr.Player({source: "http://xxxx.xxxxxxx/xxxxxx/x/xxxxx.m3u8", parentId: "#player1", poster: 'http://xxxxx.xx/play2.png'}); 
var player2 = new Clappr.Player({source: "http://xxxx.xxxxxxx/xxxxxx/x/xxxxx.m3u8", parentId: "#player2", poster: 'http://xxxxx.xx/play2.png'}); 

</script>

<div id="player1" />
<br/>
<div id="player2" />
```
