### ISSUE TITLE
flashhls getCurrentTime() returns wrong info

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#1392]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
https://www.whatismybrowser.com/w/QC7GAKG

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
https://www.whatismybrowser.com/w/QC7GAKG

**Clappr Version**: "0.2.66"

INFO:FlasHLS Clappr (version: 0.4.15 - flashls: 0.4.4.22, id: o73)
2017-05-09 18:45:28.189 VM2258:1 INFO:HLSNetStream:close
2017-05-09 18:45:28.398 VM2264:1 INFO:HLSNetStream:play(-1)
2017-05-09 18:45:28.400 VM2265:1 INFO:HLSNetStream:seek(-1)
2017-05-09 18:45:28.592 VM2282:1 INFO:Setting audio track to 0
2017-05-09 18:45:29.770 VM2289:1 INFO:Video decoding:software

**Steps to reproduce**:
1. Open Opera browser
1. Add dvr stream
1. Check that FlasHLS is used
1. In console ```player.getCurrentTime()```

This should return current playing time. Looks like time updates only then the segment of the stream is downloaded.

Did you try to reproduce this issue at http://cdn.clappr.io/
**YES**

http://i.imgur.com/IK4onWg.png

**Comment by FDiskas** [comment]
dead project

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/commits/master
