### ISSUE TITLE
Starting clappr from beginning in live mode(VOD). 

### ISSUE THREAD

**Issue by nishantkumarsah** [clappr/clappr#1393]
I have a video on disk which i convert on run time for HLS format using ffmpeg. Since playlist is still being updated every few seconds, clappr treats it as live stream. Upon playing the stream it plays it from the current position(live mode) and NOT from the beginning. How do i force it to play from beginning. I need it to play from start every time i open the player?

**Comment by nishantkumarsah** [comment]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:17
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:16.706556,
partial_file0000.ts
#EXTINF:8.341667,
partial_file0001.ts
#EXTINF:8.341667,
partial_file0002.ts
#EXTINF:8.341667,
partial_file0003.ts
#EXTINF:8.341667,
partial_file0004.ts
#EXTINF:16.683333,
partial_file0005.ts
#EXTINF:8.341667,
partial_file0006.ts
#EXTINF:8.341667,
partial_file0007.ts


This playlist is still being generated. Currently avi container is getting converted into HLS playlist. 
As soon as the playlist is available(even with one segment), the playlist is fed to clappr. 
The clappr starts in live mode since playlist is still  in generation. While in live mode clappr plays the most recent segment and NOT the first segment. 
I can not wait for playlist to be completely generated. I need to play as soon as something is available.  However it needs to play from the start.

**Comment by nishantkumarsah** [comment]
playlist after some time.  Still in generation.

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:17
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:16.706556,
partial_file0000.ts
#EXTINF:8.341667,
partial_file0001.ts
#EXTINF:8.341667,
partial_file0002.ts
#EXTINF:8.341667,
partial_file0003.ts
#EXTINF:8.341667,
partial_file0004.ts
#EXTINF:16.683333,
partial_file0005.ts
#EXTINF:8.341667,
partial_file0006.ts
#EXTINF:8.341667,
partial_file0007.ts
#EXTINF:8.341667,
partial_file0008.ts
#EXTINF:8.341667,
partial_file0009.ts
#EXTINF:16.683333,
partial_file0010.ts
#EXTINF:8.341667,
partial_file0011.ts
#EXTINF:8.341667,
partial_file0012.ts
#EXTINF:8.341667,
partial_file0013.ts
#EXTINF:8.341667,
partial_file0014.ts
#EXTINF:16.683333,
partial_file0015.ts
#EXTINF:8.341667,
partial_file0016.ts

**Comment by leandromoreira** [comment]
Please paste the final playlist, I suspect clappr is treating this playlist as a live type, which seems okay given the playlist you gave me. 

A VOD playlist usually contains some meta tags like [`EXT-X-PLAYLIST-TYPE:VOD`](https://developer.apple.com/library/content/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-TNTAG2) otherwise it'll be treated as live, anyway you also might need to wait this playlist to be finished.

The player can assume it's a VOD playlist therefore it'll only download the playlist once and since you're generating more items to this playlist the player will ignore this items.

**Comment by nishantkumarsah** [comment]
I understand that this is expected behavior. 
How do i tell clappr to play from the start when it begins playing in live mode? 
Is there any options/settings ?

**Comment by flavioribeiro** [comment]
what if you just seek to the beginning after the play?

**Comment by nishantkumarsah** [comment]
yes, this is the current situation. However, from the user experience point of view it is not an acceptable one. The user is expecting a fully downloaded file and not live mode. He wants to see video from start and not from say 5 min delayed even though he can seek back.

**Comment by kslimani** [comment]
why not simply convert the file to HLS, then serve it statically, instead doing that on-the-fly ? (_unless i missed something ?_).

**Comment by nishantkumarsah** [comment]
**Use case**

User downloads the file on cloud and expects to view/play them immediately. 

The file container is not constant. It can be .mkv or .avi or .mpeg etc with different codecs. For this reason, all the files are converted into common denominator "HLS". 
This conversion to HLS format is quick in case if only demuxing is required. However, when decoding is also required for formats like .avi, it takes a lot of time(sometime hrs). Hence, user cannot wait that long for conversion of file and thereafter to play it. 
Now for the latter case one option is to poll the availability of playlist after few seconds and play as soon as playlist is available. The polling cannot happen every other second due to performance constraints. So, by the time playlist is available and supplied to clappr the live mode is 10-20 sec ahead of the start time depending upon the speed of the encoding done by ffmpeg. This i wanted to avoid by some setting/option to play the video from the start even in live mode?

**Comment by leandromoreira** [comment]
@nishantkumarsah maybe you should look at https://github.com/kaltura/nginx-vod-module it seems that this module generates the complete playlist and the segments are being generated on the fly, this might serve you and also solve your problem.

**Comment by nishantkumarsah** [comment]
**setting/option to play the video from the start even in live mode????**

**Comment by kslimani** [comment]
@nishantkumarsah AFAIK, there is no option in Clappr to play video from start (_with live mode with DVR capabilities_). The only possible "trick" is to seek back from start on first video play event.

For example (try this on [demo page](http://clappr.io/demo/)) :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://wowza.jwplayer.com/live/jelly.stream/playlist.m3u8?DVR',
  height: 360,
  width: 640,
  events: {
    onPlay: function() {
      if (player._hasSeek) {
        return
      }
      player.seek(0);
      player._hasSeek = true;
    },
  },
});

player.attachTo(playerElement);
```

**Comment by nishantkumarsah** [comment]
thankyou
