### ISSUE TITLE
Decrease bundle size

### ISSUE THREAD

**Issue by thiagopnts** [clappr/clappr#1395]
I've been running some bundle analyzers in the code to see what we can change to decrease the bundle size:
![image](https://cloud.githubusercontent.com/assets/322239/26014537/f7e2a7ba-372a-11e7-8382-5e118c25d71d.png)

There is a lot of room for improvements, I'll use this issue to list my findings and track my progress

- [x]  remove lodash.uniqBy
- [x]  remove lodash.isequal
- [x]  remove lodash.merge
- [x]  remove lodash.once
- [x]  remove lodash.isplainobject
- [x]  remove lodash.result
- [x]  figure out where this `buffer` module is coming from
- [ ]  remove the process polyfill
- [ ]  use `babel-preset-env` to improve our babel pipeline and avoid unnecessary polyfills
- [ ]  test `CommonsChunkPlugin` for multiple bundles and async load of big dependencies
- [ ]  try to remove `clappr-zepto` 🔥 
- [ ] use `module` field in `package.json` to es6 version of the code
- [ ] only export plugins in the main and dont require all in the `Loader`
- [ ] remove white spaces from template/css code

current bundle size is 521kb

**Comment by kslimani** [comment]
The "main" property in [package.json of clappr-zepto](https://github.com/clappr/clappr-zepto/blob/master/package.json#L5) module is pointing to zepto.min.js. Maybe it worth a try to change the value to zepto.js and try to rebuild Clappr to see if it reduce size of bundle minified by uglifyjs.

**Comment by michaelcunningham19** [comment]
@thiagopnts 
Another idea is to add a release job to make a "light" version of Clappr which excludes FlashLS, as probably the majority of developers using Clappr don't even need Flash support at this point in 2017. (At least I hope so)

I have a fork of Clappr on my GitHub profile where I stripped out FlashLS entirely. See commit: https://github.com/michaelcunningham19/clappr/commit/a00b12ea0c27dbd5011f1b134a6bc2d2ea196f2e

The change resulted in a decent decrease in file size, which I will add here when I can! :)

If this sounds like a good idea I will gladly look into opening a PR to support a "light" build

Worth noting that hls.js also has a "light" build that they recently added: https://github.com/video-dev/hls.js#dependencies

**Comment by thiagopnts** [comment]
@michaelcunningham19 I'm working on this here https://github.com/clappr/clappr/tree/skinny-clappr
it has a ~175kb light version
