### ISSUE TITLE
Combine MediaControl and Playback Plugin

### ISSUE THREAD

**Issue by ewwink** [clappr/clappr#1398]
just finished my first plugin, the code is at https://github.com/ewwink/clappr-youtube-plugin it two plugin type (MediaControl and Playback)  in one file, now I call it with ` plugins: [YoutubePlugin, YoutubePluginControl]` but how to call it as one plugin like ` plugins: [YoutubePlugin]`

**Comment by leandromoreira** [comment]
@ewwink they are two distinct plugins why would you like to join them in one?

**Comment by ewwink** [comment]
To make it easier to remember the plugin name. i try to call `YoutubePluginControl` from `YoutubePlugin` like below but not work
```
this.YTControl = new YoutubePluginControl();
this.YTControl.render();
```

do you think it is possible?

**Comment by leandromoreira** [comment]
Maybe you need to create a `core`plugin` which provides these two extra plugins but I'd prefer one single project (github) with two plugins, you can make a helper:

```javascript
// all returns all the needed plugins
plugins: [YoutubePlugings.all()]
```

**Comment by ewwink** [comment]
you are right I should convert it to core plugin, maybe I'll do it in the future. and thanks
