### ISSUE TITLE
HLS (m3u files) and player event error documentation example

### ISSUE THREAD

**Issue by wicherdt** [clappr/clappr#1408]
**Browser**: Firefox 53.0.2 (64 bit)

**OS**: Windows 10

**Clappr Version**:   17 May 2017 on http://clappr.io/demo/

**Steps to reproduce**:
Example from commit : https://github.com/clappr/clappr/commit/e4c82cb44b4289e851ba15a73a836c7ae6ba70ee

"error" event dont work wiyh HLS source (m3u files)

var playerElement = document.getElementById("player-wrapper");

var r = 3; // Retry attempts

var player = new Clappr.Player({
 // HLS source 
  source: 'http://clappr.io/bad_highline.m3u8',
  height: 360,
  width: 640,
  events: {
    onError: function(e) {
      r--;
      var s = player.options.source;
      // Replace previous line by the following line to simulate successful recovery
      // var s = (r > 2) ? player.options.source : 'http://clappr.io/highline.mp4';
      var t = 10;
      var retry = function() {
        if (t === 0) {
          player.configure({source: s});
          return;
        }
        Clappr.$('#retryCounter').text(t);
        t--;
        setTimeout(retry, 1000);
      };
      player.configure({
        autoPlay: true,
        source: 'playback.error',
        playbackNotSupportedMessage: 'Network fatal error.' + ((r > 0)
            ? ' Retrying in <span id="retryCounter"></span> seconds ...'
            : ' All retry attempts failed'),
      });
      if (r > 0) {
        retry();
      }
    }
  }
});

player.attachTo(playerElement);

Did you try to reproduce this issue at http://cdn.clappr.io/
YES on http://clappr.io/demo/

**Comment by kslimani** [comment]
@wicherdt it should work with current master. Please read [this comment](https://github.com/clappr/clappr/issues/1381#issuecomment-302065612).

**Comment by wicherdt** [comment]
YES it work.
Please close issue.
