### ISSUE TITLE
Is it possible to override existing keyboard event?

### ISSUE THREAD

**Issue by RodolpheFouquet** [clappr/clappr#1412]
Browser: 58.0.3029.110 (64-bit)

OS: Win 10

Clappr Version: 0.2.65

Steps to reproduce:

* Init a new Clapper player (new Clappr.Player(...))
* Attach a callback to PLAYER_READY and then try to do something when left/right arrow are being pressed (for example output into the console.log)
* The default behavior occurs (seek to -/+ 5 secondes instead of outputting the log)

I would like to know if this approach is possible or if you ever plan to access the kibo object through the plugins API.

Thank you.

Code Sample:
https://jsfiddle.net/1dtcs3hh/

**Comment by kslimani** [comment]
@RodolpheFouquet  It seems that kibo from mediacontrol may not be available on player ready event.
You may, for example, use the play event to bind keys :

```javascript
var playerElement = document.getElementById("player");

var player = new Clappr.Player({
  source: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8",
  mute: false
});

player.on(Clappr.Events.PLAYER_PLAY, function() {
  if (!this._binded && this.core.mediaControl.kibo) {
    const k = this.core.mediaControl.kibo;

    // Unbind previous left and right keys
    k.off(['left', 'right']);

    // Bind new left and right keys
    k.down('left', function() {
      console.log('left key pressed !');
    });
    k.down('right', function() {
      console.log('right key pressed !');
    });

    // Ensure binding is done only once
    this._binded = true;
  }
});

// Player must be attached after binding event
player.attachTo(playerElement);
```

**Comment by kslimani** [comment]
Additionally, you may want to known that the internal [Kibo](https://github.com/marquete/kibo) library is exposed by Clappr module :

```javascript
var myKibo = new Clappr.Vendor.Kibo();
```

**Comment by RodolpheFouquet** [comment]
Awesome, that works, thank you!
