### ISSUE TITLE
flashls playback does not start to play from js in IE11

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1414]
**Browser**: IE 11.0.9600.18230
**OS**: Windows 7
**Clappr Version**: cdn.clappr.io

**Steps to reproduce**:
- try [this](http://audioplayer.df6.ru/audio/testie.html) page to test. It has a simple code with autoPlay to run player :
```
player = new Clappr.Player({
	width: 320,
	height: 240,
	audioOnly: true,
	persistConfig: false,
	autoPlay: true,
	startFromLevel: 1,
	flushLiveURLCache: true,
	hlsjsConfig: {
	    xhrSetup: function(xhr, url) {
		xhr.withCredentials = true;
	    },
	},
	playbackConfig: {
	    crossorigin: 'use-credentials'
	},
        plugins: [Clappr.FlasHLS],
    });
    Clappr.Log.setLevel(0);
    player.attachTo(playerElement);
```
- Expected start playing but sometimes it's not. I also noticed that if I enable always request from server option in developer network console then everything start playing because of 200 responses. But without this option with default browser cache enabled player stopped with 304 reponses:

These are screenshots after "Load" button pressed in developer console while caching is enabled:

![default](https://cloud.githubusercontent.com/assets/2188440/26264882/2281c3b8-3ce7-11e7-90bb-7bbcfd1a31a8.png)

![default](https://cloud.githubusercontent.com/assets/2188440/26264889/28b109f6-3ce7-11e7-8b5c-fd82bb023054.png)

[This](http://www.flashls.org/latest/examples/chromeless/?src=http%3A%2F%2Fhls.02.ep.emgsound.ru%2F11%2Fplaylist.m3u8) link is playing well after click on "Load". 

These are Network console screenshot after "Load" button pressed with 200 swf responses while caching is disabled:

![default](https://cloud.githubusercontent.com/assets/2188440/26265038/f9b495ea-3ce7-11e7-9e4a-fc7af0c8a355.png)

This is a renewal of https://github.com/clappr/clappr/issues/1105

Also I noticed that swf file is downloaded twice, and it adds extra time and pause while switching from preroll to live HLS stream in IE11 for example. BTW, how this pause can be avoided in general if it is possible?

With regards, Andrey.

**Comment by kslimani** [comment]
Allright, i perfectly understand what is going on here. It is a known IE11 issue. But there is a workaround.
I will send a PR this week to propose a fix for this issue.

BTW, i have a question : on your test page, do you want the radio to autoplay on page load, or only after click play button ?

**Comment by waster** [comment]
@kslimani great, thank, will wait for the fix. Actually I want to have the way to run radio on after click play button, but it is important also to start play automatically after some preroll, for example.

**Comment by waster** [comment]
@kslimani can you please describe quickly in general words (or may be give a link) what is it a known IE11 issue and workaround fix logic?

**Comment by kslimani** [comment]
Quickly, it's a bug related to ie11 cache with Flash ActiveX (_happen when you receive 304 http response when loading swf file_).

A simple workaround is to use a "cachebuster" mechanisms; For exemple by appending a random query parameter to swf file URL. (_the cons is that the swf file is always downloaded when player load another "flash" source, but i guess it is better than player error_).

My guess is : you configure a .m3u8 source which is "resolved" to be played with FlashHLS playback. Then on "play" event, the VAST plugin store source url, use player load method to play the video advert, then use player load again to play original source url : this is when the bug happen in ie11.

Without entering too much in details : the Clappr player mechanisms when it load another source, it to destroy the current container, and build another one according to the source (_this container "contains" the resolved "playback" used to display "source"_). In your case, the FlashHLS playback is created, then destroyed to create another playback for video ad (nature of playback depends on ad video source), then playback is destroyed and FlashHLS playback re-created to attempt to display original source : this is when the error happen (_only for ie11_).

_Note that i did not deeply test yet and my assumptions may be wrong, but i think this is the reason; In the past i already had to deal with this issue on another project._

**Comment by waster** [comment]
Yes, I see, but in our case first playback is created on preroll and then it is destroyed and recreated with flashls to switch to live HLS stream. In the case of "cachebuster" mechanism swf will be downloade twice as I noticed and it will cause hole (sometimes up to 4 seconds) between end of ad and start of live stream. Can it be avoided in IE11/Edge? For example can we load flash playback initially at the beginning of preroll playing and do not recreate it on HLS switching?

**Comment by kslimani** [comment]
@waster i think you can avoid Clappr to download twice the swf file if vast plugin does not use Clappr to display video advert. If you want Clappr to also display the video ad, it will be difficult to avoid the double download unless, for example, you extends the current FlashHLS playback to create your own playback plugin to change internal mechanims. (_just a thought_)

I am not sure if it worth the efforts. All advertising publisher/SDK are moving away from Flash, which will be soon deprecated. (for example, see [DFP](https://support.google.com/dfp_premium/answer/7294932?hl=en)).

I suspect also that Flash will be soon blocked by browsers. (_but i may be wrong !_).

All most recent desktop & mobile browsers can handle HLS source using hls.js playback (_except IE11 on windows 7 which still use Flash HLS_).

I did not deeply test FlashHLS playback so i can't give you a proper answer until i have performed some tests which should happen next week.

**Comment by waster** [comment]
@kslimani sure, I understand about Flash, but unfortunately it is the only way to play HLS in IE11 now. Not sure I understand about double swf download, I mean that swf file is downloaded twice each time flashls playback is used on load() method. I guess it is related to DOM changes in render() method in `src/playbacks/base_flash_playback/base_flash_playback.js` file?

**Comment by kslimani** [comment]
@waster so far my tests are pointing out that it may be a IE11 "sandbox" security issue.

Context :

* Test are run on Windows 7 with Internet explorer 11.0.9600.18665
* With an HLS source (_will resolve to FlashHLS playback_)
* By Clappr files, i mean all files in "dist" folder

First results :

When i load Clappr files from an external domain, (_ie: cdn.jsdelivr.net_) then when 304 happen on swf file the player crash. (_technically the javascript execution seems to fail on Flash object_).

But if i load Clappr files from the same domain/server than the page, if 304 happen, then player is working as expected. (_this is why i suspect a security error_)

So you may want to try to serve Clappr files on your application domain to attempt to resolve HTTP 304 issue.

Here the code i used to test on IE11 (_based on your test page_) :

```html
<html>
  <head>
    <title>My App</title>
    <style>
      .player {
        width: 320px;
        height: 240px;
        overflow: hidden;
        background-color: lightyellow;
      }
      .buttons {
        width:  640px;
      }
    </style>
  </head>
  <body>
    <div class="app">
        <div class="player"></div>
        <div class="buttons">
          <button class="bt-play">play</button>
          <button class="bt-stop">stop</button>
        </div>
    </div>
    <!-- <script type="text/javascript" src="http://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script> -->
    <script type="text/javascript" src="dist-master/clappr.min.js"></script>
    <script>
      // Note: if window.$ is undefined, it is filled with Clappr.$ (Zepto), otherwise is left unchanged
      function conf(src) {
        return {
          parent: '.player',
          width: '100%',
          height: '100%',
          audioOnly: true,
          autoPlay: !Clappr.Browser.isMobile,
          startFromLevel: 1,
          hlsjsConfig: {
            xhrSetup: function(xhr, url) {
              xhr.withCredentials = true;
            },
          },
          playbackConfig: {
            crossorigin: 'use-credentials',
          },
          source: src,
        };
      };

      var player, radio = 'http://hls-01-radio7.emgsound.ru/13/playlist.m3u8';

      $('.bt-play').on('click', function(e){
        if (player) {
          player.stop();
          player.load(radio);
        } else {
          player = new Clappr.Player(conf(radio));
        }
      });

      $('.bt-stop').on('click', function(e){
        player && player.stop();
      });
    </script>
  </body>
</html>
```

PS: i did not check yet about the double swf load issue (_but it may be something related to tag construction attributes and parameters_).

**Comment by kslimani** [comment]
@waster : double download should be fixed with #1423

**Comment by kslimani** [comment]
@waster : i confirm that serving Clappr assets on same domain fix the Flash HLS .swf HTTP 304 issue with IE11.

**Comment by waster** [comment]
@kslimani so the only one possible solution now is to serve Clappr assets on the same domain?

**Comment by kslimani** [comment]
@waster i see no other option at the moment. (_At least it solve the problem_).
