### ISSUE TITLE
Create two playbacks and switch between them

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1416]
@leandromoreira In https://github.com/clappr/clappr/issues/1244#issuecomment-269360989 you mentioned that it is possible to create two playbacks and switch between them in clappr plugin. Can you please add some small example how to do that? 

In our case we need to minimize time gap between switching html5 playback (mp3 preroll ad) and flashls playback in IE11 as this is very annoying for some users. In some cases it can be up to 3-4 seconds. 

If I understand right creating two playbacks can help in this case? Or please correct me if I'm wrong..8)

**Comment by leandromoreira** [comment]
@towerz and I are planning to release a better solution to this pattern of the problem but I'll ask if @towerz has a small plugin with this behavior !! :D

**Comment by waster** [comment]
@leandromoreira great, very much waiting for this fix, because right now we're using not very elegant way with additional player to play preroll, then unmute other player with source on ad ended.

**Comment by kslimani** [comment]
@waster : if you target desktop only browsers, then you should be able to achieve this using a Core or UI Core plugin. (_but note this may not work on mobile devices._) You can take a loot at [Chromecast plugin](https://github.com/clappr/clappr-chromecast-plugin/blob/master/src/chromecast.js) source code for a playback switch example.

**Comment by waster** [comment]
@kslimani , thanks, will definetely check this plugin for code examples.
