### ISSUE TITLE
Unable to Intercept xhr on IOS

### ISSUE THREAD

**Issue by UnitedPeace** [clappr/clappr#1418]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Safari, Chrome IOS

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
IOS

**Clappr Version**: 0.2.25
latest / 0.2.66

I'm unable to intercept xhr data on ios devices, all desktop browsers work. I tried two methods, both failed.

```
(function (open) {
    XMLHttpRequest.prototype.open = function (method, url, async, user, pass) {
		alert("test");
    open.call(this, method, url, async, user, pass);
    };
})(XMLHttpRequest.prototype.open);

var player = new Clappr.Player({
  source: "http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8",
  parentId: "#sportsstream",
  autoPlay: false,
  hlsjsConfig: {
    xhrSetup: function(xhr, url) {
		alert("test2");
    }
  }
});
```

**Comment by leandromoreira** [comment]
@UnitedPeace I think we're using native video tag on ios, which doesn't provide such thing. You can force the IOSto use hls.js though.
```javascript
{plugins: [Clappr.HLS]}
```

**Comment by UnitedPeace** [comment]
@leandromoreira Playback override does not work on ios, it still uses native html5 video tag.

**Comment by leandromoreira** [comment]
yeah, @clappr/core were discussing this a long time ago I don't remember why we decided to don't let this options ;/

Anyway, @UnitedPeace can you build your version of clappr forcing it to use hls as the main playback and see if this solves your problem?

And we can decide how can we enable people to force the usage of hls instead of native html5, beyond ios there are some android devices which would benefit from this.

**Comment by UnitedPeace** [comment]
@leandromoreira I'm having trouble getting it to use HLS, when I attempt to force it on IOS it gives "Your browser does not support the playback of this video. Please try using a different browser".

**Comment by bikegriffith** [comment]
hls.js cannot work on iOS because it does not support MSE.  Your only option for hls playback on the web in iOS right now is native `<video>`.

**Comment by kslimani** [comment]
@bikegriffith is correct. You can check the [browser compatibility list](https://github.com/video-dev/hls.js#compatibility).

**Comment by UnitedPeace** [comment]
Are there any other methods that can be used to intercept url data from the m3u8 files and dynamically change it on ios browser?

**Comment by kslimani** [comment]
Could you describe what you want to achieve ?

**Comment by bikegriffith** [comment]
If you do require altering m3u8s on the fly, you might have to not play the video at all on iOS web browser ... instead build a custom native app and direct user to open that app when on iOS.  You're going to be very limited in what's possible because iOS Safari does not (and has no immediate plan) to support either MSE or ServiceWorkers.

**Comment by UnitedPeace** [comment]
@kslimani I'm attempting to dynamically change m3u8 data client side without querying the server so much. I can do this intercepting XMLHttpRequest requests on desktop browsers but native ios html5 video does not use XMLHttpRequest requests.

**Comment by kslimani** [comment]
I'm afraid @bikegriffith is right about Safari on iOS devices. For m3u8 on-the-fly modifications you may also consider doing that server-side for consistency.

**Comment by cristian2395** [comment]
> @kslimani Estoy intentando cambiar dinámicamente el lado del cliente de datos m3u8 sin consultar tanto el servidor. Puedo hacer esto interceptando solicitudes XMLHttpRequest en navegadores de escritorio, pero el video html5 nativo de ios no usa solicitudes XMLHttpRequest.


Perdona, tienes alguna referencia o enlace que mencione esto, estuve buscando información sobre que el video nativo de ios no usa XMLHttpRequest.
