### ISSUE TITLE
IE 11 HLS playback not working...?

### ISSUE THREAD

**Issue by ibreakstuff93** [clappr/clappr#1421]
**Browser**: IE 11 - v11.0.96000.18349

**OS**: Windows 7

**Clappr Version**: 0.2.66

Have tried to playback HLS in IE 11 on Win 7, but get the "Your browser does not support the playback of this video. Please try using a different browser" message.

Playback is working across all other browsers / devices (including Chrome, FireFox, Safari, iOS, Android) - so is not a source stream issue. We are producing a live HLS stream using unified streaming server.

I've also tried forcing FlasHLS plugin, but this seems to make  no difference.

```
var player = new Clappr.Player({
  parentId: "#player-wrapper",
  height: 360,
  width: 640
});

player.load("http://somedomain.com/live.m3u8");
player.play();
```
Could anyone point me in the right direction to get it working?

**Comment by ipejasinovic** [comment]
Try like this:
`var player = new Clappr.Player({
  parentId: "#player-wrapper",
  height: 360,
  width: 640,
  plugins: [Clappr.FlasHLS]
});

player.load("http://somedomain.com/live.m3u8");
player.play();`

**Comment by ibreakstuff93** [comment]
@ipejasinovic sadly, that doesn't work either...

IE:
![clapprie](https://cloud.githubusercontent.com/assets/16917874/26352250/ddcb58e6-3fb2-11e7-900d-456064084e70.png)

Chrome:
![clapprchrome](https://cloud.githubusercontent.com/assets/16917874/26352317/22d03df8-3fb3-11e7-8deb-c7bc4c53de9a.PNG)

**Comment by leandromoreira** [comment]
@ibreakstuff93 did you check if you do have flash installed for ie? Maybe it's missing flash.

**Comment by kslimani** [comment]
@ipejasinovic can you try ? :
(_second optional argument is mimetype and third optional argument is autoplay_) 
```javascript
player.load("http://somedomain.com/live.m3u8", null, true);
```

**Comment by ibreakstuff93** [comment]
@leandromoreira 👍 I had an older version of flash, but now running the latest I get the player load up properly! Should have checked this first, sorry! ( 👎  for me!)

The issue I have now is, there is audio playback, but just a black playback (no pictures).

This is what seems to get me to the point of having a play button:

```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
source: "http://somewhere.com/live.m3u8",
mimeType: "application/vnd.apple.mpegurl",
height: 360,
width: 640,
plugins: [Clappr.FlasHLS]
});

player.attachTo(playerElement);
```
This gives me the following output:

![clappr ie old 2](https://cloud.githubusercontent.com/assets/16917874/26355606/3851e146-3fc1-11e7-8abd-522997439caa.png)

**Comment by leandromoreira** [comment]
This might be an issue with your stream, try to replicate the same problem with this source http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8

**Comment by ibreakstuff93** [comment]
I just tried it with that playlist, and I'm getting the same result as with my stream...

Audio = 👍 
Video = 👎

**Comment by kslimani** [comment]
@ibreakstuff93  If you are using latest release, try to remove `plugins: [Clappr.FlasHLS]` from configuration as it should be automatically loaded (_since hlsjs playback not supported with IE11_).

**Comment by ibreakstuff93** [comment]
thanks @kslimani - i've given it a try with / without declaring the plugin explicitly, and you're right, it will detect if it needs the plugin or not which is super! 💃 

The console log might perhaps help? there's a close, followed by setting up the audio track. Could the close be on the video?

![flashlsconsole](https://cloud.githubusercontent.com/assets/16917874/26395109/047322f8-4067-11e7-83d7-3e663f46f3b6.PNG)

**Comment by kslimani** [comment]
@ibreakstuff93 does the following code work on [demo page](http://clappr.io/demo/) :

(_replace javascript code by this one and click the "run" button_)
```javascript
var player = new Clappr.Player({
  parent: '#player-wrapper',
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  height: 360,
  width: 640,
  autoPlay: true,
});
```

**Comment by ibreakstuff93** [comment]
@kslimani still the same audio yes, but black playback, with the bar appearing if I hover over the area. 

I've checked my flash version, i'm using the latest: 25.0.0.171. And i've also done a few windows updates, so IE is now 11.0.9600.18665. It's absolutely fine on Win  8 & Win 10, just Win 7 for some unknown reason :(

**Comment by kslimani** [comment]
@ibreakstuff93 i think this is not a Clappr issue. In fact i suspect a Windows video driver problem.

Can you try the following  : right click on middle of player (_this should open a context menu with Flash plugin option choices_), then click on "parameters..." and disable hardware acceleration.

It this fix your issue, i suggest you to attempt to update your video card drivers.
