### ISSUE TITLE
Playback not switching from FlasHLS to another playback mode if not allowed by user

### ISSUE THREAD

**Issue by Eetin** [clappr/clappr#1424]
**Browser**: Safari 10.1.1 (12603.2.4)

**OS**: Mac OS 10.12.5

**Clappr Version**: 0.2.64

**Steps to reproduce**:

* Turn on plugins In security settings
* Turn on Adobe Flash Player in plugin settings
* Make flash ask for permission to use
* Open web page with clappr player with enabled FlasHLS playback plugin
* NOT allow using Adobe Flash Player
* I was expecting clappr to switch to another playback mode but it didn't and if you click play button nothing happens.

I tried it at http://cdn.clappr.io/ and results are the same. Just give it m3u8 playlist and enable FlasHLS playback plugin.

**Comment by kslimani** [comment]
@Eetin when Clappr resolve the playback to load according source provided, if Flash HLS playback is prioritiezd, then Javascript code will attempt to detect if Flash plugin is installed. I am not sure if it is possible in javascript to detect if user consented or not to run the plugin.

BTW, why would you want Clappr to use Flash HLS playback on Safari ?

Please note that latest Clappr release now use HLS.JS playback with Safari browser (_over native html5 video_). I recommend to upgrade Clappr to latest and retry without force FlashHLS playback plugins.

**Comment by Eetin** [comment]
@kslimani we used Flash HLS on Safari because of DVR issue on html5 playback.
I checked the latest version without Flash HLS plugin and everything works now.
Thank you.
