### ISSUE TITLE
Source load timeout 

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1426]
Hello, 

Can you please me advice is it possible to use some timeout handling on load() in Clappr?  For example handle some bad URL with mp3 that can not be downloaded while trying to connect and log some message about timeout passed?

Code example on http://clappr.io/demo/:
```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io:1234/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

**Comment by kslimani** [comment]
Did you try the `onError` player event ?
(_please note that html5 video load timeout is something like 20 seconds, dunno if it can be configured_)

```javascript
var player = new Clappr.Player({
  parent: '#player-wrapper',
  source: 'http://clappr.io:1234/highline.mp4',
  height: 360,
  width: 640,
  events: {
    onError: function(e) {
      // Here the code to handle the error
      console.log('bigbadaboom !', e);
    }
  },
  autoPlay: true,
});
```

**Comment by kslimani** [comment]
@waster  only way i know is to use "watchdog" timer approach.
