### ISSUE TITLE
Add a button

### ISSUE THREAD

**Issue by eseffair** [clappr/clappr#1428]
How can I add a button to the player?

**Comment by kslimani** [comment]
@eseffair you can add a button to player, for example, using an `UIContainerPlugin` or an `UICorePlugin `.

* [Here](https://github.com/clappr/clappr/blob/master/src/plugins/watermark/watermark.js) an example of `UIContainerPlugin`.
* [Here](https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js) an example of `UICorePlugin `.
