### ISSUE TITLE
How to open streams (master.m3u8) to 1080p by default?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1429]
I have noticed that MX Player for Android uses the best quality for the M3U8 streams just opening the player (in a range of 240p, 480p, 720p, 1080p)
However with Clappr, the quality increases slowly until it reach the highest level.
Is there any way to set Clappr to the highest level by default? (1080p)

**Comment by kslimani** [comment]
@hijuuijj if .m3u8 source is using HLSJS playback, you can control quality switch using [Quality switch Control API](https://github.com/video-dev/hls.js/blob/master/doc/API.md#quality-switch-control-api).

Also, you can pass HLSJS custom options in player constructor, for example :

```javascript
var player = new Clappr.Player({
  parentId: "#player-wrapper",
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  height: 360,
  width: 640,
  playback: {
    hlsjsConfig: {
      // Here HLSJS options
    }
  }
});
```

If browser is using native video to play .m3u8 source, i don't know if there is a way to control quality switch. (_for example, iOS mobile device_).
