### ISSUE TITLE
WebVTT support

### ISSUE THREAD

**Issue by alexandrevicenzi** [clappr/clappr#1435]
**Browser**: Any

**OS**: Any

**Clappr Version**: 0.2.25

**Steps to reproduce**:

* Try to load a playlist (m3u8) with subtitles

I couldn't find anywhere how to change the current subtitle track on Clappr, neither how to disable it. By default, it's loading English subtitle.

I found a [plugin](https://github.com/PreDeToR/clappr-audio-track-selector-plugin) to switch audio track, is there anything similar for subtitles? or is there any plans to support these features on Clappr without any other plugin.

Here is a good [playlist](https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8) to test. This playlist has 4 audio tracks and 4 subtitles track.

This is related with #626.

**Comment by kslimani** [comment]
You are correct @alexandrevicenzi i was able to reproduce this bug.

I proposed a fix for at least be able to enable/disable CC. The default subtitle is selected by hls.js (_English is default_). It seems there is no api/configurations options to change this yet. (_i may be wrong!_)

BTW thank you for the playlist, it helped me a lot !

**Comment by alexandrevicenzi** [comment]
@kslimani I think hls.js doesn't have this option. Testing in [https://video-dev.github.io/hls.js/demo/](https://video-dev.github.io/hls.js/demo/) there's only options to toggle audio and quality, the CC is part of video component I think.

**Comment by kslimani** [comment]
@alexandrevicenzi yes, i think too that the switch mechanisms should work directly with video element as hls.js is listening it and is aware of subtitle switch. I will take a look at switch audio plugin to see if i can do something for CC.

**Comment by kslimani** [comment]
@alexandrevicenzi i updated #1440 which should now properly handle multiple CC tracks. Could you please test if these changes satisfy your issue ?
