### ISSUE TITLE
Clappr does not play mkv (matroska) container

### ISSUE THREAD

**Issue by Abdel-ilah** [clappr/clappr#1436]
hi,
someone correct this code for me to play .mkv files please?

<div id="player"></div>
<script>
var player = new Clappr.Player({
  source:  {
    source: 'http://dl2.mihanpix.com/Film/2016/Allegiant.2016.720p.ShAaNiG.mkv',
    mimeType: 'video/x-matroska'
  },
autoPlay:'true',
parentId: '#player',
});
</script>

other examples please??
thank you.

**Comment by leandromoreira** [comment]
@Abdel-ilah I think we don't support mkv container =( if you can, you can convert it to `mp4` using ffmpeg.

**Comment by kslimani** [comment]
@Abdel-ilah : try the following code on [Clappr demo](http://clappr.io/demo/) page with __Google Chrome browser__ :

_(please note i did not test the code and it may not work)_

```javascript
var MkvPlayback = Clappr.HTML5Video.extend({
  name: 'mkv_video',
});
MkvPlayback.canPlay = function(resourceUrl, mimeType) { return true; };

var player = new Clappr.Player({
  parentId: '#player-wrapper',
  source: 'http://dl2.mihanpix.com/Film/2016/Allegiant.2016.720p.ShAaNiG.mkv',
  plugins: [MkvPlayback],
  height: 360,
  width: 640,
  events: {
    onError: function (e) {
      console.log('Error !', e);
    }
  },
});
```

**Comment by Abdel-ilah** [comment]
thanks leandromoreira, kslimani

**Comment by ewwink** [comment]
for chrome you only need to add option `mimeType: "video/mp4",` but it not work in firefox maybe you should try add plugin Flashls.
