### ISSUE TITLE
Safari Mobile check doesn't work inside WKWebView

### ISSUE THREAD

**Issue by bikegriffith** [clappr/clappr#1438]
**Browser**: WKWebView

**OS**: iOS 10

**Clappr Version**: 0.2.25

**Steps to reproduce**:

* Load player
* Observe that volume control is displayed and non-functional.  Should be hidden.

See lines of code that are not working at:
* https://github.com/clappr/clappr/blob/master/src/components/media_control/media_control.js#L690
* https://github.com/clappr/clappr/blob/master/src/components/browser.js#L56
* https://github.com/clappr/clappr/blob/master/src/components/browser.js#L62

**Comment by bikegriffith** [comment]
I'm assuming this should be a "wontfix" because it's due to the non-standard user agent in WKWebView (which technically could be overridden to work around the issue).  The only real option would be to find some better way of detecting the volume change capability without resorting to user agent snipping.  But was curious if anyone else had thoughts.

**Comment by kslimani** [comment]
@bikegriffith i think this is because this browser may be detected as Safari. (_as your links suggested_).

Could you please post the value of userAgent for this browser, maybe the regex for isSafari can be fixed.

**Comment by bikegriffith** [comment]
Default WKWebView user-agent is something like `{AppName}/73 CFNetwork/808 Darwin/16.0.0`.  It can be overridden, however, by the app. I don't think this is worth going down a regex change for Safari detection.  Closing.
