### ISSUE TITLE
display hls latency

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1439]
hi

I would like to display hls latency (console or not)
I found to get that it needs to retrieve EXT-X-PROGRAM-DATE-TIME in the manifest
It exists in hls.js 

hls.on(Hls.Events.FRAG_CHANGED,function(event,data) {
  console.log('current dateTime' + data.frag.programDateTime);
}

so how to integrate it in clappr ?
after there is a small calculation to get latency with playback fragment UTC time backend

if you have an idea to get final result, that would be great

thanks

**Comment by kslimani** [comment]
@Niko78 you can see a simple example [here](https://github.com/clappr/clappr/issues/1300#issuecomment-280971418) on how to bind hls.js playback events.

**Comment by Niko78** [comment]
merci je vais tester ;-)

**Comment by leandromoreira** [comment]
@Niko78 I think if you want to have the latency between the source and the final user you could take the PTS/DTS from the source and compare with final user, or if you want just a rough idea you can [overlay the clock over the video](https://stackoverflow.com/a/12244369/1188680) and compare.

**Comment by Niko78** [comment]
thanks @leandromoreira but I'm not a developer that's why I ask how to

**Comment by leandromoreira** [comment]
@Niko78 one easy way is to really have a clock overlay on the video and check source vs final user (player)!
