### ISSUE TITLE
PAUSE event is fired after play finished

### ISSUE THREAD

**Issue by waster** [clappr/clappr#1441]
**Browser**: FF 53

**OS**: Ubuntu 17.04

**Clappr Version**: cdn.clappr.io

**Steps to reproduce**:

* Try this code on cdn.clappr.io:
```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.on(Clappr.Events.PLAYER_PAUSE, function() { console.log("PAUSE!") });
player.attachTo(playerElement);
player.play();
```
* Wait video to finish playing.
* "PAUSE!" appears in console.

Not sure this is expected behaviour because in case of VAST plugin it can be unnecessary while using  Events.PLAYBACK_PAUSE and ![vastTracker.setPaused()](https://github.com/dailymotion/vast-client-js/blob/master/docs/api.md) to send pause event for example.

Regards, Andrey.

**Comment by kslimani** [comment]
@waster i think this is the behaviour of html5 video element.
(_the html5_video playback just listen to video element events and propagate them to container_).

In you case, you may want to filter pause event using, for example, this workaround :

```javascript
var player = new Clappr.Player({
  parentId: '#player-wrapper',
  source: 'http://clappr.io/highline.mp4',
  height: 360,
  width: 640,
  events: {
    onPause: function (e) {
      var trunc = function (n) { return parseInt(n, 10); };
      var container = this.core.getCurrentContainer();
      var isLive = container.getPlaybackType() === Clappr.Playback.LIVE;
      var duration = isLive ? 0 : container.getDuration();
      var position = container.getCurrentTime();
      var isEnd = trunc(duration) === trunc(position);
      
      if (!isLive && isEnd) return;
      console.log('PAUSE!');
    }
  },
});
```
