### ISSUE TITLE
Memory usage w/ multiple Clappr Players (HLS)

### ISSUE THREAD

**Issue by andrefilipegsilva** [clappr/clappr#1446]
**Browser**: Chrome 58.0.3029.110

**OS**: Windows 10 v1703

**Clappr Version**: 0.2.27

Hi guys,

I've been currently using Clappr to build a video wall, in which will be displayed CCTV streams in HLS format. There will be at maximum 9 streams displayed, which may come from the same source or from a different one.

My problem is that apparently having 9 displayed streams is eating all browser memory, reaching > 1.5GB over time, slowing down the performance of the site and ultimately causing it to crash. I've tried to use the `maxBufferLength` property, setting it to 5 seconds, but I've had no luck in solving the problem so far.

Can anyone provide any feedback regarding a possible solution?

Thanks.

**Comment by kslimani** [comment]
@andrefilipegsilva you may consider directly using hls.js library for this project handling your 9 html5 video elements to reduce as much as possible the memory requirements ?

**Comment by andrefilipegsilva** [comment]
@kslimani It's possible but I've adapted my code to work with Clappr...

I'm hoping for a solution within Clappr but if there isn't any, I will follow your suggestion...

**Comment by bikegriffith** [comment]
@andrefilipegsilva I'd encourage you to review the hls.js config options very carefully.  `maxBufferLength`/`maxBufferSize` are more of suggestions than real limits.  You can use [maxMaxBufferLength](https://github.com/video-dev/hls.js/blob/master/doc/API.md#maxmaxbufferlength) if necessary to cap.

You might also try to limit the resolution/bitrate of each by specifying the `currentLevel` of the hls.js playback if each rendered stream in your grid is smaller (`capLevelToPlayerSize` is a more algorithmic approach to this same thing).

In reality though, 1.5GB is (sadly) pretty reasonable to play back 9 streams at the same time in Chrome.  Did you think about (a) using Edge to play back hls natively or (b) increasing the memory on the computer?

**Comment by leandromoreira** [comment]
How did you set `maxBufferLength` @andrefilipegsilva  ?

**Comment by andrefilipegsilva** [comment]
@bikegriffith The thing is that it only reaches such amount of memory usage over time, i.e. 5-10-15 minutes. It is mandatory that my project runs across different browsers, so Edge alone is not an option. Increasing memory is a possibility but I'm trying to solve this issue in a programmatic way rather than in a physical one.

I'm gonna try to use the flags you specified and then I'll share the results.

@leandromoreira I've set the flag either like this:
```javascript
self.player = new Clappr.Player({
            source: self.hlsAddress(),
            poster: 'http://clappr.io/poster.png',
            mute: true,
            width: '100%',
            height: '100%',
            disableKeyboardShortcuts: true,
            hideVolumeBar: true,
            maxBufferLength: 5,
            hlsjsConfig: {
                maxBufferLength: 5
            }
```

**Comment by bikegriffith** [comment]
@andrefilipegsilva You need to nest `hlsjsConfig` inside a `playback` dictionary, e.g.:

```
self.player = new Clappr.Player({
            source: self.hlsAddress(),
            poster: 'http://clappr.io/poster.png',
            mute: true,
            width: '100%',
            height: '100%',
            disableKeyboardShortcuts: true,
            hideVolumeBar: true,
            playback: {
                hlsjsConfig: {
                    maxBufferLength: 5
                }
            }
```

**Comment by andrefilipegsilva** [comment]
@bikegriffith I've set the `hlsjsConfig` debug property to true without nesting the `hlsjsConfig` inside the playback and it worked... Is it different for the `maxBufferLength` property?

**Comment by kslimani** [comment]
@andrefilipegsilva it worked because of "legacy" reason.

For consistency, i recommend using
```javascript
playback: {hlsjsConfig:{ /* hls.js constructor options here */ }}
```
like @bikegriffith suggested.

(_For more details, see [this part](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L144) of HLS playback_)

**Comment by kslimani** [comment]
BTW, i see lot of people which require to customize hls.js instance with Clappr player. Maybe it would be a nice feature to introduce, for example, an advanced "before attach media" playback event which allow developer to manipulate hls instance before call attachMedia method ?

**Comment by andrefilipegsilva** [comment]
Even while setting correctly the `hlsjsConfig` dictionary within the `playback` with the options `maxBufferLength: 5` and `maxMaxBufferLength: 5` it escalates to over 1.5 GB. Any other ideas? I'm kinda stuck...

**Comment by kslimani** [comment]
@andrefilipegsilva maybe you could attempt to either use .mp4 sources or directly test with hls.js to determine if the memory (possible leak ?) comes from Clappr or from hls.js. (_because if memory issues comes from Clappr then tuning hls.js will change nothing, or the inverse will point us to the right direction for additional help_)

**Comment by andrefilipegsilva** [comment]
I'm gonna switch to 'pure' hls.js and I'll come back with results.

Thanks!

**Comment by andrefilipegsilva** [comment]
I've implemented pure hls.js and the results were better (as expected because there's no additional overhead), but the memory still rises overtime (around 15-20 minutes of spectating) to ~ 1GB and up, and it doesn't stop nor decrease significantly.

I've configured HLS with these parameters:

```javascript
var config = {
            capLevelToPlayerSize: true,
            maxBufferSize: 30,
            maxBufferLength: 5
        };
        self.hls = new Hls(config);
```
If you think this is somewhat unrelated to this project I can also ask this question on hls.js forum...

Thanks,

**Comment by kslimani** [comment]
Well it seems there is [several issues open](https://github.com/video-dev/hls.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20leak) at hls.js about memory leak, but it is hard to say if it is related to your problem.

Debug such issue may be hard. One opened issue suggest to use [this technic](https://stackoverflow.com/a/19726918/2774845) to spot the problem. Maybe you could have a try and attempt report to [hls.js](https://github.com/video-dev/hls.js) repository.

**Comment by leandromoreira** [comment]
It's likely to be something on hls.js based on your tests, so I'll label this as wontfix. Thanks
