### ISSUE TITLE
http auth

### ISSUE THREAD

**Issue by alexvasiliev** [clappr/clappr#1447]
is it possible to request hls with basic http auth?
i've tried source url like 
"http://login:password@blah/playlist.m3u8" but clappr made request like "http://blah/playlist.m3u8" with no http auth header

**Comment by leandromoreira** [comment]
@alexvasiliev does it raises any error on console log? can you try to do the same using this url http://video-dev.github.io/hls.js/demo/ ?

**Comment by alexvasiliev** [comment]
Yes, it raises 2 error:

1) GET http://blah/playlist.m3u8 401 (Unauthorized)
2) XMLHttpRequest cannot load http://blah/playlist.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://blah' is therefore not allowed access. The response had HTTP status code 401.

full stream from wireshark:
GET /blah/playlist.m3u8 HTTP/1.1
Host: blah
Connection: keep-alive
Origin: http://blah
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36
Accept: */*
DNT: 1
Referer: http://blah/index.html
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4

HTTP/1.1 401 Unauthorized
Connection: Close
WWW-Authenticate: Basic realm="AxxonNext"

same problems on [http://video-dev.github.io/hls.js/demo/](url)

**Comment by alexvasiliev** [comment]
how can i add http auth header to clappr hls request?

**Comment by kslimani** [comment]
@alexvasiliev you may needs to setup your own custom loader. Please refer to [https://github.com/video-dev/hls.js/blob/master/doc/API.md#xhrsetup](https://github.com/video-dev/hls.js/blob/master/doc/API.md#xhrsetup).

You can maybe also use fetch api  : [https://github.com/video-dev/hls.js/blob/master/doc/API.md#fetchsetup](https://github.com/video-dev/hls.js/blob/master/doc/API.md#fetchsetup)

**Comment by leandromoreira** [comment]
About the  `No 'Access-Control-Allow-Origin' ` you can [setup it correctly](https://github.com/clappr/clappr/issues/703).

**Comment by alexvasiliev** [comment]
done by custom loader.
quick solution with config for base http auth:
https://pastebin.com/iN8Gi9Fj

**Comment by alexvasiliev** [comment]
ty for quick answer

**Comment by IkiaeM** [comment]
> done by custom loader.
> quick solution with config for base http auth:
> https://pastebin.com/iN8Gi9Fj

I would like to know the syntax to add what is in the pastebin

hlsjsConfig:
{
    xhrSetup: function(xhr, url) {
        var result = url.match( /^http\:\/\/((.+)\:(.+)@)?.+/i );
        if(result.length > 3)
        {
            let login = result[2]
            let password = result[3]
            xhr.withCredentials = true;
            xhr.open("GET", url, true, login, password);
        }
    }
}

Because I can't get it to work on http://clappr.io/demo/
