### ISSUE TITLE
Change player source

### ISSUE THREAD

**Issue by caspermouse** [clappr/clappr#1453]
Hello, i have one question for you. Is that possible to change params one defined clappr player with ng-click directives which contains url address, image etc of differents video? If it is, how could I do it.

Thanks for any advice.

**Comment by kslimani** [comment]
@caspermouse why not using onclick event instead of Angular ng-click ?

**Comment by caspermouse** [comment]
I use ng-click because complete project is in Angular. If i use onclick event i still don't know how to change params. Do you have any advice?

**Comment by kslimani** [comment]
It should be possible with angulag to run javascript code (in the scope of controller?) to manipulate a Clappr instance. What exactly are you trying to achieve ? (_i am not an expert of Angular_)

**Comment by caspermouse** [comment]
Yes, it is possible. I create instance of clarpp player and thats work well. But when i try to forward another params in that player, on second click, he still shows me player with first source information.

**Comment by kslimani** [comment]
You can change player options using the `configure()` method without destroying player instance.

For example : 

```javascript
// Assume player instance is already created
player.configure({
  source: '/path/to/another/file.mp4',
  // [...]
});
```

**Comment by caspermouse** [comment]
@kslimani Thanks for advice
