### ISSUE TITLE
Resize event in Core Plugin

### ISSUE THREAD

**Issue by andrefilimono** [clappr/clappr#1454]
Hi!
Can I receive a **RESIZE** event in **Core Plugin**? 
As I see in documentation it is possible to receive only a **FULLSCREEN** event, but it does not works in iOS.

**Comment by kslimani** [comment]
@andrefilimono by "resize", do you mean player resize or window resize ?

There is also a `Events.CORE_SCREEN_ORIENTATION_CHANGED` available on mobile devices.

**Comment by andrefilimono** [comment]
@kslimani I mean player resize. I want to get new player size (width, height) when player enters into full screen (out of full screen) or on orientation change.

**Comment by kslimani** [comment]
@andrefilimono you should be able to bind current player instance resize event using this trick :

```javascript
import {CorePlugin, Events, Mediator} from 'clappr'

export default class MyPlugin extends CorePlugin {
  get name() { return 'my_plugin' }

  constructor(core) {
    super(core)
  }

  bindEvents() {
    Mediator.on(`${this.options.playerId}:${Events.PLAYER_RESIZE}`, this.playerResize)
  }

  playerResize(newSize) {
    console.log('playerResize', newSize)
  }
}
```

**Comment by andrefilimono** [comment]
Thanks, it works good!

**Comment by Bubblesphere** [comment]
@kslimani How is this done in 2020? `Mediator` does not exists

**Comment by kslimani** [comment]
@Bubblesphere 

Simply listen to core resize event in bindEvents() method. For example :

```javascript
// [...]
  bindEvents() {
    this.listenTo(this.core, Events.CORE_RESIZE, (evt) => {
      // do something with evt.width and evt.height (if > 0)
    })
  }
// [...]
```
