### ISSUE TITLE
Javascript error on FireFox prevents loading player

### ISSUE THREAD

**Issue by Support-Vezca** [clappr/clappr#1457]
**Browser**: FireFox 54.0.1 (64-bit)
**OS**: Windows 10
Clappr version as of 07 July 2017 via https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

[error][MediaControl] error on event mediacontrol:hide trigger - TypeError: this.getCurrentContainer(...) is undefined
Stack trace:
O</e.prototype.onMediaControlShow@https://cdn.jsdelivr.net/clappr/latest/clappr.min.js:1:99569
i@https://cdn.jsdelivr.net/clappr/latest/clappr.min.js:1:1600
p@https://cdn.jsdelivr.net/clappr/latest/clappr.min.js:1:1957
g</t.prototype.trigger@https://cdn.jsdelivr.net/clappr/latest/clappr.min.js:1:3160
q</e.prototype.hide@https://cdn.jsdelivr.net/clappr/latest/clappr.min.js:1:118285
q</e.prototype.render/this.hideId<@https://cdn.jsdelivr.net/clappr/latest/clappr.min.js:1:123642

No issues whatsoever on Chrome, Opera, Edge, Android Chrome, IOS.

**Comment by kslimani** [comment]
@Support-Vezca can you reproduce the error on http://clappr.io/demo/ ?
(_or in the contrary, can you provide a demo page which reproduce the error ?_)

**Comment by Support-Vezca** [comment]
@kslimani everything A+ on the demo page. I recently wrapped the iframe with a jquery fadein script in order to show a spinner until the actual iframe page loads (a html page with its own isolated clappr)... now although one would think this should not impact the iframe page as the fade logic is outside of the iframe html page, but it appears it does have an impact on clappr. I just removed the logic and everything is fine.

This is the code I added for the iframe:

` var theIframe = document.getElementById('v_' + assetid);
        if (navigator.userAgent.indexOf("MSIE") > -1 && !window.opera) {
            theIframe.onreadystatechange = function () {
                if (theIframe.readyState == "complete") {
                    //$("#vcHolder").remove();
                    $("#vcHolder").fadeOut(1000, function () { $(".vGlow_" + assetid).fadeIn(1000, function () { $("#vcHolder").remove() }); });
                }
            };
        } else {
            theIframe.onload = function () {
                $("#vcHolder").fadeOut(1000, function () { $(".vGlow_" + assetid).fadeIn(1000, function () { $("#vcHolder").remove() }); });
            };
        }`

The iframe is inside a div called 'vGlow', the div's inline style is set to 'display:none'... and of course the above code fades in that div once the iframe state changes to 'complete'.

Thus, it appears that on FireFox, if clappr is in an iframe which is inside a div which is set to 'display:none', the clappr javascript in the iframe page is unable to reference the div container on the page... ooo errrr??!

But none of this is an issue on other browsers, just FireFox it appears.

I'm going to quickly try something else, rather than the iframe parent div being set to display:none, I'll set it to visibility:hidden, and see if that makes a difference on FireFox.

If you have any opinions on any of the above, I'm all ears bud.

**Comment by Support-Vezca** [comment]
Ok, it works with visibility:hidden.

From the look of things, this appears to be an issue with how Firefox instantiates references to elements, ie if they are set to inline style of display:none at load then things go all pear shaped? or is Firefox following standards stringently and all the other browsers are being a little bit more flexible? no idea, but at least its all working.

Many thumbs up for Clappr, it really is an incredible feat of code for the massses without having to pay for commercial HLS/DASH player licenses.

**Comment by kslimani** [comment]
A possible workaround may be to set width and height of the i-frame to 0x0 or 1x1 pixel while loading, and then properly resize it when loaded. (_instead of not display_)
