### ISSUE TITLE
Play Stream https Wowza

### ISSUE THREAD

**Issue by ciclanoio** [clappr/clappr#1458]
Is it possible to run secure streaming over https?
When playing secure URL from HLS Streaming the video does not run on Clappr, in VLC for testing purposes, work.

Thanks

**Comment by leandromoreira** [comment]
@ciclanohost yes, you should be able to play stream over https with clappr (and with almost any other player).

Can you post the streaming you're trying? Maybe you're facing [an issue with your https headers](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues), mostly [the cors](https://github.com/clappr/clappr/issues/703).

**Comment by ciclanohost** [comment]
@leandromoreira  I receive this in logs:  
Streaming URL:  https://videos.ciclano.io:1443/demovod/demovod/mp4:sample.mp4/playlist.m3u8
URL PLAYER: [](https://videos.ciclano.io/embed/demovod?m=3246cddb2fd84ca)
or here to print all logs: [](http://developer.ciclano.io/player_ciclano_hash)
[error][hlsjs: unrecoverable network fatal error, evt hlsError, data [object Object] ]

**Comment by leandromoreira** [comment]
@ciclanohost it seems that you're using https (supposed to be at `port 443`) with another port, try to stick with 443 and try it again.

> There are some networks (especially some free WiFi access points) that don't allow traffic over other ports than 443 or 80.

When I tried to get the content from the url you provided (/playlist.m3u8) it didn't work.

```bash
$ curl -I https://videos.ciclano.io:1443/demovod/demovod/mp4:sample.mp4/playlist.m3u8
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

**Comment by kslimani** [comment]
* you **can** play an https stream on an http page (_with CORS headers enabled on server_)
* you **cannot** play and http stream on an https page. (_even with CORS, most browsers will block the requests_).

**Comment by kslimani** [comment]
BTW, it is because it is either a self-signed HTTS certificate, or maybe when you configured your server ssl certificate you missed to add the chain certificate.

with curl `-k` (insecure) option flag, it return an hls manifest :

```
curl -k -v "https://videos.ciclano.io:1443/demovod/demovod/mp4:sample.mp4/playlist.m3u8"
* Hostname was NOT found in DNS cache
*   Trying 52.67.206.64...
* Connected to videos.ciclano.io (52.67.206.64) port 1443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* Server certificate:
* 	 subject: CN=*.ciclano.io
* 	 start date: 2017-01-13 00:00:00 GMT
* 	 expire date: 2018-01-13 23:59:59 GMT
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA
* 	 SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /demovod/demovod/mp4:sample.mp4/playlist.m3u8 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: videos.ciclano.io:1443
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Expose-Headers: Date, Server, Content-Type, Content-Length
* Server WowzaStreamingEngine/4.7.0 is not blacklisted
< Server: WowzaStreamingEngine/4.7.0
< Cache-Control: no-cache
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: OPTIONS, GET, POST, HEAD
< Access-Control-Allow-Headers: Content-Type, User-Agent, If-Modified-Since, Cache-Control, Range
< Date: Thu, 13 Jul 2017 14:14:26 GMT
< Content-Type: application/vnd.apple.mpegurl
< Content-Length: 136
< 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=868638,CODECS="avc1.66.21,mp4a.40.2",RESOLUTION=512x288
chunklist_w1451497397.m3u8
```

**Comment by leandromoreira** [comment]
Probably @kslimani is right!

**Comment by ciclanohost** [comment]
@kslimani  Thanks for your help. Yes CORS is enable to *

When I play the URL in an external player like VLC it works. Only when the web player does not run.
I have tested with the certificate issued by wowza and I have the same result.
I also tested on transparent port at 443.

My scenario is:

A web server with geotrust certificate at 80 and https at 443
Wowza server in 1935 and https in 1443
Both on the same IP.


I created the JKS for wowza With our certified GeoTrust as directed by Wowza below:

openssl pkcs12 -export -in ciclano_io.crt -inkey ciclano_io.key -out ciclano.p12

keytool -importkeystore -srckeystore ciclano.p12 -srcstoretype PKCS#12 -destkeystore ciclano.jks -deststoretype JKS

@leandromoreira Thanks !

I will do more tests any information that can help me to correct the problem thank you

**Comment by kslimani** [comment]
I see. You could configure the ssl certificate only on https port (443) of web server which proxy to wowza port 1935. Then you don't need to configure https on Wowza.

Here an Nginx example configuration :

```
upstream wowza {
  server 127.0.0.1:1935;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name my.domain.com;

    root /srv/www;
    index index.html;

    # adjust to your needs
    ssl_certificate /path/to/my.domain.com.crt;
    ssl_certificate_key /path/to/my.domain.com.key;

    location / {
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_read_timeout 10s;
        proxy_send_timeout 10s;
        proxy_connect_timeout 10s;
        proxy_pass http://wowza;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name my.domain.com;

    return 301 https://$host$request_uri;
}
```

**Comment by ciclanohost** [comment]
@kslimani  I rebuilt the test here using just wowza and no longer the web server, using the wowza provided certificate itself:

Page:
https://57aca11f8a004.streamlock.net:9443/tests/index.html

Stream:
https://57aca11f8a004.streamlock.net/demovod/mp4:sample.mp4/playlist.m3u8

I've noticed that if Chrome or Firefox does not work, but Safari runs Clappr.

**Comment by kslimani** [comment]
It seems you have an issue with your ssl certificate. The page is hosted on domain streamlock.net but your ssl certificate is *.ciclano.io, ciclano.io which is why it does not work.

**Comment by ciclanohost** [comment]
@kslimani 

1) I just informed that I tested with both certificates, both wowza and ours. In any of them I get the error.

2) Thank you I'll keep doing tests.
