### ISSUE TITLE
Enter/Exit Full Screen Programmatically

### ISSUE THREAD

**Issue by Craytor** [clappr/clappr#1459]
**Browser**: Safari (iOS 10)

**OS**: iOS 10

**Clappr Version**: 0.2.25

General question - is it possible to enter and exit full screen programmatically? For instance, is there a function I could run to close out of full screen or vise versa?

Something like ``` player.container.exitFullscreen() ``` - I know that isn't a function, but I'm trying to see if the functionality exists.

Thanks!

**Comment by kslimani** [comment]
@Craytor on mobile device, enter fullscreen of video must be initialized with a user action, meaning a tap or click.

The mediaControl component has a `toggleFullscreen` method. You can experiment it at [demo page](http://clappr.io/demo/) using the following code example :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

$('#player-wrapper').append(
  $('<button />')
    .text('Toggle fullscreen')
    .on('click', function(){
      player.core.mediaControl.toggleFullscreen();
    })
);
```

**Comment by Craytor** [comment]
@kslimani Perfect, thank you - exactly what I was looking for. This should be better documented IMO.
