### ISSUE TITLE
Dailymotion live?

### ISSUE THREAD

**Issue by JohnMorra** [clappr/clappr#1464]
Hi! I cant load stream from dailymotion. 
http://stream-15.dc3.dailymotion.com/47/dm/1/x2yclwl/live.isml/events(live-1499294360)/live-audio=128000-video=1260000.m3u8

Im trying with this config but player is not even loading white screen when editing in html. Any ideas?

<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js"></script>
<meta name="referrer" content="no-referrer" />
<style>body {padding:0;margin:0;}</style></body><div id="player"></div>
<script>var player = new Clappr.Player({
source: "http://stream-15.dc3.dailymotion.com/47/dm/1/x2yclwl/live.isml/events(live-1499294360)/live-audio=128000-video=1260000.m3u8",
mimeType:"application/vnd.apple.mpegurl",plugins: {'core': [LevelSelector]},parentId: "#player",
width: "650",height: "450",
autoPlay: true, 
mediacontrol: {seekbar: "red", buttons: "silver"}});
</script><script>document.addEventListener('contextmenu', event => event.preventDefault());</script>

![obraz](https://user-images.githubusercontent.com/24629005/28193291-82d60040-6833-11e7-8d99-9bdd13de6de3.png)

**Comment by leandromoreira** [comment]
what is the error?

**Comment by JohnMorra** [comment]
How i can chceck errors?

**Comment by kslimani** [comment]
This Dailymotion manifest URL is "protected", (_i will not detail how_) you probably have a 403 Forbidden error when attempting to load source.

**Comment by JohnMorra** [comment]
source is geo locked as far as i know but for different country i am staying right now.  I don't know about any protection but i used to load this stream before just know i doesn't work
