### ISSUE TITLE
How to open this Flumotion M3U8 with Clappr?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1469]
I need to open this Flumotion HLS via Clappr http://rbetis-hls.flumotion.com/rbetis/live/.m3u8
It can be opened without problems via https://www.hlsplayer.net/
It's Crossdomain's issue? do I need a special parameter?

Thanks in advance.

**Comment by leandromoreira** [comment]
@hijuuijj because the URL is returning `403 Forbidden`.

![screen shot 2017-07-17 at 8 30 54 am](https://user-images.githubusercontent.com/55913/28266274-4f6cf0b2-6aca-11e7-92ec-de91f1b55284.png)

**Comment by hijuuijj** [comment]
403 error is due geo-blocking, right? I tried with TunnelBear VPN before opening this post but I can download the m3u8 file. Have you tried with https://www.hlsplayer.net ?
However I can't open it with Clappr for some reason.

**Comment by kslimani** [comment]
@hijuuijj you must understand that player is internally using an [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) to download m3u8 file and therefore is affected by server CORS policy.

hlsplayer.net is using flash for video playback and therefore is not affected by CORS policy.

For getting same behaviour, you may wants to force Flash HLS playback in Clappr player configuration.

For example, go to [Clappr demo page](http://clappr.io/demo/) and try the following code :

```javascript
var player = new Clappr.Player({
  parentId: "#player-wrapper",
  source: 'http://rbetis-hls.flumotion.com/rbetis/live/.m3u8',
  plugins: [Clappr.FlasHLS],
  height: 360,
  width: 640
});
```

**Comment by hijuuijj** [comment]
@kslimani I forgot to say that I already tried [Clappr.FlasHLS] and CORS Toggle (for Chrome)
None of them work ... neither from the Clappr demo page.

**Comment by leandromoreira** [comment]
@hijuuijj what is the error?

**Comment by hijuuijj** [comment]
No error message.. just loading... how to see the error from Clappr?
Grind Player shows this error:

Error:
Message: Security error when loading media
Detail: Cannot load M3U8: crossdomain acces denied:Error #2048

(however I can open the video from https://www.hlsplayer.net. It uses Grind Player too).

**Comment by kslimani** [comment]
I remember talked with @towerz about Flash detection is broken in Chrome. (_dunno if fixed yet_).

Could you try my example code with another browser (_For example, Firefox with Flash plugin installed_).

**Comment by leandromoreira** [comment]
@hijuuijj this shows that you're not serving the [`/crossdomain.xml`](http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html) on your site and I also could not play the stream `http://rbetis-hls.flumotion.com/rbetis/live/.m3u8` on https://www.hlsplayer.net

**Comment by kslimani** [comment]
@leandromoreira that is weird, the stream is working for me on demo page with the [javascript example](https://github.com/clappr/clappr/issues/1469#issuecomment-315741519) i provided.

**Comment by hijuuijj** [comment]
@kslimani Yes, it works with Firefox... not with Chrome

**Comment by kslimani** [comment]
It does not work with Chrome because the Flash plugin detection is currently broken.
