### ISSUE TITLE
HLS Live stream captions not working correctly

### ISSUE THREAD

**Issue by UnitedPeace** [clappr/clappr#1471]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
All browsers
**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
All os
**Clappr Version**: latest, 2.66-2.68

Running a m3u8 live stream with ts encoded captions does not work with clappr, tested on demo page and external. It does work on hls.js demo page https://video-dev.github.io/hls.js/demo/

Here is the format of the m3u8 files:

main:
`#EXTM3U
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="captions",LANGUAGE="en",INSTREAM-ID="CC1",NAME="CC1"
#EXT-X-STREAM-INF:PROGRAM-ID=1,RESOLUTION=960x720,BANDWIDTH=3500000,CODECS="avc1.640029,mp4a.40.2",CLOSED-CAPTIONS="captions"
3000_v.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,RESOLUTION=1280x720,BANDWIDTH=6000000,CODECS="avc1.640029,mp4a.40.2",CLOSED-CAPTIONS="captions"
6000_v.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,RESOLUTION=896x504,BANDWIDTH=1650000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS="captions"
1500_v.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,RESOLUTION=640x360,BANDWIDTH=990000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS="captions"
800_v.m3u8`

800_v.m3u8
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-PROGRAM-DATE-TIME:2017-06-13T20:56:25+00:00
#EXT-X-KEY:METHOD=AES-128,URI="hssgg563343d545ffe434dfe.key",IV=0xK62B50190914EYBEC5CF2134D0F3B33R
#EXT-X-MEDIA-SEQUENCE:140181
#EXTINF:5.005,
56.ts
#EXTINF:5.005,
57.ts
#EXTINF:5.005,
58.ts
#EXTINF:5.005,
59.ts`

I noticed it works with m3u8 videos that are not live. In the live video the captions are encoded in the ts files I believe.

**Comment by kslimani** [comment]
@UnitedPeace can you provide a live stream url where i could reproduce the issue ?

**Comment by UnitedPeace** [comment]
https://tental.com/m3u8test/main.m3u8

**Comment by kslimani** [comment]
@UnitedPeace the http server does not send CORS headers in responses, i could not load the manifest with Clappr.

**Comment by leandromoreira** [comment]
Clappr (HLS.js) requires you to send CORS on HTTP response header @UnitedPeace.

**Comment by UnitedPeace** [comment]
@kslimani @leandromoreira Sorry about that, here is an updated url with cors *

https://www.tental.com/m3u8test/main.m3u8

**Comment by kslimani** [comment]
Thank you @UnitedPeace ! I can reproduce the issue with the provided source. I will use it to debug and attempt to fix the issue.
