### ISSUE TITLE
Streaming de video using codec mp3 is audio bad

### ISSUE THREAD

**Issue by JeanSauzem** [clappr/clappr#1474]
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://tv01.logicahost.com.br:1935/tvrionorte/tvrionorte/playlist.m3u8',
  height: 360,
  width: 640
});

player.attachTo(playerElement);

The present video transmission has bad audio in the Clappr player

**Comment by leandromoreira** [comment]
Hi @JeanSauzem I couldn't test your stream =( what are the characteristics of this issues?

**Comment by kslimani** [comment]
@JeanSauzem the problem is not related to Clappr. It comes from either the encoder or the reception (_if live tv channel_).
