### ISSUE TITLE
Closed captions button does not show up & no default track available

### ISSUE THREAD

**Issue by areeb111** [clappr/clappr#1477]
**Browser**: Version 59.0.3071.115 (Official Build) (64-bit)
**OS**: Win 10 - 64 Bit
**Clappr Version**: 0.2.71

Hi, 
I have tested the closed captions feature with Arabic WebVTT subtitles and i got the following issues:

1. "CC" button is hidden when i have checked the CSS props with developer tools i found that is caused by `display: none`, When removing this `none` value it's working fine (Check screenshot).
2. I have tried to set the Arabic subtitle as a default subtitle by adding `default: true` as mentioned in the W3 website, But i got no luck. My goal is to set this subtitle as auto-selected and viewed when the clappr initialized.

![clappr](https://user-images.githubusercontent.com/2633763/28692820-e639c160-732a-11e7-9971-5e339b50df1a.png)

3. I have tried to change the vertical alignment of the subtitle but i couldn't even with the `::cue` CSS props, I could change the font-family and color, I hope if you can support changing the background color, opacity and vertical alignment. 

My code: 
```
        var playerElement = document.getElementById("playerhubllxgAnwSY");
        var player = new Clappr.Player({
            source: 'http://192.168.98.254:8081/vod/_definst_/mp4:test.mp4/playlist.m3u8',
            autoPlay: true,
            width: 720,
            watermark: "img/vodu.png", position: 'top-right',
            playback: {
                preload: 'metadata',
                controls: false,
                playInline: true,
                recycleVideo: Clappr.Browser.isMobile,
                externalTracks: [
                  {lang: 'ar', label: 'Arabic', src: 'http://192.168.98.254/test.webvtt', kind: 'subtitles', default: true}
                ]
              }
        });

```

**Comment by kslimani** [comment]
By default, CC is set to disabled. There is no "autoselect" or "selected by default" feature implemented yet. (_so default: true has no effect. Thought it should be possible to implement such feature. I will try to have a look_).

About CC button not showing, could you try to add the `crossOrigin` parameter ? :

```javascript
var playerElement = document.getElementById("playerhubllxgAnwSY");
var player = new Clappr.Player({
    source: 'http://192.168.98.254:8081/vod/_definst_/mp4:test.mp4/playlist.m3u8',
    autoPlay: true,
    width: 720,
    watermark: "img/vodu.png", position: 'top-right',
    playback: {
        preload: 'metadata',
        controls: false,
        playInline: true,
        recycleVideo: Clappr.Browser.isMobile,
        crossOrigin: 'anonymous', // Required if track loaded from another domain
        externalTracks: [
          {lang: 'ar', label: 'Arabic', src: 'http://192.168.98.254/test.webvtt'}
        ]
      }
});
```

**Comment by zy87302728** [comment]
@kslimani hello.
I wanna to ask if we can choose one track as the default track showing when play video?

**Comment by kslimani** [comment]
@zy87302728 this feature is not implemented yet, but it should be easy to do. (_an additional configuration parameter, if set with lang value, will attempt to select and enable CC when video start to play_).

**Comment by zy87302728** [comment]
@kslimani  the code `video.textTracks[0].mode = 'showing';` does not worked. I wanna to know how to set the additional configuration.
by the way If there is some parameter to adjust the height of the subtitle?

**Comment by kslimani** [comment]
This feature require the following changes :

* add a new function in all supported playbacks to get a track ID by language code (for example `getClosedCaptionsTrackIdByLang(lang)`
* in the closed caption plugin, listen playback container "playing" event and use the new function to attempt to get track ID using lang value from a configuration option. If it successfully get a track id then use container `closedCaptionsTrackId` setter to enable track.

**Comment by nivaldocavalcanti** [comment]
@zy87302728 to the code `video.textTracks[0].mode = 'showing';` work the video must be played, so I did this way:

```
var playerElement = document.getElementById("my_player");
var player = new Clappr.Player({
    source: 'my_url/my_source.mp4',
    ..., //my other options
    externalTracks: [{
            lang: 'pt-BR', //come to Brazil!
            label: 'Subtitles', 
            src: "my_url/my_subtitle.vtt", 
            kind: 'subtitles'
    }],
    events: {
            onPlay: function() { $('video')['0'].textTracks[0].mode = 'showing'; }, 
    },
});
```

It worked for me! I hope it helps others.

Thanks Clappr!

**Comment by kslimani** [comment]
@areeb111 : can you also try to add `crossOrigin: 'anonymous'` property value in your playback configuration; this may explains why CC button is not displayed. _(an example usage is available [here](https://github.com/clappr/clappr/pull/1440#issue-124899974))_.

**Comment by nivaldocavalcanti** [comment]
@zy87302728 sure it can. If you have two or more subtitles track it's better use this code:

`            onPlay: function() { 
              var isShowing = false;
              $.each($('video')['0'].textTracks, function(idx,val){
                if($('video')['0'].textTracks[idx].mode == 'showing'){
                  isShowing = true;
                }
              });
              if(!isShowing){
                $('video')['0'].textTracks[0].mode = 'showing'; 
              }
            }, 
`

The code I did before was forcing track 0 to be always showing, then when you choose another track you got two tracks displaying, it's really a mess on the screen. 

The code above will prevent this to happen, and only displays the track 0 if there is no other track selected. The only trouble is if you pause, disable the tracks and then press play again it will enable the track 0. But if you don't pause you can disable tracks and change tracks for good.

**Comment by Animatr** [comment]
```
var player = new Clappr.Player({
source: "playlist.m3u8",
parentId: "#player",
poster: "/newage/oleposs.png",
autoplay: true,
playback: {
    preload: 'auto',
    controls: false,
    playInline: true, // allows inline playback when running on iOS UIWebview
    crossOrigin: 'use-credentials',
    recycleVideo: Clappr.Browser.isMobile, // Recycle <video> element only for mobile. (default is true)
    triggerFatalErrorOnResourceDenied: true, // Triggers playback fatal error if resource is denied. (default is false)
    externalTracks: [ // Add external <track> (if supported by browser, see also https://www.w3.org/TR/html5/embedded-content-0.html#the-track-element)
      {lang: 'tr', label: 'Turkce', src: 'alt.vtt', kind: 'subtitles'},
    ],
  },
events: {
            onPlay: function() { $('video')['0'].textTracks[0].mode = 'showing'; },
    },
});

```

This worked for me. Thanks for informations

**Comment by Hrishikesh-K** [comment]
Hey @kslimani I seem to be facing the same issue as @areeb111 in the opening post. My CC button has display set to none. Enabling that manually works well. What am I doing wrong?

As you said, `crossorigin` might help, but, I'm loading subtitles from my own website. I still added the attribute, but, that didn't help. The CC button stays hidden.

This is my config:

```
players.forEach(player =>
  {
    var clapprConfig =
      {
        width: '100%',
        height: '100%',
        source: player.getAttribute('src'),
        poster: player.getAttribute('poster'),
        playback:
          {
            preload: 'none',
            playInline: true,
            disableContextMenu: true,
            crossorigin: 'anonymous',
            externalTracks: [
              {
                lang: 'en',
                label: 'English',
                kind: 'subtitles',
                src: player.getAttribute('subtitles'),
              }
            ]
          },
        plugins: [LevelSelector],
        levelSelectorConfig:
          {
            title: 'Quality',
            labelCallback: function(playbackLevel)
              {
                return playbackLevel.level.height+'p';
              }
          }
      }
var clappr = new Clappr.Player(clapprConfig);
clappr.attachTo(player);
```

The live demo can be checked here: https://5fc2a909639e170007e19aa3--hrishikeshk.netlify.app/projects/carry-on-bot/ (scroll to the bottom of the page).
