### ISSUE TITLE
Is there any way to open this M3U8 via Clappr?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1479]
http://livecdn1.news.cn/cncen/manifest.m3u8

It can be opened using Android/iOS devices, Microsoft Edge and Native HLS Playback for [Chrome](https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/native-hls/).
Can I skip the crossdomain?

**Comment by leandromoreira** [comment]
@hijuuijj please try to follow the guideline https://github.com/clappr/clappr/blob/master/doc/BEFORE_OPEN_AN_ISSUE.md so we can try to help you 😃

**Comment by hijuuijj** [comment]
Nice. Cors plugin solved the problem.
I have found the original source too: http://livecdn1.news.cn/www/cncen.html

Some of your links of "common steps to verify issues" doesn't work, like "hls.js demo page"

http://streambox.fr/mse/demo/
http://streambox.fr/mse/hls.js-0.7.9/demo/
