### ISSUE TITLE
FlasHLS locate .swf to local domain

### ISSUE THREAD

**Issue by yudiastira** [clappr/clappr#1480]
Hello sir,

FlasHLS doesn't locate .swf to baseUrl.
Here my code : 
```
	var player = new Clappr.Player({
	  source: 'http://dev.example.me/hls/stream.m3u8',
	  baseUrl: 'dist',
	  poster: 'http://clappr.io/poster.png',
	  mute: true,
	  height: 360,
	  width: 640,
	  plugins: [Clappr.FlasHLS]
	});
```
When i view console network tab, it's request url to http://localhost/[number].swf
Not to http://localhost/dist/[number].swf

Thank you before

**Comment by kslimani** [comment]
Indeed, i can reproduce the bug on demo page. 👍 

Please @yudiastira could you try your code with Clappr version 0.2.69 and report if it is working ?

**Comment by kslimani** [comment]
It seems that the `"data"` property rendered `<object>` element is not filled with proper assets path.
It may be related to [this commit](https://github.com/clappr/clappr/commit/6f18eaaa4e3cea670ef293747ee402db20e468c6#diff-0f8ba69a22926775b13e364cd114913bR32) -  @towerz what do you think ?

**Comment by nontonto** [comment]
0.2.69 is request to http://localhost/809981e5b09d5336c45d72d0869ada2a.swf
not to http://localhost/dist/809981e5b09d5336c45d72d0869ada2a.swf

**Comment by towerz** [comment]
@kslimani actually, the commit didn't change the asset path, just added a new parameter.

I just found out the cause, the swf path is being defined before setting `this._baseUrl`.

**Comment by maxlapshin** [comment]
Hi. We also have this problem.
