### ISSUE TITLE
Why didn't my clappr player control the fullscreen in iframes

### ISSUE THREAD

**Issue by GuangJianLee** [clappr/clappr#1481]
var playerEl = document.getElementById("player");
    var player = new Clappr.Player({
    	source: "$id",
    	height:"480",
    	width:"1000",
    	autoPlay: true,
      position: 'top-right'
});

    player.attachTo(playerEl);

**Comment by GuangJianLee** [comment]
#
![20170801091218](https://user-images.githubusercontent.com/3849139/28805000-7c8c3096-7699-11e7-8d6b-69d1727fa53a.png)
When the HLS streaming is broadcast live, there is no full screenbutton

**Comment by kslimani** [comment]
Hello, @GuangJianLee in order to help you we need you to provide some informations :

* Which version of Clappr player are you using ?
* Which OS and Browser names and versions ?
* Can you reproduce the bug on Clappr [demo page](http://clappr.io/demo/) ?
* If not, can you provide a demo page ?

See also [this guide](https://github.com/clappr/clappr/blob/master/doc/BEFORE_OPEN_AN_ISSUE.md).

**Comment by UnitedPeace** [comment]
It is likely you have embed the clappr player in an iframe and did not add the allowfullscreen="true" tag to the iframe.

**Comment by GuangJianLee** [comment]
Clappr is http://cdn.jsdelivr.net/gh/clappr/clappr@latest/dist/clappr.min.js
OS  windows 7   Browser is chrome 59.0.3071.115
I'm sorry I forgot.My player is in the iframe, I've checked the relevant issues, it's like the iframe can't be full screen and this is a question of js?

**Comment by kslimani** [comment]
@GuangJianLee if Clappr player is loaded from an iframe, you must set the iframe [`allowfullscreen`](https://developer.mozilla.org/en/docs/Web/HTML/Element/iframe) attribute to true like @UnitedPeace suggested.

**Comment by leandromoreira** [comment]
```html
<iframe allowfullscreen=true>
//
</iframe> 
```

**Comment by GuangJianLee** [comment]
Sorry, I also joined allowfullscreen= "true", but the problem is still the same. It turned out that my player was nested below two iframe. Then the parent iframe and the child iframe are set with allowfullscreen= "true" to display the full screen button. @UnitedPeace ，@kslimani @leandromoreira Thank you!
