### ISSUE TITLE
m3u8 not working

### ISSUE THREAD

**Issue by firofame** [clappr/clappr#1483]
```
<head>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/clappr/clappr@latest/dist/clappr.min.js"></script>
</head>

<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({source: "http://jiotv.live.cdn.jio.com/Star_Vijay/Star_Vijay_400.m3u8", parentId: "#player"});
  </script>
</body>
```

why is this code not working?

**Comment by UnitedPeace** [comment]
Because your has security to block requests from other websites, otherwise known as cross origin policy.

**Comment by firofame** [comment]
what about this source:
http://smumcdnems03.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Star_Vijay/Star_Vijay.m3u8

**Comment by UnitedPeace** [comment]
That one uses the same security.

**Comment by firofame** [comment]
any idea how this is done:
tv-live.in/wp-content/uploads/tv-online/Channel/India/Channel/Star%20Vijay-l1.php

**Comment by leandromoreira** [comment]
@firofame it's a security feature on the browsers, you must [setup the CORS headers](https://github.com/clappr/clappr/issues/703) in your CDN / server (the nodes which serve your stream [.m3u8]), that's why it works in the last example you provided:

![screen shot 2017-08-04 at 8 04 58 pm](https://user-images.githubusercontent.com/55913/28990112-96b9fff2-7950-11e7-9cd0-9fa3424af2e1.png)

And when we try to play your content, the master playlist works fine but then the sub-playlists are without CORS.

![screen shot 2017-08-04 at 8 08 55 pm](https://user-images.githubusercontent.com/55913/28990159-115b3c80-7951-11e7-8f36-01c4e7c2558d.png)
![screen shot 2017-08-04 at 8 09 29 pm](https://user-images.githubusercontent.com/55913/28990162-14df6e44-7951-11e7-86f1-6edb3e9dbae2.png)

**Comment by firofame** [comment]
is it normal that the link is still working using vlc, ffmpeg, and browser plugins?
eg: https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof

is there any workaround CORS, since i dont have access to the server.

**Comment by leandromoreira** [comment]
@firofame you can use the `flashls` playback (as shown in the code below) but then you might have another issue which is related to `crossdomain.xml` file. Anyway, I think the service / CDN you use to stream must have the option to change HTTP response headers.

```javascript
	var player = new Clappr.Player({
	  source: 'http://dev.example.me/hls/stream.m3u8',
	  baseUrl: 'dist',
	  poster: 'http://clappr.io/poster.png',
	  mute: true,
	  height: 360,
	  width: 640,
	  plugins: [Clappr.FlasHLS]
	});
```

**Comment by firofame** [comment]
@leandromoreira Thank you so much, i was stuck at this for almost 2 wreaks now.

fixed it with a simple WordPress plugin: https://wordpress.org/plugins/flowplayer5/

**Comment by Johnpraveenkumar** [comment]
Hai @firofame did you solved your issue?....i am having same problem.

**Comment by firofame** [comment]
@Johnpraveenkumar i couldn't solve it. I think using flashls is the solution. please post a sample code if you manage to solve it.

there is no CORS issue when implementing in native. i successfully implemented the code in android and published the app without any issues.

**Comment by m0n1sh** [comment]
@firofame  Did you solve the issue, if yes please reply.

**Comment by firofame** [comment]
No

**Comment by m0n1sh** [comment]
please connect here https://www.facebook.com/monishkumarmv

**Comment by m0n1sh** [comment]
i have a solution but it had some issues so i need to discuss.

**Comment by lovablegce** [comment]
@firofame Did you solve the issue?

**Comment by lovablegce** [comment]
@leandromoreira Do you have any idea how to get the encryption keys which are provided in the live streaming?
Sample: http://sklktcdnems05.cdnsrv.jio.com/jiotv.live.cdn.jio.com/AXN_HD/AXN_HD_1200.m3u8?jct=NNXpstYnCQSaMw46OvZodQ&pxe=1508777679&st=AQIC5wM2LY4SfczJUsPeNpQK-WxTgD1o9I3YMroM17eybG0.*AAJTSQACMDIAAlNLABQtNTA0NjQzOTU5NTkwODkzMzk3MQACUzEAAjI4*

whatever present after m3u8 is keep on changing. Is there any way to get this?

**Comment by leandromoreira** [comment]
It's explained here https://developer.apple.com/library/content/technotes/tn2288/_index.html

**Comment by eedi1** [comment]
@m0n1sh @firofame @lovablegce any one has solution plz contact eedi@gmail.com thanks

**Comment by phonerave** [comment]
bro anyone got solution

**Comment by Lethea** [comment]
For this kind of stream that protected by header referer
you cant play this directly from your website

you need to restream that via ffmpeg headers

**Comment by A-Thop** [comment]
Hey, i got a solution, all you need to do is like the following.
Add `http://thoptv.com/public/full.php?url=` before that jio link.

Example-1:
[http://thoptv.com/public/full.php?url=http://ssrigcdnems01.cdnsrv.jio.com/jiotv.live.cdn.jio.com/History_HD/History_HD_800.m3u8](http://thoptv.com/public/full.php?url=http://ssrigcdnems01.cdnsrv.jio.com/jiotv.live.cdn.jio.com/History_HD/History_HD_800.m3u8)
Example-2:
[http://thoptv.com/public/full.php?url=http://ssrigcdnems01.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Star_Sports_HD_1/Star_Sports_HD_1_800.m3u8](http://thoptv.com/public/full.php?url=http://ssrigcdnems01.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Star_Sports_HD_1/Star_Sports_HD_1_800.m3u8)

All the best . . .

**Comment by mohsinworld** [comment]
@A-Thop Can you please teach me the technique of getting token? So I can play with Clappr player with my website logo and link? Thanks

**Comment by A-Thop** [comment]
@mohsinworld I can't share the secret of our work. But i can provide you, an embed code of player with your own logo and link for free. If you want more than that you need to contact us on our Facebook page via [https://fb.me/THOPNETWORK](https://fb.me/THOPNETWORK)

**Comment by mohsinworld** [comment]
@A-Thop, You are not active on Facebook, can you give me a better way to contact you?

**Comment by A-Thop** [comment]
@mohsinworld I am not sure, when you tried to contact me, But I will check my Facebook Page Every Hour to engage with my clients. Feel Free to contact me. [https://fb.me/THOPNETWORK](https://fb.me/THOPNETWORK)

**Comment by vmcreations** [comment]
i have all jio tv link with my attach ment of server but not working in jw player
for eg like this
http://50.160.135.172:8080/jio/playlist.m3u8?url=http://ssrigcdnems01.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Star_Sports_HD_2/Star_Sports_HD_2_800.m3u8
this is examample 


this is the model that not work in  jwplayer or other website player
but work in the  mx player

**Comment by eedi1** [comment]
vmcreation how i can contact you

**Comment by eedi1** [comment]
i needtro talk

**Comment by vmcreations** [comment]
Okk talk

**Comment by eedi1** [comment]
need jio soultion

**Comment by vmcreations** [comment]
No bro iam using Thopu tv

**Comment by ProjectAdrian** [comment]
@vmcreations 
how do u get the links?
http://50.160.135.172:8080/jio/playlist.m3u8?url=http://ssrigcdnems01.cdnsrv.jio.com/jiotv.live.cdn.jio.com/Star_Sports_HD_2/Star_Sports_HD_2_800.m3u8

**Comment by mohsinworld** [comment]
I went to THOP tv

**Comment by vmcreations** [comment]
That's not working

**Comment by ProjectAdrian** [comment]
@vmcreations 
what is the working link pls?

**Comment by vmcreations** [comment]
I dont have iam using thoputv php

**Comment by mohsinworld** [comment]
@ProjectAdrian Check this link http://thoptv.com/partners/TUGUstreamTV/Embed.php?channel=Zing

You can change channel name to get all working like replace Zee_Cinema in Zing it will show Zee Cinema. Add Star_Sports_HD_1 after this http://thoptv.com/partners/TUGUstreamTV/Embed.php?channel= [http://thoptv.com/partners/TUGUstreamTV/Embed.php?channel=Star_Sports_HD_1] I can give you all the link if you want. It will be from THOP TV. I took partnership with @A-Thop you can talk to him or just use my links.

**Comment by vmcreations** [comment]
http://thoptv.com/partners/VMcreations/Embed.php?channel=Star_Sports_HD_1

**Comment by ProjectAdrian** [comment]
does it work on mx player?

**Comment by mohsinworld** [comment]
No, it's work with iframe.

**Comment by ProjectAdrian** [comment]
is there a way to play on mx player?

**Comment by mohsinworld** [comment]
Then talk to @A-Thop

**Comment by vmcreations** [comment]
Nooo

**Comment by arjunthomas** [comment]
Copy the m3u8 link using developer tools in Chrome.

**Comment by kvnishan** [comment]
Vm creation ,
How to become a partner of thoptv

**Comment by vmcreations** [comment]
Email me personally
vm44407@gmail.com

**Comment by freeiptv1** [comment]
We have a working solution for JioTV with Clappr. [http://freeiptv.ga](url)   
Format [http://freeiptv.ga/tv.php?channel=Rishtey&progid=279](url)

**Comment by mohsinworld** [comment]
Where do you get security token? Can you please tell me? @freeiptv1

**Comment by freeiptv1** [comment]
JioTV is a paid service. It requires authentication with the serial number of the SIM card to get the token.  You can embed channels with an iframe to this page, [http://freeiptv.ga/partner.php?c=9XM](url)   The c parameter takes the channel name.  such as <iframe style="width:640px;height:480px" src="http://freeiptv.ga/partner.php?c=9XM"></iframe>

**Comment by freeiptv1** [comment]
If you are interested to get the source code that fetches the security token and the serial number of a Jio SIM card. Contact us at mini.2015@yahoo.com to buy

**Comment by GurrpreetDhaliwal** [comment]
HI freeiptv1, I am looking for a way to fetch token form jio. I do have a active jio sim. Can you point me to a direction or help me with the source. ?

**Comment by freeiptv1** [comment]
@GurrpreetDhaliwal @mohsinworld 
I have sent you mails. Do reply to mini.2015@yahoo.com 

Here's the new demo [http://www.freeiptv.ga/tv.php?channel=Rishtey&progid=279](http://www.freeiptv.ga/tv.php?channel=Rishtey&progid=279)

**Comment by num47** [comment]
I have more than 100 TV links. If anyone wish to buy any link then contact with me. email: asda4545@yahoo.com

**Comment by ProjectAdrian** [comment]
anyone have zee studio?

**Comment by freeiptv1** [comment]
@ProjectAdrian I am afraid. Zee Studio isn't in the list. There is a Zee Action though [http://freeiptv.ga/tv.php?channel=Zee_Action&progid=488](http://freeiptv.ga/tv.php?channel=Zee_Action&progid=488)

**Comment by iptvbd** [comment]
@ProjectAdrian i have ditto Zee Studio working link

**Comment by vmcreations** [comment]
I have Jio m3u8....

**Comment by mohsinworld** [comment]
Who can give me JIO TV raw .m3u8 links which will work all over the world? I am willing to pay monthly.

**Comment by iptvbd** [comment]
@mohsinworld i have few... if you need knock  me iptvbd @ gmail .com

**Comment by vmcreations** [comment]
I have to all Jio channels links....I have
vm44407@gmail.com

**Comment by Matesy** [comment]
How To Download From Jio Cinema Website With m3u8.. I Was Downloading Before 2 Months From Jio With Adownloader..Now They Have Changed The Scripts..  So I M Not Able To Download From There...
i Had Tried Youtube-dl , FFMPEG, live Streamer..
Everything Giving Error 405..
Can Anyone Help Me With That...

**Comment by freeiptv1** [comment]
@Matesy  you have to append jct,pxe,st parameters that you get after login to JioTV and change useragent. We found a way to get it to work.  [http://freeiptv.ga/tv.php?channel=Toonami](http://freeiptv.ga/tv.php?channel=Toonami)

**Comment by vmcreations** [comment]
Iam selling Jio m3u8 if want contact me on
vm44407@gmail.com

**Comment by vmcreations** [comment]
Message me on hangout

**Comment by Matesy** [comment]
Can u provide Me 12 MBPS M3u8 ??
Which I Can Download With ffmpeg or youtube-dl

**Comment by freeiptv1** [comment]
@Matesy grab the link with VideoDownloadHelper. [http://freeiptv.ga/tv.php?channel=B4U_Movies&progid=182](http://freeiptv.ga/tv.php?channel=B4U_Movies&progid=182)

Jio token logic (compilable source code), channelguide, play recorded programs from Jio servers, live streaming.

Mail mini.2015@yahoo.com to buy. A Jio account is necessary

**Comment by americanmafia** [comment]
i found apk which is work in android tv , fire tv and mobile . it may be help you to view 

http://www6.zippyshare.com/v/sLFJRoOO/file.html . 

http://www.mediafire.com/file/dujtrt2a6a2k9e4/free_live_tv_india.apk 

it work out side india - i like so share here .no login nothing

**Comment by vmcreations** [comment]
I have Jio link for payment ₹750 per month

**Comment by mohsinworld** [comment]
@vmcreations Do you provide link which will work on Web [jwplayer], mobile app?

**Comment by vmcreations** [comment]
S

**Comment by Jenosan97** [comment]
How install m3u8 url working jw player how to install please help

**Comment by freeiptv1** [comment]
I sell full source for $210. Put it on any server and it will generate the token, retrieve m3u8, retrieve catchup and program list. Demo is here [http://freeiptv.ga/tv.php?channel=Zee_Cinema_HD](http://freeiptv.ga/tv.php?channel=Zee_Cinema_HD)  . Mail to freelancer1@protonmail.com. Thanks.

**Comment by vmcreations** [comment]
I will give my link for $10

**Comment by ketupatel255** [comment]
i need a link jio tv all channal..

**Comment by ketupatel255** [comment]
and sorce code for devlap server m3u8 output

**Comment by Jenosan97** [comment]
Help this

How to yupptv channel Url playlist how to play own player

**Comment by americanmafia** [comment]
@Jenosan97 @ketupatel255 @mohsinworld  no jio account need use it free http://www6.zippyshare.com/v/sLFJRoOO/file.html .

**Comment by Jenosan97** [comment]
@americanmafia Not Open app 
Continuesly Loading 
You are original source code

**Comment by americanmafia** [comment]
is should work .. where are you from ?i am from orignal source code ..04.03.2018, 16:57, "Jenosan97" <notifications@github.com>:@americanmafia Not Open app
Continuesly Loading
You are original source code

**Comment by Jenosan97** [comment]
@americanmafia How to get you Original Jio Source Code

**Comment by Jenosan97** [comment]
Yupp tv Channel Original playlist creat And play

**Comment by americanmafia** [comment]
@Jenosan97 direct mail me .. i give you more info - easyservice@protonmail.com

**Comment by americanmafia** [comment]
I will provide your own branding app
Android TV 
Android Mobile 
Fire TV
iPhone
Apple TV
Roku
KODI - Add on 
KODI - Luncher
KODI - Luncher APK
KODI - BUILD
KODI - Wizard
Website

more info mail me : 
easyservice@protonmail.com

**Comment by Jenosan97** [comment]
Website

**Comment by freeiptv1** [comment]
Watch here --> [http://freeiptv.ga/tv.php?channel=Discovery_HD_World](http://freeiptv.ga/tv.php?channel=Discovery_HD_World)

To buy the full source, contact freelancer1@protonmail.com

**Comment by americanmafia** [comment]
Free Live TV android App for your amazon fire and android tv box compatible . 

https://goo.gl/5gZqYb
http://www.mediafire.com/file/v832ah91es5nrye/free_live_tv_v1_android.apk


are you need self hosted source code ?  email me : easyservice@protonmail.com

**Comment by flavioribeiro** [comment]
wtf is this?

**Comment by flavioribeiro** [comment]
some sneaky users are using this thread to spam illegal ways of sharing content. It's sad to see people doing this shit here, I reported all usernames to github and I hope they will stop using clappr as a channel to spread their dirt. keep an eye out and help report these users! :)

**Comment by americanmafia** [comment]
@flavioribeiro use jw player

**Comment by freeiptv1** [comment]
@flavioribeiro   JioTV is a legal IPTV provider with an India-wide license but it requires auth to its api to get tokens. also it is a paid service. here's how you can auth to the api. [https://github.com/freeiptv1/jioapi/](https://github.com/freeiptv1/jioapi/)   

this is not a Clappr issue. rather they are accessing the urls without the token, which gets them a HTTP 406.  close this thread if possible.

**Comment by vmcreations** [comment]
I have Jio link working with token if anybody want contact us...immediately
for small amount.... Work in PC Android and ios

**Comment by engkazim2000** [comment]
Hi,

How to contact you @vmcreations

**Comment by vmcreations** [comment]
vm44407@gmail.com

**Comment by engkazim2000** [comment]
Hi,
email send you

**Comment by allscriptz** [comment]
full source code for jio token. contact me [https://github.com/allscriptz/jiotv](https://github.com/allscriptz/jiotv)

**Comment by engkazim2000** [comment]
Can you guide how that code will work also can we use it from any location

**Comment by allscriptz** [comment]
@engkazim2000  allscripts@protonmail.com

**Comment by Jenosan97** [comment]
Please help

How to another Streming player video to my own Streming player

**Comment by vmcreations** [comment]
Wowza streaming

**Comment by Jenosan97** [comment]
How to php api parssing script instal and download 
(multi url Streming and get url in one)

**Comment by ErickNoz** [comment]
Me to to get multiple stre

**Comment by Jenosan97** [comment]
Please send full script php

**Comment by Jenosan97** [comment]
I have jiotv Account username and pass word how to get jiotv playlist and token Streming in our site

**Comment by Jenosan97** [comment]
@leandromoreira how to play this url on jw player please help
http://livetvstream.in/api/jio/play.m3u8?ch=Sun_TV_HD

**Comment by leandromoreira** [comment]
@Jenosan97 here is the clappr player but anyway the url you posted don't seem to be working, it's returning not found instead of the playlist.

```
$ curl -v "http://livetvstream.in/api/jio/play.m3u8?ch=Sun_TV_HD"
*   Trying 139.59.15.168...
* TCP_NODELAY set
* Connected to livetvstream.in (139.59.15.168) port 80 (#0)
> GET /api/jio/play.m3u8?ch=Sun_TV_HD HTTP/1.1
> Host: livetvstream.in
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 12 Jul 2018 16:49:26 GMT
< Server: Apache/2.4.7
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: PHPSESSID=p5qr1ccmb96sib1jepim6ojg3r; path=/
< Vary: Accept-Encoding
< X-Frame-Options: DENY
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host livetvstream.in left intact
not found%
```

**Comment by Jenosan97** [comment]
@engkazim2000 http://livetvstream.in/api/jio/play.m3u8?ch=Star_Vijay

**Comment by engkazim2000** [comment]
Its not working

**Comment by engkazim2000** [comment]
@Jenosan97 can you please provide me working play.m3u8 file to my gmail eng.kazim2000@gmail.com

**Comment by Jenosan97** [comment]
No
How to get Jio Account to Jio tv playlist get

**Comment by towerz** [comment]
It seems like there are some more users trying to use this issue to share access to content they don't own. Since there's no point in keeping this conversation open, I locked the issue.
