### ISSUE TITLE
feature screenshot 

### ISSUE THREAD

**Issue by alexvasiliev** [clappr/clappr#1485]
Is there any method, that i can use to get a screenshot of current video source(with original video resolution, not current player size) from clappr?

**Comment by thiagopnts** [comment]
clappr doesn't have any methods for that, but you can achieve that by drawing the video element to a canvas and use `canvas.toDataURL()`[1] to get an image

[1] https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by alexvasiliev** [comment]
ty for quick answer
