### ISSUE TITLE
Why Did Clapper is not showing M3U8 Stream in Firefox Browser !

### ISSUE THREAD

**Issue by nk576** [clappr/clappr#1487]
**Browser**: Firefox Version 40.0

**OS**: Window 10

**Clappr Version**: 0.2.25 (LATEST)

M3U8 Stream in Clapper is  working perfectly in Google Chrome, Microsoft Edge, Android Browser....

But not working for Firefox Browser !

I am using Latest Version of Clapper... 

Kindly, Help me to Fix it

**Comment by kslimani** [comment]
Hello @nk576 ,

Is _"Firefox Version 40.0"_ a typo error ? (Latest version of Firefox on Windows should be something like 54 or greater) : if you really use version 40, i suggest you to upgrade version.

Otherwise, have you tried your .m3u8 manifest on [Clappr demo page](http://clappr.io/demo/) ?

**Comment by nk576** [comment]
![2017-08-11_1408](https://user-images.githubusercontent.com/30923481/29207221-c109d6da-7e9e-11e7-8115-bb07cab292a5.png)

**Comment by nk576** [comment]
Yes, Firefox Browser was outdated.... was not auto updating ! (Showing Upto Date)

Thanks Alot for Up Helping

New One is 55.0.1

![2017-08-11_1418](https://user-images.githubusercontent.com/30923481/29207577-1b50b4a0-7ea0-11e7-9231-98b35a8f4fe0.png)

**Comment by kslimani** [comment]
@nk576 did Firefox upgrade solved your issue ?

**Comment by nk576** [comment]
yes.. done

thanks
