### ISSUE TITLE
Example with local m3u8 please ? can't make it work by my own..

### ISSUE THREAD

**Issue by SAMYEL06** [clappr/clappr#1491]
Hello, 

Just for a little question.. I've been trying to use Clappr on Wordpress with a local file (m3u8) from my desktop but it doesn't seem to work.. I use wordpress online, just so you know.

Can you please tell me if playing from desktop is possible, and if yes, give me an example ? 

[clappr media="file:///C:/Users/Sam/Desktop/test/test.m3u8" buttoncolor=#87ff7a seekbarcolor=#8c90ff] that's  what I've put on Wordpress.

Thank you

**Comment by SAMYEL06** [comment]
And now, the player doesn't show anymore, even with a valid adress..

**Comment by leandromoreira** [comment]
@SAMYEL06 can you try to https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues ?

**Comment by Thor77** [comment]
You have to upload that file (including the ones it refers to) to a remote location somehow.
