### ISSUE TITLE
how to reduce delay to display video after click in start play

### ISSUE THREAD

**Issue by ciclanoio** [clappr/clappr#1493]
I'm trying to improve the user experience of the delay to start the video display. Usually with Clappr on our side it takes up to 10 seconds for the video to start. In JW we were able to configure this to start immediately after starting.

**Clappr Version**: last

**Comment by leandromoreira** [comment]
@ciclanohost what kind of stream are you using? hls, dash, mp4... can you provide a link to one of these streams?

If you go the [demo page](http://clappr.io/demo/), you'll see that from the moment you click on the play to the start of the video is almost instantaneously.
