### ISSUE TITLE
autoPlay not working on android browsers.

### ISSUE THREAD

**Issue by shanka12** [clappr/clappr#1495]
**autoPlay:true** not working on android browsers. Can anyone help me?

**Comment by kslimani** [comment]
On mobile devices, html5 video element require a user action (_a screen touch_) for play video. Only way to autostart video on mobile device is to mute audio.

**Comment by shanka12** [comment]
Im using the auto play for click function. I tried mute audio. its not working. first  im loading the image of the video. when click on image player will load. its works on desktop.
here is my code.

$('.dev-vid-thumb').on('click', function() {
        var vid = $(this).data('vid-id');
        var pid = $(this).data('p-id');
        $.ajax({
            url : 'https://api.vimeo.com/videos/'+vid+'?fields=files.link',
            headers : {
                'Authorization' : 'Bearer ' + 'xxxxxxxxxxxxx'
            },
            cache: true,
            json : true,
            contentType:'application/vnd.vimeo.endpoint+json',
            success: function (body) {
                $('.dev-vid-thumb').addClass('hidden');
                $('.dev-s-vid-player').removeClass('hidden');
                var player = new Clappr.Player({
                    source: body['files'][1]['link'], parentId: "#player",
                    watermark: "logo.png", position: 'top-right',
                    disableVideoTagContextMenu: true,
                    width: "100%",
                    preload: 'auto',
                    mute: true,
                });
                player.play();
            }
        });
    });

**Comment by kslimani** [comment]
This code cannot work on mobile. The player (_ie: the video element_) must be created **before** user click on button.

To achieve this you needs to do the following :

* Create Clappr instance using a "mocked" source (_see example code_)
* In Clappr playback configuration enable the [recycleVideo](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#playback-configuration) option
* In the "click" event function, call the `player.consent()` method **before** using ajax request (_or you will lose the user action_)

Here an example based on provided code :

```javascript
var player = new Clappr.Player({
  source: URL.createObjectURL(new Blob([], {type: 'application/vnd.apple.mpegurl'})),
  parentId: "#player",
  watermark: "logo.png", position: 'top-right',
  disableVideoTagContextMenu: true,
  width: "100%",
  preload: 'auto',
  playback: {
    recycleVideo: Clappr.Browser.isMobile,
    playInline: true, // allows inline playback (remove if don't want)
  },
});

$('.dev-vid-thumb').on('click', function() {
  // "store" user action
  // See: https://github.com/clappr/clappr/pull/1319#issue-213091990
  player.consent();

  var vid = $(this).data('vid-id');
  var pid = $(this).data('p-id');
  $.ajax({
    url : 'https://api.vimeo.com/videos/'+vid+'?fields=files.link',
    headers : {
      'Authorization' : 'Bearer ' + 'xxxxxxxxxxxxx'
    },
    cache: true,
    json : true,
    contentType:'application/vnd.vimeo.endpoint+json',
    success: function (body) {
      $('.dev-vid-thumb').addClass('hidden');
      $('.dev-s-vid-player').removeClass('hidden');
      player.configure({
        source: body['files'][1]['link'],
        autoPlay: true,
      });
    }
  });
});
```

**Comment by leandromoreira** [comment]
👏 👏 👏 👏 👏  bravo @kslimani

**Comment by shanka12** [comment]
Great! this is works. thank you @kslimani
