### ISSUE TITLE
Plugins option

### ISSUE THREAD

**Issue by matheusrufca** [clappr/clappr#1503]
Hi,
just a silly question, what's the difference between set plugins as array and set `playback` attribute

```
var player = new Clappr.Player({
    ...
    plugins: [...]
});
```
and
```
var player = new Clappr.Player({
    ...
    plugins: {'playback': [...]}
});
```

**Comment by kslimani** [comment]
@matheusrufca i think there is different syntax for historical reason and to maintain backward compatibility. You should not specify plugin type anymore as it is now properly handled in core.
(_ie: use the first syntax_).

**Comment by matheusrufca** [comment]
Thanks @kslimani!
