### ISSUE TITLE
Stream not working (Dailymotion)

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1508]
I'm tyring to play this stream (l'Equipe) with Cors, https, flasHLS. None of them seems to be working. It works fine opening the stream natively.

http://stream-01.ix7.dailymotion.com/29/dm/3/x2lefik/live-4.m3u8

Any ideas?

**Comment by leandromoreira** [comment]
@hijuuijj when I tried to play this on the demo page it returned a `403` page and it doesn't have the `CORS` headers too.

![screen shot 2017-09-11 at 5 48 58 pm](https://user-images.githubusercontent.com/55913/30296189-ab7ee0ba-9719-11e7-934f-00549ae6d32b.png)

However when you `curl` on the terminal:

```bash
$ curl -I https://stream-01.ix7.dailymotion.com/29/dm/3/x2lefik/live-4.m3u8
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 11 Sep 2017 20:50:48 GMT
Content-Type: application/vnd.apple.mpegurl
Connection: keep-alive
Last-Modified: Mon, 11 Sep 2017 20:50:43 GMT
Expires: Mon, 11 Sep 2017 20:50:47 GMT
Cache-Control: max-age=1, public
X-Cache-Feed: HIT
X-FEED-ID: 02
X-Backend: stream02_ix7
Age: 1
X-Cache: HIT
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length
Accept-Ranges: bytes
Strict-Transport-Security: max-age=0; includeSubDomains; preload
```

The server probably is looking at the `User-Agent` to define this.

**Comment by hijuuijj** [comment]
Another live stream without error 403 and not playable with Clappr (playable with https://www.hlsplayer.net)

http://stream-15.dc3.dailymotion.com/48/dm/3/x3m6nld/live-4.m3u8

**Comment by leandromoreira** [comment]
I tried again the URL you informed at [clappr demo page](http://clappr.io/demo) and it still raises the errors.

![screen shot 2017-09-12 at 6 25 29 pm](https://user-images.githubusercontent.com/55913/30349069-f184efae-97e7-11e7-8921-5a943703bdbf.png)

**Comment by hijuuijj** [comment]
I wonder why GrindPlayer can open the stream.

**Comment by leandromoreira** [comment]
what its request and see what are the headers... and its behaviors, is it a flash-based player?

**Comment by ilyaluk** [comment]
I guess it's because of Referer header. Dailymotion forbids m3u8 requests when referer present.
Try to remove it with ` <meta name="referrer" content="no-referrer" />` or any other method.
