### ISSUE TITLE
Subtitle changing not working

### ISSUE THREAD

**Issue by matheusrufca** [clappr/clappr#1510]
Idk if is a Clappr issue

**Browser**: Chrome, Opera, Tizen
**OS**: Windows 10, Tizen
**Clappr Version**: 0.2.71

**Steps to reproduce**:
* first step
Init clappr with following settings and HLS source
```
{
	"parentId": "clappr-container",
	"width": "100%",
	"shakaConfiguration": {
		"preferredAudioLanguage": "pt-BR",
		"streaming": {
			"rebufferingGoal": 15
		}
	},
        "plugins": [LevelSelector, AudioTrackSelector, DashShakaPlayback, Smooth],
	"source": "http://***/76/source/hls/video/sd/video.m3u8",
	"externalTracks": [{
		"language": "pt-BR",
		"languageName": "Português",
		"src": "resources/subtitles/pt-BR.vtt",
		"id": 0,
		"lang": "pt-BR",
		"label": "Português",
		"kind": "subtitles"
	}, {
		"language": "en-US",
		"languageName": "Inglês",
		"src": "resources/subtitles/en-US.vtt",
		"id": 1,
		"lang": "en-US",
		"label": "Inglês",
		"kind": "subtitles"
	}]
}
```

Added buttons to change subtitle
```
function setSubtitle(subtitle) {
	var video, textTracks;
	video = document.querySelector('video');
	textTracks = video.textTracks;

	for (var i = 0; i < textTracks.length; i++) {
		if (video.textTracks[i].language == subtitle.language) {
			video.textTracks[i].mode = 'showing';
		} else if (video.textTracks[i].language && video.textTracks[i].kind == 'subtitles') {
			video.textTracks[i].mode == 'hidden';
			//video.textTracks[i].mode == 'disabled';
		}
	}
};
```
Code is working good, I debugged many times, also tried with `setTimeout`. If I manually set `textTrack.mode` to hidden on console works.

I was expecting subititle to be hidden after I set `mode == 'hidden'` but both subtitles are showing.

![image](https://user-images.githubusercontent.com/8710641/30592812-addea1be-9d1e-11e7-89c7-54aef8a08d0b.png)

**Comment by kslimani** [comment]
@matheusrufca latest version of Clappr *should* handle subtitles and automatically display a button in mediacontrols when subtitles are available.

Take a look at [playback config documentation](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#playback-configuration).

**Comment by matheusrufca** [comment]
Hi @kslimani , thanks for your message.

I changed Clappr version to 0.2.73 and nested `externalTracks` config inside `playback` options but didnt solve nor show subtitles button.
Am I missing something?

![image](https://user-images.githubusercontent.com/8710641/30594805-be1ce2c8-9d25-11e7-84b2-d405757c337d.png)

**Comment by kslimani** [comment]
Oh, i see, i think this is because external track support has been added only for html5_video playback (_ie: .mp4 source_). It seems it is not implemented (yet) for HLS source.

**Comment by matheusrufca** [comment]
Hmm, thanks. what is weird is subtitles are working and when I set to hide via console works too.
But would be nice a native player handler for changing subtitles on streaming.
I'm running out of time now, but I can contribute in near future on this feature.

**Comment by kslimani** [comment]
There is an internal plugin in Clappr to handle subtitles (feature added [here](https://github.com/clappr/clappr/pull/1440)) - but currently, hlsjs playback supports only subtitles which are embeded in manifest. _(external track support has not been aded yet for hls, only for mp4 source)_

For example, test with [source](https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8) in clappr [Demo page](http://clappr.io/demo/).
