### ISSUE TITLE
iOS 11 container.click / container.dblclick event not triggered on tap. 

### ISSUE THREAD

**Issue by aditya0711** [clappr/clappr#1515]
**Browser**: 
Safari/Chrome/Firefox Browsers

**OS**: iOS 11

**Clappr Version**: 0.2.27

**Steps to reproduce**:

player.getPlugin("click_to_pause").disable();
Clappr.Log.setLevel(0);

if the player(container) is tapped, the click is not registered. need to hold the tap for a few seconds for the tap event to be triggered. 

Did you try to reproduce this issue at http://cdn.clappr.io/
Yes.

The click on iOS11 is registered only on Long press. On older versions its fine. 
iOS 11 onwards, if you just tap on the player(container) it will not be registered, where as if you hold the tap for more than 2-3 seconds it is then registered. 
Same thing with the double click event. 

Any specific reasons as to why this could be happening only on devices running on iOS11? Any help or steps to mitigate will be helpful

**Comment by bikegriffith** [comment]
Noticed this as well. Would be curious if anyone has a workaround or thoughts on the root cause.
