### ISSUE TITLE
Is there a version for angular 2?

### ISSUE THREAD

**Issue by vaydich** [clappr/clappr#1516]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)

**Clappr Version**: 0.2.25

**Steps to reproduce**:

* first step
* then second step
* I was expecting X but instead it shows Y

Did you try to reproduce this issue at http://cdn.clappr.io/

ps: you can attach images, logs or whatever you think might be helpful.
ps: feel free to clean this if your issue is different.

**Comment by leandromoreira** [comment]
Clappr as is it's a JS library that can be incorporated into react, angular or others but we don't provide an Xjs version of it here.

**Comment by zy87302728** [comment]
@leandromoreira Can you give us a demo for how to integrated into angular2 project？

**Comment by leandromoreira** [comment]
Hi @zy87302728 someone did a directive for it https://github.com/Defina-se/angular-clappr
