### ISSUE TITLE
Using flv.js for HTML5 flv decoding?

### ISSUE THREAD

**Issue by TinkoLiu** [clappr/clappr#1517]
flv.js works by transmuxing FLV file stream into ISO BMFF (Fragmented MP4) segments, followed by feeding mp4 segments into an HTML5 <video> element through Media Source Extensions API.

This porject can be found here [https://github.com/Bilibili/flv.js/](https://github.com/Bilibili/flv.js/)

**Comment by leandromoreira** [comment]
Thanks, @TinkoLiu I think one or we can make a playback (like [dash](https://github.com/clappr/dash-shaka-playback)) that plays `.flv` :D

**Comment by andrefilimono** [comment]
Initial implementation:
https://github.com/andrefilimono/clappr-flvjs-playback

Feel free to contribute :)
