### ISSUE TITLE
Why not working on android

### ISSUE THREAD

**Issue by gualterb** [clappr/clappr#1518]
Hello!
Not working on android, on windows, linux and windows not problem.

http://live-tv.cf/video.php?vid=http://a3live-lh.akamaihd.net/i/a3hds/antena3_1@35248/master.m3u8

Code of php file
`<title>Streaming</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="http://www." type="image/x-icon" />
<body style="margin:0">
<script src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<script src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<script src="https://cdn.jsdelivr.net/clappr.chromecast-plugin/latest/clappr-chromecast-plugin.js"></script>
<div id="player"></div>
<script>var player = new Clappr.Player({
source: "<?php echo $_GET['vid'] ?>",
plugins: [LevelSelector, ChromecastPlugin],
parentId: "#player",
height: "100%",
width: "100%",
autoPlay: true,
});
</script>
</body>`

**Comment by leandromoreira** [comment]
does it show any logging error message?

**Comment by gualterb** [comment]
No, blank page

**Comment by leandromoreira** [comment]
can you try to debug the android looking at the console tab? https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by gualterb** [comment]
Hello! I am not an android user, but a friend testing in chrome if it works. it does not work in the default browser.

**Comment by leandromoreira** [comment]
We can't really help you if we don't have any logging info 😢
