### ISSUE TITLE
Another stream not working with Clappr

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1519]
I wonder how https://www.hlsplayer.net (GrindPlayer) can play this stream: http://grupomac-lh.akamaihd.net/i/004rss0k8_1@301782/master.m3u8

I've noticed that there is an extra process during the playback, maybe it give you some clue: http://grupomac-lh.akamaihd.net/crossdomain.xml

Should Clappr generate a crossdomain.xml?

**Comment by leandromoreira** [comment]
@hijuuijj clappr can't generate the file (and actually host it) `crossdomain.xml` this needs to in your server.

Clappr can't play this playlist `http://grupomac-lh.akamaihd.net/i/004rss0k8_1@301782/master.m3u8` because it is returning `403`

**Comment by hijuuijj** [comment]
Have you tried the stream from https://www.hlsplayer.net?
Would be interesting to know how crossdomain.xml loads

**Comment by leandromoreira** [comment]
This file is required if you're using `flash` based player otherwise you shouldn't need it. http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html

**Comment by hijuuijj** [comment]
I know. I'm trying to figure out how hlsplayer.net can play it.

Another [stream](https://content-aeuf2.uplynk.com/channel/7a16e3d5ffd0413ba4d8ac89688ed7cd/f.m3u8?ct=c&ad.locationDesc=vh1_channel&ad.cust_params=_fw_ae=c123b11aa670647408778a3b81a21d70&_vmn_ar=true&expand=simulcast_standard&ad.kv=_fw_ae,c123b11aa670647408778a3b81a21d70,_vmn_ar,true,_fw_vcid2,82125:vh1_97c98de42e2249649f7b8ed38b07cc80&euid=97c98de4-2e22-4964-9f7b-8ed38b07cc80&exp=1508200775&rn=-578038744&ad.euid=97c98de4-2e22-4964-9f7b-8ed38b07cc80&cid=7a16e3d5ffd0413ba4d8ac89688ed7cd&tc=1&sig=9d1794ab19cb570bbe4711d554366ef8485beb3b9a46ef90229981950d516927&pbs=85412652d29f4a75bc277de11c7d4566) playable with hlsplayer (vh1 usa)
