### ISSUE TITLE
 Video getting messed up while clappr playing HLS video with HTML5

### ISSUE THREAD

**Issue by hashtvm07** [clappr/clappr#1520]
**Browser**: Chrome (Chrome Version 61.0.3163.100)

**OS**: Windows 10 (Pro)

**Clappr Version**: 0.6.12

I have implemented HLS Player with the help of Clappr. 
When chrome plays video using HTML5 instead of flash, video gets messed up after every few minutes. 

If anyone have come across the same issue, please help.

**Comment by leandromoreira** [comment]
Hi, @hashtvm07 these things usually are tied to either your input stream (codec, camera) our your encoder/packager generating the HLS.

You can find some tools to check your stream health https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues .
