### ISSUE TITLE
HLS mimetypes case sensitive?

### ISSUE THREAD

**Issue by contra** [clappr/clappr#1522]
Just hit this issue - for the HTML5 mimetype list, the type for m3u8 is `application/x-mpegurl` but the FlashHLS and HLS canPlay functions both check for exactly `application/x-mpegURL`

If you provide `application/x-mpegurl` as the content type it will fail to return true from canPlay, which shouldn't be the case as it works fine for the HTML5 mimetype checking.

**Comment by leandromoreira** [comment]
@contra Clappr does respect the order of the playbacks, external first and then internal, therefore I think if you added `FlasHLS` it'll be used as a hls.

**Comment by contra** [comment]
@leandromoreira Ticket doesn't have anything to do with play orders - really as simple as `mimeType: 'application/x-mpegurl'` not working when it should

**Comment by kslimani** [comment]
A simple fix could be to convert mimetype to lowercase and compare with lowercase value [here](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L576).

**Comment by leandromoreira** [comment]
sorry @contra I misread.

**Comment by contra** [comment]
Keep it open.

**Comment by leandromoreira** [comment]
Keep it open

**Comment by contra** [comment]
Keep it open.
