### ISSUE TITLE
M3U8: Audio and video out of sync...

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1529]
Recently, videos and audio are out of sync... it affects as the video progresses.
Has been any change in Clappr? I have no problems with other players such JW Player or GrindPlayer.

**Comment by tchakabam** [comment]
Hey, can you provide a test stream where you observe the issue? :)

**Comment by hijuuijj** [comment]
Any stream, like this: http://hlsackdn_gl8-lh.akamaihd.net/i/hlsdvrlive_1@81183/master.m3u8

**Comment by tchakabam** [comment]
What browser and OS are you using? :)

**Comment by hijuuijj** [comment]
Chrome 62.0.3202.75 (Build oficial) (64 bits)
Windows 10

**Comment by leandromoreira** [comment]
@hijuuijj did you test on https://video-dev.github.io/hls.js/demo/ ?

**Comment by hijuuijj** [comment]
It seems to be a bug, possibly Chrome and/or nvidia drivers

**Comment by leandromoreira** [comment]
@hijuuijj double check your master input.
