### ISSUE TITLE
RTMP?

### ISSUE THREAD

**Issue by JohnMorra** [clappr/clappr#1530]
Hello!

I cant to find any script working with rtmp sources. I was trying everything but not even one is working, any ideas ? : (

**Comment by leandromoreira** [comment]
Take a look at https://github.com/video-dev/clappr-rtmp-plugin

**Comment by JohnMorra** [comment]
cool but its not working for me :( Should i just copy my link to " source:" and thats it ? i copied to my server and player not even showing. just blank white page hmmmm

**Comment by JohnMorra** [comment]
aha, also i checked with your wordpress plugin and its not working either player doesnt start. I have checked with few sample links

**Comment by flavioribeiro** [comment]
@JohnMorra can you please redirect your questions on RTMP playback to the [rtmp plugin](https://github.com/video-dev/clappr-rtmp-plugin)?
