### ISSUE TITLE
HLS stream error: No 'Access-Control-Allow-Origin' header is present 

### ISSUE THREAD

**Issue by nexobm93** [clappr/clappr#1531]
i'm trying to load m3u8 stream, doesnt work.
start=LIVE&end=END

Any ideea why?

**Comment by leandromoreira** [comment]
did you try to inform the `mimeType` since Clappr can't infer from the URL you provided?

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://telekomtv.ro.edgesuite.net/shls/LIVE$MoozDanceHD/6.m3u8/Level(545259)?start=LIVE&end=END',
  mimeType: "application/vnd.apple.mpegurl",
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

**Comment by nexobm93** [comment]
Same with mimeType :(.

I used other webplayers with HLS support and everything is ok. This type of m3u8 doesn't work, all the rest are ok. 
The error (CONSOLE)

> "[error][hlsjs: unrecoverable network fatal error, evt hlsError, data [object Object] ]"

> Failed to load {STREAM}: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'file://' is therefore not allowed access.

**Comment by kslimani** [comment]
@nexobm93 hints are in the error message : the server which serve the manifest does not send CORS headers in the HTTP response; Therefore it is the reason why HLS.JS is failing to download it.

For more details, please check [this link](https://github.com/clappr/clappr/issues/703#issuecomment-160936968).
