### ISSUE TITLE
PLAYBACK_PLAYBACKSTATE event not triggering when user play/pause

### ISSUE THREAD

**Issue by matheusrufca** [clappr/clappr#1533]
**Browser**: Chrome 61.0.3163.100 (Official Build) (64-bit)
**OS**: Windows 10
**Clappr Version**: 0.2.77

**Steps to reproduce**:

1. Go to [http://clappr.io/demo/](http://clappr.io/demo/)

2. Add the follow lines:
```
player.on(Clappr.Events.PLAYBACK_PLAYBACKSTATE ,  function (state){
  console.log('PLAYBACK_PLAYBACKSTATE ', state)
});

player.on(Clappr.Events.CONTAINER_PLAYBACKSTATE,  function (state){
  console.log('CONTAINER_PLAYBACKSTATE', state)
});
```
3. Play and pause video 

**Expected**
Show playback state on console when user play or pause video.

**Comment by hubjac1** [comment]
I have the same issue.
As workaround it's possible to add events listener in player options but it's not ideal.

```javaScript
var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  events: {
    onPlay: ( )=> console.log('Play'),
    onPause: ( )=> console.log('Pause'),
    onError: (e) => console.log('ERROR', e),
  },
});
```

**Comment by joaopaulovieira** [comment]
The resolution of issue #1607 will solve most of inconsistent states.
