### ISSUE TITLE
Stream playable with Video.js... not playable with Clappr...

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1535]
Is there any way to play this stream with Clappr? http://live2-free-mediaset.secure.footprint.net/Content/HLS/Live/Channel(CH08HA)/index.m3u8

Video.js player can play it: http://ver.hol.es/vjs.php?vid=live2-free-mediaset.secure.footprint.net/Content/HLS/Live/Channel(CH08HA)/index.m3u8

**Comment by leandromoreira** [comment]
Have already checked if it's not your source stream? anyway you should open this issue on hlsjs github repo.

https://video-dev.github.io/hls.js/demo/?src=http%3A%2F%2Flive2-free-mediaset.secure.footprint.net%2FContent%2FHLS%2FLive%2FChannel(CH08HA)%2Findex.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined

**Comment by leandromoreira** [comment]
@hijuuijj I didn't mean it in a bad way ;P it's seriously to open an issue on hls.js github since it happens with the playback too, clappr behind the scenes uses hls.js. Thanks.
