### ISSUE TITLE
unable to play m3u8 on pc works on mobile

### ISSUE THREAD

**Issue by alwayzgame** [clappr/clappr#1536]
trying to play this m3u8 

https://sonyhdslive-lh.akamaihd.net/i/LIVELINEARCHANNELFOOD_2@320047/index_1000_av-p.m3u8?sd=10&rebase=on&id=AgBnBYVjfCj1pTi0GVqEo9PHhokeqLZq8b7C40ita8wg5vwIhDBDNby41GAK8%2fQY1M8tp56Yraa0Dg%3d%3d&hdntl=exp=1511720376~acl=%2fi%2f*~data=hdntl~hmac=b857fc67abac0df031a89d76cd07ecf0453051189661d6656fbd0f3fb0c88920

doesnt work on pc but when i change user agent to mobile it works flawlessly, what am i missing in the code someone please explain with a sample code if u can please

**Comment by leandromoreira** [comment]
Please follow the [basic instruction](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues) and if the error persists, please paste the error logging (through chrome inspector window)

**Comment by hijuuijj** [comment]
"Access Denied" using user agent and usa proxy.

**Comment by leandromoreira** [comment]
This is probably not related to clappr, can you repeat the same error with the stream http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 ?

**Comment by alwayzgame** [comment]
@leandromoreira i tried playing it on http://www.streambox.fr/ it gave me 403 forbidden error but the same stream when i switch the user agent works flawlessly what is the work around?

**Comment by leandromoreira** [comment]
@alwayzgame I tried here and it's working perfect regard which platform I'm playing.

Go to http://clappr.io/demo/ and try to play with the code:

```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

```
![screen shot 2017-11-26 at 9 07 59 am](https://user-images.githubusercontent.com/55913/33239461-90f9c308-d289-11e7-8048-a49be71e56c0.png)


It's hard to see why it would response `403`, are you using a proxy on your computer?

**Comment by alwayzgame** [comment]
This is the screen shot when i try to run m3u8 it in pc or desktop mode (not working)

http://prntscr.com/hhnrw9

The same m3u8 when i tr y to run it in mobile mode [ ctrl + shift + i ] and then press [ ctrl + shift +
 m ] (working)

http://prntscr.com/hhnsx8

i hope you understand what my problem is

**Comment by leandromoreira** [comment]
@alwayzgame I think that Akamai might be filtering the access through user-agent, when you try to access on a simulated mobile it sends the HTTP header (UA) with as if it were a mobile device.

```
User-Agent:Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Mobile Safari/537.36
```

But when you try to access through your desktop it sends another UA.

```
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

The response you're getting from Desktop ([HTTP response 403](https://en.wikipedia.org/wiki/HTTP_403)) shows that this is a server problem, not a client problem (Clappr is not part of the problem). You need to properly setup your server so they can response as expected.

**Comment by alwayzgame** [comment]
so what setting shud i tweak to make it work? 
is there a way to load the mobile user agent automatically
