### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1537]
I'm using https://cdn.jsdelivr.net/gh/clappr/clappr@latest/dist/clappr.min.js (it supports CC by default)
Is there any difference with https://cdn.jsdelivr.net/clappr/latest/clappr.min.js?
What's the difference between min,js and normal?

**Comment by kslimani** [comment]
As stated in #1504 , it is recommended to use `https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js` "npm" url format.

You get more info on [jsDelivr homepage](https://www.jsdelivr.com/) about url format.

**Comment by hijuuijj** [comment]
Loading animation freezes with the latest
https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

**Comment by hijuuijj** [comment]
https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js not compatible with Firefox:
"Your browser does not support the playback of this video. Please try using a different browser"

**Comment by towerz** [comment]
Now the bump script purges automatically after npm publish: a1134bc8e97154fc427aded27c8555b1575da898. We should have no further cache issues after a new release.
