### ISSUE TITLE
Stream not playable

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1538]
https://mdslivehls-i.akamaihd.net/hls/live/571650/fdf/bitrate_4.m3u8

HTTP Status Code 200...  seems to be ok. However I can't play it with Clappr. (tried with Cors, FlasHLS...)
It works only natively (Edge or Chrome with Native HLS Playback)

Any idea?

**Comment by leandromoreira** [comment]
It is returning 403 for the keys, the m3u8 is fine but the keys are returning 403. It's not possible to play without keys. Again, this is a server-side problem, not a clappr.

![screen shot 2017-12-02 at 12 02 39 am](https://user-images.githubusercontent.com/55913/33510553-6283ae98-d6f4-11e7-972b-650b65e8dded.png)

**Comment by mohsinworld** [comment]
How can I play this? http://cdn-livetv1.metube.id/hls/rcti_240/index.m3u8 When I browse normally it starts downloading but can't play using a player. Please help me. Thanks

**Comment by leandromoreira** [comment]
@mohsinworld your problem is also a server side problem, you need to enable CORS.

![screen shot 2017-12-02 at 8 32 35 am](https://user-images.githubusercontent.com/55913/33514460-79363e20-d73b-11e7-8bed-567a531d86bd.png)

**Comment by hijuuijj** [comment]
Something like this? http://gatekeeper.mediaset.es/key/fdf/akamai

**Comment by hijuuijj** [comment]
This one can be played with Clappr using Chrome... but not using Clappr with Edge.
However GrindPlayer and StrobeMediaPlayback can play it using Edge.

http://telecinco-mediaset-esp-live.secure.footprint.net/mediaset/cuatro/index.m3u8
