### ISSUE TITLE
unable to play my own m3u8

### ISSUE THREAD

**Issue by alwayzgame** [clappr/clappr#1540]
**Browser**: Chrome Latest Version

**Clappr Version**: 0.2.25

**Steps to reproduce**:
im streaming my own stream on my nginx server for which i have a wide open CORS config setup have enabled access control origin, however im unable to play it on clappr player or demo site or streambox im getting 304 error and 200 error, if i play the same m3u8 on microsoft edge or vlc it works fine 

304 not modified error : http://prntscr.com/hj76if

Console error: http://prntscr.com/hj795j

Did you try to reproduce this issue at http://cdn.clappr.io/: YES i tried here is the result 

http://prntscr.com/hj79mv

http://prntscr.com/hj79qv

i have added the headers from https://enable-cors.org/server_nginx.html

**Comment by leandromoreira** [comment]
It's still a cors problem as you can see.

**Comment by alwayzgame** [comment]
stream(m3u8) works on Flashhls demo page but does not work on hls demo page, and on which folder should we have the cors setup on nginx i mean this example
`location / {
  add_header 'Access-Control-Allow-Origin' '*';
  add_header 'Access-Control-Allow-Credentials' 'true';
  add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
}`
