### ISSUE TITLE
Conflict between markers plugin and playback speed plugin

### ISSUE THREAD

**Issue by zijian85** [clappr/clappr#1543]
Hi，I have just tested clappr player, but there is conflict between markers plugin and playback speed plugin. Only one plugin have affect. Code  as follows:

`var player = new Clappr.Player({
    				source: 'http://tjenkinson.me/clappr-thumbnails-plugin/assets/video.mp4',
  					poster: 'http://clappr.io/poster.png',
  					autoPlay: true,
  					width: '100%',
  					height: '100%',
    				parentId: "#player",
    				watermark: "/Public/images/logo.png", position: 'top-right',
   			 		watermarkLink: "http://example.net/",
   			 		disableVideoTagContextMenu: true,
    				plugins: {
    					core: [ClapprMarkersPlugin],
    					core: [PlaybackRatePlugin],					
  					},
  					
  					markersPlugin: {
    					markers: [
      						new ClapprMarkersPlugin.StandardMarker(30, "this is a test"),
      						new ClapprMarkersPlugin.StandardMarker(120, "this is a test1"),
      						new ClapprMarkersPlugin.StandardMarker(300, "this is a test2"),
      						new ClapprMarkersPlugin.StandardMarker(800, "this is a test3"),
   						 ],
   						 tooltipBottomMargin: 17 // optional
  					},
  					playbackRateConfig: {
    					defaultValue: '1x',
    					options: [
    						{value: '2.0', label: '2x'},
    						{value: '1.5', label: '1.5x'},
    						{value: '1.0', label: '1x'},
        					{value: '0.5', label: '0.5x'},	
    					]
  					}
  					
    			});`

At the place which plugins set:

                            `plugins: {
    					core: [ClapprMarkersPlugin],
    					core: [PlaybackRatePlugin],					
  					},`

If set PlaybackRatePlugin under the ClapprMarkersPlugin, PlaybackRatePlugin work well, but ClapprMarkersPlugin  don's work.

If set ClapprMarkersPlugin under the PlaybackRatePlugin, ClapprMarkersPlugin work well, but PlaybackRatePlugin  don's work.

                          `plugins: {
    					core: [PlaybackRatePlugin],
    					core: [ClapprMarkersPlugin],					
  					},`

I have tested in chrome and safari, all the result is same.

Any idea?

**Comment by leandromoreira** [comment]
@zijian85 try:
```
plugins: [PlaybackRatePlugin, ClapprMarkersPlugin]
```

**Comment by zijian85** [comment]
@leandromoreira  It work, Thanks.  By the way, how to force flash to play hls ?  I get code as follows:

`plugins: {playback: [Clappr.Clappr.Flashls]}`

But it does not work. Need some js be add in ? Could you give me a flashhls link ?Thanks so much.

**Comment by kslimani** [comment]
@zijian85  like @leandromoreira previously described, you should be able to configure Clappr with :

```
plugins: [Clappr.FlasHLS, PlaybackRatePlugin, ClapprMarkersPlugin]
```

Note : you don't need to specify plugin type (`playback` or `core`) in the `plugins` configuration option. Plugins will be automatically resolved by player core.
