### ISSUE TITLE
FlasHLS not compatible with Edge?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1548]
I let you know that none of my streams works using Clappr FlasHLS from Microsoft Edge. However other flash players (like GrindPlayer and StrobeMediaPlayback) are working without problems.

**Comment by towerz** [comment]
@hijuuijj what kind of issue are you having with the FlasHLS playback? Can we have more details on this?

Actually, you shouldn't need to use FlasHLS on Microsoft Edge, since the HLS playback works on Edge.

**Comment by hijuuijj** [comment]
Try to play this stream using FlashHLS: http://telecinco-mediaset-esp-live.secure.footprint.net/mediaset/telecinco/index.m3u8

I know Edge can play native HLS but I'd like to use Clappr player anyway.
