### ISSUE TITLE
38861cba61c66739c1452c3a71e39852.ttf -- file not found or wrong path

### ISSUE THREAD

**Issue by drlukacs** [clappr/clappr#1550]
**Browser**:  Firefox 57.0

**OS**:  Slackware 14.2 (64 bit)

**Clappr Version**: 0.2.25

**Steps to reproduce**:

* Install JW AllVideo on a Joomla site.
* Load google fonts
* In css, select said google fonts for body and/or all headers
* result: clappr attemps to download 38861cba61c66739c1452c3a71e39852.ttf from the website itself (instead of the CDN).

Did you try to reproduce this issue at http://cdn.clappr.io/

![screenshot85](https://user-images.githubusercontent.com/15809267/33861891-78ebcdea-deb6-11e7-956a-1ca5e88f83ec.jpg)

**Comment by kslimani** [comment]
@drlukacs check [this answer](https://github.com/clappr/clappr/issues/1153#issuecomment-249427459), it should fulfils your issue.

**Comment by drlukacs** [comment]
Thank you @kslimani for the reply; however, I am not sure if it answers the question: this problem happens only if one tries to use Google fonts. 

Why is that?

**Comment by kslimani** [comment]
@drlukacs i think (to confirm) that the font is not loaded by all browsers and this is the reason you are not getting the 404 errror all the times.

**Comment by drlukacs** [comment]
@kslimani When is clappr supposed to load the font? (What I find is that the 404 error occurs only when I am trying to use Google fonts.) 

Are you saying that the problem is with the jwAllVideo code?

http://sandbox.topgroups.ca/vumkvqvknn/THREE/en/advocacy/air-passenger-bill-of-rights/airline-passenger-rights-will-you-be-protected

**Comment by towerz** [comment]
@drlukacs @kslimani there seems to be an error in the webpack config. The url for the .ttf is not considering the baseUrl correctly. I'll check this out.

**Comment by kslimani** [comment]
@drlukacs i apologize, i missreaded your issue, i first thinked you were bundling Clappr _(which require to copy serve assets like fonts)_.

**Comment by drlukacs** [comment]
Thank you @towerz. Any luck with a fix?

**Comment by towerz** [comment]
@drlukacs I'm just testing the fix. I'm hoping to release it later today.

**Comment by towerz** [comment]
cc7b56b053b3d43e24729820c9ce484239934e51 fixes this issue. I'll release a new version soon.

**Comment by drlukacs** [comment]
Thank you, @towerz. Will the file at the following link be also updated?

https://cdn.jsdelivr.net/gh/clappr/clappr@latest/dist/clappr.min.js

**Comment by towerz** [comment]
@drlukacs yes, I'm preparing a release right now.

**Comment by drlukacs** [comment]
Thank you, @towerz, for your fast response. The issue seems to be resolved now.
