### ISSUE TITLE
Flash Playback and MediaControl 

### ISSUE THREAD

**Issue by aditya0711** [clappr/clappr#1551]
**Browser**: Chrome Version 63

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Windows

**Clappr Version**:  latest

**Steps to reproduce**:
any flash player based playback(testing with RTMP Plugin) 

The mediaControl is not updated when the playback is playing, or playback doesn't respond to any of the mediaControl action. 

![image](https://user-images.githubusercontent.com/14818486/33934688-9cc953d4-e034-11e7-8941-7853ef4ee088.png)

**Comment by Fiorello** [comment]
Hi, i can confirm the same issue with clappr(0.2.90) and rtmp-plugin (0.0.20).
Does anyone have a solution?
