### ISSUE TITLE
Broken Loading Animation in Clappr v0.2.79

### ISSUE THREAD

**Issue by sainrew** [clappr/clappr#1552]
**Clappr Version**: 0.2.79

![clappr_bug](https://user-images.githubusercontent.com/7043681/34034057-86d13ab6-e1af-11e7-8a89-70ffab5e2b4c.jpg)

**Clappr Version**: 0.2.78

![clappr_no_bug](https://user-images.githubusercontent.com/7043681/34034457-38e1655e-e1b1-11e7-8056-3547e92be478.jpg)

**Comment by kafeltz** [comment]
In the old version, the style is included as follow:
![image](https://user-images.githubusercontent.com/1765469/34254248-5f4c2e74-e632-11e7-85d4-550cb5a64e6d.png)

And in the new version is not, as follow: 
![image](https://user-images.githubusercontent.com/1765469/34254257-6e93273e-e632-11e7-983d-c13fe955ab94.png)

Something related with the lasts commits.

**Comment by leandromoreira** [comment]
I think we've changed some aspects of how we deal with CSS cc @towerz isn't?

**Comment by towerz** [comment]
@leandromoreira @kafeltz we changed the player CSS to not be nested in the player elements, but instead condensed into a single `<style>` tag.

Perhaps there's something missing in the spinner style. I'll check it.
