### ISSUE TITLE
Not Working preload For HLS Clappr

### ISSUE THREAD

**Issue by FOXIY** [clappr/clappr#1556]
Hello everybody

I can not activate preload for hls

sample code I used : 

> var playerElement = document.getElementById("player-wrapper");
> 
> var player = new Clappr.Player({
>   source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
>   poster: 'http://clappr.io/poster.png',
>   mute: true,
>   preload: 'metadata',
>   height: 360,
>   width: 640
> });
> 
> player.attachTo(playerElement);

I've tried every kind, preload not working.

thanks everybody

**Comment by techkid6** [comment]
Hi there, I'd like to re-open this!

Currently testing with a player at https://test.indiecasttv.com/player/PxrTdpg. I have `preload` set to `auto`, though `auto` or `metadata` both do not do any preloading prior to clicking "play". I'm running Clappr 0.3.4 with no external plugins enabled.

**Comment by kenfouo** [comment]
> Salut, j'aimerais rouvrir ça!
> 
> Test en cours avec un joueur sur https://test.indiecasttv.com/player/PxrTdpg . J'ai `preload`mis à `auto`, bien que `auto`ou les `metadata`deux ne font aucun préchargement avant de cliquer sur "jouer". J'exécute Clappr 0.3.4 sans plugins externes activés.

I have the same problem; in fact i want the video to preload 3 seconds after the player initializes.
I used all the preloads without success.

any help would be welcome thank you
