### ISSUE TITLE
your browser does not support playing this video, Try to use different browser

### ISSUE THREAD

**Issue by zijian85** [clappr/clappr#1559]
Hi,

Some users show the notice 'your browser does not support playing this video, Try to use different browser'  when watch m3u8 video using clapper.  what cause this problem ? How to fix it ?

One user: Windows 7 with all browsers have this problem.

Thanks
<img width="613" alt="2018-01-06 5 59 03" src="https://user-images.githubusercontent.com/30042173/34638649-554d8cb6-f30b-11e7-80b5-82eef01d98b6.png">

**Comment by kslimani** [comment]
@zijian85 : this may happen if the HLS URL does not ends with `.m3u8` extension.

This may be fixed by adding `mimeType: 'application/x-mpegURL'` to player options. (_if source url is HLS manifest_).

**Comment by RvLDSDM** [comment]
Experiencing the same! Big Issue. 

Clapper no longer works with Nginx RTMP HLS streams getting this message under Windows 10 Chrome AND Firefox.

**Comment by ConnorLinfoot** [comment]
Also having this issue, reverting back to 0.2.80 (https://cdn.jsdelivr.net/gh/clappr/clappr@0.2.80/dist/clappr.min.js) seems to resolve for now.

**Comment by towerz** [comment]
@RvLDSDM can you provide a sample URL so we can test this issue?

**Comment by towerz** [comment]
5eea6f6 should fix this issue. There was a problem in the playback priority on both 0.2.81 and 0.2.82. I'll deprecate those versions on NPM and release a new one with the fix.

Thanks for reporting @zijian85, @RvLDSDM and @ConnorLinfoot.

**Comment by zijian85** [comment]
@towerz It means if I get the new version clappr.min.js, it should fix this issue ?

**Comment by towerz** [comment]
@zijian85 if you use 0.2.83 you won't have this issue anymore.

**Comment by zijian85** [comment]
@towerz where to get the 0.2.83 version ?  I use this one  https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js.  Is it 0.2.83 ?

**Comment by kslimani** [comment]
@zijian85 you can verify this information using the global `Clappr.version` property.

Here an example : https://jsbin.com/kazatozuto/edit?html,console

**Comment by RvLDSDM** [comment]
we all use that one I guess, so it is not yet online unless you maually 
go to 0.2.83, which you normally won't because Google gives you extra 
points for using the CDN (Eco, Environment) and you always want to use 
the latest version automatically


Op 7-1-2018 om 03:22 schreef zijian85:

**Comment by zijian85** [comment]
Thanks so much . I have get the 0.2.83 version  
by  'https://cdn.jsdelivr.net/npm/clappr@0.2.83/dist/clappr.min.js'.

And this new version solved my problem. Good job.

Thanks all.
