### ISSUE TITLE
NPM version not compatible with Firefox

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1560]
https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

"Your browser does not support the playback of this video. Please try using a different browser"

No problems with https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

**Comment by hijuuijj** [comment]
Who maintains that file? what is the difference between both? (besides CC)

**Comment by towerz** [comment]
@hijuuijj I need to check why the current jsdelivr is still referencing an invalid version. The second link is using an older URL format. Both are maintained by jsdelivr itself, but I believe the second one uses our latest github tag, where the newer one uses NPM.

**Comment by MartinKolarik** [comment]
jsDelivr team member here - I can't say why the latest version doesn't work in FF, but the first (correct) link is version 0.2.83, the second is 0.2.66 (and doesn't get updated anymore).

**Comment by towerz** [comment]
@MartinKolarik actually, the first one is version 0.2.82, which has a bug and was deprecated on NPM. The latest version is still not updated to 0.2.83 on jsdelivr.

**Comment by MartinKolarik** [comment]
>the first (correct) link is version 0.2.83

More precisely, it could be any version released in the past week, since that's how long it could take for changes to propagate. Is this something that was recently fixed?

**Comment by towerz** [comment]
@MartinKolarik yes, it was fixed yesterday.

**Comment by MartinKolarik** [comment]
I see, I've just manually purged the cache for that link so you should get the latest version now. If you are interested, you can do this automatically in your build script every time you release a new version by sending a GET request to http://purge.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js That way there's no delay.

**Comment by MartinKolarik** [comment]
Note that jsDelivr does have every new version immediately after releasing it, so you can always use a link with the version specified in the URL, such as https://cdn.jsdelivr.net/npm/clappr@0.2.83/dist/clappr.min.js This delay only applies to URLs which don't use exact version numbers.

**Comment by towerz** [comment]
Great! Thank you very much, @MartinKolarik!

**Comment by hijuuijj** [comment]
https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js updated and working in Firefox.

**Comment by towerz** [comment]
Now the bump script purges automatically after npm publish: a1134bc8e97154fc427aded27c8555b1575da898. We should have no further cache issues after a new release.
