### ISSUE TITLE
onReady event not fired when source is an m3u8

### ISSUE THREAD

**Issue by marbleman** [clappr/clappr#1563]
**Browser**: Chrome  63.0.3239.132 , Firefox Version 57.0.4 and all others such as Safari etc.)

**OS**: Windows (7, 8 and 10)

**Clappr Version**: 0.2.86 (as of today)

**Steps to reproduce**:
 Use  [http://clappr.io/demo/](url)
and add onReady event:
`var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  events: {
    onReady: function() {alert('onReady triggered')}
 }  
});

player.attachTo(playerElement);`

When clicking "run", the onReady event will fire.

Now modify the source to 
`https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8`

onReady will not fire unless you hit the play button.
It does not matter whether m3u8 contains multiple streams or just a single stream.

For my understanding onReady is supposed to trigger when player setup has completed. Its behaviour should not depend on the type of source. Or am I missing something important?

**Comment by marbleman** [comment]
Addition: It's getting more confusing...

On Chrome 63.0.3239.132 onReady will fire for an m3u8 but _only_ if 'poster' is NOT an empty string, null or missing in the config object. Firefox and Safari still do not fire onReady in any case...

**Comment by leandromoreira** [comment]
@marbleman I just tested on my Firefox 57.0.4 (MacOS) and everything works as expected and I tried with an mp4 and an hls.

![screen shot 2018-01-23 at 10 56 45 pm](https://user-images.githubusercontent.com/55913/35308860-ce2423ec-0090-11e8-9368-7a302559641e.png)

**Comment by marbleman** [comment]
And onReady fires immediately when you hit the "Run" button that evaluates the code? For me it does not! Not even on Firefox on macOS... It just fires when I click the video to play (at the same time as onPlay)... 

Results as:
N: onReady fires not on player ready but only together with onPlay 
Y: onReady fires correctly when player is ready (and still idle... so independent of onPlay)

Tested so far on:
Windows 7:
   - Firefox 57.0.4: progressive: **Y**, m3u8: **N**
   - Chrome 63.0.3239.132: progresssive: **Y** , m3u8: **Y** (but only if poster paremeter is not empty)
   - InternetExplorer 11.0.9600: progressive: **Y**, m3u8: **Y** (even if poster is empty! Amazing: haven't seen something working on IE that fails elsewhere for years! ;)
   - Opera 50.0.2762.67 : progresssive: **Y** , m3u8: **Y** (but only if poster paremeter is not empty - same as Chrome) 

macOS 10.12.6 (Sierra):
    - Safari 11.0.3: progressive: **Y**, m3u8: **N** 
    - Firefox 58.0 : progressive: **Y** , m3u8: **N**
    - Chrome 63.0.3239.132: progressive: **Y**, m3u8: **N** 

Will test on Win10 later but expect a similar behaviour. It is somehow odd that Chrome behaves different on macOS and Windows. This issue appears to me as if some sort of exception keeps clappr instantiation from reaching onReady state - but I cannot see any. I have also checked isReady and it says 'false'.

**Comment by leandromoreira** [comment]
Hi @marbleman yes, I could replicate what you've described my bad, I didn't pay attention to hls streaming. I can confirm this bug.

**Comment by leandromoreira** [comment]
Thank you very much @marbleman

**Comment by wahajdar** [comment]
Hi @leandromoreira, here are some observings regarding Events propagation;

. PLAYER_READY depends on CORE_READY event
. CORE_READY gets fired once all Containers crafted from container_factory.js are resolved
. Each Container is resolving upon CONTAINER_READY event
. CONTAINER_READY getting fired on PLAYBACK_READY event from Playback components e.g. hls.js, html5_video.js etc.
. A Playback Component is supposed to fire PLAYBACK_READY in _ready() method, bubbling up the chain from BOTTOM(PLAYBACK_READY) to TOP(PLAYER_READY)

In /playbacks/hls/hls.js, _ready() method gets invoked by _setup()  but _setup() gets called under play() method i.e. the time stream play is initiated.

We can not move the _setup() invocation to constructor(), resulting in HLS Source load on Player boot.

One way could be to override parent implementation of render() method in hls.js (being inherited from html5_video.js) in a way, preserving parent functionality and call _ready() within that function and removing any other references to toggle _ReadyState and trigger PLAYBACK_READY only once.
![117aa1157b50744811bdb1283968a39a](https://user-images.githubusercontent.com/25760541/36472671-508291f4-1714-11e8-8790-b28c4281ab17.png)

Please have a look at Pull Req #1578 

Platform Sepcs;
Windows 10 Build 16299

Chrome 64.0.3282.167,
Edge 41.16299.248.0,
Firefox 58.0.2 (64-bit)

Spare me if found wrong, I am a newbie here :p
