### ISSUE TITLE
DVR hls stream stops, when tap for controls

### ISSUE THREAD

**Issue by perohu** [clappr/clappr#1564]
**Browser**: Chrome 64
**OS**: Android 7.0
**Clappr Version**: 0.2.85

When I tap on the stream while it is playing, playback stops. It happens only with DVR streams.

DVR stream example: https://player-infocam.infornax.hu/test-dvr.html   (NOT working as expected)
nonDVR  stream example : https://player-infocam.infornax.hu/test-nondvr.html  (working as expected)

Thank you

**Comment by perohu** [comment]
Am I the only one with this? Maybe I do something wrong?

**Comment by kslimani** [comment]
AFAIK : if HLS stream is live with DVR, the player allow to "pause" the stream (_also display a button to catch with live_), therefore this also enable the internal "click_to_pause" playback plugin (which may explain why video pause when you tap the screen).

For HLS live stream without DVR the behaviour is different : the stream cannot be "paused" and i think that the "click_to_pause" playback plugin is not enabled. (to confirm!).

**Comment by perohu** [comment]
Thank you for this info!
player.getPlugin('click_to_pause').disable() did the trick :)

BTW it would be great if clappr could distinguish between tap on the screen and a mouse click.

**Comment by kslimani** [comment]
> BTW it would be great if clappr could distinguish between tap on the screen and a mouse click.

I don't known if it is technically possible. Clappr is internally using a [custom Zepto](https://github.com/clappr/clappr-zepto) build. I remember seen some issues with Chrome browser which temporary constrained to disable some screen tap/mouse click handling feature.

**Comment by perohu** [comment]
As a workaround I did this:

`var isTouch = (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0));`
`if ( isTouch ) player.getPlugin('click_to_pause').disable();`

It works with most (but not all) devices.
