### ISSUE TITLE
Can't translate to hungarian

### ISSUE THREAD

**Issue by perohu** [clappr/clappr#1569]
**Browser**: all

**OS**: all

**Clappr Version**: 0.2.85

Did you try to reproduce this issue at http://cdn.clappr.io/
YES

I try to translate clappr as discribed here: https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md
Unfortunately it does not work.

Here is my config: https://player-infocam.infornax.hu/test-i18n.html
As you can see 'Live' and 'Back to live' are not translated.

I remember it worked with older versions

Thank you for any help!

**Comment by andrefilimono** [comment]
Fixed in #1576
