### ISSUE TITLE
Conflict css page

### ISSUE THREAD

**Issue by Setsusan** [clappr/clappr#1570]
In clappr v0.2.80 and higher applies styles to the page that breaks the layout in some cases..

for example: `[data-watermark] {
  position: absolute;
  min-width: 70px;
  max-width: 200px;
  width: 12%;
  text-align: center;
  z-index: 10;
}`,

and similar apply to all page elements, which can break the layout,
in earlier versions there was a different behavior.

**Comment by towerz** [comment]
@sainrew there seems to be a missing selector over there. Those rules usually are applied to player children, so it shouldn't have such conflicts.

We need to check those rules and add selectors accordingly.

**Comment by sainrew** [comment]
@towerz checked earlier versions of the player in more detail, it seems that the conflict with watermark was also earlier (v0.2.78 and below), but the styles were added only when using watermark and after initializing the player, for this reason I did not notice it before

**Comment by Setsusan** [comment]
#1735
