### ISSUE TITLE
Syncing live HLS stream between various Clappr players as closely as possible?

### ISSUE THREAD

**Issue by MasterEvilAce** [clappr/clappr#1571]
**Browser**: Chrome  64.0.3282.167
**OS**: Windows 10 x64
**Clappr Version**: 0.2.86

I've got a live HLS stream going (via nginx and the RTMP module) and I'm trying to get multiple Clappr players to be as in-sync as possible. All users will access the clappr player from the same site, but the latency difference can be drastic between all players. 

Watching locally, the player is about 6-15 seconds delayed from the livestream. This is perfectly fine. Outside users (via internet, different browsers but same player page) seem to experience 10-30s delay.
I don't particularly care about  how much delay there is, but I am interested in the stream being as sync'd up and as low a latency DIFFERENTIAL as possible.

I'm wondering if there are any settings available, even if not directly exposed, that could allow things to be more in-sync, even if that means additional delay from the live stream itself.)

In my testing, many things affect this. Pardon my terminology as it tends to vary between circles. If I have  5 second fragments(segments?), and 10 fragments per playlist, it seems the player may choose to start at any of the fragments near the end of the list (latest fragments.) This already means that one person's player may start at the 3rd to last fragment, when another person who has already been watching is just finishing that fragment and starting the next. That's already a 5-second differential, even if both players BOTH chose the 3rd to last fragment, but the players loaded at different times.

Using a smaller fragment size (1 second) tends to get players more in-sync, as this same scenario would theoretically end up with at most a 1-second differential. 
In testing, I've still seen 5-6 seconds delay between players (my phone on 4G vs a friend in a different state.)
It seems like disabling caching of the .ts files gets us even closer (2 seconds delay), but perhaps that is a coincidence in just restarting/refreshing everything. Is it possible that disabling caching of .TS files somehow invalidates the player from using those, causing it to catch up? Seems like this prevents other ideas such as using a CDN or other things in the future.

Keeping the playlist short does seem to also help tremendously (12 one-second files instead of 60 one-second files), for reasons I'm unsure of, unless each device/browser has a different preference at which .ts fragment to start at, regardless of them all being Clappr.

Please let me know if anyone has any ideas in regards to this. The ideal solution would be to have everyone have a 30 second buffer (delay) from the ACTUAL live stream, but all kept in-sync, so internet hiccups wouldn't be an issue.

**Comment by Hirbod** [comment]
Such an important and legit question... unanswered :/

**Comment by leandromoreira** [comment]
@MasterEvilAce you can try to make your segments like 2s to 3s and determine the number of segments before the edge to get.

```javascript
Clappr.new({src:...., hlsjsConfig: {liveSyncDurationCount:2}})
```

**Comment by flavioribeiro** [comment]
this can be helpful too https://medium.com/freshdevelopers/implementing-lhls-on-hls-js-4fc4558edff2

**Comment by MasterEvilAce** [comment]
Sorry for not responding earlier.
My current implementation is as follows:
Clappr with hlsjsconfig of liveSyncDuration: 10, liveMaxLatencyDuration: 20, on a stream with HLS segment size of 1second and a keyframe every 1 second.

I use liveSyncDuration (not the count variation) for the hope that it does black magic and tries to actually play 10 seconds from the end of the playlist, regardless of segment size. In my experience it doesn't really work this way, as it seems it's not going to start playing a segment halfway through (it's always going to start from the start of a full segment.) So if you have segment sizes of 5 seconds... one player starts to play, and 3 seconds later another player starts... you have a 3 second delay between those two players. Going with a 1 second segment limits this, and you're either sync'd up or you're off by a second (optimally.) That's just my experience, I have no idea the actual implementation of it.

Obviously with a segment size of 1 second, the stream is GUARANTEED to always be off at least 1 second from live. Additionally, it seems like there's around an extra second caused by having to download a new playlist, process it, download any chunks, etc. I simply am not able to achieve < 2 second delay from live even over the LAN. Also, like I said in the paragraph above, there's the additional gotcha where lets say a player downloads the playlist, and just 100 milliseconds later the playlist is actually updated with a new segment. If another player downloads that new playlist, then you've already introduced ~900ms of latency between the two players, because one started playing an older segment while the other started one segment ahead (because 10 seconds from the end of the playlist is now a different segment.)

So, with a liveSyncDuration of 10, the stream is actually ~12 seconds off of live for me, and  ~12-13, sometimes 14 seconds off for people outside my network. This means other players can be in-sync with me, or they are typically off by 1 second. If there's network issues (slow download or lots of latency) then the player seems to drag on and not start playing immediately.. this will introduce an additional delay. I simply have no idea how to allow those people to re-sync the player, unless the player itself falls 10 seconds behind (max sync duration limit.) I can lower this amount, but it can cause issues with network hiccups, and it just seems better to gracefully allow them to fall behind. Even just a 5 second difference between syncDuration and maxSyncDuration is cutting it close, IMO.

Lately, it also seems that the newer Clappr versions sometimes don't start playback immediately. On chrome it's usually fine, but on Edge and Firefox sometimes it'll be 3-5 seconds before the player starts to actually play the content.. and by then you've already added more delay. It FEELS like the syncDuration logic takes place once the playlist is first loaded, and so if there's a delay between that and actually playing the content, then anything can happen and there's no guarantees unless it hits the maxSyncDuration limit and "resets."

So, for now I guess it seems "good enough" unless developers are actively looking into improving the situation. Most viewers outside my network are 1 second or less off from me. Sometimes people are an additional second or few off, and there's just nothing that can be done in those situations. Refreshing the page doesn't even do anything really, as the content will keep playing from exactly before you refreshed.

For what it's worth, I'm also not sure if varying fragment sizes messes with the playback/syncDuration logic. I'm running nginx+rtmp and streaming with OBS w/ VBV and a 1 second keyframe. Occasionally it will generate a segment that is > 1 second, but typically < 2 seconds long. If this happens, then nginx sets the playlist target segment duration to 2 seconds instead of 1, even if all the other segments are 1 second long. Whenever this happens I've noticed some very weird/inconsistent behavior with trying to sync players, but I haven't actually tested it, nor do I have a reliable way to generate this sort of test. Basically, I think HLS.js assumes that all of the segments are of target duration, and doesn't actually look at each segment length to determine how many seconds from the end of the playlist that we are. So if the target duration varies... more hiccups are added.
