### ISSUE TITLE
How to replace/customize SeekTime.getSeekTime()

### ISSUE THREAD

**Issue by kad3nce** [clappr/clappr#1579]
I would like to customize the behavior of the `SeekTime` core plugin. I'm going to use Clappr to playback a non-live m3u8 video of a recorded event. I would like the seek time to show the actual time when scrubbing.

Put another way, if the video was recorded from 10am EST to 12pm EST, then the seek time when playing back the video should start at 10:00:00 AM EST and end at 12:00:00 PM EST.

I spent some time looking at the code in `seek_time.js` and it looks like the actualLiveTime parameter is for live streams only and doesn't quite fit my use case.

What is the most precise way to replace `SeekTime.getSeekTime()` with my own code? I'm guessing by providing my own `SeekTime` class in Clappr's plugin config, but without examples, I'm not sure exactly how to accomplish that.

I'm also thinking it would be great to subclass the core `SeekTime` class, rather than forking/reimplementing it entirely, but again, I'm not sure how to accomplish that.

**Comment by kslimani** [comment]
Maybe using the `Events.CONTAINER_TIMEUPDATE` event or something similar with an UICorePlugin.

For example, take a look at [this plugin](https://github.com/tjenkinson/clappr-thumbnails-plugin) source code : it may inspire you to satisfy your needs.

**Comment by kad3nce** [comment]
Excellent. I spent a bit of time looking at the code. It looks like what the plugin accomplishes is similar enough to what I'd like to do that I should be all set.

I'll likely just end up hiding the default seek time indicator, then follow `clappr-thumbnails-plugin`'s lead by embedding a new element containing the custom time.

Thanks so much! 🙏
