### ISSUE TITLE
Watching time in stats plugin

### ISSUE THREAD

**Issue by andrefilimono** [clappr/clappr#1581]
Is it worth to take into account the time when the video was paused as watching time?

**Comment by leandromoreira** [comment]
I don't think so, that's why we try to [discount this time](https://github.com/clappr/clappr-stats/blob/master/src/clappr-stats.js#L91-L114).

**Comment by andrefilimono** [comment]
Oh, I overlooked this plugin, thanks!
But the [internal plugin](https://github.com/clappr/clappr/blob/master/src/plugins/stats/stats.js) doesn't handle pauses.

**Comment by leandromoreira** [comment]
I think @towerz and others are planning to either drop the internal plugin or make it be the clappr-stats, is that right?

**Comment by flavioribeiro** [comment]
+1 for dropping the internal plugin and keep https://github.com/clappr/clappr-stats the official
