### ISSUE TITLE
Ipads

### ISSUE THREAD

**Issue by mufin695** [clappr/clappr#1584]
**Browser**: Safari 

**OS**: all ipads

**Clappr Version**: 0.2.25

anyone having issues with clappr playing m3u8 streams? I don't have an ipad to test on but people seem to be having issues...

**Comment by towerz** [comment]
@mufin695 are you still using 0.2.25 or was it a typo? This version is a little over 2 years old.

I tested the latest version using an iPad Pro 12.9 1st gen on http://clappr.io/demo/ and it worked normally. I used the stream from https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8 for my test.

**Comment by mufin695** [comment]
@towerz Yes, sorry that was a typo.

**Comment by leandromoreira** [comment]
@mufin695 did you test as @towerz have suggested? 

Going to http://clappr.io/demo/ and test with the HLS https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8 ?

**Comment by perohu** [comment]
I have problems on iOS too. My live streams are working great. But I create byte-range hls archives, which are working with provider "hls", but not working on iOS (HTML5)
Demo: https://archives-infocam.infornax.hu/test.html
I'm not sure if it is an issue with clappr, maybe I misconfigured the webserver? 
Unfortunately I'm not familiar with debugging iOS devices, so I'm a bit lost now

**Comment by kslimani** [comment]
@perohu on iOS, which browser are you using ?
Clappr player is internally using the hls.js library for HLS stream playback.
But on some iOS devices/browsers, it *may* uses native HTML5 video capabilities for HLS playback _(instead of hls.js library)_.
Maybe it is related to your issue ?

**Comment by perohu** [comment]
@kslimani I try with Safari.
I think that on iOS devices (I mean iPhone/iPad) Safari does not support MSE, which is used by hls.js. 
I collect statistics from viewers and I always saw "html5_video" as provider in use on iOS.
I don't think it is a problem, as iOS support HLS natively, so it should work. 
It is only not working if I generate byte-range playlist. With separate segments it is working fine with "html5_video" provider. But it so hard to maintain that many small files on our storage, so I really like to make this work with byte-ranges. 
I've just found out that it is not working with Flashls too. (Tried it with WinXP+FF)
It has warning in javascript console: 
> WARN:I/O Error while loading fragment:invalid content received

**Comment by kslimani** [comment]
@perohu if this feature is not supported by native player (html5_video provider) there may be nothing possible to do in Clappr player. You should also try with Chrome browser as it will use hls.js for playback with MSE.

**Comment by perohu** [comment]
Is it possible that Apple does not support its own stream format? :)

**Comment by kslimani** [comment]
Depending on iOS/browser version, i think it *may* be possible. Currently, i don't have access iOS devices to performs tests. I suggest you should performs these tests to ensure this is not the case.

**Comment by leandromoreira** [comment]
Please make sure your [hls stream is correct](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#hls-analyzer-usage-example), sometimes your stream is the culprit.

**Comment by perohu** [comment]
I switched back from fmp4 to mpegts. It is now working on iOS too with byterange playlist.
