### ISSUE TITLE
Does not fill the iframe (or window)

### ISSUE THREAD

**Issue by Netherdrake** [clappr/clappr#1585]
**Browser**: Any
**OS**: Any
**Clappr Version**: latest

Placing the player in the iframe is a convenient embedding option. 

I have discovered some strange behaviors:

1.) The player will not fill 100% of horizontal or vertical space when `height` and `width` properties are set at `100%`. I've enabled the iframe border for ease of seeing it in action.
![screenshot from 2018-02-26 05-03-26](https://user-images.githubusercontent.com/3516903/36868380-7186025c-1d98-11e8-957b-5920272886de.png)

2.) When `width` and `height` are set to `window.innerWidth` and `window.innerHeight`, the player won't load.
![screenshot from 2018-02-26 05-03-06](https://user-images.githubusercontent.com/3516903/36868509-d1fb2d88-1d98-11e8-95cf-560e7658eabd.png)

3.) When `window.innerX` values are bumped up a bit, the player loads, but the iframe loads ugly scrollbars.
![screenshot from 2018-02-26 05-02-03](https://user-images.githubusercontent.com/3516903/36868565-01389ee6-1d99-11e8-8732-06ed3f8b9ef3.png)

As it turns out, the issue is not constrained to `iframe`.

In the regular browser window, the player also won't load edge-to-edge. 

```html
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Player</title>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
    </head>
    <body>
        <span id='player-wrapper'></span>
        <script>
            var playerElement = document.getElementById("player-wrapper");

            var player = new Clappr.Player({
                source: 'http://clappr.io/highline.mp4',
                poster: 'http://clappr.io/poster.png',
                mute: true,
                height: '100%',
                width: '100%'
            });

            player.attachTo(playerElement);
        </script>
    </body>
</html>
```

**Comment by flavioribeiro** [comment]
ages ago I made [this](https://github.com/flavioribeiro/clappr-iframe) not sure if it's helpful and if its still working

**Comment by Netherdrake** [comment]
@flavioribeiro Thank you.

I've copied your styles, specifically:
```
<div id="player-full"
      style="border: 0px;border-radius: 0px;width: 100%;height: 100%"></div>
```
and:
```
<style>body {margin:0}</style>
```

Its much better now, I only still need this one hack, otherwise the player doesn't load.

```
  let player = new Clappr.Player({
            height: window.innerHeight - 1,
            width: '100%',
            ...
```

**Comment by piratamovil** [comment]
Try this:
```html
<html>
    <head>
        <meta charset="UTF-8" />
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <title>Player</title>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
    </head>
    <body style="margin:0">
        <span id='player-wrapper'></span>
        <script>
            var playerElement = document.getElementById("player-wrapper");

            var player = new Clappr.Player({
                source: 'http://clappr.io/highline.mp4',
                poster: 'http://clappr.io/poster.png',
                mute: true,
                height: '100%',
                width: '100%'
            });

            player.attachTo(playerElement);
        </script>
    </body>
</html>
```

**Comment by breim** [comment]
Buddy, try this:

On html:

  <div class="app">
    <div class="player"></div>
  </div>

On css:

* {
  margin:0px;
  padding:0px;
}

.player {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%; 
}

Work perfectly.
