### ISSUE TITLE
Some streams sometimes don't work

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1586]
I'm trying to open these streams and sometimes they won't open the first time ... sometimes I have to do several tries. On the other hand, with a flash player I have no problems.

http://cspan2-lh.akamaihd.net/i/cspan2_1@304728/master.m3u8
http://edge.music-choice-play-chainb1.top.comcast.net/PlayMetadataInserter/play/.m3u8
http://rtvmurcia_01-lh.akamaihd.net/i/rtvmurcia_1_0@507973/master.m3u8

I'm not sure if it's because of the latest version of clappr:
https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

**Comment by leandromoreira** [comment]
Hi @hijuuijj can you follow the [basic instructions](https://github.com/clappr/clappr/blob/master/doc/BEFORE_OPEN_AN_ISSUE.md) and also post the logging from the browser?

**Comment by hijuuijj** [comment]
I have tried 3 times the first link... 2 first times OK... the third try has failed for some reason.

**Comment by leandromoreira** [comment]
is there an error message on console?

**Comment by hijuuijj** [comment]
First try. OK
Second try, video doesn't open (no error)
Please try several times with the first link,

**Comment by hijuuijj** [comment]
This "bug" seems to be fixed, right?
