### ISSUE TITLE
Unable to configure MediaControl after player creation

### ISSUE THREAD

**Issue by markmatney** [clappr/clappr#1592]
**Browser**: Firefox 59.0b10, Chromium 64.0.3282.167

**OS**: Ubuntu 16.04

**Clappr Version**: 0.2.87

**Steps to reproduce**:

* Create and attach player:
```javascript
player = new Clappr.Player({
    ...
    /* MediaControl-specific options */
    hideMediaControl: true,
    mediaControl: {seekbar: "#E113D3"}
})
player.attachTo( ... )
```
* Call `configure` and see that the `MediaControl` still hides after a timeout, and the seekbar has not changed colors:
```javascript
player.configure({
    ...
    hideMediaControl: false,
    mediacontrol: {seekbar: "#F00"}
})
```

(I will propose a fix shortly.)

**Comment by flavioribeiro** [comment]
closed by #1593
