### ISSUE TITLE
How to set custom headers for JWT

### ISSUE THREAD

**Issue by Liniik** [clappr/clappr#1604]
Hi, I'm using clappr (HLS) with Vue.js in connection with REST API server and authentication with [JWT](https://jwt.io/). For requests and response handling I'm using axios.

When I request index.m3u8 from server everything is ok, because I pass Auth header to axios. But when clappr requests chunks, it gets 401 unauthorized because of missing header. I don't see an option for this in docs (maybe feature request?). I wanted to try some solutions from older issues but mostly pages doesn't exist (e.g. #1447) or I don't know where to put code from issue (#1075 and the hlsjs part).

Am I missing some basics or do I have to really modify some nearly core sources? Thanks

**Comment by leandromoreira** [comment]
Hey @Liniik  add this configuration to your clappr.
```javascript
hlsjsConfig: {
    xhrSetup: function(xhr, url) {
      xhr.withCredentials = true; // do send cookies
    }
}
```

**Comment by Liniik** [comment]
That was it, thank you. I couldn't find where to place it...
