### ISSUE TITLE
Refactor configure and options

### ISSUE THREAD

**Issue by towerz** [clappr/clappr#1608]
We should make it easier to work with `configure` and scoped `options` on all kinds of Plugin, as well as the MediaControl.

The `configure` method should always be available for the plugins and for specific cases, such as Playbacks, their `options` should refer to a specific set of options instead of a copy/reference to the entire `options` object.

**Comment by kslimani** [comment]
Not sure if the best location to write this, but a nice feature for plugins would be also to allow them to load asynchronously. 
I mean, when the core create plugin instances and then configure them, it would be nice to expose some mechanism/interface  (promise ?) to allow the core to wait for all plugin to be ready. (with some timeout mechanism ?)

For example, this would ease the asynchronous loading of an external embed script in plugins.

Also a nice feature in next major release could be to rethink the autoPlay mechanism. Currently, most playbacks check and autostart in constructor. I think i would be better if it was the core which call container/playback play method. Also exposing a mechanism in core, (promise ?) to intercept play intent and override/modify core autoplay decision (usable by UI core plugins, etc...)

**Comment by towerz** [comment]
@kslimani I agree with you. We intend to review the plugin loading to introduce dependency management and asynchronous loading. Another feature we want to add is version checking, to allow a plugin to depend on a given Clappr  version and/or other plugins versions.
