### ISSUE TITLE
Hijacking the current time, total time & mouse over seek bar time with an offset for a non-live streamed source

### ISSUE THREAD

**Issue by Bubblesphere** [clappr/clappr#1609]
Hi,

I'm currently attempting to overwrite the displayed current,  total, and mouse over seek bar time of the player with an offset. Since my source isn't a live video, I cannot use the actual live time from the built in plugins. I thought the easiest way to do the current and total time would be to make a plugin which would bind to one of the three time update events (CONTAINER_TIMEUPDATE, PLAYBACK_TIMEUPDATE, PLAYER_TIMEUPDATE) and then overwrite the html. Upon testing, only CONTAINER_TIMEUPDATE is ever called. Unfortunately, the CONTAINER_TIMEUPDATE seems to be called a little to late which cause the current time to flicker between the container's actual time and the hijacked version. Also, I was going to use the MEDIACONTROL_MOUSEOVER_SEEKBAR event for overriding the mouse over seek bar time but it isn't called when I mouse over the seek bar. It seems like the only triggered events are from the container ones. Here's what my code looks like.

```javascript
var hijackSeekbar = Clappr.UIContainerPlugin.extend({
            name: 'hijack_seekbar',
            bindEvents: function () {
                this.listenTo(this.container, Clappr.Events.CONTAINER_TIMEUPDATE, this.containerTimeUpdate);
                this.listenTo(this.container, Clappr.Events.PLAYBACK_TIMEUPDATE, this.playbackTimeUpdate);
                this.listenTo(this.container, Clappr.Events.PLAYER_TIMEUPDATE, this.playerTimeUpdate);
                this.listenTo(this.container, Clappr.Events.MEDIACONTROL_MOUSEMOVE_SEEKBAR, this.mediacontrolMouseoverSeekbar);
            },
            containerTimeUpdate: function (obj) {
                // called but hijacking time here causes flicker between
                // the container's time and the hijacked version
                console.log("Container Time Update");
                this.updateTime(obj.current, obj.total);
            },
            playbackTimeUpdate: function () {
                // never called
                console.log("Playback Time Update");
            },
            playerTimeUpdate: function () {
                // never called
                console.log("Player Time Update");
            },
            mediacontrolMouseoverSeekbar: function () {
                // never called
                console.log("Mediacontrol Mouseover Seekbar");
            },
            updateTime: function (current, total) {
                var originalTimeOffset = new Date("2018-01-01 05:30:00");
                var newTime = new Date(originalTimeOffset);
                var newTimeTotal = new Date(originalTimeOffset);

                newTime.setTime(originalTimeOffset.getTime() + Math.floor(current) * 1000);
                newTimeTotal.setTime(originalTimeOffset.getTime() + Math.floor(total) * 1000);

                $("[data-position]").html(newTime.toTimeString().split(' ')[0]);
                $("[data-duration]").html(newTimeTotal.toTimeString().split(' ')[0]);
            }
        });
```

To fix the flickering issue, instead of making a plugin, I was able to deal with the current and total time hijacking via:
```javascript
var player = new Clappr.Player({
  events: {
    onTimeUpdate: function() { ... },//Fired when the time is updated on player
  }
})
```

Unfortunately, with this technique, there's no event to hijack the seek bar hover time. Is there any way I can get to my goal creating a plugin? If not, how can I deal with the hijacking of the seek bar hover time?

Thanks

**Comment by joaopaulovieira** [comment]
You need the correct references for each event you listening on `bindEvents`, like:
```javascript
bindEvents: function() {
    this.listenTo(this.container, Clappr.Events.CONTAINER_TIMEUPDATE, this.containerTimeUpdate);
    this.listenTo(this.container.playback, Clappr.Events.PLAYBACK_TIMEUPDATE, this.playbackTimeUpdate);
...
},
```
For listen `MEDIACONTROL_MOUSEMOVE_SEEKBAR`, you need the media control reference for `listenTo` and this is not accessible on `container` area, only in `core`.

you can see an example in the [seek_time](https://github.com/clappr/clappr/blob/master/src/plugins/seek_time/seek_time.js#L48
) plugin.

Doing this, i think it will work the way you expect it.

**Comment by Bubblesphere** [comment]
Thanks, that did it. Everything mentioned worked. Do you know by any chance the difference between the concept of container, playback and player? It would help me understand which to pick in the future.

**Comment by joaopaulovieira** [comment]
You can read more about the project architecture on the [wiki](https://github.com/clappr/clappr/wiki/Architecture) or if you have any specific questions, send to Clappr channel at [video-dev Slack](http://video-dev.org/).
