### ISSUE TITLE
HLS.JS 0.9.0 events deprecation

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr#1610]
This is not yet an issue, as Clappr is currently using hls.js version 0.8.9.

But in 0.9.0 the `LEVEL_SWITCH` and `AUDIO_TRACK_SWITCH` events are deprecated for `LEVEL_SWITCHING` and `AUDIO_TRACK_SWITCHING`. _(see also [this PR](https://github.com/video-dev/hls.js/pull/1606]))_.

In the  HLS.JS playback, the `LEVEL_SWITCH` is used [here](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L157).

**Comment by towerz** [comment]
Thanks @kslimani! 

The playback was changed to use the correct event in b37b7cee, released on version 0.2.90.
