### ISSUE TITLE
Bootstrap4 && clappr fonts issue

### ISSUE THREAD

**Issue by Kolunchik** [clappr/clappr#1620]
**Browser**: latest Chrome, latest Firefox
**OS**: Linux
**Clappr Version**: https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

**Steps to reproduce**:
* Make some page with Bootstrap 4
![without](https://user-images.githubusercontent.com/23293196/38385320-41a2120e-391a-11e8-90d2-ca3d069e15ec.png)
* Add Clappr instance
![with](https://user-images.githubusercontent.com/23293196/38385331-4ebc2f38-391a-11e8-8a5c-600b7068cbc5.png)
* Done. Fonts changed

Hello!
How we can prevent adding of clappr-style with fixed Roboto fonts to page`s head?

Thanks for great player!

**Comment by towerz** [comment]
@Kolunchik currently, there's no option to disable adding the Roboto font, but it loads using an URL formed using the `baseUrl` parameter. 

If you're not using any Flash-based playback, you could add the `baseUrl` parameter to change from where the assets will load. If you're using any Flack-based playback, you'll need to serve the .swf files from the URL where you've changed the `baseUrl`  to.
