### ISSUE TITLE
I can't skip forward videos.

### ISSUE THREAD

**Issue by MarlonEtiene** [clappr/clappr#1622]
**Browser**: Latest Chrome and Firefox

**OS**: Ubuntu 16.04

**Clappr Version**: latest

**Steps to reproduce**:

Hello,
If I use this piece of code
```
         var player = new Clappr.Player({
            source: '/storage/resources/{{ $resource['resource_type_id'].'/'.$resource['id'].'/'.$resource['uploaded_video'] }}',
            height: 360,
            width: 640,
            mimeType: "video/mp4",
            autoPlay: true,
            actualLiveTime: true
        });
```
The video play normally and I can forward
But If I change the url for my protected url (I am using laravel and response the video base64 encoded) with this code
```
var player = new Clappr.Player({
            source: "{{ route('video.url', [\MyLib\Helpers\Helpers::newGuid(), $resource['resource_type_id'], $resource['id']]) }}",
            poster: 'http://clappr.io/poster.png',
            height: 360,
            width: 640,
            mimeType: "video/mp4",
            autoPlay: true,
            actualLiveTime: true
        });
```

The video play normally, but I can't forward, All times I try, the video restarts.

Can anyone help me please?

PS. I use only mp4 format.

**Comment by towerz** [comment]
@MarlonEtiene sorry I didn't pick up your issue. Are you still having this issue playing your content?

If so, how can I reproduce? Are you trying to load a base-64 encoded video as a string on the `source` parameter? Is that correct? If not, how are you trying to load the base-64 encoded video then?

**Comment by MarlonEtiene** [comment]
Sorry for taking the time to give you feedback, I had some problems.
The solution was to load the videos encoded in base64.
Thank you
