### ISSUE TITLE
Player in page with height: "100%" isn't displayed when DOCTYPE is set

### ISSUE THREAD

**Issue by t1254362** [clappr/clappr#1623]
I was trying to have a 100% width and height player.

width: "100%" is working fine, but when I add height: "100%" it goes to 0px.

I was trying this example from a similar Issue: https://github.com/clappr/clappr/issues/1387#issuecomment-299216771
And it working, but with this I found what is the difference and how to break that code: add at top:
```
<!DOCTYPE html>
```

With the example at is, it works, but if I add DOCTYPE I have the same behaviour: with 100% width, it works, with 100% height, it has 0px as 100%.

I modified my original page to remove DOCTYPE and now height: "100%" works.

Why I need to remove <!DOCTYPE html> to use height: "100%"? I want to fill a div (not always the full page), and without DOCTYPE it works

I'm using your CDN import: https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

**Comment by kslimani** [comment]
When you set player width and height attributes to `"100%"`, player size adjust to parent container size (ie: it fills it). You should double check the css rules applied to your player container element.

**Comment by t1254362** [comment]
What css can apply to <!DOCTYPE html>?

Here you can see that this works: http://jsbin.com/vebayogisa/edit?html,output
But this not: http://jsbin.com/levazoxoja/edit?html,output

**Comment by t1254362** [comment]
I will look this, same the same problem with other elements (not clappr):
https://stackoverflow.com/questions/10380346/css-styles-not-applied-properly-if-use-doctype

**Comment by t1254362** [comment]
Ok, I see. you should define "html" and "body" css to 100%:
```
      html {
        width: 100%;
        height: 100%;
      }
      html body {
        width: 100%;
        height: 100%;
      }
```

Or use in body:
```
<body style="position:absolute;top:0px;left:0px;right:0px;bottom:0px;background-color:green;">
```

First time that I see people talking about css in HTML tag.
