### ISSUE TITLE
Get currently playing file fragment path?

### ISSUE THREAD

**Issue by daniel-loader** [clappr/clappr#1627]
Question or request really, can you get the currently played path? 

I can see the list of fragments being downloaded in the chrome network debugging but was wondering if the play itself can give me what's currently being played?

Thanks

**Comment by vagnervjs** [comment]
Hi @daniel-loader, if you are using the HLS playback (w/ hls.js) you can implement a [floader](https://github.com/video-dev/hls.js/blob/master/docs/API.md#floader), using the hlsjsConfig playback option, and get the path of each fragment loaded.

E.g.:
```
options.playback.hlsjsConfig = {
    fLoader: yourFloaderImplementation
}
```

To know about the hls.js loader details, check: https://github.com/video-dev/hls.js/blob/master/docs/API.md#loader

This help you?

**Comment by daniel-loader** [comment]
Possibly, was looking for something that could just display a variable of the HLS fragment currently being played in the player. I'll have to have a read.

**Comment by vagnervjs** [comment]
@daniel-loader if you need any help please update here, closing the issue.
