### ISSUE TITLE
html5_video:3 error

### ISSUE THREAD

**Issue by khalilleo** [clappr/clappr#1628]
**Browser**:  Chrome Version 64.0.3282.186

**OS**: Windows 7

**Clappr Version**: lastest from jsdelivr

**Steps to reproduce**:

I kept getting this error at certain second in a video

![_20180417113822](https://user-images.githubusercontent.com/2585057/38880615-23f1522e-4234-11e8-801f-95bef9268c0f.png)

Did you try to reproduce this issue at http://cdn.clappr.io/
YES

config is 
`var player = new Clappr.Player({
  source: URL(MP4 FILE),
  height: 360,
  width: 640,
  preload:'auto',
  maxBufferLength:60
});`

**Comment by jhonatangomes** [comment]
Hello, can you share your the video source you're using?

Can you test using the previous Clappr version ([0.2.90](https://cdn.jsdelivr.net/npm/clappr@0.2.90/dist/clappr.min.js))? 

On 0.2.90 there is no error screen and you have to share your log. To enable the log use `Clappr.Log.setLevel(0)`.

**Comment by towerz** [comment]
@khalilleo could you please share the URL you were using for testing? The error code 3 is a decode error, which means your browser can't decode the video (https://developer.mozilla.org/en-US/docs/Web/API/MediaError). 

Have you tested the player with the default video in the demo page?

**Comment by vagnervjs** [comment]
@khalilleo can you check, please, if the problem still occurs on the latest Clappr version (0.2.93)?
