### ISSUE TITLE
Start playing HLS without waiting for full segment download 

### ISSUE THREAD

**Issue by fooger** [clappr/clappr#1633]
Hello. I coded all my videos with ffmpeg option "-movflags faststart" (moov atom at the front of the file (Fast Start)). But when i start play the HLS m3u8 playlist, the video start playing only after segment fully downloaded ( https://i.imgur.com/tnrDwj3.png )
Is it possible not to wait for downloading full segment (when video has moov atom at the front of the file)?
Thank you!
P.s. sorry for my english

**Comment by kslimani** [comment]
How many seconds are your segments duration ? maybe you could try reduce them, to decreased download duration of first fragment and therefore the playback start.

**Comment by fooger** [comment]
My fragments duration has 10 sec. Experimented with 5 sec, but in fullhd - downloading (starting time) is too long..
Is it possible to start playing without full segment downloading?
