### ISSUE TITLE
error msg instead of play icon

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1635]
I upgraded to the last one clappr version 0.2.92 and when I test with Chrome/Opera/Vivaldi browsers
when no stream available, I try for 10s then I call "stop"
instead of getting the "play icon" in the middle I get : default_error_title default_error_message error code : hls :4
no problem with IE/Edge and Firefox
For sure I need the "play icon" for my users to click to play

no issue at all with 0.2.90
I added debug from 0.2.92 and 0.2.90

[clappr0290-OK.log](https://github.com/clappr/clappr/files/1969667/clappr0290-OK.log)
[clappr0292-KO.log](https://github.com/clappr/clappr/files/1969668/clappr0292-KO.log)

![0292](https://user-images.githubusercontent.com/17108017/39560403-2780522a-4e9e-11e8-8bdc-d863cdc4e09f.PNG)
![0290](https://user-images.githubusercontent.com/17108017/39560404-2798c706-4e9e-11e8-9d00-85c61607e144.PNG)

**Comment by jhonatangomes** [comment]
Hello, I could not reproduce this but we I have a similar problem and got a solution that is being tested on #1638.

Can you check if this happens with the changes that are applied to #1638?

**Comment by Niko78** [comment]
@jhonatangomes : I can confirm now it is fixed with 0.2.93 in adding
disableErrorScreen: true,
in player configuration

thanks

**Comment by vagnervjs** [comment]
@Niko78 thanks!
