### ISSUE TITLE
What is the proper syntax for the use of multiple plugins?

### ISSUE THREAD

**Issue by imabee101** [clappr/clappr#1637]
I can not for the life of me find one example of the proper way to specify multiple plugins. I can only find single plugin examples which is so frustrating! 
plugins: [ChromecastPlugin], [HelloWorld], ???
plugins: [ChromecastPlugin, HelloWorld], ???

Also having trouble loading plugins
Trying to load the nerd stats plugin but its not working
<head>
    <script type="text/javascript" src="http://127.0.0.1/clappr-master/dist/clappr.min.js"></script>
	<script type="text/javascript" src="http://127.0.0.1/clappr-chromecast/dist/clappr-chromecast-plugin.min.js"></script>
	<script type="text/javascript" src="http://127.0.0.1/clappr-nerd-stats-master/dist/clappr-nerd-stats.js"></script>
	<script type="text/javascript" src="http://127.0.0.1/clappr-stats-master/dist/clappr-stats.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/clappr/dash-shaka-playback@latest/dist/dash-shaka-playback.min.js"></script>
  </head>

**Comment by imabee101** [comment]
`<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="http://127.0.0.1/clappr-master/dist/clappr.min.js"></script>
	<script type="text/javascript" src="http://127.0.0.1/clappr-chromecast/dist/clappr-chromecast-plugin.min.js"></script>
	<script type="text/javascript" src="http://127.0.0.1/clappr-nerd-stats-master/dist/clappr-nerd-stats.js"></script>
	<script type="text/javascript" src="http://127.0.0.1/clappr-stats-master/dist/clappr-stats.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/clappr/dash-shaka-playback@latest/dist/dash-shaka-playback.min.js"></script>
  </head>

<body>
    <div id="player"></div>
    <script>
      var player = new Clappr.Player(
        {
          abrEwmaDefaultEstimate: 4000000, maxBufferLength: 30, startFragPrefetch : true, maxSeekHole: 0, initialLiveManifestSize : 2, enableWorker: true, abrMaxWithRealBitrate : true, autoPlay: true, 
		  parentId: '#player',
          plugins: [DashShakaPlayback, ChromecastPlugin, ClapprNerdStats, ClapprStats],
		  source: 'http://watch.imabee.ca/live/event1.m3u8', height: 360, width: 640, 
		  clapprNerdStats: {
        shortcut: ['command+shift+s', 'ctrl+shift+s'],
        iconPosition: 'top-right'
      },
          shakaConfiguration: {
            preferredAudioLanguage: 'pt-BR',
            streaming: {
              rebufferingGoal: 15, bufferinggoal : 15,
            }
          },
          shakaOnBeforeLoad: function(shaka_player) {
            // shaka_player.getNetworkingEngine().registerRequestFilter() ...
          },
          
		  
        });
    </script>
  </body>
</html>`

**Comment by leandromoreira** [comment]
`plugins: [Dash, SomethingElse, Anything]`

**Comment by imabee101** [comment]
Thankyou
