### ISSUE TITLE
bug(strings): default error message translation issue

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr#1641]
**Browser**: any
**OS**: any
**Clappr Version**: master

There is a small issue with default error messages where not defined for language : it returns "default_error_title" and "default_error_message" instead of fallback to english version. _(reason is that current code expects that translation keys exists)_.

@jhonatangomes i suggest you rollback changes from e21ec7063cafda7f890b71f7b4758ed5aafdb71c but try to translate with Google from the english strings, you should get better translation results. (i assume you translated from portuguese ? :stuck_out_tongue: )

**Steps to reproduce**:

Simply go to [this page link](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZXgubXA0JywKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogIGxhbmd1YWdlOiAncnUnLAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK). (Clappr demo page).

**Comment by jhonatangomes** [comment]
#1643 fixes this bug.

About the rollback: I prefer to wait for PRs with these messages translated like on #1634 to guarantee it'll be right. 

I don't remember if it was translated from portuguese :smile:, maybe it was, but I really don't remember. I did the rollback just to prevent possible wrong messages.
