### ISSUE TITLE
Make clappr responsive

### ISSUE THREAD

**Issue by imabee101** [clappr/clappr#1645]
What is a simple way of making clappr take up the full size of its container? 

Thanks

**Comment by kslimani** [comment]
@imabee101 in the player configuration, just set `width` and `height` attributes to `'100%'` and it will automatically adjust to container element.

**Comment by imabee101** [comment]
Thank-you for the response. I did that and the player will no longer load.
[https://i.gyazo.com/032a7fb5de867eb40b13a92d269e7ab1.png](url)

**Comment by kslimani** [comment]
@imabee101 check if the player container element has appropriate size.

Example :

```html
<html>
  <head>
    <title>My App</title>
    <style>
      .player {
        width: 640px;
        height: 360px;
      }
    </style>
  </head>
  <body>
    <div class="app">
        <div class="player"></div>
    </div>
    <script>
      var player = new Clappr.Player({
        source: 'http://clappr.io/highline.mp4',
        parent: '.player',
        height: '100%',
        width: '100%'
      });
    </script>
  </body>
</html>
```

**Comment by imabee101** [comment]
Thank-you very much!

**Comment by imabee101** [comment]
I tried the code you specified and the player just stays at 640 by 360. The player wont change sizes. Any other suggestions?

**Comment by kslimani** [comment]
With `width` and `height` set to `'100%'` Clappr player will adapt size to the "player" container div.
You have to change css style on container div to fullfills your needs.

**Comment by imabee101** [comment]
Thank-you

**Comment by tecfu** [comment]
Here's how you would make Clappr responsive using Bootsrap. 

I was forced to use a slightly different technique than what @kslimani suggests above to get this to work. 

```
<div class="embed-responsive embed-responsive-16by9">
  <div id="player-container" class="embed-responsive-item"></div>
</div>

<script>
   new Clappr.Player({
            source: manifestUri,
            mute: false,
            autoPlay: false,
            parent: '#player-container',
            width: '100%',
            height: '100%'
  })
</script>
```
See example here: https://codepen.io/tecfu/pen/LJRmPQ

**Comment by SammyInsane** [comment]
> Here's how you would make Clappr responsive using Bootsrap.
> 
> I was forced to use a slightly different technique than what @kslimani suggests above to get this to work.
> 
> ```
> <div class="embed-responsive embed-responsive-16by9">
>   <div id="player-container" class="embed-responsive-item"></div>
> </div>
> 
> <script>
>    new Clappr.Player({
>             source: manifestUri,
>             mute: false,
>             autoPlay: false,
>             parent: '#player-container',
>             width: '100%',
>             height: '100%'
>   })
> </script>
> ```
> 
> See example here: https://codepen.io/tecfu/pen/LJRmPQ

Thanks for this my saviour. Works perfect. Just need to change parent: '#player-container' to parentId: '#player-container'
