### ISSUE TITLE
how can I make a play button and stop

### ISSUE THREAD

**Issue by Ali-Talib-jabar** [clappr/clappr#1647]
Hi I want to create a button through which I can play video and stop using JavaScript

I tried this code but it did not work as I wanted
`status = document.getElementById(".play-video");
                function togglePlay() {
                    return player.stop ? player.play() : player.play();
                }`

![screen shot 2018-05-22 at 22 23 31-fullpage](https://user-images.githubusercontent.com/4175957/40385644-ef0882a6-5e0f-11e8-8496-196e89a920b7.png)
![screen shot 2018-05-22 at 22 23 54-fullpage](https://user-images.githubusercontent.com/4175957/40385646-ef3bb25c-5e0f-11e8-80a9-48a6653d1631.png)

I am not familiar with the policies of this site I may have posed a question in a problematic format

**Comment by flavioribeiro** [comment]
are you sure your ternary is right? Both conditions are calling `play()`. Try

```javascript
function togglePlay() { return player.isPlaying() ? player.pause() : player.play(); }
```

**Comment by Ali-Talib-jabar** [comment]
@flavioribeiro Yes it works but how can i change the icon from stop to play , Yes it works but how can i change the icon from stop to run. Watch the pictures

**Comment by towerz** [comment]
@Ali-Talib-jabar you can switch the icons by listening to the play/pause/stop/ended events:
```js
var showPlayIcon = function() { ... }
var showStopIcon = function() { ... }
var player = new Clappr.Player({
  //...
  events: {
    onPlay: showStopIcon,
    onStop: showPlayIcon,
    onEnded: showPlayIcon
  }
})
```
