### ISSUE TITLE
Automatically reload load stream

### ISSUE THREAD

**Issue by imabee101** [clappr/clappr#1649]
Is there a way to get clappr to keep checking for an hls stream even after several hours of being offline? Also is there a simple way to control the client player for example change the playlist without the client refreshing the page?

Thanks

**Comment by kslimani** [comment]
I am not sure to understand the "keep checking" part, but you can implement a retry mechanism following [these examples](https://github.com/clappr/clappr/blob/master/doc/PLAYER_ERRORS.md#example).

Also, you can load another source by calling the player [`configure()`](http://clappr.github.io/classes/Player.html#method_configure) method.

Example :

```javascript
// Assuming player is Clappr Player instance
player.configure({source: 'http://clappr.io/highline.mp4', autoPlay: true})
```

**Comment by imabee101** [comment]
If the stream goes offline, say an hour later it goes back online. How can I get the playback to resume without the user having to refresh?

**Comment by kslimani** [comment]
A possible solution is to implement a retry mechanism inspired from previously linked [examples](https://github.com/clappr/clappr/blob/master/doc/PLAYER_ERRORS.md#example).

**Comment by imabee101** [comment]
Thank-you. Is it also possible to display a poster instead of the 3 dots?

**Comment by kslimani** [comment]
Examples have been updated to work with latest clappr version in #1650.

**Comment by freeyland** [comment]
The examples are working file but there is an issue when you try to load an new url:
// Assuming player is Clappr Player instance
player.configure({source: 'http://clappr.io/highline.mp4', autoPlay: true})
The player keeps retrying to connect to the previous url. 
Thanx for the help
