### ISSUE TITLE
missed watermark in full-screen mode

### ISSUE THREAD

**Issue by MrSamoylov** [clappr/clappr#1652]
**Browser**: Safari iOS 11.4
**OS**: iOS 11.4
**Device**: iPhone/iPad
**Clappr Version**: 0.2.25 http://clappr.io/demo
**Steps to reproduce**:

* use any watermark with any position or custom UIContainerPlugin.extend for text:
Example: watermark: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Cute-Ball-Favorites-icon.png", position: 'top-right',
* open Safari browser on iPhone/iPad
* Play video
* change view to full-screen mode

Once the video is deployed in full screen, the watermark will disappear

Did you try to reproduce this issue at http://cdn.clappr.io/ - yes. I tried on http://clappr.io/demo

<a href="https://ibb.co/eM0nf8"><img src="https://thumb.ibb.co/eM0nf8/photo5246976553148066024.jpg" alt="photo5246976553148066024" border="0"></a>

**Comment by kslimani** [comment]
@MrSamoylov it is a known limitation for iOS devices.

While in fullscreen mode, it is the native controls which are used.

Technically, when video goes to full screen mode, it is handled by device mediaplayer (quicktime ?) and therefore it is not possible (AFAIK) to set overlay elements.

**Comment by kslimani** [comment]
@MrSamoylov i think it is a global behaviour on all iOS devices browsers.

**Comment by MrSamoylov** [comment]
@kslimani thanks for information. I will try to find another way...
