### ISSUE TITLE
Add Log error levels to documentation & document "setLevel"

### ISSUE THREAD

**Issue by ranst91** [clappr/clappr#1653]
**Browser**: Chrome (latest)

**OS**: Windows 10

**Clappr Version**: 0.2.95

Going through all issues related to logging, it seems like someone insisted on having fatal errors logged without an open to turn them off.

I'd appreciate providing of any way to disable also fatal errors, as it makes no sense to have them on production.

Also, the documentation (API reference) does not supply any info on "Clappr.Log"

**Comment by kslimani** [comment]
@ranst91 currently you can disable fatal error logging by calling :

```javascript
Clappr.Log.setLevel(4);
```

There is also a `disableErrorScreen` player option to disable the "error screen" internal plugin. (set to true).

**Comment by kslimani** [comment]
You are correct, i don't think that `Log` internal plugin has any documentation yet, or i missed it also. (only some issues reference  it)

**Comment by ranst91** [comment]
Editing this issue post to reflect the new issue arises from the discussion

**Comment by MarcosEllys** [comment]
I'll make this

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
