### ISSUE TITLE
Player generate div with the class name "container" cause bootstrap mix

### ISSUE THREAD

**Issue by Lethea** [clappr/clappr#1656]
When player load, it generate div with class="container pointer-enabled".  We use boostrap for website and the player ui affacted. Can I change the generated class name as player-container as well ?

**Comment by kslimani** [comment]
@Lethea it also use `data-container` element attribute. This may allow you to write some css override rules using, for example, the `.container[data-container]` selector.

Anyway, i think you are correct, a possible enhancement in next Clappr major release could be to add prefixes to css classes used by player to avoid these conflicts.

**Comment by ralomach** [comment]
Hi! I have the same problem using Tailwind CSS. Any news?

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.

**Comment by arunpt** [comment]
@rafaellotto Hi, did you find any fix? for me, play button is getting of centered when using with tailwindcss

**Comment by rafaellotto** [comment]
> @rafaellotto Hi, did you find any fix? for me, play button is getting of centered when using with tailwindcss

Hi, @arunpt. No, the only project I use Clappr now is without Tailwind CSS.

**Comment by arunpt** [comment]
@rafaellotto Thanks for the update
