### ISSUE TITLE
Black screen when playing m3u8 playlist in IE 11

### ISSUE THREAD

**Issue by chrisprog20** [clappr/clappr#1657]
**Browser**: IE 11 (Version 11.0.9600.18893CO)

**OS**: Windows 7

**Clappr Version**: 0.2.80

**Description**:

IN IE 11 I want to load an m3u8 playlist from my streaming provider.
When I click on the play button the audio occurs but the screen remains black.
I have the latest Adobe Flash plugin also installed and I tried with deactivated/activated
hardware acceleration (set up in the Flash plugin settings) but nothing helped.

Can someone confirm this issue or give advice what I can additionally do to see the video?

Thank you for your answer in advance.

Christian

**Comment by chrisprog20** [comment]
Hi kslimani,
thank you for your quick reply. I tried now my m3u8 playlist on your [Clappr demo page](http://clappr.io/demo/) and there I got also the black screen. I have to say that the URL to the playlist uses "https". Maybe it has to do with that?

**Comment by kslimani** [comment]
You are correct, If your manifest url protocol is https, the player will not be able to download it on an http page if the resolved playback is hls.js.

Since current master uses hls.js version 0.9.1, you may want to try your manifest on [hls.js 0.9.1 demo page](https://streambox.fr/mse/hls.js-0.9.1/demo/)

**Comment by chrisprog20** [comment]
Thank you for your answer kslimani. 
I tried my url on the hls.js 0.9.1 demo page (which is served via https lile my manifest url).
There I got the following message:

> your Browser does not support MediaSourceExtension / MP 4 mediasource

So now we got the proof that my browser cannot play hls video. But in that case clappr should fall back to the flash player plugin, right? 

And that does not work at the moment (even when the manifest url protocol matches with the page's url protocol and the files from the dist folder of the current clappr master branch (version 0.2.96)).

Maybe this console output helps which occurs after I clicked the play button in the middle of the black screen:
> INFO:FlasHLS Clappr (version: 0.4.16 - flashls: 0.4.4.24, id: o39)
INFO:HLSNetStream:close
INFO:HLSNetStream:play(-1)
INFO:HLSNetStream:seek(-1)
INFO:Setting audio track to 0

Cheers
Christian

**Comment by kslimani** [comment]
The provided output console indicate that it is the FlasHLS playback which is used by Clappr. (using Flash plugin). So it indicate also that Clappr has properly fallback to flash playback.

Now the question seems to be why FlasHLS version 0.4.4.24 display a black screen.

Can you try again with [this page](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly92aWRlby1kZXYuZ2l0aHViLmlvL3N0cmVhbXMveDM2eGh6ei94MzZ4aHp6Lm0zdTgnLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAKfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cg==) ? if it work, then it may be an issue with your video format.

**Comment by chrisprog20** [comment]
Hi kslimani, 
when I try the default video url in the demo page it works in IE 11.
When I try it with the stream url for my video it does not work.
So it is an issue with my video format...
Do you have an idea what could be the reason for this wrong video format?

Thank you again for your time.
Cheers
Christian

**Comment by kslimani** [comment]
A good start could be to try Clappr [common steps to verify issues](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues). (especially the media info tools). May be your source includes non-supported feature.

Also @leandromoreira may be able to help you on this issue _(if he's not too buzy :grin:)_

**Comment by chrisprog20** [comment]
Hi kslimani!
Thank you again for your hints. :) I will try to work through your link [common steps to verify issues](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues) without asking@leandromoreira for help ;)

**Comment by leandromoreira** [comment]
=) feel free to post it here maybe we can help you

**Comment by chrisprog20** [comment]
Thank you @leandromoreira  :)
We tested some videos on http://www.flashls.org/latest/examples/chromeless/ and there we found that some are working on IE 11 in combination with Windows 7 and others not.
Our video streaming provider was then informed about that and told us that he tries to do an "easier" 
encodation of the videos.
I will keep you informed about the outcome! :)

**Comment by kslimani** [comment]
@chrisprog20 on Flashls chromeless examples page, you can modify the debug log verbose level, by clicking on the "Advanced control" button. This may give you more hints on why stream is not working.

(if you have not noticed already this feature)

**Comment by chrisprog20** [comment]
@leandromoreira: Thank you for your hint. I have not discovered that yet. 
I will check this page with the more detailed verbose level again if I have a free time slot for it. :)

**Comment by chrisprog20** [comment]
So, I was able to play the videos on IE 11 and Win 7 with the following settings on 
[http://www.flashls.org/latest/examples/chromeless/](http://www.flashls.org/latest/examples/chromeless/) under button "quality control":

- current level: 1 (480p / 4885kb)
- next level: 1 (480p / 4885kb)
- load level:  1 (480p / 4885kb)
- cap level: none

I will try the [clappr level selctor plugin](https://github.com/clappr/clappr-level-selector-plugin). Maybe it helps.

**Comment by chrisprog20** [comment]
Ok, the level selector plugin seemed not to work. Hence we decided to show a flash player in IE <= 11 and the clappr plugin in Edge and all other browsers. Now word is beautiful again :)
