### ISSUE TITLE
Multiplay on Mobile

### ISSUE THREAD

**Issue by dinhkhaihtc** [clappr/clappr#1658]
Hello everyone, can anyone help me with regard to viewing many players on mobile?
Thanks!

**Comment by kslimani** [comment]
You may want to experiments with `playInline` player [playback option](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#playback-configuration).

**Comment by towerz** [comment]
@dinhkhaihtc you can embed multiple instances of the player with the `playInline` option (as @kslimani replied), but keep in mind that at least on iOS you cannot have multiple streams running simultaneously.
