### ISSUE TITLE
detroy player with plugin

### ISSUE THREAD

**Issue by ewwink** [clappr/clappr#1664]
please see code for the problem

```
var destroyPlayer = Clappr.ContainerPlugin.extend({
  bindEvents: function() {
    this.listenTo(this.container, Clappr.Events.CONTAINER_ERROR, this.onerror);
  },
  onerror: function(e) {
    // this.destroy(); # player not destroyed
    // this.container.destroy() # only some part destroyed
    // right code ?
  }
});
```

**Comment by kslimani** [comment]
@ewwink if you wants to destroy player instance, simply call the player `destroy()` method. It cleanup the player instance and remove itself from the DOM. For more details, refers to [player api documentation](http://clappr.github.io/classes/Player.html).

BTW, in your code example, `this` is not the player instance, it is your container plugin instance.

**Comment by ewwink** [comment]
you mean like this?
```
var player = new Clappr.Player({source: "http://your.video/here.mp4", parentId: "#player"});
player.destroy()
```
but I want do it with plugin.

**Comment by kslimani** [comment]
Using a player plugin to destroy the player instance seems to be a bad design (in my opinion).

Anyway, if you take a loot at [player destroy](https://github.com/clappr/clappr/blob/master/src/components/player.js#L421) method, you can see it first unbind player events calling player instance stopListening() method, then it call core instance destroy() method.

You can access easyly access core instance from your plugin instance, but for player instance you may needs to pass the reference to your plugin (maybe defining an external interface plugin method to inject player instance when created). There is maybe another way, but i missed it.

**Comment by ewwink** [comment]
it seem the easiest way is using zepto
```
onerror: function(e) {
      $('#'+this.options.parentElement.id).html('<video src=...')
}
```

one more question, is there way to fallback from clappr to native `<video>` tag on android? I have .m3u8 file which CORS is not allowed but it work with `<video>` tag and clappr not, I tried adding `recycleVideo` and `playInline` but still not work.

**Comment by ewwink** [comment]
nevermind I will use `Clappr.Browser.isMobile` instead and @kslimani thanks for your support.
