### ISSUE TITLE
Errors in clappr player

### ISSUE THREAD

**Issue by Pengi123** [clappr/clappr#1665]
**Browser**: Chrome Version 46.0

**OS**: Mac OS Sierra 10.12.6  

**Clappr Version**: 0.2.25

Hi i need Help I getting error on my clappr player i test my link m3u8 on demo clapper player and work, but when i put to my site clapper player is getting: Could not play video.

Error code: hls:4

Please Help

Best Regards

**Comment by leandromoreira** [comment]
@Pengi123 can you post how you're using clappr? also if it's working on demo page why don't you try to replicate the same page at your side?
