### ISSUE TITLE
How to make mediacontrol listen to core/player events?

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1666]
Hello.
I extend mediacontrol. Among other things It should hide its elements depending on fullscreen state.
So I need to listen core or player fullscreen event and get its payload. But I can't figure up the structure of the app and Its inner objects cross references.

Sorry fo my english.)

**Comment by kslimani** [comment]
There is currently no reliable way, exposed by Clappr (from media control bar point of view) to detect enter and exit fullscreen. (AFAIK, mediacontrol has no access to core component)

If you really needs to do something when player is entering or exiting fullscreen, i suggest to try to override the mediacontrol [playerResize()](https://github.com/clappr/clappr/blob/master/src/components/media_control/media_control.js#L244) methods.

Fullscreen toggle events is something which may require to be enhanced in future major version of the player.
