### ISSUE TITLE
Add rate to video

### ISSUE THREAD

**Issue by Arman-Amirahmadi** [clappr/clappr#1667]
Hi every one ...
I want to add rate to video player . i want to have 5 star at top-right of player.
User can choose 1 to 5 star .... please help me

**Comment by flavioribeiro** [comment]
I'd just get a snippet like [this](https://css-tricks.com/star-ratings/), fork [this](https://github.com/lucasrodcosta/clappr-nerd-stats) or [this](https://github.com/flavioribeiro/clappr-p2phls-stats-plugin) repository and make the changes accordingly.
