### ISSUE TITLE
HLS playaback

### ISSUE THREAD

**Issue by ctaity** [clappr/clappr#1670]
Is posible to add an option to user HLSJS nextLevel to set the level, is for a smooth switch. 

Thanks

**Comment by kslimani** [comment]
Yes, you can pass option to HLS instance using the `hlsjsConfig` player option.

Example :

```javascript
var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  hlsjsConfig : {
    // here any hls.js configuration options
  }
});
```

**Comment by ctaity** [comment]
but the is hardcoded in the playback code:

In the file: https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js

`set currentLevel(id) {
    this._currentLevel = id
    this.trigger(Events.PLAYBACK_LEVEL_SWITCH_START)
    this._hls.currentLevel = this._currentLevel
  }`

The line:  this._hls.currentLevel = this._currentLevel should be something like:

`if (options.smoothSwitch)
     this._hls.nextLevel  = this._currentLevel
else
    this._hls.currentLevel = this._currentLevel
`

**Comment by leandromoreira** [comment]
@ctaity this code `offers` the possibility to manually set the levels but by default it uses the hlsjs algorithm to adapt to the "right" bit rate.

**Comment by ctaity** [comment]
This code offers the posibility to use smooth switch to adapt levels.

https://github.com/video-dev/hls.js/blob/master/docs/API.md

hls.currentLevel: Trigger an immediate quality level switch to new quality level. This will pause the video if it was playing, flush the whole buffer, and fetch fragment matching with current position and requested quality level. Then resume the video if needed once fetched fragment will have been buffered.

hls.nextLevel: Trigger a quality level switch for next fragment. This could eventually flush already buffered next fragment.

XP is better using nextLevel, the posibility to buffer the playback is minimal. With current level, the playback stop, buffers the new level, and start again.

**Comment by leandromoreira** [comment]
thank you @ctaity I'll let @kslimani @towerz and @vagnervjs to take a look at it.

**Comment by kslimani** [comment]
if i understand correctly, @ctaity is proposing to add an additional Clappr player option.

For example `hlsSmoothSwitch` (which default to false).
If this new option is set to true, then it will use hls.js `nextLevel` setter instead of `currentLevel` setter when HLS playback `currentLevel()` setter method is called.

_(if these assumptions are correct, it is a very easy feature to adds which does not introduce any breaking changes)_.

**Comment by ctaity** [comment]
Exactly 👍

**Comment by flavioribeiro** [comment]
@ctaity can this one be closed?
