### ISSUE TITLE
comment and like button

### ISSUE THREAD

**Issue by Arman-Amirahmadi** [clappr/clappr#1676]
as you can see in image (Pic number 1)
I added two icon to player , i copied the code to (Code 1)

and my problem is ...
if you click on icons , video will play or pause.

1- i need that the video stay clickable.
2- if user click on icons , video MUST NOT pause or play
**Pic number 1**
<a href="https://imgbb.com/"><img src="https://image.ibb.co/eC8oeT/2018_07_24_15_03_35.jpg" alt="2018_07_24_15_03_35" border="0"></a>

**Code 1**
`
<div id="player">
     </div>
       var Ratestarvideo = Clappr.UIContainerPlugin.extend({
            name: 'Ratestarvideo',
            initialize: function () {  this.render();  },
           bindEvents: function () {

                                         this.listenTo(this.container, Clappr.Events.CONTAINER_MOUSE_ENTER, this.show);
                                         this.listenTo(this.container, Clappr.Events.CONTAINER_MOUSE_LEAVE, this.hide);  },
            hide: function () { this.$el.hide();  },
            show: function () {  this.$el.show(); },
            render: function () {

                this.$el.html('<div class="R_boxer"> <div class="rightbx"><span> <a href="http://google.com"><i class="fas fa-heart"></i> </a> </span></div><div class="rightbx paft5"><span> <i class="fas fa-comment-alt"></i></span></div></div>');
                this.container.$el.append(this.$el);
                this.hide();
                return this;
            }
        });

        var player = new Clappr.Player({
            source: "big_buck_bunny.mp4",
            poster: 'http://arsenal.ir/images/news/big/951b34e2-c033-420f-921c-75bc58f40a8c.jpg',
            parentId: "#player",
            plugins: [Ratestarvideo]
        });`

**Comment by Arman-Amirahmadi** [comment]
` 
    <style type="text/css">
        .R_boxer {
        float:right;
        width:40px;
      
        }
        .rightbx {
            position: relative;
            float: right;
            margin-top: 10px !important;
            margin-right: 10px !important;
            padding-top: 8px !important;
            width: 40px;
            height: 40px;
            background-color: rgba(255,255,255, 0.5);
            **z-index: 999999999;**
            border-radius: 200px;
            transition: opacity .55s ease-in-out;
            -moz-transition: opacity .55s ease-in-out;
            -webkit-transition: opacity .55s ease-in-out;
        }

      
            .paft5
        {
            padding-top: 5px !important;
        }
        
        .rightbx span
        {
            opacity: .1;
            font-size: 27px;
            padding: 0;
            font-family: FontAwesome !important;
            z-index: 2;
        }
        .rightbx:hover > span
        {
            color: red;
            opacity: 1;

        }
         .rightbx:hover {
            opacity: 1;
            -webkit-box-shadow: 0px 0px 15px 0px rgba(0,0,0,0.43);
            box-shadow: 0px 0px 15px 0px rgba(0,0,0,0.43);
            transition: opacity .55s ease-in-out;
            -moz-transition: opacity .55s ease-in-out;
            -webkit-transition: opacity .55s ease-in-out;
        }
        
      
  

    </style>


`


I used 999999999 !!! :-( but it does NOT working well

**Comment by kslimani** [comment]
Try to bind a click event on your buttons and call `preventDefault()` and/or `stopPropagation()` of the click event object.

**Comment by Arman-Amirahmadi** [comment]
@kslimani would you please give me example

**Comment by kslimani** [comment]
Go to [Clappr demo page](http://clappr.io/demo/) and copy paste this example :

```javascript

var playerElement = document.getElementById("player-wrapper");

var MyPlugin = Clappr.UICorePlugin.extend({
  name: 'my_plugin',
  bindEvents: function() {
    this.listenTo(this.core.mediaControl, Clappr.Events.MEDIACONTROL_CONTAINERCHANGED, this._onMediaControlContainerChanged);
  },
  _onMediaControlContainerChanged: function() {
      this._appendElToContainer();
  },
  _appendElToContainer: function() {
    this.core.mediaControl.container.$el.append(this.el);
  },
  render: function() {
    // will draw a small blue square on top left
    this.$btn = $('<div>')
      .css({
        'position': 'absolute',
        'z-index': '999',
        'width': '40px',
        'height': '40px',
        'background-color': '#00f',
      })
      .on('click', function(e) {
        // prevents mouse click propagation
        e.preventDefault();
        e.stopPropagation();
        console.log('click !');
      });

    this.$el.append(this.$btn);
  },
});

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  plugins: [MyPlugin],
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

**Comment by kslimani** [comment]
@Arman-Amirahmadi i cannot reproduce your issue on Clappr demo page. When i click on blue box it display message in console as expected. It only goes fullscreen if i double click (which is an expected behaviour due to html5 video element).

**Comment by Arman-Amirahmadi** [comment]
@kslimani Thank you man  
How can hide  the blue box and show it with button box ( controller )

**Comment by kslimani** [comment]
@Arman-Amirahmadi take a look at [this plugin](https://github.com/LA1TV/clappr-heading-plugin), it should give you enough hints to resolve your issues.
_(i learned how to create my first Clappr plugin through this plugin !)_.
