### ISSUE TITLE
function is not defined - CommentPlugin

### ISSUE THREAD

**Issue by Arman-Amirahmadi** [clappr/clappr#1677]
i made a plugin , external
and i got a error

<img src='https://image.ibb.co/fUxfw8/2018_07_25_17_36_31.jpg'>

### my JS  is .....

var MyPlugin = Clappr.UICorePlugin.extend({
  name: 'CommentPlugin',
  bindEvents: function () {
    this.listenTo(this.core.mediaControl, Clappr.Events.MEDIACONTROL_CONTAINERCHANGED, this._onMediaControlContainerChanged);
    this.listenTo(this.core.mediaControl, Clappr.Events.CONTAINER_MOUSE_ENTER, this.show);
    this.listenTo(this.core.mediaControl, Clappr.Events.CONTAINER_MOUSE_LEAVE, this.hide);
  },
  _onMediaControlContainerChanged: function () {
    this._appendElToContainer();
  },
  _appendElToContainer: function () {
    this.core.mediaControl.container.$el.append(this.el);
  },
  render: function () {

    this.$btn = $('<div id="com_plugin" class="R_boxer"> <div class="rightbx paft5" id="MainLike"> <span>  <i class="fas fa-heart"></i> </span> <div class="rating" id="likebox"><span id="star5">☆</span><span id="star4">☆</span><span id="star3">☆</span>  <span id="star2">☆</span>   <span id="star1">☆</span></div></div> <div class="rightbx paft5" id="comment"><span> <i class="fas fa-comment-alt"></i></span> </div>  </div>')
      .css({
        'position': 'absolute',
        'z-index': '999',
        'width': '200px',
        'right': '0px',
        'font-size': '31px',
        'height': '40px',

      })
      .on('click', "#star1", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 1 !'); })
      .on('click', "#star2", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 2 !'); })
      .on('click', "#star3", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 3 !'); })
      .on('click', "#star4", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 4 !'); })
      .on('click', "#star5", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 5 !'); })
      .on('click', "#comment", function (e) { e.preventDefault(); e.stopPropagation(); console.log('ITS comment :D'); })
      ;
    this.$el.append(this.$btn);
  },

});

**Comment by kslimani** [comment]
Your player configuration is wrong. It should be somthing like :

```javascript
var player = new Clappr.Player({
  source: 'http://path/to/video.mp4',
  parentId: '#player-wrapper',
  plugins: [MyPlugin],
});
```

Be careful not to confuse the name of the class with the plugin internal name. In your javascript code, you named the plugin class instance __MyPlugin__ with the internal name __CommentPlugin__.

I suggest you change it to something like : 

```javascript
var CommentPlugin = Clappr.UICorePlugin.extend({
  name: 'comment_plugin',
  // [...]
});
```

**Comment by kslimani** [comment]
Please note that "mediacontrol" player option is used to override the default internal [mediacontrol](https://github.com/clappr/clappr/blob/master/src/components/media_control/media_control.js) component.

**Comment by Arman-Amirahmadi** [comment]
Thank you @kslimani
and finally , how can i add CSS to my plugin's js file???

**Comment by kslimani** [comment]
Most of external plugins use a module bundler, which ease this issue. You should take a look at [Clappr external plugin list](https://github.com/clappr/clappr/blob/master/doc/EXTERNAL_PLUGINS.md) and take the time to study plugins projects to findout which one could satify yours.

**Comment by Arman-Amirahmadi** [comment]
@kslimani 
<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/nydd_2018-08-01_17-30-18.jpg" border="0" alt="آپلود عکس" /></a>

NOW ... i want to config 

  var player = new Clappr.Player({
            source: 'http://clappr.io/highline.mp4',
            plugins: [MyPlugin],
            height: 360,
            width: 640,
            MyPlugin: {
                rate_enabled:true,
                rate_url: '',
                rate_name: '',
                comment_enabled:true,
                comment_url:'',
                comment_name: '',
            },
        });



i want...

if comment_enabled:true , the comment icon will show , and if its false , so i disable comment icon

?

**Comment by leandromoreira** [comment]
If you're doing an `UICorePlugin`, you can access the options through the `this.core.options.MyPlugin`

**Comment by leandromoreira** [comment]
Post the code of your plugin here.

**Comment by Arman-Amirahmadi** [comment]
@leandromoreira 
download file from : https://ufile.io/azcnk

i added these line as comment to the code 
     

>   //////  my Request and Quesstion
>       //////  1- i want to enable / disable  plugin with  rate_enabled AND comment_enabled
>       //////  if rate_enabled was FALSE in config, 'stars' must NOT show in player
>      //////  if comment_enabled was FALSE in config, 'stars' must NOT show in player
>      //////  2-I need Ajax to send rate_name/comment_name to an Url ( rate_url OR comment_url )
>

**Comment by leandromoreira** [comment]
@Arman-Amirahmadi I won't download your file but here's the gist: if you're doing an `UICorePlugin`, you can access the options through the `this.core.options.CommentPlugin` inside your functions.

**Comment by Arman-Amirahmadi** [comment]
@leandromoreira  it is not new information

i don know where should i use the code  `this.core.options.CommentPlugin`  



plugin Js: 

`var CommentPlugin = Clappr.UICorePlugin.extend({
 

  name: 'CommentPlugin',
  bindEvents: function () {
    this.listenTo(this.core.mediaControl, Clappr.Events.MEDIACONTROL_CONTAINERCHANGED, this._onMediaControlContainerChanged);
    this.listenTo(this.core.mediaControl, Clappr.Events.CONTAINER_MOUSE_ENTER, this.show);
    this.listenTo(this.core.mediaControl, Clappr.Events.CONTAINER_MOUSE_LEAVE, this.hide);

  },
  _onMediaControlContainerChanged: function () {
    this._appendElToContainer();
  },
  _appendElToContainer: function () {
    this.core.mediaControl.container.$el.append(this.el);
  },
  render: function () {

    this.$btn = $('<div id="com_plugin" class="R_boxer"> <div class="rightbx paft5" id="MainLike"> <span>   <svg width="30" height="30" xmlns="http://www.w3.org/2000/svg"> <g><rect fill="none" id="canvas_background" height="32" width="32" y="-1" x="-1" /> <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid"> <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%" /></g></g><g> <path stroke="#000" id="svg_1" d="m306.317757,141.523815c49.681566,-119.902053 244.335573,0 0,154.159783c-244.335573,-154.159783 -49.681566,-274.061836 0,-154.159783z" stroke-width="15.5" fill="#fff" /><path stroke="#ff0000" id="svg_2" d="m15.256412,10.73355c4.42795,-10.298192 21.776804,0 0,13.240532c-21.776804,-13.240532 -4.42795,-23.538724 0,-13.240532z" fill="#bf0000" /></g></svg> </span> <div class="rating" id="likebox"><span onclick="myFunction()" id="star5">☆</span><span id="star4" onclick="myFunction()">☆</span><span id="star3" onclick="myFunction()">☆</span>  <span id="star2" onclick="myFunction()" >☆</span>   <span id="star1" onclick="myFunction()" >☆</span></div></div> <div class="rightbx paft5" id="comment" onclick="myFunction()"><span>  <svg width="30" height="30" xmlns="http://www.w3.org/2000/svg">    <g>  <rect fill="none" id="canvas_background" height="32" width="32" y="-1" x="-1" /> <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid"> <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%" /> </g>   </g>   <g>  <path stroke="#000" id="svg_2" d="m4.472179,25.588237l4.225187,-7.550059l0,0c-4.476246,-2.277518 -5.753538,-6.567875 -2.950895,-9.911835c2.80259,-3.343941 8.768014,-4.647068 13.781436,-3.010535c5.013421,1.636523 7.434262,5.677085 5.592598,9.334742c-1.841566,3.657655 -7.342841,5.735348 -12.709318,4.799945l-7.939008,6.337743z" stroke-opacity="null" fill="#ffffff" /></g></svg></span> </div>  </div>')
                  .css({
        'position': 'absolute',
        'z-index': '999',
        'width': '200px',
        'right': '0px',
        'font-size': '31px',
        'height': '40px',

      })
      .on('click', "#star1", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 1 !'); })
      .on('click', "#star2", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 2 !'); })
      .on('click', "#star3", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 3 !'); })
      .on('click', "#star4", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 4 !'); })
      .on('click', "#star5", function (e) { e.preventDefault(); e.stopPropagation(); console.log('star 5 !'); })
      .on('click', "#comment", function (e) { e.preventDefault(); e.stopPropagation(); console.log('ITS comment :D'); })
      ;
    this.$el.append(this.$btn);
  },
  
});


`

` <script type="text/javascript" charset="utf-8">
    window.onload = function () {

      var player = new Clappr.Player({
        source: 'http://www.html5rocks.com/en/tutorials/video/basics/devstories.mp4',
        parentId: '#player-wrapper',
        CommentPlugin: {
                rate_enabled:true,
                rate_url: '',
                rate_name: '',
                comment_enabled:true,
                comment_url:'',
          comment_name: '',
        
            },
        plugins: [CommentPlugin]
      });

     //////  my Request and Quesstion

     //////  1- i want to enable / disable  plugin with  rate_enabled AND comment_enabled
     //////  if rate_enabled was FALSE in config, 'stars' must NOT show in player
     //////  if comment_enabled was FALSE in config, 'stars' must NOT show in player
 
      ////// 2-I need Ajax to send rate_name/comment_name to an Url ( rate_url OR comment_url )

      
    }
  </script>`

**Comment by leandromoreira** [comment]
@Arman-Amirahmadi were you able to access your options through `this.core.options.CommentPlugin.rate_enabled` ?

**Comment by Arman-Amirahmadi** [comment]
@leandromoreira 
Yes ! every where i need , i can access to  `this.core.options.CommentPlugin.rate_enabled`
question: 
1- where should i use it to handle the job 
2- is this the syntax  :arrow_down_small: 
 `this.core.options.CommentPlugin.rate_enabled:true` 
`this.core.options.CommentPlugin.rate_enabled:false`

**Comment by leandromoreira** [comment]
@Arman-Amirahmadi you can read the wiki https://github.com/clappr/clappr/wiki/Our-first-plugin it shows how to create the simplest plugin ever with UI and then you can jump on some of the existent plugins to see how they work.

**Comment by Arman-Amirahmadi** [comment]
@leandromoreira  yes ... but i did not find the answer ....
its about 'Hello World' project with no Function , so i did it before.
at this moment i need to onclick='CallFunc' and , i know  know how >?!

**Comment by leandromoreira** [comment]
@Arman-Amirahmadi this project is very simple https://github.com/lucasrodcosta/clappr-nerd-stats/blob/master/src/clappr-nerd-stats.js it offers an UI and it has click function.
