### ISSUE TITLE
Is it possible to listen to video tag events? 

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1678]
A question.
I'm trying to implement Apple Fairplay streaming in playback extention (not a piece of cake for beginner). Its front-end example code contains event listeners for video tag itself (specifically 'webkitneedkey' and 'error'). How could I listen to these within a playback plugin or from outside?
Or may FPS be already implemented in Clappr?

**Comment by kslimani** [comment]
There are several technical solutions.

One technical solution may be to create a playback plugin which extends [hls.js](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js) playback plugin. (as an external plugin, it will be prioritary loaded). Note also that hls.js playback plugin extends [html5_video](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js) playback plugin.

Then you can add your own logic and or listen to particular video element events.

If you never yet created an external playback plugin [this project](https://github.com/kslimani/clappr-playback-boilerplate) may be a good start. (it 's a playback plugin boilerplate project which should still be functional).

**Comment by sapolio** [comment]
@kslimani 
Thank you very much.
I will certainly make a PR to hls.js as soon as I become a real coder )

**Comment by shishiraHaleneer** [comment]
@sapolio Any luck extending hls playback plugin of clappr ? I also tried listening to events of video tag in safari browser. but it didnt work . I came across this though https://github.com/video-dev/hls.js/issues/1628

**Comment by sapolio** [comment]
@shishiraHaleneer
This works for me, in Safari too:
```
class myExtension extends HLS {
    someMethod() {
        this.el.addEventListener('webkitneedkey', this.onneedkey, false)
    }
}
```
`this.el` contains a reference to a video element created by the playback in this particular case.

**Comment by shishiraHaleneer** [comment]
@sapolio thanks for reponse, It was problem with CORS. I resolved it. But I got different error this time 
XMLHttpRequest cannot load skd://<key>. Cross origin requests are only supported for HTTP.

**Comment by sapolio** [comment]
@shishiraHaleneer 
sorry for the long silence.
Fairplay streaming playlist causes such an error if you are not on Safari + OS X.
BTW: I've just implemented the very first version of Fairplay ready HTML5-playback extension, so I could answer some questions. )
