### ISSUE TITLE
enhancement: source-less player instance

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr#1679]
See [this example](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK) in Clappr demo page.

If i create a source-less player instance, the playback isn't supposed to render no ? (and not displaying the playback support error).

If i remember well,  previous Clappr version did not have this behaviour.

@towerz @joaopaulovieira @jhonatangomes @leandromoreira what do you think ?

EDIT: and @vagnervjs ! :grinning:

**Comment by jhonatangomes** [comment]
I think it was always like this, but I don't think it's the best way.

Maybe just a black box as a placeholder with the core created but without a container should be better. 

What do you think?

**Comment by towerz** [comment]
The behavior was always like this, since we didn't think creating a player instance with no sources was necessary. It wouldn't harm to have the player created with no containers (since there's no source configured), as @jhonatangomes mentioned. We already talked about this and will have it implemented.

**Comment by kslimani** [comment]
At the time i wrote this issue, i was pretty sure i could create a source less instance in the past without the error message (sorry for that). I think i used a "dummy" source to do the trick when i did those tests.

But yeah, the ability to handle "no source" at construction time can be a nice enhancement. (especially for mobile devices).

_PS: since you tagged as "enhancement" i left the issue open. (but feel free to close it, if required)._

**Comment by joaopaulovieira** [comment]
This is a nice one to do on [Clappr-core](https://github.com/clappr/clappr-core). What you think, @towerz ?

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
