### ISSUE TITLE
HTML5Video Playback's attemptAutoPlay() fails for mobile devices because this.consented can never be true

### ISSUE THREAD

**Issue by stefanullinger** [clappr/clappr#1680]
**Browser**: Safari 11
**OS**: iOS 11.4
**Clappr Version**: 0.2.97

**Steps to reproduce**:

* On iOS Safari, open [https://jsfiddle.net/stefanullinger/j2tarp3x/embedded/result](https://jsfiddle.net/stefanullinger/j2tarp3x/embedded/result)
* click the play button
* I was expecting to see the player playing the stream, but instead I need to manually click the player again to start the playback, i.e. "autoplay" does not work.

I have identified https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L161 to be the problem, as `this.consented` can never be true at this point in the code.

Previous discussion started here: https://github.com/clappr/clappr/pull/1644#issuecomment-410216072

Thanks in advance!

Best,
Stefan

**Comment by kslimani** [comment]
Good catch. I will take a deeper look ASAP. 👍

**Comment by kslimani** [comment]
I pushed a fix which should satisfy this issue.

Also, about #1644 discussion,

in the provided JSFiddle example, i see you created a source-less instance of the player which may display an error message. (see #1679 ) and also fails to "consent" (since no playback instance resolved).

As workaround, i suggest to use this little trick which use a "dummy" mp4 video source :

```javascript
var player = new Clappr.Player({
  parentId: '#playerWrapper',
  source: Clappr.Utils.Media.mp4,
  mimeType: 'video/mp4',
  playback: {
    recycleVideo: true,
    playInline: true
  }
});

$('#play').on('click', function() {
  // at this point, the video element (used by dummy video) will be consented
  player.consent();

  // at this point, a new playback instance will be created, recycling the consented video element
  player.load('https://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_2mb.mp4', '', true);
});
```
