### ISSUE TITLE
Fullscreen doesn't fire on iOS

### ISSUE THREAD

**Issue by amiznikov** [clappr/clappr#1682]
**Browser**: Safari

**OS**: ios 11.4

**Clappr Version**: 0.2.97

**Steps to reproduce**:

Just start on Iphobe you demo and use my config.
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
    playback: {
      playInline: 'playsinline'
    },  
  events: {
  onReady: function() {
    console.log('ready')
  },
   onResize: function()  {
     console.log(Clappr.Player.Utils.isFullscreen())
   }
  }
});
player.on(Clappr.Events.PLAYER_RESIZE, function() { 
  console.log(Clappr.Utils.isFullscreen())
});
player.on(Clappr.Events.PLAYER_FULLSCREEN, function() { 
  console.log(arguments)
  console.log(Clappr.Utils.isFullscreen())
  })
player.attachTo(playerElement);

or you can use link
http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogICAgcGxheWJhY2s6IHsKICAgICAgcGxheUlubGluZTogJ3BsYXlzaW5saW5lJwogICAgfSwgIAogIGV2ZW50czogewogIG9uUmVhZHk6IGZ1bmN0aW9uKCkgewogICAgY29uc29sZS5sb2coJ2hlbGxvIHdvcmxkJykKICB9LAogICBvblJlc2l6ZTogZnVuY3Rpb24oKSAgewogICAgIGNvbnNvbGUubG9nKENsYXBwci5QbGF5ZXIuVXRpbHMuaXNGdWxsc2NyZWVuKCkpCiAgIH0KICB9Cn0pOwpwbGF5ZXIub24oQ2xhcHByLkV2ZW50cy5QTEFZRVJfUkVTSVpFLCBmdW5jdGlvbigpIHsgCiAgY29uc29sZS5sb2coQ2xhcHByLlV0aWxzLmlzRnVsbHNjcmVlbigpKQp9KTsKcGxheWVyLm9uKENsYXBwci5FdmVudHMuUExBWUVSX0ZVTExTQ1JFRU4sIGZ1bmN0aW9uKCkgeyAKICBjb25zb2xlLmxvZyhhcmd1bWVudHMpCiAgY29uc29sZS5sb2coQ2xhcHByLlV0aWxzLmlzRnVsbHNjcmVlbigpKQogIH0pCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK

I can't see fullscreen event in Console, Safari browser.

**Comment by kslimani** [comment]
It *may* be an iOS Safari limitation, see [caniuse fullscreen api](https://caniuse.com/#feat=fullscreen).

But it may have changed in latests version of Safari, i will perform tests when i have some time.

**Comment by towerz** [comment]
@kslimani is right, there is a limitation on iOS Safari (and derived browsers). The fullscreen API is not supported, so what happens is that the video tag itself goes to fullscreen, without the `Core` instance receiving an event for that transition.

I'll investigate better if we can add a way to detect this transition and trigger the fullscreen event properly, but it still wouldn't be under the player control.

**Comment by amiznikov** [comment]
But you can use two events webkitbeginfullscreen webkitendfullscreen and this events works great on all ios devices) exactly i don't now about something flag, which show me enable or disable fullscreen

**Comment by towerz** [comment]
@amiznikov the problem is not related to DOM events, but Clappr events. The way fullscreen is implemented is related to the fullscreen API, not the HTMLVideoElement fullscreen feature. Since the event occurs in a different component, we need to wire things out so that the video element fullscreen event triggers a Clappr fullscreen event.

**Comment by rgaufman** [comment]
Any solution to this?

**Comment by amiznikov** [comment]
> Any solution to this?

i use this code: 
`      this.player.core.getCurrentPlayback().$el.on('webkitendfullscreen', () => {
        try {
          this.player.core.handleFullscreenChange()
        } catch(e) {
        }        
      })`

but, i saw on new version it's fixed(i didn't test it)
