### ISSUE TITLE
Add disabling video loading animation to documentation

### ISSUE THREAD

**Issue by ranst91** [clappr/clappr#1683]
@towerz described a solution to the following issue:
The issue is as described in here: https://github.com/clappr/clappr/issues/893,

However, I couldn't find the documentation for it. I assume it should be documented

**Comment by towerz** [comment]
@ranst91 you can disable the spinner plugin:
```javascript
var player = new Clappr.Player({ ... });
// after attach
player.getPlugin('spinner').disable();
```

**Comment by ranst91** [comment]
It seems to resolve the issue. That probably means this issue should go towards the documentation problem. Such a simple fix is expected to already be mentioned in documentation.

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/pull/1685
