### ISSUE TITLE
How to add chart at top of seekbar

### ISSUE THREAD

**Issue by Arman-Amirahmadi** [clappr/clappr#1684]
Hi every one , i want to add chart at top of seek bar.
in RED BOX i want to add chart 

<a href="https://image.ibb.co/jdusmK/2018_08_08_11_26_23.jpg" target="_blank"><img src="https://image.ibb.co/jdusmK/2018_08_08_11_26_23.jpg" border="0" alt=" ax" /></a>

 **how to add HTML add top of Seek bar , ( it show/hidden with seek bar )**

**Comment by Arman-Amirahmadi** [comment]
@leandromoreira , Leo do you have solution ?

**Comment by leandromoreira** [comment]
I think you need to code your CSS not based on a fixed size but using the media element as reference.

**Comment by Arman-Amirahmadi** [comment]
so i do it with css
