### ISSUE TITLE
How to disable playback on click?

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1686]
Hello!

I made a poster-plugin extension that shows the countdown before the broadcast starts.
But the player starts playback on the click, which is undesirable during the countdown
Please advise how to temporarily disable this behavior

**Comment by thiagopnts** [comment]
you can override the built-in poster plugin with yours without this functionality, as mentioned in this just merged new docs: https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#how-can-i-disable-or-override-a-plugin

**Comment by sapolio** [comment]
Thanks!
I've already successfully overrided built-in poster. But playback on click is implemented somewere else AFAIK.

**Comment by thiagopnts** [comment]
ah, you can try to `player.getPlugin('click_to_pause').disable();` then

**Comment by sapolio** [comment]
It only affects on Pause during playback ))

**Comment by sapolio** [comment]
There isn't any special code. Just like that `player.getPlugin('click_to_pause').disable();`
[test player](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwpwbGF5ZXIuZ2V0UGx1Z2luKCdjbGlja190b19wYXVzZScpLmRpc2FibGUoKTsK)

When the player is already playing this prevents of pause/play, but it does not block the very first click.

**Comment by sapolio** [comment]
I was inattentive, sorry.
I only needed to override the `clicked()` method of poster.
