### ISSUE TITLE
Multiple data source switching problems

### ISSUE THREAD

**Issue by fanzihui** [clappr/clappr#1688]
Browser: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
OS:  OS9, android6.0

Clappr Version: 0.2.25

When using vue.js, there are multiple m3u8 data sources on the page, but there are multiple players when changing data sources. What is the situation?

**Comment by kslimani** [comment]
The scenario you are describing sound like you are creating another player instance when you switch source.

What methodology do you use to switch source ?

**Comment by fanzihui** [comment]
Well, yes, I created a method directly in a method, but each time I execute new Clappr, it means that each time I create a player window, the previous one is not destroyed, so it appears multiple times. I hope that later, although new Clappr can display one, instead of adding a player each time it is created.

**Comment by kslimani** [comment]
I don't know how you strucured your vue.js rendering mechanisms, but when you create a Clappr Player instance (and attach it), it is added to the DOM.

If you want to remove it from the DOM, just call the player instance [destroy()](http://clappr.github.io/classes/Player.html#method_destroy) method.

You can also keep the player instance and load another source by calling the player instance [load()](http://clappr.github.io/classes/Player.html#method_load) method.

**Comment by fanzihui** [comment]
thank you
