### ISSUE TITLE
Stop player after a certain amount of time or on click

### ISSUE THREAD

**Issue by cviewsupport** [clappr/clappr#1692]
Is it possible to tell clappr player to stop playing after a certain amount of time like 5 minutes?

I started testing by trying to use a link to pass the "player.stop()" function... but I cant get it to work.

When I click the link to send player.stop() chrome dev tools says "player.stop is not a function".

`<button onclick="player.stop()">Test Stop</button>
`

Any ideas?

Once I was able to get it to stop by clicking the link... then I was going to work on the javascript to pass the "stop" function after a certain amount of time...

**Comment by flavioribeiro** [comment]
@cviewsupport do you mind hosting your code somewhere? first bet is that you're losing the context to `player` when passing the call to `setTimeout` or something

**Comment by cviewsupport** [comment]
Could I just paste the code from the page here?

What you said makes sense.... because I know player.stop() is a function of clappr.
it is like my javascript on the page is not connected to the clappr.js file to see the functions.

**Comment by cviewsupport** [comment]
I was thinking of pasting the code here... but it is a big page full of code... 
You probably don't want to read through all of that...

Would it be easier for me to just post the part where the player is initialized?

**Comment by flavioribeiro** [comment]
yes

**Comment by cviewsupport** [comment]
Just to be clear... the player is working fine.  It is just being able to use the player.stop(), player.pause() etc functions that I am having a problem with.

Here is the code.

We include clappr at the top of our page like this:
`<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>`

Then down the page we have these divs:

```
<div id="videoContainer" class="videoContainer">
     <div id="includedContent"></div>
  </div>
````

The div #includedContent gets populated from a file called calppr.html

Here is the clappr.html source:

```
`<div>
    <div id="player"></div>
    <script>
        var server = getParameterByName('server');
        var uuid = getParameterByName('uuid');
        uuid = uuid.replace(/-/g, "");

        var checkUrl = function() {
                $.ajax({
                        type : "GET",
                        url:"http://" + server + "/media/" + uuid + "/cview.m3u8",
                        error: function() {
                                checkUrl();
                        },
                        success: function() {
                                var player = new Clappr.Player({
                                        events: {
                                                onStop: function() {this.player.play(); },
                                                onEnded: function() {this.player.play(); },
                                                onError: function() {this.player.play(); }
                                        },
                                        language: 'en-EN',
                                        source: "http://" + server + "/media/" + uuid + "/cview.m3u8",
                                        autoPlay: true,
                                        disableVideoTagContextMenu: true,
                                        parentId: "#player",
                                        width: "100%",
					playInline: true,
                                });
                        }
                });
        }

        checkUrl();

    </script>



<!--kj stop testing-->
<button onclick="player.stop()">Test Stop or Pause</button>
<!--end kj stop function testing-->


</div>

````

At the bottom of that page you see the button where I try to call the player.stop() function.

Once I can get that to work... I will work on the ultimate goal... which is to get the video to stop after 5 minutes.

Thank you so much for your time!
I really do appreciate any tips you can give!

**Comment by leandromoreira** [comment]
maybe the easy solution would be to use [the event api](https://github.com/clappr/clappr/blob/master/doc/API_EVENTS.md):

```javascript
var player = new Clappr.Player({
  events: {
    onPlay: function() { // here you setTimetout player.stop()... },//Fired when player starts to play
  }
})
```

**Comment by cviewsupport** [comment]
OK, I changed up the code and now I can get it to fire the player.pause funcation after 5 seconds.... BUT the function does not work.   The video does not stop and I get an error.

My code:
```
                                        events: {
                                                onPlay: function() {setTimeout(player.pause, 4000); },
                                                onStop: function() {this.player.play(); },
                                                onEnded: function() {this.player.play(); },
                                                onError: function() {this.player.play(); }
                                        },
```
Error:
Uncaught TypeError: Cannot read property 'mediaControl' of undefined

**Comment by towerz** [comment]
@cviewsupport this is actually a JavaScript scope problem. You can't pass a method reference (`player.pause` - this is actually just a function) to be called by `setTimeout` without binding it to the player instance itself.

You need to bind it first, for example using `.bind()` or an arrow function:
```
setTimeout(player.pause.bind(player), 4000);
```
or 
```
setTimeout(() => player.pause(), 4000);
```

**Comment by cviewsupport** [comment]
Thank you!  I am now able to stop the video after a certain amount of time.

Do I have to do the scripting for this in the same code block where the new player object is created?
Or can I do it elsewhere on the page?

I need to add some type of message that tells people the video has timed out on purpose... and I would like to write the javascript for that elsewhere in the page to keep the "player code" clean...

Thanks again!!!!!

**Comment by towerz** [comment]
@cviewsupport you can do it anywhere. There's no limitation, as long as you have access to the player instance wherever you're handling the timeout. This way you can write your timeout script elsewhere.

**Comment by cviewsupport** [comment]
Can I still use the "event" in another place?

I ask because right now the event: is in the player code....
If I just skip down the page I still have access to the player but I can't use the "events" method again right?

```
var player = new Clappr.Player({
                                        events: {
                                                onPlay: function() { setTimeout(() => player.stop(), 60000); },
```
I can't do that again down the page... right?

**Comment by towerz** [comment]
@cviewsupport I'm not sure what you're asking.

I thought you wanted to have a function somewhere else that could be called by the `onPlay` event callback, and that would be able to pause or stop the video, like this:
```javascript
var player = new Clappr.Player({
  events: {
    onPlay: function() { setTimeout(stopVideoAndShowMessage, 6000); }
  }
});

// ... some more code or HTML tags

var stopVideoAndShowMessage = function() {
  player.stop();
  // show message that the video timed out
}
```

If that's not what you asked, please clarify, perhaps with an example.

**Comment by towerz** [comment]
@cviewsupport I just looked at your previous example, and you could just use your `timeOutVideo` function:
```javascript
var player = new Clappr.Player({
  events: {
    onPlay: function() { setTimeout(timeOutVideo, 6000); }
  }
});
```
In this function you could just display the message you wanted to.

**Comment by cviewsupport** [comment]
Yes!  Thats pretty much what I am trying to do.
Question... in this line don't we have to bind the variable to the object?
onPlay: function() { setTimeout(stopVideoAndShowMessage, 6000); }

For example...
onPlay: function() { setTimeout(() => player.stop(), 60000); }, //binding the function to the object

Hopefully that makes sense?

**Comment by towerz** [comment]
@cviewsupport no, in this case, the function doesn't need to be bound since we are using the `player` reference itself. It only needs to be bound when referencing or calling directly a function that belongs to the player instance.

**Comment by cviewsupport** [comment]
That does not work... it is back to giving the same error it was in the beginning.
Uncaught TypeError: player.stop is not a function

```
var player = new Clappr.Player({
                                        events: {
                                                //onPlay: function() { setTimeout(() => player.stop(), 60000); },
                                                onPlay: function() { setTimeout(timeOutVideo, 5000); },
                                                onStop: function() {this.player.play(); },
                                                onEnded: function() {this.player.play(); },
                                                onError: function() {this.player.play(); }
                                        },
                                        language: 'en-EN',
                                        source: "http://" + server + "/media/" + uuid + "/cview.m3u8",
                                        autoPlay: true,
                                        disableVideoTagContextMenu: true,
                                        parentId: "#player",
                                        width: "100%",
					playInline: true,
                                });
                        }
                });
        }

        checkUrl();



var timeOutVideo = function() {
player.stop();
}

    </script>
```

**Comment by towerz** [comment]
@cviewsupport I just noticed that your player reference is scoped to your ajax success callback function. To be used externally, it should be declared in the same scope as the functions that access it.

You could just change the `var player` declaration to the script tag scope:

```javascript
var server = getParameterByName('server');
var uuid = getParameterByName('uuid');
uuid = uuid.replace(/-/g, "");
var player

var checkUrl = function() {
  $.ajax({
    type : "GET",
    url:"http://" + server + "/media/" + uuid + "/cview.m3u8",
    error: function() {
      checkUrl();
    },
    success: function() {
      player = new Clappr.Player({
//...
```

**Comment by kslimani** [comment]
@cviewsupport as @towerz already explained, your issue is about Javascript scope.

I recommend you first [read this article](https://hackernoon.com/understanding-javascript-scope-1d4a74adcdf5), then read [this one](https://toddmotto.com/everything-you-wanted-to-know-about-javascript-scope/).

It *should* give you enough explanations to solve your issue.

**Comment by leandromoreira** [comment]
> Someone said IE does not like those arrow functions.

then try the normal function.

```js
// since player is available that's fine
onPlay: function() { setTimeout(function() { player.stop()}, 5000); },
```

**Comment by cviewsupport** [comment]
Yes!  Thank you so much!  I should have thought of that!!! I had my mind stuck on having to bind the variable... I forgot you don;t have to do that if you are up in the function....  Thanks again!
