### ISSUE TITLE
sudden failure of the hls stream playback

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1695]
**Browser**: Chrome 68
**OS**: Ubuntu 16, OS X
**Clappr Version**: 0.2.85, 0.2.97 (and clappr demo page)

Playing back hls stream for some time (1 to 20 minutes), playback  synchronously (on different pages/machines) stops in two ways depending on player versions.

OS X / ubuntu + clappr .85:
  The screen freezes, chunklist requests continue to be sent, no .ts requests are sent.
  Looks like paused: play button is displayed in the corner. Being pressed turns into a stop button, and .ts requests begin to be successfully sent again. The next time you press the button (stop button at this moment), the playback continues.

Ubuntu + clappr .97:
  "Could not play video. There was a problem trying to load the video. Error code: hls:3"
  No requests are sent.

I could not reproduce the problem on other browsers.

**Comment by sapolio** [comment]
I'm pretty shure these two problems occur for single reason, they occur at the same moment playing back a single stream.

**Comment by kslimani** [comment]
Does the problems occurs for any video source, or it is a particular one ?

**Comment by sapolio** [comment]
Only one bad stream is known at the moment. And It surely is the reason.
I've just caught the error. Three players, two versions, single stream and error.
> PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: timestamp=26645333 duration=21333 size=498 side_data_size=0 is_key_frame=1 encrypted=0 discard_padding (ms)=(0, 0)

**Comment by kslimani** [comment]
You may be also interested to compare the hls.js library version embeded with each Clappr version. (the version is available, for example, by typing `console.log(Clappr.HLS.HLSJS.version)` in browser javascript console).

**Comment by sapolio** [comment]
Well, hlsjs is 0.8.9 and 0.9.1 respectively. But the difference in clappr behaviour is because of errorScreen plugin that was added in clappr@0.2.91.
So the problem is in the stream.
I listen to player errors and reload.
```
player.on(Clappr.Events.PLAYER_ERROR, err =>  {
   if (err.code === 'hls:3') {
       player.load(player.options.sourse)
       player.play()
    }
});
```
I don't know if there is a better way.

**Comment by kslimani** [comment]
In the case of HLSJS playback component, the `PLAYBACK_ERROR` event is trigger when a fatal error which cannot be cannot be recovered happen.

So yes, listening to `PLAYER_ERROR` to plug a playback retry mechanism is a good way.
(since it is fatal error, i think you don't need to check error code but just try to recover source).

There are also [some examples](https://github.com/clappr/clappr/blob/master/doc/PLAYER_ERRORS.md) in documentation.

**Comment by sapolio** [comment]
How could I emit an authentic fatal error to test my code?
Stream problems are not regular, and sometimes I have to wait a long time )

**Comment by kslimani** [comment]
Maybe load a source from the web/local network and suddenly unplug your network cable :grin: 

In chrome browser dev tools there is also a feature to simulate this.

**Comment by sapolio** [comment]
This issue could be closed I think.
The last question is how to reliably determine a fatal error and whether I need to do it at all. Probably not all of them are worth it to restart the player.
I'm a bit confused by the presence of many different designs of error objects.

**Comment by sapolio** [comment]
Thank you!
