### ISSUE TITLE
Mid roll plugin

### ISSUE THREAD

**Issue by dkisdbest** [clappr/clappr#1696]
Hi, is there any working mid roll plugin for clappr? I found this one https://github.com/JMVTechnology/Clappr-Ads/ it works on windows/android devices with chrome browser but it has this issue https://github.com/JMVTechnology/Clappr-Ads/issues/6 on chrome browser with apple devices.

sorry for posting this here but not getting response from elsewhere. any help appreciated

**Comment by andrefilimono** [comment]
There is the plugin for prerolls: https://github.com/kslimani/clappr-google-ima-html5-preroll
It can be simply extended to support midrolls.
