### ISSUE TITLE
How a core-plugin could know if container is created?

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1698]
I'm trying to make a core plugin get access to containers stuff.
The problem is that `this.core.getCurrentContainer()` returns undefined when `bindEvents()` is performed.
It's understood, that container is created later. But what should I do to catch Its appearance?

**Comment by kslimani** [comment]
Just listen to `CORE_READY` event to get current container and do cleanup (if any) using destroy method.

```javascript
export default class MyPlugin extends UICorePlugin {

  // [...]

  bindEvents() {
    this.listenTo(this.core, Events.CORE_READY, this._onCoreReady)
  }

  _onCoreReady() {
    // Here you can get curent container or playback
    let container = this.core.getCurrentContainer()
    let playback this.core.getCurrentPlayback()
  }

  _cleanup() {
    // Here do cleanup stuff (if any)
  }

  destroy() {
    this._cleanup()
    super.destroy()
  }
}
```

**Comment by towerz** [comment]
@sapolio if necessary, in addition to the method that @kslimani commented, you can use `CORE_CONTAINERS_CREATED` if you need to listen to all container creation events as well.
