### ISSUE TITLE
Download Live Streaming video with RTMP format

### ISSUE THREAD

**Issue by aroraayush** [clappr/clappr#1700]
**Browser**: Chrome 69

**OS**: Mac OS 10.11.1

**Clappr Version**: 0.2.25

**Steps to reproduce**:

I wish to allow a record button on my web page that shows live streaming video of my car dashcam. I want to allow "Start Recording" and "Stop Recording" functionality. How can I do so??

**Comment by leandromoreira** [comment]
Hi @aroraayush this is repository is only about the video player clappr if you want to know how to stream from your dashcam to a server you might look at [OBS](https://obsproject.com/) or other encoder and you can find tons of [good tutorials about that](https://medium.com/go-live/easy-steps-to-use-obs-for-youtube-live-490535eae598).

**Comment by aroraayush** [comment]
@leandromoreira Thanks for helping out. But, I want to add clappr to a webapge of mine and want to record and download the recorded bit on the client web page. OBS is a standalone app that I cannot request my users to download

**Comment by leandromoreira** [comment]
@aroraayush maybe you can take a look at [webrtc](https://webrtc.github.io/samples/src/content/getusermedia/gum/).
