### ISSUE TITLE
How the player selects the proper playback?

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1702]
Question.
Please explain how Clappr selects the proper playback?

I've implemented Fairplay streaming playback by extending html5_video.
Since Fairplay is always HLS with a slightly extended m3u8, I expect some conflicts, because this playlist and DRM system are supported only by Apple devices and the stream itself must be played only by native media element of Safari.
It should be used only if the three conditions match: OS X, Safari, extended m3u8 playlist

Other DRMs are coming soon, so I need to control this situation )
Thanks in advance!

**Comment by kslimani** [comment]
The logic to select a playback is in core factory [here](https://github.com/clappr/clappr/blob/master/src/components/container_factory/container_factory.js#L34).

As you can see, each playback classes expose a canPlay() method which return true or false. The first playback which return true will be used. (it resolve using source url and provided mime type).

For example, in HLS playback, the method is [here](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L616).
