### ISSUE TITLE
Speed of video

### ISSUE THREAD

**Issue by Tanya159** [clappr/clappr#1705]
Does the player support video rewind?

**Comment by MediaJunkie1** [comment]
Clappr does support seeking (rewind) IF the stream supports it.

If you want to rewind a stream that does not support dvr/seeking/rewind.... you would need to download the stream.

**Comment by Tanya159** [comment]
Sorry, incorrectly put it. Can the user change the playback speed?

**Comment by flavioribeiro** [comment]
https://github.com/Viewly/clappr-playback-speed 
https://github.com/bikegriffith/clappr-playback-rate-plugin

**Comment by kslimani** [comment]
Take a look at [this plugin](https://github.com/bikegriffith/clappr-playback-rate-plugin)
_(disclaimer : i don't know if it still work with latest version of the player)_
