### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Tanya159** [clappr/clappr#1707]
What means error code 3?

**Comment by Tanya159** [comment]
It's related to hls session. 
My code
`var playerElementR8 = document.getElementById("player-r8");
    playerR8 = new Clappr.Player({
        source: 'http://.../video.m3u8',
        mute: true,
        autoPlay: true,
        height: 190,
        width: 330
    });
    playerR8.attachTo(playerElementR8);`

**Comment by leandromoreira** [comment]
Can you attach more logging text from this error? (via console in the browser)

**Comment by Tanya159** [comment]
`Object
data:
details: "manifestParsingError"
fatal: true
networkDetails: XMLHttpRequest {onreadystatechange: ƒ, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
reason: "no level found in manifest"
type: "networkError"
url: "http://77.108.82.59:8080/R1/mono-1526483400-605.m3u8"
__proto__: Object
evt: "hlsError"`

**Comment by leandromoreira** [comment]
@Tanya159 it seems that your master playlist sometimes are empty`"no level found in manifest"`!
