### ISSUE TITLE
Not Working On Android

### ISSUE THREAD

**Issue by Lakhwinder123** [clappr/clappr#1708]
Hi I paste This Code

<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({source: "https://hlsotherent-lh.akamaihd.net/i/ams23_9xtashan@127489/index_2000_av-p.m3u8?sd=10&dw=7200&b=100-2500&rebase=on&hdntl=exp=1538140869~acl=!*%2fi%2fams23_9xtashan%40127489%2f*!%2fpayload%2fyupptvnewservice_5_-1_124.253.155.170_IN_124.253.155.170%2f*~data=hdntl~hmac=8bb678267f62fa9fdf7f009724ceda8b90e110f0dabf599a7e28734e6c33d817", parentId: "#player"});
  </script>
</body>

But It IS Work Fine On My Pc But Not On Android 
Error:- HLS4

**Comment by leandromoreira** [comment]
Did you try [to test your stream on clappr demo page?](https://github.com/clappr/clappr/blob/master/doc/BEFORE_OPEN_AN_ISSUE.md#guideline-to-open-an-issue-bug)

**Comment by leandromoreira** [comment]
If it does work on the demo page while using Android I suppose this might be something at your page, try to replicate the demo on your page.

**Comment by Lakhwinder123** [comment]
How to replicate demo on my page

**Comment by leandromoreira** [comment]
@Lakhwinder123 I'm sorry I was trying to say for you to try to see how the demo's code was done and then see if there is any changes between your code and the demo's code.

**Comment by Lakhwinder123** [comment]
same like demo but error came hls4
