### ISSUE TITLE
Can't disable a plugin on player ready.

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1709]
Hi!
Trying to hide the poster using `PosterPlugin.disable ()` on _PLAYER_READY_ does not succeed if I did not wait for a while.
The method is defined, the "enabled" key is changed, but `$el.hide ()` does not work.
Here is an example:
http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogIGV2ZW50czogewogICAgb25SZWFkeTogKCkgPT4gewogICAgICBjb25zdCBwb3N0ZXIgPSAKICAgICAgICBwbGF5ZXIuY29yZS5nZXRDdXJyZW50Q29udGFpbmVyKCkuZ2V0UGx1Z2luKCJwb3N0ZXIiKQogICAgICAgIAogICAgICBmdW5jdGlvbiBkKCkgewogICAgICAgIHBvc3Rlci5kaXNhYmxlKCkKICAgICAgfQogICAgICAKICAgICAgZCgpCiAgICAgIHNldFRpbWVvdXQoZCwgMTAwMCkKICAgIH0KICB9Cn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=

**Comment by sapolio** [comment]
The poster is still there in your example though. )
Actually I've tried to hide the button.
Well It's understood, that I have lots of possibilities of hiding unnecessary elements, but Isn't it even interesant? Because "disable" method seemed to be very reliable way to disable plugins. (at least for me)))

**Comment by kslimani** [comment]
oh ? poster plugin should not be enabled in my example.
(maybe is it Safari which display preview frame on video element ?)

Another issue may be at "PLAYER_READY" time, if you call disable() on plugin, it properly hide and disable plugin dom elements, BUT it does not remove the "poster" attribute on video element.

**Comment by sapolio** [comment]
I meant that the big play button was still there, as was the poster element itself. Of course, the poster image was not a problem.
At the moment, I'm solving the problem by replacing the built-in poster plugin with a dummy.

As I demonstrated in my example, the disable() method works fine a second after the player is ready, but it does not happen if I call it immediately.

[This line](https://github.com/clappr/clappr/blob/d1312ff18536a7134aa52372992c0236e2b19d0d/src/base/ui_container_plugin.js#L36) does not work on player ready
The following line works fine.
