### ISSUE TITLE
How to add Ads In player

### ISSUE THREAD

**Issue by lamadya** [clappr/clappr#1715]
hello 
i want to add ads like youtube in player please how to this

**Comment by leandromoreira** [comment]
You can look at the [external plugins](https://github.com/clappr/clappr/blob/master/doc/EXTERNAL_PLUGINS.md). There are at least two:
* https://github.com/kslimani/clappr-google-ima-html5-preroll
* https://github.com/vix-simplex/clappr-vast-ad-plugin
