### ISSUE TITLE
Customize error strings "could not play video ..."

### ISSUE THREAD

**Issue by patrickd2206** [clappr/clappr#1719]
Hi, currently I use the clappr player on the site https://blog.fs1.tv/gemeinderat/ and it works good. But is it possible to customize the error-strings? The stream is not sent all the time, just once a month, and I would like to communicate that in the error message. I saw that it is possible to change the language strings (https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md), but when i build that in only the language is changeing - not the error strings ("could not play video. there was a problem trying to load the video.") Can I customize that? 

Thanks very much!
Patrick

**Comment by yuanrunmao** [comment]
Yes.  For exmaple:
```javascript

new Clappr.Player({
    height: "100%",
    width: "100%",
    strings: {
        'zh-CN': {
           'default_error_title': '无法播放视频。',
           'default_error_message': '尝试加载视频时出了问题。',
           ......
       }
    }
```
The strings could be found at [src/plugins/strings.js#L35](https://github.com/clappr/clappr/blob/master/src/plugins/strings.js#L35) .

Hope this helpful.

**Comment by patrickd2206** [comment]
This helps:
new Clappr.Player({
    height: "100%",
    width: "100%",
    strings: {
        'zh-CN': {
           'default_error_title': '无法播放视频。',
           'default_error_message': '尝试加载视频时出了问题。',
           ......
       }
    }

The strings could be found at src/plugins/strings.js#L35 .

Thanks to Kevin Mao.
