### ISSUE TITLE
Help me "convert" this...

### ISSUE THREAD

**Issue by PostMalone** [clappr/clappr#1721]
Sorry if this question was already asked, but i have some issues with this code...:

I want to add "CdnBye" to my Clappr player (https://github.com/cdnbye/hlsjs-p2p-engine) but i dont know how...

This is my code: 

`    var playerElement = document.getElementById("ppp"); 
    var clap = {
    source: targetValue,
     height: "100%",
     width: "100%",
    parentId: "#ppp",
    plugins: [LevelSelector,ChromecastPlugin],   
    mimeType: "application/x-mpegURL",
    autoPlay: false,
    playInline: true,
    mediacontrol: {seekbar: "#eee", buttons: "#eee"}, 
    chromecast: {
              appId: '9DFB77C0',
              contentType: 'video/m3u8',
              media: {
                type: ChromecastPlugin.None,
                title: 'Live',
                subtitle: 'Live'
              }
            }
    }
    var player = new Clappr.Player(clap);`

All i need is add these things:

`    playback: [CDNByeClapprPlugin]
            },
            playback: {
                hlsjsConfig: {
                    debug: false,
                    // Other hlsjsConfig options provided by hls.js
                    p2pConfig: {
                        tag: 'clappr',
                        // Other p2pConfig options provided by CDNBye
                    }
                }
            }
        });`

But i have no idea how to without removing Chromecast and level selector plugins...

So if anyone could instert CdnBye to my code i would appreciate it.

**Comment by breim** [comment]
Buddy,

Did you try this example ? [Example]( https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/demo/clappr-demo.html)

**Comment by breim** [comment]
Buddy,

Did you try this example bellow ?
https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/demo/clappr-demo.html

**Comment by PostMalone** [comment]
> Buddy,
> 
> Did you try this example bellow ?
> https://github.com/cdnbye/hlsjs-p2p-engine/blob/master/demo/clappr-demo.html




Yes, i did, it works, but i'm having issues adding Level selector plugin and Chromecast plugin into that code :(
