### ISSUE TITLE
Video freezes and audio continues for 2 to 3 seconds at slow internet

### ISSUE THREAD

**Issue by shakthihcue** [clappr/clappr#1722]
**Browser**: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**OS**: Windows 10 Pro

**Clappr Version**: 0.2.100

**Steps to reproduce**:

* Go to demo site http://cdn.clappr.io/
* Paste the below code
   `var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: false,
  plugins: [Clappr.FlasHLS],
  height: 360,
  width: 640
});

player.attachTo(playerElement);`
* Run the player by throttling internet at 512kbps/256kbps

**Expected Behaviour**: Video and audio to stay in sync before, during and after buffer.

**Actual Behaviour**: Video freezes and audio plays for 2 to 3 seconds before buffering starts.

**Comment by leandromoreira** [comment]
* Did you see the same behavior with another dash resource (try to use an external example stream i.e. `https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd` )?
* Did you try [to debug to see if your stream is okay](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues)?

**Comment by shakthihcue** [comment]
- I am a noob in this streaming, muxing logics. Considering that my requirement is to play HLS v4 stream across browsers. I tried all resources that were available to try this issue

- Yes i did follow the steps mentioned except this step (tool to check the health of your stream) as I dint knew how to perform this step and consume the logs.

**Comment by leandromoreira** [comment]
@shakthihcue when you use the test stream `http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8` does it still behave the same?

**Comment by shakthihcue** [comment]
> http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8

It seems to work as expected but I would like confirm if the above url is by HLS v3 or HLS v4 as I got to know that HLS v4 has separate audio and video file because of which sync might miss.

Below are the manifest comparisons of urls.

- http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 (not sure about HLS version)

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2149280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=1280x720,NAME="720"
url_0/193039199_mp4_h264_aac_hd_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2149280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=1280x720,NAME="720"
url_1/193039199_mp4_h264_aac_hd_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=246440,CODECS="mp4a.40.5,avc1.42000d",RESOLUTION=320x184,NAME="240"
url_2/193039199_mp4_h264_aac_ld_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=246440,CODECS="mp4a.40.5,avc1.42000d",RESOLUTION=320x184,NAME="240"
url_3/193039199_mp4_h264_aac_ld_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=460560,CODECS="mp4a.40.5,avc1.420016",RESOLUTION=512x288,NAME="380"
url_4/193039199_mp4_h264_aac_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=460560,CODECS="mp4a.40.5,avc1.420016",RESOLUTION=512x288,NAME="380"
url_5/193039199_mp4_h264_aac_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=836280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=848x480,NAME="480"
url_6/193039199_mp4_h264_aac_hq_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=836280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=848x480,NAME="480"
url_7/193039199_mp4_h264_aac_hq_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6221600,CODECS="mp4a.40.2,avc1.640028",RESOLUTION=1920x1080,NAME="1080"
url_8/193039199_mp4_h264_aac_fhd_7.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6221600,CODECS="mp4a.40.2,avc1.640028",RESOLUTION=1920x1080,NAME="1080"
url_9/193039199_mp4_h264_aac_fhd_7.m3u8

- HLS v4 manifest

#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-0",NAME="Default",AUTOSELECT=YES,DEFAULT=YES,URI="segments/ZZZZZ360sample1_audio_v4.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=88120000,CODECS="avc1.640028",URI="segments/ZZZZZ360sample1_1080p_iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=78735000,CODECS="avc1.4d001f",URI="segments/ZZZZZ360sample1_720p_iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=47421000,CODECS="avc1.42001f",URI="segments/ZZZZZ360sample1_480p_iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=27884000,CODECS="avc1.42001e",URI="segments/ZZZZZ360sample1_360p_iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=16333000,CODECS="avc1.420015",URI="segments/ZZZZZ360sample1_270p_iframe.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4586000,RESOLUTION=1280x720,CODECS="avc1.640028,mp4a.40.2",AUDIO="audio-0"
segments/ZZZZZ360sample1_1080p_v4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3570000,RESOLUTION=1280x720,CODECS="avc1.4d001f,mp4a.40.2",AUDIO="audio-0"
segments/ZZZZZ360sample1_720p_v4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1962000,RESOLUTION=854x480,CODECS="avc1.42001f,mp4a.40.2",AUDIO="audio-0"
segments/ZZZZZ360sample1_480p_v4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1095000,RESOLUTION=640x360,CODECS="avc1.42001e,mp4a.40.2",AUDIO="audio-0"
segments/ZZZZZ360sample1_360p_v4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=840000,RESOLUTION=480x270,CODECS="avc1.420015,mp4a.40.2",AUDIO="audio-0"
segments/ZZZZZ360sample1_270p_v4.m3u8


Can you please direct me with right understanding of the difference.

**Comment by leandromoreira** [comment]
hey @shakthihcue the version is in the segment playlist (`ZZZZZ360sample1_720p_v4.m3u8`).

**Comment by leandromoreira** [comment]
[Here's a summary of HLS version features](https://www.gpac-licensing.com/2014/12/08/apple-hls-technical-depth/)

**Comment by shakthihcue** [comment]
So which means the stream(http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8) you shared of version 7 and the one i have shared is of version 4.

Could you please help me fix for this version 4 stream.

**Comment by leandromoreira** [comment]
@shakthihcue do you use any product to generate the streams?

**Comment by shakthihcue** [comment]
Amazon Elastic Transcoder.

Attaching below the sample preset for one of the quality:
Segment length = 6 sec
![image](https://user-images.githubusercontent.com/38973228/47495350-87707b80-d871-11e8-8b0a-c3e4e3f8310a.png)

**Comment by leandromoreira** [comment]
Maybe this can help you to select a smaller version https://aws.amazon.com/blogs/aws/ets-hls4-support/

**Comment by shakthihcue** [comment]
Thanks.

Which option do you recommend would generate a stream that would play with web application running on clappr, android on exoplayer and ios on native plugin.

PS: Exoplayer seems to pause video until both audio and video buffers are equal I suppose.

**Comment by shakthihcue** [comment]
But should player not support version 4 which has separate video and audio stream to run in sync.?

Just curious in a way to fix this issue at the player level. More detailed justification would really help me in taking back the points and demand for a change in streaming version.

**Comment by leandromoreira** [comment]
> But should player not support version 4 which has separate video and audio stream to run in sync.?

Yeah, you can search for each plataform/player/device, what issues do they have.
