### ISSUE TITLE
Is there a way to make streaming faster?

### ISSUE THREAD

**Issue by muzammilversiani** [clappr/clappr#1724]
I am using clappr in my Ionic 3 project. Its working good but the only issue is that the streaming is really slow. I always have to wait at least 10 seconds. This is my code:

                        var playerElement = document.getElementById("player");
			this.api = new Clappr.Player({
				source: "https://mystreamingserver/media.m3u8", 
				baseUrl: 'assets/js/clappr-master/dist',
				width: '100%',
				height: '100%',
				autoplay: true,
				preload: true,
				mimeType: 'application/x-mpegurl',
				watermark: 'assets/imgs/watermark.png',
				position: 'bottom-left',
				disableVideoTagContextMenu: false,
				disableKeyboardShortcuts: true,
				useHardwareVideoDecoder: false,
				chromeless: true
			});
			this.api.attachTo(playerElement);
                    this.api.load("https://mystreamingserver/media.m3u8", 'application/x-mpegurl', true);`

**Comment by leandromoreira** [comment]
Maybe this issue is related to your streaming, how long are the chunks? what's the avg latency for a given chunk?

**Comment by muzammilversiani** [comment]
Hi @leandromoreira sorry I don't have knowledge about chunks, can you tell me how can I find. One thing I want to share is that when I play the same media in the native Android VLC player, it works fine and there is no delay.

**Comment by leandromoreira** [comment]
@muzammilversiani have you tried to use the stream provided to test? I mean use this source http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 and see if the same delay happens.

**Comment by muzammilversiani** [comment]
Hi @leandromoreira 

I just tried your streaming link it took 4-5 seconds and after that it ran smoothly without buffering. I have attached screenshots of both the streaming requests. There is a difference, the bunny one is requesting only .ts files whereas mine is calling both m3u8 and ts.

![bunny](https://user-images.githubusercontent.com/3109193/47951967-2e4bca80-df8a-11e8-8872-062f894f1dd3.png)
![mine](https://user-images.githubusercontent.com/3109193/47951969-31df5180-df8a-11e8-924a-93082275d3ca.png)

**Comment by leandromoreira** [comment]
@muzammilversiani by looking only at these logging I assume that part of your start up problem is related to the size of your chunks, you can see that it took many seconds to download a single video segment file (.ts).

Try to shrink your segment size (like from 10s to 4s or 5s), this option is probably available at your stream service.

**Comment by muzammilversiani** [comment]
Hi @leandromoreira ok I will try and let you know.

Thank you so much

**Comment by muzammilversiani** [comment]
Hi @leandromoreira thank you so much mate, that fixed the issue, the channels are loading faster than before. There is still something I need to ask. Sometimes I get the error "Could not load the playback" or something like this. I happens when the first segment (.ts) file failed to fetch for some reasons. Is there any way to retry. I mean if the segment failed to fetch, player should retry this until it gets the segment?

**Comment by leandromoreira** [comment]
I'm glad, sure you can see an [example about retrying errors at the documentation](https://github.com/clappr/clappr/blob/master/doc/PLAYER_ERRORS.md)

**Comment by muzammilversiani** [comment]
@leandromoreira thank you so much man! Its working just perfect!
