### ISSUE TITLE
Stereo audio track not playing in video in ionic 3 

### ISSUE THREAD

**Issue by pawanvivekananda** [clappr/clappr#1725]
**Browser**: ionic 3

**OS**: Android

**Clappr Version**: 0.2.100

**Steps to reproduce**:

Take a Stereo audio track hls video in android and play one track goes missing.

**Comment by leandromoreira** [comment]
@pawanvivekananda did you try to run this resource http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 ?

**Comment by leandromoreira** [comment]
Does it produce the same issue?
