### ISSUE TITLE
Chromecast problems

### ISSUE THREAD

**Issue by yashpunjabi** [clappr/clappr#1726]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Google Chrome 70.0.3538.77 (Official Build) (64-bit)

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Windows 10

When chromecasting most videos, a lot of people are just seeing 'Clappr' on screen and nothing else.
See https://www.reddit.com/r/Chromecast/comments/7jg0nw/i_just_get_the_message_clappr_when_trying_to_cast/ for examples of people struggling with issue

**Comment by leandromoreira** [comment]
@towerz did the latest release fixed this?

**Comment by ziddey** [comment]
This sounds like an implementation issue by whatever bootlegger is providing the streams. Many of these streams require some form of credentials or drm, which are not supported by the default chromecast receiver.
