### ISSUE TITLE
videos cannot be separated

### ISSUE THREAD

**Issue by emmmmmmp** [clappr/clappr#1730]
Hello,
I couldn't separate them from each other.
There are five videos on my website, https://www.oneleaf.pro/2018/11/07/ffmpeg-bbc/
Please give me a hand.

**Comment by kslimani** [comment]
In your website page, you have only one div element with id="player" and you use it for the four player.
I suggest you to create four div with, for example, id which equals "player1",  "player2", etc...

**Comment by emmmmmmp** [comment]
Thank you! It's perfect now.
