### ISSUE TITLE
PiP for desktop?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1731]
Since Chrome 70 for desktop brings picture-in-picture I miss that option for Clappr.
Is there any way to enable it? I've tried the plugin but it does not work (or I don't see any button) by adding:

  <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.pip-plugin/latest/clappr-pip-plugin.js"></script>

...and...

plugins: [ClapprPIPPlugin]

**Comment by ziddey** [comment]
Working fine here by just right-clicking the video and selecting "picture in picture"

**Comment by hamesjarden** [comment]
Working fine here by just right-clicking the video and selecting "picture in picture." No plugin required

**Comment by hijuuijj** [comment]
I don't see any "picture in picture" option with right click from Clappr.
Anyway would be better to have an icon

**Comment by hamesjarden** [comment]
Should be very simple to create a plugin if you want to give it a go:

https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture

If anything, you could just modify clappr-pip-plugin

**Comment by towerz** [comment]
@hijuuijj @hamesjarden we already have a working version of the pip plugin for Chrome. We'll release this version this week. Just setting up the repository and packages.

**Comment by hijuuijj** [comment]
> @hijuuijj @hamesjarden we already have a working version of the pip plugin for Chrome. We'll release this version this week. Just setting up the repository and packages.

Thank you, I was thinking about changing Clappr to HLS.js
One of the reasons why Clappr does not convince me is this: https://github.com/clappr/clappr/issues/1617

**Comment by towerz** [comment]
@hijuuijj @hamesjarden we released the [clappr-pip](https://github.com/clappr/clappr-pip), which supports both OS-based picture-in-picture implementations. It's split into two different plugins, one for actually implementing the PiP and the other one for the media control button.

**Comment by hijuuijj** [comment]
I have noticed this:

https://cdn.jsdelivr.net/clappr/latest/clappr.min.js
Works with LevelSelector
Works with Chromecast
Does not work with PiP

https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js
Works with PiP
Does not work with LevelSelector
Does not work with Chromecast
Some m3u8 fail

Is there any way to integrate everything to the first one?

**Comment by towerz** [comment]
@hijuuijj we can't do that. Actually, the first url (https://cdn.jsdelivr.net/clappr/latest/clappr.min.js) uses an older format which can't be updated, so it was stuck on version 0.2.66.

The latter one is the one which is currently updating. We updated both [LevelSelector](https://clappr.github.io/clappr-level-selector-plugin/) and [Chromecast](http://clappr.github.io/clappr-chromecast-plugin/) plugins to work with it. You shouldn't have any issues with it. If you have a look at the links you'll see the plugins working with `clappr@latest`.

**Comment by towerz** [comment]
@hijuuijj about the m3u8 failures, do we have an issue for that? Are you referring to #1704?

**Comment by hijuuijj** [comment]
https://content.uplynk.com/channel/4ee18bd581dc4d3b90303e0cb9beeb0f.m3u8

Error code: hls:networkError_manifestParsingError with https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

With https://cdn.jsdelivr.net/clappr/latest/clappr.min.js works fine

**Comment by towerz** [comment]
@hijuuijj it's working with the latest Clappr, you can check it with the [demo page](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9jb250ZW50LnVwbHluay5jb20vY2hhbm5lbC80ZWUxOGJkNTgxZGM0ZDNiOTAzMDNlMGNiOWJlZWIwZi5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgYXV0b1BsYXk6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK)

**Comment by hijuuijj** [comment]
I know. The problem is that the new version does not seem to work on some servers.

**Comment by towerz** [comment]
@hijuuijj if it's not working with some servers, there may be some error either with the manifests or with the server response. The older version of Clappr that you mentioned uses an older version of hls.js and perhaps it doesn't enforce strict validation of the response or manifest.

If you have a sample that we can analyze, we could attempt to detect the issue and help you fix it, but I'd suggest you to follow [these instructions](https://github.com/clappr/clappr/blob/dev/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues) to detect any issues with those failing streams.

**Comment by towerz** [comment]
@hijuuijj if you want to continue the discussion about his.js and failing streams, let's move it to it's own issue. 

If you just want to use the picture in picture plugin for 0.2.x, you can use [clappr-pip 0.1.0](https://cdn.jsdelivr.net/npm/clappr-pip@0.1.0/dist/clappr-pip.min.js). It should work with 0.2.66, although I haven't tested it with such an old version. I tested with 0.2.100 and it worked correctly. I'd suggest you lock the versions of the other plugins (Chromecast, Level selector) as well, to avoid breaking on any future changes.
