### ISSUE TITLE
HLS AES Key Manual Injection

### ISSUE THREAD

**Issue by rafaellupo** [clappr/clappr#1732]
Hi,
I'm pretty new to Clappr, and I'm facing some basic issues like "How do I access HLSJS instance from Clappr instance?"

The point is that I want to rewrite the `hls.config.loader` function so I can do my own Key logic, like that one over here -> [Manual AES Key Injection](https://github.com/video-dev/hls.js/issues/946)

Any hint on how can I do that ?

**Comment by kslimani** [comment]
In the current lastest release and assuming `player` is the Clappr player instance and the resolved playback instance is the HLS one, then the HLS.JS instance is available with `player.core.activePlayback._hls`.

You should also be able to pass custom parameters to HLSJS constructor using the [hlsjsConfig](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#hls-buffer-length) config property.
