### ISSUE TITLE
TypeError: element.addEventListener is not a function.

### ISSUE THREAD

**Issue by lorenzosjb** [clappr/clappr#1733]
This happens with version 0.3.1 and 0.3.0, with 0.2.100 works perfect

![untitled](https://user-images.githubusercontent.com/7716358/48742750-d964b100-ec25-11e8-96fe-82e7050c4264.png)

**Comment by leandromoreira** [comment]
Thanks @lorenzosjb can you provide the following information:

```
Browser: YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox, IE)

OS: YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)

Steps to reproduce:

    first step
    then second step
    I was expecting X but instead it shows Y
```

**Comment by lorenzosjb** [comment]
* My browser is Chrome Version 70.0.3538.102 (Official Build) (64-bit)
* OS is Windows 7.0 Professional 64-bit Service Pack 1

Steps to reproduce:
* Using 
* "webpack": "3.5.1",
* "webpack-bundle-analyzer": "^2.9.1",
* "webpack-dev-server": "2.7.1",
* "babel-cli": "^6.26.0",
* "babel-cli": "^6.26.0",
* "babel-core": "6.25.0",
* "babel-eslint": "7.2.3",
* "babel-jest": "20.0.3",
* "babel-loader": "7.1.1",
* "babel-preset-es2015": "^6.24.1",
* "babel-preset-react": "^6.24.1",
* "babel-preset-react-app": "^3.0.2",
* "babel-preset-stage-0": "^6.24.1",
* "babel-runtime": "6.23.0",
* "react-responsive-modal": "^3.5.1",

I was expecting the player showing but instead it shows a blank screen and after several minutes this error.

`import` React from 'react';
import Modal from 'react-responsive-modal';
import Clappr from 'clappr';

class Player extends React.Component {

  constructor(props) {
    super(props);
    this.state = { open: false };
  }

  onOpenModal() { 
    this.setState({ open: true }); 
  }

  onCloseModal() { 
    this.setState({ open: false }); 
  }
  
  render() {
      return (
        <div>
          <a onClick={this.onOpenModal.bind(this)}>{this.props.title || 'Open Video Player'}</a>
          <Modal open={this.state.open} onClose={this.onCloseModal.bind(this)} center>
            <div style={{ width:'800px', height:'452px' }}>  
              <ClapprComponent id="ClapprVideo" source={this.props.url}  width="800px" height="454px" poster={this.props.poster}/>
            </div>
          </Modal>
        </div>
      );
  }

}

class ClapprComponent extends React.Component {

  componentDidMount() {
    const { id, source, width, height, poster } = this.props;
    this.clappr_player = new Clappr.Player({
      parent: `#${id}`,
      source,
      width,
      height,
      poster,
      autoPlay:true
    });
  }
  
  componentWillUnmount() {
    this.clappr_player.destroy();
    this.clappr_player = null;
  }
  
  render() {
    const { id } = this.props;
    return (<div id={id}></div>); 
  }
  
}

export default Player;
`

**Comment by towerz** [comment]
@lorenzosjb there's just a small issue with the parameters you're calling Clappr with. You're using `parent` instead of `parentId` to inform the parent element. Actually, the name you used makes more sense, but we initially only supported an element id.
