### ISSUE TITLE
How to play this stream directly in Live mode?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1736]
Is there any way to play this stream directly from "Live" point? I have to move the progress bar to the end.

http://canalsur-new-live.hls.adaptive.level3.net/egress/bhandler/canalsur_live/rtva_new/.m3u8

**Comment by ziddey** [comment]
Tried a handful of browsers using the clappr [demo](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NhbmFsc3VyLW5ldy1saXZlLmhscy5hZGFwdGl2ZS5sZXZlbDMubmV0L2VncmVzcy9iaGFuZGxlci9jYW5hbHN1cl9saXZlL3J0dmFfbmV3Ly5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK) and they all stream from the live point.

**Comment by hijuuijj** [comment]
Are you sure? try to move the progress bar to the end (even if it shows "Live")
