### ISSUE TITLE
Playback starts 10 seconds into video

### ISSUE THREAD

**Issue by ryan77627** [clappr/clappr#1737]
**Browser**: Firefox 62

**OS**: Fedora 28

**Clappr Version**: Latest version on jsdeliver

**Steps to reproduce**: 

* Go to this link:  https://beta.stoicproductions.org/newvideo/viewtopic.php?f=4&t=9
* Press play on video and it will start 10 seconds into the video
* I was expecting it to start at zero but it starts at zero

Did you try to reproduce this issue at http://cdn.clappr.io/?
* Yes, it started at zero like it should.

I have no idea why it keeps starting at 10 seconds, could it be cause of how phpbb handles bbcode since Codepen plus cdn works fine? Here is my code I'm using:

```
<script type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js">
  </script>
   <div id="player_video"></div>
  <script>
    var player = new Clappr.Player({
      source: "{URL}/index.m3u8",
      poster: "{URL}/poster.jpg",
      parentId: "#player_video",
      width: "100%",
      height: "auto"
    });
  </script>
```
({URL} is bbcode placeholder, the url it points to is: https://video.stoicproductions.org/Keppler2)

Is there anything that can affect where Clappr starts it's playback? Or is there an hls.js option I can set? Thanks!

**Comment by towerz** [comment]
@ryan77627 there seems to be a conflict between Clappr and your query string parameter. Clappr uses the `t` parameter by default as a starting position (in seconds), or it parses it from the format `(([0-9]+h)?([0-9]+m)?[0-9]+s)`.

So having `t=9` would always make the player start at 9 seconds into the video.

**Comment by towerz** [comment]
@ryan77627 there's an option that you can pass to the player for it to ignore the query string parameter, called `autoSeekFromUrl`. You just need to set it to `false`, so the player won't use the query string to auto-seek.

In your example, it would be:
```javascript
    var player = new Clappr.Player({
      source: "{URL}/index.m3u8",
      poster: "{URL}/poster.jpg",
      parentId: "#player_video",
      width: "100%",
      height: "auto",
      autoSeekFromUrl: false
    });
```

**Comment by ryan77627** [comment]
I just found the config option as you posted the answer, thanks. I'll do this since auto seeking isn't applicable yet for me. If it ever is I may try to figure out the code so I can change the letter it looks for in the URL, but that's for another day. Thanks for the help!
