### ISSUE TITLE
How to add AES Drm custom header or update drm url in playlist when playing?

### ISSUE THREAD

**Issue by mical892524** [clappr/clappr#1740]
Clappr extends Hls.js, In hls.js, it can custom pLoader and update playlist content when playing. so In Clappr, how to add AES Drm custom header or update drm url in playlist when playing?

**Comment by towerz** [comment]
@mical892524 you can pass options directly to hls.js through the playback options. For example, if you want to add a custom pLoader, just do:
```javascript
var player = new Clappr.Player({
  //...
  playback: {
    hlsjsConfig: {
      pLoader: ...
    }
  }
});
```

**Comment by mical892524** [comment]
@towerz  Can you give me a pLoader demo?

**Comment by kslimani** [comment]
Take a look at [HLS.JS documentation](https://github.com/video-dev/hls.js/blob/master/docs/API.md#loader).
