### ISSUE TITLE
Custom plugin

### ISSUE THREAD

**Issue by pdtan** [clappr/clappr#1741]
**Browser**: Latest Chrome

**OS**: Windows 10

**Clappr Version**: latest

**Steps to reproduce**:

* writed plugin
* added to player
* I was expecting button shown but instead it's not

Did you try to reproduce this issue at http://cdn.clappr.io/: yes, not showing

Source: https://pastebin.com/xDw0rzq6

**Comment by pdtan** [comment]
I'll wait for new updates. Btw where do I put the `setTimeout` function? Tried in `render` and `attachButton` but it didn't work.

**Comment by thekendog** [comment]
@pdtan did you ever figure this out?  I'm trying to do the same thing.
