### ISSUE TITLE
hls:4 error from ffmpeg generated content

### ISSUE THREAD

**Issue by REELcoder** [clappr/clappr#1743]
**Browser**: Safari Version 12.0.1 (13606.2.104.1.2), Firefox, etc.
**OS**: Mac OS 10.13.6

**Clappr Version**: 0.3.1

**Steps to reproduce**:

* I use ffmpeg to packetize live TV content received via DVB-S2 using the HLS output. Video is h264, Audio is ac3 and transcoded to aac. Each TS packet is ~1 second long. 
* Randomly the stream is not played and hls:4 error is raised
* Other players, e.g. VLC play the same content.

Example content: https://hackersgarden.dyn.ch/media/master_1.m3u8

Did you try to reproduce this issue at http://cdn.clappr.io/: Do not get CORS to work on my apache server...

**Comment by leandromoreira** [comment]
This might be related to the way you using ffmpeg, you can [check here](https://github.com/clappr/clappr/blob/dev/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues) some tools to do the verification over your stream.

**Comment by REELcoder** [comment]
hls.js: Buffer appending error

**Comment by leandromoreira** [comment]
@REELcoder this might point to a problem at your ffmpeg command line to generate hls. I recommend you to take a look at [this example](https://gist.github.com/mrbar42/ae111731906f958b396f30906004b3fa).

**Comment by REELcoder** [comment]
@leandromoreira Thanks for the hint. I use a recent ffmpeg which is able to create the master playlist itself. The following command is used. The video stream is h264 720p and is only copied by ffmpeg. The audiostream is transcoded to aac with ffmpeg defaults. 

`ffmpeg -i http://localhost:8008/1 -map 0:v -map 0:a:0 -c:v copy -c:a aac -f hls -hls_time 1 -hls_start_number_source datetime -hls_allow_cache 0 -hls_flags delete_segments -master_pl_name master_1.m3u8 ffmpeg_1_data.m3u8`

The manifests created by ffmpeg with above command are as follows:
master_1.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=433400,RESOLUTION=1280x720
ffmpeg_1_data.m3u8
```

ffmpeg_1_data.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:1
#EXT-X-MEDIA-SEQUENCE:20181216122741
#EXTINF:0.960000,
ffmpeg_1_data20181216122741.ts
#EXTINF:0.960000,
ffmpeg_1_data20181216122742.ts
#EXTINF:0.960000,
ffmpeg_1_data20181216122743.ts
#EXTINF:0.960000,
ffmpeg_1_data20181216122744.ts
#EXTINF:0.840000,
ffmpeg_1_data20181216122745.ts
#EXT-X-ENDLIST
```

To me this looks fine. In one out of 10 attempts clappr plays the ffmpeg generated content without problems. Occassionally clappr is stuck with the hls:4 errror and is not starting to play even if I wait a minute until ffmpeg has created new TS files and updated the ffmpeg_1_data.m3u8.

As you can see this is live content and ffmpeg deletes old TS files. Only 5 TS files are listed in the m3u8. There is only 1 quality level as the videostream is not transcoded. Your example is for VOD content which is statically held on the server.

**Comment by leandromoreira** [comment]
HTTP streaming requires you to have a closed GOP, I think that might be your problem, I'd suggest you to try these two commands (fine tune them to your neeeds, resolution and buffer size):

```bash
# here I'm assuming your input is 30 fps
ffmpeg -i http://localhost:8008/1 -map 0:v -map 0:a:0 \
          -c:v libx264 \ 
          -x264opts keyint=30:min-keyint=30:scenecut=-1 \ # we're forcing it to have 1 second gop without scene cut
          -tune zerolatency -s 1280x720 \ 
          -b:v 1400k -bufsize 1400k \ 
          -c:a aac \
          -f hls -hls_time 1 -hls_start_number_source datetime \ # maybe it'd be a good ideia to increment the hls time for 2
          -hls_allow_cache 0 -hls_flags delete_segments \
          -master_pl_name master_1.m3u8 ffmpeg_1_data.m3u8

# and changing the audio codec

ffmpeg -i http://localhost:8008/1 -map 0:v -map 0:a:0 \
          -c:v libx264 \ 
          -x264opts keyint=30:min-keyint=30:scenecut=-1 \ # we're forcing it to have 1 second gop without scene cut
          -tune zerolatency -s 1280x720 \ 
          -b:v 1400k -bufsize 1400k \ 
          -c:a libfdk_aac -b:a 128k \
          -f hls -hls_time 1 -hls_start_number_source datetime \ # maybe it'd be a good ideia to increment the hls time for 2
          -hls_allow_cache 0 -hls_flags delete_segments \
          -master_pl_name master_1.m3u8 ffmpeg_1_data.m3u8
```

**Comment by REELcoder** [comment]
OK, I see the point. The input stream is as it is sent by the TV stations. Your command examples include transcoding the video stream. For my application transcoding is not an option. I will check if the generated TS segments include an closed GOP. 

The question is still why for the same TV station it works in 9 of 10 cases without trouble and a few minutes later the player does not start...

**Comment by REELcoder** [comment]
I checked GOP using https://gist.github.com/use-sparingly/7041ee993adb5c911f90#file-iframe-probe-py

All TS segments from my example at https://hackersgarden.dyn.ch/media/master_1.m3u8 have closed GOP's and each one starts with an I-frame. Seems GOPs are fine here and ffmpeg is doing a good job...

What else can I check?

**Comment by leandromoreira** [comment]
Some of these are just [(wild) guesses I usually do](https://haasn.xyz/posts/2016-12-25-falsehoods-programmers-believe-about-%5Bvideo-stuff%5D.html) when I'm facing such a problem:

* did you double check to see if you are reliable for [hls apple's requirements](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices#2969492)?
* did you run [apple's  mediastreamvalidator](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html) or even another [hls-analyzer](https://github.com/epiclabs-io/hls-analyzer)?
* can you increase your hls_time? (like 2s for segment)
* does your gop is a multiplier of the chunk size? (hls_time, like for a 2s chunk you need to have either 1s or 2s gop)
* does your framerate is equal across all the renditions?
* does your audio framerate (frequency) is equal  across all the renditions?
* did you run a load test to see if any request takes longer than segment size? (causing it to be stale)
* are your PTS sync between chunks?

**Comment by REELcoder** [comment]
- some of the hls requirements are of course not met since I have just one rendition. Clappr seems to accept this most of the time...
- mediastreamvalidator output seems to be fine with some minor deviations:
```
mediastreamvalidator: Version 1.2 (373.7-180828)
[/media/master_1.m3u8] Started root playlist download
[ffmpeg_1_data.m3u8] Started media playlist download
[ffmpeg_1_data.m3u8] Received media playlist response
[ffmpeg_1_data.m3u8] SequenceNum: 20181216122741  Size: 1320136 bytes Duration: 0.9600 sec Bitrate: 1375141.6667
[ffmpeg_1_data.m3u8] SequenceNum: 20181216122742  Size: 1369016 bytes Duration: 0.9600 sec Bitrate: 1426058.3333
[ffmpeg_1_data.m3u8] SequenceNum: 20181216122743  Size: 1248508 bytes Duration: 0.9600 sec Bitrate: 1300529.1667
[ffmpeg_1_data.m3u8] SequenceNum: 20181216122744  Size: 1328220 bytes Duration: 0.9600 sec Bitrate: 1383562.5000
[ffmpeg_1_data.m3u8] SequenceNum: 20181216122745  Size: 1165788 bytes Duration: 0.8400 sec Bitrate: 1387842.8571
[ffmpeg_1_data.m3u8] All media files delivered and have end tag, stopping

--------------------------------------------------------------------------------
ffmpeg_1_data.m3u8
--------------------------------------------------------------------------------
Processed 5 out of 5 segments
Average segment duration: 0.936000
Total segment bitrates (all discontinuities): average: 10994.30 kb/s, max: 11408.47 kb/s
Playlist max bitrate: 433.400000 kb/s
Audio Group ID: AUDIO


Discontinuity: sequence: 0, parsed segment count: 5 of 5, duration: 4.680 sec, average: 10994.30 kb/s, max: 11408.47 kb/s
Track ID: 1
Video Codec: avc1
Video profile: High
Video level: 4
Video resolution: 1280x720
Video frame rate: 50.000
Track ID: 2
Audio Codec: AAC-LC
Audio sample rate: 48000 Hz
Audio channels: 2
Audio channel layout: Stereo (L R)

--------------------------------------------------------------------------------
MUST fix issues
--------------------------------------------------------------------------------

Error: Measured peak bitrate compared to master playlist declared value exceeds error tolerance
--> Detail:  Measured: 11408.47 kb/s, Master playlist: 433.40 kb/s, Error: 2532.32%
--> Source:  http://core/media/master_1.m3u8
--> Compare: ffmpeg_1_data.m3u8

--------------------------------------------------------------------------------
SHOULD fix issues
--------------------------------------------------------------------------------

Warning: #EXT-X-ALLOW-CACHE has been deprecated
--> Detail:  Line: #EXT-X-ALLOW-CACHE:NO
--> Source:  ffmpeg_1_data.m3u8

```
I manually fixed both issues. Still the same error on Safari and Firefox.

- hls_time 2 seconds does not help. There are 2 I-frames in the affected content, 1 s should be fine
- framerate is 50 fps and I have just one rendition as I do not transcode on the fly.
- no stale segments are found
- PTS are perfect.

I don't know...

**Comment by REELcoder** [comment]
Have you tried yourself to run my content in CDN?

In firefox I have the following in the console:
```
window.controllers/Controllers is deprecated. Do not use it for UA detection. ace.js:1:279195
Media resource blob:http://clappr.io/a88de112-eff0-3f4a-be32-9530d1341b5f could not be decoded. demo
Error: This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006) - virtual RefPtr<MP4Demuxer::InitPromise> mozilla::MP4Demuxer::Init(): Parse MP4 metadata failed html5_video.js:423:18 
```

In Safari:
```
InvalidStateError: The object is in an invalid state. 
  onSBUpdateEnd - hls.js:11930```

**Comment by leandromoreira** [comment]
It won't help but you should increase your GOP for 1s, since you fixed the bitrate issue, I'd say for you the next step would be test it [with another segmenter](https://github.com/lucasmundim/nginx-rtmp-dockerfile#how-to-use). We use hls.js/clappr for more  than 5 years with many 24 hours / 7 days streaming, this is seemgly something on the hls generation.

**Comment by REELcoder** [comment]
Sure. Maybe some other segmenter will work, as it is working with ffmpeg most of the time.

But the main question will not be answered: Why does it randomly not work. If we know what "something" is, I'm sure this would be fixed fast in ffmpeg. But if clappr fails without any useful error, for me this looks like an issue with clappr.

**Comment by leandromoreira** [comment]
I can tell you that I use ffmpeg for my tests and it works just fine! ;/

# open two terminal tabs

at the first run:

```
# if you're on macos
ffmpeg -re -pix_fmt uyvy422 -f avfoundation -i "0" -pix_fmt yuv420p -x264opts keyint=30:min-keyint=30:scenecut=-1 -tune zerolatency -s 1280x720 -b:v 1400k -bufsize 1400k -hls_start_number_source epoch -f hls stream.m3u8
```
at the second run (on the same folder):

```
# npm -g install http-server
http-server -a :: -p 8081 --cors -c-1
```

Now go to [clappr's demo page](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2xvY2FsaG9zdDo4MDgxL3N0cmVhbS5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK) and play it. It worked here =) joking aside, this command I gave you do not transcode audio to `aac` maybe that might be your problem, the audio no the video.

**Comment by REELcoder** [comment]
The last sentence was obviously the clue...

The TV stations send multiple audio streams. Usually the stereo stream is the the first in the list. In rare cases the 5.1 stream is the first and selected by the ffmpeg option -map 0:a:0. This seems not to work.  Have still to find out why.

As per Apple HLS requirement 2.3 one stereo AAC stream must be provided. This is violated in the affected example. Or ffmpeg does not properly transcode the 5.1 stream.
