### ISSUE TITLE
Send View Duration in Google Analytics

### ISSUE THREAD

**Issue by ChairmanMeow** [clappr/clappr#1744]
I am trying to send over Google Analytics view time - ie how long the video is played before the page is closed or video is paused. 

I am looking at the plugin here: https://github.com/clappr/clappr/blob/master/src/plugins/google_analytics/google_analytics.js

What would be the best way to add in this feature? 

Is it possible to get the current playtime from Clappr? Then I can send an event onunload to google analytics with the current playtime.

**Comment by kslimani** [comment]
To add a feature to an existing plugin, simple create a new one which extends the existing one and  add your logic.

To get current playtime (if i am not wrong) you can listen to `CONTAINER_TIMEUPDATE` event.

I made a [Google Analytics plugin](https://github.com/playmedia/clappr-ga-events-plugin) some time ago, i don't know if it still working with latest version (major refactor in last versions), but it could be a source of inspiration or a starting point.
