### ISSUE TITLE
Overlaps boxes in the video

### ISSUE THREAD

**Issue by daviduarte** [clappr/clappr#1745]
I have a serie of boxes (represented as euclidian coordinates) storaged in a plain text file in a server that I want to overlap the video in the Clappr player in specific moments. 

a - I'm using HLS with the segments starting in 0. What is the best way to sync the box with the frames? (Maybe storaging the box in a file with the same name of segment?)

b - There's a way to download this information with the HLS segments and overlap the video in real time using Clappr? For example, supose a video of a person walking that has a box that follows the person. So, in each frame, I want a draw the respective box over the person, suposing I have the coordinates of box in each frame.

OBS.: I can't edit the frames and re-encode the video due the high computational cost.

**Comment by afonsocdaniel** [comment]
Hi, @daviduarte, you can listen to HLS `Events.PLAYBACK_FRAGMENT_LOADED` but this would be imprecise, a better suggestion is to mark the video _timestamps(pts or possiton) for your boxes and list to _ CONTAINER_TIMEUPDATE event so you can show the boxes at the right time.
