### ISSUE TITLE
Custom Media Control Button in 0.3.0

### ISSUE THREAD

**Issue by thekendog** [clappr/clappr#1746]
**Browser**: Chrome Version 71.0.3578.98

**OS**: Windows 10

**Clappr Version**: 0.3.0

I was using the example on the built in plugins page (https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md) to add custom media control buttons.  It doesn't work with 0.3.0 and I see on the releases page it mentions that MediaControl has changed into a plugin itself.  Is there an example of how to insert custom media control buttons with the latest version?

**Comment by bikegriffith** [comment]
You need to register it as a core plugin now:

Don't do this anymore in v0.3,
```
let player = new Clappr.Player({
    source: "http://your.video/here.mp4",
    mediacontrol: { external: MyMediaControl }
  });
``

Instead, do this:
```
let player = new Clappr.Player({
    source: "http://your.video/here.mp4",
    plugins: { core: [MyMediaControl] }
  });
```

**Comment by thekendog** [comment]
Excellent. Worked like a charm.  Thanks!
