### ISSUE TITLE
onPlay/PLAYER_PLAY Not Firing When Loading New Source

### ISSUE THREAD

**Issue by thekendog** [clappr/clappr#1749]
**Browser**: Chrome Version 71.0.3578.98

**OS**: Windows 10

**Clappr Version**: 0.3.1

**Steps to reproduce**:

* Load initial media source
* Use player.load(newsource)
* The onPlay/PLAYER_PLAY event is not firing when playback of the new source begins.  This was working prior to 0.3.

Did you try to reproduce this issue at http://cdn.clappr.io/

Yes, here is a link...

http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBhdXRvUGxheTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogIGV2ZW50czogewoJCQlvblBsYXk6IGZ1bmN0aW9uKCkgewoJCQkJY29uc29sZS5sb2coJ3BsYXliYWNrIHN0YXJ0ZWQnKTsKCQkJfQoJCX0KfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cgp2YXIgbm9kZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoImJ1dHRvbiIpOwp2YXIgdGV4dG5vZGUgPSBkb2N1bWVudC5jcmVhdGVUZXh0Tm9kZSgiQ2xpY2sgTWUiKTsKbm9kZS5hcHBlbmRDaGlsZCh0ZXh0bm9kZSk7CmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJvdXRwdXQiKS5hcHBlbmRDaGlsZChub2RlKTsKCm5vZGUub25jbGljayA9IGZ1bmN0aW9uKCkgewogIHBsYXllci5sb2FkKCdodHRwOi8vd3NlMS5yZXNvcnRjYW1zLmNvbS9saXZlL2JlZWNoc3VtbWl0LnN0cmVhbS9wbGF5bGlzdC5tM3U4Jyk7Cn07Cg==

**Comment by kslimani** [comment]
I can also reproduce the issue with `configure()`. IT seems there is a regression in event binding when reloading a source. [Demo code](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBvcHRpb25zID0gewogIHNvdXJjZTogJ2h0dHA6Ly9jbGFwcHIuaW8vaGlnaGxpbmUubXA0JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgYXV0b1BsYXk6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MCwKICBldmVudHM6IHsKICAgIG9uUGxheTogZnVuY3Rpb24oKSB7CiAgICAgIGNvbnNvbGUubG9nKCdwbGF5YmFjayBzdGFydGVkJyk7CiAgICB9CiAgfSwKfTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcihvcHRpb25zKTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsKCnZhciBub2RlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiYnV0dG9uIik7CnZhciB0ZXh0bm9kZSA9IGRvY3VtZW50LmNyZWF0ZVRleHROb2RlKCJDbGljayBNZSIpOwpub2RlLmFwcGVuZENoaWxkKHRleHRub2RlKTsKZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoIm91dHB1dCIpLmFwcGVuZENoaWxkKG5vZGUpOwoKbm9kZS5vbmNsaWNrID0gZnVuY3Rpb24oKSB7CiAgb3B0aW9ucy5zb3VyY2UgPSAnaHR0cDovL3dzZTEucmVzb3J0Y2Ftcy5jb20vbGl2ZS9iZWVjaHN1bW1pdC5zdHJlYW0vcGxheWxpc3QubTN1OCc7CiAgcGxheWVyLmNvbmZpZ3VyZShvcHRpb25zKTsKfTsKCg==)

**Comment by kslimani** [comment]
@afonsocdaniel could you please re-open the issue, i confirm that calling player.configure() in 0.3.x seems to not "rebind" player events. (it is working in 0.2.100)

**Comment by kslimani** [comment]
This issue should be fixed in next Clappr release. (fixed by #1778).
