### ISSUE TITLE
Error Screen stay while its playing

### ISSUE THREAD

**Issue by esmondgh** [clappr/clappr#1751]
onError:  function() { setTimeout(() => player.play(), 5000) },

I'm using this ternary and for reason, the Error Screen stay while its playing.
Any solution?.

**Comment by kslimani** [comment]
Try something like :

```javascript
onError: function() {
  setTimeout(() => {
    // https://github.com/clappr/clappr/blob/master/src/components/player.js#L422
    player.load(player.options.source, player.options.mimeType, true)
  },
  5000
)}
```

**Comment by esmondgh** [comment]
Hi kslimani - It worked, but not the way I want it to behave.

Lets take the POSTER for example. When I click the big Play Button, the POSTER stays and the player start to load the stream. As soon as it start playing the POSTER disappears.

I want the same for the Error Screen. As soon as it start playing the Error Screen should disappear.
