### ISSUE TITLE
Override fullscreen function

### ISSUE THREAD

**Issue by edoudou** [clappr/clappr#1753]
As I said in the title, I want to know if it is possible to change the callback of the fullscreen button ? I would like it to fullscreen an other (parent) div. I have other things in that div that are also important to fullscreen.

**Comment by afonsocdaniel** [comment]
Hi, @edoudou nowadays we don't have support for that. A simple suggestion for now, you can extends the `MediaControl` component and overrides the method `toggleFullscreen`.

**Comment by edoudou** [comment]
Do you have a code sample of how to do it ?
I have tried different way, but I can't figure it out.

1st attempt :
```js
const MyCustomControls = Clappr.MediaControl.extend({
  toggleFullscreen : () => {
    console.log("Test");
  }
});
```
2nd attempt :
```js
const MyCustomControls extends Clappr.MediaControl {
  toggleFullscreen = () => {
    console.log("Test");
  }
}
```

I tried initializing the player like this : 
```js
this.player = new Clappr.Player({
      ...
      mediacontrol : {external : MyCustomControls},
      ...
    });
```

and like this : 
```js
this.player = new Clappr.Player({
      ...
      mediacontrol : MyCustomControls,
      ...
    });
```

No errors, but it does not override anything.

Thx in advance.
