### ISSUE TITLE
mediaControl events. What am I doing wrong?

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1754]
**Browser**: Chrome 71.0.3578.98

**OS**: Mac OS Mojave

**Clappr Version**: 0.3.1

Extending UICorePlugin.
```
bindEvents () {
    this.listenTo(this.core.mediaControl, Events.MEDIACONTROL_MOUSEMOVE_SEEKBAR, this.onMouseMove)
    this.listenTo(this.core.mediaControl, Events.MEDIACONTROL_RENDERED, this.onMediaControlRendered)
  }
```
I can use these events by adding listeners to the player object as follows:
```
player.listenTo(player.core.mediaControl, Clappr.Events.MEDIACONTROL_RENDERED, something)
```
But they do not work in my plugin with the latest version of the player, being added to bindEvents.
And they work if the player version is 0.2.93

**Comment by kslimani** [comment]
Clappr version 0.3.0 introduce breaking changes. One one these changes is that the mediacontrols is now a core plugin. A workaround is to get mediacontrol plugin instance and bind events :

See [this example](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAsCiAgLy8gU2ltcGxlIG1lZGlhY29udHJvbHMgZXZlbnQgdGVzdAogIGV2ZW50czogewogICAgb25SZWFkeTogZnVuY3Rpb24oKSB7CiAgICAgIHZhciBtID0gcGxheWVyLmNvcmUuZ2V0UGx1Z2luKCdtZWRpYV9jb250cm9sJyk7CiAgICAgIG0ubGlzdGVuVG8obSwgQ2xhcHByLkV2ZW50cy5NRURJQUNPTlRST0xfTU9VU0VNT1ZFX1NFRUtCQVIsIGZ1bmN0aW9uKGUpIHsKICAgICAgICBjb25zb2xlLmxvZygnTUVESUFDT05UUk9MX01PVVNFTU9WRV9TRUVLQkFSIScpOwogICAgICB9KTsKICAgICAgLy9jb25zb2xlLmxvZygncmVhZHkhJywgbSk7CiAgICB9CiAgfQp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK). (it may not the proper way to do it, maybe @joaopaulovieira could confirm ?)

See also the diff [between version 0.2.100 and 0.3.0](https://github.com/clappr/clappr/compare/0.2.100...0.3.0).

**Comment by sapolio** [comment]
But closed_captions for example is still using such a line in bindEvents method:
`this.listenTo(this.core.mediaControl, Events.MEDIACONTROL_RENDERED, this.render)`

**Comment by ewwink** [comment]
I think the changes is about `core.mediaControl.container` to `core.activeContainer` and not `core.mediaControl` but I quest the your problem is missing event `CORE_ACTIVE_CONTAINER_CHANGED`, you can try this simple plugin

```javascript
var testPlugin = Clappr.UICorePlugin.extend({
  name: 'test_plugin',
  bindEvents: function() {
    this.listenTo(this.core, Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED, this.reload);
    this.listenTo(this.core.mediaControl, Clappr.Events.MEDIACONTROL_MOUSEMOVE_SEEKBAR, this.onMouseMove);
  },
  unBindEvents: function() {
    this.stopListening(this.core, Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED);
    this.stopListening(this.core.mediaControl, Clappr.Events.MEDIACONTROL_MOUSEMOVE_SEEKBAR);
  },
  reload: function() {
    this.unBindEvents();
    this.bindEvents();
  },
  onMouseMove: function() {
    console.log('gg');
  },
});

var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [testPlugin]
});

player.attachTo(playerElement);
```

**Comment by sapolio** [comment]
As an experiment, I extended a core plugin, adding an insignificant change, and found that the handlers no longer work. All of them.
```
export default class dvr extends DVRControls {
  get something () { return 'something' }
}
```
As far as I understand, this should not be so. Correct me, please, if I am not right.

**Comment by sapolio** [comment]
@ewwink 
unfortunately it is not a matter of changing the container
correct handlers stop working when I extend the built-in core plugin

**Comment by sapolio** [comment]
so adding a container change handler really helps
Thanks to all!
