### ISSUE TITLE
ClappR is loading font with an invalid URL

### ISSUE THREAD

**Issue by blop** [clappr/clappr#1755]
**Browser**: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**OS**: 
macOS 10.14.2 (18C54)

**Clappr Version**: 0.3.1

**Steps to reproduce**: Setup player with custom baseUrl and play video

ClappR player is setup with baseUrl: 'r/clappr' (also tried 'r/clappr/')
ClappR is loading font with an invalid URL.
http://127.0.0.1:8080/r/clappr//38861cba61c66739c1452c3a71e39852.ttf

That URL is not "normalized" because it contains a double slash //.
The web server we use gives a 404 for that URL.

The correct URL should be http://127.0.0.1:8080/r/clappr/38861cba61c66739c1452c3a71e39852.ttf
(That URL is working properly and returns the TTF file)

Could you verify how the baseUrl is handled and how the ttf (and other external resources) URL are being build ?

Thank you!
Regards!

Olivier

**Comment by ash0080** [comment]
same

**Comment by blop** [comment]
🤔

**Comment by towerz** [comment]
Hi @blop, sorry for missing your issue.

Actually, the way Clappr sets the assets URLs is by appending `baseUrl` with the path of the asset, something like `<baseUrl>/38861cba61c66739c1452c3a71e39852.ttf`.

It doesn't add any extra slashes other than the one at the beginning of the path, so if you use `'r/clappr/'` you'll end up with an extra slash, but not when you use `'r/clappr'`. I just checked it running the dev server (`yarn start`) with the current dev branch.

**Comment by blop** [comment]
Yes, I now set the baseUrl without the trailing slash, it seems better indeed.

I suggest you remove automatically any trailing slash from the baseUrl too, so that it's more user friendly for others. Or at least mention this in the documentation.
