### ISSUE TITLE
CSS - poster not resized properly

### ISSUE THREAD

**Issue by blop** [clappr/clappr#1758]
Browser:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

OS:
macOS 10.14.2 (18C54)

Clappr Version: 0.3.1

When the poster is bigger than the actual player/window, it gets cut instead of resized.
I feel the follow CSS is better to get it resized properly : 

```
.player-poster[data-poster] {
  background-size: contain;
}
```

**Comment by blop** [comment]
🤔

**Comment by towerz** [comment]
Hi @blop, I think we should actually add a flag to choose whether or not to cut content or put some black padding in the poster itself.

We're in the process of extracting the plugins code from the main repository so we can work in the core and plugins separately. This will probably be added to the next version of the player.

If you just need to make a quick change for your use, you could just add the css you mentioned to the poster. If you want to make it a class, just access the plugin element (`el`) and add the class:

```javascript
player.getPlugin('poster').el.classList.add('<your class>')
```

**Comment by inside83** [comment]
so how to make the poster fit the player window?

**Comment by monteirocamis** [comment]
May I try this issue ?

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
