### ISSUE TITLE
React Scripts 2.1.3 + HLS : Not working

### ISSUE THREAD

**Issue by edoudou** [clappr/clappr#1759]
**Browser**: Chrome, Opera, Firefox
**OS**: Elementary OS
**Clappr Version**: 0.2.25

**Steps to reproduce**:

Try to use Clappr with a HLS stream with React Scripts 2.1.3, it fails.
Came back to React-Scripts 1.1.1, everything works fine.

**Comment by flavioribeiro** [comment]
do you have a snippet or JSFiddle you can share?
