### ISSUE TITLE
no plugins working with 0.3

### ISSUE THREAD

**Issue by perohu** [clappr/clappr#1760]
Hi,
After I upgraded to clappr 0.3, all of my used plugins are stopped working

I use these plugins:
https://github.com/bikegriffith/clappr-playback-rate-plugin
https://github.com/chriswiggins/clappr-capture-plugin

They worked with 0.2.x.
With 0.3 there is no js error in browser console, they are just not working without any error.

The rate plugin is on the official external plugins list as it is compatible with latest Clappr.
Am I doing something wrong?
Thank you!

**Comment by ewwink** [comment]
related to issue https://github.com/clappr/clappr/issues/1754 the plugin need to listen on `CORE_ACTIVE_CONTAINER_CHANGED` event

**Comment by perohu** [comment]
Thx.
So it means that the plugins are not compatible? I have to ask the maintainer of the plugins to make it compatible with Clappr 0.3.x?
Sorry i'm not a JS developer.

**Comment by ewwink** [comment]
yes its not compatible and you should ask the developer to fix it.
