### ISSUE TITLE
How to bypass nimblesession

### ISSUE THREAD

**Issue by ikniazi23** [clappr/clappr#1762]
I have  issue when i play this link on ip at which i capture it from an app it open successfully but when i try to access it from another ip it says Forbbiden.

Please tell me the solution.Thanks in advance.

https://cdn.jazztv.pk:8087/app/SaudiSunnah-141/live/141M/chunks.m3u8?nimblesessionid=38413230&wmsAuthSign=c2VydmVyX3RpbWU9Mi81LzIwMTkgOToxOTowMCBBTSZoYXNoX3ZhbHVlPUVmZWROdy9JQ2hSdkxoSkpMVFJnd0E9PSZ2YWxpZG1pbnV0ZXM9MQ==

**Comment by leandromoreira** [comment]
This seems to be not related to Clappr @ikniazi23

**Comment by towerz** [comment]
I'm closing this issue as invalid, since it's not directly related to Clappr and asks information regarding bypassing session protection of a given service.
