### ISSUE TITLE
Autoplay not working on Chrome PC... and playback not working on Samsung Browser

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1764]
Working on Firefox, Edge... but not working on Chrome PC
In addition, can't be played on Samsung Browser (Android). Most streams fail with Clappr. (Error code: html5_video:4)

http://www.rsbdylgy.lucusvirtual.es/dw.htm

Any idea?

**Comment by towerz** [comment]
@hijuuijj thanks for reporting. This appears to be related to Chrome (and Safari) blocking autoPlay with sound.

This one won't play (when attempting autoPlay with sound): [autoPlay with sound](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NhbmFsc3VyLW5ldy1saXZlLmhscy5hZGFwdGl2ZS5sZXZlbDMubmV0L2VncmVzcy9iaGFuZGxlci9jYW5hbHN1cl9saXZlL3J0dmFfbmV3L2NodW5rbGlzdF9iMjEyODAwMC5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIGF1dG9QbGF5OiB0cnVlLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAKfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cg==)

This one will play correctly (starting autoPlay with mute: true): [autoPlay without sound](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NhbmFsc3VyLW5ldy1saXZlLmhscy5hZGFwdGl2ZS5sZXZlbDMubmV0L2VncmVzcy9iaGFuZGxlci9jYW5hbHN1cl9saXZlL3J0dmFfbmV3L2NodW5rbGlzdF9iMjEyODAwMC5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIGF1dG9QbGF5OiB0cnVlLAogIG11dGU6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK)

Chrome has some documentation on how it whitelists domains based on its [Media Engagement Index (MEI)](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei).

**Comment by towerz** [comment]
The same logic applies to mobile browses as well. The only difference is that most browsers (especially Safari) on mobile devices will always block autoplay with audio.

We'll release a "click to unmute" plugin to help prevent these kind of issues, while warning the user that the video started autoplaying without sound, and an interaction is necessary to enable audio. If you're not able to wait for it, you can develop it yourself, perhaps based on what youtube does on mobile pages.
