### ISSUE TITLE
Acceleration on iframe

### ISSUE THREAD

**Issue by maza2k2** [clappr/clappr#1765]
Hi, all.
Mobile acceleration does not work on iframe.
Somebody know how to fix it ?

**Comment by kslimani** [comment]
@maza2k2 what do you mean by "mobile acceleration" ?

I suspect you mean the ability of switch to fullscreen, if this is the case, the reason may be your iframe element which is missing the `allowfullscreen` attribute.

Example :

```html
<iframe src="https://example.com/page.html" allowfullscreen></iframe>
```

**Comment by thiagopnts** [comment]
hi @maza2k2, you need to add `allow="gyroscope; accelerometer"` to your iframe tag(I dont know much about browser support tho). Another solution is to listen the events in the child page and postMessage that to the parent.

**Comment by maza2k2** [comment]
Sorry, its issue for https://github.com/thiagopnts/clappr-video360
