### ISSUE TITLE
Request: show position/duration in live-mode as well

### ISSUE THREAD

**Issue by platinum55** [clappr/clappr#1771]
hello,

when playing an m3u8 playlist which dont has an "#EXT-X-ENDLIST" entry yet(so live mode is on), the position and duration is not visible underneath the seekbar, instead there is the "Live" symbol.

Is there any way to display both, the Live-symbol AND position/duration in Live mode? I already searched but didn't find an option for this, also I dont have the skills to change the source myself, tried it for hours now :)

thank you beforehand

**Comment by platinum55** [comment]
noticed another thing right now: when the m3u8 playlist contains an "#EXT-X-START:TIME-OFFSET=0", the player jumps to the position which is fine, but the position is not visible here, and the bar-scrubber in live mode is always on the very right side on the seekbar.

its just confusing and makes user initial seeking difficult, because you dont know your current position in the stream

**Comment by thekendog** [comment]
If it's a live stream then it wouldn't have a duration, so how would the seekbar work?

**Comment by platinum55** [comment]
there is a duration calculated from the parts in the m3u8 file. When you seek back in time, while in Live mode, the player shows the correct duration(which updates every second and increases) and shows "Back to live" - so I think the position/duration is already there, I just need to know how to show/implement it :)

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
