### ISSUE TITLE
stream not working from ip address

### ISSUE THREAD

**Issue by arpanmaurya** [clappr/clappr#1772]
When i run hls stream using localhost it works fine but when i use local ip address instead of localhost it shows this(image) error and the server is datavideo nvs40 .
![image](https://user-images.githubusercontent.com/45965444/54024752-991e4400-41be-11e9-861a-d7365907b9f2.png)
thanks in advance

**Comment by kslimani** [comment]
You should check the output of javascript console it may give you some hints.
Also check if your http server is listening on your ip address (and not only localhost ip).

**Comment by arpanmaurya** [comment]
![image](https://user-images.githubusercontent.com/45965444/54027948-50b85380-41c9-11e9-83a1-7b00ac6c30e8.png)
on localhost
![image](https://user-images.githubusercontent.com/45965444/54027957-59a92500-41c9-11e9-9eed-5b0fb180780a.png)
on ip address 
console doesn't show anything.

**Comment by kslimani** [comment]
I see on your screenshot that Google Chrome is installed. Can you try with Chrome instead of Internet Explorer and check the javascript console ?

**Comment by arpanmaurya** [comment]
![image](https://user-images.githubusercontent.com/45965444/54029698-4e58f800-41cf-11e9-816c-1b3258de7dd2.png)
localhost
![image](https://user-images.githubusercontent.com/45965444/54029703-5749c980-41cf-11e9-9ccd-25acee3d81b0.png)
ip address 
in chrome cors has been an issue even tho i am doing it from live streaming server.

**Comment by kslimani** [comment]
you need to ensure that cors headers are sent by the server which deliver the hls stream. This is something you can configure in most streaming servers.

**Comment by arpanmaurya** [comment]
> you need to ensure that cors headers are sent by the server which deliver the hls stream. This is something you can configure in most streaming servers.

after checking i can't find the setting in my server is their alternate way if i can't do it from my live streaming server?

**Comment by kslimani** [comment]
What server are you using ?
check this website, it contains usefull informations about enabling CORS headers : [https://enable-cors.org/server.html](https://enable-cors.org/server.html)

**Comment by arpanmaurya** [comment]
it is coming directly from a live streaming server 
https://www.datavideo.com/us/product/NVS-40
this one.

**Comment by kslimani** [comment]
If you are using Apache, just modify your configuration following [this guide](https://enable-cors.org/server_apache.html).

**Comment by arpanmaurya** [comment]
don't close the issue i am facing another challenges so i can't test this right now plus i m finding why this error is happening 
![image](https://user-images.githubusercontent.com/45965444/54182375-5b276580-44c7-11e9-93ec-0a907af4a856.png)

**Comment by kslimani** [comment]
This issue is out of scope of Clappr player. Unfortunately can't help you on this one, i don't use Windows. Maybe you could get some help on XAMPP forum :  [https://community.apachefriends.org/f/viewforum.php?f=16&sid=256577674a52ab24f053ab03c24745d3](https://community.apachefriends.org/f/viewforum.php?f=16&sid=256577674a52ab24f053ab03c24745d3).

**Comment by arpanmaurya** [comment]
i solved the problem from by passing the cors header but it only works for IExplorer which is my case and i consider this issue is solved for me.
thank you.
