### ISSUE TITLE
Same code. 1st working 2nd not working

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1773]
Same code:

Working: http://www.rsbdylgy.lucusvirtual.es/clappr.php?v=http://dwgoed11hdvfh.cloudfront.net/c9/live.smil/index.m3u8

Not working: http://www.rsbdylgy.lucusvirtual.es/video.htm

Can someone clarify this?

**Comment by ewwink** [comment]
it used Referer protection but unfortunately it only check if in URL contain `dwgoed11hdvfh.cloudfront.net/` not what hostname referer is.  :)

**Comment by hijuuijj** [comment]
What do you mean with 'both are work'?
How I do need to change in the URL 2 code?

**Comment by ewwink** [comment]
```
http://www.rsbdylgy.lucusvirtual.es/video.htm?dwgoed11hdvfh.cloudfront.net/
```
