### ISSUE TITLE
Mobile devices - tap seekbar scrubber to move

### ISSUE THREAD

**Issue by DvorinM3** [clappr/clappr#1774]
**Browser**: Android Chrome: 72.0.3626.121, Android Firefox: 65.0.1  (I would say all Android devices)

**OS**: I haven't tested.
**Clappr Version**:  clappr@latest

In demo (cdn.clappr.io) it doesn't work as well.

-------------------------------------------

Hello everybody,
I am testing this excelent player to play HLS livestream in LAN. On Desktop everything works fine, but on mobile devices (Android, Chrome/Firefox) I can't tap and move the seekbar scrubber to seek in the history (and forward). Only works tapping on timeline, but it's not the best (precise) way to move just few seconds back during long livestream.

Is it possible to make it works somehow ?

Thank you for any ideas :)
Martin

**Comment by DvorinM3** [comment]
update: My friends successfully tested on iPhone Xr and Samsung Galaxy S8

**Comment by towerz** [comment]
Hi @DvorinM3 we're working in a new version of the Clappr UI with touch controls. Currently we only support basic touch interaction, but this will change soon.

**Comment by DvorinM3** [comment]
Great, thank you for info! :)

**Comment by inside83** [comment]
Any update on this?
I just figured out that on mobile you have to tap the seekbar to go back and forward.
Sliding the playhead doesn't work, making thumbnails on seekbar a lot less useful for mobile viewers 🙄

**Comment by abdulkadirakyildiz** [comment]
I'm looking forward to the scrubber moving feature on mobile. Can you provide information about versioning and development?

**Comment by abdulkadirakyildiz** [comment]
Until a better solution is like this. Mouse events coming to the device can be found as touch and both can be supported in that way.
https://gist.github.com/Alex1990/d462cb9f90ed2b1a9390
