### ISSUE TITLE
Vast and Clappr video Reactjs

### ISSUE THREAD

**Issue by TueTinhTV** [clappr/clappr#1775]
Hello everyone.
Good night for you.
I have a project's Nextjs and try run video with VAST in this.
I used Videojs, Clappr but i cann't solve. I had search demo same project, and received a lit of example but not needed for used.
Can help me or give me some idea!!!

**Comment by leandromoreira** [comment]
You might find some help at the [closed issues related to ads (specifically vast)](https://github.com/clappr/clappr/issues?q=is%3Aissue+vast+is%3Aclosed)

**Comment by TueTinhTV** [comment]
> You might find some help at the [closed issues related to ads (specifically vast)](https://github.com/clappr/clappr/issues?q=is%3Aissue+vast+is%3Aclosed)

Happiness when see reply for me.
:D "Hello World. 01001000 01100101 01101100 01101100 01101111 00100000 01110111 01101111 01110010 01101100 01100100  "
I try and  research your suggestions. Thank for your presents.

**Comment by TueTinhTV** [comment]
Pleaz!
Help for clappr vast in project Nextjs.
I'm junior .Net.
