### ISSUE TITLE
Change history of clappr project? Overview of new functions and bug fixes?

### ISSUE THREAD

**Issue by sstonemen** [clappr/clappr#1776]
I search for a list of new feature, bug fixes and so on for each new clappr version.

For example: where can I find the changes from 0.3.2 to 0.3.3 without read all code changes? Is there an overview?

**Comment by matheusrufca** [comment]
https://github.com/clappr/clappr/releases

**Comment by towerz** [comment]
Hi @sstonemen. Usually we add the changes to the GitHub releases page (as @matheusrufca replied), but we've had a problem with the latest release and it wasn't added. Thanks for pointing this out.

I'll update the releases as soon as possible.

**Comment by sstonemen** [comment]
Thank you!
