### ISSUE TITLE
how to use plugins in vue?Thumbnails on seekbar,360 videos ,except flv.js show not define or not mounted.

### ISSUE THREAD

**Issue by FairyWorld** [clappr/clappr#1777]
how to use plugins in vue.js+webpack?(ALL)Thumbnails on seekbar,360 videos ,except flv.js show not define or not mounted.

**Comment by FairyWorld** [comment]
![QQ截图20190326130004](https://user-images.githubusercontent.com/32956212/54972615-5c788800-4fc7-11e9-82ad-a668e22c6ff5.png)

**Comment by thiagopnts** [comment]
Hi, this looks more like an issue on how you're bundling everything. Do you have a sample project with the setup we can check?
