### ISSUE TITLE
HLS Levels bitrate should return interger

### ISSUE THREAD

**Issue by ewwink** [clappr/clappr#1780]
**Clappr Version**: 0.3.3

I have m3u8 playlist and it `level.bitrate` is like 
```
#EXT-X-STREAM-INF:BANDWIDTH=571104,...
#EXT-X-STREAM-INF:BANDWIDTH=279221,...
```
which is not return `int` if divided by `1000`, should we use `parseInt(level.bitrate/1000)` or `level.bitrate.slice(0, -3)` for better view?

https://github.com/clappr/clappr/blob/004e69133c0b2cf5d6e061050c82ec943b6f8f85/src/playbacks/hls/hls.js#L431

![clappr-bitrate](https://user-images.githubusercontent.com/760764/55678235-34bae580-5920-11e9-8c65-9908a4a63a8f.jpg)

**Comment by kslimani** [comment]
The [clappr-level-selector plugin](https://github.com/clappr/clappr-level-selector-plugin) has a `labelCallback` option which allow you to pass a function to apply custom label formatting.

**Comment by ewwink** [comment]
yes I know, but I think it better to fix it in the Clappr core.

**Comment by leandromoreira** [comment]
and give it a little extra space and when it bigger than 1000 use Mbps

**Comment by kslimani** [comment]
Would not it be better that the playback level "display label formatting logic" be (and be enhanced) in the level selector plugin ?
_(So any playback which properly implements the level feature can benefit from these improvements)._

**Comment by leandromoreira** [comment]
Let's see what @jhonatangomes and @towerz think about it.

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
