### ISSUE TITLE
Spanish language correct translation

### ISSUE THREAD

**Issue by matigumma** [clappr/clappr#1788]
actual:
es : {live:"vivo",back_to_live:"volver en vivo",disabled:"Discapacitado",playback_not_supported:"Su navegador no soporta la reproducción de un video. Por favor, trate de usar un navegador diferente."},

new:
live:"vivo",
back_to_live:"volver en vivo",
disabled:"No disponible", or disabled:"Deshabilitado",
**default_error_title: "No se puede reproducir este video.",**
playback_not_supported:"Su navegador no soporta la reproducción del video. Por favor, trate de usar un navegador diferente."

**Comment by leandromoreira** [comment]
I think `No disponible` is better and about the message for `default_error_title` I think yours is great.

**Comment by leandromoreira** [comment]
keep it open
