### ISSUE TITLE
Automatically reload/load live stream without refreshing page

### ISSUE THREAD

**Issue by ibowman15** [clappr/clappr#1789]
Is there a way to get clappr to keep checking for an hls stream without the client refreshing the page?

Maybe a retry mechanism? (Not even really sure what that is)

Sorry, I'm very very new to code...trying to work through this.

Error Code: Cannot load https://parkland.phxcdn.com:8443/live/parklandhs/index.m3u8HTTP response code:404 Not Found
37.031 | A network error occured

`<script type='text/javascript' src='https://cdn.jsdelivr.net/clappr/latest/clappr.min.js'></script> 
<center> 
   <div id='player'></div> 
</center> 
<script> 
   var player = new Clappr.Player({ 
       source: 'https://parkland.phxcdn.com:8443/live/parklandhs/index.m3u8', 
       poster: 'https://static.wixstatic.com/media/e51675_5bcab88baf9b4114a74a1dffca28e22a~mv2.png', 
       mute: false, 
       width: 640, 
       height: 360, 
       autoPlay: true, 
       parentId: '#player' 
    }); 
</script>
`

**Comment by kslimani** [comment]
Take a look at [Player Error](https://github.com/clappr/clappr/blob/dev/doc/PLAYER_ERRORS.md) handling documentation.

**Comment by ibowman15** [comment]
Still a bit confused by this. Is there an easy fix where I can just enter a line of code to have this work? Again, very very very new to all of this...

**Comment by kslimani** [comment]
Try this code on Clappr [demo page](clappr.io/demo/) : it retry the stream each 10 seconds on error :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://parkland.phxcdn.com:8443/live/parklandhs/index.m3u8HTTP',
  disableErrorScreen: true, // Disable the internal error screen plugin
  height: 360,
  width: 640,
  events: {
    onError: function(e) {
      setTimeout(function() { player.configure(player.options); }, 10000);
    }
  }
});

player.attachTo(playerElement);
```

**Comment by ibowman15** [comment]
Would this replace my entire video player code or would I add this to my existing code?

**Comment by kslimani** [comment]
The only "parts" you may have interest are `disableErrorScreen` and `events` player configuration options.
