### ISSUE TITLE
Measure total internet usage in video.

### ISSUE THREAD

**Issue by breim** [clappr/clappr#1791]
Is it possible to measure the total internet usage? using HLS?

Ex: I need to know the total of fragments downloaded in a video and how much it represents in MB. So I can control the traffic that each video has been receiving.

Thanks.

____

PT:

É possível medir o total de internet utilizado? usando o HLS?

Ex: preciso saber o total de fragmentos baixados em um vídeo e o quanto isso representa em MB. Assim consigo controlar o trafego que cada vídeo vem recebendo.

Obrigado

**Comment by breim** [comment]
I tried NerdStats and Clappr Stats plugin, but cant get this information.

**Comment by leandromoreira** [comment]
maybe you can use https://github.com/clappr/clappr-stats and make the sum by yourself: `bitrateMostUsed * watchHistory.last` something similar to that

**Comment by breim** [comment]
Buddy,

i did some tests, in my case **metrics.extra.bitrateWeightedMean * metrics.extra.buffersize)/10000000000** almost perfect to retrieve total bandwidth used  in **MB**.

Thx for help o/
