### ISSUE TITLE
Autoplay Policy Changes on Chrome

### ISSUE THREAD

**Issue by danishnazir** [clappr/clappr#1792]
I ran into an issue where videos stopped playing on start, reading this article a video must be muted to autoplay. 
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Is this a known issue, or do I have a setting wrong?

**Comment by kslimani** [comment]
It is a known issue, many browsers have changed their autoplay policy. For example, latest Firefox has added a feature to control which website can autoplay video or not, etc...)
