### ISSUE TITLE
source

### ISSUE THREAD

**Issue by TAli2017** [clappr/clappr#1794]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)

**Clappr Version**: 0.2.25

**Steps to reproduce**:

* first step
* then second step
* I was expecting X but instead it shows Y

Did you try to reproduce this issue at http://cdn.clappr.io/

ps: you can attach images, logs or whatever you think might be helpful.
ps: feel free to clean this if your issue is different.

**Comment by leandromoreira** [comment]
Hi @TAli2017 I think you just forgot to type your issue
