### ISSUE TITLE
How to change the quality of video mp4 in clappr?

### ISSUE THREAD

**Issue by kaylos** [clappr/clappr#1795]
How to make a video quality change?

Example, i have simple mp4 video with different quality.

link quality 480  : http://example.com/name_videos_480.mp4
AND 
link quality 720  : http://example.com/name_videos_720.mp4

How i can add two link in clappr and to make menu in Mediacontrol for change quality video?

**Comment by leandromoreira** [comment]
I personally think it's easy and better for you to move towards into converting these videos into dash or hls. https://blog.infireal.com/2018/04/mpeg-dash-with-only-ffmpeg/
