### ISSUE TITLE
Feature Request: Closed captions (Subtitles) settings

### ISSUE THREAD

**Issue by areeb111** [clappr/clappr#1796]
Hi, 
Please consider this as a plugin or an add-on to be implemented in next versions, Because it's very useful.

**Closed captions (subtitle) settings** that will include the following options to be changed during playback:
- Font family (Default system fonts which are available in MacOS and Windows and their alternatives) - With support of user input font-family (If already installed).
- Font size
- Responsive font size (Based on screen size and full-screen mode).
- Font color
- Text shadow
- Text outline
- Text opacity
- Text vertical / horizontal alignment (Margin Top, Bottom, Right and Left).
- Background color / opacity for text container.

Thank you

**Comment by flavioribeiro** [comment]
refs https://github.com/video-dev/hls.js/issues/1324
