### ISSUE TITLE
Unable to play stream

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1797]
I'm not able to play this stream with Clappr:
http://rtmonenews.secureswiftcontent.com/Origin02/ngrp:RTM2/chunklist_b3696000.m3u8

However this site can play it:
http://yoursports.stream/live?v=rtmsports

Where is the trick?

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues

**Comment by hijuuijj** [comment]
Does not work from CDN, hls.js page or flashls page.

Also I have have enabled "Cors on Apache" (https://enable-cors.org/server_apache.html)
Installing: sudo a2enmod headers & adding to .htaccess: Header set Access-Control-Allow-Origin "*"

Same error code: hls:networkError_manifestLoadError

**Comment by leandromoreira** [comment]
![image](https://user-images.githubusercontent.com/55913/58632782-0c66bc00-82bd-11e9-896e-e1af0ed795a5.png)
For me it's returning `403`!

**Comment by hijuuijj** [comment]
I know Leandro... my question is how http://yoursports.stream/live?v=rtmsports can play it with Clappr.

**Comment by leandromoreira** [comment]
@hijuuijj because they know how to deal with the needed authorization and authentication for the stream.
