### ISSUE TITLE
Create a definitive spinner

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#180]
Our current spinner is breaking player's design. We need a better one.

**Comment by irongomme** [comment]
What do you expect as a "definitive spinner" ?

**Comment by thiagopnts** [comment]
I think we will stick with the current one. Any thoughts @flavioribeiro @towerz?

**Comment by towerz** [comment]
@thiagopnts +1 on sticking with the current spinner. I think implementing the proposed spinner will be overly complicated and could have limited benefit.

@irongomme The proposed spinner was an animated Clappr logo, with two animation phases: one for opening/closing the logo, and other for making a spin animation.

**Comment by flavioribeiro** [comment]
+1 for the current one, we can safely close this. :+1:
