### ISSUE TITLE
live mode can't be detected with player.core.getPlaybackType()

### ISSUE THREAD

**Issue by hsa1280** [clappr/clappr#1803]
Hello, I used player.core.getPlaybackType() to detect live mode or VOD mode, the function always returns 'vod' for either live stream mode or VOD mode. Seems like this functions can't detect the right playing mode, please take a look. 

If there is a better way to detect live mode, please let me know.

Thanks.

**Comment by kslimani** [comment]
The correct playback type may not be immediatly available.

A possible way could be to listen to `CONTAINER_SETTINGSUPDATE` container event.

For example, try the following code in [Clappr demo page](http://clappr.io/demo/) :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  height: 360,
  width: 640,
  events: {
    onReady: function() {
      this.core.activeContainer.listenTo(
        this.core.activeContainer,
        Clappr.Events.CONTAINER_SETTINGSUPDATE,
        function() {
          console.log('playback_type', this.getPlaybackType());
        }
      );
    },
  },
});

player.attachTo(playerElement);
```

**Comment by hsa1280** [comment]
Thanks for the reply, please close this issue.
