### ISSUE TITLE
Please explain what the "mediator" is used for"

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1806]
I don't fully understand the events in clappr.
In which cases do I need the "mediator"?

**Comment by leandromoreira** [comment]
Clappr is an extensible media, its [architecture was designed](https://github.com/clappr/clappr/wiki/Architecture) around components and events.

I don't think you need to use the `mediator` even when [you're creating an plugin](https://github.com/clappr/clappr/wiki/Our-first-plugin), you usually relly on `bindEvents` and `listenTo` to communicate/listen to other components.

```
        bindEvents: function() {
          this.listenTo(this.container, Clappr.Events.CONTAINER_PAUSE, this.show);
          this.listenTo(this.container, Clappr.Events.CONTAINER_PLAY, this.hide);
        }
```

However the most common usage of clappr is through the [API events](https://github.com/clappr/clappr/blob/dev/doc/API_EVENTS.md) where you can listen to the main events or when by using external plugins, like [metrics](https://github.com/clappr/clappr-stats#usage) for instance and even build another plugins, like [nerd stat](https://github.com/lucasrodcosta/clappr-nerd-stats#clappr-nerd-stats), based on existent plugins.

@clappr/core thoughts?

**Comment by flavioribeiro** [comment]
AFAIK we created the Mediator to build a bridge for communication some components back in the flash days. Reference: https://github.com/video-dev/clappr-rtmp-plugin/blob/745a9d8ab56c2245a40995cedb33aad3e186d1a9/src/RTMP.as#L389-L395

**Comment by towerz** [comment]
@flavioribeiro is right. The Mediator was created for bridging Flash with other components but has been misused for some other purposes. We'll remove it in the near future so I'd recommend avoiding using it for any purpose.
