### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by andrepolischuk** [clappr/clappr#1810]
I work on some project that uses clappr and typescript under the hood. So I typed most of clappr modules locally. And I would like to add these ts definions to clappr repo. What do you think about this?

**Comment by towerz** [comment]
Hi @andrepolischuk. Sure, feel free to open a PR to add these ts definitions.
Thanks!

**Comment by juliovedovatto** [comment]
@andrepolischuk Did you had chance to share these incredible typings? :D

**Comment by banagale** [comment]
@towerz Hey, would you please consider posting your type file? This would be a useful addition to this project.  Related request: #1899
