### ISSUE TITLE
Request - Support for SMPTE-TT subtitles

### ISSUE THREAD

**Issue by kumarashu123** [clappr/clappr#1812]
Is support for this SMPTE-TT format in clappr?
If supports, How we can integrated?

**Comment by leandromoreira** [comment]
https://github.com/clappr/dash-shaka-playback/issues/62

**Comment by leandromoreira** [comment]
keep it open

**Comment by palemieux** [comment]
[imscJS](https://github.com/w3c/imsc) supports SMPTE-TT to HTML fragment conversion.

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
