### ISSUE TITLE
Video element recycling enabled by default

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr#1813]
While browsing code about default option initialization, i found that `recycleVideo` playback option is initialized to `true` by default, since [this commit](https://github.com/clappr/clappr/commit/9d2d307ff7c1c2a90f5d5afa9bd041c6eef2ac6c#diff-200a325d8607daea7e681ef9d1ab1426).

In the past, i set this option to `false` by default for backward compatibility reason, but also because i found bugs with some browsers like Firefox (desktop). I recommend to enable this option only with mobile/tablet devices.

@towerz @leandromoreira @joaopaulovieira : could you confirm this option should still be enabled by default ? _(if yes, i will make a PR to update documentation)_.

**Comment by towerz** [comment]
@kslimani yes, it should be enabled by default. It helps in solving many issues regarding autoplay permissions.
