### ISSUE TITLE
problem with safari and change currentTime

### ISSUE THREAD

**Issue by amiznikov** [clappr/clappr#1817]
**Browser**: Safari 12.1.1

**OS**: Mac os mojave

**Clappr Version**: latest

**Steps to reproduce**:

* https://78.ru/images/uploads/1558877101988.mp4 play file
* seek to unload position
* page hang

https://bit.ly/2J6nLmI

**Comment by towerz** [comment]
Hi @amiznikov, this seems to be an issue related to how Safari handles the video buffering and playback using MP4 directly.

Your MP4 file is approximately 1.5 GB, and Safari struggles to keep the buffer filled and the playback running smoothly. After seeking for a while it hangs, even without any Clappr code. You can check this behavior [here](https://codepen.io/towerz/pen/XLaEPZ). There's only the `<video>` tag on the code, with no JS running, and the playback hangs after a while when seeking.

**Comment by towerz** [comment]
I'd suggest creating a DASH or HLS stream instead of accessing the MP4 directly. This will allow for better buffer handling and smoother playback for larger videos.
