### ISSUE TITLE
How to remove click to pause

### ISSUE THREAD

**Issue by ctaity** [clappr/clappr#1818]
Hi. I need in mobile disable click to pause. Like youtube on mobile.

First click show controls. 
Later i show a pause button on center like youtube. Because on live streams on mobile phones is better to transition to full scrren i thinlñk and dont pause the streaming. Thanks

**Comment by kslimani** [comment]
The player instance explose a [`getPlugin` ](http://clappr.github.io/classes/Player.html#method_getPlugin) method.

For example you can test the following code on [Clappr demo page](http://clappr.io/demo/) :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  width: 640,
  height: 360,
  events: {
    onReady: function() {
      if (Clappr.Browser.isMobile) {
        var plugin = this.getPlugin('click_to_pause');
        plugin && plugin.disable();
      }
    },
  },
});

player.attachTo(playerElement);
```

**Comment by hijuuijj** [comment]
Much better. I hate the click/pause in DVR streams.

`                 events: {
                     onReady: function() {
                         var plugin = this.getPlugin('click_to_pause');
                         plugin && plugin.disable();
                     },
                 },
`

**Comment by ctaity** [comment]
Perfect. Thanks
