### ISSUE TITLE
User-agent

### ISSUE THREAD

**Issue by venkymadhu** [clappr/clappr#1819]
I need a help on how to add user-agent in clappr source code

**Comment by kslimani** [comment]
What do you mean by "add user-agent" ?

Clappr library contains a [Browser](https://github.com/clappr/clappr/blob/dev/src/components/browser/browser.js#L185) component (undocumented afaik) exposed as `Clappr.Browser` which (but not only) parse browser user agent.

Go to [demo page](http://clappr.io/demo/), open javascript console, type `console.log(Clappr.Browser)`  and take a look at the result.

**Comment by venkymadhu** [comment]
i mean i want to change user-agent in clappr player.By default iam getting 
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
i want to know is there any way to change this user agent in clappr source code

**Comment by kslimani** [comment]
I see currently no way to inject a custom user agent in Clappr player.
The Clappr Browser component uses the [Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator).userAgent property from browser which is read only.

**Comment by leandromoreira** [comment]
I might not getting the whole picture but Clappr just read the user agent, your browses set it up, so from the point of the view of the player (the html client) you can't set (write) the user agent.

**Comment by phillipseamore** [comment]
All requests are done by the users browser and you can't change the UA for the requests.
