### ISSUE TITLE
M3u8 with nimblesessionid 

### ISSUE THREAD

**Issue by alaasml3** [clappr/clappr#1820]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)

**Clappr Version**: 0.2.25

**Steps to reproduce**:

* first step
* then second step
* I was expecting X but instead it shows Y

Did you try to reproduce this issue at http://cdn.clappr.io/ no 

ps: you can attach images, logs or whatever you think might be helpful.
ps: feel free to clean this if your issue is different.

Dear support 

I have stream below keek changes and blocking after awhile (nimblessionid 

http://vstream3.hadara.ps:8081/RayaHD1_web/web/playlist.m3u8?nimblesessionid=183330769

How i can keep watching without (nimblessionid )

**Comment by leandromoreira** [comment]
this seems not related to clappr at all
