### ISSUE TITLE
A working hls link not playing in clappr

### ISSUE THREAD

**Issue by AmrElbalshy** [clappr/clappr#1826]
Hi all,
This hls link: http://31.220.0.134:8081/live/spstreamskymv/playlist.m3u8
is working on a site using clappr but when i try to play it with the player it's not working for me.

Can anyone help me please in configuring clappr to play it? 

Note: Website URL - http://bit.ly/2Z3BGk8

**Comment by towerz** [comment]
@AmrElbalshy I couldn't play the live stream link you posted, even in the original website URL. 

But usually, there are some protections in place to prevent playing the streams in other domains, like CORS headers, which informs the browser to prevent unauthorized access.

**Comment by d0n0t** [comment]
can we something about it? for CORS
