### ISSUE TITLE
VOD playback resume and Playlist

### ISSUE THREAD

**Issue by myplanetsolutionx** [clappr/clappr#1836]
Hi, please can anybody give a clear example of clappr player vod playback resume and how to create playlist ...

have search all the internet for this but no success... please just help out

**Comment by kslimani** [comment]
There is a [Clappr playlist plugin](https://github.com/towerz/clappr-playlist-plugin) but i don't know if it is still working with latest version.

**Comment by myplanetsolutionx** [comment]
@kslimani  have tried it before its not working..

> 
> 
> There is a [Clappr playlist plugin](https://github.com/towerz/clappr-playlist-plugin) but i don't know if it is still working with latest version.

Have tried it, but its not working....

**Comment by durgeshksh1** [comment]
Hi,
I managed to create a playlist with css and js:

HTML
`<div class="vid-player">
        <div  class="player" id="player"></div>

        <div class="playlist">
            <ol id="playlist">
                <li class="activVid"><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Aquarium</a></li>
                <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Fantastic</a></li>
                <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Merlot</a></li>
                <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Serenity</a></li>
                <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> running</a></li>        
            </ol>
        </div>
    </div>`

CSS

`* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
html{
    max-width: 1200px;
    box-sizing: border-box;
    background: #eee;
    margin: 0 auto;
}

body  {
    background-color: #809ee9;
    min-height: 100vh;
}

.vid-player{
    width: 90%;
    /* max-height: 300px; */
    margin: 10px auto;
    display:flex;
    flex-wrap: wrap;
    box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 13px 10px rgba(0,0,0,0.21);
}
.player{
    flex-grow: 4;
    min-width: 300px;
    min-height: 300px;
    height: 0;
}

.playlist{
    flex-grow: 2;
    padding: 0 0 0 10px;
    background: #818181;
    min-width: 300px;
    min-height: 300px;
    height: 0;
    overflow-y: scroll;
}

.playlist ol li {
    width: 100%;
    height: 70px;
    /* background:#00a8ff; */
    display:inline-block;
    display:flex;
    margin-top: 10px;
    cursor: pointer;
    padding: 5px;
}

.playlist ol li a {
    display: flex;
    text-decoration: none;
    color: rgb(0, 0, 0);
    align-items: center;
    width: 100%;
}

.playlist ol li img {
    padding: 0 10px 0 0;
    height: 60px;
}

.activVid{
    background: #00a8ff;
}

.inactivVid{
    background: #202020;
}`

JS

` 
var player = new Clappr.Player({
            parentId: "#player",
            source: "path/to/video/file",
            width: "100%",
            height: "100%",             
            plugins: [LevelSelector],
            levelSelectorConfig: {
                title: 'Quality',
                labels: {
                    2: '720p', // 500kbps
                    1: '540p', // 240kbps
                    0: '360p', // 120kbps
                },
            },
        });
var playlist = document.querySelectorAll('#playlist a');
            // console.log(playlist[0]);
			// Add onclick event to playlist items
            for(var i=0; i<playlist.length; i++){
                playlist[i].onclick = changeConfig;
            }

            function changeConfig(event){
                event.preventDefault();
                // Change the background colur of active video.
                var playlistItems = document.querySelectorAll('#playlist li')
                for(var i=0; i<playlistItems.length; i++){
					playlistItems[i].classList.remove("activVid");
					playlistItems[i].classList.add("inactivVid");
                }
				var parent= event.target.parentNode;
				parent.classList.remove("inactivVid");
                parent.classList.add("activVid");

                // Change the video source
                var src = this.getAttribute('att') + '.m3u8';
                // console.log(src);
                player.configure({
                    source: src,
					poster: '',
                });

                player.play();
            }		`

You can play with css to customize it.
![playlist](https://user-images.githubusercontent.com/26226832/62522561-9009cf80-b84f-11e9-84b6-4e703a0c2a86.png)

Hope this helps

**Comment by myplanetsolutionx** [comment]
> 
> 
> Hi,
> I managed to create a playlist with css and js:
> 
> HTML
> 
> ```
>     <div class="playlist">
>         <ol id="playlist">
>             <li class="activVid"><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Aquarium</a></li>
>             <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Fantastic</a></li>
>             <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Merlot</a></li>
>             <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> Serenity</a></li>
>             <li class=""><a href="#" att='path/to/video/file'><img src="path/to/image/file" alt=""> running</a></li>        
>         </ol>
>     </div>
> </div>
> ```
> 
> CSS
> 
> `* {
> margin: 0;
> padding: 0;
> box-sizing: border-box;
> }
> html{
> max-width: 1200px;
> box-sizing: border-box;
> background: #eee;
> margin: 0 auto;
> }
> 
> body {
> background-color: #809ee9;
> min-height: 100vh;
> }
> 
> .vid-player{
> width: 90%;
> /* max-height: 300px; */
> margin: 10px auto;
> display:flex;
> flex-wrap: wrap;
> box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 13px 10px rgba(0,0,0,0.21);
> }
> .player{
> flex-grow: 4;
> min-width: 300px;
> min-height: 300px;
> height: 0;
> }
> 
> .playlist{
> flex-grow: 2;
> padding: 0 0 0 10px;
> background: #818181;
> min-width: 300px;
> min-height: 300px;
> height: 0;
> overflow-y: scroll;
> }
> 
> .playlist ol li {
> width: 100%;
> height: 70px;
> /* background:#00a8ff; */
> display:inline-block;
> display:flex;
> margin-top: 10px;
> cursor: pointer;
> padding: 5px;
> }
> 
> .playlist ol li a {
> display: flex;
> text-decoration: none;
> color: rgb(0, 0, 0);
> align-items: center;
> width: 100%;
> }
> 
> .playlist ol li img {
> padding: 0 10px 0 0;
> height: 60px;
> }
> 
> .activVid{
> background: #00a8ff;
> }
> 
> .inactivVid{
> background: #202020;
> }`
> 
> JS
> 
> `
> var player = new Clappr.Player({
> parentId: "#player",
> source: "path/to/video/file",
> width: "100%",
> height: "100%",
> plugins: [LevelSelector],
> levelSelectorConfig: {
> title: 'Quality',
> labels: {
> 2: '720p', // 500kbps
> 1: '540p', // 240kbps
> 0: '360p', // 120kbps
> },
> },
> });
> var playlist = document.querySelectorAll('#playlist a');
> // console.log(playlist[0]);
> // Add onclick event to playlist items
> for(var i=0; i<playlist.length; i++){
> playlist[i].onclick = changeConfig;
> }
> 
> ```
>         function changeConfig(event){
>             event.preventDefault();
>             // Change the background colur of active video.
>             var playlistItems = document.querySelectorAll('#playlist li')
>             for(var i=0; i<playlistItems.length; i++){
> 				playlistItems[i].classList.remove("activVid");
> 				playlistItems[i].classList.add("inactivVid");
>             }
> 			var parent= event.target.parentNode;
> 			parent.classList.remove("inactivVid");
>             parent.classList.add("activVid");
> 
>             // Change the video source
>             var src = this.getAttribute('att') + '.m3u8';
>             // console.log(src);
>             player.configure({
>                 source: src,
> 				poster: '',
>             });
> 
>             player.play();
>         }		`
> ```
> 
> You can play with css to customize it.
> ![playlist](https://user-images.githubusercontent.com/26226832/62522561-9009cf80-b84f-11e9-84b6-4e703a0c2a86.png)
> 
> Hope this helps

Hi thanks this works for me, i was able to adapt it to fit my requirement... much grateful bro.
