### ISSUE TITLE
How to run this rtmp url with clappr

### ISSUE THREAD

**Issue by AmrElbalshy** [clappr/clappr#1837]
Hi there,
I would like to run this stream using clappr, could someone please write a working code for that?

rtmp://$OPT:rtmp-raw=rtmp://80.82.65.59:443/liverepeater playpath=13 live=1 pageUrl=http://popeoftheplayers.pw/ token=#atd%#$ZH timeout=15

**Comment by leandromoreira** [comment]
https://github.com/video-dev/clappr-rtmp-plugin#clappr-rtmp-plugin

**Comment by AmrElbalshy** [comment]
Thanks, is this rtmp url format is right?

"rtmp://$OPT:rtmp-raw=rtmp://80.82.65.59:443/liverepeater playpath=13 live=1 pageUrl=http://popeoftheplayers.pw/ token=#atd%#$ZH timeout=15"

**Comment by leandromoreira** [comment]
@AmrElbalshy I don't think so but take a look at https://www.wowza.com/docs/how-to-format-adobe-flash-rtmp-urls
