### ISSUE TITLE
ProgressBar not worked when I init multiple instances of Clappr.

### ISSUE THREAD

**Issue by wufeng87** [clappr/clappr#1839]
**Browser**: Chrome latest

**OS**:  Mac OS 10.13.6

**Clappr Version**: 0.3.7

**Steps to reproduce**:

I inited three instance of Clappr. But some of them couldn't change progress by the progress bar, when I drag the ProgressBar, it restart the mp3/mp4 again.

![image](https://user-images.githubusercontent.com/1686808/62283231-a98fcd80-b483-11e9-8562-47b391eaf60a.png)

**Comment by wufeng87** [comment]
```
this['player'+id] = new window.Clappr.Player({
            source: source, parentId: _id,
            height: type == 'mp3' ? 60 : 360,
            hideMediaControl: type == 'mp3' ? false : true,
            // plugins: {
            //     'core': [window.Clappr.MediaControl, window['clappr-playback-rate-plugin'].default]
            // }
        });
```

**Comment by leandromoreira** [comment]
I think you mush create n parent id as well `parentId: _id`

**Comment by towerz** [comment]
@wufeng87 try running (this sample)[http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXJzID0gW10KZm9yICh2YXIgaSA9IDA7IGkgPCAzOyArK2kpIHsKICB2YXIgcGxheWVyID0gbmV3IENsYXBwci5QbGF5ZXIoewogICAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogICAgcG9zdGVyOiAnaHR0cDovL2NsYXBwci5pby9wb3N0ZXIucG5nJywKICAgIG11dGU6IHRydWUsCiAgICBoZWlnaHQ6IDM2MCwKICAgIHdpZHRoOiA2NDAKICB9KTsKICBwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7CiAgcGxheWVycy5wdXNoKHBsYXllcik7Cn0KCgo=]. It adds 3 players to the same parent element and the seekbar is working properly.
