### ISSUE TITLE
Question about dynamic loop flag change

### ISSUE THREAD

**Issue by oFilipMalinowski** [clappr/clappr#1840]
Is it possible to change `loop` state during playback?

**Comment by towerz** [comment]
@oFilipMalinowski it should be. Actually, the playback component can be updated dynamically, but I noticed a strange behavior when calling `player.configure({ loop: false })`. 

Apparently, the way it removes the `loop` state is not having any effect. We'll need to fix this.

**Comment by oFilipMalinowski** [comment]
@towerz Yeah, that's what I observed using player.configure() which made me think that there is some other way to use it.

**Comment by kslimani** [comment]
For HTML5 video playback component, it may be because the loop property is set [only in constructor](https://github.com/clappr/clappr/blob/dev/src/playbacks/html5_video/html5_video.js#L126) ?

**Comment by kslimani** [comment]
A simple fix could be to add this code in html5 video playback :

```javascript
  configure(options) {
    super.configure(options)
    this.el.loop = !!options.loop
  }
```

@towerz what do you think ?

**Comment by towerz** [comment]
@kslimani yeah, the playback is missing the configure implementation. It would be better to check whether there are other properties that need to be reconfigured dynamically, for example controls, etc.

**Comment by kslimani** [comment]
@towerz do you suggest to move the "loop" handling logic to `media_control` plugin (like for mute/volume) and add method(s) to playback component to handle loop boolean state ?

**Comment by towerz** [comment]
@kslimani no, actually the `controls` property of the HTML5Video element. All properties that can be changed dynamically could be configured by calling the playback's `configure` method

**Comment by towerz** [comment]
@kslimani I think we can discuss this in a separate issue. Since configure was not implemented, we can move on with this initial implementation, and add more properties that could be configured dynamically (`controls`, remote playback/AirPlay support, etc).
