### ISSUE TITLE
Question: something like onCanPlay event

### ISSUE THREAD

**Issue by oFilipMalinowski** [clappr/clappr#1842]
So my question is if there is any event that provides information about similar state to what we get in Html5 Video player oncanplay Event?
https://www.w3schools.com/jsref/event_oncanplay.asp

In general I would need to listen to an event where I can execute .play() on Clappr player object.

I was trying my luck with executing .load() and then executing this kind of code:
```
if (!this.playerObject.isReady) {
  this.playerObject.core.getCurrentPlayback().on(Clappr.Events.PLAYBACK_READY, () => {
    this.events.onCanPlay();
  });
} else {
  this.events.onCanPlay();
}
```
Sadly I did not succeed calling .play() this way for example when loading HLS content.

It is necessary for us to be able to perform such step by step actions since the architecture of our DLNA solution requires it.
Thanks.

**Comment by kslimani** [comment]
Clappr player has a "ready" event.

For example, try this code on [Clappr demo page](http://clappr.io/demo/) :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  height: 360,
  width: 640,
  events: {
    onReady: function() {
      console.log('ready !');
    },
  },
});

player.attachTo(playerElement);
```

Take also a look at [api events documentation](https://github.com/clappr/clappr/blob/dev/doc/API_EVENTS.md).

**Comment by oFilipMalinowski** [comment]
@kslimani In piece of the code of my previous comment you can see that I'm listening to this event

**Comment by oFilipMalinowski** [comment]
Seems to be working fine! Thanks for help
