### ISSUE TITLE
PLAYER_ENDED event and animated GIFs

### ISSUE THREAD

**Issue by aFilipMalinowski** [clappr/clappr#1843]
From my observations when playing animated GIF, **PLAYER_ENDED** is always fired immediately at the beginning of playback, despite gif can be animated the next 10-20 seconds. This is undesired behaviour, isn't it?

**Comment by luanraithz** [comment]
This seems to happen because [the load event in the html_img playback](https://github.com/clappr/clappr/blob/dev/src/playbacks/html_img/html_img.js#L40).
I don't think that gifs should be handled exactly the same way images are.
