### ISSUE TITLE
Trouble using "Automatically Seek To Point Specified in URL"

### ISSUE THREAD

**Issue by aFilipMalinowski** [clappr/clappr#1847]
**Browser**: Chrome 76.0.3809.100 (Official Build) (64-bit)

**OS**: Ubuntu 18.04.3

**Clappr Version**: 0.2.25

Hi all. I am having some trouble and hope you'll be able to help me.
Auto seek to time position specified in resource URL does not work.
Tested on HLS video streams.

Code snippet of how I load the video:
```
  load(data) {
    let source = this.source;

    if (data && data.time) {
      source = source + "?t=" + data.time;
    }

    //NOTE this.playerObject == new Clappr.Player()
    this.playerObject.consent().configure({
      source: source,
      mimeType: this.mimeType,
      poster: this.poster,
      autoPlay: this.autoplayState,
      chromeless: this.chromeless,
      autoSeekFromUrl: true,
    });

    return null;
  }
```

Is there something I'm doing wrong?
Thanks.

**Comment by kslimani** [comment]
AFAIK the [autoSeekFromUrl](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#automatically-seek-to-point-specified-in-url) feature read the time value in seconds from the browser page url, not from the stream source url.

**Comment by aFilipMalinowski** [comment]
I see it now. Thanks.

Any hopes to support it as a part of source url?
Honestly it did not come up to my mind that it could be anywhere else than in source url. For example YouTube embedded player handles it as part of url.

**Comment by towerz** [comment]
@aFilipMalinowski I think we could support this as part of the source URL as well. AFAIK there's one catch in this matter. If the server that provides the content also handles the query string, we could end up with a double seek in that case. 

We should be aware of that case and document the feature properly if we go in that direction.

**Comment by aFilipMalinowski** [comment]
In this case maybe you could add another built in plugin where start point could be specified?

We are currently developing Angular based web application where it is troublesome to include **t** in query string since query string gets changed quite often. It is possible for us to manage it in it but it will be a bit nasty solution.

**Comment by kslimani** [comment]
I think for adding such feature, it would be better to create a new optional playback configuration parameter. No point adding a query parameter in source url if intent is to start media playback at custom position. _(if you can dynamically add a parameter to source url, you can dynamically set a playback parameter)_.
