### ISSUE TITLE
player.getCurrentTime() not updating when seeking

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1848]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Chrome 76.0.3809.132

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Windows 10

**Clappr Version**: 0.2.25
Last one from cdn

**Steps to reproduce**:
If you play a 2k video, and seek it:

player.listenTo(player, Clappr.Events.PLAYER_PLAY, OnPlayerStarted);
function OnPlayerStarted() {
console.log(player.getCurrentTime());
}

you will see that when the video start to play again the current time is not the right one.
It take some time (I don't know how much) to update the current time

**Comment by towerz** [comment]
@DanieleSuppo73 you probably aren't using the right URL to get the latest version from CDN. The URL you should be using to load the latest version is this one: https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

Clappr is currently on version `0.3.8`. Version 0.2.25 is way too old (from December 2015). The current version works as expected. You can test the behavior [here](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwoKcGxheWVyLmxpc3RlblRvKHBsYXllciwgQ2xhcHByLkV2ZW50cy5QTEFZRVJfUExBWSwgT25QbGF5ZXJTdGFydGVkKTsKZnVuY3Rpb24gT25QbGF5ZXJTdGFydGVkKCkgewpjb25zb2xlLmxvZyhwbGF5ZXIuZ2V0Q3VycmVudFRpbWUoKSk7Cn0K)

**Comment by DanieleSuppo73** [comment]
You are right it seem to work
