### ISSUE TITLE
Error playing 2 video stream (.m3u8) 

### ISSUE THREAD

**Issue by jeferbr** [clappr/clappr#1850]
Error playing 2 video stream (.m3u8) or more on the same page html.

Error displayed within minutes of live:  **Error code: hls:networkError_levelLoadError**

Note: The error is also displayed when it is on 2 different pages at the same time, it seems that limits by connection.

**Browser:**Google Chrome V 76.0.3809.132 

My code:
`
<div id="player"></div>
<div id="player1"></div>

var player = new Clappr.Player({
        source: 'https://........./video1.m3u8',
        plugins: [ChromecastPlugin],
        parentId: '#player',
        poster: 'https://.......cover.jpg',
        chromecast: {
          appId: '9DFB77C0',
          contentType: 'video/mp4',
          media: {
            type: ChromecastPlugin.Movie,
            title: 'A',
            subtitle: 'A'
          }
        }
      });

 var player1 = new Clappr.Player({
        source: 'https://........./video2.m3u8',
        plugins: [ChromecastPlugin],
        parentId: '#player1', 
		poster: 'https://....../cover2.jpg',		  		  
        chromecast: {
          appId: '9DFB77C0',
          contentType: 'video/mp4',
          media: {
            type: ChromecastPlugin.Movie,
            title: 'B',
            subtitle: 'B'
          }
        }
      });`

**Comment by towerz** [comment]
@jeferbr could you provide more info on what kind of streams you're trying to load? Perhaps sharing a test URL so we can check why the error occurs.

AFAIK the level load error is related to the hls.js playback being unable to load a given level and failing to fallback to a redundant one. This could mean your ABR is misconfigured somehow, or some of your variants are not available or accessible.
