### ISSUE TITLE
Question: DIV visible in Fullscreen

### ISSUE THREAD

**Issue by lenusch** [clappr/clappr#1851]
Sorry, can't find any Solution for my Problem. 
And i don't know if here's the right Place to ask for but i have following Problem: 

i have created a DIV which shows up if i hit a button in the media control bar. But this wont work on Fullscreen. My DIV in right hand corner (i.e. some sort of Playlist) wont pop up. 
Do i have to initiate this with Javascript? Does anyone has some hint / example for me? 

I tested this with Chrome / Safari. 
I also tried to insert my DIV into the Wrapper of the Player, but it seems that Code gets cleaned after entering fullscreen. Any Advice would be awesome. 

Thank you in Advance

**Comment by towerz** [comment]
@lenusch if you are adding this element outside of the Player core element, it won't be displayed in fullscreen, since only the Player (and its children) would be visible in the mode.
