### ISSUE TITLE
Usage with react portals

### ISSUE THREAD

**Issue by ChristopheBougere** [clappr/clappr#1853]
I am trying to integrate Clappr in a React project. I have been able to add some react components as custom controls following [this post](https://medium.com/@bikegriffith/using-clappr-with-reactjs-14a338e3451f), but they can't access to their context, which is a real issue.

I think [React Portals](https://reactjs.org/docs/portals.html) could be the solution to this.

Has anyone experienced React Portals with Clappr? Any feedback on this method?

**Comment by towerz** [comment]
@ChristopheBougere actually, there has been some work with React. Some of my colleagues created a React Portal plugin to use with Clappr: https://github.com/tacnoman/clappr-create-portal. It's a little bit undocumented, but it's quite straightforward to use.

It's being actually used on some of Globo.com products, including some plugins at the sports, news products, as well as their main video product ([Globoplay](https://globoplay.globo.com)).

**Comment by ChristopheBougere** [comment]
Hi @towerz, thanks for sharing!
Would you mind giving some tips on how to use it?
Let say I define my player like this:
```
new Clappr.Player({
    source: 'https://path.to/my.m3u8',
    autoPlay: true,
    parent: this.playerRef.current,
    plugins: [
      ClapprCreatePortal,
    ],
});
```
And that I have various React components I want to add as overlays.
Then how can I add my React components to the `ClapprCreatePortal`?

Also, there is [a reference](https://github.com/tacnoman/clappr-create-portal/blob/master/src/index.js#L28) to `globo_media_control`. Can we get rid of it without breaking anything?

**Comment by flavioribeiro** [comment]
maybe another reference to check https://github.com/satyakeerthikotte/HLS-Video-Player

**Comment by ChristopheBougere** [comment]
Thanks @flavioribeiro, definitely a good resource on usage with react, but I don't see anything specific for my case (adding custom overlays components inside the player).
Am I missing something?

**Comment by ChristopheBougere** [comment]
I finally managed to use React Portals to add custom controls to the player thanks to https://github.com/tacnoman/clappr-create-portal
It might be interesting to add this link to the documentation.
Thanks for your help!
