### ISSUE TITLE
Blocked by CORS policy No access control allow origin issue

### ISSUE THREAD

**Issue by xinglong717** [clappr/clappr#1856]
I am going to open browns.m3u8 file on my html page.
But I can't see the video, it displays the error like this.

Access to XMLHttpRequest at 'http://tenishakalera.s3-accelerate.amazonaws.com/browns.m3u8' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I need your help asap.
Thanks.

**Comment by leandromoreira** [comment]
@xinglong717 your server response didn't add the required [`cors` headers](https://github.com/clappr/clappr/blob/dev/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues)

> Cross-Origin Resource Sharing (CORS) is a mechanism that uses additional HTTP headers to tell browsers to give a web application running at one origin, access to selected resources from a different origin. A web application executes a cross-origin HTTP request when it requests a resource that has a different origin (domain, protocol, or port) from its own. Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

You can check that in the [demo page](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL3RlbmlzaGFrYWxlcmEuczMtYWNjZWxlcmF0ZS5hbWF6b25hd3MuY29tL2Jyb3ducy5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK).

**Comment by leandromoreira** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/55913/65420873-98ef3a00-ddd8-11e9-886d-2e5071f86c1b.png">

**Comment by xinglong717** [comment]
Thanks for your response, leandromoreira.

![image](https://user-images.githubusercontent.com/32957829/65609409-0eceed80-dff3-11e9-982f-7a9a9df10135.png)

This is my file.

How can I add header??

**Comment by leandromoreira** [comment]
The header should be placed in the streaming server not at your page. There is a site full of [resources mentoring about how to add these headers to some servers like nginx and apache](https://enable-cors.org/)
