### ISSUE TITLE
externalTracks (.vtt) don't show up

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1857]
Hello I'm trying to show .vtt captions, but I can't make them work.
1 - I'm using the last clappr version from CDN
2 - I've added "AddType text/vtt .vtt" in .htaccess file of my Apache server (without it I got a warning about mime type, so the player at least "know" that it should read the track).
3 - I've disabled "Video360" plugin to understand if this was the issue

When I play the file I don't get any error in Chrome console, but the .vtt captions do not show

This is my simple code:
` videoPlayer.player = new Clappr.Player({
                source: url,
                // plugins: {container: [Video360],},
                width: "100%",
                height: "100%",
                parentId: container,
                poster: poster,
                playback: {
                    externalTracks: [ 
                        {lang: 'en', label: 'English', src: 'data/Venezia_LidoPellestrina/caption.vtt', kind: 'subtitles'},
                        {lang: 'it', label: 'Italian', src: 'data/Venezia_LidoPellestrina/caption.vtt'} // 'kind' default value is 'subtitles'
                    ]
                }
            });`

And this is my .vtt file (just an example)

WEBVTT - This is an example

1
00:00:00:00 --> 00:00:10:00 align:middle line:90%
These are caption frames
from a sample file

2
00:00:15:00 --> 00:00:20:00 align:middle line:90%
Another caption

**Comment by towerz** [comment]
@DanieleSuppo73 your code is right, that's the way you should be using the external tracks. But your .vtt file is in the wrong format. The timestamps aren't in the correct format. I tried testing your code and ended up with empty text tracks when using your example file.

The correct format would be something like this:
```webvtt
WEBVTT

1
00:00:00.000 --> 00:00:10.000 align:middle line:90%
These are caption frames
from a sample file

2
00:00:15.000 --> 00:00:20.000 align:middle line:90%
Another caption
``` 

You can see it working [here](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogIHBsYXliYWNrOiB7CiAgICBleHRlcm5hbFRyYWNrczogWwogICAgICB7IAogICAgICAgIGxhbmc6ICdlbicsCiAgICAgICAgbGFiZWw6ICdFbmdsaXNoJywKICAgICAgICBzcmM6ICdodHRwOi8vY2xhcHByLmlvL3Rlc3QudnR0JwogICAgICB9CiAgICBdCiAgfQp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK).

**Comment by DanieleSuppo73** [comment]
Many thanks @towerz for your reply
now the external track is working, but not with "Video360" plugin enabled.
Is there a way, or maybe another Clappr 360 plugin, to make .vtt work with 360 degrees video?

**Comment by DanieleSuppo73** [comment]
I see, many thanks
