### ISSUE TITLE
External tracks don't show up with Video360 plugin

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1858]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Chrome  76.0.3809.132

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Windows 10 pro 1809

**Clappr Version**: 0.3.8
Last version from CDN

**Steps to reproduce**:
`videoPlayer.player = new Clappr.Player({
                source: url,
                plugins: {container: [Video360],},
                width: "100%",
                height: "100%",
                parentId: container,
                poster: poster,
                playback: {
                    externalTracks: [
                        {lang: 'en', label: 'English', src: '.../caption.vtt', kind: 'subtitles'},
                        {lang: 'it', label: 'Italian', src: '.../caption.vtt'} // 'kind' default value is 'subtitles'
                    ]
                }
            });
`
Press play,
caption don't show up

Did you try to reproduce this issue at http://cdn.clappr.io/
No, I don't know how to enable Video360 plugin on http://cdn.clappr.io/

**Comment by andrefilimono** [comment]
Hi, it seems to be a problem in Video360 plugin, since it hides a "video" tag displaying the provided VTTs and unprocessed video and shows another html element (canvas) rendering 360 video instead of it.

So, if you open dev tools, remove the canvas and make the video tag visible, then you'll get captions displayed.

**Comment by leandromoreira** [comment]
It might be better to open an issue there. cc @thiagopnts

**Comment by towerz** [comment]
@DanieleSuppo73 please open the issue in the [plugin repository](https://github.com/thiagopnts/clappr-video360). Since it's not related to this project, it will only add clutter here.

**Comment by DanieleSuppo73** [comment]
Many thanks to all, I'll open this issue
