### ISSUE TITLE
Introduce PLAYBACK_STOP_INTENT

### ISSUE THREAD

**Issue by paluh** [clappr/clappr#1861]
Thanks for creating Clappr!

**Is your feature request related to a problem? Please describe.**
I want to be able to know what is the user current playback intent based on clappr events.

I'm trying to monitor our player playback and restore it when connection is back or our stream is up again.
I'm able to track easily when a user started playback by handling `PLAYBACK_PLAY_INTENT` event. But when there is an playback error (like network connection problem etc.) player sends me multiple events and one of them is `PLAYBACK_STOP`. As far as I understand I'm not able to distinguish this event from users real "playback stop intent" (when she/he hits the stop button etc.).

**Describe the solution you'd like**
I want to propose addition of symmetrical event `PLAYBACK_STOP_INTENT` so it would be possible to track not only the state of a player but also an intention of the user.

**Comment by paluh** [comment]
Wow! Thanks for quick response @towerz. I'm really glad that you like the idea. I'm not sure if I can help with implementation because I'm not fluent with internals of your great project but... for sure I can test `PLAYBACK_STOP_INTENT` and incorporate these changes into my `paluh/purescript-clappr` bindings!

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
