### ISSUE TITLE
Player invisble - Heigth problem

### ISSUE THREAD

**Issue by KingHorse2015** [clappr/clappr#1864]
**Browser**: Firefox 70.0b11

**OS**: Windows Server 2019 Standard

**Clappr Version**: 0.3.8

**Steps to reproduce**:
* Set heigth to 100% and width to 100%
* Look at webbrowser.
* I expect a full height of the window player. But instead the player is a height of 0px.

Did you try to reproduce this issue at http://cdn.clappr.io/
No, I didn't
![noheigth](https://user-images.githubusercontent.com/15171668/66145162-84961300-e60a-11e9-8478-f82bde205774.PNG)

ps: you can attach images, logs or whatever you think might be helpful.
ps: feel free to clean this if your issue is different.

**Comment by kslimani** [comment]
@KingHorse2015 it is not a bug. When you set percentage for width and heigth, the player instance adjust his size to the "container" element. (in your case, the container may have a 0px height value).

Take a look at [this example](https://github.com/clappr/clappr/issues/1639#issuecomment-395414240), _(not the same issue, but it give an idea of how it works)_.

**Comment by KingHorse2015** [comment]
This code has solved the problem.
`body, html {
	height: 100%;
	
}
.player {
	width: 100%;
	height: 100%;
}`
