### ISSUE TITLE
Safari iOS 10 - Clappr not working

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1867]
I think it's a bug:
I've created 2 div with flex-box.
I'd like to show the video in the 1st div, and something else in the 2nd div.
The problem is that when I click on play button the video goes full-screen, and the standard iOS  player is used in place of Clappr. 

**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Safari 10 on iPhone 6 plus

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
iOS10

**Clappr Version**: 0.3.8
Last one

**Steps to reproduce**:

<div class="page" style="display: flex">
    <div id="panel1" style="flex: 1">
        <div id="player"></div>       
    </div>
    <div id="panel2"  style="flex: 1">
        <div id="other"></div>
    </div>
</div>

<script>
    var player = new Clappr.Player({
        source: "https://player.vimeo.com/external/356158599.m3u8?s=4cc2e833252c2f761dad31c7a825828d68146a78",
        width: "100%",
        height: "100%",
        parentId: 'player',
    });
</script>

**Comment by kslimani** [comment]
@DanieleSuppo73 this is not a bug, but an expected behaviour on iOS.

Set the `playInline` [playback option](https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md#playback-configuration) to true to avoid this behaviour on recent iOS devices.

For example :

```javascript
var player = new Clappr.Player({
  source: 'https://player.vimeo.com/external/356158599.m3u8?s=4cc2e833252c2f761dad31c7a825828d68146a78',
  width: "100%",
  height: "100%",
  parentId: 'player',
  playback: {
    playInline: true,
  },
});
```

**Comment by DanieleSuppo73** [comment]
Many thanks!
