### ISSUE TITLE
bug: mediacontrols show up loading source using configure()

### ISSUE THREAD

**Issue by kslimani** [clappr/clappr#1868]
**Browser**: Chrome, Firefox (should be any)

**OS**: Linux (should be any)

**Clappr Version**: 0.3.8 (latest)

**Steps to reproduce**:

Go to [Clappr demo page](http://clappr.io/demo/), and open Javascript console.

Click on play icon to run the player, then load source using configure by typing this in console :

```javascript
player.configure({source:'http://clappr.io/highline.mp4'})
```

The player reload the source, but the media controls are visible (seems enabled internally) and also showup when player not started yet by mouse overring player.

Note: the `player.load('http://clappr.io/highline.mp4')` is working as intended. (ie: does not show mediacontrol until player is started).

**Comment by leandromoreira** [comment]
I confirmed this at `MacOS 10.14.6` in `Firefox 69.0.2 (64-bits)`

**Comment by kslimani** [comment]
I think i have a proposition to fix this issue. I will send a PR.
