### ISSUE TITLE
Clappr don't work on latest android browsers for blogspot

### ISSUE THREAD

**Issue by radiopalacz** [clappr/clappr#1870]
Please help me with clappr dont work on my android chrome and samsung browsers.
Here's my blogger site with videos:
https://radiopalacz.blogspot.com/2019/10/blade-runner-filmy-uniwersum.html
Everything working fine on PC (any browser) but on my android phone it even dont show the player on chrome and samsung browsers.

**Comment by kslimani** [comment]
I am not sure if this will fix your issue, but try to assign a unique variable for each player instance.

For example instead of :

```javascript
// player 01
var player = new Clappr.Player(){ /* [...] */ };

// player 02
var player = new Clappr.Player(){ /* [...] */ };
```

Try creating unique variables :

```javascript
// player 01
var player1 = new Clappr.Player(){ /* [...] */ };

// player 02
var player2 = new Clappr.Player(){ /* [...] */ };
```

**Comment by radiopalacz** [comment]
I've change variables but it still dont work. Maybe I must wait for next releases of clappr player. I dont have any idea how to fix it.

**Comment by kslimani** [comment]
It seems that Clappr is not defined when your blog page is displayed using a mobile device layout.

This is not a Clappr issue : the player is not included in page when loading mobile layout. (ie: the clappr player `<script>` is missing).

I have no knowledge with blogspot, but there should be a way to also include the script while loading mobile version of your page.

**Comment by radiopalacz** [comment]
That suggestion really help me. I 've changed layout theme for mobile phones. First to "non standard" and then totally turn it off and set to "for computers". And script is loaded properly for both settings. Thank You a lot. 👍
