### ISSUE TITLE
Use older version instead of latest

### ISSUE THREAD

**Issue by cviewsupport** [clappr/clappr#1872]
**What do you want to do with Clappr?**
I want to be able to use one specific version of clappr that we know works well for us.

Right now my page just uses the latest version of clappr like this:
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>

**What have you tried so far?**

I tried including clappr like this but when I did I lost auto play on iOS devices. (the video still worked but I had to click play manually.  When I switch back to using "latest" then auto play works again).

<script type="text/javascript" src="/js/clappr.min.js"></script>-->

The only file I had in my /js directory was the clappr.min.js file.
Do I need to include ALL the other source files as well?

Thanks!

**Comment by kslimani** [comment]
@cviewsupport check the jsDelivr page : [https://www.jsdelivr.com/package/npm/clappr](https://www.jsdelivr.com/package/npm/clappr)

For example; to load Clappr 0.2.100 : 

```html
 <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr@0.2.100/dist/clappr.min.js"></script> 
```

**Comment by cviewsupport** [comment]
Thanks.

If I wanted to host that on my own server would I just need the min.js file?

Or would I need to download the whole source?

 

The idea was to host on our server so as to not include anything external.

 

Thanks for your time!

 

Thanks,

Kenny Johnson

ChildView.com

866-343-3656

**Comment by kslimani** [comment]
If you want to host Clappr player on your server, you may need to host the ["dist"](https://github.com/clappr/clappr/tree/master/dist) folder content.

Also set the  `baseUrl` option if required. (see also [this issue](https://github.com/clappr/clappr/issues/1755#issuecomment-485983301)).
