### ISSUE TITLE
[Multiple instances] Play one, Stop the rests automatically

### ISSUE THREAD

**Issue by duythongle** [clappr/clappr#1873]
**What do you want to do with Clappr?**
How can I stop other instances on play of a particular player?

**What have you tried so far?**
Setup 2 instances of clappr here [https://codepen.io/thomas_le/pen/YzzQLWp](https://codepen.io/thomas_le/pen/YzzQLWp) then have no idea how to achieve this behavior.

**Comment by kslimani** [comment]
A solution may be to use player [event api](https://github.com/clappr/clappr/blob/dev/doc/API_EVENTS.md)  to bind `onPlay` event to call `stop()` method on other player instances.

**Comment by duythongle** [comment]
Thanks @kslimani. I've just found out a way https://codepen.io/thomas_le/pen/YzzQLWp

**Comment by leandromoreira** [comment]
@duythongle it seems that's also stoping all players when you seek

**Comment by duythongle** [comment]
@leandromoreira, thanks for pointing that out. Big problem in VOD playback. Do you have any idea to avoid that?

Luckily, all my contents are live stream for now. I can disable seeking.

**Comment by Hrishikesh-K** [comment]
No solution for this yet? :(
