### ISSUE TITLE
Question: Use <video> tag instead parent-<div>

### ISSUE THREAD

**Issue by doublex** [clappr/clappr#1874]
We have a `<video>`-tag, e.g.: `<video><source...></video>`.
Is there a chance to create a Clappr-Instance using this `<video>`-tag?

**Comment by kslimani** [comment]
By default, Clappr player internally create is own Video element. _(according source type)_.

If you need to play a source providing your own Video element, this can be achieved using a custom Playback plugin.

**Comment by doublex** [comment]
Thanks!
