### ISSUE TITLE
How to avoid iOS go fullscreen on live stream

### ISSUE THREAD

**Issue by zedlen** [clappr/clappr#1875]
**What do you want to do with Clappr?**
I want to play live stream without going into fullscreen, in any device when enter on the page the stream play normally into the spcified div except from ios devices, which when enter on the page the stream open on full screen, and when exit of full screen the stream pauses, it only play when it's into fullscreen
**What have you tried so far?**
I have tried this options in the constructor
```

			playback: {
				playInline: true,
			},
```

but still the same, I havent tried any other optios cause I have not found another one, hope you can help.

Running on iOS 13
Using Clappr 0.3.11

**Comment by kslimani** [comment]
Setting the `playInline` to true like you described should play the video inline in browser _(if the device handle it)_  :

```javascript
var player = new Clappr.Player({
  source: "https://your.video/here.mp4",
  playback: {
    playInline: true,
  },
});
```

Unfortunately, i don't have any iOS 13 device. Maybe someone else can confirm this issue ?

**Comment by kslimani** [comment]
@zedlen : i tested the `playInline` playback option on [Clappr demo page](http://clappr.io/demo/) with an iPhone 7 with iOS version 13.1 (17A844) and it was working _(ie: video does not open automatically in fullscreen)_.
