### ISSUE TITLE
How can i do this ? Buffering related question

### ISSUE THREAD

**Issue by h4rpreet** [clappr/clappr#1882]
I want it to buffer like youtube, Only little buffering ahead of your viewing position and if viewer pauses the video buffering should stop as well. I want to do this to save bandwidth. Can this be done ? If yes, how to do it. 

**What have you tried so far?**

**Comment by kslimani** [comment]
If your source is an HLS media, then you may be able to tune using [configuration parameters](https://github.com/video-dev/hls.js/blob/master/docs/API.md#fine-tuning).
_(Clappr player is internally using [hls.js](https://github.com/video-dev/hls.js/))_

HLS.JS playback configuration can be set using the [`hlsjsConfig`](https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md#hls-configuration) option :

```javascript
var player = new Clappr.Player({
  source: "https://your.video/playlist.m3u8",
  playback: {
    hlsjsConfig: {
      // hls.js specific options
    }
  },
  // [...]
});
```

**Comment by h4rpreet** [comment]
Yes, i am using HLS. As far as i understand  with HLS it loads only some chunks, not whole video

But do you know how can i make it stop loading loading wheen video is paused.

**Comment by kslimani** [comment]
I am not an hls.js expert, in [an old issue](https://github.com/video-dev/hls.js/issues/542) i have read it will try to load next fragments until buffer >= config.maxBufferSize. It also suggest calling stopLoad() instance method.

Maybe listent to pause event attempt to call stopLoad() on hlsjs instance ?
