### ISSUE TITLE
Can't extend MediaControl

### ISSUE THREAD

**Issue by ofrzeta** [clappr/clappr#1884]
**Browser**: Firefox 68.2.0esr, Chrome 68.2.0esr 

**OS**: CentOS 7

**Clappr Version**: 0.3.9

**Steps to reproduce**:

* I tried extending Clappr.MediaControl  to use it in the creation of a new Clappr player object but it didn't work. When I inspect the corresponding variable it is a "Surrogate()" function instead of an Object. I understand this is from the implementation of utils.extend but I don't understand why it is not properly evaluated.
 
* Code to extend the media control:
```
if (typeof Clappr !== 'undefined') {
  console.log("extending clappr mediacontrol");
  var ClapprCustomFullscreenMediaControl = Clappr.MediaControl.extend({
    toggleFullscreen : function() {
      console.log("called toggleFullscreen callback");
      this.options.fullscreenCallback();
    }
  });
}
...
clappr_conf.mediacontrol = ClapprCustomFullscreenMediaControl;
player = new Clappr.Player(clappr_conf);

```
When I console.log the ClapprCustomFullscreenMediaControl variable it show:
```
ƒ Surrogate() {
      (0, _classCallCheck3.default)(this, Surrogate);

      for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
        args[_key] = arguments[_key];…
```

**Comment by kslimani** [comment]
@ofrzeta Since version 0.3.x, mediacontrols has become an ui core plugin.

Try to add your custom mediacontrols in the Clappr configuration using the `plugins` option.

For example :

```javascript
var player = new Clappr.Player({
  // [...]
  source: 'https://acme.org/myvideo.mp4',
  plugins: [ ClapprCustomFullscreenMediaControl ],
});
```

**Comment by ofrzeta** [comment]
Thanks a lot. Now it works.
