### ISSUE TITLE
Listen to playlist update hls event

### ISSUE THREAD

**Issue by perohu** [clappr/clappr#1885]
**What do you want to do with Clappr?**
I'd like to listen, when a live hls stream's playlist is updated

**What have you tried so far?**

This is my code. Can someone help me, what am I doing wrong? Thank you!

```
var testPlugin = Clappr.UICorePlugin.extend({

  name: 'test_Plugin',

  bindEvents() {
    if (Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED) {
      this.listenTo(this.core, Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED, this.rebindEvents)
    },
    this.listenTo(this.core.mediaControl, Clappr.Events.MEDIACONTROL_PLAYING, this.onMediaControlPlaying)
  },

  rebindEvents() {
    this.stopListening()
    this.bindEvents()
  },

  onMediaControlPlaying(){
    this.core.getCurrentPlayback()._hls.on('LEVEL_UPDATED', function(event, object) {
      console.log("playlist update");  // this never runs
    });
  },

});



```

**Comment by kslimani** [comment]
Your main issue here is that the HLSJS instance object is created only when player starts to play. Depending on if HLS source is LIVE or VOD, it may be also destroyed on stop event (if LIVE).

To get HLSJS instance, i think it can be done on playback "play" event.

For example :
_(try this code on [Clappr demo page](http://clappr.io/demo/))_

```javascript
var playerElement = document.getElementById("player-wrapper");

var TestPlugin = Clappr.UICorePlugin.extend({
  name: 'test_Plugin',

  bindEvents() {
    if (Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED) {
      this.listenTo(this.core, Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED, this._onContainerChanged)
    } else {
      this.listenTo(this.core.mediaControl, Clappr.Events.MEDIACONTROL_CONTAINERCHANGED, this._onContainerChanged)
    }
  },

  _playback() {
    return this.core.activePlayback
      ? this.core.activePlayback
      : this.core.getCurrentPlayback();
  },

  _onContainerChanged() {
    this._hlsIsBinded = false
    this._bindPlaybackEvents();
  },

  _bindPlaybackEvents() {
    var p = this._playback();
    if (p.name === 'hls') {
      p.listenTo(p, Clappr.Events.PLAYBACK_PLAY, this._onPlay);
    }
  },

  _onPlay() {
    if (this._hlsIsBinded) return; // Bind HLS events only once
    if (this._hls) {
      console.log('HLS Instance available', this._hls);
      // Do binding stuff with HLS instance here
      this._hlsIsBinded = true;
    }
  }

});

var player = new Clappr.Player({
  source: ' https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
  plugins: [ TestPlugin ],
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

**Comment by perohu** [comment]
Thank you kslimani!

**Comment by Jaikant** [comment]
> Your main issue here is that the HLSJS instance object is created only when player starts to play. Depending on if HLS source is LIVE or VOD, it may be also destroyed on stop event (if LIVE).
> 
> To get HLSJS instance, i think it can be done on playback "play" event.
> 
> For example :
> _(try this code on [Clappr demo page](http://clappr.io/demo/))_
> 
> ```js
> var playerElement = document.getElementById("player-wrapper");
> 
> var TestPlugin = Clappr.UICorePlugin.extend({
>   name: 'test_Plugin',
> 
>   bindEvents() {
>     if (Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED) {
>       this.listenTo(this.core, Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED, this._onContainerChanged)
>     } else {
>       this.listenTo(this.core.mediaControl, Clappr.Events.MEDIACONTROL_CONTAINERCHANGED, this._onContainerChanged)
>     }
>   },
> 
>   _playback() {
>     return this.core.activePlayback
>       ? this.core.activePlayback
>       : this.core.getCurrentPlayback();
>   },
> 
>   _onContainerChanged() {
>     this._hlsIsBinded = false
>     this._bindPlaybackEvents();
>   },
> 
>   _bindPlaybackEvents() {
>     var p = this._playback();
>     if (p.name === 'hls') {
>       p.listenTo(p, Clappr.Events.PLAYBACK_PLAY, this._onPlay);
>     }
>   },
> 
>   _onPlay() {
>     if (this._hlsIsBinded) return; // Bind HLS events only once
>     if (this._hls) {
>       console.log('HLS Instance available', this._hls);
> 
>       // Do binding stuff with HLS instance here
>       this._hls.on(Clappr.HLS.HLSJS.Events.LEVEL_LOADED, function(event, object) {
>         console.log("playlist update");
>       });
> 
>       this._hlsIsBinded = true;
>     }
>   }
> 
> });
> 
> var player = new Clappr.Player({
>   source: ' https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
>   plugins: [ TestPlugin ],
>   height: 360,
>   width: 640
> });
> 
> player.attachTo(playerElement);
> ```
> 
> EDIT: added "level loaded" HLS binding example _(HLSJS internal class is exposed by Clappr.HLS.HLSJS)_

Thanks @kslimani for this! But I just wish it was simpler to get the HLS instance than writing an entire plugin for it ...
