### ISSUE TITLE
Issue with playing HLS stream

### ISSUE THREAD

**Issue by savke24** [clappr/clappr#1886]
**Browser**: Version 78.0.3904.108 (Official Build) (64-bit)
**OS**: Windows 10

**Clappr Version**: Latest

**Steps to reproduce**:

Hello guys, i have issue with playing this stream : 
http://185.180.14.6:8081/aer35/index.m3u8

I had try on test pages and in clappr in crome developer console i see that stream is working (ts fragments are downloading) but in player i dont get any picture or sound,just loading.
On flasHls page i get video but i dont get sound.
Same behavior i get on my local hosted pages. 

From same server i have streams that work without any issue and also this stream generally work in vlc.

I googled a lot but couldn't find solutions.

I think codec is not issue as i have stream that are working with sames codes.

So only difference that i have found between streams that work and those that don't is that those that don't work are having metadata info, but that is coming from source and is not something on i can effect on.

Any help would be appreciated.
 
Thank You.

Kind Regards,

**Comment by leandromoreira** [comment]
It's playing. you can see it by yourself [here](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovLzE4NS4xODAuMTQuNjo4MDgxL2FlcjM1L2luZGV4Lm0zdTgnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=)
<img width="898" alt="image" src="https://user-images.githubusercontent.com/55913/70395751-c06da000-19e0-11ea-918c-fb9742ad17a3.png">

**Comment by leandromoreira** [comment]
Maybe it's something in your network.

**Comment by savke24** [comment]
Hi Leandro,

Thank You for getting back to me.

Did you test this on Chrome ? 

Can You send me source code of this test page? 
I try different version of clappr , but without success.

Also for me this stream dont work on http://clappr.io/demo/

check attach,that is from my local webserver  :

![clappr](https://user-images.githubusercontent.com/58664361/70396003-fd4b8e00-1a04-11ea-9f9f-0def91af1578.PNG)

**Comment by leandromoreira** [comment]
I tested with Firefox you can test it too http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovLzE4NS4xODAuMTQuNjo4MDgxL2FlcjM1L2luZGV4Lm0zdTgnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=

**Comment by savke24** [comment]
Its same on firefox and on chrome for me.

On this clappr demo page i get in console that files are downloading,but stream on player dont work..Just 3 dots loading.

How can i debug this on my side ?

**Comment by leandromoreira** [comment]
@savke24 I think the files are taking too long to download, I'm seeing 3 to 6 seconds to download each TS segment.

**Comment by leandromoreira** [comment]
Try to run mediastreamvalidator and other tools to see if they point for something else https://github.com/clappr/clappr/blob/dev/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues

**Comment by savke24** [comment]
This is output of hls-anylazer : 

Master playlist. List of variants:
        Playlist: http://185.180.14.6:8081/aer35/tracks-v1a1/mono.m3u8, bw: 3082655

***** Analyzing variant (3082655) *****

        ** Generic information **
        Version: 3
        Start Media sequence: 37198
        Is Live: True
        Encrypted: False
        Number of segments: 4
        Playlist duration: 23.52

        ** Downloading http://185.180.14.6:8081/aer35/tracks-v1a1/2019/12/08/23/31/39-06080.ts, Range: None **
        ** Tracks and Media formats **
        Track #0 - Type: video/avc, Format: Video (H.264) - Profile: 0, Level: 0, Resolution: 0x0, Encoded aspect ratio: 1/1, Display aspect ratio: 1
        Track #1 - Type: audio/mpeg, Format: MPEG Audio (MP3)

        ** Timing information **
        Segment declared duration: 6.08
        Track #0 - Duration: 0.0 s, First PTS: -1e-06 s, Last PTS: -1e-06 s
        Track #1 - Duration: 0.0 s, First PTS: -1e-06 s, Last PTS: -1e-06 s
        Duration is 0

        ** Frames **
        Track #0 - Frames:      AA: 37199, BB: 3082655

                Keyframes count: 0
                Warning: there are no keyframes in this track! This will cause a bad playback experience

        Track #1 - Frames:

As i see mediastreamvalidator is only for mac OS or it can be used on linux ?

**Comment by savke24** [comment]
This is output of mediainfo : 

General
Complete name                            : http://185.180.14.6:8081/aer35/index.m3u8
Format                                   : HLS
File size                                : 449 Bytes
Duration                                 : 5s 760ms
Overall bit rate                         : 624 bps

Video
ID                                       : 1-211 (0xD3)
Menu ID                                  : 1-465 (0x1D1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.0
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Muxing mode                              : HLS / MPEG-TS
Codec ID                                 : 27
Duration                                 : 5s 680ms
Bit rate                                 : 2 425 Kbps
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 fps
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Bits/(Pixel*Frame)                       : 0.234
Stream size                              : 1.64 MiB
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.470 System B, BT.470 System G
Matrix coefficients                      : BT.601
Source                                   : tracks-v1a1/mono.m3u8

Audio
ID                                       : 1-221 (0xDD)
Menu ID                                  : 1-465 (0x1D1)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Mode                                     : Joint stereo
Muxing mode                              : HLS / MPEG-TS
Codec ID                                 : 4
Duration                                 : 5s 760ms
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Delay relative to video                  : -177ms
Stream size                              : 90.0 KiB
Language                                 : English
Source                                   : tracks-v1a1/mono.m3u8

**Comment by savke24** [comment]
This is url of stream that work for me without issue : 

http://185.180.14.6:8081/aer34/index.m3u8

mediainfo output : 

General
Complete name                            : http://185.180.14.6:8081/aer34/index.m3u8
Format                                   : HLS
File size                                : 450 Bytes
Duration                                 : 6s 24ms
Overall bit rate                         : 598 bps

Video
ID                                       : 1-211 (0xD3)
Menu ID                                  : 1-1001 (0x3E9)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.0
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Format settings, GOP                     : M=3, N=27
Muxing mode                              : HLS / MPEG-TS
Codec ID                                 : 27
Duration                                 : 5s 960ms
Bit rate                                 : 1 300 Kbps
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 fps
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : MBAFF
Bits/(Pixel*Frame)                       : 0.125
Stream size                              : 946 KiB
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.470 System B, BT.470 System G
Matrix coefficients                      : BT.601
Source                                   : tracks-v1a1/mono.m3u8

Audio
ID                                       : 1-221 (0xDD)
Menu ID                                  : 1-1001 (0x3E9)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Muxing mode                              : HLS / MPEG-TS
Codec ID                                 : 4
Duration                                 : 6s 24ms
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Delay relative to video                  : -98ms
Stream size                              : 141 KiB
Source                                   : tracks-v1a1/mono.m3u8

**Comment by leandromoreira** [comment]
try to check the I-Frames (IDR), if they're present and aligned

```

            Keyframes count: 0
            Warning: there are no keyframes in this track! This will cause a bad playback experience

```

**Comment by savke24** [comment]
I am getting that same message on stream that is working so i dont think that that is issue : 

Master playlist. List of variants:
        Playlist: http://185.180.14.6:8081/aer34/tracks-v1a1/mono.m3u8, bw: 2320192

***** Analyzing variant (2320192) *****

        ** Generic information **
        Version: 3
        Start Media sequence: 20432
        Is Live: True
        Encrypted: False
        Number of segments: 4
        Playlist duration: 22.32

        ** Downloading http://185.180.14.6:8081/aer34/tracks-v1a1/2019/12/09/01/30/10-05400.ts, Range: None **
        ** Tracks and Media formats **
        Track #0 - Type: video/avc, Format: Video (H.264) - Profile: 0, Level: 0, Resolution: 0x0, Encoded aspect ratio: 1/1, Display aspect ratio: 1
        Track #1 - Type: audio/mpeg, Format: MPEG Audio (MP3)

        ** Timing information **
        Segment declared duration: 5.4
        Track #0 - Duration: 0.0 s, First PTS: -1e-06 s, Last PTS: -1e-06 s
        Track #1 - Duration: 0.0 s, First PTS: -1e-06 s, Last PTS: -1e-06 s
        Duration is 0

        ** Frames **
        Track #0 - Frames:      AA: 20433, BB: 2320192

                Keyframes count: 0
                Warning: there are no keyframes in this track! This will cause a bad playback experience

        Track #1 - Frames:

**Comment by leandromoreira** [comment]
ohhh I think I see, it's your audio format, you're using `mp3` and you should be using aac.

**Comment by leandromoreira** [comment]
also you can use ffprobe to check frame I frequency.

```
$ ffprobe -loglevel error -select_streams v:0 -show_entries frame=pict_type 42-05680.ts | grep "type=I"
pict_type=I
pict_type=I
pict_type=I
pict_type=I
pict_type=I
pict_type=I
```

**Comment by savke24** [comment]
not sure that is also issue : 
for bot streams i got same audio codec info : 

Non working stream : 
HLS Analyzer : Track #1 - Type: audio/mpeg, Format: MPEG Audio (MP3)
mediainfo : Format : MPEG Audio
                   Format version : Version 1
                   Format profile : Layer 2
VLC Codec info : Mpeg Audio layer 1/2 (mpga)

Working stream : 
HLS Analyzer : Track #1 - Type: audio/mpeg, Format: MPEG Audio (MP3)
mediainfo : Format : MPEG Audio
                   Format version : Version 1
                   Format profile : Layer 2
VLC Codec info : Mpeg Audio layer 1/2 (mpga)

**Comment by leandromoreira** [comment]
I mean, I think `mp3` has restriction to play at chrome not that the `mp3` is wrongly encoded try with aac

**Comment by leandromoreira** [comment]
I suppose the playback needs to (additionally) demux the mp3 https://github.com/video-dev/hls.js/blob/master/src/demux/mp3demuxer.js and regenerate aac https://github.com/video-dev/hls.js/blob/master/src/remux/mp4-generator.js anyway if you can swap it to aac to see

**Comment by savke24** [comment]
Sure i will try now
This is output of ffprobe : 

 ffprobe -loglevel error -select_streams v:0 -show_entries frame=pict_type 03-05440.ts | grep "type=I"
pict_type=I
pict_type=I
pict_type=I

**Comment by savke24** [comment]
Ok i am not sure how to use and include that 2files , but i have transcode stream and now is aac codec but still cant play it: 
mediainfo details : 

Complete name                            : http://185.180.14.6:8081/aer35/index.m3u8
Format                                   : HLS
Format profile                           : Master
File size                                : 480 Bytes
Duration                                 : 5s 738ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 669 bps

Video
ID                                       : 1-211 (0xD3)
Menu ID                                  : 1-901 (0x385)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Muxing mode                              : HLS / MPEG-TS
Codec ID                                 : 27
Duration                                 : 5s 640ms
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 fps
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.470 System B, BT.470 System G
Matrix coefficients                      : BT.601
Source                                   : tracks-v1a1/mono.m3u8
Source_Original                          : 2019/12/09/02/16/05-05760.ts

Audio
ID                                       : 1-221 (0xDD)
Menu ID                                  : 1-901 (0x385)
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 4
Format profile                           : LC
Muxing mode                              : HLS / MPEG-TS / ADTS
Codec ID                                 : 15
Duration                                 : 5s 738ms
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Delay relative to video                  : -222ms
Language                                 : English
Source                                   : tracks-v1a1/mono.m3u8
Source_Original                          : 2019/12/09/02/16/05-05760.ts

**Comment by savke24** [comment]
I should mention that this row stream from satelite and don't do any transcode on it ,now i am using original video and transcode just audio to aac.

**Comment by savke24** [comment]
Ok so i think that definitively is video issue here, as when i transcode video and left audio original stream is working , but when did otherwise ,stream didn't  work ...But question is what is difference in video when trascoding it ,and if can video be somehow played without transcoding it 
i am seding now transcoded video media info

**Comment by savke24** [comment]
Transcoded Video : 

Video
ID                                       : 1-211 (0xD3)
Menu ID                                  : 1-901 (0x385)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Muxing mode                              : HLS / MPEG-TS
Codec ID                                 : 27
Duration                                 : 5s 920ms
Bit rate                                 : 1 398 Kbps
Width                                    : 1 024 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Stream size                              : 1 011 KiB
Source                                   : tracks-v1a1/mono.m3u8
Source_Original                          : 2019/12/09/02/23/44-05920.ts


Original RAW not transcoded VIDEO : 
Video
ID : 1-211 (0xD3)
Menu ID : 1-465 (0x1D1)
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L3.0
Format settings, CABAC : Yes
Format settings, ReFrames : 4 frames
Muxing mode : HLS / MPEG-TS
Codec ID : 27
Duration : 5s 680ms
Bit rate : 2 425 Kbps
Width : 720 pixels
Height : 576 pixels
Display aspect ratio : 16:9
Frame rate : 25.000 fps
Standard : PAL
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Interlaced
Scan order : Top Field First
Bits/(Pixel*Frame) : 0.234
Stream size : 1.64 MiB
Color primaries : BT.601 PAL
Transfer characteristics : BT.470 System B, BT.470 System G
Matrix coefficients : BT.601
Source : tracks-v1a1/mono.m3u8

**Comment by leandromoreira** [comment]
the funny thing is that it works on firefox, at least on mine... 

> But question is what is difference in video when trascoding it ,and if can video be somehow played without transcoding it
i am seding now transcoded video media info

yes, the only way to know this info is by looking into `ffprobe` to see its timing, frames, packets to see which are the differences

**Comment by savke24** [comment]
yea, something in raw stream is messing with player ,so question is if is possible to somehow work around that. 
i am not that familiar with ffprobe, but if you can send me command that You need ,i will send You output.

**Comment by leandromoreira** [comment]
it's late in here but anyway it'd take forever to figure it out =/ one thing we can do is to run it on hlsjs player because it can provide debug logging info https://video-dev.github.io/hls.js/demo/ (but it requires your stream to be under https or you run it locally)

**Comment by leandromoreira** [comment]
>yea, something in raw stream is messing with player ,so question is if is possible to somehow work around that.

I don't think so but if we could it'd take longer and maybe the hlsjs people wouldn't accept since it might be some oddity of PAL original original encoding video

**Comment by savke24** [comment]
i was just start to type that i am going to bad :D 
yea when you have time send me those commands , and will return yo outputs ..
I think already check that page and i think it didnt work  (probably because https which i didn't know it must be ) .
Anyway i will try to test that localy and let You know.

Thank You for Your time and effort.
Talk to You soon
