### ISSUE TITLE
[Android] hide navigationUI on fullscreen

### ISSUE THREAD

**Issue by ziddey** [clappr/clappr#1888]
**Is your feature request related to a problem? Please describe.**
On recent versions of Chrome for Android, the navigation bar still shows when fullscreen.

**Describe the solution you'd like**
Navigation bar should be hidden like before

**Describe alternatives you've considered**
Can force immersive mode each time, but is not a good solution.

This feature was implemented here: https://www.chromestatus.com/feature/5188650908254208

My current solution is to override requestFullscreen like so:
```
Clappr.Utils.Fullscreen.requestFullscreen = function(el) {
	if (el.requestFullscreen)
		el.requestFullscreen({navigationUI: "hide"})
	else if (el.webkitRequestFullscreen)
		el.webkitRequestFullscreen()
	else if (el.mozRequestFullScreen)
		el.mozRequestFullScreen()
	else if (el.msRequestFullscreen)
		el.msRequestFullscreen()
	else if (el.querySelector && el.querySelector('video') && el.querySelector('video').webkitEnterFullScreen)
		el.querySelector('video').webkitEnterFullScreen()
	else if (el.webkitEnterFullScreen)
		el.webkitEnterFullScreen()
};
```

Rather than submit a PR to have this be hardcoded, perhaps a better solution would be to have this be configurable when creating a player.

Would also be nice to set fullscreen orientation similarly. Now, I have:
```
player.on('fullscreen', function(isFullscreen) {
	if (isFullscreen) {
		screen.orientation.lock('landscape');
	}
});
```

**Comment by ziddey** [comment]
Also, I'm looking into what happens when pinching in fullscreen mode. The default behavior exits fullscreen on pinch either in or out. Haven't looked too far into it, but so far I've tried stubbing core.handleWindowResize / core.resize as well as calling disableResizeObserver() without any effect. I'm trying to implement pinch to zoom (object-fit: cover) with viewport-fit=cover to fill these newer ultrawidescreen/notched phones. Any ideas?

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
