### ISSUE TITLE
Change Source of live stream

### ISSUE THREAD

**Issue by MohammaedAlani** [clappr/clappr#1889]
**What do you want to do with Clappr?**
                player = new Clappr.Player({
                        source: this.data.current_channel.streaming_url,   //on click
                        width: '100%',
                        parentId: "#livetv-player", 
                        plugins: [LevelSelector],
                        autoPlay: true,
                        levelSelectorConfig: {
                            title: 'Quality',
                            labels: {
                                2: 'High', // 500kbps
                                1: 'Med', // 240kbps
                                0: 'Low', // 120kbps
                            },
                        },
                        
                }); 
            },
**What have you tried so far?**
onclick i want to change this url to another url and old request stop all create new request for new source.

**Comment by kslimani** [comment]
@MohammaedAlani to change source url (and/or any configuration option) on an existing player instance use the `configure` method.

```javascript
// [...]
player.configure({
  source: 'another-url',
  // ...
});
```

**Comment by MohammaedAlani** [comment]
ok. that is work fine thank you.
I have another question when playing video mp4 in browser the player stop and starts loading but there is a buffer. and if backward little play when returning the same point stop again. if I do forward little play and no problem and after a few times show the same issues if there any solution for that or any idea to make listing or event solve the issues.

**Comment by kslimani** [comment]
I am not sure to understand your last question. But in case of .mp4 source, it __may__ be related to video metadata. For example, in FFmpeg it can be fixed using the `movflags=+faststart` option. You can read more [here](https://ffmpeg.org/ffmpeg-formats.html#mov_002c-mp4_002c-ismv).
