### ISSUE TITLE
Bug: Source fallback not working

### ISSUE THREAD

**Issue by RussCoder** [clappr/clappr#1891]
**Browser**: Chrome 79.0.3945.88

**OS**: Windows 10

**Clappr Version**: 0.3.12

This [demo example](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlczogWwogICAgJ2h0dHA6Ly9yZXRybzcwLmhvc3RpbmdyYWRpby5ydTo4MDI1L25vdC1yZWFsLm1wMycsCiAgICAnaHR0cDovL3JldHJvNzAuaG9zdGluZ3JhZGlvLnJ1OjgwMjUvcmV0cm83MC0xMjgubXAzJywKICBdLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAKfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cg==) doesn't work, because the first link isn't a real source, but the second link is the real source.

If you swap the links or remove the first one, it will work.

**Current behavior**: Clappr uses only the first link and if it is incorrect nothing works.

**Expected behavior**: Clappr should have used the second link as a fallback, and it should have worked.

Also it seems that the example from [this issue](https://github.com/clappr/clappr/issues/941) doesn't work either.

Specifically, I need it to work with icecast audio streams.

**Comment by kslimani** [comment]
@RussCoder i think that the `sources` does not work the way you think. As far as i remember, this option is used to provide multiple video/audio formats for the same "source". (for example, a video.mp4 with a video.m3u8)

Technically, it pickup the first source supported by the browser _(checking mime type, file extension, ...)_ and also select the proper "playback plugin" associated. This check if done before the source is attempted to play.

It is not (AFAIK) a way to provide a "fallback" if the playback has failed on first source.

But you should be able to achieve a simple "fullback" feature listening to error event. Take a look at [error documentation](https://github.com/clappr/clappr/blob/dev/doc/PLAYER_ERRORS.md) examples.

**Comment by RussCoder** [comment]
@kslimani thank you for the reply. 

Yes, I wanted it to work as multiple sources in the audio tag (the code can be executed on http://cdn.clappr.io):

```js
var playerElement = document.getElementById("player-wrapper");

playerElement.innerHTML =`
  <audio controls>
      <source src='http://retro70.hostingradio.ru:8025/not-real.mp3' type='audio/mp3'>
      <source src='http://retro70.hostingradio.ru:8025/retro70-128.mp3' type='audio/mp3'>
  </audio>
`;
```

I also tried to follow your advice to handle errors and it seems this way works - I just use the next source after each error.

**Comment by jorbig** [comment]
What would the script be to achieve this fallback functionality?

**Comment by Vivekji98** [comment]
Reclaim my data

**Comment by jorbig** [comment]
Care to elaborate? The error documentation is down.

**Comment by kslimani** [comment]
https://github.com/clappr/clappr#example

**Comment by jorbig** [comment]
Right now I have a simple fallback that changes the source to the backup m3u8 on error, but ideally I want Clappr to try the primary source again when an error happens while playing the backup source. In short: on error it should toggle between my two sources. How could this be achieved?
