### ISSUE TITLE
Control brightness and volume from the screen?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1892]
Is there any possibility to control brightness and volume from the screen as I do with VLC? (sliding my finger vertically from the left or right side)

**Comment by leandromoreira** [comment]
can we control the brightness of a screen by the web browser? about the volume, do you want it to behave like that for all cases or only for mobile?

**Comment by hijuuijj** [comment]
Got it. I speak from my absolute ignorance. Thanks.

**Comment by kslimani** [comment]
I think video brightness browser addons/plugins exists. Just perform some search with your favorite search engine website.
