### ISSUE TITLE
Catching the end of the stream

### ISSUE THREAD

**Issue by Infrox** [clappr/clappr#1893]
Hey there, is it possible to somehow make the player automatically try to catch up to the stream when its buffering? I want the player to return to the real-time after it has lagged. At the moment, if the user is watching with poor connection, the player buffers every once in a while and he becomes further and further away from the real time.

**Comment by leandromoreira** [comment]
you may try to replace the [hls.js BufferController](https://github.com/video-dev/hls.js/blob/30cb6d3ac7eafb25ca93f08ed7bcc250703d721c/src/controller/buffer-controller.ts) (via options) providing your implementation that needs to catch up by seeking forward at 1.25x or less

**Comment by Infrox** [comment]
Could you show me an example?

**Comment by leandromoreira** [comment]
I don't have but you can search at the hlsjs issues things like that might help you https://github.com/video-dev/hls.js/issues/1505 

OR you could try to brute force by [handling the error](https://github.com/clappr/clappr/blob/dev/doc/PLAYER_ERRORS.md) and calculating the edge distance and changing playback speed...
