### ISSUE TITLE
Error code: html_video: 4

### ISSUE THREAD

**Issue by Avrinbai** [clappr/clappr#1894]
Dear developer, I am from China and I really like your plugin, but I encountered an error when I was running the code.
I'm not sure if it's an encoding problem because my video format is mkv.
I passed the code file into the attachment.
[video.zip](https://github.com/clappr/clappr/files/4069403/video.zip)

**Comment by kslimani** [comment]
I think mkv container is not widely supported by web browsers. I suggest to convert your video to another container; For example : mp4.

**Comment by Avrinbai** [comment]
> 我认为mkv容器不受Web浏览器的广泛支持。我建议将您的视频转换为另一个容器；例如：mp4。

OK, I'm already converting MP4 format, thank you very much for replying!
