### ISSUE TITLE
MediaControl settings driven by playback.

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1895]
I've been customizing mediacontrol for a while, adding options for managing styles and ways to pass this data to other UI plugins. Recently, it became necessary to change the order of elements, and then I was surprised to find that playback affects the location of controls. Through the container.
At the same time, for some reason, the playback knows exactly which panel the element should be placed in, and mediacontrol can apply these settings many times. This makes the extension of the native mediacontrol more complicated.
Of course, I should have thought about writing mediacontrol from scratch, but it hasn't come to that yet. And I would still like to rely mainly on a ready-made architecture.
So is there a real need for such a mix of functionality in the playback and UI?

**Comment by joaopaulovieira** [comment]
I don't know if today is necessary this accoupling between the media control and other Clappr components (like `container` and `playback`) but in another moment this has been necessary. One example is the component to indicate the `HD quality`, only the `playback` know this feature and update the settings to render on media control.

The current media control contains a bunch of legacy code. (sorry 😅)

We have plans to create a brand new one media control, but this is one of the various other changes in our plans. We already do the first step to make this change when transforming the media control from Clappr component to one `UICorePlugin`.

So, if you need any other thing that is not a custom style on the current media control and its elements, I recommend creating one custom media control to replace then.
