### ISSUE TITLE
overriding css color play/stop button

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1897]
hi,
Is there a possibility to override the color of play/stop/pause button directly in clappr without changing it in clappr.js ? I would like to have possibility to put them white or black
I'm not familiar with that so help is welcome.
Thanks

**Comment by sapolio** [comment]
This is possible if you extend the media control plugin.
You should alter the applyButtonStyle method, which is executed every time the play/stop button is re-rendered.

**Comment by Niko78** [comment]
> 
> 
> You should also be able to change colors using custom css rules. _(overriding default css rules)_

that's what I would like to do but how do you do that inside clappr ?

**Comment by kslimani** [comment]
I just remembered there is also an option to change buttons colors (and also progress bar color) :

For example :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  height: 360,
  width: 640,
  mediacontrol: {buttons: "#66B2FF"}
});

player.attachTo(playerElement);
```

Se also [documentation](https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md#control-bar-colors).

**Comment by Niko78** [comment]
thanks kslimani, yeah it changes all buttons
I just need to change play/stop (and even spinning circle) in the middle of player, that's all
I try to find a solution

**Comment by kslimani** [comment]
Do you need to "dynamically" change the colors ?

**Comment by Niko78** [comment]
nope
We have a form for our users and they have to choose button color (black/white) before creating player page. I need that because they chose background and sometimes background is white or black and player button can be hidden, that's why I need this option

**Comment by sapolio** [comment]
The "buttons" option (as in the comment above) changes all buttons at once. 
If you need to change one specific button, you will need to modify the media control plugin or override the css rules for this element.
By changing the plugin itself, you can add a custom color option to use in the future.
Of course, you need to be familiar with Javascript to do this.

**Comment by kslimani** [comment]
I agree with @sapolio about overriding [applyButtonStyle](https://github.com/clappr/clappr/blob/dev/src/plugins/media_control/media_control.js#L646) mediacontrol method, if you need to dynamically change bouton colors depending on some conditions _(like background color)_.

Btw i am not sure to understand when you write "in the middle of player" : are you referring to icons color for "poster" and "spinner" plugins ?

**Comment by Niko78** [comment]
you are right in your last comment, "middle of player" means poster/spinner yes, only that

**Comment by kslimani** [comment]
_(already posted on Slack, but i add it also here for completeness)_

A simple css trick to change poster play icon color is _(set color to red)_ :

```css
.play-wrapper[data-poster] svg path {
    fill: #f00 !important;
}
```

**Comment by Niko78** [comment]
works great thanks
I added also the second 👍 
  .spinner-three-bounce[data-spinner] > div {
            background-color: red !important;
        }

**Comment by inside83** [comment]
@Niko78 adn @kslimani 
where exactly do you add this
```
.play-wrapper[data-poster] svg path {
    fill: #f00 !important;
}
.spinner-three-bounce[data-spinner] > div {
background-color: red !important;
}
```

**Comment by kslimani** [comment]
It is [css](https://www.w3schools.com/css/), added in html page where player is displayed.

**Comment by inside83** [comment]
yeah, thank you
added it between style tags and it's working great
do you (or anyone else) by any chance know if the play button can be replaced in the same way?

**Comment by kslimani** [comment]
You can override css rules for any button. Just use browser console inspector tools to get selectors.

![image](https://user-images.githubusercontent.com/1758996/105382793-bcb2d200-5c10-11eb-8e0a-6845c37feb91.png)

![image](https://user-images.githubusercontent.com/1758996/105382842-cd634800-5c10-11eb-97ce-a405b66bfc15.png)

**Comment by inside83** [comment]
@kslimani thank you for your response but you assume I'm a CSS guru like yourself 😊
could I bother you wit instructions as to how to actually change default play button with some other?
I found this https://www.svgrepo.com/svg/13672/play-button
But when I check the default one, this comes up
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" data-poster="" class="poster-icon">
<path fill="#010101" d="M1.425.35L14.575 8l-13.15 7.65V.35z"></path>
</svg>
```
And I have no idea what to do... 🤷‍♂️

**Comment by kslimani** [comment]
There are no feature yet in player to change mediacontrol icons, and therefore it is complicated.
(technically, you may need to fork the media_control and poster plugins project, replace svg icons and recompile your own versions of the plugins)

**Comment by inside83** [comment]
So I can't change default play button (the big one, when the player loads) but I could change the buttons under the seekbar using css?
Could you pretty please provide a code for it? 🙏
What about the seekbar itself? Any way to make it thicker a bit?

**Comment by kslimani** [comment]
A simple Javascript trick to change poster svg icon is :

```javascript
var playerElement = document.getElementById("player-wrapper");

var customPlay = '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 492.719 492.719" xml:space="preserve"><path d="M492.719,166.008c0-73.486-59.573-133.056-133.059-133.056c-47.985,0-89.891,25.484-113.302,63.569 c-23.408-38.085-65.332-63.569-113.316-63.569C59.556,32.952,0,92.522,0,166.008c0,40.009,17.729,75.803,45.671,100.178 l188.545,188.553c3.22,3.22,7.587,5.029,12.142,5.029c4.555,0,8.922-1.809,12.142-5.029l188.545-188.553 C474.988,241.811,492.719,206.017,492.719,166.008z"/></svg>';

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  events: {
    onReady: function() {
      Clappr.$('.poster-icon').replaceWith(customPlay);
    }
  }
});

player.attachTo(playerElement);
```

You can test this code [HERE](http://clappr.io/demo/).

It is more complicated to change the media controls while video is playing (ie: you can't use a simple trick).

**Comment by inside83** [comment]
♥ 😀
Thanks a lot!!!

**Comment by mikevipe** [comment]
Another way:

locate: 
.player-poster[data-poster]:hover .play-wrapper[data-poster]{opacity:1}.player-poster[data-poster] .play-wrapper[data-poster]{width:100%;height:75%;margin:0 auto;opacity:.75;transition:opacity

change the height:75% to 0% and then use a poster image.
