### ISSUE TITLE
Rewind seek bar for live is not available

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1898]
I'm not able to rewind this video with Clappr: 

https://voa-lh.akamaihd.net/i/voa_tvmc2@317693/master.m3u8

However I can do it with Native HLS Playback Chrome extension
https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof

Is there any way to enable it? with some plugin or extra code.

Thanks in advance.

**Comment by leandromoreira** [comment]
This HLS is 30s long and it seems do not fit into the [DVR enable logic](https://github.com/clappr/clappr/blob/6fd26c6437e07a9af86377eb63781cfff6aff8b5/src/playbacks/hls/hls.js#L629).

**Comment by hijuuijj** [comment]
Thanks Leandro. So there is no way to force the rewind for some videos? Sometimes I want to repeat something that happened a few seconds ago.

**Comment by leandromoreira** [comment]
Yes, as you can see you can pass the [`hlsMinimumDvrSize`](https://github.com/clappr/clappr/blob/6fd26c6437e07a9af86377eb63781cfff6aff8b5/src/playbacks/hls/hls.js#L114) option.

**Comment by hijuuijj** [comment]
Ok, adding hlsMinimumDvrSize: 1 or any number
Thank you!
