### ISSUE TITLE
How to overlay something on full-screen mode?

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1900]
**What do you want to do with Clappr?**
I'm actually overlaying some text on the video, with an absolute positioned div over the player div.
It's perfectly working, but when I go full-screen my text obviously disappear.
How can I do the same when the player is full-screen?
I can't understand which div is created in full-screen mode, could you help me?
Many thanks!

**What have you tried so far?**

<div id="player" style="height: 100%;"></div>

<div id="textOverTheVideo" style="position: absolute;>
<p>MyText</p>
</div>

**Comment by kslimani** [comment]
If i remember correctly, it is the container element which is set to fullscreen except on some mobile devices (like iphone) where it is the video element which is set to fullscreen (and therefore it is impossible to overlay anything).

For example, just  could llisten to fullscreen events to re-render your overlay element.

**Comment by renatofrota** [comment]
```
player.core.toggleFullscreen = function() {
    if (!document.fullscreenElement) {
        // choose an outer element to go fullscreen
        // (the player should be within this element)
        outer = document.querySelector("body");
        outer.requestFullscreen();
        // hide inner elements which have "hide-fs" class
        // by adding 'display-none' class (previously prepared with "display: none;")
        const hidefs = document.querySelectorAll(".hide-fs");
        for (let i = 0; i < hidefs.length; i++) {
            hidefs[i].classList.add('display-none');
        }
    } else {
        // the request to exitFullscreen always go to the document
        // it does not work if you send it directly to the outer element
        document.exitFullscreen();
        // display the inner elements again removing 'display-none' class
        const hidefs = document.querySelectorAll(".hide-fs");
        for (let i = 0; i < hidefs.length; i++) {
            hidefs[i].classList.remove('display-none');
        }
    }
};
```

You may also need to adjust the height or max-height of video element to `100vh` (adding a prepared CSS class to the video element or any of the elements within the outer element that went fullscreen, for example).
