### ISSUE TITLE
Custom button on UI

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1901]
**What do you want to do with Clappr?**
I'm using a custom plugin to show Closed Captions, and I'd like to put on the bottom UI a new button to show/hide them (and choose the language).
Is it possible to put a new button on the UI?
Or, maybe, is it possible to show the standard CC button and "redirect" it to my plugin?

Many thanks!

**What have you tried so far?**

**Comment by kslimani** [comment]
Yes it is possible, just study the current [internal CC plugins](https://github.com/clappr/clappr/tree/dev/src/plugins/closed_captions)

The code responsible to insert the icon is [here](https://github.com/clappr/clappr/blob/dev/src/plugins/closed_captions/closed_captions.js#L124)
