### ISSUE TITLE
What is the spinner event for clappr

### ISSUE THREAD

**Issue by shamun** [clappr/clappr#1903]
![image](https://user-images.githubusercontent.com/107349/75123133-01528800-56a5-11ea-9478-c28ded9d3569.png)

**What do you want to do with Clappr?**
Get the event of the spinner showing?

```
<div data-spinner="" class="spinner-three-bounce" style="display: none;">
<div data-bounce1=""></div>
<div data-bounce2=""></div>
<div data-bounce3=""></div>
</div>
```

**What have you tried so far?**
Following not triggering the event of dot dot dot...
```
player.on(Clappr.Events.PLAYER_ENDED, function() { console.log("end!") });
player.on(Clappr.Events.PLAYBACK_BUFFERING, function() { console.log("buffer!") });
player.on(Clappr.Events.PLAYBACK_PAUSE, function() { console.log("pause!") });
player.on(Clappr.Events.PLAYBACK_PROGRESS, function() { console.log("pause!") });
```

**Comment by leandromoreira** [comment]
try to do it inside the player config https://github.com/clappr/clappr/issues/1902

**Comment by shamun** [comment]
@leandromoreira : i tried #1902 but the "spinner" event is not triggering. When you play the video of streaming. and then the streaming is closed. there is three dot dot dot.. like loading icon. Those events i was looking for.

PLAYER_PLAY, PLAYER_ENDED, PLAYER_SEEK, PLAYER_PAUSE, PLAYER_READY.

But the spinner event seems like do not exist on them?

**Comment by shamun** [comment]
Unable to get the spinner event.

```
var playerElement = document.getElementById("player_wrapper");
var player = new Clappr.Player({
  source: 'https://mysite.1.m3u8', 
  mute: false,      
  height:'100%',
  width:'100%',      
});

player.listenTo(player, Clappr.Events.PLAYER_READY, () => {
  console.log("OK - Video ready");
});
player.listenTo(player, Clappr.Events.PLAYER_ENDED, () => {
  console.log("NOK - Video End");
});
player.listenTo(player, Clappr.Events.PLAYBACK_BUFFERING, () => {
  console.log("NOK - Video Buffer");
});
player.listenTo(player, Clappr.Events.PLAYER_PAUSE, () => {
  console.log("NOK - Video Pause");
});
player.listenTo(player, Clappr.Events.PLAYER_SEEK, () => {
  console.log("NOK - Video Seek");
});
player.attachTo(playerElement);
```

**Comment by leandromoreira** [comment]
@shamun it does show when buffering https://github.com/clappr/clappr/blob/dev/src/plugins/spinner_three_bounce/spinner_three_bounce.js#L24

Each event has its own listening objects.

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

player.listenTo(player.core.activeContainer, Clappr.Events.CONTAINER_STATE_BUFFERING, () => {
  console.log("NOK - Video Buffer");
});

```

demo here http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly90ZXN0LXN0cmVhbXMubXV4LmRldi94MzZ4aHp6L3gzNnhoenoubTN1OCcsCiAgcG9zdGVyOiAnaHR0cDovL2NsYXBwci5pby9wb3N0ZXIucG5nJywKICBtdXRlOiB0cnVlLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAKfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7CgpwbGF5ZXIubGlzdGVuVG8ocGxheWVyLmNvcmUuYWN0aXZlQ29udGFpbmVyLCBDbGFwcHIuRXZlbnRzLkNPTlRBSU5FUl9TVEFURV9CVUZGRVJJTkcsICgpID0+IHsKICBjb25zb2xlLmxvZygiTk9LIC0gVmlkZW8gQnVmZmVyIik7Cn0pOwo=

**Comment by shamun** [comment]
Thanks!!! It is working now. Spinner event is received.

```
// Step 0
var playerElement = document.getElementById("player_wrapper");
var player = new Clappr.Player({
  source: 'https://mysite/1.m3u8', 
  mute: false,      
  height:'100%',
  width:'100%',  
  events: {
    onStop:  function() { console.log("stop!"); },    // OK
//    onBufferFull:  function() { console.log("stop!"); }, // NOK
//    onBuffering:  function() { console.log("stop!"); }, // NOK
  }   
});

// Step 1
player.listenTo(player, Clappr.Events.PLAYER_READY, () => {
  console.log("OK - Video ready");
});

// Step 2
player.attachTo(playerElement);

// Step 3: Must be called here
player.listenTo(player.core.activeContainer, Clappr.Events.CONTAINER_STATE_BUFFERING, () => {
  console.log("OK - Video Buffer");
});
```
