### ISSUE TITLE
Controlling playback speed - is it possible with Clappr?

### ISSUE THREAD

**Issue by katsar0v** [clappr/clappr#1906]
**What do you want to do with Clappr?**

I would like to control the speed of the video (e.g. 0.5x, 0.75x, 1x, 1.25x, 1.5x)

**What have you tried so far?**

I tried the following plugins:

* https://github.com/Lethea/clapper-playback-speed-plugin-extended
* https://github.com/Viewly/clappr-playback-speed
* https://github.com/bikegriffith/clappr-playback-rate-plugin

I tried the plugins with Clappr `0.3.9` and an old version like `0.2.5` (from cdn), both did not work. Maybe someone can help me out here?

**Comment by kslimani** [comment]
A quick way to have fun with current playback speed is :
_(you can try this code a [Clappr demo page](http://clappr.io/demo/) using browser Javascript console)_

```javascript
// Assuming "player" is Clappr Player instance
var currentSpeed = player.core.activePlayback.el.playbackRate; // 1

// Set speed to 50%
player.core.activePlayback.el.playbackRate = 0.5;
```

See also [HTMLMediaElement.playbackRate](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate).

**Comment by katsar0v** [comment]
> A quick way to have fun with current playback speed is :
> _(you can try this code a [Clappr demo page](http://clappr.io/demo/) using browser Javascript console)_
> 
> ```js
> // Assuming "player" is Clappr Player instance
> var currentSpeed = player.core.activePlayback.el.playbackRate; // 1
> 
> // Set speed to 50%
> player.core.activePlayback.el.playbackRate = 0.5;
> ```
> 
> See also [HTMLMediaElement.playbackRate](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate).

Thank you, this works, but I would like to have this settings menu or dropdown like here:

![image](https://user-images.githubusercontent.com/7236157/75761062-af5ed180-5d38-11ea-996c-2b0cbf66e531.png)

I guess this is possible from the API, but is there a *working* extension that does the job?

**Comment by kslimani** [comment]
It seems that the plugin repository has not been updated since a long time. There was some changes in Clappr 0.3.x release. You may need to open an issue in plugin repository ?

**Comment by katsar0v** [comment]
> It seems that the plugin repository has not been updated since a long time. There was some changes in Clappr 0.3.x release. You may need to open an issue in plugin repository ?
> 
> EDIT: it seems the project is accepting PR. If i find some time i may submit a PR to fix it.

That sound great (with the PR), as for the plugin repos - I submitted issues as well, but I think the repositoroes / projects are not maintained anymore.

**Comment by kslimani** [comment]
@katsar0v  your issue should be resolved with latest release of [https://github.com/bikegriffith/clappr-playback-rate-plugin](https://github.com/bikegriffith/clappr-playback-rate-plugin).

**Comment by katsar0v** [comment]
Thank you @kslimani !
