### ISSUE TITLE
Where is doc for all available Clappr.Player possible options?

### ISSUE THREAD

**Issue by pedrofurtado** [clappr/clappr#1909]

**Comment by kslimani** [comment]
Clappr API doc exists, but i am not sure it is up to date _(but it give a good preview)_. It is [here](https://clappr.github.io/classes/Player.html#method_constructor).

See also [BUILTIN_PLUGINS](https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md) doc.
