### ISSUE TITLE
player.getDuration() return NaN or 0

### ISSUE THREAD

**Issue by DanieleSuppo73** [clappr/clappr#1910]
I don't know if it's a bug, or I'm missing something:
I should get the video duration when the video is ready, but with my videos it return 0, with the provided demo video it return NaN

**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Chrome

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Windows 10

**Clappr Version**: 0.3.8

**Steps to reproduce**:

var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.listenTo(player, Clappr.Events.PLAYER_READY, () => {
  console.log("Video ready");
  console.log(player.getDuration())  /// NaN

  
});

player.attachTo(playerElement);

Did you try to reproduce this issue at http://cdn.clappr.io/

YES

ps: you can attach images, logs or whatever you think might be helpful.
ps: feel free to clean this if your issue is different.

**Comment by joaopaulovieira** [comment]
Hi @DanieleSuppo73 !

Doing some tests I noticed that the `video element` is not returning the `duration` property as soon as its state changes to `READY`. We need further investigation but it appears to be a bug.

To solve it momentarily, if you delay the call to the `getDuration` method a bit, the answer will come correctly.

An example of how to do it: http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogIGV2ZW50czogewogICAgb25SZWFkeTogZnVuY3Rpb24oKSB7CiAgICAgIHNldFRpbWVvdXQoKCkgPT4gewogICAgICAgICByZXR1cm4gY29uc29sZS5sb2codGhpcy5nZXREdXJhdGlvbigpKTsKICAgICAgfSwgMTAwMCk7CiAgICB9CiAgfQp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK

**Comment by Steffeng5** [comment]
As I also stumbled over this issue I found a maybe better way: clappr provides a timeupdate event

http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogIGV2ZW50czogewogICAgb25UaW1lVXBkYXRlOiBmdW5jdGlvbihldmVudCkgewogICAgICBjb25zb2xlLmxvZyhldmVudCkKICAgIH0KICB9Cn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=
