### ISSUE TITLE
Media Control Bar Stop Button Hide or Disable

### ISSUE THREAD

**Issue by volkankoc** [clappr/clappr#1911]
Hello
I want to disable or hide the stop button on clappr, can you help me
![clappr_m3u8](https://user-images.githubusercontent.com/22777823/76700590-116cee80-66ca-11ea-92c3-2ae2abfd122e.png)

this project m3u8 live

**Comment by kslimani** [comment]
A "fast and dirty" way in javascript :

```javascript
// Assume player is playing live stream
Clappr.$('.media-control-button[data-playpause]').hide();
Clappr.$('.media-control-button[data-playstop]').hide();
```

**Comment by joaopaulovieira** [comment]
Yeah, currently there is no way to deactivate media control buttons via options. We need to add this config to media control.
