### ISSUE TITLE
add advertisement

### ISSUE THREAD

**Issue by k2name** [clappr/clappr#1912]
Hi.
Need organize the display of advertising before the main video.
I tried the option sources - only the first file plays.

    var player = new Clappr.Player({
    sources: [
        "http://url/video/hls/small/index.m3u8",
        "http://url/video/hls/big/index.m3u8"
    ],
    parentId: "#player",
    poster: "http://url/video/hls/big/poster.jpg",
    disableErrorScreen: true,
    autoPlay: false,
    loop: false,
    height: 576,
    width: 1024});

How need add other source before main video?

**Comment by kslimani** [comment]
To play consecutively videos, the [Clappr Playlist Plugin](https://github.com/towerz/clappr-playlist-plugin) may help.

To display [VAST-compliant](https://www.iab.com/guidelines/digital-video-ad-serving-template-vast/) adverts, the [Clappr IMA SDK Plugin](https://github.com/kslimani/clappr-ima-plugin) may help.

**Comment by k2name** [comment]
IMA SDK Pluggin work with google.
It`s wrong way for me. 

Im will play before main video, video from local storage. 
Maybe Clappr Playlist Plugin - best way for it. Now need time for check it.
Thanks

**Comment by k2name** [comment]
it`s best issue https://github.com/towerz/clappr-playlist-plugin/issues/3
