### ISSUE TITLE
Replace an error message with a file

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1914]
I would like to replace any Clappr error with a PHP or JS file (with an alert).
What code should I include?

Thank you in advance.

**Comment by joaopaulovieira** [comment]
Hi @hijuuijj , can you show an example of what JS file you use in this case?

**Comment by hijuuijj** [comment]
if any Clappr error, open:

<script>alert('Video not available')</script>

**Comment by joaopaulovieira** [comment]
Hi @hijuuijj !

You can disable the `ErrorScreen` plugin and listen to `ERROR` event to do it.

One example:
```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

player.core.getPlugin('error_screen').disable();

player.core.on(Clappr.Events.ERROR, () => {
  player.stop();
  alert('A Clappr error');
})
```
Run this code above on `http://clappr.io/demo` and force a error via console on developer tools:

```
player.core.trigger(Clappr.Events.ERROR, {code: 'ERROR_TEST', level: 'FATAL', UI:{title: 'error title', message: 'error message'}});
```

This stops Clappr and shows an alert.

**Comment by joaopaulovieira** [comment]
@hijuuijj Was that the behavior you wanted?
