### ISSUE TITLE
[error][hlsjs: failed to recover]

### ISSUE THREAD

**Issue by andrzej33113** [clappr/clappr#1915]
**Browser**: Chrome 80.0.3987.149, EDGE 18363 

**OS**: Windows 10 PRO

**Clappr Version**: 0.3.8

Hi, 
I started stream with clappr, but when i try from IPOX PRO camera (from rtsp) i got black screen and error "[error][hlsjs: failed to recover]" in console. 
It's doesn't work on firefox/chrome, but in Microsoft Edge i see video without any problem...
Can u help me? 
U can check stream on http://sblinternet.pl/kamery/test-168 try with edge and chrome/firefox.

Here is camera settings
![image](https://user-images.githubusercontent.com/23656786/77903066-8b80a400-7282-11ea-9e3c-53efa4d42e38.png)

Did you try to reproduce this issue at http://cdn.clappr.io/

![image](https://user-images.githubusercontent.com/23656786/77905665-f3d18480-7286-11ea-832e-205cfd895565.png)

@edit 
In VLC Media Player stream work without any problem.

![image](https://user-images.githubusercontent.com/23656786/77907264-a1de2e00-7289-11ea-9bfc-2d20da0c88ca.png)

**Comment by kslimani** [comment]
On your test page, the m3u8 hls playlist loaded by the player inside the iframe return a 404 http error. (not found).

**Comment by andrzej33113** [comment]
> Na stronie testowej lista odtwarzania m3u8 hls ładowana przez odtwarzacz wewnątrz elementu iframe zwraca błąd 404 http. (nie znaleziono).

Try again now.

**Comment by me-vlad** [comment]
Hi, @andrzej33113 

Stream missing on your Wowza media server (returns 404)

curl -v http://streaming.e-sbl.net:1935/live_aac//playlist.m3u8
*   Trying 178.218.224.13:1935...
* TCP_NODELAY set
* Connected to streaming.e-sbl.net (178.218.224.13) port 1935 (#0)
> GET /live_aac//playlist.m3u8 HTTP/1.1
> Host: streaming.e-sbl.net:1935
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Server: WowzaStreamingEngine/4.8.0
< Content-Length: 0

**Comment by kslimani** [comment]
The hls.js _(the library used internally by Clappr to play hls source)_ error for your playlist is `manifestIncompatibleCodecsError`. It means that the codec used to encode the video is not supported by the browser. Try to change the level/profile codec used to match one compatible with web browsers.

**Comment by andrzej33113** [comment]
> Hi, @andrzej33113
> 
> Stream missing on your Wowza media server (returns 404)
> 
> curl -v http://streaming.e-sbl.net:1935/live_aac//playlist.m3u8
> 
> * Trying 178.218.224.13:1935...
> * TCP_NODELAY set
> * Connected to streaming.e-sbl.net (178.218.224.13) port 1935 (#0)
> 
> > GET /live_aac//playlist.m3u8 HTTP/1.1
> > Host: streaming.e-sbl.net:1935
> > User-Agent: curl/7.66.0
> > Accept: _/_
> 
> * Mark bundle as not supporting multiuse
>   < HTTP/1.1 404 Not Found
>   < Accept-Ranges: bytes
>   < Server: WowzaStreamingEngine/4.8.0
>   < Content-Length: 0

It's because i make some changes at streaming engine, now it's work.



> The hls.js _(the library used internally by Clappr to play hls source)_ error for your playlist is `manifestIncompatibleCodecsError`. It means that the codec used to encode the video is not supported by the browser. Try to change the level/profile codec used to match one compatible with web browsers.

Well, i test every profile on camera settings, what do u mean about level? In topic u have screen from camera settings

**Comment by me-vlad** [comment]
Check your brouser codec capabilities for example on page
https://cluster.video/

About H254 Profiles and Levels
https://en.wikipedia.org/wiki/Advanced_Video_Coding#Profiles
https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels

If you using Wowza Streaming Engine - you can transcode your stream to desired H254 profile, level etc

And I still see 404 status for stream http://streaming.e-sbl.net:1935/live_aac//playlist.m3u8

**Comment by andrzej33113** [comment]
> Check your browser codec capabilities for example on page
> https://cluster.video/
> 
> About H254 Profiles and Levels
> https://en.wikipedia.org/wiki/Advanced_Video_Coding#Profiles
> https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels
> 
> If you using Wowza Streaming Engine - you can transcode your stream to desired H254 profile, level etc
> 
> And I still see 404 status for stream http://streaming.e-sbl.net:1935/live_aac//playlist.m3u8

When I'm transcoding from Wowza to h264 video work without any problem, but this is problem because many resources being used, my streaming engine is on virtual machine without graphic card. This problem is only on IPOX PRO CAMERA, in other (u can see for example here http://sblinternet.pl/kamery/bieru-rynek-76 ) is working.

**Comment by me-vlad** [comment]
Try to find an optimal encoding settings on your camera.
Hint - check Audio encoding settings - it must be aac or mp3 (not pcm or ulaw)
Video - H264 (at least profile baseline level 3.0)

**Comment by andrzej33113** [comment]
Ok, when I'm play from IE it's work, on Edge it's work, on other - doesn't work... 
![image](https://user-images.githubusercontent.com/23656786/77917952-811ed400-729b-11ea-9d63-acac254ea535.png)





> Try to find an optimal encoding settings on your camera.
> Hint - check Audio encoding settings - it must be aac or mp3 (not pcm or ulaw)
> Video - H264 (at least profile baseline level 3.0)

I'm trying every combination, now when i'm aplly new setting on camera i can watch stream, but after refresh again get [error][hlsjs: failed to recover]

**Comment by me-vlad** [comment]
Your initial (main/master) manifest playlist.m3u8 contains just 1 entry

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2987074,CODECS="avc1.676400",RESOLUTION=1920x1080
chunklist_w1326666730.m3u8

Try to set up Wowza hls packetizer (Cupertino Streaming Packetizer) to use 3  

                <Property>
                    <Name>cupertinoMaxChunkCount</Name>
                    <Value>10</Value>
                    <Type>Integer</Type>
                </Property>
                <Property>
                    <Name>cupertinoPlaylistChunkCount</Name>
                    <Value>3</Value>
                    <Type>Integer</Type>
                </Property>

**Comment by andrzej33113** [comment]
![image](https://user-images.githubusercontent.com/23656786/77921352-f391b300-729f-11ea-838e-be4d7f5edc2c.png)
Still i see error... the only was is transcoding h264 to h264...

**Comment by me-vlad** [comment]
Also  your playlist contains incorrect codec info 
CODECS="avc1.674200"

But you video is H264 High level 4.2 -  avc1.64002A

**Comment by me-vlad** [comment]
How I see baseline 3.1 video but playlist still wrong

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=4325583,CODECS="avc1.674200",RESOLUTION=1280x720
chunklist_w475716430.m3u8

Try to add SMIL file (rynek.smil) with corrects codecs info to you apllication content directory
/usr/local/WowzaStreamingEngine/content/live by default for app "live"

<?xml version="1.0" encoding="UTF-8"?>
<smil title="Rynek Cam SMIL">
<head></head>
<body>
    <switch>
        <video src="rynek_imielin.stream" system-bitrate="4300000" width="1920" height="1080" title="Rynek Camera">
            <param name="videoBitrate" value="4300000" valuetype="data"/>
            <param name="videoCodecId" value="avc1.64002A" valuetype="data"/>
          </video>
     </switch>
</body>
</smil>


And user URL with smil

http://streaming.e-sbl.net:1935/live/smil:rynek.smil/playlist.m3u8

**Comment by andrzej33113** [comment]
> Jak widzę wideo bazowe 3.1, ale lista odtwarzania jest nadal niepoprawna
> 
> # EXTM3U
> # EXT-X-VERSION: 3
> # EXT-X-STREAM-INF: BANDWIDTH = 4325583, CODECS = "avc1.674200", RESOLUTION = 1280x720
> chunklist_w475716430.m3u8
> 
> Spróbuj dodać plik SMIL (rynek.smil) z poprawkami informacji o kodekach do katalogu zawartości aplikacji
> / usr / local / WowzaStreamingEngine / content / live dla aplikacji „na żywo”
> 
> ```
> <? Wersja XML = Kodowanie „ 1.0 ” = „ UTF-8 ” ?>
> < smil  title = " Rynek Cam SMIL " >
> < głowa > </ głowa >
> < ciało >
>     < przełącznik >
>         < video  src = " rynek_imielin.stream "  system-bitrate = " 4300000 "  width = " 1920 "  height = " 1080 "  title = " Rynek Camera " >
>             < nazwa parametru  = „ videoBitrate ” wartość = „ 4300000 ” valueetype = „ data ” />  
>             < nazwa parametru  = " videoCodecId " wartość = " avc1.64002A " valueetype = " data " />  
>           </ wideo >
>      </ switch >
> </ body >
> </ smil >
> ```
> 
> I użyj nowego adresu URL z smil
> 
> http://streaming.e-sbl.net:1935/live/smil:rynek.smil/playlist.m3u8
> 
> W moim przykładowym obrazie bitrate 4300000, rozdzielczość 1920x1080, kodek - H264 High 4.2

It's work!!!!
Thank u very much, how can i repay now? :D

**Comment by andrzej33113** [comment]
> How I see baseline 3.1 video but playlist still wrong
> 
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-STREAM-INF:BANDWIDTH=4325583,CODECS="avc1.674200",RESOLUTION=1280x720
> chunklist_w475716430.m3u8
> 
> Try to add SMIL file (rynek.smil) with corrects codecs info to you apllication content directory
> /usr/local/WowzaStreamingEngine/content/live by default for app "live"
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <smil title="Rynek Cam SMIL">
> <head></head>
> <body>
>     <switch>
>         <video src="rynek_imielin.stream" system-bitrate="4300000" width="1920" height="1080" title="Rynek Camera">
>             <param name="videoBitrate" value="4300000" valuetype="data"/>
>             <param name="videoCodecId" value="avc1.64002A" valuetype="data"/>
>           </video>
>      </switch>
> </body>
> </smil>
> ```
> 
> And use new URL with smil
> 
> http://streaming.e-sbl.net:1935/live/smil:rynek.smil/playlist.m3u8
> 
> In my sample video bitrate 4300000 , resolution 1920x1080, codec - H264 High 4.2

It works!!!!!
Thank u very much, how can i repay now? :D
