### ISSUE TITLE
HLS less then 2 min video seeking not fill up

### ISSUE THREAD

**Issue by pandiyaavps** [clappr/clappr#1916]
For HLS video less than 2 min duration, media control buffer UI issue faced, could you help me.

**Comment by pandiyaavps** [comment]
![RapL (23)](https://user-images.githubusercontent.com/31888700/78003841-eb487f00-7356-11ea-9139-9cb0cda6a378.png)

Video buffered fully but seeking stop

**Comment by chriswiggins** [comment]
Do you have an ENDLIST tag in your m3u8?

**Comment by pandiyaavps** [comment]
> Do you have an ENDLIST tag in your m3u8?

yes i got ENDLIST tag like this.
![Screenshot from 2020-04-06 12-52-47 png  1225×698 ](https://user-images.githubusercontent.com/31888700/78540269-889d2a80-7811-11ea-813f-631b8b4f552a.png)

**Comment by pandiyaavps** [comment]
Could you help me here

**Comment by chriswiggins** [comment]
Can you host the player and m3u8 publicly somewhere please so we can see it and diagnose?
