### ISSUE TITLE
The player in ipad HLS mode

### ISSUE THREAD

**Issue by yacall** [clappr/clappr#1917]
The player on ipad in HLS mode is not controllable. Actually once you touch the player for fullsscreen or... it pauses the video or plays it

**Comment by kslimani** [comment]
It is not a bug, but an intended feature : if you touch/tap the player it play/stop the video, if you double-touch/tap it toggle to fullscreen.

**Comment by joaopaulovieira** [comment]
Closing this issue because as @kslimani  said, this is not a bug but the expected behavior
