### ISSUE TITLE
Help !!! How to change color to a CLAPPR player?

### ISSUE THREAD

**Issue by C-Mix** [clappr/clappr#1920]
Someone can help me change the color of my CLAPPR player, I’d appreciate it infinitely.

**Comment by me-vlad** [comment]
https://github.com/clappr/clappr/wiki/Embed-Parameters

you can customize control bar colors adding the mediacontrol hash, eg: 
```mediacontrol: {seekbar: "#E113D3", buttons: "#66B2FF"}```

**Comment by C-Mix** [comment]
Thanks for your help friend, I already apply the code and I work perfectly, another question as I can do so that in my player where it says LIVE I can add another text for example that says in this way: LIVE - MEGATV. That is to say that when playing the file at the bottom leave the way I just mentioned. Thank you in advance for your answer. Blessings!!

**Comment by me-vlad** [comment]
https://github.com/clappr/clappr/blob/dev/src/plugins/strings.js

Add to your player optons something like this:

```
    strings: {
      'en-US': {
        'live': 'live-megatv',
        'back_to_live': 'back to live',
        'disabled': 'Disabled',
        'playback_not_supported': 'Your browser does not support the playback of this video. Please try using a different browser.',
        'default_error_title': 'Could not play video.',
        'default_error_message': 'There was a problem trying to load the video.',
      }   
    },  
```

**Comment by C-Mix** [comment]
Thanks friend, I tried the code you sent me but I couldn’t make it work, I will send you the code of my player so that you can please guide me where the code you provided me would go. I also have another problem when I am playing something and for example I stop the reproduction and then I want it to resume but you can no longer stay black and the controls disappear, help me also with that please. I invite you to try my player and realize the problem I mentioned. I send you my player code below:

<head>
  <link rel="stylesheet" href="styles.css">
    <script src="//cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
</head>

 <body>
  <div id="player"></div>
   <center>  <script>
        var player = new Clappr.Player({
            source: "http://live-edge01.telecentro.net.ar/live/musictop.smil/.m3u8", 
                                parentId: '#player',
                                autoPlay: 'true',
                                mediacontrol: {seekbar: "#00FFFB", buttons: "#00FFFB"},
                                hlsjsConfig: {liveSyncDuration: 60},
                                disableVideoTagContextMenu: 'true',
                                width: '730px',
                                height: '400px' });
    </script> </center>
</body>

**Comment by C-Mix** [comment]
Thanks friend, I tried the code you sent me but I couldn’t make it work, I will send you the code of my player so that you can please guide me where the code you provided me would go. I also have another problem when I am playing something and for example I stop the playback and then I want it to resume, it is no longer possible, the controls disappear, help me also with that please. I invite you to try my player to see the problem I mentioned. Here I leave the code of my player:

```
<head>
  <link rel="stylesheet" href="styles.css">
    <script src="//cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
</head>

 <body>
  <div id="player"></div>
   <center>  <script>
        var player = new Clappr.Player({
            source: "http://live-edge01.telecentro.net.ar/live/musictop.smil/.m3u8", 
                                parentId: '#player',
                                autoPlay: 'true',
                                mediacontrol: {seekbar: "#00FFFB", buttons: "#00FFFB"},
                                hlsjsConfig: {liveSyncDuration: 60},
                                disableVideoTagContextMenu: 'true',
                                width: '730px',
                                height: '400px' });
    </script> </center>
</body>
```

**Comment by C-Mix** [comment]
A thousand Thanks friend, you have helped me a lot, I thank you of all heart, I wish you the greatest success and God bless you.
