### ISSUE TITLE
Stop the video in the background (php-ajax)

### ISSUE THREAD

**Issue by volkankoc** [clappr/clappr#1921]
I pull the video address and play it with php-ajax. When I shoot a new video again, it keeps playing in the background. How can I stop this?
Note: Videos need to play automatically when called.

**Comment by volkankoc** [comment]
please help

**Comment by luzeduardo** [comment]
Hi @volkankoc. Could you share a snippet of code you're using to handle it?

**Comment by volkankoc** [comment]
> Hi @volkankoc. Could you share a snippet of code you're using to handle it?

this player code
`  for ($i=0; $i<count($link) ; $i++): ?>    
            <script>
                var playerElement = document.getElementById("<?php echo "player".$i ?>");
                var player = new Clappr.Player({
                  source: '<?php echo $link[$i]['address']?>',
                  mute: true,
                  width:'300',
                  height:'200',
                  autoPlay: true
                });
                player.attachTo(playerElement);
            </script>   
          <?php endfor?>`

Example filtre link bottom
https://www.w3schools.com/howto/howto_js_filter_elements.asp

There are multiple players on the page. I group in the form of an example on this page. Videos play automatically. The videos that remain in the background continue to play because I chose them without refreshing the page. My wish is to stop videos in the background every time I make a selection here.
thank u.

**Comment by joaopaulovieira** [comment]
Hi @volkankoc, just to confirm if I understand right: It's to autoplay the first instance and stops the current instance playing when other Clappr instance starts? If yes, you can do something like this:

``` javascript
var playerElement = document.getElementById("player-wrapper");

var playerOptions = {
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  height: 180,
  width: 320,
}

var firstPlayer = new Clappr.Player({
  ...playerOptions,
  autoPlay: true,
  events:{
    onPlay:() => allPlayers.forEach(instance => instance !== firstPlayer && instance.pause())
  }
});

var secondPlayer = new Clappr.Player({
  ...playerOptions,
  events:{
    onPlay:() => allPlayers.forEach(instance => instance !== secondPlayer && instance.pause())
  }
});

var allPlayers = [firstPlayer, secondPlayer]

firstPlayer.attachTo(playerElement);
secondPlayer.attachTo(playerElement);
```

You can run this code here: http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgYXV0b1BsYXk6IHRydWUsCiAgaGVpZ2h0OiAxODAsCiAgd2lkdGg6IDMyMCwKICBldmVudHM6ewogICAgb25QbGF5IDpmdW5jdGlvbigpIHsKICAgICAgYWxsUGxheWVycy5mb3JFYWNoKGZ1bmN0aW9uKHBsYXllckluc3RhbmNlKSB7CiAgICAgICAgcGxheWVyICE9PSBwbGF5ZXJJbnN0YW5jZSAmJiBwbGF5ZXJJbnN0YW5jZS5zdG9wKCkKICAgICAgfSkKICAgIH0KICB9Cn0pOwoKdmFyIHBsYXllcjIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgaGVpZ2h0OiAxODAsCiAgd2lkdGg6IDMyMCwKICAgIGV2ZW50czp7CiAgICBvblBsYXkgOmZ1bmN0aW9uKCkgewogICAgICBhbGxQbGF5ZXJzLmZvckVhY2goZnVuY3Rpb24ocGxheWVySW5zdGFuY2UpIHsKICAgICAgICBwbGF5ZXIyICE9PSBwbGF5ZXJJbnN0YW5jZSAmJiBwbGF5ZXJJbnN0YW5jZS5zdG9wKCkKICAgICAgfSkKICAgIH0KICB9Cn0pOwoKdmFyIGFsbFBsYXllcnMgPSBbcGxheWVyLCBwbGF5ZXIyXQoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwpwbGF5ZXIyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=

But, even it's not what I described, note that Clappr player instances are independent of each other. So, you need to handle each one manually when one action affects more than one Clappr instance.

**Comment by volkankoc** [comment]
> Hi @volkankoc, just to confirm if I understand right: It's to autoplay the first instance and stops the current instance playing when other Clappr instance starts? If yes, you can do something like this:
> 
> ```js
> var playerElement = document.getElementById("player-wrapper");
> 
> var playerOptions = {
>   source: 'http://clappr.io/highline.mp4',
>   poster: 'http://clappr.io/poster.png',
>   height: 180,
>   width: 320,
> }
> 
> var firstPlayer = new Clappr.Player({
>   ...playerOptions,
>   autoPlay: true,
>   events:{
>     onPlay:() => allPlayers.forEach(instance => instance !== firstPlayer && instance.pause())
>   }
> });
> 
> var secondPlayer = new Clappr.Player({
>   ...playerOptions,
>   events:{
>     onPlay:() => allPlayers.forEach(instance => instance !== secondPlayer && instance.pause())
>   }
> });
> 
> var allPlayers = [firstPlayer, secondPlayer]
> 
> firstPlayer.attachTo(playerElement);
> secondPlayer.attachTo(playerElement);
> ```
> 
> You can run this code here: http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgYXV0b1BsYXk6IHRydWUsCiAgaGVpZ2h0OiAxODAsCiAgd2lkdGg6IDMyMCwKICBldmVudHM6ewogICAgb25QbGF5IDpmdW5jdGlvbigpIHsKICAgICAgYWxsUGxheWVycy5mb3JFYWNoKGZ1bmN0aW9uKHBsYXllckluc3RhbmNlKSB7CiAgICAgICAgcGxheWVyICE9PSBwbGF5ZXJJbnN0YW5jZSAmJiBwbGF5ZXJJbnN0YW5jZS5zdG9wKCkKICAgICAgfSkKICAgIH0KICB9Cn0pOwoKdmFyIHBsYXllcjIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgaGVpZ2h0OiAxODAsCiAgd2lkdGg6IDMyMCwKICAgIGV2ZW50czp7CiAgICBvblBsYXkgOmZ1bmN0aW9uKCkgewogICAgICBhbGxQbGF5ZXJzLmZvckVhY2goZnVuY3Rpb24ocGxheWVySW5zdGFuY2UpIHsKICAgICAgICBwbGF5ZXIyICE9PSBwbGF5ZXJJbnN0YW5jZSAmJiBwbGF5ZXJJbnN0YW5jZS5zdG9wKCkKICAgICAgfSkKICAgIH0KICB9Cn0pOwoKdmFyIGFsbFBsYXllcnMgPSBbcGxheWVyLCBwbGF5ZXIyXQoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwpwbGF5ZXIyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=
> 
> But, even it's not what I described, note that Clappr player instances are independent of each other. So, you need to handle each one manually when one action affects more than one Clappr instance.


Thanks for the answer, but there was no solution for me. I have a lot of players called my player. How can I control them this way. also the name of all player

**Comment by joaopaulovieira** [comment]
Seems you need to create unique instances when adding one player with your script. After that, you can manage each one or aggregate in one dictionary as well.
