### ISSUE TITLE
Webpage integration

### ISSUE THREAD

**Issue by natzakaria** [clappr/clappr#1922]
Am new to clappr 
I used the simple code on the clappr.io to embed my wowza stream using clappr as the player in my site but not successful.
Tried http, rtmp and rtsp to no avail.
Please advise

Code from the main site:

<head>
  <script type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js">
  </script>
</head>
            
            
<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({source: "http://your.video/here.mp4", parentId: "#player"});
  </script>
</body>

**Comment by leandromoreira** [comment]
hi, what's the error? (did you notice something on the console or network tabs?)

**Comment by natzakaria** [comment]
Hi
I get this error although it plays perfectly fine on VLC.

![image](https://user-images.githubusercontent.com/65059352/81472946-e87e5b00-922d-11ea-8ac0-37830c42778e.png)

**Comment by leandromoreira** [comment]
You can read https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues but I think you're facing CORS issue, it's explained at the link above as well.

**Comment by natzakaria** [comment]
I tried and the results below:
Now what do I need to do and what do I add to the website?

CDN - hls:networkError_manifestLoadError
Cors headers - don’t know how to - unfortunately I am not a coder
his.js.demo page : Cannot load http://natz3.asuscomm.com:1935/live/myStream/playlist.m3u8HTTP response code:0 This might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension
44.77 | A network error occured

**flashls. demo page - SUCCESS**

**Comment by natzakaria** [comment]
I tried this - while it shows on my webpage I still cant play the my m3u8 stream from WOWZA Streaming Engine - please advise

<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<div id="oper"></div>
<div id="vid"></div>
<script>
 player = new Clappr.Player({
 source: "PASTE YOUR M3U8 LINK HERE",
 mimeType: "application/x-mpegURL",
 autoPlay: true, 
 height: "100%",
 width: "100%",
 plugins: {"core": [LevelSelector]}, 
 parentId: "#vid"});
</script>
