### ISSUE TITLE
Which version of hls.js is used in clappr?

### ISSUE THREAD

**Issue by ampersand83** [clappr/clappr#1925]
**What do you want to do with Clappr?**
We are building a player to play the hls livestream of a radiostation. (https://hlshr3.akamaized.net/hls/live/2016536/hr3/master.m3u8)
Unfortunately the player crashes very often with an "hlsjs: could not recover from error" message. 
The corresponding error message from hls.js is : "RangeError: source array is too long".
Sometimes the stream runs for hours without a single crash and thenn suddenly it crashes every few minutes.

**What have you tried so far?**
We have tried to figure out the cause of this error by running that exact stream on the hls demo page (https://hls-js-latest.netlify.app/demo/). Other than in clappr no errors have appeared so far. However when switching the hls.js version on the hls.js demopage to v0.12.1 we also get unrecoverable errors of the player. 
Our question is now which hls.js version does the clappr player use? Is it a version close to v0.12.1? From our point of view the hls.js developers must have implemented some improvements in the latest versions that make the unrecoverable errors while playing our stream disappear. Any chance that you could update the hls.js version that clappr uses? If that's not easily possible, can you give us a hint on how we could build our own clappr fork with a newer hls.js version. We really love your player and all the features it has but with all those sudden crashes it is barely not usable.

**Comment by leandromoreira** [comment]
We use 0.12.2 https://github.com/clappr/clappr/blob/dev/package.json#L52 being the last stable 0.13.2 https://github.com/video-dev/hls.js/releases

@joaopaulovieira @towerz @jhonatangomes is there any reason we're at `0.12.2`?

**Comment by jhonatangomes** [comment]
I don't know any reason for not upgrading. I think we can go to the latest version.

**Comment by ampersand83** [comment]
Hi @jhonatangomes and @leandromoreira. 
Thank you for your quick reply. I'd really appreciate it if you'll upgrade hls.js to the latest version..

**Comment by ampersand83** [comment]
Hi @jhonatangomes and @leandromoreira, any updates on this issue?

**Comment by pedrofurtado** [comment]
Any news?

**Comment by leandromoreira** [comment]
@joaopaulovieira

**Comment by pedrofurtado** [comment]
we are also in trouble because of network errors in hls, that crashes clappr

**Comment by gladissoncaetano** [comment]
I am also having these same problems as mentioned by Pedro Furtado. They could update the hls js library used by Clappr as soon as possible.

**Comment by WillRadi** [comment]
Update hls js would be very helpful, to me! I'm with the same issue crashing clappr

@jhonatangomes @leandromoreira @towerz

**Comment by joaopaulovieira** [comment]
Hi everyone! We released the version [0.3.13](https://github.com/clappr/clappr/releases/tag/0.3.13) with the latest version (0.13.2) of hls.js.

**Comment by Niko78** [comment]
... and hls.js is now in 0.14 ;-)

**Comment by joaopaulovieira** [comment]
In the current Clappr architecture, we have separated hlsjs-playback to its own repository (https://github.com/clappr/hlsjs-playback/). Now, issues/questions related to this playback can be opened in this repository (:

For this specific case of updating hls.js, both in the previous version and in the current version of Clappr and hlsjs-playback it's possible to use only the playback code and import the `hls.js` module separately. With that, anyone can use the version of `hls.js` they want without relying on a new release of hlsjs-playback.

An example of using this version of hlsjs-playback (hlsjs-playback.external.js) is in the project repository to run locally: https://github.com/clappr/hlsjs-playback/blob/master/public/index. hlsjs-external.html

We will update the version of `hls.js` whenever possible for the` hlsjs-playback.js` but the `hlsjs-playback.external.js` already serves people who do not want to wait for this release.

I think it already helps anyone who doesn't want to wait for our test/release flow.
