### ISSUE TITLE
Stream working only with Clappr extension for Chrome

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1926]
Using this Chrome extension that uses Clappr: https://chrome.google.com/webstore/detail/reproductor-m3u8-hls-play/lcipembjfkmeggpihdpdgnjildgniffl

... I can play this stream: http://livecdn1.news.cn/cnccn/manifest.m3u8

Why can't I play the same stream using Clappr directly?

**Comment by kslimani** [comment]
Playing an http stream in the browser is not the same as in and extension or application scope/environnement.

There are security policies which apply. for example [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), or attempting to play an http source in an https page, etc...
