### ISSUE TITLE
How to remove play icon?

### ISSUE THREAD

**Issue by shanka12** [clappr/clappr#1927]
How to remove this play icon or replace different play icon?
![Screenshot 2020-06-05 at 14 49 52](https://user-images.githubusercontent.com/8470380/83859925-3fe3ee00-a73c-11ea-915e-4a398e7266aa.png)

**Comment by ioppermann** [comment]
The play icon is rendered in the `poster`-plugin: https://github.com/clappr/clappr/blob/dev/src/plugins/poster/poster.js (see the `render()` method at the end of the file).

You might modify it such that it accepts a different SVG for the play button via its configuration.

Currently it just uses the SVG from https://github.com/clappr/clappr/blob/dev/src/icons/01-play.svg

If you change the SVG here it will also change the play icon that is used in the media control at the bottom.

**Comment by shanka12** [comment]
Great. Thank you @ioppermann

**Comment by JeppeTh** [comment]
This seems to work as well
`player.getPlugin('poster').$playWrapper.hide()`
Or playing with css settings or similar.

**Comment by sktechnology** [comment]
it possible to change the play logo by image ?
