### ISSUE TITLE
'media-control-notransition' class works wrong

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1928]
Starting with commit 41b2897d2169e8c799871977d9d045abc05379cd, the MediaControl setSeekPercentage method does it wrong removing the 'media-control-notransion' class.
This negatively affects the experience of dragging the seek-bar scrubber.
Adding this class in the rendering method is also useless.

**Comment by joaopaulovieira** [comment]
Hi, @sapolio. Can you please open this issue on the clappr-plugins repo? This helps a lot with the bug control between the projects inside the Clappr org.
