### ISSUE TITLE
How can I update the video source without the viewer noticing?

### ISSUE THREAD

**Issue by Raino** [clappr/clappr#1929]
Hello! 
I'm showing a stream of .m3u8. The source of my thread has a lifetime, after which the link becomes "outdated" and it is regenerated. 
**I need to update it in the player, so that it is not noticeable in the player (the video is not paused, collapsed, or hung). My new link is stored in the _strlink_ variable when calling the _genlink_ function** 
My source link looks like this: 
`https://xxx.xx/xxxxxx/index.m3u8?hash=lIANSfoVHU79SdVJ7UkOVw&expires=1591634308`
The hash and expires variables are updated every 10 seconds to maintain thread validity

I found this on GitHub https://github.com/clappr/clappr/issues/1453. 
It says that when you change the video source in this way, the player should not be destroyed, but in practice, the player stops altogether or just restarts. 
I also found this code https://github.com/clappr/clappr/issues/1467, 
but it didn't work for me, the player still gives an error that the stream is unavailable. I tried to take the code from the last link outside of the player block and the video was shown, but with the help of the player. Namely, the player stops anyway, the error "Could not play video" appears and after a while the video starts playing, but the error remains. 
It seems to me that it is possible to do what I want, just a question of how. 
Can you tell me how to solve this problem? 
I will be very grateful to you!

**Comment by Raino** [comment]
@leandromoreira Can you help me, please?

**Comment by leandromoreira** [comment]
@towerz @jhonatangomes @joaopaulovieira are way better than I to help you with that... but I think you can rely on the [error mechanism](https://github.com/clappr/clappr/blob/dev/doc/PLAYER_ERRORS.md) to achieve that, it'll be transparent but not smooth.

**Comment by Raino** [comment]
@leandromoreira I tried to use the onError event and change the source of the player using it, but unfortunately nothing happened

**Comment by leandromoreira** [comment]
@kslimani answered something around that here https://github.com/clappr/clappr/issues/1889

```javascript
// [...]
player.configure({
  source: 'another-url',
  // ...
});
```

**Comment by Raino** [comment]
@leandromoreira I tried using `configure` before I wrote my message (https://github.com/clappr/clappr/issues/1453), but unfortunately when using it, the player stops. The user has to manually launch it.

**Comment by towerz** [comment]
@Raino have you tried [this approach](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9pbnZhbGlkLmRvbWFpbi92aWRlby5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwLAogIGV2ZW50czogewogICAgb25FcnJvcjogKCkgPT4gcGxheWVyLmNvbmZpZ3VyZSh7CiAgICAgIHNvdXJjZTogJ2h0dHA6Ly9jbGFwcHIuaW8vaGlnaGxpbmUubXA0JywKICAgICAgYXV0b1BsYXk6IHRydWUsCiAgICB9KQogIH0KfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cg==)? It's similar to what @kslimani and @leandromoreira suggested.

This approach could also work with [in-stream errors](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly90ZXN0LXN0cmVhbXMubXV4LmRldi94MzZ4aHp6L3gzNnhoenoubTN1OCcsCiAgcG9zdGVyOiAnaHR0cDovL2NsYXBwci5pby9wb3N0ZXIucG5nJywKICBtdXRlOiB0cnVlLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAsCiAgZXZlbnRzOiB7CiAgICBvbkVycm9yOiAoKSA9PiBwbGF5ZXIuY29uZmlndXJlKHsKICAgICAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogICAgICBhdXRvUGxheTogdHJ1ZSwKICAgIH0pLAogICAgb25QbGF5OiAoKSA9PiBzZXRUaW1lb3V0KAogICAgICAoKSA9PiBwbGF5ZXIuY29yZS5hY3RpdmVDb250YWluZXIudHJpZ2dlcihDbGFwcHIuRXZlbnRzLkNPTlRBSU5FUl9FUlJPUiksIAogICAgICAzMDAwCiAgICApLAogIH0KfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cg==).

**Comment by Raino** [comment]
@towerz I tried this method. In the console, I saw that a few seconds before the onError event appeared, the console already displayed that the requested link was unavailable. As a result, updating the link took a very long time and it is very noticeable to the user. Maybe you can act ahead of time to replace the link before the error appears, so that the user's player doesn't hang up?

**Comment by kslimani** [comment]
AFAIK, with default Clappr HLS playback, you cannot change the source manifest "on-the-fly" __without the user noticing__.

And even if you extend the default HLS playback to change internal error mechanisms, it may not work on all browser/device. _(ie: device native html5)_

You can also attempt to reduce error behaviours using [fine tuning](https://github.com/video-dev/hls.js/blob/master/docs/API.md#fine-tuning). _(set in [hls playback](https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md#hls-configuration) configuration option)_

You __may__ be able to achieve this from server side using [Redundant/Failover Playlists](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW22).

Another approach could be a user session pool mechanism, for example, passing a user session id in stream url. _(but this is out of Clappr scope)_

**Comment by Raino** [comment]
@kslimani What kind of fine settings do you recommend that I set to solve my question?

**Comment by phillipseamore** [comment]
This really sounds like an you'd rather want AES encryption and key delivery.  All your segments and playlists would then also be cacheable.

**Comment by kslimani** [comment]
@Raino look at the options with "timeout" or "retry" sufix _(if you want to reduce when playback will trigger an error)_. Anyway, i don't think it will "solve" your issue.

**Comment by Raino** [comment]
@kslimani Strange, I heard that someone managed to work with the same links as me through clappr and just unnoticed by the user

**Comment by Raino** [comment]
@kslimani @towerz I found one library for an open videojs player https://github.com/videojs/http-streaming It allows you to add attributes to each package. 
Maybe I just don't know and you have some kind of analog for clappr? 
If not, then maybe this is a good idea for the future development of the clappr player?
