### ISSUE TITLE
I want to pause the video on specific condition...

### ISSUE THREAD

**Issue by amitgoyalliet** [clappr/clappr#1933]
I am new in clappr. I just want to pause/play the video on specific condition without timeout condition.
I used this code which I check on other blogs but I don't want any timeout:

 player.on(Clappr.Events.PLAYER_PLAY, videoPlay)
  function videoPlay(e) {
            console.log("videoPlay");
            setTimeout(player.pause.bind(player), 10000);
            
        };

**Comment by kslimani** [comment]
I am not sure to understand what you are you trying to achieve.

The player instance have `pause` method to pause the player.

```javascript
var player = new Clappr.player({ /* some configuration */ });

// to pause the player call pause method
if (/* some condition*/) {
  player.pause();
}
```

**Comment by amitgoyalliet** [comment]
> ```js
> player.pause();
> ```

Can you let me know how to set player video current time by zero (0)?

**Comment by kslimani** [comment]
```javascript
// [...]
player.seek(0);
```
