### ISSUE TITLE
Refresh PHP from Clappr?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1935]
I have a m3u8 that stops every 1 minute.
I'd like to refresh the PHP every 55 seconds (when Clappr detects the error)
The only option I found is by using: `<meta http-equiv="refresh" content="55">`
However it disables the full screen every time it refreshes.

Any idea?

**Comment by kslimani** [comment]
When a fatal error has occured the player is automatically stopped, which leave the fullscreen mode.

You can load another source using the player error event. More details [here](https://github.com/clappr/clappr/blob/dev/doc/PLAYER_ERRORS.md).

**Comment by hijuuijj** [comment]
Thank you. It works with this code:

`events: {onError: function(e) {window.location.replace("file.php");}},`

I have disabled the error messages with `disableErrorScreen: true,` however still showing the play icon (triangle) for a few moments. How to disable that icon?

Is there a way to keep the last frame of the video until it loads again?

**Comment by kslimani** [comment]
Just disable the `poster` plugin like you already did [here](https://github.com/clappr/clappr/issues/1818#issuecomment-506593519) with click to play plugin.

**Comment by hijuuijj** [comment]
Hi kslimani,

Still showing the icon before loading PHP https://i.ibb.co/0yX5Y5G/triangle.png

`Events: {onReady: function() {var plugin = this.getPlugin('click_to_pause'); plugin && plugin.disable();},},`

I repeat the question. Is there a way to keep the last frame of the video until it loads again?

Thank you for your patience.

**Comment by kslimani** [comment]
In your provided example, you disabled the 'click_to_pause' plugin;
But i suggested you disable the __poster__ plugin. ie: `getPlugin('poster')`.

**Comment by hijuuijj** [comment]
I copied [that](https://github.com/clappr/clappr/issues/1818#issuecomment-506593519) code from [your](https://github.com/clappr/clappr/issues/1818#issuecomment-506439680) code, a little above.

Please could you put the code to remove the "triangle"? :)

**Comment by leandromoreira** [comment]
I think you can try to solve some things by yoursself.

**Comment by hijuuijj** [comment]
I wasn't asking for an extensive and complex code, just a little one-line help.
Regards.
