### ISSUE TITLE
autoPlay is not working in React component ?

### ISSUE THREAD

**Issue by Dastnbek** [clappr/clappr#1939]
**Browser**: Chrome latest version
**OS**: Windows 10
**Clappr**: Version**: 0.3.13
```
import React, { useEffect } from "react";
import Clappr from "clappr";

Actually it is not working if I refresh the page.

export const ClapprPlayer = (props) => {
  const { id, source } = props;
  useEffect(() => {
    let player = null;
    player = new Clappr.Player({
      parentId: `#${id}`,
      source: source,
      autoPlay: true,
      width: "100%",
      height: "300px",
    });
    return () => {
      player.destroy();
      player = null;
    };
  }, []);

  return (
      <div id={id} ></div>
  );
};
```
And then in main file
```
import { ClapprPlayer } from "./components/ClapperPlayer";
 
<ClapprPlayer id="video1" source="http://1.1.1.1/cam1/index.m3u8"/>
 
```

**Comment by banagale** [comment]
I also am seeing that `autoplay: true` has no effect on a react embedded player.

In my case I'm using it in an effect hook.

I worked around this by just doing a `player.play()` immediately after `let player = new Clappr.Player(options);`

**Comment by leticiafernandes** [comment]
Hi @Dastnbek. Seems like the problem you're reporting is related to [this PR](https://github.com/clappr/clappr/pull/2014) proposal. May you check, please?
