### ISSUE TITLE
HLS livestream failover with event/error when chunklist stalls

### ISSUE THREAD

**Issue by sphinx33** [clappr/clappr#1942]
**What do you want to do with Clappr?**
I'd like to programmatically switch the (hls live) source of the player, as soon as the chunklist doesn't return new segments for a certain amount of time.

In detail: After I stop my encoder (or it loses connection), Wowza Streaming Engine delivers the "last" chunklist for some time before it gets removed and the player triggers an error (404). There is no ENDLIST tag indicating, that the stream stopped. I'd like to have the player fire an event or error, when the playhead approaches the end of the available data and no new segments appear in the chunklist for a certain amount of time. Then it would be possible to load another source before the player starts to buffer.

**What have you tried so far?**
Handle the onError event: It fires not until Wowza drops the chunklist and several (player-sided) retries (~60 seconds buffering)
Lowering the hls.js levelLoadingTimeOut and levelLoadingMaxRetry settings (15-20 seconds buffering until onError fires)
Setting up a redundant playlist as specified in the hls specs was not successful, because the timestamps of the two independent sources can not be synchronized.

I noticed, that the interval between fetching the chunklists shrinks, as the playhead approaches the last segment. So some logic has to happen there already. However, my skills won't let me get further and I'm hoping to find help this way.

Thank you in advance and all the best,
Tobias

**Comment by asheroto** [comment]
I am interested in this, too.  If I skip around 5+ times on an HLS stream the chunklist seems to fail.  Need it to reload the source file when this happens.

Thanks for details @sphinx33

**Comment by asheroto** [comment]
@sphinx33 , interested to see if version 0.4.0 works for you.  Try using it instead of the one through jsdelivr cdn.  I'm not a dev for clappr, just another user.
