### ISSUE TITLE
Clappr Vod Problem on Different Servers

### ISSUE THREAD

**Issue by SxtBox** [clappr/clappr#1943]
Hello,
I have a problem with the player for vod play
or the player has a problem or I did not make the settings correct

the problem is, in some servers work mp4 and some not

TEST Player https://demo.kodi.al/Streaming/AIO_Vendors/Test_Embed_Video_Player_API/

Clappr Problem [VOD]
http://62.171.188.48/test_vod/E_Type_Here_I_Go_Again.mp4
http://62.171.188.48/test_vod/E-Type%20-%20Here%20I%20Go%20Again.mp4

Clappr OK [VOD]
https://demo.kodi.al/Streaming/AIO_Vendors/Test_Embed_Video_Player_API/test_vod/E_Type_Here_I_Go_Again.mp4
https://demo.kodi.al/Streaming/AIO_Vendors/Test_Embed_Video_Player_API/test_vod/E-Type%20-%20Here%20I%20Go%20Again.mp4

Vodeo-js [OK] with same video
http://albdroid.al/live-tv/test-mp4-http6217118848test_vode_type_here_i_go_againmp4.html

    Player CODE
    <head>
    
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.js"></script>
    
    </head>

    <div id="tv_player"></div>
    <script type='text/javascript'>
    var player = new Clappr.Player({
	sources: ["https://demo.kodi.al/Streaming/AIO_Vendors/Test_Embed_Video_Player_API/test_vod/E-Type%20-%20Here%20I%20Go%20Again.mp4"],
	// sources: ["http://62.171.188.48/test_vod/E-Type%20-%20Here%20I%20Go%20Again.mp4"], // Don't Work
	// type: [type="video/mp4"], // NO ACTIVE
	//sources: ["MP4 SOURCE"],
       height: "100%",
       width: "100%",
	// poster: "https://png.kodi.al/tv/albdroid/black.png",
	// watermark: "https://png.kodi.al/tv/albdroid/smart_x1.png", position: 'top-right',
	watermarkLink: "",
       autoPlay: true,
       mediacontrol: {seekbar: "#ccc", buttons: "#ccc"},
	title: 'Test Player',
       // subtitle: 'Test Subtitle',
       disableVideoTagContextMenu: true,
	parentId: "#tv_player",
	events: {
       onReady: function() {  },
	}

	,playback: {preload: 'metadata', playInline: true, recycleVideo: Clappr.Browser.isMobile, externalTracks: []}
	});

     </script>

**Comment by leandromoreira** [comment]
I went to the demo page and it seem that it's all working just fine:

http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovLzYyLjE3MS4xODguNDgvdGVzdF92b2QvRV9UeXBlX0hlcmVfSV9Hb19BZ2Fpbi5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=



http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovLzYyLjE3MS4xODguNDgvdGVzdF92b2QvRS1UeXBlJTIwLSUyMEhlcmUlMjBJJTIwR28lMjBBZ2Fpbi5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=

**Comment by SxtBox** [comment]
i see it works very well
the problem is that the player does not work in HTTPS Protocol
I tried it on http and it works
if you have the player at https also get from https server to http vod server
the output is https://url.mp4
[https://ibb.co/zRYtqjc](url)

**Comment by leandromoreira** [comment]
@SxtBox which url will cause problem when used as HTTPS?

**Comment by SxtBox** [comment]
if player is in https domain
see the difference

default code from your player
http http://albdroid.al/test_vod/
https https://demo.kodi.al/Streaming/AIO_Vendors/Test_Embed_Video_Player_API/test_vod/

**Comment by leandromoreira** [comment]
It's working BUT you might be facing [an mixed content issue](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content), this there's nothing to do with clappr. You can read about it on provided link.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/55913/87253421-5d9a2680-c451-11ea-9758-0c601201cd2e.png">

**Comment by SxtBox** [comment]
i will look into this problem, thank you very much for the time you lose with me.
