### ISSUE TITLE
How do you run the rebuilder

### ISSUE THREAD

**Issue by TroyDota** [clappr/clappr#1948]
**What do you want to do with Clappr?**
I want to rebuild with code ive changed for my use case.

**What have you tried so far?**
`npm i && npm run build`
https://pastebin.com/u8Lv7KFS

**Comment by joaopaulovieira** [comment]
Hi @TroyDota !

Apparently is one problem with one of dev dependencies. It's fixed now on the latest commit.

Can you try again with this fix?

Thanks!

**Comment by TroyDota** [comment]
:+1: thanks

**Comment by TroyDota** [comment]
@joaopaulovieira on an unrelated issue the builder did not build a min js?

**Comment by TroyDota** [comment]
Also when running the rebuilder it builds with changes i made in plugins but not changes i made in core?

**Comment by TroyDota** [comment]
![image](https://user-images.githubusercontent.com/49777269/89097538-15cb4700-d3e0-11ea-9275-a19606b83731.png)
it seems to build parts twice,

**Comment by TroyDota** [comment]
[clappr.js.zip](https://github.com/clappr/clappr/files/5010014/clappr.js.zip)
is what it compiled.

**Comment by joaopaulovieira** [comment]
I ran the build without changes and I cannot to reproduce your case. Did you check that your custom build is not actually inserting `HTML5Video` twice?
