### ISSUE TITLE
Autoplay problem.

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1949]
Hi!
I am trying to automatically play the HLS stream.
(version 0.2.97
autoPlay: true
mute: true)
Playback does not start automatically on android. But it starts well on the latest version of Clappr.
Please tell me what exactly is the difference so that I can come up with a workaround without switching to the new version?

**Comment by kslimani** [comment]
I think latest "autoplay" modifications for 0.2.x was [this PR](https://github.com/clappr/clappr/pull/1681/files) and [this PR](https://github.com/clappr/clappr/pull/1432/files). 
_(just did an autoplay keyword research in merged pull requests)_
