### ISSUE TITLE
How to upgrade the HLS.js version in Clappr 0.13.x?

### ISSUE THREAD

**Issue by pedrofurtado** [clappr/clappr#1952]
I need to upgrade the hls.js version used in latest clappr 0.13.x version. How can I do that?

**Comment by pedrofurtado** [comment]
@joaopaulovieira @leandromoreira @jhonatangomes If you guys could clarify how can I do this (the steps, I mean), it will be awesome 🎉 🤝

**Comment by pedrofurtado** [comment]
I think the steps is these below. Is that correct?

1 - Fork the repo
2 - Edit the file https://github.com/clappr/clappr/blob/0.3.13/package.json#L52, changing version of hls.js
3 - Edit the file https://github.com/clappr/clappr/blob/0.3.13/package.json#L3, changing version of clappr
4 - Run npm run release
5 - Use dist/clappr.js inside project

Right?

**Comment by kslimani** [comment]
To rebuild Clappr with latest hls.js version, clone Clappr repository and create a local branch using tag version (for example 0.3.13) :

```shell
git clone https://github.com/clappr/clappr.git
cd clappr
git checkout tags/0.3.13 -b 0.3.13
```

Then you can use `npm` or `yarn` to change hls.js dependency version. _(and install dev. dependencies)_

Finally you can use `npm run build` to compile unminified version, or `npm run release` to compile minified version.

**Comment by pedrofurtado** [comment]
@kslimani Thanks for feedback! I will test here these steps that you described 🎉
