### ISSUE TITLE
HLS stream stuck on loop loading fragment

### ISSUE THREAD

**Issue by asheroto** [clappr/clappr#1953]
**The Problem**:
When playing an HLS stream that has a minor issue (present in ffprobe), Clappr continues to try to load the same fragment over and over and does not move on.  It continues indefinitely.  It gets stuck on that fragment and doesn't move forward.

Is there a variable I'm missing on the config???

**Browser**: 
Chrome 84.0.8417.135

**OS**: 
Server 2019

**Clappr Version**: 
0.4,0

**Steps to reproduce**:
1.  See m3u8 file 1 below and try to play it with Clappr
2.  Skip forward, then skip back < 10 seconds, then forward, repeat a few times quickly until frozen (while video is playing)
3.  Stream is frozen, upon checking debug window the same fragment is stuck on a loop loading.....

![image](https://user-images.githubusercontent.com/49938263/90821690-eb8eea00-e2f8-11ea-8230-3fcca00d2e83.png)

I tried using the hlsjs-playback 0.4.1 as a plugin and got a slightly different error:

![image](https://user-images.githubusercontent.com/49938263/90822763-89cf7f80-e2fa-11ea-9103-3646965e1b6a.png)

**m3u8 file 1, **problem occurs with Clappr**, does **not** occur with VLC as network stream:**
https://asheroto.com/1396-5-1/1396-5-1.m3u8

here is the ffprobe output from one of the ts files from m3u8 file 1...
![image](https://user-images.githubusercontent.com/49938263/90833416-96110800-e30d-11ea-96c2-acfe6813ebf1.png)

**m3u8 file 2, problem does **not** occur with Clappr or VLC:**
https://asheroto.com/2190-1-4/2190-1-4.m3u8

and here is the ffprobe output from one of the ts files from m3u8 file 2....
![image](https://user-images.githubusercontent.com/49938263/90833474-b345d680-e30d-11ea-945e-23245d01f10d.png)

See m3u8 files for .ts files.

Note, both hosted on the same server, same everything, just different ts files.

Using clappr js config: https://gist.github.com/asheroto/7e393ce097420a3c1ffc798f65d1a450

For some reason it's stuck loading the same fragment over and over.  Sometimes the video is paused with the time moving, other times the time is not moving.  Again, it only seems to happen with with ts files that also have a minor warning in ffprobe.

**I need some type of setting that forces the loading of the fragment to give up and move on to the next ts file.....**

**Comment by asheroto** [comment]
**Update**

It's definitely because the stream had warnings such as

`start time for stream x is not set`

I know getting a more valid conversion is ideal, but is there any way I can detect that this loop is occurring and resume or reload the video?

**Comment by asheroto** [comment]
Bump

**Comment by asheroto** [comment]
In summary, how can I force Clappr to skip a fragment that it gets stuck on?  Or is this a bug that needs to be fixed internally?  I found that some streams have a bad fragment, I just need Clappr to skip over that instead of retrying dozens of times.  :-)

Thanks!

**Comment by leandromoreira** [comment]
@asheroto I don't think clappr can help you on this =( 

For error handling you can read https://github.com/clappr/clappr#how-to-handle-player-fatal-errors (there is a retry mechanims in there)

I think you're facing media/ingest/transcode issues (as stated by your ffmpe/ffprobe output) https://github.com/clappr/clappr#common-steps-to-verify-issues

**Comment by kslimani** [comment]
@asheroto : Clappr player internally use the hls.js library for hls playback.

Can you reproduce your issue on [hls.js demo page](https://hls-js.netlify.app/demo/) ?

If the is the case, you may want to report the issue on the [hls.js library repository](https://github.com/video-dev/hls.js).
