### ISSUE TITLE
How Can I Change the Height of the Media Controls?

### ISSUE THREAD

**Issue by asheroto** [clappr/clappr#1954]
**What do you want to do with Clappr?**
I want to make the media control bar slightly bigger so that when mobile users are tapping the full screen button, they don't accidentally skip to the end of the video (which I have done several times).  So I just need to raise the height of the media control by 20% or so to make the full screen button more accessible.

**What have you tried so far?**
Researched plugins, but I don't know if I need that or not?

Thanks!

**Comment by leandromoreira** [comment]
I think you can learn from previous issues like this specific one https://github.com/clappr/clappr/issues/1787 or  more https://github.com/clappr/clappr/issues?q=custom+media+controls
