### ISSUE TITLE
Write a proxy over Clappr player

### ISSUE THREAD

**Issue by Niharika098** [clappr/clappr#1958]
**What do you want to do with Clappr?**

Hi
I want to know what is the approach to write a proxy over clappr.

I am planning to implement a mid-stream CDN switcher to use the best CDN based on performance and for this, the approach I thought would be to intercept the request from clappr using a proxy, fetch the content from cdn of my choice and give the response back to clappr.

**What have you tried so far?**

I have done my research and came across 3 approaches to solve this problem online

1.Run a local http server on each client and change the url to clappr to point to the local http server and then do loadbalancing
2.Overwrite XMLHttpRequest
3.Use serviceworker

Would love to get your feedback on what would be an ideal approach or is there any other open source approach to solve this problem.

**Comment by phillipseamore** [comment]
1) Is the only logical solution and will work with any player.

**Comment by Niharika098** [comment]
Sorry for me being naive but how do I run a http server locally on the client side using plain javascript

Also can you kindly explain a bit about why you feel the other approaches are not logical. Since they tend to achieve the same thing as well.

**Comment by phillipseamore** [comment]
Sorry, read your post too fast! You certainly won't run it locally, you'd run it centrally.

**Comment by joaopaulovieira** [comment]
Hi @Niharika098, any Clappr component is possible to extend and add/modify what you want.

In your approach, your switcher returns the CDN endpoint to get the video source, right?

If yes, I think one plugin to do the request to your switcher and handle with sending the video source for the Playback resolves.

For this approach, you need:
* The `CDN Switcher Plugin` listen to one `play` event to init your flow;
* Do the request to get the video source 
* Send the video source to the `Playback`

The `Playback` needs to wait for the `CDN Switcher Plugin`, so you can extend the `Playback` you use to add this new logic.

**Comment by joaopaulovieira** [comment]
@Niharika098 The approach I commented on above is suitable for you?

Did you implement any other approach?
