### ISSUE TITLE
Safari through drawImage capture screenshots failed

### ISSUE THREAD

**Issue by colinox** [clappr/clappr#1959]
chrome、firefox through drawImage can get the screenshot,  Safari through drawImage capture screenshots failed! Please help to solve thank you

**Comment by joaopaulovieira** [comment]
Can you show what you trying to do with the drawImage and Clappr? You can use the clappr.io/demo to show (:

**Comment by joaopaulovieira** [comment]
Closing due to no response received. If there is anything new, you can open the issue again (:
