### ISSUE TITLE
Somebody forgot to update npm with 0.4.0.....

### ISSUE THREAD

**Issue by asheroto** [clappr/clappr#1960]
npm still has 0.3.13 as the latest version: https://www.npmjs.com/package/clappr
thus
jsdelivr.com still has 0.3.13.

me needs 0.4.0 on cdn plz!

👍 

Thanks guys!

**Comment by kslimani** [comment]
I think (but i may be wrong ?) that 0.4.x use a new package namespace : https://www.npmjs.com/package/@clappr/core

**Comment by asheroto** [comment]
Ahh that looks right.  Thanks!

**Comment by asheroto** [comment]
Reopened... srry... tested Clappr-core but it's truly only the core of Clappr.  I want the official release. :-D

**Comment by kslimani** [comment]
What do you mean by "only" ? this package is (to my knowledge) the official release for 0.4.x

Please note that several playback plugins have been splitted from core player; You need to also include them if required. (take a deeper look of the [readme file](https://github.com/clappr/clappr-core#plugins))

**Comment by kslimani** [comment]
For example, for HLS playback it should be something like :

```html
<html>
  <body>
    <head>
      <script src="https://cdn.jsdelivr.net/npm/clappr/core@latest/dist/clappr-core.min.js"></script>
      <script src='https://cdn.jsdelivr.net/npm/@clappr/hlsjs-playback@latest/dist/hlsjs-playback.min.js'></script>
    </head>
    <script>
      var player = new Clappr.Player({
        // [...]
        source: "http://your.video/here.mp4",
        plugins: [HlsjsPlayback],
      });
    </script>
    <!-- [...] -->
  </body>
</html>
```

**Comment by joaopaulovieira** [comment]
Hi @asheroto! As @kslimani said, the package name has changed (is `@clappr/player` now). We have an example in the README of the package URL on the JSDelivr CDN (https://github.com/clappr/clappr#clapper-usage)

Just an adjustment in relation to the example of @kslimani did: The default package of Clappr already includes the `hlsjs-playback`. We decided to do this to maintain the same behavior as the previous version. The example would be the same as the README (https://github.com/clappr/clappr#clapper-usage), just changing the source to a `.m3u8`.

**Comment by asheroto** [comment]
Ah okay, thank you for that info!
