### ISSUE TITLE
Demo still loads pre 0.4.x architecture?

### ISSUE THREAD

**Issue by blacktrash** [clappr/clappr#1964]
http://clappr.io/demo/ loads
https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js
and not
https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.min.js

**Comment by blacktrash** [comment]
Certainly the scripts differ which can lead to [confusion](https://github.com/clappr/hlsjs-playback/issues/4#issuecomment-698995834) ;-)

**Comment by joaopaulovieira** [comment]
Wow! I forgot to update when I made the release `0.4.0`, my fault. 🤦

It's updated now. Thank you!
