### ISSUE TITLE
Error code catalog

### ISSUE THREAD

**Issue by pcandido** [clappr/clappr#1965]
Hello,

I have been working on an error handling policy on a product built on top of Clappr. I'd like to know if there is some kind of catalog of error codes that I can use to document, prevent, and properly handle those errors.

This is an example of an event received from event PLAYER_ERROR:

```json
{
  "description": "",
  "level": "FATAL",
  "origin": "html5_video",
  "scope": "playback",
  "raw": {},
  "code": "html5_video:4",
  "UI": {
    "title": "Não foi possível reproduzir o vídeo.",
    "message": "Ocorreu um problema ao tentar carregar o vídeo."
  }
}
```

I believe I should use the code `html5_video:4` as the error identifier. In this case, I just need the list of all the codes and their descriptions (preferable to be low-level description)

For this specific error (prefixed by `html5_video`), I also believe I can consult https://developer.mozilla.org/en-US/docs/Web/API/MediaError. Am I right? Are there other kinds of errors besides `html5_video`? And how can I get the whole list with descriptions?

Thanks

**Comment by joaopaulovieira** [comment]
Hi @pcandido. You can check how we build one error object [here](https://github.com/clappr/clappr-core/blob/master/src/base/error_mixin/error_mixin.js) but essentially, the error object has the respective parameters:

### `origin`
>The component or plugin where the error occurred.

### `scope`
>The Clappr layer where the error occurred (`core`, `container`, or `playback`).

### `level`
>The error level in one scale of severity. (You can check about levels [here](https://github.com/clappr/clappr-core/blob/master/src/components/error/error.js)).

### `raw`
>The error raw data received.

### `code` 
>The error code received. By default, Clappr composes this information with the `origin` (`${origin}:${code}`) but is possible to disable with the `useCodePrefix` config disabled.

### `description`
>The error message data received.

### `UI`
>For `FATAL` level errors only. One object with `title` and `message` text parameters.

For playback errors like the `html5_video:4`, you need to search on the playback error docs of each playback implementation. For the `html5_video` (that uses the HTML5 video tag implementation) the best docs are the MDN docs as you already commented.

If you use the [hlsjs-playback](https://github.com/clappr/hlsjs-playback/), you can search for the `hls.js` docs [here](https://github.com/video-dev/hls.js/blob/master/docs/API.md) and if you use the [dash-shaka-playback](https://github.com/clappr/dash-shaka-playback) you can search for the `shaka-player` docs [here](https://shaka-player-demo.appspot.com/docs/api/index.html).

**Comment by joaopaulovieira** [comment]
@pcandido Does this information help you?

**Comment by pcandido** [comment]
Yes, it does. Thank you.
