### ISSUE TITLE
Subtitles in Clappr HLS

### ISSUE THREAD

**Issue by asheroto** [clappr/clappr#1966]
**What do you want to do with Clappr?**

I want to use SRT or VTT subtitles in Clappr.

**What have you tried so far?**

I've tried using https://mydomain.com/subtitles/123.vtt,https://mydomain.com/video/123.m3u8  in "source" but can't get it to work.  I know the files are correct.  What's the format to load subtitles with the full URL specified while using m3u8 (HLS) thanks!

**Comment by joaopaulovieira** [comment]
Hi @asheroto, I think [this PR](https://github.com/clappr/clappr-plugins/pull/23) should fix your problem.

**Comment by asheroto** [comment]
Thank you so much @joaopaulovieira 
I will check it out!!!!

**Comment by asheroto** [comment]
@joaopaulovieira Looks like this will work for me, but how can I get that PR's clappr-plugins.js to be part of the clappr source code?

**Comment by joaopaulovieira** [comment]
We will merge this PR on `clappr-plugins` and release a new version of `clappr-player` using this updated version of `clappr-plugins`.

If you need it ASAP, you can fork the branch of the PR on `clappr-plugins`, generate one build, and fork `clappr-player` too and apply your custom build of `clappr-plugins` on it.

**Comment by asheroto** [comment]
Looking forward to the merge

**Comment by asheroto** [comment]
@joaopaulovieira how do I generate a build?  Sorry, I'm a n00b when it comes to GitHub and JS builds.

**Comment by joaopaulovieira** [comment]
We finally generate the release with the fix. You can validate on Clappr demo now: http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9iaXRkYXNoLWEuYWthbWFpaGQubmV0L2NvbnRlbnQvc2ludGVsL2hscy9wbGF5bGlzdC5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK

**Comment by asheroto** [comment]
Works!  Score!

**Comment by asheroto** [comment]
Is there any way to specify the VTT or SRT file with an M3U8 (HLS)?  Or must you specify it within the M3U8 file only?

**Comment by joaopaulovieira** [comment]
Clappr accepts the two approaches.

To use an external subtitle, you need to use the [`playback.externalTracks`](https://github.com/clappr/clappr-core#externaltracks) option. Example:

```javascript
player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  ...
  playback: {
    externalTracks:[{
      kind: 'subtitles',
      label: 'custom',
      lang: 'en',
      src: /* The URL for subtitle source, like -> http://localhost:8080/sample.vtt */,
    }]
  }
})
```

Or you can specify into the `.m3u8` manifest as the media example used in my previous comment.


It's possible to use the two approaches together too. Just play one media with the subtitles defined in the `.m3u8` manifest and config one external subtitle via `playback.externalTracks` option.

**Comment by asheroto** [comment]
Got it, thanks so much!

**Comment by asheroto** [comment]
Having an issue with Clappr detecting external subtitle on an HLS stream.  Subtitles are VTT.

**With HLS.js the subtitles work fine**, and load by default as expected, and are selectable (click the dot menu on the right and you can turn them on/off) - in this test do not skip because there is only about 5 minutes of video, but if you wait until second 20 you will see the captions load:

https://privcloud.co/HLSTEST/hlsjs.php

![image](https://user-images.githubusercontent.com/49938263/136572285-15c6912c-5ff8-45ac-bcce-624e4a754139.png)

**With Clappr, the subtitles do not load**, are not selectable, and appear absent.  However, if you look at the source, you can see the `<track` HTML tag inserted.  I have tried kind `subtitles` and kind `captions` but do not see a change.
https://privcloud.co/HLSTEST/clappr.php

![image](https://user-images.githubusercontent.com/49938263/136572237-6bf78329-20c3-4a3f-a73b-3d5892708275.png)


Any ideas?
