### ISSUE TITLE
Failed to execute Start on TimeRanges

### ISSUE THREAD

**Issue by asheroto** [clappr/clappr#1967]
**Browser**: 
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**OS**: 

Server 2019 / Win 10

**Clappr Version**: 

0.4.1 (latest)

**Steps to reproduce**:

I have a script that saves the time of the video and then resumes that time.  On version 0.4.0 it works fine, but on 0.4.1 I get the following error...

![image](https://user-images.githubusercontent.com/49938263/94778457-e9558c00-038a-11eb-9a40-772b14f29b5b.png)

**Comment by joaopaulovieira** [comment]
Can you share the media and the script to reproduce the problem? You can use clappr.io/demo to do this (:

**Comment by joaopaulovieira** [comment]
@asheroto ping

**Comment by asheroto** [comment]
I believe this has been resolved, I'll close it.
