### ISSUE TITLE
Play with 30 second delay

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1969]
I have a stream that always freezes during 30 seconds. After this time the video continues and does not stop again..
The stream allows go back up to 1:30 minutes.

How to start the video 30 seconds delay?

Thank you in advance.

**Comment by joaopaulovieira** [comment]
I think is one problem with the stream, no? Maybe one investigation to understand why the video freezes after 30 seconds is a better approach.

The problem occur when playing the stream in another Player too?

**Comment by hijuuijj** [comment]
Hi João Paulo. Unfortunately the streams stopped working. Thank you anyway.
