### ISSUE TITLE
Usage with Nuxt.js

### ISSUE THREAD

**Issue by just-tom** [clappr/clappr#1971]
Hi all,

Wondering if anyone has successfully used Clappr (+ plugins) with Nuxt.js in SSR mode?

I have Clapper (0.4.1) Installed and trying to use as an import in my vue component:

`import Clappr from '@clappr/player'`

This works fine when navigating to the page using the nuxt-routing etc, but if I refresh the page containing this vue component I get the error Window is not defined.

Any help will be much appreciated

**Comment by joaopaulovieira** [comment]
I've never used Nuxt.js but I think this problem is because Clappr is being built before the DOM reference exists. Your component loaded via SSR need to use a placeholder instead of the Clappr Player and when it's loaded on the client-side (when exists the DOM reference), Clappr will have what it needs to start correctly.

**Comment by KeremTurkyilmaz** [comment]
Any suggestions ? 
My workaround is this.
```
<script>
let clappr = null;
if (process.client) clappr = require('clappr');

export default {
	name: 'EventPlayer',
	props: {
		streaming: {
			type: Object,
			required: true
		}
	},
	data() {
		return {
			player: null
		};
	},
	mounted() {
		if (process.browser) {
			this.player = new clappr.Player({
				source: this.streaming.url,
				parent: this.$refs.player,
				width: '100%',
				height: '100%',
				events: {
					onPlay: () => this.play(),
					onStop: () => this.stop()
				}
			});
			this.player.setVolume(50);
			this.player.play();
		}
	},
	methods: {
		play() {
			if (!this.player) return;
			this.player.play();
		},
		stop() {
			if (!this.player) return;
			this.player.stop();
		}
	}
};
</script>
```
