### ISSUE TITLE
0.4.14 broken on IE

### ISSUE THREAD

**Issue by Bubblesphere** [clappr/clappr#1972]
**Browser**: IE11

**OS**: W10

**Clappr Version**: 0.4.14 (https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.min.js)

**Steps to reproduce**:

* Go to http://clappr.io/demo/
* play the video
* Check the console. There's this error
![image](https://user-images.githubusercontent.com/8861575/97726888-17231300-1aa6-11eb-94cb-a72c4c1b5882.png)

This issue does not happen when I use 0.3.13 (https://cdn.jsdelivr.net/npm/clappr@0.3.13/dist/clappr.min.js)

**Comment by joaopaulovieira** [comment]
Hi @Bubblesphere! I don't have a Windows PC and remote work makes access to company devices more difficult. Can you help with this problem, guys? @jhonatangomes @leandromoreira @towerz

**Comment by leandromoreira** [comment]
me neither :(

**Comment by kslimani** [comment]
I think this error is due to IE 11 [does not support Array.from](https://caniuse.com/?search=array.from). Line 8641 of clappr-core esm bundle is :

```javascript
// ...
var textTracks = this.el.textTracks ? Array.from(this.el.textTracks) : [];
// ...
```

If i remember correctly, there is (was ?) a module loading polyfills to handle this issue.

**Comment by kslimani** [comment]
I remembered wrong, there is no support for "Array.from" method in [polyfills](https://github.com/clappr/clappr-core/blob/master/src/base/polyfills.js) module.

Also i am curious why IE11 is using the esm.js file ? maybe something related to Rollup bundler ?

Also, IE11 will be officialy end of life next year.

**Comment by leticiafernandes** [comment]
Hi @Bubblesphere, as @kslimani said the IE11 will be discontinued by Microsoft soon. We don't think it's a valid effort to solve this issue and will close it. Feel free to send us a PR if you like :) 

[Offical Microsoft Report](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge)
