### ISSUE TITLE
No closed captions from HLS live stream

### ISSUE THREAD

**Issue by ofrzeta** [clappr/clappr#1973]
**Browser**: 68.12.0esr (64-bit)

**OS**: CentOS 

**Clappr Version**: 0.4.1

**Steps to reproduce**:

Closed captions embedded in an HLS live stream don't work. No CC button is shown. It does work with the same stream on Clappr 0.3.12.
Test stream is https://cdn.techcast.com/test/_definst_/amlst:caption-test/playlist.m3u8
I tried to make it work with the hlsjs-playback.min.js 

Did you try to reproduce this issue at http://cdn.clappr.io/
yes, doesn't work either (also using hlsjs-playback.min.js  or not)

**Comment by Bubblesphere** [comment]
You might find useful information [here](https://github.com/clappr/hlsjs-playback/issues/4)

**Comment by ofrzeta** [comment]
So so .. :) It doesn't really solve the problem but at least provides some pointers to debug, so thanks!

**Comment by joaopaulovieira** [comment]
Hi @ofrzeta, I think this PR should fix your problem.

**Comment by kslimani** [comment]
😉 https://github.com/clappr/clappr-plugins/pull/23

**Comment by joaopaulovieira** [comment]
@ofrzeta The reported problem still happens?

**Comment by ofrzeta** [comment]
I didn't have the opportunity to check back then because the fix wasn't in a Clappr release and now unfortunately I no longer have a source with closed captions, sorry.

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
