### ISSUE TITLE
I want to modify clappr ui 

### ISSUE THREAD

**Issue by Denjjo** [clappr/clappr#1974]
I want to give the playlist 
<img width="852" alt="Screenshot 2020-11-04 at 9 05 40 PM" src="https://user-images.githubusercontent.com/73953633/98133305-6f617700-1ee3-11eb-9820-1bc872040332.png">

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by joaopaulovieira** [comment]
Hi @Denjjo. For one custom UI, you can create your own Media Control plugin. You can see how the current media control plugin works on the [player-plugins repo](https://github.com/clappr/clappr-plugins/blob/master/src/plugins/media_control/media_control.js).

We have one example for build one plugin too in the [Wiki](https://github.com/clappr/clappr/wiki/Our-first-plugin).

**Comment by Denjjo** [comment]
thanks for this and I start working if I have a new issue with that I will tell you

**Comment by joaopaulovieira** [comment]
Hi @Denjjo! Just an update: I created a new media control plugin with a more flexible architecture for customizing the UI and adding new components.

If you have not created your own media control plugin or would like to know another example, take a look: https://github.com/joaopaulovieira/clappr-media-control-plugin

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
