### ISSUE TITLE
Loading picture is showing twice

### ISSUE THREAD

**Issue by winie** [clappr/clappr#1975]
**Browser**: All, but tested with Firefox 82.0 (64-Bit)

**OS**: Kubuntu 20.04

**Clappr Version**: 0.4.1

**Steps to reproduce**:

* Create image with transparent background and transparent elements in image
* Set image as poster in `Player` constructor.
* Open website with clappr player and you see the poster image twice (different sizes)

Did you try to reproduce this issue at http://cdn.clappr.io/: yes, its the same there

You see KIF 48,5 logo twice. A little one in the big one:

![grafik](https://user-images.githubusercontent.com/12683936/98176708-5ebbfb80-1ef9-11eb-9773-8b845bced0d7.png)

Problem:
The video-tag has a poster attribute with the poster image as value. A div-tag with classes `player-poster` and  `clickable` has also the poster image as background image: style='background-image: url("poster.svg");'

So if you set a image with a transparent background and transparent elements. you see the second loading poster from the video-tag behind the loading poster from the div. Both loading images does not have the same size. you only see it while the stream/video is loading.

My solution was, to set a background color in the loading image:
![grafik](https://user-images.githubusercontent.com/12683936/98177473-ff5eeb00-1efa-11eb-8025-da2300b58a9d.png)

**Comment by winie** [comment]
It should be named in the ´Known issues`

**Comment by winie** [comment]
Do you need more information?

**Comment by joaopaulovieira** [comment]
Hello @winie
Yeah, this is really odd behavior. We need to fix it.

**Comment by joaopaulovieira** [comment]
On the next **@clappr/plugins** version this will be fixed: https://github.com/clappr/clappr-plugins/commit/e85f92b587ffc18f78664f253ab09edd63c9cf94

**Comment by joaopaulovieira** [comment]
Hi @winie,

We shipped this fix on the latest version /õ/

**Comment by winie** [comment]
> Hi @winie,
> 
> We shipped this fix on the latest version /õ/

Thanks, i will test it.

**Comment by joaopaulovieira** [comment]
Hi @winie 
Do you have any news about it?

**Comment by leticiafernandes** [comment]
Hi @winie, we will close this issue due to inactivity. Feel free to reopen if still happens.
