### ISSUE TITLE
Supported subtitles formats

### ISSUE THREAD

**Issue by nelson777** [clappr/clappr#1978]
I would like to know which subtitle formats are accepted by Clappr.

I've made it work with .vtt format. I also tried sub and srt, but it didn't work. Do I have to use only .vtt format ?

In order to make it work I used playback.externalTracks option like this:

	playback: {
		externalTracks: [
			{ lang: 'en', label: 'Test1', src: '<host>/assets/subtitles/test1.vtt', kind: 'subtitles', default: true },
			{ lang: 'en', label: 'Test2', src: '<host>/assets/subtitles/test2.srt', kind: 'subtitles', default: false },
			{ lang: 'en', label: 'Test3', src: '<host>/assets/subtitles/test3.sub', kind: 'subtitles', default: false }
		]
	}
 
In this test, all 3 options appeared on cc icon, but only .vtt really worked.

I see there's a srt plugin available: https://github.com/jmvtechnology/Clappr-Subtitle

But as stated in this page: "This is a very early version. You can't select subtitle tracks, and long srt files may run slow."

I can't afford to use an early version as my project will be used by thousands of people enterprise-wide.

There other options I'm missing ?

**Comment by kslimani** [comment]
I think it uses browser video element capabilities. So if subtitle format is supported by browser, it should work.

**Comment by nelson777** [comment]
As stated [here](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#HTML5_and_Video_Captions) there is .vtt support only.

Are there any other way ? In the negative case, are there any plans to incorporate support for other subtitles format ?

**Comment by kslimani** [comment]
I don't know about other format. It seems that major browsers tend to [support the vtt format](https://caniuse.com/webvtt).

**Comment by leticiafernandes** [comment]
Hi @nelson777, if you want to use other formats apart from `.vtt` I suggest you create subtitle plugins to accept these formats. If you need help creating the plugin send us an issue to ask for help.
