### ISSUE TITLE
Can't disable closed cations

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#1981]
**Browser**: chrome 87

**OS**: mac os 10.15.5

**Clappr Version**: 0.4.2

Can't disable closed cations on HLS Live ))
[Your demo](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAiLy9saXZlLXN0cmVhbXMuY2RudmlkZW8ucnUvc21pbHMvYnVubnlfcGxheWxpc3QubTN1OCIsCiAgcG9zdGVyOiAnaHR0cDovL2NsYXBwci5pby9wb3N0ZXIucG5nJywKICBtdXRlOiB0cnVlLAogIHBsYXliYWNrOiB7CiAgICAgICAgICBleHRlcm5hbFRyYWNrczogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgbGFuZzogInJ1IiwKICAgICAgICAgICAgICBsYWJlbDogImV4YW1wbGUiLAogICAgICAgICAgICAgIHNyYzogIi8vcGxheWVycy1zdGFuZC5jZG52aWRlby5ydS9jbGFwcHIvc3R5bGluZy1kZXYvc3VidGl0bGVzLWV4YW1wbGUtMS52dHQiLAogICAgICAgICAgICAgIGtpbmQ6ICJzdWJ0aXRsZXMiLAogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgbGFuZzogInJ1IiwKICAgICAgICAgICAgICBsYWJlbDogImZpc2giLAogICAgICAgICAgICAgIHNyYzogIi8vcGxheWVycy1zdGFuZC5jZG52aWRlby5ydS9jbGFwcHIvc3R5bGluZy1kZXYvc3VidGl0bGVzLWV4YW1wbGUtMi52dHQiLAogICAgICAgICAgICAgIGtpbmQ6ICJzdWJ0aXRsZXMiLAogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgbGFuZzogImVuIiwKICAgICAgICAgICAgICBsYWJlbDogImxvcmVtIiwKICAgICAgICAgICAgICBzcmM6ICIvL3BsYXllcnMtc3RhbmQuY2RudmlkZW8ucnUvY2xhcHByL3N0eWxpbmctZGV2L3N1YnRpdGxlcy1leGFtcGxlLTMudnR0IiwKICAgICAgICAgICAgICBraW5kOiAic3VidGl0bGVzIiwKICAgICAgICAgICAgfSwKICAgICAgICAgIF0sCiAgICAgICAgICBjcm9zc09yaWdpbjogImFub255bW91cyIsCiAgICAgICAgfSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=)

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
