### ISSUE TITLE
Player fails to restart playback once

### ISSUE THREAD

**Issue by Hrishikesh-K** [clappr/clappr#1982]
**What do you want to do with Clappr?**

I'm using a simple HLS video and using Level Selector plugin. The video plays fine and all. However, after the video ends, there's a black screen that shows the big play button again. Clicking on that button gives HLS4 error with a reload button below it and clicking on that button loads the video again just fine.

There's a demo on my website: https://v2--hrishikeshk.netlify.app/projects/carry-on-bot/ (scroll to bottom). Try skipping to the end and you'll see the big play button as described above.

**What have you tried so far?**

I have no idea how to start fixing it. Not sure if this is Clappr problem or the plugin problem. I get error 404 for some `blobs` in my console. But, that's it.

It would be acceptable to disable the end screen completely so restarting is not an option, but, that would be last resort (if at all it's possible). Any other advice would be welcome.

**Comment by kslimani** [comment]
@Hrishikesh-K is your issue fixed with Clappr 0.4.3 ?

**Comment by Hrishikesh-K** [comment]
@kslimani Thanks a lot for your work. It seems to work fine.
