### ISSUE TITLE
seek fails on Android Mobile HLS

### ISSUE THREAD

**Issue by asheroto** [clappr/clappr#1983]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Applies to Android Mobile (1) Firefox, (2) Chrome, (3) Chromium relatives

**OS**: 
Android 10

**Clappr Version**: 
0.4.2

**Steps to reproduce**:
Define a var to the Clappr player, then use the ".seek" command and try to skip to a particular point in the video.  Fails on any HLS stream, haven't tried other types but possibly affects all videos.

var cPlayer = new Clappr.Player({
		width: "100%",
		height: "100%",
		controls: true,
		autoPlay: true,
		source: "specify-video-source-here",
});

cPlayer.seek(6.5); // This fails on Android Mobile (any browser) but works on Desktop versions

**Comment by blacktrash** [comment]
That's related to `autoPlay`, not `seek`. `autoPlay` is not allowed on mobile devices unless the video is muted (`mute` option).

**Comment by asheroto** [comment]
I think so too, but seek doesn't work even after a video is playing and I try to call it.

**Comment by Suldeaked** [comment]
addthis.com/js/300/addthis_widget.js#pubid=ra-62a534ff99e29ba8

**Comment by asheroto** [comment]
?

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
