### ISSUE TITLE
hls error 4 on replay attempt

### ISSUE THREAD

**Issue by blacktrash** [clappr/clappr#1984]
**Browser**: any browser I've tried so far

**OS**: any I've tried so far

**Clappr Version**: 0.4.2 / latest, regression in this aspect from 0.4.1

**Steps to reproduce**:

* go to http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly90ZXN0LXN0cmVhbXMubXV4LmRldi94MzZ4aHp6L3gzNnhoenoubTN1OCcsCiAgcG9zdGVyOiAnaHR0cDovL2NsYXBwci5pby9wb3N0ZXIucG5nJywKICBtdXRlOiB0cnVlLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAKfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cg==
* play until end
* after poster appears try to play again
* player hangs, depending on devices shows hls error 4

Expected: replay should work

Did you try to reproduce this issue at http://cdn.clappr.io/
Yes, see above.

**Comment by Hrishikesh-K** [comment]
Exactly the same case as my issue here: https://github.com/clappr/clappr/issues/1982. So, it seems I'm no the only one.

**Comment by alaxicsmith** [comment]
I'm having the same issue, too.

**Comment by kslimani** [comment]
I could reproduce the issue, i proposed a fix in Clappr core.

**Comment by kslimani** [comment]
@blacktrash is your issue fixed with Clappr 0.4.3 ?

**Comment by blacktrash** [comment]
@kslimani, yes indeed, it is. As can be verified in the demo as well.
Sorry for not getting back earlier. Closing.
