### ISSUE TITLE
Clappr in php

### ISSUE THREAD

**Issue by qutub11** [clappr/clappr#1985]
Can you please tell me how can i add clappr to my php file. Basically my php generates url, but i want when url generates it should play in clappr. is that possible with clappr ?

Below is my code, can you please add clappr to it.

<?php
// usage main.php?c=123
$input = $_GET["c"];
if (!$input){
   exit("Channel ID not found");
}
$channel_meta = JsonfromURI("https://catalogapi.mee.com/v1/channel/${input}");
$stream_url = $channel_meta->stream_url_hls;
$tok_json = JsonfromURI("https://useraction.mee.com/token/live.php");
$video_token = $tok_json->video_token;
$m3u8 = $stream_url.$video_token;
echo $m3u8;

function JsonfromURI($url) {
   $resp = file_get_contents($url);       
   return json_decode($resp);
};

**Comment by jakecausier** [comment]
You can simply echo out the $m3u8 variable into the Clappr script. 

Example:
```php
<div id="player"></div>
<script>
    var player = new Clappr.Player({
        source: "<?php echo esc_url($m3u8) ?>",
        parentId: "#player"
    });
</script>
```

**Comment by joaopaulovieira** [comment]
Hi @qutub11 

Does the @jakecausier response work for you?
