### ISSUE TITLE
Field of view seems really zoomed in in comparison to 360 videos on YouTube. Is it possible to adjust the FoV?

### ISSUE THREAD

**Issue by TheGreatestZenMaster** [clappr/clappr#1987]
**What do you want to do with Clappr?**
I want to zoom out the field of view a bit further as it feels too zoomed in.

**Comment by leticiafernandes** [comment]
Hi @TheGreatestZenMaster, your doubt is related to [clappr-video-360](https://github.com/thiagopnts/clappr-video360) plugin?

**Comment by joaopaulovieira** [comment]
Closing this issue. @TheGreatestZenMaster fell free to open again if you have more info (:
