### ISSUE TITLE
Caption toggle problems

### ISSUE THREAD

**Issue by Hrishikesh-K** [clappr/clappr#1991]
**Browser**: Chrome 87, Firefox 84

**OS**: Windows 10, Android 10

**Clappr Version**: 0.4.2

**Steps to reproduce**:

* Visit: https://5fdfa74891b4fa0007ed659e--hrishikeshk.netlify.app/projects/goodbye-adam/#end-result
* Play the video.
* Click on the captions button to toggle the English captions.
* Click on the captions button again and try to disable captions.

The captions get enabled fine, but upon trying to disable them, they don't get disabled. However, the captions list does add the selected class to the disabled list item.

**Comment by leticiafernandes** [comment]
Hi @Hrishikesh-K. Thank you for your repport. This issue is duplicated, we will update the status at #1981.
