### ISSUE TITLE
level selector doesn't work with 0.3.13 and 0.4

### ISSUE THREAD

**Issue by Niko78** [clappr/clappr#1993]
Hi,
I opened the same issue in level selector github page but I prefer double here 
https://github.com/clappr/clappr-level-selector-plugin/issues/99

I use this plugin in clappr but since 0.3.13 or even with last 0.4 it doesn't work well.
It works when switch is automatic.. but if I select manualy diretly from list a value, video is frozen.

I reproduced online in clappr demo page and in console it displays :
[warn][Loader] missing version information for level_selector
I can see well m3u8 requests in network tab but no ts

I tried with other players and it works.

if you have an idea
Thanks

PS : I confirm that in downgrading in 0.3.12 it works well

**Comment by Niko78** [comment]
well after few other tests, it's not exactly that issue
it appears when I change resolution manualy, player puts itself in pause, so I have to reclick on play button in bar

**Comment by Niko78** [comment]
still same issue with 0.4.3

**Comment by pedra** [comment]
Version 0.4.3
![image](https://user-images.githubusercontent.com/4870358/107663903-a4136600-6c6a-11eb-94df-4231163d0499.png)

**Comment by Niko78** [comment]
any news ? cause I'm still in 0.3.12 which is too old now
clappr project seems a bit dead... :-(

**Comment by leandromoreira** [comment]
did you check the https://github.com/clappr/clappr-core and https://github.com/clappr/clappr-plugins ? Clappr is a composition of two other projects: @clappr/core and @clappr/plugins.

**Comment by leandromoreira** [comment]
@jhonatangomes @joaopaulovieira

**Comment by Niko78** [comment]
possible to fix this issue asap ? I'm still blocked in 0.3.13
thanks

**Comment by jhonatangomes** [comment]
Hi, @Niko78 

I'm following this issue on https://github.com/clappr/clappr-level-selector-plugin/issues/99

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
