### ISSUE TITLE
Autoplay not working on mobile

### ISSUE THREAD

**Issue by issimissimo** [clappr/clappr#1996]
**What do you want to do with Clappr?**
I'd like to autoplay videos on mobile devices (Android, iOS).
It work on desktop (Windows) but not on mobile.

I've read of some code with this extra option:
```
playback: {
                playInline: true,
                recycleVideo: Clappr.Browser.isMobile,
            }
```
but I can't find any documentation on it...
Many thanks

**What have you tried so far?**
```
var player = new Clappr.Player({
            source: "video/Dummy.mp4",
            width: "100%",
            height: "100%",
            autoPlay: true,
});
```

**Comment by kslimani** [comment]
On mobile devices, video playback require a user action.

It is possible to autoplay video on some mobile devices if you set `mute` player option to `true`.

**Comment by issimissimo** [comment]
Many thanks kslimani,
I've been able to autoplay on mobile (at least on my Samsung S8) with this code:
`var player = new Clappr.Player({
            width: "100%",
            height: "100%",
            disableVideoTagContextMenu: true, /// don't know what it do but maybe it's useful
            mute: true,
            chromeless: true, /// just to hide the seek bar
            playback: {
                playInline: true,
                recycleVideo: true,
            },
        });

player.configure({
            source: "video/Dummy_vertical.mp4",
            autoPlay: true,
        });
`

Do you think I could have issues on some devices (maybe iOS) with this code?

**Comment by kslimani** [comment]
iPhone mobile devices should be able to autoplay video if muted. _(unless it is a very (very!) old iOS iphone/ipad version, where Safari new autoplay policy not implemented)_

**Comment by leaofelipe** [comment]
Hi, @kslimani and @issimissimo. I Just created a Pull Request about the autoplay issue.

[Check this PR](https://github.com/clappr/clappr/pull/2014) 👍

**Comment by leaofelipe** [comment]
[This PR](https://github.com/clappr/clappr/pull/2014) solved the question 👍
