### ISSUE TITLE
Error messages are broken

### ISSUE THREAD

**Issue by AInteriorB** [clappr/clappr#1999]
**Browser**: any

**OS**: any

**Clappr Version**: 0.4.3

**Steps to reproduce**:

* open [http://clappr.io/demo/](http://clappr.io/demo/)
* define a source that is not available
* click play
* design of error messages is broken

It seems that [player-data] overwrites CSS display values on the player-error-screen div and its children:
`[data-player] > div {
    display: block;
}`

<img width="673" alt="Bildschirmfoto 2021-02-10 um 11 09 39" src="https://user-images.githubusercontent.com/49516700/107495538-8245b080-6b90-11eb-90cb-bb015cd9e83e.png">

**Comment by joaopaulovieira** [comment]
Fixed on the version `0.4.4`. Thank you for the report @AInteriorB !
