### ISSUE TITLE
How to hide the fullscreen button from UI

### ISSUE THREAD

**Issue by issimissimo** [clappr/clappr#2000]
Hello,
I'd like to hide the fullscreen button from UI.
How can I do?
Many thanks!

**Comment by joaopaulovieira** [comment]
Hi @issimissimo ! Check the issue #1198 and this comment [here](https://github.com/clappr/clappr/issues/1198#issuecomment-807918914).

**Comment by pedrochamberlain** [comment]
We're closing this issue up. If you have any further questions, please reopen it!
