### ISSUE TITLE
Preload first image frame from HLS stream

### ISSUE THREAD

**Issue by fabioricali** [clappr/clappr#2001]
Hi, 

is it possible to load as poster the first frame of a hls streamig?
I tried here without success:
http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9zdHJlYW0yLnhkZXZlbC5jb20vdmlkZW8xczMtNy9zdHJlYW0vcGxheWxpc3QubTN1OCcsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK

furthermore I tried with the raw hls.js library and it works...
Can you help me?

Thank you

**Comment by joaopaulovieira** [comment]
Hi @fabioricali,

At the latest `@clappr/player` version it's possible to get this behavior when you don't set one poster image.

One example: http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9iaXRkYXNoLWEuYWthbWFpaGQubmV0L2NvbnRlbnQvTUkyMDExMDkyMTAwODRfMS9tM3U4cy9mMDhlODBkYS1iZjFkLTRlM2QtODg5OS1mMGY2MTU1ZjZlZmEubTN1OCcsCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwo=

**Comment by fabioricali** [comment]
Thank you! It works...
