### ISSUE TITLE
Safari HLS CPU load and crash/reload page

### ISSUE THREAD

**Issue by dkirilenko** [clappr/clappr#2004]
**Browser**: Safari 14

**OS**: iPhone SE (2 edition)

**Clappr Version**: "0.4.3"

**Steps to reproduce**:
1. I've created a simple rails application with one page which returns me `m3u8` file and `ts`
2. Created DOM element and applied javascript to run Clappr
```
   <script type="text/javascript">
        var playerElement = document.getElementById("player");

        var player = new Clappr.Player({
          source: '/playlist.m3u8',
          mute: true,
          height: 360,
          width: 640
        });

        player.attachTo(playerElement);
    </script>
```
3. After 1-2 minutes browser tab crashes and reloads the page

`Did you try to reproduce this issue at http://cdn.clappr.io/`  --> It's local streaming m3u8 file creating,  so no

Helps:
1. Used your cdn link from github. Here is full HTML:
```
<!DOCTYPE html>
<html>
  <head>
    <title>FfmpegHls</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.min.js"></script>
  </head>

  <body>
    <div id="player"></div>
    <script type="text/javascript">
        var playerElement = document.getElementById("player");

        var player = new Clappr.Player({
          source: '/playlist.m3u8',
          mute: true,
          height: 360,
          width: 640
        });

        player.attachTo(playerElement);
    </script>
  </body>
</html>
```
2. Here is START of video, Github accept only 10Mb. Total video time is 1 min 38 sec

https://user-images.githubusercontent.com/7079311/111618791-77181d00-87ed-11eb-8d8a-2127fb8cc003.MOV

3. Here is END of video

https://user-images.githubusercontent.com/7079311/111618948-a7f85200-87ed-11eb-8d2e-6b25a951cc51.MOV

4. Before crash and reload I see this message, sorry in Ukrainian (this page was reloaded because of problem):
![image](https://user-images.githubusercontent.com/7079311/111619128-d9711d80-87ed-11eb-9464-f74cd7964c49.png)

5. Here is one of the log from mobile:
```
{"app_name":"com.apple.WebKit.WebContent","timestamp":"2021-03-18 12:58:09.00 +0200","app_version":"8610","slice_uuid":"F3E40BD3-45F0-3D8A-84F5-4CFC2EE0A459","adam_id":0,"build_version":"8610.4.3.0.4","bundleID":"com.apple.WebKit.WebContent","share_with_app_devs":0,"is_first_party":1,"bug_type":"142","os_version":"iPhone OS 14.4.1 (18D61)","incident_id":"6F25E608-1779-4D79-8A6E-A82BB1BBFE8E","name":"com.apple.WebKit.WebContent"}
Date/Time:        2021-03-18 12:54:27.062 +0200
End time:         2021-03-18 12:58:03.448 +0200
OS Version:       iPhone OS 14.4.1 (Build 18D61)
Architecture:     arm64e
Report Version:   32
Incident Identifier: 6F25E608-1779-4D79-8A6E-A82BB1BBFE8E

Data Source:      Microstackshots
Shared Cache:     0901E8F8-7CE6-3486-B9CC-5A5F224DD026 slid base address 0x19458c000, slide 0x1458c000

Command:          com.apple.WebKit.WebContent
Path:             /System/Library/Frameworks/WebKit.framework/XPCServices/com.apple.WebKit.WebContent.xpc/com.apple.WebKit.WebContent
Identifier:       com.apple.WebKit.WebContent
Version:          8610 (8610.4.3.0.4)
Parent:           UNKNOWN [1]
PID:              599

Event:            wakeups
Action taken:     none
Wakeups:          45001 wakeups over the last 216 seconds (208 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:    45000
Limit duration:   300s
Wakeups caused:   45001
Wakeups duration: 216s
Duration:         216.39s
Duration Sampled: 212.24s
Steps:            56

Hardware model:   iPhone12,8
Active cpus:      6
```

Any ideas? Thanks.

**Comment by rgaufman** [comment]
I am having the same issue on iPhone 11 Pro Max and on iPhone 12 Pro :( - any ideas?

**Comment by dkirilenko** [comment]
Guys, it works with `Clappr.version => "0.3.1"`. Any ideas?

**Comment by joaopaulovieira** [comment]
Hi @dkirilenko! Can you please test with the bundle without the `hlsjs-playback`? The iOS mobile devices can play .m3u8 natively (with HTML5 implementation) and with this test, we can identify it is one problem related to the hls.js package.

**Comment by joaopaulovieira** [comment]
Hi, @dkirilenko! Did you get to take the test that I mentioned above?

**Comment by leticiafernandes** [comment]
Hi @dkirilenko, we will close this issue due to inactivity. Feel free to reopen if still happens.
