### ISSUE TITLE
FFMPEG video not loading

### ISSUE THREAD

**Issue by rajmylav** [clappr/clappr#2007]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Chrome and firefox
**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Mac and windows
**Clappr Version**: 0.3.8
latest version
**Steps to reproduce**:

expecte dthe video to stream but it stops 

Did you try to reproduce this issue at http://cdn.clappr.io/

ps: you can attach images, logs or whatever you think might be helpful.
ps: feel free to clean this if your issue is different.

```

<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/clappr-chromecast-plugin@latest/dist/clappr-chromecast-plugin.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/clappr/dash-shaka-playback@latest/dist/dash-shaka-playback.js"></script>
</head>

<body>
<div id="player"></div>
<script>
    var player = new Clappr.Player(
        {
            source: 'http://m2.websecureme.net:80/1QzXhQcuQZJ4vYC/D1tSuOaeyE/63491?play_token=W2XoeGvp6g',
            mimeType: "application/x-mpegurl",
            plugins: [DashShakaPlayback],
            shakaConfiguration: {
                preferredAudioLanguage: 'pt-BR',
                streaming: {
                    bufferingGoal: 30,
                    rebufferingGoal: 15,
                    bufferBehind: 60
                }
            },
            shakaOnBeforeLoad: function(shaka_player) {
                // shaka_player.getNetworkingEngine().registerRequestFilter() ...
            },
            parentId: '#player'
        });
</script>
</body>
</html>
```

**Comment by joaopaulovieira** [comment]
I think it would be good to look at how your streaming is being generated because if this problem only happens with that particular media, it seems to have more to do with the media than with Clappr. If you can get public media for testing that reproduces the same problem, it would help with the investigation.
