### ISSUE TITLE
How to play ism/manifest?

### ISSUE THREAD

**Issue by sturlath** [clappr/clappr#2008]
Can I play this with Clappr and what plugin do I need? `//amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest` you can see it playing [here](https://ampdemo.azureedge.net/azuremediaplayer.html)

**Comment by joaopaulovieira** [comment]
Hi @sturlath,
The current Clappr playbacks that I know are:
 * `HTML5Playback`: https://github.com/clappr/clappr-core/blob/master/src/playbacks/html5_video/html5_video.js
* `HLSjsPlayback`: https://github.com/clappr/hlsjs-playback/
* `DashShakaPlayback`: https://github.com/clappr/dash-shaka-playback

Both [hls.js](https://github.com/video-dev/hls.js/) (used on hlsjs-playback) and [shaka-player](https://github.com/google/shaka-player) (dash-shaka-playback) apparently don't support MSS.

You can contribute to one of those projects to add the support or implements one new Clappr playback with this compatibility.

If you choose to contribute to one of the existent projects, the shaka-player already have one discussion about the MSS support: https://github.com/google/shaka-player/issues/703

**Comment by joaopaulovieira** [comment]
@sturlath Was it clear to you what the next steps would be if you want the MSS support?

**Comment by sturlath** [comment]
I would love to be able to contribute a PR for this but that´s unfortunately way out of my expertise I think. 

What I have been trying to find is a player that can then be "ported" to Blazor (that might be something I could do). 

I asked MS if I could use their Azure Media Player there and got the response ["I'd recommend those alternate player frameworks for now over AMP, as the AMP player is getting a bit out of date."](https://docs.microsoft.com/en-us/answers/questions/377441/can-you-use-the-azure-media-player-in-a-blazor-was.html). 

I found Clappr after seeing it on the [hls.js page](https://github.com/video-dev/hls.js) so I decided to ask this question.

I'm fairly new to this all but I´m looking for a player that supports what is possible (what ever that really might be) in AMS and can be ported/used in Blazor at some time.

So like you see, not a lot of help from me other than the information that there is a need to replace this aging AMP player... I have not gone far enough in my programing against AMS to hit any needed use cases (now I´m not using any DRM and just showing the [test player](https://ampdemo.azureedge.net/azuremediaplayer.html?url=https%3a%2f%2ftest-eventstreaming.preview-euwe.channel.media.azure.net%2fc4ab3b2e-9183-4171-a3cb-1fd284c9b552%2fpreview.ism%2fmanifest) in IFrame (just temp solution).

**Comment by kslimani** [comment]
The [dash.js](https://github.com/Dash-Industry-Forum/dash.js) library may be able to play this file. You can test it [here](https://reference.dashif.org/dash.js/latest/samples/smooth-streaming/mss.html).

But note that MSS support has been dropped from some streaming products. For example, take a look at [WSE 4.8.12 release note](https://www.wowza.com/docs/wowza-streaming-engine-4-8-12-release-notes#overview). _(they dropped MSS and Adobe HDS support)_

A (long) time ago, Leandro has made a [dash.js playback plugin](https://github.com/leandromoreira/clappr-dash-dashjs) for Clappr. It can be used as a starting point to create your own.

**Comment by sturlath** [comment]
Thank you @kslimani the path  `//amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest ` is playable in the dash.js  test player. So I might look into that further.

Just one quick question more, on the drop of MSS. 

That would just mean I could not later move to another streaming vendor and stream my already recorded videos, right? As I can gather [Wowza ](https://www.wowza.com/)is another streaming provider just like Azure Media Services, correct?

Thanks all for your quick responses btw!

**Comment by kslimani** [comment]
As you might guess, I can't recommand any streaming vendor ;-)

I am not an Azure expert, but as far as i know, it support many streaming output formats.

Take a look at [dynamic packaging concept documentation](https://docs.microsoft.com/en-us/azure/media-services/latest/encode-dynamic-packaging-concept#hls-protocol).

You can, for example, stream the previously provided stream url in HLS format _(providing mime type to Clappr player)._

Test this code on [Clappr demo page](http://clappr.io/demo/) :

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest(format=m3u8-cmaf)',
  mimeType: 'application/vnd.apple.mpegurl',
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

**Comment by johndeu** [comment]
The key part that @kslimani mentions above is the requirement to change the format tag to HLS. 
The default /manifest returns a Smooth Streaming format manifest. 

You need to append the format=m3u8-cmaf to get an HLS CMAF based manifest
or you could use format=mpd-time-cmaf to get an MPEG-DASH streaming manifest if the player supported DASH.

**Comment by kslimani** [comment]
For completeness, you can also test MPEG-DASH format using this code on [Clappr demo page](http://clappr.io/demo/) :

_**Note:** you must load the dash playback plugin, by adding the following url in the "Add external plugins" input field and click on "+" button : `https://cdn.jsdelivr.net/gh/clappr/dash-shaka-playback@latest/dist/dash-shaka-playback.min.js`._

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest(format=mpd-time-cmaf)',
  mimeType: 'application/dash+xml',
  plugins: [DashShakaPlayback],
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```
