### ISSUE TITLE
MPD doesn't load? 0.4.4 (fiddle)

### ISSUE THREAD

**Issue by fmp777** [clappr/clappr#2010]
**Browser**: Chrome 90.0.4430.93 (Official Build) (arm64)

**OS**: Mac OS 11.3

**Clappr Version**: 0.4.4

**Steps to reproduce**:
https://jsfiddle.net/qx9h4L5w/1/

Do I have the wrong dash?
Honestly its been hard to try to use clappr, seems very scattered since 0.4? Confusing to know how to use it. I wouldn't be surprised if i have something wrong. Maybe since HLS is integrated to the player dash should be too?

**Comment by joaopaulovieira** [comment]
Hi @fmp777,

You need to use [dash-shaka-playback](https://github.com/clappr/dash-shaka-playback) to play `.mpd` media. About having support for all media formats by default, it's possible to have a build like this, but this will make the size much larger due to all the dependencies and maybe this is not worth it in most cases.

We leave it as external playbacks to be used only when necessary, but if it's a general need for everyone who uses the project, I don't see why not.

What do you think @leandromoreira @jhonatangomes @clappr/core ?

**Comment by fmp777** [comment]
Hi @joaopaulovieira !

I do have dash-shaka loaded in that fiddle - just hard to know if i have the right one...  I'm not really clear on how to use the new 0.4 version + plugins as neither repository readme seems to give any instruction.  I've done npm install @clappr/player and @clappr/plugins - build there's no build scripts.  Just trying to do what most people would probably do? Use them in a web page.

**Comment by joaopaulovieira** [comment]
In fact, some documentation is outdated or some information is missing, but I will try to summarize here:

1. The version you using of `dash-shaka-playback` is very old. The project is in `3.x.x` while the one used in your fiddle is `2.0.8`. In the documentation, there is a link to `2.0.5` that has to be removed. I recommend always using the link that points to the latest available version: https://cdn.jsdelivr.net/npm/dash-shaka-playback@latest/dist/dash-shaka-playback.min.js

![Screen Shot 2021-05-03 at 16 24 27](https://user-images.githubusercontent.com/5631063/116924606-7d901600-ac2e-11eb-99a6-45500b910147.png)

2. If you took a look at `dash-shaka-playback`, you saw that not only external playback but any plugin has to be loaded to be used. Without it, your example will never work. This is documented so I think it was just a lack of attention.

![Screen Shot 2021-05-03 at 16 43 27](https://user-images.githubusercontent.com/5631063/116924801-baf4a380-ac2e-11eb-9543-ac31439dd92c.png)

3. The media domain that is on your fiddle is with CORS barring the domain from the fiddle so even with all the correct settings, the video would still not play. You can use other media with CORS released to take the test: `//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd`

**Comment by joaopaulovieira** [comment]
> I've done npm install @clappr/player and @clappr/plugins - build there are no build scripts.

You only need to use @clappr/player if you don't need one custom clappr build. You can see more about the three main clappr package here: https://github.com/clappr/clappr/releases/tag/0.4.0

**Comment by joaopaulovieira** [comment]
@fmp777 This worked for you?

**Comment by leticiafernandes** [comment]
Hi @fmp777, we will close this issue due to inactivity. Feel free to reopen if still happens.
