### ISSUE TITLE
How to switch the video button with the function

### ISSUE THREAD

**Issue by jianhang** [clappr/clappr#2011]
Can I add the next episode button to the navigation bar?The bottom of the navigation bar can always be shown, rather than hover

**Comment by kslimani** [comment]
To always show the mediacontrol bar set the player configuration option `hideMediaControl` to `false,`.

Adding a "next episode" button is a little more complicated. You may need to write a plugin to achieve this.
If you intent to customize media controls, i strongly recommand to take [João media control plugin](https://github.com/joaopaulovieira/clappr-media-control-plugin) as a starting point.

**Comment by jianhang** [comment]
Thank you. Could you please tell me how to get the total and current playing time of the video

**Comment by jianhang** [comment]
> 要始终显示媒体控制栏，请将播放器配置选项设置`hideMediaControl`为`false,`。
> 
> 添加“下一个情节”按钮稍微复杂一些。您可能需要编写一个插件来实现此目的。
> 如果您打算自定义媒体控件，我强烈建议您以[João媒体控件插件](https://github.com/joaopaulovieira/clappr-media-control-plugin)为起点。

Thank you. Could you please tell me how to get the total and current playing time of the video

**Comment by kslimani** [comment]
You can get the current and total playing time of the video respectively using [getCurrentTime()](https://github.com/clappr/clappr-core#-playergetcurrenttime) and [getDuration()](https://github.com/clappr/clappr-core#-playergetduration) player instance methods.
