### ISSUE TITLE
m3u8 error

### ISSUE THREAD

**Issue by telase** [clappr/clappr#2012]
Why doesn't it play these links?
1 : https://mn-nl.mncdn.com/blutv_kanald/smil:kanald_sd.smil/chunklist.m3u8

and 2 : http://persik.by/stream/6696/480248/10463.m3u8
2. The link does not play on my web page while playing with the same js on the local computer, you can look here.
https://www.youtube.com/watch?v=u6D9drjmvB4

**Comment by leandromoreira** [comment]
Hi there @telase did you try to follow the https://github.com/clappr/clappr#common-steps-to-verify-issues

**Comment by joaopaulovieira** [comment]
@telase any news about it?

**Comment by telase** [comment]
I changed the player, it opens all
"Ultimate Video Player"
