### ISSUE TITLE
Timeout 500 ms has been reached

### ISSUE THREAD

**Issue by PreDeToRLinux** [clappr/clappr#2017]
Hi Guys

I have run into a very weird issue.

I am busy building a app for iOS using cordova.

When I run my app as a simple website and I connect to the site from the iPad using safari video playback works fine (.m3u8 files)
When I then build the app, load it into the iPad and try running the player again I get an error every time, "Timeout 500 ms has been reached"   (line 3264 in clappr.js 0.4.5) 

When I deploy the same app to my iPhone and play the same url it works perfectly.

Any ideas what could be causing this issue.

I start the player like this (with all the fields set correctly for it):
          playerClappr = new Clappr.Player({
            poster: img_url,            
            watermark: img_url,            
            playback: {
              playInline: true,                
            },                                                      
            source: video_url,                   
            parentId: "#"+div_id,
            width:item_w,
            height:item_h,
            autoPlay: true,                                               
          });

**Comment by pedrochamberlain** [comment]
Hi @PreDeToRLinux, could you share a print or log of the error you're facing?

[A good idea for debugging would be to enable Clappr's logs.](https://github.com/clappr/clappr#how-can-i-log-messages-with-clappr)

**Comment by PreDeToRLinux** [comment]
Hi @pedrochamberlain 

Please see the screenshot below.

![image](https://user-images.githubusercontent.com/6190756/122877259-b4cd9a00-d336-11eb-8bcb-883c736b137e.png)

**Comment by PreDeToRLinux** [comment]
@pedrochamberlain any ideas on this issue?

**Comment by leticiafernandes** [comment]
@PreDeToRLinux The message above is a warning and probably not what is causing your playback to throw an error. What is the behavior you expect and what problem are you facing for it?

**Comment by PreDeToRLinux** [comment]
@leticiafernandes I am trying to play a video on a iPad as an embedded app.

I take the exact same app and video playback works fine on iPhones. but fails with the above error on a iPad.
I then take this code and open it on safari on the iPad and it works fine.

It seems to be linked to the fact that its running via cordova, but this is simply a webview and works fine on iPhone.

**Comment by PreDeToRLinux** [comment]
As a sample here is my flow:
1) I have a image and a div with a onclick event (this works fine)
2) On the click I fetch the playback url and setup a player with autoplay & inline play (this works fine and fetches the m3u8 files)
3) on the iPad it then gives the error above and this screen.

![image](https://user-images.githubusercontent.com/6190756/123765215-d3e3a300-d8c5-11eb-8f40-71dd024bedcf.png)

**Comment by kslimani** [comment]
@PreDeToRLinux i think it is because the "user interaction" is lost when you perform the fetch.

Take a look at the provided example in [this comment](https://github.com/clappr/clappr/issues/1680#issuecomment-410649572). _(and put your fetch logic just after the `player.consent()` call)_

**Comment by PreDeToRLinux** [comment]
@kslimani would that be the case since it works on iPhone and the same code works fine on safari just not when its served via cordova ?

I tried the following:
          playerClappr[video_content_id] = new Clappr.Player({
            mimeType : 'application/x-mpegURL',            
            poster: img_url,            
            playback: {
              playInline: true,                
            },                                                      
            source: responseData.video_url,                   
            parentId: "#"+div_id,
            width:item_w,
            height:item_h,
            autoPlay: true,                                               
          });
          
          playerClappr[video_content_id].consent();

And its still not working.

Example: 
![image](https://user-images.githubusercontent.com/6190756/123791854-3cd81480-d8e0-11eb-942e-941a770ae3b8.png)
Simple div with a image and data.

From there when the user clicks on the div, I fetch the playback url and create the clappr player instance (as above)
with or without autoplay it fails.


I also tried creating a player with no source, then on click doing the consent and load manually,  the player still failed.
1st Click:
    playerClappr[video_content_id] = new Clappr.Player({
      mimeType : 'video/mp4',            
      poster: img_url,            
      playback: {
        playInline: true,                
      },                                                      
      source: Clappr.Utils.Media.mp4,                   
      parentId: "#"+div_id,
      width:item_w,
      height:item_h,
      autoPlay: true,                                               
    });

2nd Click:
          playerClappr[video_content_id].consent();
          
          playerClappr[video_content_id].load(responseData.video_url,"application/x-mpegURL",true);

**Comment by kslimani** [comment]
Please note that autoplay policies differs between devices and also browsers. (and therefore behaviors).

Let me attempt to explain the mechanisms :

When autoplay is not allowed in a browser, the common scenario is it require a __"user interaction"__ to allow the video element to start playing video content. _(for example, a mouse click event)_.

In most cases, when user perform interaction the video element _MUST_ be already inserted in the dom.
_(ie: Clappr player instance already exists)_.

Technically, a Video element is "consented" when play() or load() methods are called as a result of user interaction.
_(Note also that browsers will "store" consent for either the single Video element or for the entire page)._

When you perform a fetch inside the onclick event listener, if the user interaction _(mouse click)_ is not stored _(by calling load() or play() on Video element)_ then is it __lost__ _(and fail to start video after fetch)_.

This is one of the reasons that Clappr player instance expose a consent() method in adition to play().
_(technically, the consent() method just call load() method of the internal playback video element)_.

Clappr player provide also a mechanism to internally "recycle" video elements _(to keep stored consent)_, instead to create new each time you load another content url.
_(for example when using playyer.load() or player.configure() methods)_

@PreDeToRLinux does these explanations help you to understand better what is happening in your app ?
