### ISSUE TITLE
Trying to implement fullscreen

### ISSUE THREAD

**Issue by manollas2015** [clappr/clappr#2019]
**What do you want to do with Clappr?**
I am trying to go fullscreen programmatically but getting error.

**What have you tried so far?**
This Works
http://clappr.io/demo/index.plainhtml5.html#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2NsYXBwci5pby9oaWdobGluZS5tcDQnLAogIHBvc3RlcjogJ2h0dHA6Ly9jbGFwcHIuaW8vcG9zdGVyLnBuZycsCiAgbXV0ZTogdHJ1ZSwKICBoZWlnaHQ6IDM2MCwKICB3aWR0aDogNjQwCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOwpwbGF5ZXIuY29yZS5tZWRpYUNvbnRyb2wudG9nZ2xlRnVsbHNjcmVlbigpOw==
This Dont
https://jsfiddle.net/t6rkLw84/1/

**Comment by kslimani** [comment]
In web browsers, a __"user interaction"__ is required to toggle to fullscreen. _(for example a mouse click)_

In your jsfiddle, if you add a button which toggle fullscreen, it will work if you click on it.
