### ISSUE TITLE
play button position in small size

### ISSUE THREAD

**Issue by audiobras** [clappr/clappr#2020]
Hello,

I see a strange thing. I am trying to use the clappr to play some hls audio only streams and then I used that config:

`var player = new Clappr.Player({
  source: 'https://myurl/playlist.m3u8',
parentId: '#player',
  poster: '',
  height: 45,
  hideMediaControl: false,
  width: 325,
 
});`

In demo page the play button stay align in middle and in the center. But in my page the play button stay scruffy near the bottom of the player.

[https://fb.radiosnaweb.com/clapp/sample.png](https://fb.radiosnaweb.com/clapp/sample.png)

How can I handle that and why in http://clappr.io/demo it is ok and in my code not?

**Comment by kslimani** [comment]
The issue you describe seems to be a CSS conflict: use browser debug tool to inspect and check css rules applied on play button.

**Comment by audiobras** [comment]
I try to simulate in a page without other css stuff: [https://v2.atendimento.inf.br/teste.html](https://v2.atendimento.inf.br/teste.html )

**Comment by kslimani** [comment]
It is the background image you configured as poster : https://fb.radiosnaweb.com/clapp/play9.png

**Comment by audiobras** [comment]
> It is the background image you configured as poster : https://fb.radiosnaweb.com/clapp/play9.png

But the issue is the vertical alignement of the play button in stop state. It stay not in the middle, it stay near the botton. I did not find a reason for that misalignment. Try stop the play and you will see where the play button pops up.

**Comment by audiobras** [comment]
I found out what was affecting the placement of the play button in the stopped state:

this tag on my page before the <html> tag:

<!doctype html>
