### ISSUE TITLE
Clappr support HEVC playback on Tizen or webOS?

### ISSUE THREAD

**Issue by Nachompiras** [clappr/clappr#2021]
Hi everybody.

Has anyone tried playing HLS HEVC on tizen or webOS with clappr ?.

HLS.js doesn't works for me.

**Comment by joaopaulovieira** [comment]
Hi @Nachompiras !

I think you'll need to use one custom Clappr playback implementation for that. We start to build one new playback implementation to be used on smart TVs that have compliance with the HbbTV specs: https://github.com/clappr/clappr-html5-tvs-playback

Maybe this playback works for you or at least inspires you to build one new Clappr playback for other smart TVs devices that fit with your needs (:

**Comment by iamaamir** [comment]
can we integrate this with bitmoving or any custom player/provider ?

**Comment by iamaamir** [comment]
> Hi @Nachompiras !
> 
> I think you'll need to use one custom Clappr playback implementation for that. We start to build one new playback implementation to be used on smart TVs that have compliance with the HbbTV specs: https://github.com/clappr/clappr-html5-tvs-playback
> 
> Maybe this playback works for you or at least inspires you to build one new Clappr playback for other smart TVs devices that fit with your needs (:

can we integrate this with bitmoving or any custom player/provider  on TV?
