### ISSUE TITLE
Using any player events from the page.

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr#2024]
Hi!
I'm wondering if I can set a handler, for example, for the CORE_ACTIVE_CONTAINER_CHANGED event from a script on the page.

I tried this right after creating the Clappr.Player instance:
`player.on(Clappr.Events.PLAYER_READY, () => console.log('PLAYER READY'))
  player.listenTo(player.core, Clappr.Events.CORE_READY, () => console.log('CORE READY'))`
But both the player and its core had been ready for that moment, and nothing I'd got.

**Comment by kslimani** [comment]
You can create a core plugin to achieve this.

Here a simple ES5 example you can try on [Clappr demo page](http://clappr.io/demo/) :

```javascript
var playerElement = document.getElementById("player-wrapper");

var MyPlugin = Clappr.CorePlugin.extend({
  name: 'my_plugin',
  bindEvents: function() {
    this.listenTo(this.core, Clappr.Events.CORE_ACTIVE_CONTAINER_CHANGED, function() {
      console.log('core container changed !');
    });
  },
});

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  height: 360,
  width: 640,
  plugins: [MyPlugin],
});

player.attachTo(playerElement);
```

**Comment by sapolio** [comment]
@kslimani, thank you.
