### ISSUE TITLE
How to refresh Clappr automatically when it shows an error?

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#2027]
Some time ago I asked about how to automatically refresh Clappr before displaying an error (using MPD / DASH)
With this code I solved the problem:

shakaConfiguration: {
manifest: {retryParameters: {maxAttempts: Infinity}},
streaming: {retryParameters: {maxAttempts: Infinity}},
drm: {retryParameters: {maxAttempts: Infinity}},
},

Now I'd like to know what code do I have to use for M3U8 / HLS.

Thank you in advance.

**Comment by joaopaulovieira** [comment]
Hi @hijuuijj HLS.js has on session on the docs about fatal error recovery: https://github.com/video-dev/hls.js/blob/master/docs/API.md#fatal-error-recovery

**Comment by hijuuijj** [comment]
> Hi @hijuuijj HLS.js has on session on the docs about fatal error recovery: https://github.com/video-dev/hls.js/blob/master/docs/API.md#fatal-error-recovery

Could you give me a hand, please? I have no idea how to do it even reading the document.

Thanks.

**Comment by kslimani** [comment]
Internally, hls playback does [trigger an error](https://github.com/clappr/hlsjs-playback/blob/master/src/hls.js#L335) when it is a fatal error.

If you require the player to automatically attempt to retry to play source, you need to add some code.

There are [two examples](https://github.com/clappr/clappr#example) in Clappr readme.

**Comment by hijuuijj** [comment]
> Internally, hls playback does [trigger an error](https://github.com/clappr/hlsjs-playback/blob/master/src/hls.js#L335) when it is a fatal error.
> 
> If you require the player to automatically attempt to retry to play source, you need to add some code.
> 
> There are [two examples](https://github.com/clappr/clappr#example) in Clappr readme.

These examples have not worked for me. I get the same erroor:

Error code: hls:networkError_manifestParsingError

All I can do is replace the error message with the play button

`disableErrorScreen: true,`

Any other suggestion?
