### ISSUE TITLE
Change of Spanish Translation

### ISSUE THREAD

**Issue by hugocm99** [clappr/clappr#2029]
On clappr.min.js the Spanish translation of the controls is not accurate. The correct one should be like this:
es:{live:"En Directo",back_to_live:"volver al directo",disabled:"Video no disponible",playback_not_supported:"El video no se puede reproducir en su nevegador. Utilice un navegador diferente."}

**Comment by flavioribeiro** [comment]
Hey @hugocm99, you can submit a PR with the changes on https://github.com/clappr/clappr-core/blob/master/src/plugins/strings/strings.js#L61-L66. 

I'm not fluent in Spanish but was looking into [this blog](http://trampalabras.blogspot.com/2017/12/cual-es-la-diferencia-entre-en-vivo-y.html) and just thinking about the differences between `en vivo` and `en directo`. For a lot of the content people stream in the wild, `en vivo` would probably be an accurate message. What do YouTube and others use normally?

**Comment by hugocm99** [comment]
Well, the thing is that you need to separate maybe between Spanish of Spain and Spanish of South America.
In this case for Spanish from Spain will be better " En Directo" but for SouthAmerica one it's more used "En Vivo"
That's main point and the first difference

Also

**Comment by flavioribeiro** [comment]
That makes sense. I can see that on [this line](https://github.com/clappr/clappr-core/blob/master/src/plugins/strings/strings.js#L107) we're exporting the Spanish portion as  `es-419` (es-419 – Spanish appropriate for the Latin America and Caribbean region, using the UN M.49 region code) so that looks correct. I would suggest a pull request extending the object with `es-ES` and make them both available.

**Comment by hugocm99** [comment]
Yeah, would be great, anyway @flavioribeiro I'll correct the Spanish Lathinoamerican part cause some of the translations are not correct like the one of "Disable" that might be "no disponible" I think

**Comment by pedrochamberlain** [comment]
Closing this issue since the translation was fixed in https://github.com/clappr/clappr-core/pull/64
