### ISSUE TITLE
How to use more than one source

### ISSUE THREAD

**Issue by hugocm99** [clappr/clappr#2030]
I have been trying with the player using more than hls one source, for the case that when the first one doesn't work, it should go to the second one, but it stops in the first one and doesn't go to the second one.
There's a possibility that when the first source doesn't work the player go automatically to the second one?

**Comment by kslimani** [comment]
There is no internal mechanism to handle alternate source. But you can achieve this using error handler, [here a simple example](https://github.com/clappr/clappr#example).

**Comment by pedrochamberlain** [comment]
Closing this issue since it has already been answered.
