### ISSUE TITLE
Iphone (IOS 15) not work (all browsers)

### ISSUE THREAD

**Issue by IkiaeM** [clappr/clappr#2042]
Here is the error that the console returns when I try to launch the stream...

CONSOLE : 

DOMException { line: 1, column: 175869, sourceURL: "https://cdn.jsdelivr.net/clappr/latest/clappr.min.js" }

**Comment by LewisSmallwood** [comment]
I'm also experiencing this problem  since upgrading to iOS 15.

**Comment by utilsites** [comment]
Our videos with clappr are also not working, tested with iOS 15 on IPhone 11, 10, 9 and 8.
We were not able to see errors, the video just keeps loading forever, confirmed that on iOS 15.
On IPhone 9 and 11 we were able to get the problem only after updating from iOS 14 to iOS 15, so we confirm that iOS 15 is the problem.
It is strange that the problem does not only occurs in Safari but also on Chrome for IPhone, so the problem seems related with the operation system itself?
Need help, thanks.

**Comment by LewisSmallwood** [comment]
Similar issues have been reported on GitHub in other repositories. (e.g. [Video not displaying in iOS 15](https://github.com/ogoguel/activegs-ios/issues/15))

I have submitted a bug report to Apple, awaiting their response.

**Comment by pedrochamberlain** [comment]
Sorry for the late reply.

Is the problem still happening? I accessed [Clappr's demo page](http://clappr.io/demo/) with an iPhone XR running iOS 15 and the player loaded and streamed successfully. Could you update us on that? @IkiaeM 

Perhaps Apple has already fixed the issue. Did they answer you on the matter? @LewisSmallwood

**Comment by IkiaeM** [comment]
I just tried the same as you and indeed on your "Demo" page it seems to work. (Iphone XR max, IOS 15.1)
But it still doesn't work for me. The console does not return any error. And my code looks like this:

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<div id="player"></div>
    <script>
        var player = new Clappr.Player({
            disableErrorScreen: true,
            source: 'https://xxx.com/x.m3u8',
            poster: 'https://xxx.com/x.png',
            parentId: '#player',
            width: '100%',
            height:'100%',
            mute: false,
            watermark: 'https://xxx.com/x.png',
            position: 'top-left',
            watermarkLink: 'https://xxx.com'
        });
    </script>
```

This same code works perfectly on your demo site but not on my site, I don't understand why... Any idea?

**Comment by kslimani** [comment]
Be carefull @IkiaeM , on the code snippet you provided, it is not the same Clappr player version as demo page.

For latest 0.4.x player version, replace your jsDelivr script url by :

```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.min.js"></script>
```

**Comment by IkiaeM** [comment]
I just changed and it still doesn't seem to be getting better... @kslimani
I used different browsers and private browsers to make sure there were no cache issues.
And according to the safary console, it doesn't even seem to try to load the video stream.. Mais le charge correctement sur la demo..

**Comment by utilsites** [comment]
The[ clappr demo page](http://clappr.io/demo/) is using a mp4 file as source.
In our case is a m3u8 file (using HLS), a big diference I think, can be because of that that it does not work on iOS 15?

**Comment by IkiaeM** [comment]
I tried with the demo and a m3u8 source and it works correctly with my code on the demo but not on my site... I really don't know what the difference is... My site is in https that's the only thing I see...

**Comment by utilsites** [comment]
Is clappr using native browser media to fetch hls our is using a wrapper lib?

**Comment by kslimani** [comment]
Clappr is internally using hls.js for m3u8 playback (for browser like Chrome or Firefox). But note that on browser like Safari, it use native html5 video for playback.

**Comment by utilsites** [comment]
Ok that difference is important, and the prob was related to that.

**Comment by ssamjh** [comment]
I'm having users reporting this too but since I don't have an iPhone to test it makes it hard to diagnose. I'm using m3u8 streams.

**Comment by thomscoder** [comment]
Same issue on Iphone with iOS 15.5

**Comment by leaofelipe** [comment]
Hi guys, we just released a [new Clappr version](https://github.com/clappr/clappr/releases/tag/0.5.0) with HLSJS update. Can you test if this issue continues?

**Comment by utilsites** [comment]
> Hi guys, we just released a [new Clappr version](https://github.com/clappr/clappr/releases/tag/0.5.0) with HLSJS update. Can you test if this issue continues?

When it will be published to [](https://www.npmjs.com/package/clappr?activeTab=versions) ?

**Comment by leaofelipe** [comment]
@utilsites I think you are looking at the legacy versions.
Since de version 4, we've changed a lot of things: https://www.npmjs.com/package/@clappr/player

You can see all the breaking changes from the legacy `v0.3.x` to `0.4.x` here: https://github.com/clappr/clappr/releases/tag/0.4.0

**Comment by utilsites** [comment]
Ahh didn't notice that...
It would be good that you could make that warning in [npmjs](https://www.npmjs.com/package/clappr?activeTab=versions) 
Also when we search on npm for clappr it's not clear which project is the latest:
![image](https://user-images.githubusercontent.com/15893370/212437321-6e11067b-4538-4f82-8524-d1c43277bbbd.png)
Also in github releases, and clappr website, could have links to the npmjs website, I thing it does note have.
Also in the http://clappr.io/ the example is still using the legacy url, so it's confusing.

**Comment by leaofelipe** [comment]
Nice @utilsites! I'll do this soon as possible. Thank you very much!

**Comment by utilsites** [comment]
> Nice, @utilsites! I'll do this soon as possible. Thank you very much!

Ok on NPM but on [clappr website](http://clappr.io/) is still missing update:

![image](https://github.com/user-attachments/assets/f5ee9bec-a332-4feb-b492-979f58899cbd)
