### ISSUE TITLE
Click to Stop for Livestreams

### ISSUE THREAD

**Issue by radosslav** [clappr/clappr#2048]
**What do you want to do with Clappr?**

I need click to stop functionality for HLS, m3u8 livestreams similar to click to pause for the ordinary mp4 files.

**What have you tried so far?**

I spend the last two days trying literally everything that I can - the official plugins, old repos with custom codes, and even trying to put invisible div on top of the player that play/stop onclick, but this broke double click to fullscreen functionality and showing controls on mouseover.

If someone with deep JS knowledge can help with this because I'm primary backend and something at first glance so simple turned into a real nightmare...

**Comment by pedrochamberlain** [comment]
Hello @radosslav! 

I'm not perfectly sure if you need a button that **pauses** an HLS livestream with DVR enabled, or a button that **stops** the livestream altogether.

If the former is the case, please check the following example: I've built a [demo where Clappr loads a LIVE, DVR-enabled HLS source](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9jcGgtcDJwLW1zbC5ha2FtYWl6ZWQubmV0L2hscy9saXZlLzIwMDAzNDEvdGVzdC9tYXN0ZXIubTN1OCcsCiAgcG9zdGVyOiAnaHR0cDovL2NsYXBwci5pby9wb3N0ZXIucG5nJywKICBtdXRlOiB0cnVlLAogIGhlaWdodDogMzYwLAogIHdpZHRoOiA2NDAKfSk7CgpwbGF5ZXIuYXR0YWNoVG8ocGxheWVyRWxlbWVudCk7Cg==). The pause button is built into the media control. Not much is required.
