### ISSUE TITLE
Autostart HLS stream

### ISSUE THREAD

**Issue by Byskoven62** [clappr/clappr#2049]
Hello.

I need a little help. Is it possible to make the player autoload / autostart when it receives a hls stream?

I have tried with this code:
    onError: function (e) {
      setTimeout (function () {player.configure (player.options);}, 15000);
    },

But I have made it so that the player disappears when there is no stream it is with this code:

onStop: function (e) {
$ (". player"). hide ();
    },

onPlay: function (e) {$ (". player"). show ();
    },

But when it reloads, the player is briefly displayed so that it will look as if it is flashing

I am using nginx server with rtmp module on Rasberry pi 

Sorry for my English!

**Comment by kslimani** [comment]
To attempt to autostart source, just add/set `autoPlay: true` in your player options of configure() method call. (onError event handler).

Also, take the time to read [autoplay section](https://github.com/clappr/clappr#play_or_pause_button-about-autoplay) in Clappr documentation.
