### ISSUE TITLE
[warn][Loader] missing version information for ...

### ISSUE THREAD

**Issue by hermify** [clappr/clappr#2055]
Clappr 0.4.7

After update, I get warning in Console:   **_[warn][Loader] missing version information for ...._**
for my selfwritten plugins, I wrote based on some examples on here
(https://github.com/clappr/clappr/wiki/Our-first-plugin)

Where do i have to set version information? Any tips or docs out there?

**Comment by kslimani** [comment]
Yes, you have to implement the [supportedVersion()](https://github.com/clappr/clappr-plugins/blob/master/src/plugins/poster/poster.js#L13) getter.
