### ISSUE TITLE
Play

### ISSUE THREAD

**Issue by heinhtwe** [clappr/clappr#2056]
**What do you want to do with Clappr?**
I want to play the livestream file. I add this m3u8 link “ https://i-am-so-cool.licenses4.me/cdn/premium31/chunks.m3u8?md5=Njgc81Udw63VE0wHYJXncg&expires=1646751049” into the source as the following. 

<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<div id="oper"></div>
<div id="vid"></div>
<script>
 player = new Clappr.Player({
 source: "https://i-am-so-cool.licenses4.me/cdn/premium31/chunks.m3u8?md5=Njgc81Udw63VE0wHYJXncg&expires=1646751049",
 mimeType: "application/x-mpegURL",
 autoPlay: true, 
 height: "400",
 width: "100%",
 plugins: {"core": [LevelSelector]}, 
 parentId: "#vid"});
</script>

**What have you tried so far?**
But the player didn’t play the file. Why? How can I fix it? My blogger site is https://www.football-live.co.uk/?m=1

**Comment by pedrochamberlain** [comment]
Hello @heinhtwem! Could you share more information regarding this issue? I fear it may be related to your CDN.

I tried loading the livestream source you shared on my machine, and I'm receiving a `403` error when a request to https://uacdn.ga/ is made by your CDN. You can check that by your browser's Network tab.

Furthermore, I did let Clappr try to load the stream for a few more minutes. It did occasionally play for a few seconds, but it quickly stopped after that.

**Comment by the-poor-gamer-124** [comment]
it is because this person is trying to use someone elses stream lol
