### ISSUE TITLE
Is JW Player much faster than Clappr?

### ISSUE THREAD

**Issue by robocopz** [clappr/clappr#2058]
Some streams take much longer to look sharp (change the bitrate) when using Clappr.
With JW Player they look sharp almost instantly.
Is it a Clappr problem? can it be optimized in any way?
Also I can't change the audio channel either, which is a bit disappointing.

**Comment by hijuuijj** [comment]
Yes I have stopped using clappr. It feels like a bit slow and outdated. Jwplayer is definitely much better in my opinion
Anyway, Clappr has been very useful to me these years
