### ISSUE TITLE
Play partially downloaded segments

### ISSUE THREAD

**Issue by anesuc** [clappr/clappr#2061]
**What do you want to do with Clappr?**
Is there a way of playing a partially downloaded segment like we do when playing a normal mp4 file? Like if I have a 30 second segment as an example, is there a way to play that segment as the rest of it is being downloaded? Either with mpeg dash or hls. The is in relation to converting an mp4 file to either mpeg dash or hls in order to properly utilise a lot of plugins and such related to clappr.

**What have you tried so far?**
Several config options and searching around online

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
