### ISSUE TITLE
Clappr video not showing on website

### ISSUE THREAD

**Issue by Delrichie** [clappr/clappr#2067]
Please can someone tell me what's wrong with this code? The player is not displaying on my site

<head>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script> <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr-playback-rate-plugin@latest/lib/clappr-playback-rate-plugin.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/cdnbye@latest/dist/hlsjs-p2p-engine.min.js"></script> <script type="text/javascript" src="//cdn.jsdelivr.net/npm/cdnbye@latest/dist/clappr-plugin.min.js"> </script>
</head>
<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({
      source: "",
      mimeType: "application/x-mpegurl",
      autoPlay: true,
      width: "100%",
      height: "250",
      parentId: "#player"
    plugins: [CDNByeClapprPlugin], 
      playback: { 
      hlsjsConfig: { 
       maxBufferSize: 0,
        maxBufferLength: 10, 
          liveSyncDurationCount: 10,
            p2pConfig: { 
              live: true, } } }
    plugins: [PlaybackRatePlugin],
    player.on(Clappr.Events.PLAYBACK_ERROR, function(error){console.log(error);});
  </script>
</body>

**Comment by nisiharayosi** [comment]
Try removing "<!DOCTYPE html>" from the HTML of the site containing the player.
Might be a problem with the current version.

This solved it for my site.
