### ISSUE TITLE
How can I set a play range in Clappr

### ISSUE THREAD

**Issue by nelson777** [clappr/clappr#2073]
I need a way to set a play range. Say that my video durantion is 01:45:00 minutes long. I want to make the player play only from customizable range, say from 00:07:00 till 01:35:00 (blocking 7 minutes in the start, 10 minutes in the end in this case). I want the user to be able to customize range with a control such as this:

[<img src="https://i.imgur.com/aO2P1S3.png" width="300"/>](https://i.imgur.com/aO2P1S3.png)

I started to code capturing onseek event and if outside the range I would seek to the nearest valid position. But while doing this I thought that maybe there is some already implemented range function that I'm not aware of or some plugin.
Is there any way of doing this with a better strategy than the one I described above ? Thanks.

**Comment by leaofelipe** [comment]
Hi @nelson777 , unfortunately we don't have any plugin related to this play range feature, and I don't know any created by the community. But, talking about the strategy, this plugin may need a more complex solution than just using `onsSeek` events. Involving Media Control and Playbacks, for example.

**Comment by nelson777** [comment]
I understand. I couldn't do it easily in Clappr so I used Video.js and rangeslider plugin. 
Thanks.
