### ISSUE TITLE
Gatsby Build failure due to "window" is not available during Server-side-rendering

### ISSUE THREAD

**Issue by marksteven** [clappr/clappr#2076]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
Chrome - Safari - Firefox
**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Mac Big Sur 11.6.8
**Clappr Version**: 0.3.8
^0.3.13
**Steps to reproduce**:
Use any Gatbsy starter EG npx gatsby new gatsby-starter-hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
* first step
* Add Clappr
* then second step
* add a simple video player page I used many but last test was this one  React Hooks one ( https://codesandbox.io/s/34b28?file=/src/App.js )

If you then use "Gatsby develop" the video player will load fine on localhost:8000
Leading you to believe all is good.

However if you then do a "Gatsby build" you get
" ERROR 
Page data from page-data.json for the failed page "/ClapprPlayr/": {
  "componentChunkName": "component---src-pages-clappr-playr-js",
  "path": "/ClapprPlayr/",
  "result": {
    "pageContext": {}
  },
  "staticQueryHashes": []
}
failed Building static HTML for pages - 3.992s
 ERROR #95312 
"window" is not available during Server-Side Rendering."

* Did you try to reproduce this issue at http://cdn.clappr.io/?
* Yes unable to

What forum notes I was able to find it seems no one has been able to fix this "window" error
Hoping someone in the community has an answer

**Comment by marksteven** [comment]
To update.
Gatsby using react-hls": "^0.0.8" instead of clappr works with no "window" error
That might give a clue to someone better than me at fixing errors

**Comment by marksteven** [comment]
Hi Leo, 
Thankyou very much for getting back to me on this. It has been consuming alot of time before I realised what was going on.
I agree it is not a Clappr issue and in fact turns out to be a simple one (being the window gets called on build) 
I was looking at going into the node_modules and modifying Clappr but then realised the next time project was built it would revert to the old code and fail again.
The engineers from Gatsby got back to me and mentioned people would have similar results from Netify as well as Gatsby with errors so thats quite a few people so might be worth fixing. 
They also pointed me to a page on how to fix it for myself. 
But also recommended contacting Clappr about it as it appears to be a quick fix and would stop others having the same issues.
So the page is this one
https://www.gatsbyjs.com/docs/debugging-html-builds/#how-to-check-if-window-is-defined

Hope this helps you and others

Cheers
Mark

**Comment by leaofelipe** [comment]
Thank you for your suggestion @marksteven! I'll discuss this issue with the rest of the team.
