### ISSUE TITLE
use latest version hls.js

### ISSUE THREAD

**Issue by vdalex25** [clappr/clappr#2077]
i have m3u8 playlist witch playing in native hlsjs but doesnt play in clappr 
how can i use clappr with latest version hlsjs

**Comment by leaofelipe** [comment]
@thiagopnts Nice! 👏🏻👏🏻👏🏻

**Comment by leaofelipe** [comment]
We've just released a [Clappr new version](https://github.com/clappr/clappr/releases/tag/0.5.0) with the new hlsjs version 🎉
