### ISSUE TITLE
Design and add a Favicon to the page

### ISSUE THREAD

**Issue by soustab10** [clappr/clappr#2082]
**Is your feature request related to a problem? Please describe.**
Adding a favicon to the webpage.

**Describe the solution you'd like**
I would like to design an favicon, take review from developers and then implement it the webpage.

**Screenshots:**

The present webpage looks like this, which does not look good:
![image](https://user-images.githubusercontent.com/95632583/195086401-19daef2d-9e3f-470a-a754-c28814be0878.png)

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by calvinmorett** [comment]
### Clappr Favicon
![image](https://user-images.githubusercontent.com/11654917/201498911-c88db6dd-b4b5-4beb-998e-fe0a312aba92.png)

**Files**:

> - about.txt
> - android-chrome-192x192.png
> - android-chrome-512x512.png
> - apple-touch-icon.png
> - favicon.ico
> - favicon-16x16.png
> - favicon-32x32.png
> - site.webmanifest
> 

Download
[https://wetransfer.com/downloads/134760a44518e0f00c7bf399b41191f720221112234304/37d58436304f88b599f6f83ff4d1fe3720221112234313/213993?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid](https://wetransfer.com/downloads/134760a44518e0f00c7bf399b41191f720221112234304/37d58436304f88b599f6f83ff4d1fe3720221112234313/213993?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)

> The [emoji graphics](https://github.com/twitter/twemoji/blob/master/assets/svg/1f3ac.svg) are from the open source project [Twemoji](https://twemoji.twitter.com/). The graphics are copyright 2020 Twitter, Inc and other contributors. The graphics are licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/). You should review the license before usage in your project.

---

**Installation**
1. Place the files in the root directory of your website.

> - android-chrome-192x192.png
> - android-chrome-512x512.png
> - apple-touch-icon.png
> - favicon-16x16.png
> - favicon-32x32.png
> - favicon.ico
> - site.webmanifest


2. Next, copy the following link tags and paste them into the head of your HTML.
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
```

**Comment by TheXro** [comment]
@leaofelipe @calvinmorett   can i you assign this to me
