### ISSUE TITLE
Add clappr link to the clappr logo in readme.md file

### ISSUE THREAD

**Issue by Abubakrce19** [clappr/clappr#2084]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by leaofelipe** [comment]
Hi, @Abubakrce19! Can you please fill out the form correctly? 👍🏻

**Comment by leaofelipe** [comment]
Issue Associated with this PR: https://github.com/clappr/clappr/pull/2085
