### ISSUE TITLE
Controls bug

### ISSUE THREAD

**Issue by mscodepl** [clappr/clappr#2088]
i added `controls: false,` code to player but controls already showing

**Comment by pedrochamberlain** [comment]
Hi @mscodepl, 

I've verified your issue, and it seems to work normally. Bear in mind that, as the `@clappr/core` documentation regarding the `playback.controls` option explains, this option currently only works when using the `HTML5Video` playback.

Check the following video for reference, I'm running the `@clappr/core` project without any changes:

https://user-images.githubusercontent.com/40682476/213805407-50c451fc-0ac4-4ce4-8767-af44744a96e4.mp4
