### ISSUE TITLE
Improve our logging plugin

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#209]

**Comment by dusterio** [comment]
It would be nice to log current TS segment name, maybe current bandwidth (adaptive HLS) when it's being switched

**Comment by flavioribeiro** [comment]
hey @dusterio we can do it by requesting these informations from [flashls](flashls.org) swf. Can you tell me the big picture of your application so we can try to implement this?

**Comment by dusterio** [comment]
I'm making an application that streams (live) random worldwide videos, and I'm planning to add a dynamic (Google) map pointing to the origin of the video. Whenever a TS segment changes – map marker moves to the new point, so JS needs to be able to handle new segment events. 

If you request information from flashls – in case of HTML5 video capable browsers, you won't get anything? I would have to behave differently depending on video player format.

**Comment by dusterio** [comment]
By the way, since you mentioned flashls – are you still using flashls for SWF mode? I don't see any references anywhere

**Comment by flavioribeiro** [comment]
@dusterio yes, clappr use flashls in case the browser doesn't have HLS native support. Our bootstrap is simple - when creating the container, the factory [asks](https://github.com/clappr/clappr/blob/master/src/components/container_factory/container_factory.js#L31-L33) for every playback plugin if it can play the given source and if so it returns the chosen playback.  On Safari@mac, WiiU and Playstation 4, the html5_video playback returns true for m3u8 sources, meaning that clappr will play it on `<video>` tag. 

Said this, we need to take a look on internal browser implementations to check if it dispatches events when finishes downloading TS segments. On the other hand, flashls dispatches this event and there's an external plugin that already listen this event. You can check it [here](https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js#L42).

**Comment by dusterio** [comment]
@flavioribeiro by the way, when including this said plugin (Level Selector), I get this:
Uncaught Error: Cannot find module 'underscore'
Uncaught ReferenceError: LevelSelector is not defined
It doesn't work out of the box. But yes – I will try to bind to important events the same way and see how it goes

**Comment by flavioribeiro** [comment]
@dusterio we removed underscore from last clappr bundle causing the plugins to be deprecated. @lucasmundim - levelselector maintainer - is already working on an update and I'm sure it will be released this week. Try using our [generator](github.com/clappr/generator-clappr-plugin) to build your plugin boilerplate and bind a callback to `fragmentloaded` event. Tell me if it works for your use case.

**Comment by dusterio** [comment]
@flavioribeiro by the way, did you modify flashls? does it still have "fragmentplaying" event?

**Comment by flavioribeiro** [comment]
@dusterio you can find our flashls fork [here](https://github.com/clappr/flashls).  Instead of the raw flashls' ChromelessPlayer we use [this](https://github.com/clappr/flashls/blob/master/src/com/globo/Player.as) one. [Comparing](https://github.com/clappr/flashls/compare/prod...mangui:master) our branch with mangui's master branch, we're not too much outdated but with [dev](https://github.com/clappr/flashls/compare/prod...mangui:dev) we are. I'll check with @mangui if makes sense to merge with dev and if so we can make `fragmentplaying` event available. For now, I would go with `fragmentloaded` until we solve this.

**Comment by towerz** [comment]
I think we can close this issue, since 0a83e0a7d34313531caa4e1373528af74f5821f9 added support for showing objects on player log.

We still could add better tuning of log levels, but it's not really necessary for now.
