### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by InsolenceWillow** [clappr/clappr#2102]
Is There A Way To Put A Backup Stream On Clappr, Like When One Stream Doesn't Work, The Backup One Pops Up Too!

If You Need My Clappr HTML Code, Here: ` <head>  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js">  </script></head><body>  <div id="player"></div><script>    var player = new Clappr.Player({source: "https://pluto-live.plutotv.net/egress/chandler/pluto01/live/VIACBS02/master.m3u8", parentId: "#player", mediacontrol: {seekbar: "#ff0000", buttons: "#d94f00"}, autoPlay: "true"});  </script></body>        `

**Comment by Ben-lad** [comment]
Hi,

Regarding your question about adding a backup stream on Clappr, one way to achieve this is to use the error event provided by Clappr to switch to a backup stream in case the primary stream fails to load.

Here is an example code that demonstrates this approach:

`var primarySource = 'https://primary-stream-url.com/live/master.m3u8';
var backupSource = 'https://backup-stream-url.com/live/master.m3u8';

var player = new Clappr.Player({
  source: primarySource,
  parentId: '#player',
  autoPlay: true
});

player.on('error', function() {
  player.load(backupSource);
});
`
In this code, the error event is used to listen for any errors that occur when loading the primary stream. If an error is detected, the load method is called to switch to the backup stream.

**Comment by InsolenceWillow** [comment]
@Ben-lad Thank You, I'll Try That Code Right Now!
