### ISSUE TITLE
website server issue

### ISSUE THREAD

**Issue by Obamalug** [clappr/clappr#2108]
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)

**Clappr Version**: 0.3.8

**Steps to reproduce**:

* first step
* then second step
* I was expecting X but instead it shows Y

**Does it happen only in your streaming?**
* If it does, please provide your streaming URL.

**To consider:**
* Did you try to reproduce this issue at http://cdn.clappr.io/?
* Did you check if it's a CORS problem?

**ps:** Please, attach images, logs or whatever you think might be helpful.

**ps:** Feel free to clean this if your issue is different.

**Comment by nedmax** [comment]
Is there a problem here? 
Can we close this?
