### ISSUE TITLE
Create new home page design for Clappr docs

### ISSUE THREAD

**Issue by paulocesarjr** [clappr/clappr#2123]
Hey folks, we would like to create a new website using docusaurus and this issue is just to create a layout for the home page. You can use Figma and share the layout with us, we will probably create another issue to implement this layout after [merging the docs in monorepo](https://github.com/clappr/clappr/pull/2130).

We have some references: [React](https://react.dev/), [Vidstack](https://www.vidstack.io/), [Jest](https://jestjs.io/).

**Comment by felipecesr** [comment]
Hi @vr-varad, sorry for the delay in responding. I've edited this issue description. Let me know if you have any questions.

**Comment by vr-varad** [comment]
Can u elaborate the issue basically what you want It would be better to understand the issue
