### ISSUE TITLE
Move @clappr/plugins to Monorepo

### ISSUE THREAD

**Issue by felipecesr** [clappr/clappr#2128]

**Comment by felipecesr** [comment]
**Description**
Combine `@clappr/plugins` repository into `clappr` repository keeping the commit history.

**More information**
This [**article**](https://mattmazzola.medium.com/creating-a-monorepo-from-separate-repos-merging-repositories-f7942885ace6) can help you know how to do that.

**Comment by jhonatangcavalcanti** [comment]
Done https://github.com/clappr/clappr/releases/tag/0.6.0
