### ISSUE TITLE
Clappr Mobile FullScreen Mode

### ISSUE THREAD

**Issue by wesley901** [clappr/clappr#2132]
Hi, I am using your player and I like it very much, but I have a problem. I read the documentation but I could not solve it. When I click on the player on mobile, I want it not to open full screen, especially in the advertisement, but it becomes full screen on mobile. How do I prevent advertising videos from opening in full screen on mobile? Thank you.

**Comment by kslimani** [comment]
In player playback configuration try with `playInline` property to true :

```js
var player = new Clappr.Player({
  // [...]
  playback: {
    playInline: true,
  },
  // [...]
});
```

**Comment by wesley901** [comment]
Thank you very much.
After the advertising ends, the video must be played again for the broadcast to start. Can we start the broadcast automatically when the ad ends or we skip the advertising?

**Comment by kslimani** [comment]
Depending on which solution you use to display advertising (Clappr plugin ?, some library displayed over player ?), to be able to start video automatically, you need to "capture" user click (also called user consent).

If you are able to capture click event (the one used to start the advert), then you can immediatly call the `player.consent()` method. (technically it "store" the user consent inside internal video element).

When your advert has ended, you can call `player.play()` méthod to start playback.

**Comment by wesley901** [comment]
Thank you 👍

**Comment by wesley901** [comment]
> Depending on which solution you use to display advertising (Clappr plugin ?, some library displayed over player ?), to be able to start video automatically, you need to "capture" user click (also called user consent).
> 
> If you are able to capture click event (the one used to start the advert), then you can immediatly call the `player.consent()` method. (technically it "store" the user consent inside internal video element).
> 
> When your advert has ended, you can call `player.play()` méthod to start playback.

I want to turn on automatic broadcasting after the advertisement for Clappr player, but I couldn't do it even though I tried hard, can you help?

**Comment by kslimani** [comment]
try this [plugin](https://github.com/kslimani/clappr-ima-plugin), or take a look at source code.
