### ISSUE TITLE
Update hls.js version

### ISSUE THREAD

**Issue by DimaDemchenko** [clappr/clappr#2146]
@jhonatangcavalcanti
Could you please update the Hls.js version to a recent one in hlsjs-playback [package](https://github.com/clappr/clappr/tree/main/packages/hlsjs-playback)?

Hls.js v1.5.x has no API changes but brings nice features, like the Managed Media Source Extensions API, which allows using Hls.js on iPhones, which is crucial for our project: P2P video delivery with Clappr.

**Comment by Niko78** [comment]
+1

**Comment by rgaufman** [comment]
+1

**Comment by Niko78** [comment]
reactivate this need
