### ISSUE TITLE
Pop-out plugin

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#255]

**Comment by towerz** [comment]
@flavioribeiro Do you remember what kind of pop-out functionality we were aiming for?

**Comment by flavioribeiro** [comment]
yes, we discussed with the designers of globoplay project about the possibility to popout the player the same way twitch.tv does: 

![image](https://cloud.githubusercontent.com/assets/244265/7441877/726779c6-f0c8-11e4-9853-f42fe9ead1ca.png)

**Comment by towerz** [comment]
Thanks @flavioribeiro.
