### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by felipernb** [clappr/clappr#270]
Chromecast is now the second best selling media streamer in the market (http://www.macrumors.com/2014/12/02/apple-tv-chromecast-roku-2014/) and pretty much any streaming service is either already supporting or working towards support it. It would be nice to have it working with Clappr as well.

**Comment by towerz** [comment]
Added basic Chromecast support on 0.1.7. Additional functionality and improvements will be added over time.

Perhaps extracting the plugin to a separate project will be better to keep improving without depending on new Clappr releases.

**Comment by barbosa** [comment]
Yay! :beers:

**Comment by deedos** [comment]
Hi. great feature! congrats!
how to call it ? I tried enableChromecast: true, but nothing happens
abraços

**Comment by towerz** [comment]
Thanks @deedos!

The Chromecast integration works only in the following conditions, in addition to setting `enableChromecast: true`:
- You are using the Chrome browser with the Chromecast extension
- The computer is in the same network as the Chromecast device.
- The receiver app you are trying to access is published.

The sample Clappr Chromecast receiver is used when you don't set `chromecastAppId`, so you probably were using it by default. It was published by the time this issue was closed. Are you sure the other conditions were met when you tested this feature? Did you test using http://cdn.clappr.io?

**Comment by flavioribeiro** [comment]
refs #374

**Comment by dayvson** [comment]
I understand the reason of why you guys want to test and experiment with Chromecast and decide to make it a core plugin, but I believe this decision should be re-evaluated.

Mainly for two reasons, 
1 - To make this code work, it will require that a user have a Chromecast device, which is an enormous external dependency. I believe this reason should be strong enough to make the case of make Chromecast as an external plugin.

2 - Also, there are no tests today about for this plugin; I believe Clappr core plugins and code base should have a high test coverage and be as lightweight as possible.

To put it into another perspective, this plugin as it is today does not add that much value for most of the users and it makes the codebase bigger. In a scenario where a user needs to Cast audio/videos in his application is perfectly reasonable to add an external plugin to enable the feature.

I can move it to an external plugin and send a pull request if you guys agree.

**Comment by flavioribeiro** [comment]
reopening this issue so we can follow up with @dayvson comments

**Comment by towerz** [comment]
@flavioribeiro @dayvson we already considered extracting some non vital plugins into external codebases. I agree the chromecast plugin should be the first of them.

I'm already doing some cleanup in the clappr project, so you don't need to worry about this.

**Comment by leandromoreira** [comment]
+ 1 @dayvson

**Comment by towerz** [comment]
Removed this on 90840eebe1b837f27771b6598793017fb916388d. I think we can close this again. The plugin source will be added to [clappr/clappr-chromecast-plugin](https://github.com/clappr/clappr-chromecast-plugin).

**Comment by flavioribeiro** [comment]
awesome! great work, @towerz
