### ISSUE TITLE
Support source fallbacks

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#285]
Clappr should be able to receive source fallbacks, like:

``` javascript
var player = new Clappr.Player({
  sources: ["http://your.video/here.mp4", "http://your.video/here.ogg", 
    "http://your.video/here.webm"], 
  parentId: "#player"});
```

Maybe we need another embed parameter describing how clappr should play the given sources like `fallback`, `sequence` or `pip` for example.

**Comment by deedos** [comment]
Maybe is wise re-opning this for logically choose wen using different playback engines like https://github.com/shankardevy/clappr-dash-plugin . Is there anything already done for done! Overall clappr keeps going so fine..thanks
