### ISSUE TITLE
Proper npm package?

### ISSUE THREAD

**Issue by ronag** [clappr/clappr#313]
Would be nice with a proper npm package for usage with e.g. WebPack?

**Comment by flavioribeiro** [comment]
hi @ronag, we're uploading all releases to [npm](https://www.npmjs.com/package/clappr). Do you think this issue is somehow associated with #133?

**Comment by ronag** [comment]
The problem I have is `clappr.js` when doing `require` to set itself on ```window``` but not on ```module.exports```

**Comment by thiagopnts** [comment]
Yes, that would be nice. We end up putting it on window for some old browserify misbehavior. I think its now fixed and we can go this way.

**Comment by towerz** [comment]
Next release will work properly with `require`. Setting Clappr to `window` will still be needed though, to support different kinds of applications.
