### ISSUE TITLE
Add support for protocol relative urls (//path/to/media)

### ISSUE THREAD

**Issue by whadar** [clappr/clappr#341]
It would be better not specify http or https for many reasons (e.g //cdn.publisher.com/path.mp4)
When using URLs without protocols we currently get - oops error occurred message.

**Comment by flavioribeiro** [comment]
Hey @whader, we use the protocol part of url source to help us on playback matching. On [RTMP](https://github.com/clappr/clappr-rtmp-plugin/blob/master/src/main.js#L67) case, for example, we match the source by looking for the protocol only. On [HLS](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L337) we allow both `http` and `https` on regex match. Can you elaborate more about your case?
