### ISSUE TITLE
Video to GIF Plugin (Meme Generator)

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#351]
https://github.com/yaronn/GifW00t

**Comment by flavioribeiro** [comment]
http://jnordberg.github.io/gif.js/tests/video.html

**Comment by flavioribeiro** [comment]
https://github.com/yahoo/gifshot

**Comment by Metrakit** [comment]
Haha nice idea

**Comment by flavioribeiro** [comment]
more resources;
http://www.sitepoint.com/html5-video-fragments-captions-dynamic-thumbnails/
http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2014/12/html5-video-article-demos/thumbnails-demo.html
