### ISSUE TITLE
Control bar only shows stop button in HLS stream

### ISSUE THREAD

**Issue by holygekko** [clappr/clappr#354]
I can only pause a hls video by clicking on the video itself. The controls on the control bar only show the stop button (square) but not the play (triangle) or pause (vertical bars) button.

See: http://cdn.clappr.io/
and use http://stream.flowplayer.org/drive.m3u8 as source file.

**Comment by flavioribeiro** [comment]
hi @holygekko, I've reproduced here. Clappr is mixing the behavior of VoD and live on media control. I'll try to find the reason. Thanks for reporting.

**Comment by flavioribeiro** [comment]
@holygekko it should be fixed now. I bumped a new version, you can check the fix on http://cdn.clappr.io. Be sure that you're getting the new version (0.0.101).

**Comment by holygekko** [comment]
Fantastic! Thanks!
