### ISSUE TITLE
Assets hardcoded, should be overridable 

### ISSUE THREAD

**Issue by osk** [clappr/clappr#356]
Assets are hardcoded to be served from http://cdn.clappr.io/ but I would want to be able to set where it is being served from.

https://github.com/clappr/clappr/search?utf8=%E2%9C%93&q=cdn.clappr.io+language%3Ajavascript+language%3Ascss&type=Code

**Comment by stjernstrom** [comment]
Also this would make it possible to server assets from a secure https server

**Comment by irongomme** [comment]
i would like too ...

**Comment by irongomme** [comment]
After looking to it, it can be easy for swf assets, but how can we do for scss files, because they are compiled ... 
We have to extract all the lines working with assets from the scss to dynamically generates them into the app from new parameters , is that true ?

**Comment by thiagopnts** [comment]
@irongomme We solve this problem in some of our internal plugins, I think we can apply the same solution to clappr. I'll take a look on this now.

**Comment by thiagopnts** [comment]
https://github.com/clappr/clappr/commit/19740cd8a3a7a5ecab3b9a7bed96d2ad20c08920 adds a new baseUrl param to use a custom host, if no baseUrl is passed it will try to get it from the current host.
