### ISSUE TITLE
Styling guidelines

### ISSUE THREAD

**Issue by osk** [clappr/clappr#358]
I'm digging this project and am testing it out for video playing.

I want to style the controls and have done so by playing with the rendered controls. Is there a preferred way to style at the moment?

**Comment by flavioribeiro** [comment]
hi @osk, you can make a simple customization by [changing](https://github.com/clappr/clappr#control-bar-colors) the colors of the current media control or creating a new media control from scratch, inheriting from the built-in and adding it externally (you can [use](https://github.com/clappr/generator-clappr-plugin) the plugins generator).

We actually did a media control plugin to use at Globo.com, here's a screenshot of the player:
![image](https://cloud.githubusercontent.com/assets/244265/6136665/b6c76bca-b159-11e4-865b-f7f91aa0c177.png)

Unfortunately it's closed but I'm sure we can help if you want to create your own.
The thumb preview guy on top of the seekbar is another plugin that inherits from [seek_time](https://github.com/clappr/clappr/tree/master/src/components/seek_time) and use [nginx-video-thumbextractor-module](https://github.com/wandenberg/nginx-video-thumbextractor-module) on server side.

**Comment by osk** [comment]
I noticed the possibility of changing colors, but I want to rearrange the elements your screenshot isn't far off what I'm aiming for :-)
By messing with the CSS and overriding the default styles I'm able to get very close to what I want, but isn't that preferred? Is creating a special plugin the way to go? Seems a bit much for skinning

**Comment by thiagopnts** [comment]
You need to create an external plugin if you want to have more control over this, like changing template structure, etc. Overriding the CSS would be a more practical way.

**Comment by flavioribeiro** [comment]
I'm closing this for now. Feel free to reach us if you have plans to create your own media control plugin.
