### ISSUE TITLE
Reuse template on flash-based plugins (flash, hls)

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#359]
Both [flash](https://github.com/clappr/clappr/blob/master/src/playbacks/flash/public/flash_playback.html), [hls](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/public/hls_playback.html) and external [RTMP](https://github.com/clappr/clappr-rtmp-plugin/blob/master/public/rtmp_playback.html) plugins (more to come) has exactly the _same_ template. We could save some bits by reusing it.

**Comment by towerz** [comment]
I believe 40a21f2b96fb1fae98cbc7ba1ad57e2b726745c6 closes this issue. If we need to do more work for the RTMP playback we can revisit this issue or create a new one.
