### ISSUE TITLE
HLS on android is always detected as LIVE

### ISSUE THREAD

**Issue by stjernstrom** [clappr/clappr#360]
Experimenting with both LIVE and VOD HLS streams. In the browsers everything is correct but on both my sony xperia android phone and my android tablet the VOD stream is labeled as "LIVE" but the scrubber is displaying correct with time (but not seekable, but that is a android bug i think)

Using the player/html/js from the repo (version 0.0.101)

**Comment by flavioribeiro** [comment]
hey @stjernstrom it should be fixed now. Can you try and tell me if it works for you?

**Comment by stjernstrom** [comment]
Great work @flavioribeiro 

This updates fixes the problem. I have tested two different android phones and a tablet and both LIVE and VOD and both works as expected now!

**Comment by flavioribeiro** [comment]
awesome @stjernstrom, thanks for testing. We'll look at some minor issues and bump a new tag. :beers:

**Comment by stjernstrom** [comment]
Awesome work!

Cheers!
