### ISSUE TITLE
Seeking not working in Safari

### ISSUE THREAD

**Issue by whadar** [clappr/clappr#362]
For an HLS VOD, seek is not working. For instance for this stream: http://cdnbakmi.kaltura.com/p/1375472/sp/137547200/playManifest/entryId/0_ncvvnzfe/flavorIds/0_obbhtwhw,0_ikr2ob7t/format/applehttp/protocol/http/a.m3u8

**Comment by flavioribeiro** [comment]
reproduced here

**Comment by flavioribeiro** [comment]
thanks for reporting @whadar, the fix will be present on next release.

**Comment by stjernstrom** [comment]
This fix almost fixed issue #360 the progressbar/seek is now working on android, but a VOD is still labeled as LIVE.

**Comment by flavioribeiro** [comment]
good @stjernstrom, we'll take a look on it today.
