### ISSUE TITLE
Bad request from live hls streams

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#368]
I've noticed that on some kinds of hls streams, clappr start playing but then fails and stop playing.

I've tested it on chrome and firefox with the following stream : 
http://live.francetv.fr/simulcast/France_3/hls_v1/index.m3u8

When i watch requests, this happens because there is a bad request (400) after about twenty, thirty seconds. So is it a stream issue or a clappr issue ?

The strange thing is that it just play perfectly on ipad safari, with no errors and no breaks  !

**Comment by irongomme** [comment]
After some investigations, i think the problem is here : 

- The first request to the m3u8 is good and stream is playing
- The .ts are requested, so no problem
- The second request to the m3u8 is called with an additionnal ?time=xxx parameter , probably to avoid caching from the browser, but the streaming server doesn't support this parameter and reject the request by a 400 error (bad request), so the playing stop !

Which part of the app is responsible of this parameter time ?
is there a way to don't put this param at the end of the hls request ?

**Comment by flavioribeiro** [comment]
hello @irongomme, the `?time=` parameter is a workaround to fix internal flash cache issues with some combination of Flash Player / IE. If you want to disable it just add `flushLiveURLCache: false` on your embed parameters. Tell me if it works for you.

**Comment by chriswiggins** [comment]
Your server application should not fail with any additional query strings, it should just ignore them anyway

Sent from my iPhone

On 27/02/2015, at 5:54 am, Fl?vio Ribeiro <notifications@github.com<mailto:notifications@github.com>> wrote:


hello @irongomme<https://github.com/irongomme>, the ?time= parameter is a workaround to fix internal flash cache issues with some combination of Flash Player / IE. If you want to disable it just add flushLiveURLCache: false on your embed parameters. Tell me if it works for you.

-

**Comment by irongomme** [comment]
@chriswiggins i'm agree, but it's not mine and it just doesn't ignore query strings  .... 
@flavioribeiro thxs, i'll try it, but how do you modify embed parameters from the javascript params ? Have i to modify clappr source to do it ?

Otherwise i made a dirty fix from my environment : I've put an nginx conf which proxy pass the final streaming server without query strings .... and it works ! But i'd rather like a clean solution from clappr.

**Comment by flavioribeiro** [comment]
@irongomme you don't need to change the source. When creating the player instance, just add the parameter I just said. Example:
```html
<script>
  var player = new Clappr.Player({
    source: "http://your.video/here.m3u8", parentId: "#player", flushLiveURLCache: false 
  });
</script>
```

**Comment by irongomme** [comment]
@flavioribeiro Cool !

You said that this parameter is a fix for flash on IE, does that mean it could not work as expected on it if i put this param to false ?

**Comment by irongomme** [comment]
It works with flushLiveURLCache to false

Thxs !

**Comment by flavioribeiro** [comment]
:beers:
