### ISSUE TITLE
Centered play icon keeps its original size

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#373]
The play icon on the center of the video is not visible because of its size of 4px

I've noticed it on : 
  - Chrome linux
  - Firefox linux
  - Safari iOs 7 iphone and iOs 8 ipad
  - Chrome Android 4.1 
  - Internet Android 4.1
  - IE 10 Surface

This is a css issue, i can take a look on it ... !

**Comment by irongomme** [comment]
I've got it : 

**In facts, this happens when we use percents dimensions for the player height**

  - The poster plugin listen for resize and apply a font-size equal to the playerInfo height (height defined in the player instanciation)
  - When i set a 100% height, it set a 100% font-size and this is the problem !

I see in src/plugins/poster/poster.js (l.103) :
```
var height = PlayerInfo.currentSize ? PlayerInfo.currentSize.height : this.$el.height()
```

So, why can't we simply just put : 
```
var height = this.$el.height()
```

???

This works for me with this fix ...

**Comment by thiagopnts** [comment]
Sorry for the delay, and thanks for investigating on this. By "player height 100%" you mean the `height` attribute on player initialization?

**Comment by irongomme** [comment]
Yes, i need the player to be responsive

**Comment by thiagopnts** [comment]
I see, this change was introduced by @towerz at https://github.com/clappr/clappr/commit/e364cd3db277122aefb53fe499dcc72cb65c61ef to keep the icon size proportional when changing player's size. Currently we don't support percent height/width, we need the `data-player` div to have a fixed size for reference to the inner elements. For adaptive size, you would need to use `.resize({width/height})`.

**Comment by towerz** [comment]
@irongomme Please check whether the problem persists using the latest version (0.0.114). I believe this behavior has been fixed for percentage values.

**Comment by irongomme** [comment]
@towerz 

:ok_hand: 

Great, it works as expected, and i don't have to maintain my own branch to have this behavior, thxs !

**Comment by towerz** [comment]
@irongomme Anytime! I'm closing this issue then. If you find any other problem please reopen.
