### ISSUE TITLE
Hide seek bar on live streams

### ISSUE THREAD

**Issue by btecu** [clappr/clappr#381]
Is it possible to hide the seek bar on live streams or at least have the bar but hide the control?

**Comment by flavioribeiro** [comment]
hello @btecu, clappr has a `chromeless` option that hides both seekbar and media controls. Try embedding the player with the given parameters:
```javascript
var player = new Clappr.Player({
  source: 'http://cdn.bem.tv/stream/soccer5/playlist.m3u8',
  chromeless: true,
  autoPlay: true,
  mute: true,
  height: 360,
  width: 640
});
```
You can try on http://cdn.clappr.io. It fits your use case?

**Comment by btecu** [comment]
I'm aware of `chromeless`, however, the volume and full screen options are very important.

**Comment by flavioribeiro** [comment]
hmm, I see. So, we don't have this feature yet, would you mind sending a pull request?

**Comment by thiagopnts** [comment]
Also you can just `$('[data-seekbar]').hide()`

**Comment by btecu** [comment]
@thiagopnts thanks, that works for me.
@flavioribeiro I feature could be nicer so if there're no plans for it, you can close the issue.
