### ISSUE TITLE
autoPlayVisible should become an external plugin

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#382]
Talking with @thiagopnts we thought that [autoPlayVisible](https://github.com/clappr/clappr#auto-play-when-visible) option should be moved to an external plugin, avoiding the need of `scrollmonitor` dependency on the default bundle.

**Comment by thiagopnts** [comment]
removed at https://github.com/clappr/clappr/commit/3a62542eb63272859fff4e9de8c4b4bb7783b149

**Comment by towerz** [comment]
Seems to me this issue should be closed then. Please reopen if there's anything else to do.
