### ISSUE TITLE
Way to change sources from external plugin 

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#383]
I want to change source from an external plugin during the play, 
is that possible and how ?

**Comment by flavioribeiro** [comment]
@irongomme if you create a core plugin you'll receive core instance on constructor which has `load(source)` method. This fits your needs?

**Comment by irongomme** [comment]
@flavioribeiro yes this is a core plugin

i've tried it but unfortunately i've got a 'Uncaught TypeError: undefined is not a function'

It seems that the external plugin does't know about load function from core object

I've used the clappr plugin generator to write this plugin, is that the good way ?

**Comment by flavioribeiro** [comment]
yes, the generator is the way to go. Can you point me to your code?

**Comment by irongomme** [comment]
Of course : 

https://github.com/irongomme/clappr-channels/blob/master/src/main.js

**Comment by irongomme** [comment]
Ok i've found it .... 
My call of the plugin from player parameters was wrong, i've put 

```
plugins: { 'container': [Channels] }
```

Instead of 
```
plugins: { 'core': [Channels] }
```

:grimacing:

**Comment by irongomme** [comment]
Is there a procedure to follow ? 
Because changing the source cause the player to stop playing, and calling mediaControl.play() just after throw an error

**Comment by irongomme** [comment]
I've got this working : 
```
this.core.load(source)
this.container.on(Events.CONTAINER_READY, this.container.play)
```

**Comment by flavioribeiro** [comment]
:+1:
