### ISSUE TITLE
mediacontrol lose focus on iOs

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#386]
The behavior i've noticed : 

  - On iOs (7&8) , if we don't use controls when they are shown the first time, just after playing start, i can't let them re-appear by touching the player.
  - But, if i am quick enough to touch the controls when they appear the first time, it work as expected : controls re-appear when i touch the screen.

Strange !

**Comment by thiagopnts** [comment]
Good catch, currently all mobile interactions are still lacking attention from us

**Comment by irongomme** [comment]
Sorry for this issue because in fact everything is OK !

This was due to my plugin which was implemented after the mediacontrol html, that's why i loosed focus ....
