### ISSUE TITLE
No HLS playback on mobile

### ISSUE THREAD

**Issue by whadar** [clappr/clappr#387]
The player simply shows a play button and nothing starts. Tested on
Nexus 5
Nexus 4
Samsung Galaxy S5

Looks like the fallback from flash is not working

**Comment by stjernstrom** [comment]
Which browser are you using? I think it's only Chrome on android who's handling HLS, I would not rely on the stock Browser for Android and even Chrome have problems on older phones. To summarize, HLS on android is a mess. 

You can try your phones on this page to see if they work (without clappr) http://www.jwplayer.com/html5/hls/

**Comment by whadar** [comment]
The browser is always Chrome. 
The JW test page work well on Chrome (Nexus5), but no luck with clappr.

**Comment by stjernstrom** [comment]
You have a sample page I can test? I've a Sony Z3 and it's working with clappr

**Comment by whadar** [comment]
I was testing a page with non-standard clappr version.
With a vanilla and latest version of clappr, things work as expected
