### ISSUE TITLE
Report playback name being used to Google Analytics

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#390]

**Comment by vitorbaptista** [comment]
This seems [to be done](https://github.com/clappr/clappr/blob/master/src/plugins/google_analytics/google_analytics.js#L36-L38) as well?

**Comment by flavioribeiro** [comment]
sorry for taking SO LONG @vitorbaptista. I was thinking of dispatching a new event that expose the name of the plugin (if it's using flashls, hls.js, html5_video or flash, for example)
