### ISSUE TITLE
Dependency free plugins

### ISSUE THREAD

**Issue by thiagopnts** [clappr/clappr#393]
It would be nice if we could write plugins without the boilerplate from the generator, using ES5. Something like:

```javascript
var MyPlugin = UICorePlugin.extend({foo: ...});
```

cc @tulios

**Comment by towerz** [comment]
@thiagopnts Talking with @tulios, we agreed on two proposed changes to allow for dependency free plugins.

The first one is exposing the plugin classes under the Clappr namespace to avoid using CommonJS "require", to avoid conflict with other "require" implementations. The other is creating the "extend" method or using a factory method if "extend" conflicts with our current ES6 class implementation.

I intend to implement this week so we can move on to Clappr 0.1.0.

**Comment by towerz** [comment]
@thiagopnts @tulios I just pushed some changes to allow for the proposed construct:
```javascript
var MyPlugin = UICorePlugin.extend({foo: ...});
```
Now you can create plugins like this:
```javascript
var MyPlugin = Clappr.UIContainerPlugin.extend({
  constructor: function() { this.render() },
  render: function() {
    this.$el.html('This is a test')
    this.container.$el.append(this.$el);
    return this
  }
});
var player = new Clappr.Player({ ...
  plugins: { container: [MyPlugin] }
});
```
The `constructor` method is used for the object initialization. There's no need for calling the parent constructor, as it is automatically called.

**Comment by thiagopnts** [comment]
Awesome!! 🍻
