### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by towerz** [clappr/clappr#396]
Since the project is growing up quickly and there aren't many tests to guarantee the code won't break due to changes, we need to improve our quality control.

The structure of the code seems stable enough for us to ensure its stability increasing the test coverage.

**Comment by joaopaulovieira** [comment]
We need to check the actual test coverage and set the desired percentage.

**Comment by joaopaulovieira** [comment]
Closing because the project was broken down into smaller projects and the remaining code is only for generating packages.
