### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aguxtremo** [clappr/clappr#399]
When source is http://5133.live.streamtheworld.com/LOS40_ARGENTINA_SC or http://provisioning.streamtheworld.com/pls/LOS40_ARGENTINA.pls or http://5133.live.streamtheworld.com/LOS40_ARGENTINAAAC , the player not work.

What is the problem? Thanks!

**Comment by flavioribeiro** [comment]
Hey @aguxtremo, it seems that these are shoutcast streams. If I'm correct, clappr doesn't have support for it yet. Pull requests are welcome.

**Comment by aguxtremo** [comment]
no, it's not shoucast.
Shoucast is http://www.radiolatina.info:9776/;/stream.mp3 , and work very good!

**Comment by towerz** [comment]
@aguxtremo The problem here seems to be that the player is not able to determine the media format based on its URL. Currently, the playbacks use the URL file extension for determining the media type. Since both http://5133.live.streamtheworld.com/LOS40_ARGENTINA_SC and http://5133.live.streamtheworld.com/LOS40_ARGENTINAAAC do not present a file extension, the player cannot determine whether it can play the media or not. We have some ideas to work this out but they're still not implemented.

As for the PLS playlist (http://provisioning.streamtheworld.com/pls/LOS40_ARGENTINA.pls), it seems that the HTML5 audio tag do not support it on both Firefox and Chrome. Safari reports "maybe" for its playback capabilities.

On Chrome and Firefox:
```
> el = document.createElement('audio')
< <audio>
> el.canPlayType('audio/x-scpls')
< ""
```
On Safari:
```
> el = document.createElement('audio')
< <audio>​</audio>​
> el.canPlayType('audio/x-scpls')
< "maybe"
```

@thiagopnts @flavioribeiro What do you think of adding a way to determine the mime type based on the Content-Type header for these URLs with no file extension?

**Comment by aguxtremo** [comment]
You can use http://5133.live.streamtheworld.com/LOS40_ARGENTINA_SC?.aac or http://5133.live.streamtheworld.com/LOS40_ARGENTINA_SC?.mp3 but neither works

**Comment by towerz** [comment]
@aguxtremo This is because the query string is ignored when determining the file extension:
```var resourceParts = resource.split('?')[0].match(/.*\.(.*)$/) || []```

**Comment by flavioribeiro** [comment]
@towerz how are you planning to implement this? I wonder if we can solve it by adding a playback plugin that stays at the tail of Loader array, dispatching `HEAD` requests inside its `canPlay` method and routing to the right plugin after that.

**Comment by towerz** [comment]
@flavioribeiro I was thinking of something like that, but after some time I changed my mind about adding a fallback check at the end of the Loader array. 

Instead, I would suggest adding a check for missing extension on the URL before searching for the right playback on the Loader array. Only if the URL does not have an extension, we would check for the mime type using a `HEAD` request prior to going through the Loader array lookup. This way we won't have to worry about routing to the right plugin from the tail of the Loader array.

**Comment by flavioribeiro** [comment]
+1 for your solution :clap:

**Comment by towerz** [comment]
Any thoughts, @thiagopnts?

**Comment by thiagopnts** [comment]
I'm not familiar with this, is not specifying an extension to the source a common thing in streaming services?

**Comment by towerz** [comment]
@thiagopnts Yes, specifying a file extension is a common thing in streaming services, but this solution is only for non-standard URLs.

**Comment by snsxn** [comment]
@towerz just trying to add ?.mp3 fails as you said (no query string admitted), but I have the content-type.
It's possible to tell it to Clappr?
I'm checking the streams and 90% doesn't have extension

**Comment by towerz** [comment]
@snsxn What kind of streams are you referring to? AFAIK, most streaming solutions generate URLs including the playlist file extension, like pls or m3u8. Some other streaming formats use an URL that do not include a file extension, like smooth streaming, but those are still unsupported.

About this feature of telling Clappr the content-type for the URL, it's still not supported. We're considering adding this feature of processing the content-type either from a `HEAD` request or a embed parameter to a standalone plugin. This way we can keep the Clappr core simple, but still able to support this kind of situation.

**Comment by snsxn** [comment]
@towerz lot of streamings has IP and port style URLs. Many shoutcast streamings must have (;) at the end to receive the correct content-type and play it. The solution is to add ?.mp3 (the extension received from the HEAD Content-Type)

**Comment by towerz** [comment]
@snsxn I agree there are some streaming solutions that don't use file extensions, such as smooth streaming, and others. Since even the HLS spec allows identifying the stream type through content-type, we'll add an embed parameter to allow setting this externally.

**Comment by towerz** [comment]
@aguxtremo @snsxn I added a mimeType parameter to player embed to allow setting this information externally.

Unfortunately I'm still facing some security issues when trying to check the mime type for a given URL. It's probably a dead end, but I'll keep trying for a while before giving up and be satisfied just with the external parameter.

You can now create the player like this:
```
var player = new Clappr.Player({
    source: 'http://provisioning.streamtheworld.com/pls/LOS40_ARGENTINA.pls',
    mimeType: 'audio/x-scpls; charset=UTF-8'
})
```

Hope this will help solving many of those issues.
