### ISSUE TITLE
Your browser does not support the playback of this video.

### ISSUE THREAD

**Issue by shacharz** [clappr/clappr#403]
Windows 7, Firefox. Tried playing an HLS stream, e.g: https://livestream.peer5.com/stream_1000k_48k_640x360.m3u8

**Comment by wicherdt** [comment]
Adobe flash player installed?

**Comment by shacharz** [comment]
yea

**Comment by wicherdt** [comment]
On my PC with windows 7 and firefox with flash seem all OK

**Comment by shacharz** [comment]
Maybe it's codec related? a codec that isn't installed on my machine and Chrome has it?

**Comment by flavioribeiro** [comment]
@shacharz can you reproduce with vanilla clappr without your external plugin?

**Comment by shacharz** [comment]
Yup, I've reproduced it on cdn.clappr.io

**Comment by towerz** [comment]
@shacharz Could you please check if your Flash Player and Firefox versions are up to date? If you have any Flash blocker or an outdated version of the Flash plugin, the HLS playback may not load correcly.

**Comment by shacharz** [comment]
Indeed it was outdated flash player :grimacing: 
thanks guys
