### ISSUE TITLE
Seekbar doesn't work when playing mp3 files

### ISSUE THREAD

**Issue by egftechman** [clappr/clappr#405]
When playing mp3 files, seekbar isn't functional. Tested in Chrome, Firefox on Linux, Safari on OS X, IE on Windows.

**Comment by flavioribeiro** [comment]
+1, I could reproduce here on chrome and firefox at linux using http://bem.tv/shakira.mp3

**Comment by egftechman** [comment]
I should add the URL of the pagevwhere I am using it, for testing....http://eastgrandforks.tv/?file=22

**Comment by towerz** [comment]
@egftechman @flavioribeiro Just pushed a fix for this issue, could you please check against 760db90c8c0f5b43a2e1cf93923e9e0269a2abbd?

**Comment by egftechman** [comment]
Just rebuilt locally, seekbar now works in clappr.js, but not clappr.min.js with a mp3 file....

**Comment by egftechman** [comment]
Just rebuilt locally and seekbar now works with mp3 files. Thanks for help.

**Comment by flavioribeiro** [comment]
fixed, thanks @towerz
