### ISSUE TITLE
Expose playback events on player object

### ISSUE THREAD

**Issue by towerz** [clappr/clappr#406]
There were some requests for adding support for something like:

```player.on('player:play', function() { console.log('play!') })```

Currently we're planning on exposing the following events: play, pause, stop, seek, timeupdate, ended. I believe this will cover most use cases.

**Comment by guzz** [comment]
Hello @towerz, is there any way of listening to events with clappr yet?

**Comment by deedos** [comment]
Hi @towerz

Could you show @Guzz and me an example on how to listen to a play event?
Em 15/04/2015 14:03, "guzz" <notifications@github.com> escreveu:
