### ISSUE TITLE
load() new stream can't stop previous loaded stream

### ISSUE THREAD

**Issue by snsxn** [clappr/clappr#407]
After change the source to a new streaming URL, the previous streaming is still loading, as seen in firebug.
Tried with **load('')**, **.pause()**, **.stop()** and **destroy()**, but always still loading previous stream.

Any idea to solve this?

**Comment by towerz** [comment]
@snsxn Could you please elaborate more on this? I tried to reproduce this behavior on http://cdn.clappr.io but I couldn't. Can you tell me how to reproduce this?

**Comment by snsxn** [comment]
I'll try it:
1. Load and play http://icecast-streaming.nice264.com/melodiafm?.mp3 (after removing resource.split('?') from clappr)
2. Then I change source of the player to http://icecast-streaming.nice264.com/europafm?.mp3
3. Looking at firebug, I can see how the first streaming keeps loading
* tried with the different methods mentioned before to pause, or stop or destroy and none of these clear the player and cancels any current HTTP request

**Comment by towerz** [comment]
@snsxn Discarding the source of the HTML 5 tag when stopping playback solved the problem. I also added a way for passing the mime-type of the content so you don't need to change the code anymore.

**Comment by snsxn** [comment]
I will implement this new version.Thanks!
