### ISSUE TITLE
Fix flash hls player

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#410]

**Comment by flavioribeiro** [comment]
@leandromoreira am I the guilty here?

**Comment by leandromoreira** [comment]
@flavioribeiro no, I don't think so :smile:  ! We had observed that the latest flash_hls build was behaving pretty weird (going backward and forward during the switch of bitrates) and we need to track it down to understand what is happening.

**Comment by towerz** [comment]
We are currently testing using flashls chromeless player directly since we don't actually customize it for Clappr. Work is being done in the flashls_dev branch.
