### ISSUE TITLE
play button not working after stopped.

### ISSUE THREAD

**Issue by hatsch** [clappr/clappr#412]
as already mentioned by @irongomme in #384 the play button stopped working after the player was stopped once.

it stopped working with this commit: c34b40764fc2a75ac4d86a35b1a96a773f02b70b
so some dependencies may have broken it.

the latest working commit is c34b40764fc2a75ac4d86a35b1a96a773f02b70b ( i am using that one right now)

**Comment by irongomme** [comment]
I'm doing the same, i use new releases for js but old release for the swf

**Comment by irongomme** [comment]
@towerz Great job !
