### ISSUE TITLE
HLS not working with current sources

### ISSUE THREAD

**Issue by JoosyBill** [clappr/clappr#416]
I am able to play mp4 video on current Chrome, but loading a viable m3u8 playlist is causing an error due to the Flash player not loaded. Using clappr.js the error is on line 80 of hls.js. globoPlayerSetflushLiveURLCache is null. I tried this with a local build as well as via http://cdn.clappr.io/latest/clappr.js.

    setFlashSettings() {
        this.el.globoPlayerSetflushLiveURLCache(this.flushLiveURLCache)   <-- line 80
        this.el.globoPlayerCapLeveltoStage(this.capLevelToStage)
        this.el.globoPlayerSetmaxBufferLength(0)
      }

**Comment by irongomme** [comment]
@JoosyBill I think this problem is linked with this issue : #412

Can you try to use clappr locally, and use this version of HLSPlayer : 
https://github.com/clappr/clappr/blob/a9281a41a1ffeb600d7c5fb3fcf543b81375b764/dist/assets/HLSPlayer.swf

use the baseUrl param to set the path of your assets

**Comment by aergistal** [comment]
@irongomme 

I confirm this works with the the provided `HLSPlayer.swf`. Tested with a live, adaptive bitrate stream.

**Comment by towerz** [comment]
@JoosyBill Could you please check whether the problem have been solved after commit 48c94affdd787659cc1655469885eae8b0cfaa46?

**Comment by JoosyBill** [comment]
Hi Bruno,

Yes, this commit solves the problem. I apologize for not testing the new commit sooner. Thank you for addressing the issue so quickly.

-Bill

**Comment by towerz** [comment]
@JoosyBill I'll close this issue then. Thanks for your help.
