### ISSUE TITLE
Playing and Pausing the video doesn't change the icon

### ISSUE THREAD

**Issue by LeonardoCardoso** [clappr/clappr#418]
When you click the video (not play/pause button) it doesn't change the play/pause button.

**Comment by LeonardoCardoso** [comment]
I've noticed that if you play or pause the video by clicking on container it doesn't change the icons.
But if you pause the video by clicking on play/pause button and resume the video by clicking on container it works.
I also noticed that changeTogglePlay() is only called to play (or resume) the video by clicking the container.

**Comment by towerz** [comment]
@LeonardoCardoso thanks for your help. I'm not sure when this feature broke, but I'll add some tests to avoid regression issues.
