### ISSUE TITLE
No buffering animation in HLS stream

### ISSUE THREAD

**Issue by shacharz** [clappr/clappr#421]
what happens: Looks like if you're watching a stream, and the player don't have any more .ts to play there's not rebuffering animation.

what should happen: rebuffering animation should play

reproduce: 
go to http://cdn.clappr.io/
replace the stream with http://www.streambox.fr/playlists/test_001/stream.m3u8
disconnect your internet (do it fast so you won't buffer the entire movie :) )
when buffer runs out the frame will freeze and there's no rebuffer animation

**Comment by towerz** [comment]
Seems the playback was missing a state (PAUSED_BUFFERING) as well as enforcing there were less than 1 second on buffer when switching to PLAYING_BUFFERING. 

The latter condition could lead to the player being hung on PLAYING_BUFFERING state without actually considering itself as buffering (triggering the event Events.PLAYBACK_BUFFERING).

I'm already testing a solution for this, and I'll push as soon as possible.

**Comment by towerz** [comment]
@shacharz please test using master to check if there's any other problem displaying buffering indicator.

**Comment by shacharz** [comment]
works like a charm, thanks.

**Comment by shacharz** [comment]
When can we expect 0.0.115?

**Comment by towerz** [comment]
@shacharz We were planning to jump directly to 0.1.0 but since there were lots of issues, I believe by the end of this week we'll release 0.0.115 before going for 0.1.0.
