### ISSUE TITLE
Change fonts url to //

### ISSUE THREAD

**Issue by shaharmor** [clappr/clappr#424]
Hi,

Currently the fonts link is `http://fonts.googleapis.com/css?family=Roboto`.
This shows a console error if website is using SSL.

Please change link to: `//fonts.googleapis.com/css?family=Roboto`

**Comment by hatsch** [comment]
i also stumbled around that issue with SSL enabled.
wouldn't it be the best way to just add it to the dist/assets directory and serve the font from the local webserver. this way the webfont is also not acting as a tracker for google.

there is already another font in the assets directory:  Player-Regular.ttf

License wise it should be fine, as google says "The fonts in the directory are all released under open source licenses; you can use them on any non-commercial or commercial project."
