### ISSUE TITLE
Fail reading font from CDN due to cross-site

### ISSUE THREAD

**Issue by ishahak** [clappr/clappr#429]
I'm getting this error in Chrome on Mac:
Font from origin 'http://cdn.clappr.io' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8881' is therefore not allowed access.
VM439:1 FlasHLS Clappr (version: 0.1, id: o5)

I think you should add the cross-domain headers when serving the fonts
many thanks
-Itay

**Comment by towerz** [comment]
@ishahak I'm not sure why you're having this issue. The CDN is already configured to return CORS headers correctly. I tried accessing it using curl and the result was this: 
```
curl -I -H 'Origin: http://localhost:8881' 'http://cdn.clappr.io/latest/assets/Player-Regular.ttf'
HTTP/1.1 200 OK
x-amz-id-2: lRFx2lMP1pxoUbtNj3Vej+V+V3AuB17Y/e3M2RykOa6b79gFJMIPgtZ0X3g8bVGtVkVoBeOm2Vk=
x-amz-request-id: BD092FEA2F9EEC04
Date: Thu, 30 Apr 2015 21:16:18 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, HEAD
Access-Control-Max-Age: 3000
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Last-Modified: Thu, 23 Oct 2014 20:22:09 GMT
ETag: "3e43a5d764f841e7e78896de82cd6c50"
Content-Type: application/x-font-ttf
Content-Length: 5081
Server: AmazonS3
```
Could you please check whether this command returns the same from your location?

**Comment by ishahak** [comment]
Hi Bruno,
many thanks for your response.
Chrome is reporting this:

   1. Remote Address:
      54.231.33.36:80
      2. Request URL:
      http://cdn.clappr.io/latest/assets/Player-Regular.ttf
      3. Request Method:
      GET
      4. Status Code:
      200 OK (from cache)
      1. Response Headers
      1. Content-Length:
      5081
      2. Content-Type:
      application/x-font-ttf
      3. Date:
      Tue, 28 Apr 2015 06:25:56 GMT
      4. ETag:
      "3e43a5d764f841e7e78896de82cd6c50"
      5. Last-Modified:
      Thu, 23 Oct 2014 20:22:09 GMT
      6. Server:
      AmazonS3
      7. Via:
      1.1 Application and Content Networking System Software 5.5.37
      8. x-amz-id-2:
      SE50NB7HL9afMpebgf1vRTFH9Y1Q59Ln1+xB7LGWmD0r5XL0+dN1WLiAWSsV+ZuT
      9. x-amz-request-id:
      059232200AFFF7E6
      2. Request Headers
      1. Provisional headers are shown
      2. Origin:
      http://localhost:8881
      3. Referer:
      http://localhost:8881/
      4. User-Agent:
      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36


--> so I do not see the headers which you see.

besides,here is my curl response:

*>curl -vv http://cdn.clappr.io/latest/assets/Player-Regular.ttf
<http://cdn.clappr.io/latest/assets/Player-Regular.ttf>*

* Adding handle: conn: 0x7f9b58804000

* Adding handle: send: 0

* Adding handle: recv: 0

* Curl_addHandleToPipeline: length: 1

* - Conn 0 (0x7f9b58804000) send_pipe: 1, recv_pipe: 0

* About to connect() to cdn.clappr.io port 80 (#0)

*   Trying 54.231.13.244...

* Connected to cdn.clappr.io (54.231.13.244) port 80 (#0)

> GET /latest/assets/Player-Regular.ttf HTTP/1.1

> User-Agent: curl/7.30.0

> Host: cdn.clappr.io

> Accept: */*

>

< HTTP/1.1 200 OK

< x-amz-id-2:
ZKh05nsEjGBJxc1Evspgy8zd+GjLbhc8KOlF2Y4xIFtf57/6Et+po16RyYPDL2qgjrA1OYB3+F0=

< x-amz-request-id: 5A853D952A5FE993

< Date: Fri, 01 May 2015 07:04:32 GMT

< ETag: "3e43a5d764f841e7e78896de82cd6c50"

* Server AmazonS3 is not blacklisted

< Server: AmazonS3

< Content-Length: 5081

< Content-Type: application/x-font-ttf

< Last-Modified: Thu, 23 Oct 2014 20:22:09 GMT

< Via: 1.1 ntn01-dmz-wsa-1-mgmt.cisco.com:80 (Cisco-WSA/8.5.0-497), 1.1
Application and Content Networking System Software 5.5.37

< Connection: Close

<


--> so it is possible that the Flash plug-in on Mac is not using the -I
option which I'm getting just like you:

*>curl -I -H 'Origin: http://localhost:8881 <http://localhost:8881>'
'http://cdn.clappr.io/latest/assets/Player-Regular.ttf
<http://cdn.clappr.io/latest/assets/Player-Regular.ttf>'*

HTTP/1.1 200 OK

x-amz-id-2: DXQUkIw5W9+RyVwkY6d6pAedqPYGajvd6gC2Zrj9cAZgoEatxB19Qn78xNqMdmu5

x-amz-request-id: C2BA2A8DAD60ABAE

Date: Fri, 01 May 2015 07:11:47 GMT

Access-Control-Allow-Origin: *

Access-Control-Allow-Methods: PUT, GET, POST, DELETE, HEAD

Access-Control-Max-Age: 3000

Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method

ETag: "3e43a5d764f841e7e78896de82cd6c50"

Server: AmazonS3

Content-Length: 5081

Content-Type: application/x-font-ttf

Last-Modified: Thu, 23 Oct 2014 20:22:09 GMT

Via: 1.1 ntn01-dmz-wsa-1-mgmt.cisco.com:80 (Cisco-WSA/8.5.0-497), 1.1
Application and Content Networking System Software 5.5.37

Connection: Close



2015-05-01 0:21 GMT+03:00 Bruno Torres <notifications@github.com>:

**Comment by towerz** [comment]
@ishahak I noticed you didn't add the Origin header to your curl request. Could you please try it again, using the parameter -H 'Origin: http://localhost:8881'?

I suspect this Cisco ACNS may not set the response headers correcly, even when the Origin header is set. Your browser request/response made me think this way. Maybe testing through a VPN may show whether this is true.

**Comment by ishahak** [comment]
Hi Bruno,
I can confirm that with VPN I do not see this error.
so it means that without "Origin" header, loading of fonts will fail. this
leads to a problem for some corporate networks.
I think you can close this bug.
many thanks!
-Itay

2015-05-02 1:28 GMT+03:00 Bruno Torres <notifications@github.com>:

**Comment by towerz** [comment]
@ishahak Unfortunately this is not easy to solve, but you can work around this issue by hosting the fonts and other assets on the same domain as the page that will load the player. This way, the cross origin policy does not apply and fonts will load correctly.
