### ISSUE TITLE
Need Documentaion on how to use DVR controls

### ISSUE THREAD

**Issue by lkkadiri** [clappr/clappr#430]
I was not able to see or find any documentation on how to enable DVR controls on a live stream. I am able to play a live HLS stream, but have no access to the seek bar as it seems stuck towards the end. Any pointers on how to enable the dvr controls plugin?

**Comment by towerz** [comment]
@lkkadiri You don't need to explicitly enable DVR controls on a live stream. The player detects whether the live stream playlist has a duration considered to have DVR (more than 240 seconds - currently this value is hardcoded) and displays the controls accordingly.

You can enable/disable the DVR controls plugin using the embed parameter useDvrControls (true/false). It's enabled by default.

**Comment by lkkadiri** [comment]
@towerz Thanks for your response, but i feel like i am noticing a bug. I started the stream(click play) and waited over 5 mins, it still would not let me seek, seems to be stuck to the very end on the right. is there anything i need to watch out for?

This is what i have for the player,
<head>
<script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
</head>
<script type="text/javascript">
  var player = new Clappr.Player({source: "http://10.0.1.69/media/hls.m3u8",maxBufferLength: 100, useDvrControls: true, mediacontrol: {seekbar: "#E113D3", buttons: "#66B2FF"}, parentId: "#player"});
</script>

![screen shot 2015-04-30 at 4 15 31 pm](https://cloud.githubusercontent.com/assets/539311/7423622/2dfeba4e-ef54-11e4-9308-9dec6efde882.png)


Any help would be great!

**Comment by towerz** [comment]
@lkkadiri Is your playlist generation set to "appending" mode? Clappr relies on the m3u8 playlist to keep track of previous .ts chunks so it can seek back on live streams. If your playlist is in "rolling" mode it will discard older chunks, and make them inaccessible to the player.

Please try to check whether this is true. Just keep track of your playlist at the beginning of playback and then compare it against the playlist 5 minutes later or so. If the .ts chunks from the former are not present at the latter, then you are set to a rolling playlist and thus DVR is not available.

**Comment by lkkadiri** [comment]
Were using Elemental server to spit out m3u8, it makes chunks of ts files. I am confused about what the append mode and rolling modes are as i see no documentation on elemental to set it. However i do see a bunch of ts files that the playlist uses.

**Comment by jfairley** [comment]
Actually it's "Elemental Live" that we're using. Elemental Server is merely a transcoder.

I'm not sure how to toggle "appending" vs "rolling" mode, but we've tried "VOD mode" (which sounds right) off and on and have no DVR support either way.

Is there anything special in the m3u8 file? Would it be helpful to share a sample playlist file?

**Comment by jfairley** [comment]
It's worth noting that we have also tried JWPlayer. DVR works with that player, but we'd like to use (and eventually contribute to) clappr if we can get the basics working.

**Comment by jfairley** [comment]
Oh. VOD mode works if we give it 240 seconds of buffer time.  Sweet.
