### ISSUE TITLE
Can't press space in input when clappr is loaded

### ISSUE THREAD

**Issue by mortchm** [clappr/clappr#431]
Hi,

when clappr is loaded, you can't press on space in input[type=text]

here is a demo of the bug:

http://site4u.fr/clappr/

try to press on space in the input you will see nothing, the only way to do a space is to press ctrl+space.

Do you know how can i solve this ?

thanks

**Comment by towerz** [comment]
@mortchm Yesterday I pushed a fix for this behavior. Could you please try testing with the version on master? It will probably work as it should.

**Comment by towerz** [comment]
@mortchm Your test page is pointing to the latest version of Clappr (updated today to version 0.0.115). I ran some tests and now the input is working correctly. I'm closing the issue now, please reopen if you find anything wrong.
