### ISSUE TITLE
External RTMP - how to add

### ISSUE THREAD

**Issue by princ007** [clappr/clappr#433]
Hi,
I have downloaded the external rtmp plugin.
I tried to integrate the javascript code and plugin code together with default Clappr player usage code, but it's not working for me :(

Can you, please, help, how to integrate correctly the rtmp plugin to default player?
Thank you.

**Comment by towerz** [comment]
@princ007 I'm not sure what's the problem you are having, could you please paste here the code you are having trouble with?

I checked the latest version of the plugin and it exposes the plugin class(`RTMP`) in the window object, so no `require` is needed. The code should probably look like this:
```html
<script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/0.0.6/rtmp.min.js"></script>
(...)
<div id="player-wrapper"></div>
```
```javascript
var player = new Clappr.Player({
  source: "rtmp://your.source", 
  parentId: "#player-wrapper", 
  plugins: { playback: [RTMP] }
});
```

**Comment by princ007** [comment]
Hi @towerz Thank you for the answer.
I actually tried to use the combination of code for m3u8 and rtmp, but it seems can't be functionally to me.

Here is my code, probably I made some mistakes.
https://gist.github.com/princ007/e2f372223e8a2de39bc0#file-gistfile1-as

**Comment by towerz** [comment]
Hi @princ007, I checked your code and it seems ok. It worked just fine in http://cdn.clappr.io.

The only thing the got my attention is that the scripts in http://www.hits2hits.com/plugins/html5/dist/clappr.min.js and http://www.hits2hits.com/plugins/html5/rtmp/dist/rtmp.min.js are not loading correctly. Probably you need to adjust your HTTP server settings.
