### ISSUE TITLE
0.1.0 not working anymore

### ISSUE THREAD

**Issue by buzzdev** [clappr/clappr#438]
Hi,
until last friday, Clappr 0.0.115 was happily working with live HLS by me.
Since today, the 0.1.0 version, even with your example basic setup doesn't work anymore.

All i get is:
```
Uncaught Error: Error: An invalid exception was thrown.
        n.setFlashSettings.value @ clappr.min.js:3
        n.firstPlay.value @ clappr.min.js:3
        n.play.value @ clappr.min.js:3
        n.play.value @ clappr.min.js:2
        n.clicked.value @ clappr.min.js:4
        ready.a.proxy @ clappr.min.js:6
```
Checking out the previous commit makes it work again.

Could there be some problem?
thanx
m.

**Comment by towerz** [comment]
Hi @buzzdev, have you tested on http://cdn.clappr.io? We've run some tests using HLS both with and without DVR and it's working correctly.

If you are using your own bundled version of clappr, please check if the request for flashlsChromeless.swf is returning ok and if your crossdomain.xml is configured correctly.

**Comment by buzzdev** [comment]
Hi @towerz, i used the cdn version and today i've stripped it to bare minimum of an example in your md, to make sure, that i am not messing it in my app:
```
<head>
  <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
</head>
<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({source: "http://your.video/here.mp4", parentId: "#player"});
  </script>
</body>
```
Even this stopped working after the last commit 3 days ago.
Then i checked out one commit earlier, saved locally, and everything works again.

Crossdomain is set to * and works as expected.

My stream is a live HLS/h264 stream.

thanx
m.

**Comment by towerz** [comment]
@buzzdev I just pushed a new version (0.1.1) to the CDN that solves this problem. The flash object was enforcing that the domain of the page embedding the player is the same as the one serving the swf file.

**Comment by buzzdev** [comment]
@towerz, thanx Bruno, i'll test the new version today and let you know.
My stream is not working at http://cdn.clappr.io so far.

**Comment by buzzdev** [comment]
Hi @towerz, i've updated my local files to 0.1.1 and it does NOT work, same as it does not work at http://cdn.clappr.io with following error:
```
Uncaught TypeError: this.el.playerSetflushLiveURLCache is not a function
```
thanx
m

**Comment by buzzdev** [comment]
Oh! sorry, my fault.
I had it cached and after completely wiping the cache, it is WORKING now.
Many thanxs
