### ISSUE TITLE
HLS playback error

### ISSUE THREAD

**Issue by dasumin** [clappr/clappr#439]
Hi. I'm trying to get hls playback working. It seems to be some bug in the playback source.

With pre-built, cdn-hosted or built on my computer player, I get
``Uncaught TypeError: this.el.playerSetflushLiveURLCache is not a function``
in the browser console, when trying to play HLS.
It is line ``85`` in ``src/playbacks/hls/hls.js``.

When commenting out this line, I get similar errors for other functions under ``this.el``.

**Comment by towerz** [comment]
@dasumin Could you please check whether flashlsChromeless.swf is returning correctly? Have you tested your HLS stream on http://cdn.clappr.io? We've run some tests on this page with both DVR on and off and it's working ok.

If it's really not working on the test page, please send the URL of your video stream or the page where your stream is not working.

**Comment by towerz** [comment]
@dasumin I just pushed 0.1.1 that fixes this problem. Please let me know if something else appears.
