### ISSUE TITLE
Plug-in corruption? Requires version change.

### ISSUE THREAD

**Issue by konashark** [clappr/clappr#443]
I don't believe this is really an issue with Clappr, but I wanted to report this behavior since it will likely affect others. Both members of my team have encountered this now:
The player simply stopped functioning (v 0.0.114). No pulsing dots, nothing. Just the background poster image. Clearing the cache, restarting Chrome, restarting the Mac... nothing fixed it.
Out of desperation, I moved to the latest version of Clappr and it started working again. A short while before the bad behavior began, the browser reported a plug-in crash for Shockwave (I see this about once a week but usually a restart of the browser fixes it.) My only guess is that the plug-in crash corrupted something local to my environment that was tied to the version of Clappr I was using (I don't know if this makes sense or not). But as soon as I moved to a different version of Clappr, the video started working again. Note: I had been using the 'bad' version for a month without any problems so it wasn't the version of the player itself that was bad, but something got corrupted that made it start failing.

**Comment by gotsulyak** [comment]
I've seen the same thing today. Clappr just didn't work - nor local, nor production. Then I've updated it and all things going fine now.

**Comment by towerz** [comment]
@konashark @gotsulyak I couldn't reproduce this issue anywhere I tested. Could you please check whether this still happens? If so, please check if there's something wrong when requesting the SWF. It could mean that the browser is canceling the request or the request is not returning the file in its entirety.
