### ISSUE TITLE
Problem with aspect ratio at Crhome v41

### ISSUE THREAD

**Issue by gotsulyak** [clappr/clappr#444]
I've installed latest Clappr 0.1.1 and it works good with Firefox and IE, but it seems that there's strange bug with Crhome (at least with v41). 

Clappr 0.1.1 plays most of my 16:9 video streams as 4:3 (shrinks them by width) at Chrome browser.

**Comment by konashark** [comment]
Interesting. I'm not seeing this issue in Chrome, but I was seeing something related... a 4:3 stream (at least the content was 4:3, not sure if the actual stream was 4:3 or 16:9) was chopping off 10% (or so) of the top and bottom of the frame. I haven't had enough chance to research to post as an issue, but when I saw your message it made me think there's probably something to what I was seeing.

**Comment by gotsulyak** [comment]
I've attached screenshot from Firefox with right 16:9 and Chrome screen with shrinked screen. As I see now chopped image even more brighter (that's not good and seems like another problem).

![4_3](https://cloud.githubusercontent.com/assets/669544/7596150/58c3329c-f8f4-11e4-983d-ab19eba7f14d.jpg)
![16_9](https://cloud.githubusercontent.com/assets/669544/7596155/5e04f79a-f8f4-11e4-9427-39f647a0dfd3.jpg)

**Comment by towerz** [comment]
@gotsulyak What kind of source are you using? Is it a MP4 file or HLS stream?

**Comment by gotsulyak** [comment]
It's a live HLS. You could try by yourself with similar stream: http://hlsstr04.svc.iptv.rt.ru/hls/CH_MIR/variant.m3u8?version=2

**Comment by konashark** [comment]
I also tried this stream and it started out in 4:3 exactly as you say... but then after a minute or so it corrected to 16:9. Odd.

**Comment by konashark** [comment]
... and now it's gone back to 4:3 squished. Something in stream seems to have triggered it... the content is 4:3 squished, but when it was showing the channel's own splash screens, it was fine.

**Comment by gotsulyak** [comment]
And here another example with http://hlsstr04.svc.iptv.rt.ru/hls/CH_MIR24/variant.m3u8?version=2

Please see thin grey line above player - the exact size of Clappr is 640x360 in both cases.

#1 Firefox - no problems

![16-9](https://cloud.githubusercontent.com/assets/669544/7599096/0f6066f6-f908-11e4-8d8b-5340e0a54374.jpg)

#2 Chrome - video is shrinked (see black parts) and much-much brighter

![4-3](https://cloud.githubusercontent.com/assets/669544/7599099/14317f62-f908-11e4-9f26-6cc98919705f.jpg)

**Comment by towerz** [comment]
@gotsulyak @konashark It seems to be related to hardware acceleration, which is enabled by default. If you disable it with `useHardwareVideoDecoder: false`, the video is displayed correctly.

**Comment by gotsulyak** [comment]
@towerz you are right, the bug disappear without hardware acceleration, thanks! OK, I have to check it with different platforms and browsers later, but for now it's easier simply detect Chrome or disable acceleration by default.
