### ISSUE TITLE
Scaling incorrectly

### ISSUE THREAD

**Issue by kyleparisi** [clappr/clappr#446]
![screen shot 2015-05-12 at 9 51 38 pm](https://cloud.githubusercontent.com/assets/1286753/7602326/366bdb20-f8f1-11e4-8acb-93057f43f964.png)
Bottom is jwplayer for reference.

If I had to guess it has to do with the console output: 
	
	192.168.0.11/:1 [.PPAPIContext]GL ERROR :GL_INVALID_ENUM : glTexImage2D: target was GL_TEXTURE_RECTANGLE_ARB

Different browsers didn't work.  Stream was a live RTMP.

**Comment by towerz** [comment]
@kyleparisi This seems to be a problem with google chrome pepper flash player. As far as I know it's a problem with hardware acceleration. The RTMP plugin doesn't seem to include an option for disabling hardware acceleration, but I think it needs it to support google chrome correctly.

**Comment by kyleparisi** [comment]
Ah I see.  Shall I post on the clappr rtmp plugin page?

**Comment by towerz** [comment]
Yes, I think it would be better to have an issue in the plugin project.

**Comment by timbiker** [comment]
Dears,
I just want to comment that I have a issue which seems to be similar.
I play a 4:3 video in a 4:3 size clappr player, and I get a black part at the top and a missing part at the bottom.

I am also unable to select different full screen mode (fit/fill...)

**Comment by towerz** [comment]
@timbiker What kind of video are you playing when you have these issues?

About different fullscreen modes, Clappr still doesn't support this. It always fits the content inside the player frame.

**Comment by timbiker** [comment]
Indeed I forgot to mention,
I am also using the the rtmp plugin, reading an flv(h264+aac) stream encoded with ffmpeg.

Playing the stream with JWplayer or vlc is just fine

**Comment by towerz** [comment]
Since this issue is related to the RTMP plugin, I'll close this one.

Regarding supporting other fullscreen modes, we don't have any plans to implement this, since it's directly related to how the playback plugins work. If the playback plugins add support for this feature, it will be automatically enabled in Clappr.
