### ISSUE TITLE
Weird error on OSX

### ISSUE THREAD

**Issue by shaharmor** [clappr/clappr#447]
Hi,
I'm getting this weird error in the console whenever clappr starts playing (hls):
[.PPAPIContext]GL ERROR :GL_INVALID_ENUM : glTexImage2D: target was GL_TEXTURE_RECTANGLE_ARB

Any idea what that is?

**Comment by leandromoreira** [comment]
I think this is an issue related to flash and chrome https://code.google.com/p/chromium/issues/detail?id=454251 
What do you think @towerz @thiagopnts @flavioribeiro is it related to either clappr or flashls?

**Comment by flavioribeiro** [comment]
yep, its related to pepper flash implementation. @shaharmor, are u experiencing black screens when facing this error?

**Comment by shaharmor** [comment]
No, the issue does not affect the streaming at all, its just the console
logs...

**Comment by towerz** [comment]
This annoying message will stop occurring after we change hardware acceleration defaults and close #450.

I'll close this issue for now.
