### ISSUE TITLE
Google Analytics plugin not working on Chrome

### ISSUE THREAD

**Issue by AndCycle** [clappr/clappr#451]
I am a newbie using clappr,
just playing around google analytic trying to get some result,

I found that when using Chrome 42, clappr won't send out any ga related event,
but ga plugin works under Fx 38.

**Comment by leandromoreira** [comment]
if it's still a problem we'll reopen it.

**Comment by AndCycle** [comment]
the problem is based on you can't mix http and https content, 
cause by clapper is currently still hosted on http://cdn.clappr.io/latest/clappr.js ,
just be sure not to do assumption on protocol.

**Comment by leandromoreira** [comment]
@AndCycle Thank you very much !!!!
