### ISSUE TITLE
doesn't handle https

### ISSUE THREAD

**Issue by AndCycle** [clappr/clappr#452]
when embed clappr in https web site,
it will try to get file under http which trigger security alarm due to http/https mix,
then result in failed loading plugin or related file (ga.js

**Comment by towerz** [comment]
@AndCycle We're in the process of migrating http://cdn.clappr.io to the project sponsor CDN. We plan to enable HTTPS during this migration.

You could also host your own version of Clappr in your HTTPS enabled domain, you just need to set the baseUrl parameter accordingly.

**Comment by AndCycle** [comment]
@towerz thanks for the hint :)
