### ISSUE TITLE
Level Selector is not working with the latest version

### ISSUE THREAD

**Issue by tarkanlar** [clappr/clappr#456]
It loads and shows HD but it doesn't let you choose the bitrate

![alt text](https://i.imgur.com/p2bqTrf.png?1)

**Comment by flavioribeiro** [comment]
hey @tarkanlar I think you should open this issue on the [plugin](https://github.com/clappr/clappr-level-selector-plugin)'s repo!

**Comment by towerz** [comment]
Closing this issue since clappr/clappr-level-selector-plugin#2 was created.
