### ISSUE TITLE
Mediator doesn't support multiple parameters

### ISSUE THREAD

**Issue by shaharmor** [clappr/clappr#463]
Hi,

It seems that the Mediator class doesn't support passing triggering an even with more than one parameter.

For example:
```javascript
Mediator.on('eventName', function(arg1, arg2, arg3) {
    // only arg1 will be passed here
});
Mediator.trigger('eventName', arg1, arg2, arg3);
```

**Comment by thiagopnts** [comment]
A common pattern is to pass an `options` hash instead of multiple arguments, like this:

```javascript
Mediator.on('eventName', function(options) {
    console.log(options.arg1, options.arg2); // foo bar
});
Mediator.trigger('eventName', {arg1: 'foo', arg2: 'bar' });
```

**Comment by shaharmor** [comment]
I know, but even in Clappr itself there are places that trigger with multiple paramters...

https://github.com/clappr/clappr/blob/master/src/playbacks/hls/flashls_events.js#L11
https://github.com/clappr/clappr/blob/master/src/playbacks/hls/flashls_events.js#L17
https://github.com/clappr/clappr/blob/master/src/playbacks/hls/flashls_events.js#L20

and probably others...
