### ISSUE TITLE
Mpeg-dash plugin through dash.js integration

### ISSUE THREAD

**Issue by deedos** [clappr/clappr#467]
Hi.

How difficult would be to have a mpeg-dash plugin for Clappr, through an integration with Dash.js like video.js did here https://github.com/Dash-Industry-Forum/dash.js/tree/development/contrib/videojs . Once the dash plugin from @shankardevy is outdated and not working, integration with a heavily developed player for the matter would be nice
thanks

**Comment by towerz** [comment]
Hi @deedos, we are analyzing how to add Dash support to Clappr, either through a plugin or built-in playback.

**Comment by flavioribeiro** [comment]
there's also a effort to make a plugin [here](https://github.com/opendrops/clappr-dash-plugin) but seems to be abandoned. I think that make sense to ping the owner before bootstrap another one

**Comment by leandromoreira** [comment]
I also started to play with https://github.com/google/shaka-player

**Comment by towerz** [comment]
@flavioribeiro it seems that the project you mentioned didn't even start. There's only the initial commit and the code seems to be only a bootstrap, perhaps generated by the plugin generator.

**Comment by flavioribeiro** [comment]
@towerz I saw it working some time ago, maybe @opendrops didn't push everything to github

**Comment by shankardevy** [comment]
guys, I am not actively working on dash integration these days.

**Comment by jfairley** [comment]
I would love to see DASH integration. I tried to use [shankardevy/clappr-dash-plugin](https://github.com/shankardevy/clappr-dash-plugin), because it is linked from the

README. Unfortunately, it's not in NPM, so I cloned it. I'm struggling to get it integrated. Is anyone else using this plugin successfully?

**Comment by towerz** [comment]
@jfairley this plugin is based on clappr version 0.1.x. It won't work with 0.2.x as is, but I think it wouldn't be so hard to make some changes.

@leandromoreira and I are working on plugins based on (shaka-player)[https://github.com/google/shaka-player] and (dash.js)[https://github.com/Dash-Industry-Forum/dash.js], but both are still in progress.

**Comment by jfairley** [comment]
How is the progress going? I suspect I'm better off waiting rather than fixing the other plugin.

**Comment by flavioribeiro** [comment]
so @leandromoreira built a plugin for DASH support on clappr, check it out on https://github.com/clappr/dash-shaka-playback

**Comment by leandromoreira** [comment]
we also did a playback using dashjs (https://github.com/leandromoreira/clappr-dash-dashjs) although it's not the best option IMO
