### ISSUE TITLE
Uncaught TypeError: Error #1009

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#469]
This error is rising up every time the player load a new hls source !

**Comment by towerz** [comment]
@irongomme Are you loading another source using `load` or instantiating a new player?

Does this happen on any specific browser/OS?

**Comment by irongomme** [comment]
I've only tested on chrome (v43) linux

This happened on first load, and then i use load method to change the source (core.load)

**Comment by towerz** [comment]
@irongomme I've tested on chrome v43 on all OSes (Windows, Linux, OS X) and it worked ok. What flash version and Linux distribution are you using?

**Comment by irongomme** [comment]
@towerz I have a testing environment here : http://www-pp.iwiplay.net/play/2/7

For your questions : 
i'm using OpenSuSe 13.2 with Adobe Flash Player - Version : 17.0.0.188

**Comment by irongomme** [comment]
I've found the break point : 

This error is raised when i trigger play externaly : 

```
var container = player.core.getCurrentContainer();
container.play()
```

Stacktrace  : 

```
Uncaught TypeError: Error #1009(anonymous function) 
@ VM4251:1play 
@ clappr.js:5897play 
@ clappr.js:3629(anonymous function) 
@ TvCtrl.js:73triggerEvents 
@ clappr.js:8441trigger 
@ clappr.js:8379ready 
@ clappr.js:3578triggerEvents 
@ clappr.js:8441trigger 
@ clappr.js:8379bootstrap 
@ clappr.js:5845(anonymous function) 
@ clappr.js:5809triggerEvents 
@ clappr.js:8439trigger 
@ clappr.js:8379Mediator.trigger 
@ clappr.js:8843ready 
@ clappr.js:5640_createClass.createCallbacks.value.window.Clappr.flashlsCallbacks.(anonymous function) 
@ clappr.js:6141(anonymous function) 
@ VM4246:1
```

After testing with old releases, i've found this error came between release 0.1.0 and 0.1.1

**Comment by irongomme** [comment]
I've compared those two releases, and it seems to be a HLSPlayer issue, because the only difference which make it happened is the replacement of flashlsChromeless by HLSPlayer !

**Comment by towerz** [comment]
@irongomme I've tested this in your environment, and it seems to be a problem related to using both `autoPlay: true` and calling `play()` when the `playback:ready` event is triggered. Seems to be a race condition.

Try removing the call to `currentContainer.play()` on the `playback:ready` event, letting the autoPlay handle it instead. Please let me know if this works for you, since I can't test your stream (I'm receiving an error 403 when trying to load it).

**Comment by leandromoreira** [comment]
@irongomme is this still valid?
