### ISSUE TITLE
Strange behavior clappr-level-selector-plugin

### ISSUE THREAD

**Issue by wicherdt** [clappr/clappr#471]
No autohide after select stream quality.
![screen](https://cloud.githubusercontent.com/assets/11627731/7892680/b7c0920c-0656-11e5-96fe-9a603d76eaff.png)

Another on console log:
TypeError: this.getContainer(...).playback.el.playerSmoothSetLevel is not a function
this.getContainer().playback.el.playerSmoothSetLevel(level);

Firefox 38.0.1
Clappr 0.1.4
clappr-level-selector-plugin version with Commits on May 17, 2015

**Comment by towerz** [comment]
Hi @wicherdt, please try to open plugin-related issue in the plugin repository. This one has been fixed on https://github.com/clappr/clappr-level-selector-plugin/commit/2208be71d169ae9836dd2487e263fe7c8397afb7. We'll release a new version of the plugin soon.

Please let me know if it's working for you.
