### ISSUE TITLE
gitter.im channel

### ISSUE THREAD

**Issue by anthonyettinger** [clappr/clappr#475]
Can we add a gitter.im channel for clappr?

**Comment by flavioribeiro** [comment]
+1 for the gitter channel

**Comment by thiagopnts** [comment]
I've been using gitter with nickel.rs, really good so far

**Comment by towerz** [comment]
Sure, why not? :+1:

**Comment by anthonyettinger** [comment]
one of the core team members needs to sign in and initiate the PR to add the badge. Pretty easy to do.

**Comment by thiagopnts** [comment]
Done :)
https://gitter.im/clappr/clappr

**Comment by towerz** [comment]
:beers:
