### ISSUE TITLE
ability to disable console messages

### ISSUE THREAD

**Issue by VladimirVSgh** [clappr/clappr#479]
After start hls playback i see a lot of console messages:

INFO:HLSNetStream:close
INFO:HLSNetStream:play(-1)
INFO:HLSNetStream:seek(-1)

Is there a way to hide it? window.DEBUG = false can't help for these messages.

console.log = function () {} works, but it is not good.

**Comment by thiagopnts** [comment]
AFAIK these messages are from flashls, maybe we can disable it in our fork clappr/flashls

**Comment by towerz** [comment]
Hi @VladimirVSgh, I just pushed a change that adds a parameter `hlsLogEnabled` to control whether these messages are shown. The default value is `true`.

We still haven't released a version with this change, but you can test using the one in `master`.

**Comment by chovy** [comment]
How do I use this flag?

**Comment by towerz** [comment]
@chovy Just add `hlsLogEnabled: false` to embed parameters:
```javascript
var player = new Clappr.Player({
    ...
    hlsLogEnabled: false,
    ...
});
```
