### ISSUE TITLE
Player is not respecting the redirected URLs when loading segments

### ISSUE THREAD

**Issue by konashark** [clappr/clappr#482]
I'm not sure I fully understand the details of this issue, but the video server experts on my team say this is causing a lot of problems and inefficiencies in the video delivery:

When the player requests the manifest file and it hits a HTTP 302, the client should remember the new location for all subsequent requests instead of hitting the base endpoint every time (which will every time result in a HTTP 302, causing unnecessary round trip times and delay).

The m3u8s contain relative paths too, so the player is appending these relative paths to the original URL rather than the 302 redirected URL.

**Comment by towerz** [comment]
Hi @konashark, our HLS playback uses a flash implementation based on flashls. Unfortunately, the flash code is not aware of redirects, and there's no way to detect whether a redirect occurs or obtain the final URL inside the flash player environment.

I would recommend not using redirects due to this limitation. Adobe Air and other ActionScript based environments offer this feature, but it's missing on the flash player environment.

**Comment by konashark** [comment]
Thanks for the quick reply (that somehow I missed yesterday).
I'm assuming from your answer, that the Flash portion of the player is not code that we have access to... ie: if we were to try to figure out how to enhance the code ourselves?

**Comment by towerz** [comment]
No, the flash portion of the player is code we can change. Unfortunately the URLLoader api is restricted in the flash plugin environment.

Before replying I tried to enhance our HLS implementation listening to a response status event when requesting the main playlist. In the browser flash plugin, the event never occurs. Checking the documentation I discovered the event is only available in desktop apps, but not in the browser.

**Comment by konashark** [comment]
Thanks for looking into this. Is the bottom line that this would be tricky, or that it would be pretty much impossible? Wondering if I should sic one of my hacker colleagues on it, or not to bother.

**Comment by towerz** [comment]
I believe this would be impossible due to the nature of the flash plugin. Perhaps your hacker colleagues could take a look at it, but I wouldn't reccomend implementing a hack to support redirects. In this case I keep my recommendation to avoid redirects whenever possible.

**Comment by towerz** [comment]
Closing this issue, since we can't fix this behavior.
