### ISSUE TITLE
FlashHLS not working in IE10

### ISSUE THREAD

**Issue by vrehak** [clappr/clappr#483]
I tested using http://91.121.17.70/clappr.html in IE10 on Windows 7 and Windows 8. Clicking on the triangle play button does not play the video, only the following messages appear in console:
INFO:HLSNetStreamer:close
INFO:Setting audio track to 0

I don't think the problem is in FlashHLS itself, because the example with Flowplayer at http://flashls.org/flashls-0.4.1.0/examples/flowplayer/ works as expected.

**Comment by towerz** [comment]
Hi @vrehak could you please test again using http://flashls.org/flashls-0.4.1.0/examples/chromeless/ instead? Clappr HLS implementation is based on flashls chromeless player.

**Comment by vrehak** [comment]
Yes, the chromeless example works in my test IE10 on Windows 8.

**Comment by towerz** [comment]
The main difference between both tests (Clappr Flashls vs Chromeless Flashls) is that Clappr enables hardware acceleration by default for the HLS playback. You could try and disable it for older IE versions.

Just set the parameter `useHardwareVideoDecoder` to false to disable hardware acceleration. Please let me know if this solves your problem.

**Comment by stanogurnik** [comment]
We were able to start HLS stream on IE10 when  `useHardwareVideoDecoder` is set to false. Thank you

**Comment by towerz** [comment]
I think we can close the issue right now. I just pushed a change to make `useHardwareVideoDecoder` default value to be `false`.
