### ISSUE TITLE
Expose logging capabilities

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#484]
Log object (https://github.com/clappr/clappr/blob/master/src/plugins/log/log.js) could be useful within plugins or player extensions. What do you think ? @thiagopnts @towerz @flavioribeiro

**Comment by towerz** [comment]
:+1: totally agree

**Comment by towerz** [comment]
I would suggest introducing some changes to the log plugin, like setting the player log level, instead of using a global variable DEBUG to set whether or not log messages are enabled.

**Comment by leandromoreira** [comment]
@towerz can you see if it's okay with your idea?

**Comment by thiagopnts** [comment]
We could also not require it when building for production

**Comment by towerz** [comment]
@leandromoreira cool, that's exactly what I suggested.

@thiagopnts what do you mean by not requiring it when building for production? Not having any log messages shown or not having the log plugin available? We opted for making the default log level only have WARN or ERROR messages.

**Comment by thiagopnts** [comment]
not having the plugin in the bundle
