### ISSUE TITLE
Chrome doesn't play HLS with height/width set to 100%

### ISSUE THREAD

**Issue by yisding** [clappr/clappr#485]
It gives an error 1009 (I think this is from flash?)

**Comment by towerz** [comment]
@yisding The error code 1009 is from flash, and means that a null object has been referenced. Looking further into the issue it seems like you set width/height to 100% but the parent element have an undefined size, like zero width or height.

If you set the size of the player parent element, setting 100% to either width or height (or both) will work correctly.

**Comment by yisding** [comment]
Thanks Bruno! I'll give that a try.

**Comment by towerz** [comment]
I made a small change to the [Clappr test page](http://cdn.clappr.io) to allow testing with percent values. You can test there if you want.

**Comment by towerz** [comment]
Closing issue. Please reopen if there are further questions.
