### ISSUE TITLE
player not do working with crossdomain.xml

### ISSUE THREAD

**Issue by dinhkhaihtc** [clappr/clappr#494]
I had custom crossdomain.xml file but player remains inactive

site-control permitted-cross-domain-policie=all
allow-access-from domain="*.mydomain.com" secure="false"
allow-http-request-headers-from domain="*.mydomain.com" headers="*" secure="false" 

div id="player"
 script
    var player = new Clappr.Player({source: "http://mydomain.com/demo/playlist.m3u8", parentId: "#player"});
  script

**Comment by chsergey** [comment]
try to set param
 baseUrl: 'your_base_url' + path_to_clapper_assets

**Comment by towerz** [comment]
@dinhkhaihtc Are you loading Clappr from your own domain? If so, you should configure the `baseUrl` parameter as @chsergey mentioned. If not, please let me know how your setup works and what errors messages are displayed.

**Comment by ebuildy** [comment]
Here my crossdomain.xml:

````xml
<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy SYSTEM
"http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
    <site-control permitted-cross-domain-policies="all"/>
    <allow-access-from domain="*" secure="false"/>
    <allow-http-request-headers-from domain="*" headers="*" secure="false"/>
</cross-domain-policy>
````

Served by Nginx:

````
location = /crossdomain.xml
{
add_header Content-Type text/x-cross-domain-policy;
}
````

Give a try!
