### ISSUE TITLE
"Stretching" HLS video

### ISSUE THREAD

**Issue by chriswiggins** [clappr/clappr#498]
Guys,

Looking through Clappr source it isn't obvious what Flashls source is being used for Clappr. I'd like to add support to stretch, letterbox and zoom the video playing though HLS but I can't seem to find where I can modify this to make it happen!

Let me know and I'll make a PR.

Thanks
Chris

**Comment by towerz** [comment]
@chriswiggins We use our own fork of flashls (https://github.com/clappr/flashls). We keep the `dev` branch synced with the original flashls and use our custom player classes in the `clappr` branch.

There's a separate build script, called `build_clappr.sh` used for creating the HLSPlayer.swf used on the hls playback.

If you have any further questions please let me know.

**Comment by chriswiggins** [comment]
Brilliant thanks. If I have any issues modifying it, I'll comment over there.

**Comment by tarkanlar** [comment]
Is there any updates on this issue? @chriswiggins
