### ISSUE TITLE
can not play m3u8 file

### ISSUE THREAD

**Issue by luhaiyong** [clappr/clappr#500]
hi ,
i use IE11 ,my test code is

  <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>

    var player = new Clappr.Player({source: "output.ts", parentId: "#player"});

output.ts : is my test file,
when the player source is mp4, that broswer can play !
but i change to TS ,or m3u8 ,it is failed
and the test file m3u8 can be played in VLC player in my pc!

plz help me !
thanks!

**Comment by flavioribeiro** [comment]
hey @luhaiyong first of all you need to point clappr to the correct manifest file (m3u8) instead of the ts itself. Can you send us your HLS source url?

**Comment by luhaiyong** [comment]
hey ,flavoribeiro.
may test code 
var player = new Clappr.Player({source: "http://live.3gv.ifeng.com/live/hongkong.m3u8", parentId: "#player"});

http://live.3gv.ifeng.com/live/hongkong.m3u8 .i use VLC player,that can play.

i use IE 11 ,can not play show noting,then i use firefox ,it shows"your browser does not support rhe playback of this vedio,try to use a different browser"

plz help test ,if u work well ,plz send me your test code .
thanks very much!

**Comment by flavioribeiro** [comment]
could you upload a `crossdomain.xml` file on `http://live.3gv.ifeng.com/crossdomain.xml` with the content below?

```
<cross-domain-policy>
<site-control permitted-cross-domain-policies="all"/>
<allow-access-from domain="*" secure="false"/>
<allow-http-request-headers-from domain="*" headers="*" secure="false"/>
</cross-domain-policy>
```

**Comment by luhaiyong** [comment]
hey ,flavioribeiro.
i build a local nginx server .
i push my m3u8 file and ts file in the folder: /usr/local/nginx/html/app
and do as u said add a crossdomain,xml in the floder /usr/local/nginx/html/ 
the code in crossdomain,xml is the same as above.

then i test again ,failed again ,show noting ! vlc player  also can play!
plz help me !
thanks very much!

**Comment by flavioribeiro** [comment]
I still can't see the crossdomain on http://live.3gv.ifeng.com/crossdomain.xml

**Comment by flavioribeiro** [comment]
any updates on this @luhaiyong ?

**Comment by mak999** [comment]
hi ! Can you help me playing m3u8 file with clappr ?

http://urtmpkal-f.akamaihd.net/i/077zoqxzy_1@130091/index_3_av-p.m3u8

thanks
