### ISSUE TITLE
can't support #EXT-X-PROGRAM-DATE-TIME

### ISSUE THREAD

**Issue by tokenian** [clappr/clappr#506]
when hls m3u8 has #EXT-X-PROGRAM-DATE-TIME, clappr not work.
but we cut off the #EXT-X-PROGRAM-DATE-TIME, it works
environment: pc firefox 39.0 or chrome 37

**Comment by towerz** [comment]
@tokenian Could you please elaborate on that? 

What kind of source are you trying to load? Do you have any sample streams we can use to reproduce this error?

**Comment by flavioribeiro** [comment]
@tokenian can you still reproduce this error with hlsjs?
