### ISSUE TITLE
How to reload M3U8 when TS file status 404 ?

### ISSUE THREAD

**Issue by devin87** [clappr/clappr#508]
If the TS file status 404,clappr always retry to load the TS file ,how can I listen the error Event? or clappr how to reload M3U8 after error.
```
ERROR:I/O Error while loading fragment:HTTP status:404,msg:Error #2032
live.html
WARN:retry fragment load in 1000 ms, count=0
```

I've tried something like this, but not work:
```
//PLAYER_ERROR
//PLAYBACK_ERROR
//CONTAINER_ERROR
player.on(Clappr.Events.CONTAINER_ERROR, function(){});
player.core.getCurrentContainer().on(Clappr.Events.CONTAINER_ERROR, function(){});
```

clappr:0.18

**Comment by towerz** [comment]
@devin87 Currently, Clappr only report HLS errors that are critical, when the playback fails. These retries are automatic, the player keeps trying to load a given TS file until a limit is reached, then it stops and triggers an error event.

If it's not doing that correctly, please let me know. Perhaps there's a bug in that.

**Comment by devin87** [comment]
@towerz Thanks. Here is the console log.
```
ERROR:I/O Error while loading fragment:HTTP status:404,msg:Error #2032
hls.html
WARN:retry fragment load in 4000 ms, count=2

ERROR:I/O Error while loading fragment:HTTP status:404,msg:Error #2032
hls.html
WARN:max load retry reached on last fragment of live playlist, retrying loading this one...

ERROR:I/O Error while loading fragment:HTTP status:404,msg:Error #2032
hls.html
WARN:max load retry reached on last fragment of live playlist, retrying loading this one...

...(not stops)
```

1. I do not know how to catch the exception in player (some events seems not trigger)?
2. HLS has timeout configuration for load the m3u8 or TS file?

**Comment by towerz** [comment]
Hi @devin87, I have been testing some options and adding some extra parameters to control HLS behavior.

If you use the latest version of clappr, you can now listen to the error event in case the fragment loading fails and the player stops retrying. The default behavior now is to not skip to the next fragment after reaching the maximum number of retries. Instead, it triggers an error event, which you can listen to and handle accordingly.

You can now control HLS retry behavior using the following parameters:
- `keyLoadMaxRetry` - the maximum number of retries for loading decryption keys after a load error occurs
- `keyLoadMaxRetryTimeout` - the maximum retry timeout (in ms) for loading decryption keys after a load error occurs
- `fragmentLoadMaxRetry` - the maximum number of retries for loading fragments after a load error occurs
- `fragmentLoadMaxRetryTimeout` - the maximum retry timeout (in ms) for loading fragments after a load error occurs
- `fragmentLoadSkipAfterMaxRetry` - whether or not the player should skip to the next fragment after reaching the maximum number of retries. If set to false, an error event is triggered instead.

**Comment by devin87** [comment]
@towerz Thanks very much. I used some of the ways to let the player continue,some code like this.
```
setInterval(function(){
    if(is_playing) {
        //playback occasionally get stuck, the state still PLAYING
        if(player.core.mediaControl.container.playback.currentState == "PLAYING") do something;
        else {
            ...
            player.core.mediaControl.container.playback.firstPlay();
        }
    }
}, 2000);
```

I found another issue in the new version(clappr:0.1.13-0.2.5),the element(div.spinner-three-bounce)  not hidden after the player started playing.

**Comment by towerz** [comment]
@devin87 Can you share the source you are using? When you say the player gets stuck, you are referring to this retry loop you mentioned before? If so, on 0.2.5 the default behavior is to give up after retrying the current fragment, so you would get an error instead of the retry message.

About the spinner not hiding after playback starts, I could not reproduce. Could you please share the steps to reproduce this?

**Comment by devin87** [comment]
@towerz I can't test because the api server have some problems. I said the player gets stuck,not IO error, it happened on linux sometimes, I think is the decoding or graphics driver question. I mean can the player change the state when playback error?

The spinner hidden question, when the playback init, refresh the page, sometimes will ok,sometimes not. The version 0.1.8 no the problem.

Clappr is a great project (If can support to IE8 would be better, ha ha...). Thanks all of you. Here is the my code about playback.
```javascript
var player;

function create_player(src) {
    if (player) player.destroy();

    player = new Clappr.Player({
        parentId: "#player",
        baseUrl: "clappr",
        source: src,
        useHardwareVideoDecoder: true,

        autoPlay: true
    });

    var timer, is_playing, last_error_time;

    player.on(Clappr.Events.PLAYER_PLAY, function () {
        is_playing = true;

        if (timer) return;

        timer = setInterval(function () {
            if (!is_playing) return;

            if (player.core.mediaControl.container.playback.currentState == "PLAYING") {
                last_error_time = 0;
            } else {
                if (!last_error_time) last_error_time = Date.now();
                else {
                    var time = Date.now();
                    if (time - last_error_time > 5000) {
                        last_error_time = time;
                        player.core.mediaControl.container.playback.firstPlay();
                    }
                }
            }
        }, 2000);
    });

    player.on(Clappr.Events.PLAYER_STOP, function () {
        is_playing = false;
    });
}
```

**Comment by devin87** [comment]
I test right now, if I change the channel,  the spinner not hidden.
```
create_player(src1);
create_player(src2);
```
