### ISSUE TITLE
“Update Your Browser” Error

### ISSUE THREAD

**Issue by gofdias** [clappr/clappr#513]
Presenting a message for those whose browsers are old.

**Comment by gofdias** [comment]
![situacoes_de_erro-browser_antigo](https://cloud.githubusercontent.com/assets/12396236/9044429/f6fe00a6-39f2-11e5-84a4-a7f010fe0a03.png)

**Comment by gofdias** [comment]
![situacoes_de_erro-browser_antigo](https://cloud.githubusercontent.com/assets/12396236/9044451/215395a0-39f3-11e5-84bc-ab90a1d9dd41.jpg)

**Comment by thiagopnts** [comment]
wrong repo? :P

**Comment by flavioribeiro** [comment]
awesome error screen, btw :+1:

**Comment by towerz** [comment]
:+1:

**Comment by gofdias** [comment]
Sorry, boys. Thanks, @flavioribeiro!
