### ISSUE TITLE
not working help!!!

### ISSUE THREAD

**Issue by kingjedidiah** [clappr/clappr#515]
error in rtmp of clappr in the scrit...
helppppppp

![screenshot 19](https://cloud.githubusercontent.com/assets/13598741/9056345/ee785e26-3a3e-11e5-84a8-c5e7d0d5a2b2.png)

**Comment by thiagopnts** [comment]
Can you share your source? Also I'm not sure if you can play a stream from a `file://`

**Comment by flavioribeiro** [comment]
@kingjedidiah hey, with the last updates on the plugin your stream should play fine. Feel free to open this issue again if u face issues.
