### ISSUE TITLE
How can i make video from 4:3 to 16:9

### ISSUE THREAD

**Issue by nextlivetv** [clappr/clappr#523]
I use strem in 4:3 720X576 because I need less CPU when with jwplayer i can stretching it.
How can i make video from 4:3 to 16:9  like in JWplayer with option stretching: exactfit ;
Please help me.
http://support.jwplayer.com/customer/portal/articles/1413113-configuration-options-reference

**Comment by towerz** [comment]
@nextlivetv currently Clappr doesn't support stretching the media source, instead using black bars and centering the media, so there's no options for that.

Could you explain more how are you using this? Are you simulating anamorphic pixel aspect ratio using this? Are you using this for progressive download or for streaming?

**Comment by tarkanlar** [comment]
I really need to stretch media source anyone can any idea how we can do this?

**Comment by nextlivetv** [comment]
there's no option.
I tried all options.
You have to use 16:9 and probleme its done.

**Comment by tarkanlar** [comment]
I just saw clappr is moving to hlsjs (https://github.com/clappr/clappr/issues/555) so may be it will be solved there

**Comment by tarkanlar** [comment]
Nope not solved with the hlsjs as well

**Comment by flavioribeiro** [comment]
@mangui, what's your thoughts on this one? do u think it's feasible to implement on hlsjs? I wonder if it's possible to play with canvas size in order to accomplish this behavior

**Comment by mangui** [comment]
in flash you can easily stretch, jwplayer uses the following code to stretch:
https://github.com/jwplayer/jwplayer/blob/master/src/flash/com/longtailvideo/jwplayer/utils/Stretcher.as.

in html5, it has nothing to do with hls.js, you just need to find a way to stretch the video element itself.
CSS3 transform seems to be the way
http://stackoverflow.com/questions/3779771/html-5-video-stretch/3780896#3780896
