### ISSUE TITLE
main in package.json for version 0.2.7

### ISSUE THREAD

**Issue by dviramontes** [clappr/clappr#532]
Currently for version 0.2.7 
the package.json looks like 

`main: 'src/main.js' `

As a browserify consumer of clappr, this fails to build and bundle correctly.

Can we point main to `dist/clappr.min.js` for this release ?

cc: @jfairley @lkkadiri

**Comment by jfairley** [comment]
https://github.com/clappr/clappr/commit/b309deb795fa0f02cd024f46751385972b1dd3fd

**Comment by dviramontes** [comment]
duplcate of https://github.com/clappr/clappr/issues/532
closing.
