### ISSUE TITLE
problem with npm run release

### ISSUE THREAD

**Issue by cherihung** [clappr/clappr#534]
Tried to do a `npm run release` after pulling down the repo.
But I'm not able to. getting an error:

```
8 info clappr@0.2.8 Failed to exec release script
9 error clappr@0.2.8 release: `webpack --progress -d -p --optimize-minimize --optimize-dedupe --output-filename clappr.min.js`
9 error Exit status 8
10 error Failed at the clappr@0.2.8 release script.
10 error This is most likely a problem with the clappr package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     webpack --progress -d -p --optimize-minimize --optimize-dedupe --output-filename clappr.min.js
```

**Comment by towerz** [comment]
@cherihung what OS and node version are you using? 

Can you run the command `webpack --verbose --progress -d -p --optimize-minimize --optimize-dedupe --output-filename clappr.min.js` and paste here the output?

**Comment by cherihung** [comment]
It was with dependencies not installing correctly I think. I cleared my npm cache and reinstalled all modules, then manually npm installed webpack. It is now running that script. Thanks! 
p.s. i'm on Win7 node 1.4.X

**Comment by towerz** [comment]
Everything is working fine then. That's great! :+1:
