### ISSUE TITLE
[Clappr.Log] set log level to disabled

### ISSUE THREAD

**Issue by cherihung** [clappr/clappr#540]
Just pulled the latest from upstream. What does this log error message mean?
(I saw it streaming HLS feed)

Also is there any way to mute console message like this one?
**FlasHLS Clappr (version: 0.4.2.3 - flashls: 0.4.2.1, id: o6)**

Setting `hlsLogEnabled` to false didn't turn it off. And looking at the newly exposed set of hls config options, nothing jumps out as the right option.

**Comment by towerz** [comment]
@cherihung this message is just to inform the current log state. It's a side effect of setting the log to disabled on initialization.

The Flashls message cannot be muted right now, but it will respond to `hlsLogEnabled` in the next version.

**Comment by towerz** [comment]
@cherihung I removed the Clappr.Log message on initialization on a6a7a12490240561f5fd062fba5391574ca0bf5c, and updated the clappr flashls implementation to 0.4.3 which responds to `hlsLogEnabled` on 3f5fdf903564c0367cfd26cd826206d4033902cd.
Both commits are included in version 0.2.10.

**Comment by cherihung** [comment]
terrific. thanks!

**Comment by towerz** [comment]
Closing the issue then. :+1:
