### ISSUE TITLE
HLS stream sometimes appear to be stuck

### ISSUE THREAD

**Issue by cherihung** [clappr/clappr#541]
I'm hoping for any suggestion or direction to debug this issue with what these HLS log messages mean. 

Been testing clappr in the last few days to stream HLS manifests. 
Mostly it's been smooth but there are times when a stream would appear to be stuck upon loading. autoplay is set to true.

I test played the stream on Flashls.org, worked fine each time.
But with clappr, it's just stuck with the loading dots kept loading. But I'm seeing the segments being downloaded via the Network tab.

The hlslog message is as below:
```
INFO:HLSNetStream:close
INFO:HLSNetStream:play(-1)
INFO:HLSNetStream:seek(-1)
INFO:Setting audio track to 0
```
so the last bit of message is always on `INFO:Setting audio track to 0` instead of `INFO:Video decoding:software` when a stream plays successfully.

I'm sorry that I cannot share the URL to the actual stream. But I can say a smoothly working stream and this buggy stream are hosted on the same server. I'm seeing this issue on firefox and chrome consistently.

**Comment by leandromoreira** [comment]
Thanks @cherihung can you describe (or give us a little bit more detail) the steps to reproduce this behavior? 

Even if you use this url `http://www.streambox.fr/playlists/test_001/stream.m3u8` you still will face (sometimes) this **stuck**? is it on VOD or live?

**Comment by cherihung** [comment]
When I use this http://www.streambox.fr/playlists/test_001/stream.m3u8 I have not encountered the "stuck" issue. The streams I'm trying are all VODs. 

My project is in Angular (1.2). The stream url is passed in dynamically. I initiate the Clappr player in a angular.element(document).ready(...). And I'm creating the player instance like so:

```
var player = new Clappr.Player({ ...  });
...

thanks!

**Comment by leandromoreira** [comment]
The stream http://www.streambox.fr/playlists/test_001/stream.m3u8 is also a **vod**. If you tested this url http://www.streambox.fr/playlists/test_001/stream.m3u8 at http://cdn.clappr.io/ and you can't reproduce this behavior it might be a indicative that your stream is suffering something.

And the usage of Angular (dynamically loading sources) with Clappr should be fine. 

* When the video got stuck, did you still hear the sound?

**Comment by cherihung** [comment]
thanks for the response. it is likely to the that stream's problem.
to answer your question, yes, audio works. thanks!
