### ISSUE TITLE
Can't play .m3u8 audio live stream from Akamai

### ISSUE THREAD

**Issue by neowinston** [clappr/clappr#543]
I'm trying to play a live audio stream served by Akamai, but it only works using Safari on the Mac. I have no audio with Firefox and Chrome.

Here is the code:

var player = new Clappr.Player({source: "http://bbnmedia-lh.akamaihd.net/i/BibleBroadcasting_Englishios@87472/master.m3u8", parentId: "#player"});

How do I fix this problem? Thank you!

**Comment by leandromoreira** [comment]
Hi @neowinston it's working fine for me at http://cdn.clappr.io/ 

Are you receiving any error?

```javascript
var player = new Clappr.Player({
  source: 'http://bbnmedia-lh.akamaihd.net/i/BibleBroadcasting_Englishios@87472/master.m3u8',
  poster: 'http://clappr.io/poster.png',
  height: 360,
  width: 640,
  parentId: "#player-wrapper"
});
```

**Comment by neowinston** [comment]
Hi Leandro, 

Thanks for your prompt reply!

Using http://cdn.clappr.io/ it works for me also, but if I try to put my .m3u8 url on the index.htm file, inside clappr-master/public directory it doesn't work. Any idea why?

**Comment by leandromoreira** [comment]
@neowinston are you seeing any error at your browser's console? By the way, you need to serve this `index.html` file from a server. (ex:)

```shell
sudo python -m SimpleHTTPServer
```

But looking at https://github.com/clappr/clappr/issues/542 @towerz also mentioned that you need to pass `baseUrl: "http://cdn.clappr.io/latest"`

```javascript
var player = new Clappr.Player({
  source: 'http://bbnmedia-lh.akamaihd.net/i/BibleBroadcasting_Englishios@87472/master.m3u8',
  poster: 'http://clappr.io/poster.png',
  height: 360,
  width: 640,
  baseUrl: "http://cdn.clappr.io/latest",
  parentId: "#player-wrapper",
});
```

**Comment by neowinston** [comment]
I'm trying to make it work using sudo python -m SimpleHTTPServer. I'll let you know the results. Thanks!

**Comment by leandromoreira** [comment]
@neowinston make sure to pass `baseUrl` pointing to `"http://cdn.clappr.io/latest"` (this is where the player will download the assets, fonts, swf...)

Given your behavior (working on safari... which works on [tag video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)) you've described I bet if you pass `baseUrl` it'll work.

**Comment by towerz** [comment]
@neowinston I understand you are getting errors when serving locally the HLS swf component used for other browsers to load the stream.

If you are loading using `sudo python -m SimpleHTTPServer` you can instead of setting `baseUrl` to load assets from the CDN, just create a symbolic link to the `dist/` folder called `latest` under the `public/` folder:
```shell
$ cd public
$ ln -sf ../dist latest
$ sudo python -m SimpleHTTPServer
```
This way clappr will automatically detect it's `baseUrl` from where it was loaded from.

**Comment by neowinston** [comment]
Hi towerz,

Thanks for your reply. I'll be trying your suggestions.

For us the ideal situation is to get hid of Flash 100%. Is that even possible, to serve our streaming audio to all browsers without any Flash involved?

Thanks!

**Comment by towerz** [comment]
@neowinston we don't think we can get rid of Flash 100% due to the lack of browser support for either streaming format (HLS/Dash). We used the table [here](https://developer.mozilla.org/en-US/Apps/Build/Audio_and_video_delivery/Live_streaming_web_audio_and_video) as reference.

We are planning to have support for both HLS and Dash using MSE, but both implementations are still under test. In the mean time, the only browser that supports HLS natively is Safari (Chrome support was unreliable, last time we checked), so I wouldn't discard Flash right away.

Since you are working with audio, why are you using HLS to stream? There should be other format you could use with native support from all browsers.

**Comment by neowinston** [comment]
Hi towerz,

Thanks for your reply! Reading the Mozilla article I have a better understanding of the streaming formats and their relation to different browsers.

We're using ACC streaming because it's provided by Akamai and the time we thought it would the best option instead of MP3, considering royalties costs. 

In the beginning we're using WMA over MMS protocol, but we had to use FFMPeg in our iOS App to decode it, which was a real pain to maintain. But with an .m3u8 streaming all we needed to make it work on the iPhone was 3 lines of code.

What would be a good option then? Considering our native Apps for iPhone, Android, Windows Phone and the regular web browsers? Do you think that the clappr code would still be a good option? Thanks for your time!

**Comment by towerz** [comment]
@neowinston about your concern of getting rid of Flash entirely, is it about your need to support iOS? If that's the case, you don't need to worry, we just need Flash to play HLS on desktop browsers that doesn't support playing it natively. Almost all mobile browsers support HLS natively.

If that's not the case, you would need to use a player supporting HLS through MSE, which Clappr does not support (for now). Alternatively you could change your streaming format to one that is supported by most desktop browsers. I believe [Icecast](http://icecast.org/) supports streaming AAC content directly and has good browser support.

You can test a sample stream I found at http://dir.xiph.org/by_format/AAC. Just paste this code on http://cdn.clappr.io:
```javascript
var player = new Clappr.Player({
  source: 'http://streaming14.tdiradio.com:8000/radiojat',
  poster: 'http://clappr.io/poster.png',
  mimeType: 'audio/aac',
  parentId: '#player-wrapper',
  height: 360,
  width: 640
});
```
About using Clappr in native apps, we're still developing native libraries for iOS and Android. The iOS version is almost ready, but the Android library is still frozen. If you are using webviews to render content, I think Clappr will work ok, but I'm not a great fan of using webviews for playing audio/video content. If your apps are mostly web-based, I think this would be ok.

**Comment by neowinston** [comment]
Thanks for the info, thanks for the code. We'll be looking into Icecast to know more about it. When we reach a conclusion we'll let you know. Once more, we thank you for shared knowledge!

**Comment by towerz** [comment]
Anytime! I'll close the issue for now, but feel free to ask again if you're still having problems.
