### ISSUE TITLE
more precise seeking method?

### ISSUE THREAD

**Issue by cherihung** [clappr/clappr#545]
I've looked through the API doc but couldn't find a more precise method for moving the playhead other than the seek() method.
http://clappr.github.io/files/src_base_playback.js.html#l39

But that one is only based on percentage instead of an exact position by second (something like jwplayer's seek()).

Is there one available?

UPDATE: I can achieve the same result by doing some calculation in my script. e.g. (desiredTime / totalDuration) * 100. But maybe useful to be able to seek by passing in time as seconds directly.

**Comment by cherihung** [comment]
nevermind. I figure I can calculate the position

**Comment by towerz** [comment]
Agree to that. We don't usually seek directly using seconds, so I think this is the reason why this function is missing. 

The seek method using percentage values is more useful to implement a custom `MediaControl`, but for an external API it's useful to have both implementations.

**Comment by flavioribeiro** [comment]
@dayvson is working on that, you can follow the progress/discussion on #654
