### ISSUE TITLE
Disableling Player's Font Icon Buttons

### ISSUE THREAD

**Issue by dviramontes** [clappr/clappr#549]
![screen shot 2015-09-02 at 2 03 55 pm](https://cloud.githubusercontent.com/assets/144226/9768048/8131967c-56de-11e5-972d-b20699f1c38c.png)

is there a way to disable font icons buttons from displaying ?

In our Clapper.player config:
```
window.player = new Clappr.Player({
  chromeless: true
});
```
having `chromeless:true` does disable the player's default buttons 
but font icon buttons (`3e43a5d764f841e7e78896de82cd6c50.ttf`) still try to load. 

Ideally we would like to disable them. Interestingly this button
only shows up at the end of a stream.

Using clappr v0.2.8

Thanks

cc @lkkadiri @jfairley

**Comment by towerz** [comment]
@dviramontes Using `chromeless: true` should disable displaying these icons. It seems to be a bug in the `Poster` plugin.

**Comment by dviramontes** [comment]
I see, should i file an issue on that repo?
I don't see a `Poster` in your package.json dependencies.

**Comment by towerz** [comment]
@dviramontes the `Poster` plugin is one of Clappr built-in plugins. There's no need to file another issue, I was just stating that this issue is indeed a bug in the player.

**Comment by dviramontes** [comment]
@towerz thanks so much!
