### ISSUE TITLE
How to build HLSPlayer.swf

### ISSUE THREAD

**Issue by jfairley** [clappr/clappr#551]
I want to add functionality to the HLS flash fallback, but I cannot find how to build [`HLSPlayer.swf`](../blob/e8e2991a91b8d1f59f9a51d9b2f34b6086a3f544/src/playbacks/hls/public/HLSPlayer.swf).

I see [`Player.as`](../blob/e8e2991a91b8d1f59f9a51d9b2f34b6086a3f544/src/playbacks/flash/Player.as) and [`build_player.sh`](../blob/e8e2991a91b8d1f59f9a51d9b2f34b6086a3f544/src/playbacks/flash/build_player.sh) in the source code which creates [`Player.swf`](../blob/e8e2991a91b8d1f59f9a51d9b2f34b6086a3f544/src/playbacks/flash/public/Player.swf), but this seems to be used only for a "flash" playback type from [`flash.js`](../blob/e8e2991a91b8d1f59f9a51d9b2f34b6086a3f544/src/playbacks/flash/flash.js).

How can I build my own version of the HLS flash player??

**Comment by flavioribeiro** [comment]
hey @jfairley, `HLSPlayer.swf` is a build of [flashls](github.com/mangui/flashls). I'm not sure if it's a plain build from flashls' master branch or the guys are maintaining a fork. Let's wait for @towerz or @leandromoreira  to answer this one :)

**Comment by jfairley** [comment]
Oh, interesting. Thanks @flavioribeiro. I'm interested to learn the proper workflow for getting in new features.

Also, how is `Player.swf` used? Is that for RTMP?

**Comment by flavioribeiro** [comment]
we did this in order to support `mp4` playback on old firefox and other browsers that don't have native support for it. It also enables the player to play 3gp and mov, even though we're not displaying as supported formats on README.

**Comment by jfairley** [comment]
:+1: thanks

**Comment by towerz** [comment]
@jfairley Like @flavioribeiro mentioned, we're maintaining a fork of [flashls](https://github.com/mangui/flashls). It's only used to expose extra settings over the `ChromelessPlayer`, which is the base implementation for the HLS playback. You can check the differences checking the `clappr` branch in our [fork](https://github.com/clappr/flashls). It's implemented in the `io.clappr.Player` class.

**Comment by jfairley** [comment]
@towerz I was just having a look at [mangui/flashls](https://github.com/mangui/flashls) to make the necessary changes. Would you prefer that I submit a PR into [clappr/flashls](https://github.com/clappr/flashls) instead?

**Comment by towerz** [comment]
Are these changes specific to Clappr? If so, it would be better to submit a PR into the clappr fork, otherwise I'd submit a PR to [mangui/flashls](http://github.com/mangui/flashls).

**Comment by jfairley** [comment]
No. I want to expose the step function on the NetStream object. Highly generic.

**Comment by jfairley** [comment]
FYI, I am testing the waters to make sure there is no one vehemently opposed before I do the work.
https://github.com/mangui/flashls/issues/382

**Comment by towerz** [comment]
That's nice. :+1: 

If you need any assistance with building your own version of HLSPlayer.swf while your changes are not added to flashls, just let me know.

**Comment by dviramontes** [comment]
Hey @towerz 
what version of flex do I need to build https://github.com/clappr/flashls ?

**Comment by dviramontes** [comment]
Nevermind @towerz 
@jfairley and I figured it out. There is a ***clappr*** branch has the right build script
for building HLSPlayer.swf

**Comment by towerz** [comment]
@dviramontes you figured it out just before I answered. If you need help with anything else, please let me know.

**Comment by dviramontes** [comment]
Hey @towerz 
so what started this crusade of building the **HLSPlayer.swf** player was an need to add a custom function to grab a screenshot of the video player (since we use Clappr.HLS playback, we can't use the conventional <video/> element to canvas way). 

What i'm having trouble with is capturing that image from within `org/mangui/chromeless/ChromelessPlayer.as`. I need to be able to call 

```
var screenshotData:BitmapData = new BitmapData(stage.stageWidth, stage.stageHeight);
screenshotData.draw(stage); <----
```
but this image is always empty. Would you happen to know which of the following would be
the Object to call `.draw()` on ?
- this
- _hls.stage
- _stageVideo
- something else I havent seen ? :/

let me know if the question makes sense. 
Thanks in advance..

**Comment by towerz** [comment]
Hi @dviramontes, I'm not sure why the stage is empty, but I would attempt to call `.draw()` on _hls.stage. If this doesn't work, I'd try to create an issue on [mangui/flashls](https://github.com/mangui/flashls) and ask directly to @mangui.

**Comment by mangui** [comment]
you can refer to https://github.com/mangui/flashls/issues/273

**Comment by towerz** [comment]
Thanks @mangui.

**Comment by dviramontes** [comment]
thanks @towerz!

**Comment by enbplas11** [comment]
@jfairley @dviramontes @flavioribeiro 
Good, how building custom HLSPlayer for clappr from mangui/flashls.?
