### ISSUE TITLE
Acessing HLS tags

### ISSUE THREAD

**Issue by AlekzFateJumper** [clappr/clappr#552]
I need to read the HLS tag #EXT-X-PROGRAM-DATE-TIME, for the first, last and current video segment. I'm cracking my head for 3 days and still haven't found out how to do it.

**Comment by leandromoreira** [comment]
@AlekzFateJumper we use [mangui/flashls](https://github.com/mangui/flashls/) to provide hls, we just pass a given source (`'http://example.com/myvideo/playlist.m3u8'`) but we don't manage hls internal state, a.k.a. you will not have access to the playlist within clappr.

The major interaction we do is to setup flashls by [passing arguments to build it](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L40).

**Comment by flavioribeiro** [comment]
just curious, can u tell me why u need this info?

**Comment by AlekzFateJumper** [comment]
I'm developing a custom timeline for security camera. I've already made a
hack to contour this problem, filtering the m3u8 via PHP and returning the
key points via AJAX.

2015-09-17 15:18 GMT+00:00 Flávio Ribeiro <notifications@github.com>:

**Comment by towerz** [comment]
@AlekzFateJumper have you tried checking the list of fragments on the current level? There should be a `program_date` attribute in it. Something like: `player.core.getCurrentPlayback().getCurrentLevel().fragments[0].program_date`

**Comment by AlekzFateJumper** [comment]
This worked fine on Firefox, but crashed in Chrome, the getCurrentLevel() does not exist in Chrome.

**Comment by flavioribeiro** [comment]
Force the use of FlasHLS on Chrome by adding `plugins: {playback: [Clappr.FlasHLS]}` on the embed params and you'll have the same methods for both chrome and firefox
