### ISSUE TITLE
hideVolumeBar is broken

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#553]
If i want to force the hideVolumeBar parameter to true, it has no effect and the volume control is still visible. I've tested it on chrome and firefox.

**Comment by leandromoreira** [comment]
thanks @irongomme I rewrite the title, if you don't mind. Because it seems that this not a problem only for hls.

- hideVolumeBar true has no effect on live hls
+ hideVolumeBar is broken

**Comment by towerz** [comment]
Just pushed a fix for the parameter handling. Let's keep in mind that this option doesn't remove the volume control from the interface, only hides/collapses the volume bar keeping only the volume/mute icon.
