### ISSUE TITLE
Strange controls visibility with firefox

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#556]
I've recently notice that on firefox, i can't see : 

- The play link (div.play-wrapper > div.poster-icon.play)
- The volume icon on the bottom right
- The fullscreen icon on the bottom right

A sample can be found here : http://www.iwilive.net/streams/view/pleneuf0

**Comment by flavioribeiro** [comment]
did u check if there's a css conflict that only express in firefox?

**Comment by irongomme** [comment]
You must be right because it doesn't happens on cdn.clappr.io and neither on my other websites.

**Comment by irongomme** [comment]
Ok i've found it : i made a wrong use of player.resize, so it didn't work fine on firefox
