### ISSUE TITLE
Document how to run the dev server

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#557]
I saw that we've dropped `gulp` in favor of on `npm` but couldn't see documentation about `start` and `watch` tasks. It would be great to add it on `Readme.md`.

**Comment by dayvson** [comment]
Hey @flavioribeiro 
I sent a pull request to add that 
https://github.com/clappr/clappr/pull/570

**Comment by flavioribeiro** [comment]
thx @dayvson!! :beers:
