### ISSUE TITLE
Spinner is not visible all the time on android

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#562]
I've notice this behavior on hls source and mp4 source with android : 
- When i click play, the spinner appear
- When video is downlading, just before the beginning of the reading of the movie, i've got a black screen, and we can think, as an end user, that the player is not working

**Comment by leandromoreira** [comment]
still a problem?

**Comment by joaopaulovieira** [comment]
I did some tests and could not reproduce the behavior.

I Tested on:
**Android**: `7.1.1`
**Media**: http://clappr.io/highline.mp4 and http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8
**Environment**: `local` and http://clappr.io/demo/

Could you say the Android version and the medias that you used to reproduce this problem, @irongomme ?
