### ISSUE TITLE
Black screen, I need a help.

### ISSUE THREAD

**Issue by floriano12** [clappr/clappr#565]
My player is black screen. My adobe flash player is activated on browser.

I try my stream live on: IE, Mozilla, Crome, don't work.
```
<head>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/0.0.6/rtmp.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="probe/clappr/dist/rtmp.js"></script>
    <title>RTMP Test Page</title>
</head>
<body>
<div id="player"></div>
  <script>
    window.onload = function() {
      var player = new Clappr.Player({
        source: 'rtmp://tviza.com:1935/live', 
        parentId: "#player",
        autoPlay: true,
        plugins: {'playback': [RTMP]},
        gaTrackerName: 'MyPlayerInstance',
	mediacontrol: {seekbar: "#E113D3", buttons: "#66B2FF"}
      });
    }
  </script>
</body>
```
What I'm wrong?

Thanks in advance for any help!

**Comment by towerz** [comment]
@floriano12 the RTMP plugin hasn't been updated to work with clappr 0.2.x properly. Perhaps that's why you are getting a black screen. The playback fails to load, breaking the player.

**Comment by floriano12** [comment]
Thanks @towerz
what to do, how I can solve ?

**Comment by flavioribeiro** [comment]
I know that it's not the best solution but you can use an old version of clappr:

```html
<head>
    <script type="text/javascript" charset="utf-8" src="http://cdn.clappr.io/0.1.0/clappr.min.js"></script>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/0.0.6/rtmp.min.js"></script>
    <title>RTMP Test Page</title>
</head>
<body>
<div id="player"></div>
  <script>
    window.onload = function() {
      var player = new Clappr.Player({
        source: 'rtmp://tviza.com:1935/live', 
        parentId: "#player",
        autoPlay: true,
        plugins: {'playback': [RTMP]},
        gaTrackerName: 'MyPlayerInstance',
    mediacontrol: {seekbar: "#E113D3", buttons: "#66B2FF"}
      });
    }
  </script>
</body>
```

btw, this problem was already reported on https://github.com/clappr/clappr-rtmp-plugin/issues/26, https://github.com/clappr/clappr-rtmp-plugin/issues/25 and https://github.com/clappr/clappr-rtmp-plugin/issues/24

**Comment by flavioribeiro** [comment]
I'm gonna try to work on that this week. @floriano12 please report RTMP issues directly on the plugin repo: https://github.com/clappr/clappr-rtmp-plugin

**Comment by floriano12** [comment]
thanks @flavioribeiro 

not open player, why ? dont work!

**Comment by flavioribeiro** [comment]
you're able to play your stream on vlc?

**Comment by floriano12** [comment]
I use FMLE. 
I don't think.

**Comment by flavioribeiro** [comment]
I think that you're missing the stream name in your source url. Check your FMLE config.

**Comment by floriano12** [comment]
is good FMLE config, with the old player works FMLE

you can try on vlc ?

**Comment by floriano12** [comment]
@flavioribeiro this player work on mobile devices ? I try now but I receive a message: your browser does not support the playback of this video. Try to use a different browser.

**Comment by floriano12** [comment]
I stoped the stream live, but player run.

**Comment by vbHeiko** [comment]
This RTMP Player worked for me (tested on 30.August 2016):
`<html>
<head>
  <script type="text/javascript" charset="utf-8" src="http://cdn.clappr.io/0.1.0/clappr.min.js"></script>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/0.0.6/rtmp.min.js"></script>
</head>
<body>
 <div id="player"></div>
<script>
      var player = new Clappr.Player({
        source: 'rtmp://xyz.com/live/Stream-123523670', 
        parentId: "#player",
        autoPlay: true,
        plugins: {'playback': [RTMP]},
        gaTrackerName: 'MyPlayerInstance',
    mediacontrol: {seekbar: "#E113D3", buttons: "#66B2FF"}
      });
</script>
</body>
</html>`
