### ISSUE TITLE
Can't retrieve player bitrate

### ISSUE THREAD

**Issue by wholegrn** [clappr/clappr#569]
Hi,

I'm using clappr to read some HLS streams. I need to get player bitrate. To do so, i'm using this piece of code : 

```javascript
player.listenTo(player.core.getCurrentContainer(), Clappr.Events.CONTAINER_BITRATE, function(bitrate) 
		{ console.log(' container bitrate changed... '+ bitrate); 
	});
```
But the callback method is never called.

However i do receive events such as Events.CONTAINER_SEEK.

Thanks.

**Comment by towerz** [comment]
@wholegrn are you using Safari for your tests?

I tested your snippet on http://cdn.clappr.io and received the events correctly using this code on both Chrome and Firefox:
```javascript
var playerElement = document.getElementById("player-wrapper");
var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/test_001/stream.m3u8',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});
player.attachTo(playerElement);
player.listenTo(player.core.getCurrentContainer(), Clappr.Events.CONTAINER_BITRATE, function(bitrate) { console.log(' container bitrate changed... ', bitrate); });
```
If you are using Safari, we use it's native HLS implementation, which doesn't expose bitrate change events.

**Comment by wholegrn** [comment]
@towerz Indeed, i used Safari for my tests.
I tested my code on Chrome and it worked !

Thank you.
