### ISSUE TITLE
Clappr does not work with Yandex browser on Windows 7

### ISSUE THREAD

**Issue by Kreeig** [clappr/clappr#574]
clappr player not work on yandex browser ,   only work on OS - Windows 10 , can anyone fix so it can play on Windows 7 too ?

**Comment by leandromoreira** [comment]
@Kreeig did you notice any console error? what kind vide were you playing? do you have any url to test?

**Comment by Kreeig** [comment]
yes , for example - http://sportlive.ws/s/euro2 , you see there no error , just not play

**Comment by leandromoreira** [comment]
hey @Kreeig I rewrite the title (for SEO) and I'll let this issue open so anyone can pick an try to fix it. Thanks.

**Comment by FDiskas** [comment]
I have that browser and it works on Fedora 23 + Yandex Browser. The video is flash version

**Comment by flavioribeiro** [comment]
I've tested here with MacOS Yosemite, it's working fine. @Kreeig can you still reproduce this?
