### ISSUE TITLE
Postback in asp.net webform

### ISSUE THREAD

**Issue by madmarten** [clappr/clappr#577]
Hi, when I put clappr in a asp.net webform it works starting playing the video, but as soon as I try to click the fullscreen button it generates a postback and the player is unloaded, but I can doubleclick in the player and get fullscreen without postback event. I can click play/pause without problem and also change volume. Also clicking 'HD' button or changing quality with the quality selector plugin generates this postback event and unloads the player totally so it's not visible anymore and it's not playing in the background. If I use the exact same code to for using clappr in an MVC project it works fine.

Do you have any idea what could cause this?

**Comment by flavioribeiro** [comment]
Can you send us an URL where we can reproduce this problem?

**Comment by madmarten** [comment]
Sorry for late respons. We will be moving away from webforms soon hopefully so I won't bother with this anymore. I'm not sure it's Clapprs fault anyway, but I have tried several other players and they don't behave like this. The page in question is hard to make public and availalable 24/7 since it's a live stream. I will close this for now.
