### ISSUE TITLE
HLS.js release?

### ISSUE THREAD

**Issue by jfairley** [clappr/clappr#587]
Curious when we'll see an NPM distribution containing HLS.js.

It works well for me when installed locally, but our release is blocked by this one.

Thanks!

**Comment by flavioribeiro** [comment]
+1

**Comment by dviramontes** [comment]
any updates on the release ?

**Comment by flavioribeiro** [comment]
yep, @leandromoreira just did it, wait a bit until we have it on cdn

**Comment by jfairley** [comment]
:confetti_ball:

**Comment by dviramontes** [comment]
im guessing the npm publish is to follow as well ?

**Comment by leandromoreira** [comment]
@jfairley @dviramontes we had a little problem while releasing the newer version of clappr, so this is wrong ;( . We'll fix it soon, I'm sorry. :hankey:

**Comment by dviramontes** [comment]
@leandromoreira 
O.K. thanks for the update!

**Comment by leandromoreira** [comment]
@jfairley @dviramontes @flavioribeiro we're live! (once again, I'm sorry)

**Comment by dviramontes** [comment]
yay! thanks so much!

**Comment by jfairley** [comment]
![62gjbzx](https://cloud.githubusercontent.com/assets/992483/10642520/54bbbf96-77db-11e5-9a96-24c90a1ccf61.png)
