### ISSUE TITLE
Does not support IE11 [defineProperty: Unsupported property or method ]

### ISSUE THREAD

**Issue by nxtreaming** [clappr/clappr#588]
Object.defineProperty(exports, '__esModule', {
	    value: true
	});

I use the latest clappr which is located in "http://cdn.clappr.io/latest/clappr.min.js"

![clappr_debug](https://cloud.githubusercontent.com/assets/3108107/10556287/d72643f2-74b1-11e5-92c0-d3de9372a8c7.png)
"

**Comment by leandromoreira** [comment]
@nxtreaming is still happening?
