### ISSUE TITLE
Clappr falls back to flash with HLS .m3u8 even though Clappr.HLS explicitly defined

### ISSUE THREAD

**Issue by lightest** [clappr/clappr#599]
Hi everyone,

HTML:
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<script type="text/javascript" src="clappr/clappr.js"></script>
	<script type="text/javascript" src="logic.js"></script>
</head>
<body>
	<div class="clappr-container"></div>
</body>
</html>
```

JavaScript (logic.js):
```javascript
window.onload = function () {
    var player = new Clappr.Player({
        source: 'http://www.streambox.fr/playlists/test_001/stream.m3u8',
        parentId: '.clappr-container',
        plugins: { playback: [Clappr.HLS] }
    });
};
```

So when I load my page there is flash object instead of `<video>`. I thought dailymotion's hls.js was adopted exactly to move away from flash. May be I misunderstood something?

Browsers tested:
Chrome 46
FireFox 41

**Comment by flavioribeiro** [comment]
hey @lightest I think the guys didn't release a version with hlsjs integration yet so that means you can build by yourself and it's gonna work. We are avoiding hlsjs playback on firefox until we have MSE enabled by default as you can see here:
https://github.com/dailymotion/hls.js/blob/master/README.md#compatibility
https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L105

**Comment by flavioribeiro** [comment]
refs #587

**Comment by flavioribeiro** [comment]
@lightest can u test again and reopen if its still an issue? we're now live with hlsjs in prod

**Comment by lightest** [comment]
@flavioribeiro It works I confirm. Sorry for lack of feedback got a bit bussy. One more question. To switch between flash and hlsjs I need to use Clappr.FlashHLS/Clappr.HLS correct? The thing is that some particular playlists doesn't work with hlsjs but used to work with flash.

**Comment by flavioribeiro** [comment]
yep! Adding the playback you want to play on the `plugins` array will add it in the first priority for playing your source.
