### ISSUE TITLE
Cannot find module "./public/style.scss"

### ISSUE THREAD

**Issue by dethos** [clappr/clappr#600]
Hello, yesterday I tried and successfully used the player, based on the example in the readme. 
Yet tonight I tried it again and chrome is giving me the following error:

> Uncaught Error: Cannot find module "./public/style.scss"   clappr.min.js:3

I'm including the file like this:

` <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>`

Looks like you launched a new release today, so perhaps this is a new thing.

**Comment by flavioribeiro** [comment]
yep, could reproduce on http://cdn.clappr.io/ so I think we have a critical issue here..

ping @towerz @leandromoreira @thiagopnts

**Comment by leandromoreira** [comment]
@dethos are you still facing this issue? I tried http://cdn.clappr.io/ and everything seems fine.

**Comment by dethos** [comment]
@leandromoreira No, today I tried again, the error no longer shows up and the player is working just fine.

**Comment by leandromoreira** [comment]
thanks @dethos
