### ISSUE TITLE
RFC: Add support to manage audio/video/text tracks at Playback interface

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#626]
While I'm creating the dash playback I'm seeing a lot of opportunities to clappr. :) Dash/HLS offers multiple audio/video/text tracks.

I think it might be useful to add these capabilities to our `Playback`.

I also think that @towerz is working to open source our solution to Adobe DRM (which also handles multiples audios...)

**This is very inspired by [shaka](https://shaka-player-demo.appspot.com/docs/shaka.player.Player.html).**
## Propose

We can treat a `track` as a simple abstraction regardless of this type (audio, video or text)

``` javascript
text = {
  id: 0, //*mandatory: an unique identifier
  active: false, //*mandatory: weather this track is active or not,
  lang: 'pt-BR' //optional: the track's language
}

audio = {
  id: "A",
  active: true,
  lang: 'en-US'
}

video = {
  id: "3D",
  active: false,
  lang: null
}
```

The idea is to support the following operations:
-  `enableTextTrack(enable=true)`  //this is needed, we can mute and we need to be watching at least one video track :P
-  `audioTracks()`
-  `selectAudioTrack(id)`
-  `textTracks()`
-  `selectTextTrack(id)`
-  `videoTracks()`
-  `selectVideoTrack(id)`
### Solution A

**Just append more methods to Playback.**

**Good**: simple adhoc, **Bad**: not all playbacks needs to know manage audio/video/text tracks
### Solution B

**Create a new class like `AVTTrackHandler` and compose Playback (aka `get avtTrackerHandler`).**

**Good**: not so coupled, **Bad**: force us to always to know and use the compositon `playback.avtTrackerHandler.selectVideoTrack`
### Solution C

**Create a new sub-class like `PlaybackWithTrackHandler` and extend from it.**

**Good**: not so coupled, **Bad**: yet another layer of heritance :-1: 
### Solution D

????
## Question
- Do we need more fields to represent a track? (maybe `type: 'audio'` but I don't think of any use cases for it)
- What do you think?
- What solution do you like most?

**Comment by kevin2o** [comment]
Was this implemented? I love the player, but I have playlists with multiple audio tracks and I can't find an option to change the track.

**Comment by leandromoreira** [comment]
@kevin2o it was not ;/ but I still think it's a solid feature

**Comment by kevin2o** [comment]
@leandromoreira Thanks for the update. Yeah, too bad. Clappr is by far the smoothest player I've used, but my problem is that the playlists I use have multiple audio tracks and English is not default.

**Comment by PreDeToR** [comment]
Hi @leandromoreira 

Has switching audio tracks been implemented yet, or is there a way to do it?

**Comment by leandromoreira** [comment]
@PreDeToR the way you switch audio tracks depends on the playback =/ for instance, if you are using HLS you should be using the [playback directly](https://github.com/dailymotion/hls.js/blob/master/API.md#audio-tracks-control-api). 

```javascript
var hls = clappr.core.getCurrentContainer().getCurrentPlayback()._hls
var all = hls.audioTracks;
hls.audioTrack = all[0];
```

This issue aims to solve that by providing an API for these common operations, therefore we can build upon this, like we did with [bitrate levels](https://github.com/clappr/clappr-level-selector-plugin).

**Comment by PreDeToR** [comment]
Hi @leandromoreira 

I setup a m3u8 that through VLC I can switch to the different audio tracks, yet I am not seeing anything in "hls.audioTracks" any suggestions where else to look?

**Comment by leandromoreira** [comment]
@PreDeToR I just checked at cdn and I could reproduce with this code `player.core.getCurrentPlayback()._hls` the **player** being the instance name you gave, also please notice that `_hls` will be only available after you click `PLAY`:

```javascript
player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  onPlay: function() { console.log(player.core.getCurrentPlayback()._hls. audioTracks) }
});
```

**Comment by PreDeToR** [comment]
@leandromoreira I just tried the above code on cdn and I do not get the play event triggered.

![buttons_to_click7](https://cloud.githubusercontent.com/assets/17157144/18632782/6f16c1ce-7e79-11e6-80bf-20428eb8e566.png)
![buttons_to_click8](https://cloud.githubusercontent.com/assets/17157144/18632786/7bc6db5c-7e79-11e6-875f-fffda5caa2c0.png)



I also tried the normal play event and got the following:
![buttons_to_click9](https://cloud.githubusercontent.com/assets/17157144/18632875/f9030e74-7e79-11e6-8107-2435d26865ef.png)

**Comment by leandromoreira** [comment]
@PreDeToR my bad, I wrote that code out of my head, this one worked (although this stream doesn't offer multiple audios).

```javascript
var playerElement = document.getElementById("player-wrapper");

player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  events: {
    onPlay: function() {
      console.log(player.core.getCurrentPlayback()._hls.audioTracks);
    }
  }
});

player.attachTo(playerElement);

```

**Comment by PreDeToR** [comment]
@leandromoreira  Thanks for the update, that now shows an "undefined" for me in the log,
Should it not alteast return 1 audioTrack on the above video?

**Comment by leandromoreira** [comment]
> Should it not at least return 1 audioTrack on the above video?

It seems that the hls.js team chose don't add a single track.

**Comment by PreDeToR** [comment]
hmm, I tried two different m3u8 files, and neither of them return it :(

http://danievtest3.dedicated.co.za/converted/Main.m3u8          -Embedded Audio Into the video file
http://danievtest3.dedicated.co.za/converted/ExtraMain.m3u8  -Explicitly defined audio files.

**Comment by leandromoreira** [comment]
@PreDeToR try to test these files at http://dailymotion.github.io/hls.js/demo/ maybe it is an issue at hls.js

**Comment by PreDeToR** [comment]
@leandromoreira http://danievtest3.dedicated.co.za/converted/ExtraMain.m3u8 works fine on the demo page.

Still cant see it on clappr  :(

**Comment by leandromoreira** [comment]
[I saw](https://github.com/dailymotion/hls.js/blob/master/demo/index.html), maybe this is something only available at new version 6.x

```javascript
var playerElement = document.getElementById("player-wrapper");

player = new Clappr.Player({
  source: 'http://danievtest3.dedicated.co.za/converted/ExtraMain.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  events: {
    onPlay: function() {
      var hls = player.core.getCurrentPlayback()._hls;
       hls.on("hlsAudioTracksUpdated",function(event,data) {
          console.log("audioTracks", data.audioTracks);
       });
    }
  }
});

player.attachTo(playerElement);
```

**Comment by PreDeToR** [comment]
@leandromoreira any plans on updating to version 6.x ?

**Comment by leandromoreira** [comment]
yes, https://github.com/clappr/clappr/issues/1143 as well we need to define an API to handle multiple audio/video tracks across different playbacks (dash, hls, ...).

**Comment by PreDeToR** [comment]
@leandromoreira thanks for all your help, I really appreciate it.

**Comment by PreDeToR** [comment]
@leandromoreira 
This has taken a long time, i know :(
Here is a link to a audio track selector, its very basic,and I used the level selector as a base for the plugin.

You guys are more than welcome to look at it, and add it to the external plugins list:
https://github.com/PreDeToR/clappr-audio-track-selector-plugin
