### ISSUE TITLE
Use hlsjs on Firefox 42+

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#633]
Firefox 42 was just released with Media Source Extension enabled for all sites, which means we can use hlsjs on it. According to https://github.com/dailymotion/hls.js/issues/37#issuecomment-153406269 we are good to go and match UA's for firefox 42 and above on https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L121-L127.

**Comment by flavioribeiro** [comment]
here's the full release notes: https://www.mozilla.org/en-US/firefox/42.0/releasenotes/

**Comment by dayvson** [comment]
hey @flavioribeiro, I am working on that ;)

**Comment by cpeterso** [comment]
I'm a program manager on Mozilla's media team. If you have questions about Firefox's MSE implementation, feel free to CC me or drop by the #media channel on Mozilla's IRC server. :)

**Comment by leandromoreira** [comment]
Thank you very much @cpeterso

**Comment by flavioribeiro** [comment]
@cpeterso is it true that MSE is not available for FF 42 on linux? (https://github.com/dailymotion/hls.js/issues/37#issuecomment-156167815)

**Comment by dviramontes** [comment]
:+1:

**Comment by cpeterso** [comment]
@flavioribeiro: that's correct. MSE won't be enabled by default on Linux until FF 43 (December 15).

**Comment by alexandrevicenzi** [comment]
:+1:

**Comment by kafeltz** [comment]
:+1:

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/pull/686/files
