### ISSUE TITLE
HLSJS doesn't support AES-128 decryption

### ISSUE THREAD

**Issue by itsjamie** [clappr/clappr#634]
There should be a call out on your HLS support that any browser that uses HLSJS with HLS encryption (AES-128) will fail, and repeat the request for the .ts chunk over and over and over, if this was missed could have been a costly deployment for flash disabled devices.

**Comment by leandromoreira** [comment]
*any browser that uses HLSJS with AES-128

**Comment by leandromoreira** [comment]
@itsjamie I'm gonna close since it's now [supported](https://github.com/dailymotion/hls.js#features)
