### ISSUE TITLE
Youtube/Vimeo/Embed Players Support

### ISSUE THREAD

**Issue by rafaell-lycan** [clappr/clappr#636]
It's possible to use with Youtube or Vimeo instead the embed solution?

**Comment by flavioribeiro** [comment]
There's a plugin to support youtube id's (https://github.com/towerz/clappr-youtube-playback) but I'm not sure if we have something for Vimeo.

**Comment by rafaell-lycan** [comment]
Why this isn't on the official documentation? =/

**Comment by rafaell-lycan** [comment]
Anyway thanks @flavioribeiro

**Comment by flavioribeiro** [comment]
@rafaell-lycan clappr has a bunch of external plugins which we're not willing to have inside of the player bundle. Our idea is to keep clappr core as simple/tiny as possible.

**Comment by flavioribeiro** [comment]
@rafaell-lycan thanks for the heads up on adding youtube plugin on readme. tell me if you want some help to implement the vimeo plugin!
