### ISSUE TITLE
Is there a way to disable the keyboard bindings on the player itself ?

### ISSUE THREAD

**Issue by dviramontes** [clappr/clappr#640]
I'm looking specifically at these two:

[this.kibo.down(['left'], () => this.seekRelative(-15)) and 
this.kibo.down(['right'], () => this.seekRelative(15))](https://github.com/clappr/clappr/blob/674dbdd7f5ec4ddaff129f9c0efe3cd72759c8ba/src/components/media_control/media_control.js#L496)

I tried calling  `window.player.core.mediaControl.unbindKeyEvents()`
and got: `Uncaught TypeError: Cannot read property 'off' of undefined(…)`
It doesn't look like its a function I would be able to call externally. Not exposed.
Is there a different way?

Thanks!

**Comment by dayvson** [comment]
I just sent a pull request that will fix it.

**Comment by flavioribeiro** [comment]
#641 fixes that. thanks @dayvson

**Comment by dviramontes** [comment]
That was way fast!
Thanks so much @dayvson !

**Comment by dviramontes** [comment]
just noticed that calling:
`window.player.core.mediaControl.unbindKeyEvents();`
breaks the player. Is there another way to disable this shortcut key functionality ?
