### ISSUE TITLE
Error on player ready state.

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#651]
http://jsfiddle.net/frzkqja8/

**Comment by FDiskas** [comment]
If video is ended the folowing events are triggered:
```
PLAYER_PAUSE
PLAYER_ENDED
PLAYER_TIMEUPDATE
```
Strange order. The video ends and how its could be paused? Ok - video ended but how it can still update time?

**Comment by leandromoreira** [comment]
Just for reference  https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L141

**Comment by FDiskas** [comment]
Please take a look at first link to.

**Comment by leandromoreira** [comment]
Hey @FDiskas I just try to run it on cdn.clappr.io and it was working okay, can we close this?

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});
player.on(Clappr.PLAYER_ERROR, (e) => console.log(e))
player.attachTo(playerElement);

```

**Comment by FDiskas** [comment]
No we can't close this. 
```js
$(function () {
    var player = new Clappr.Player({
        source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
        parentId: "#player-wrapper",
        //autoPlay: true
    });
    player.on(Clappr.Events.PLAYER_ERROR, function(a) { alert('PLAYER_ERROR!', a.error.code) });
});
```
Try this code. Same error. And there is nothing special with this code, but error event is frown.

**Comment by leandromoreira** [comment]
@FDiskas cool, I think I know what it is this.
https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L48
```javacript
this.el.src = options.src
```
