### ISSUE TITLE
Missing events, methods

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#653]
Hello, thanks for good player. Still missing some events

* fullscreen - then user enters or exits from fullscreen
* ready - then player is ready for play some video
* load - then first segment is loaded or first timeUpdate event is triggered
* volume - then user changes the volume

Missing methods
* getVolume - get current value of volume. Get it from localStorage not good.
* requestFullscreen / cancelFullscreen - to toggle fullsscreen from outside the player

**Comment by flavioribeiro** [comment]
hey @FDiskas do you mind breaking this issue in smaller ones? One for each missing event and method? This way we could close it with commits and receive contribs

**Comment by FDiskas** [comment]
Shure.

**Comment by flavioribeiro** [comment]
thanks @FDiskas !!

**Comment by flavioribeiro** [comment]
Closing this since the feature requests are already placed in other issues
