### ISSUE TITLE
Samsung galaxy note 10.1 video size problem

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#655]
Watch in full screen, then go back to normal and result is - video width is shrinked
Samsung galaxy note 10 http://www.gsmarena.com/samsung_galaxy_note_10_1_n8000-4573.php
GT-N8000
Android 4.1.2
![screenshot_2015-11-12-00-26-59](https://cloud.githubusercontent.com/assets/468006/11104954/a16747a2-88d4-11e5-8de2-db21b6f58715.png)

**Comment by flavioribeiro** [comment]
@FDiskas can you test with different sources (like a hls, for example)

**Comment by FDiskas** [comment]
Not easy to do this with tablet - need working and hosted url with example.

**Comment by FDiskas** [comment]
![screenshot_2015-11-12-01-04-55](https://cloud.githubusercontent.com/assets/468006/11105717/74ad9c02-88d9-11e5-8d5c-37f430936363.png)

**Comment by FDiskas** [comment]
In playlist header
```
#EXT-X-PLAYLIST-TYPE:VOD
```
And there exists the
```
#EXT-X-ENDLIST
```
Witch means that there is not a LIVE stream.

**Comment by FDiskas** [comment]
:arrows_counterclockwise: so this problem is solved?

**Comment by leandromoreira** [comment]
@FDiskas can you check it again? we release a tons of fixes, several related to size and css.

**Comment by FDiskas** [comment]
:eggplant: The video is displaying that there is a Live video not a record. Then I try to unhide the status bar - it pauses the video. Then I press the fullscreen it displays the native video player not a clappr. Then I go back from the fullscreen there is no clappr video at all. Only the white screen of jsbin website.

**Comment by leandromoreira** [comment]
Thanks @FDiskas

**Comment by FDiskas** [comment]
Samsung galaxy s5 - imposible cant enter the fullscreen. By double tap - got blank page
![bs_realdroid_mobile_samsung galaxy s5-4 4-1080x1920](https://cloud.githubusercontent.com/assets/468006/15313446/03d68632-1c14-11e6-8e87-daa83297b47a.jpg)
