### ISSUE TITLE
Missing "fullscreen" event

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#656]
We need a fullscreen event - then user enters or exits from fullscreen.
Thanks

**Comment by markx** [comment]
There is already a fullscreen event, `Events.CONTAINER_FULLSCREEN`, which is triggered on `toggleFullscreen`. If that doesn't help, could you be more specific about what your need?

**Comment by FDiskas** [comment]
Thanks. So we need a better documentation.

**Comment by flavioribeiro** [comment]
yep, @leandromoreira is working on the docs but I couldn't find them on the repo. @leandromoreira are u planning to track the docs? Btw, pull requests on docs are welcome! that's why this one is an open source project

**Comment by leandromoreira** [comment]
I'm with tons of documentations on hold :)

**Comment by FDiskas** [comment]
So how to use it? this not works on http://cdn.clappr.io/
```js
player.on(Clappr.Events.CONTAINER_FULLSCREEN, function(a, b) { console.log('CONTAINER_FULLSCREEN!', a, b) });
```

**Comment by leandromoreira** [comment]
@FDiskas 

Events are attached for its specific component, for instance: `Clappr.Events.CONTAINER_FULLSCREEN` works on **container** not [player events](https://github.com/clappr/clappr/blob/master/src/base/events.js#L202-L262)

I would suggest for you to read a little bit of the [code](https://github.com/clappr/clappr/tree/master/src) itself as well some [blog posts](http://blog.flavioribeiro.com/clappr-an-extensible-media-player-for-the-web/) to get more familiar with clappr.

**Comment by FDiskas** [comment]
@leandromoreira :+1:

**Comment by FDiskas** [comment]
Ok - I will ask then for an example. I'm not so advanced as you are.
I need to disable the controls and enable them on fullscreen. How I should do that?

**Comment by leandromoreira** [comment]
Almost all components responds to `disable` and `enable` ;) I think something similar to this might work

```javascript
var container = player.core.getCurrentContainer()
container.on(Clappr.Events.CONTAINER_FULLSCREEN, () => player.core.mediaControl.disable() )
```
