### ISSUE TITLE
Missing "volume" event

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#657]
Need a changed volume event - then user changes the volume value or executes a mote() function
Thanks

**Comment by dayvson** [comment]
hey @FDiskas, when this pull request get merged you will be able to listen this event like:
```
player.on(Clappr.Events.PLAYER_VOLUMEUPDATE, function(volume){ 
                         console.log("volume", volume);
});
player.setVolume(50);
```

**Comment by FDiskas** [comment]
:+1:  thank you
