### ISSUE TITLE
Missing "requestFullscreen" / "cancelFullscreen " method

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#659]
Wanted requestFullscreen / cancelFullscreen methods - to toggle fullsscreen from outside the player.

**Comment by towerz** [comment]
@FDiskas while the player doesn't include an external interface to control fullscreen, you can call `toggleFullscreen` on the player core object:
```javascript
player.core.toggleFullscreen()
```

**Comment by FDiskas** [comment]
http://cdn.clappr.io/ in console try enter `player.core.toggleFullscreen()` :)

**Comment by FDiskas** [comment]
Looks like this is reproducible bug #655

**Comment by towerz** [comment]
Closing this issue since a new one was created with this feature/enhancement spec.
