### ISSUE TITLE
how to control mediacontrol show and hide 

### ISSUE THREAD

**Issue by 569934390** [clappr/clappr#661]
when mousemove and moseleave container the mediacontrol auto show and hide ,i can't control it show or hide;how to control it with javascript

**Comment by towerz** [comment]
@569934390 you can call the methods `show` and `hide` on the media control object. Assuming you have a `player` object, you could do something like this:
```javascript
// shows media control
player.core.mediaControl.show()
// hides media control
player.core.mediaControl.show()
```

**Comment by FDiskas** [comment]
What about option `chromeless: true,`
http://cdn.clappr.io/
```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  chromeless: true,
  autoPlay: true
});

player.attachTo(playerElement);
```

**Comment by 569934390** [comment]
maybe I didn't describe clearly, i mean how to control it hide or show, then when mouseover or mouseleave it don't hide or show again.if i use your method ,it will still show and hide when mousemove or mouseleave.

**Comment by leandromoreira** [comment]
Hey @569934390,

Do you want that neither `mousemove` or `mouseleave` shows the media control? when would it show? you do have [chromeless](https://github.com/clappr/clappr#chromeless) options too

Just out of curiosity, why do you need that?

**Comment by FDiskas** [comment]
In my case, I need to turn off controls by default, but turn them back ON in fullscreen mode.
Other case, is when I change the seek position with API - the controls are displayed (that is wrong)

**Comment by 569934390** [comment]
Hey @leandromoreira 
yes, i want it hide anytime ,the requirement is that, except the real video, i also need to play advertisement (before adv and after adv),so when the before or after adv is playing  i don't want
 the mediacontrol show ,but when the real video is playing i want the mediacontrol show.

**Comment by leandromoreira** [comment]
@569934390 you can disable/enable it !!!

`core.mediaControl.disable()`
and
`core.mediaControl.enable()`

**Comment by 569934390** [comment]
i already tried ,but it seems don't work, when the mouse move or leave, the mediacontrol is still show or hide, the disable properties is still true,it seems like there is something changed it

**Comment by leandromoreira** [comment]
@569934390 you need to do that on play or in an event, maybe enable it again on pause.

Go to http://cdn.clappr.io, before you hit `play` type the following:

`p.on(Clappr.Events.PLAYER_PLAY, function(){p.core.mediaControl.disable()})`

Please notice that `p` will be not available and you should use your clappr instance.

**Comment by 569934390** [comment]
@leandromoreira
thanks a lot ,it worked ! 
i try my code on http://cdn.clappr.io too ,it seems work fine,so maybe i used a old version which has this bug. the new version already fix it

**Comment by leandromoreira** [comment]
hey @569934390 you can always use events, the `p` is not a bug, the only thing is that we're not exposing it through `document.window` but you can always use your instance :)

```javascript

var player = new Clappr.Player({
  source: "http://your.video/here.mp4",
  parameter1: "value1",
  parameter2: "value2",
});

player.on(Clappr.Events.PLAYER_PLAY, function(){p.core.mediaControl.disable()})
//and
player.on(Clappr.Events. PLAYER_ENDED, function(){p.core.mediaControl.enable()})
```

**Comment by 569934390** [comment]
@leandromoreira 
i use it the same way ，but not the player_play event，maybe i use the wrong event!
and the document(http://clappr.github.io/) is too simple,maybe some demo is good

**Comment by 569934390** [comment]
@leandromoreira 
now as i said before,i need to play advertisement,but in mobile it need a tap to play, the load method(player.load(xxxxxx)) will create new video tag ,so i need to tap three times to play before adv,after adv and video,if change  the src ,it only need one tap,so i want to made load method to change src if it's exists. i'm going to change the load method source code,but i think it's a bad way.
do you have any good idea to do it?

**Comment by FDiskas** [comment]
@leandromoreira Thanks for the example. One issue here - if player has option `autoPlay:true` is set then 
```js
player.on(Clappr.Events.PLAYER_PLAY, function(){player.core.mediaControl.disable()})
```
this not works.

**Comment by FDiskas** [comment]
@569934390 Yes I have the same problem. No way to change the stream url without reloading player - so in mobile the video will be stopped.

**Comment by 569934390** [comment]
@FDiskas 
i means if i play many videos ,but i only want tap one time, if change the exist video src not create new video ,by that  you only need one tap

**Comment by leandromoreira** [comment]
@569934390 and @FDiskas you can always use [`load`](http://clappr.github.io/classes/Player.html#method_load) method:

```javascript
var player = new Clappr.Player({
  source: "http://your.video/ad.mp4",
  parameter1: "value1",
  parameter2: "value2",
});
//on mobile, it requires touch
//then on touch you can load another source :P
player.load("http://your.video/normal.m3u8")
```

**Comment by FDiskas** [comment]
@leandromoreira yes sure, but there is a issue on this with mobile devises #666

**Comment by leandromoreira** [comment]
I think if you chain the calls (`load` another `source` and play it when ready) within the user action, you're good to go.

**Comment by FDiskas** [comment]
Yes I tried that already - this not helps.

**Comment by FDiskas** [comment]
Why method `player.seek(50)` shows the controls bar?

**Comment by leandromoreira** [comment]
Hey @FDiskas if you would navigate through the code, you would see that seeking (no matter if by UI our the API) triggers SETTINGSUPDATE which renders **media control**:

* [`player.seek`](https://github.com/clappr/clappr/blob/master/src/components/player.js#L256)
* [`container.setCurrentTime`](https://github.com/clappr/clappr/blob/master/src/components/container/container.js#L254)
* in case mp4/hls for mobile:
  * [`playback.seek`](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L181)
* in case hls.js:
  * [`playback.seek`](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L57)
  * [`mediaControl.render`](https://github.com/clappr/clappr/blob/32e5525a8ed31279176f452ade19cf33cc4408d6/src/components/media_control/media_control.js#L450)

You can always disable the **media control** and enable it after the seek.

**Comment by Allan-Nava** [comment]
How can I show the media controller for hls stream?

**Comment by towerz** [comment]
@Allan-Nava I'm not sure of what you want exactly. The `MediaControl` component is always shown for any kind of source automatically unless you are using the `chromeless` option.

**Comment by Allan-Nava** [comment]
I have the m3u8 but the media control doesn't appear

**Comment by towerz** [comment]
@Allan-Nava can you share a URL where I can see the problem you're having? Can you reproduce the issue on the [test page](http://clappr.io/demo/)? In what platform are you experiencing this issue?

For example, I tested using a Bitmovin sample HLS stream and it's showing the media control normally. You can check it [here](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9iaXRkYXNoLWEuYWthbWFpaGQubmV0L2NvbnRlbnQvc2ludGVsL2hscy9wbGF5bGlzdC5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgYXV0b1BsYXk6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK).

**Comment by Allan-Nava** [comment]
Maybe because i use another configuration with parentId
