### ISSUE TITLE
player.load() do not clears previews requests

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#662]
Then player is playing live HLS its requesting the playlist regulary, but if you change the video source
`player.load('http://***.m3u8')` witch is a record not live - the old url is still requesting
![h5zi30d](https://cloud.githubusercontent.com/assets/468006/11118041/aabe6416-8947-11e5-8675-9f31456a9cbc.png)
And if you continue to load other playlists jusing same method `player.load('')` all old requests is still requesting for playlists.

**Comment by towerz** [comment]
It seems like calling the playback `destroy` method doesn't detach the media source when stopping playback.

**Comment by towerz** [comment]
@FDiskas what version of Clappr are you using? Can you share a live HLS source for us to reproduce this problem?

**Comment by FDiskas** [comment]
This bus exists and on http://cdn.clappr.io/
I have no public HLS sources so try this one
`//wms.shared.streamshow.it/canale8/canale8/playlist.m3u8`
and
`//stream.flowplayer.org/bauhaus.m3u8`
p.s. before you try install https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog
and enable - this will allow cross-domain request.
Here is a bug screenshot: http://i.imgur.com/lx85yAy.png
As you can see the segments still loading from other source

**Comment by FDiskas** [comment]
If i call `player.destroy()` ajax requests still requesting.

**Comment by FDiskas** [comment]
`//nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8`

**Comment by FDiskas** [comment]
Is this fix already released?

**Comment by leandromoreira** [comment]
Not yet, @FDiskas you can see the releases here https://github.com/clappr/clappr/releases
