### ISSUE TITLE
Missing `main_controls` plugin

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#664]
We need to controll the main controls. Like bind some events or listen them for triggers or add more buttons or replace them with other icons.
And access them like
```js
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);
var spinner = player.getPlugin('spinner'); console.log(spinner);
```

**Comment by leandromoreira** [comment]
@FDiskas I don't know if I could understand you, but I would suggest:

* create a custom media control
* listen to specific events

We at globo.com do tons of customization over clappr (you can see it here, http://globoplay.globo.com/v/4065877/)

**Comment by flavioribeiro** [comment]
The control bar isn't a plugin but a component of the player. If you want to add stuff on the controls you can write a core plugin like this https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js.
