### ISSUE TITLE
Mobile device play next video issue

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#666]
Then next video source is loaded video is stopped. Needs manually hit the play button.
Example: http://bit.ly/1LbX2w9
p.s. please install a plugin https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog
before test
```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://beta.adventistplay.se:1935/ekebyholm/abr.smil/playlist.m3u8?DVR',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  autoPlay:true
});

player.attachTo(playerElement);

player.on(Clappr.Events.PLAYER_ENDED, function() {
  player.load('//nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8');
});
```

**Comment by FDiskas** [comment]
I know that for security reasons on mobile devices there is no ability to autoplay videos. But the next video could be played without stop. Probably the problem is that on `player.load()` you destroying the player, but not just updating the source.

**Comment by FDiskas** [comment]
Any news about that? How to play multiple videos with non stop on mobile devices?

**Comment by leandromoreira** [comment]
Hey @FDiskas ,

Try to change `src`:

```javascript
//you load your ad and then in a given event you ...
onClick(){
player.play()

player.on(XXX, function(){
player.core.getCurrentPlayback().el.src =  "http://realthing"
player.play();
})

```

**Comment by FDiskas** [comment]
This looks like not working. Player is still requesting wrong segments

**Comment by leandromoreira** [comment]
@FDiskas is it still the same?

**Comment by FDiskas** [comment]
It works on mp4 video files, but not works on HLS or DVR

**Comment by leandromoreira** [comment]
@FDiskas cool, I'm gonna close this one since this behavior will be handled by https://github.com/clappr/clappr/issues/550

**Comment by FDiskas** [comment]
@leandromoreira  Any example?
