### ISSUE TITLE
FIX: npm run build ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#671]
Probably related: https://github.com/webpack/css-loader/issues/145#issuecomment-151594092
I added 
```js
require('es6-promise').polyfill();
```
```
npm install es6-promise
```
to the **webpack.config.js** file at the top and problem gone

**Comment by flavioribeiro** [comment]
@FDiskas you can submit improvements/bugfixes/feature requests by following this workflow: https://github.com/clappr/clappr#contributing
