### ISSUE TITLE
player.setVolume() does not updates the localStorage value

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#677]
On http://cdn.clappr.io/ website in console enter
```js
localStorage
```
This will return the
```json
{clappr.cdn.clappr.io.volume: "0"}
```
then enter
```js
player.setVolume(50);
```
and then again
```js
localStorage;
```
but if the volume is changed by pressing on volume control bar then localStorage returns
```json
{clappr.cdn.clappr.io.volume: "56.02678571428571"}
```

**Comment by FDiskas** [comment]
Because of this bug after loading new player the volume are changed to wrong value.

**Comment by dayvson** [comment]
Hey @FDiskas I sent a pull request to fix this issue https://github.com/clappr/clappr/pull/701
After it gets merged could you please test it?

**Comment by FDiskas** [comment]
Version 0.2.22 still has this bug. As I can see there is no release yet.
p.s. I'm testing on http://cdn.clappr.io/

**Comment by gamtiq** [comment]
Version 0.2.47 still has this bug. It seems that the bug was brought back by c805ffa

**Comment by FDiskas** [comment]
I see that there is no tests written. :D 
https://github.com/clappr/clappr/commit/736138a5f8b01bde61d9bacfc5bc70b0555aaa50
So why we returning to the same bug twice?

**Comment by towerz** [comment]
@FDiskas you are welcome to submit a PR and add proper tests if you wish.

**Comment by FDiskas** [comment]
It's not my bussines
