### ISSUE TITLE
LG G3 mobile full-screen issue

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#680]
The fullscreen issue. This happens then I click on player fullscreen icon.
![screenshot_2015-11-19-15-11-28](https://cloud.githubusercontent.com/assets/468006/11271706/8a7ac314-8ed0-11e5-8773-05954843ede6.png)

**Comment by leandromoreira** [comment]
Hey,

What android are you using and what browser? I'd like to insist for you to try to follow [our guideline to open issues](https://github.com/clappr/clappr#guideline-to-open-an-issue-bug).

**Comment by FDiskas** [comment]
Browser: http://whatsmybrowser.org/b/HTYERUD
Android: 5.0

**Comment by leandromoreira** [comment]
Thanks @FDiskas for pointing that out, we don't know how this browser works we'll need to check that after.

**Comment by FDiskas** [comment]
So its working now?
