### ISSUE TITLE
HLS manifest not recognized as playable media if URL doesn't end with m3u8

### ISSUE THREAD

**Issue by derrod** [clappr/clappr#683]
I noticed this while checking issue #648 with the Microsoft stream.

The URL of the base manifest is
`http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl)`
When used as src URL on the test page at http://cdn.clappr.io/ the player will return the following error:
`Your browser does not support the playback of this video. Please try using a different browser.`
It works if you append ".m3u8" to the URL. The content type sent by the server is `application/vnd.apple.mpegurl`.

I'm not sure where the error is though. A quick look through the source and some trial and error didn't turn up any results :/

**Comment by leandromoreira** [comment]
@derrod, I think, although the server responds with the proper content type [we don't use the header](https://github.com/clappr/clappr/blob/master/src/components/container_factory/container_factory.js#L32) from the server instead we use the `options`.

Please, try the following:

```javascript
var player = new Clappr.Player({
  source: "http://your.video/ism/manifest",
  mimeType: "application/vnd.apple.mpegurl",
  parentId: "#player"
});
```

**Comment by derrod** [comment]
Ah Thanks. It might be a good idea to add that to the documentation/wiki :)

**Comment by leandromoreira** [comment]
@derrod thanks done deal https://github.com/clappr/clappr#add-mimetype-for-extension-less-url
