### ISSUE TITLE
Real time of seekbar

### ISSUE THREAD

**Issue by cowai** [clappr/clappr#685]
Hi,
It should be possible to have the real time in the dvr buffer for the hls stream.

Is that possible today? If not, anyone wanting to point me in the right direction?

Update:
Just to clearify. Instead of showing the dvr buffer duration in the seek bar, show the relevant local time of the seeked position.
That means that "LIVE" will be now, and everything is relative to current time. Makes sense?

**Comment by cowai** [comment]
This issue can be closed as the feature has been implemented.

**Comment by thiagopnts** [comment]
Thanks!
