### ISSUE TITLE
HE-AAC HLS problem in chrome

### ISSUE THREAD

**Issue by cowai** [clappr/clappr#692]
Right now there is a bug with hls.js/chrome when using HE-AAC. It can sometimes fail appending segments so there is a total freeze.

Related bug report: https://code.google.com/p/chromium/issues/detail?id=534301
Blog article talking about he-aac switching bugs: http://engineering.dailymotion.com/introducing-hls-js/

If we could reinitiate the mediasource when this happens it would be a nice fix until chrome fixes this itself.

**Comment by leandromoreira** [comment]
maybe it's better to open this "issue" on https://github.com/dailymotion/hls.js with @mangui

**Comment by mangui** [comment]
@cowai 
the issue happens when no CODECS are specified in the main manifest.
if your manifest correctly declare the audio codec, then it should be fine ? or please share your stream

**Comment by cowai** [comment]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=120000,CODECS="avc1.77.30,mp4a.40.5",RESOLUTION=256x192
miracle1_low/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=350000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=480x360
miracle1_med/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1028000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=768x576
miracle1_high/index.m3u8

@mangui 
http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2F146.185.141.228%2Fhls%2Fmiracle1.m3u8


I get "Frag Appending Error" every once in a while and I need to restart the stream.

**Comment by cowai** [comment]
As you can see I have the codecs setup.
The encoder is libav/avconv with libfdk-aac and -profile:a aac_he on the first level.
The strange thing is that the error can come long after it has upgraded to the last level (LC AAC)

**Comment by cowai** [comment]
it seems to be too ahead of the playlist. I see that after 1448461299000.ts is requested it goes directly to 1448461279000.ts (two segments ago), and the last m3u8 request before that did not have a newer ts than 1448461299000.ts. So this seems to a timings issue.

**Comment by cowai** [comment]
Example: 
![selection_013](https://cloud.githubusercontent.com/assets/445843/11399645/0c32d038-9389-11e5-96d8-f9ed0b24a9f9.png)

**Comment by cowai** [comment]
@mangui Should I submit this issue to https://github.com/dailymotion/hls.js instead? Or do you quickly see something wrong with my stream and it doesn't need another issue created?

**Comment by mangui** [comment]
@cowai 
can you report the log of your playback session from chrome://media-internals ?

**Comment by cowai** [comment]
00:00:00 00	pipeline_state	kCreated
00:00:00 00	event	WEBMEDIAPLAYER_CREATED
00:00:00 00	url	blob:http%3A//dailymotion.github.io/ee5bb695-87dc-4d47-916a-bdb6b5fd1d38
00:00:00 20	pipeline_state	kInitDemuxer
00:00:00 322	info	Audio codec: mp4a.40.2
00:00:00 322	found_audio_stream	true
00:00:00 322	audio_codec_name	aac
00:00:00 322	duration	10800
00:00:00 322	info	Video codec: avc1.640c
00:00:00 322	found_video_stream	true
00:00:00 322	video_codec_name	h264
00:00:00 322	pipeline_state	kInitRenderer
00:00:00 324	audio_dds	false
00:00:00 324	audio_decoder	FFmpegAudioDecoder
00:00:00 324	video_dds	false
00:00:00 324	video_decoder	FFmpegVideoDecoder
00:00:00 324	pipeline_state	kPlaying
00:00:00 327	seek_target	10770.1162109375
00:00:00 327	pipeline_state	kSeeking
00:00:00 328	pipeline_state	kPlaying
00:00:00 334	event	PLAY
00:00:02 592	info	Audio codec: mp4a.40.2
00:00:02 592	info	Video codec: avc1.6401f
00:00:10 02	debug	Audio splicer skipping frames for small overlap of 229us at time 10780030984us.
00:00:10 584	height	576
00:00:10 584	width	768
00:00:18 586	info	Audio codec: mp4a.40.2
00:00:18 586	info	Video codec: avc1.64015
00:00:18 588	duration	10800.046977
00:00:18 589	debug	Generated splice of overlap duration 26978us into new buffer at 10789886977us.
00:00:19 857	error	Audio splicing failed: coded frame timestamp differs from expected timestamp 10789945678us by -58701us, more than threshold of +/-50ms. Expected timestamp is based on decoded frames and frame rate.
00:00:19 857	error	audio decode error during playing
00:00:19 857	pipeline_error	pipeline: decode error
00:00:19 857	pipeline_state	kStopping
00:00:19 859	pipeline_state	kStopped

**Comment by cowai** [comment]
I see that the audio codec reported by chrome is mp4a.40.2, but the first level is in fact mp4a.40.5.

**Comment by mangui** [comment]
weird, could you share your stream ? 
even privately, here is my email address
```curl -i https://api.github.com/users/mangui/events/public | grep email | grep gmail```

**Comment by cowai** [comment]
I posted it further up but here you go: http://146.185.141.228/hls/miracle1.m3u8

**Comment by mangui** [comment]
could you confirm that the error only happens when using adaptive streaming ?
I don't seem to get the issue while checking on a mono level stream, for example http://146.185.141.228/hls/miracle1_high/index.m3u8

**Comment by cowai** [comment]
Yes in my experience it only happens with the main manifest. Also if I throttle the bandwidth a little (a limit that is more that the stream bitrate) it can trigger the bug also. It seems to be too slow fetching the manifest file. If you see my screenshot further up you will see that.

**Comment by mangui** [comment]
can you retry on http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2F146.185.141.228%2Fhls%2Fmiracle1.m3u8
with Auto-Recover Media Error enabled ?

**Comment by cowai** [comment]
Yes it fixes it self with the Auto-Recover option.
Btw, does it make sense that it seem to be a bit more stable and robust when I have 4s segment length instead of 10s?

**Comment by mangui** [comment]
well, i can see sample overlapping with your stream when doing quality switch 
i.e. your fragments are not well aligned when switching between quality level. I saw a gap of 150ms.
also if could avoid using different audio codecs (HE-AAC and AAC) it would help, as browsers are not supporting audio codec switch really well with MSE.

**Comment by cowai** [comment]
Hi,
I have tried with HE-AAC only but that is not any better, and LC-AAC is terrible at 32kbit/s.

When you say sample overlapping, are you talking about segments overlapping each other across level/quality?
I will see if I can somehow get the levels to match. How small gap is needed? 0?

Is this what I want to fix?
```shell
$ filename=$(curl -s http://146.185.141.228/hls/miracle1_low/index.m3u8|grep \.ts|tail -n1);ffprobe http://146.185.141.228/hls/miracle1_high/$filename 2>&1 | grep "start" && ffprobe http://146.185.141.228/hls/miracle1_med/$filename 2>&1 | grep "start" && ffprobe http://146.185.141.228/hls/miracle1_low/$filename 2>&1 | grep "start"
  Duration: 00:00:10.16, start: 34650.618189, bitrate: 1066 kb/s
  Duration: 00:00:10.14, start: 34650.636000, bitrate: 450 kb/s
  Duration: 00:00:10.21, start: 34650.723000, bitrate: 151 kb/s
```
Also, is the auto-recover option something I can pass with clappr?

Thank you for your help! Much appreciated.

**Comment by leandromoreira** [comment]
I think yes @cowai , https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L36

```javascript
new Clappr.Player({
  hlsjsConfig: {
    debug : false,
    autoStartLoad : true,
    maxBufferLength : 30,
    maxBufferSize : 60*1000*1000,
    liveSyncDurationCount : 3
  }, source: "http://my.live.video/hls.m3u8"
})
```

**Comment by mangui** [comment]
autorecover is not an hls.js option.
it is handled directly in the demo page.

https://github.com/dailymotion/hls.js/blob/master/demo/index.html#L564-L567

**Comment by leandromoreira** [comment]
can I close this @cowai ?

**Comment by cowai** [comment]
The problem is not totally fixed yet. But it doesn't really have anything to do with Clappr so I guess it can be closed for now.

**Comment by leandromoreira** [comment]
@cowai try this (I'm not sure about what error would be, it's not an event though):

```javascript
//.. after clappr's creation

clappr.on(Clappr.Events.PLAYER_ERROR, function(error) {
  var playback = clappr.core.getCurrentPlayback()
  if (playback.name !== 'hls') return

  var errorTxt, mediaError = error
  if (mediaError.code === mediaError.MEDIA_ERR_DECODE) {
    playback.hls.recoverMediaError()
  }
})
```
