### ISSUE TITLE
mutating the [[Prototype]] performance warning in Firefox

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr#702]
Browser: Firefox 42.0

OS: Fedora 23 x86_64

Clappr Version: 0.2.22

Steps to reproduce:

1 open http://cdn.clappr.io/ in firefox 42
2 open console Ctrl+Shift+J
You can see a warning 
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

warning indicates line 1861 in clappr.js 

``` javascript
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object. setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
```

Related stackoverflow thread:
http://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance/23809148#23809148

**Comment by leandromoreira** [comment]
@me-vlad is this still happening?

**Comment by me-vlad** [comment]
@leandromoreira yes, checked again with firefox 43 on linux and windows 10 - same warnings on  http://cdn.clappr.io/

**Comment by leandromoreira** [comment]
I thought it was only an annoying warning https://bugzilla.mozilla.org/show_bug.cgi?id=984146 maybe we'll need to update babel (since I think it's the culprit of it)

**Comment by leandromoreira** [comment]
http://stackoverflow.com/questions/33858349/fixing-mutating-the-prototype-of-an-object-in-babeljs-6

**Comment by joaopaulovieira** [comment]
I tested on Firefox 59 and could not reproduce.
@me-vlad is this still happening?

**Comment by me-vlad** [comment]
Firefox 59.0.1 - no warnings
