### ISSUE TITLE
How to resolve cors?

### ISSUE THREAD

**Issue by tanchun** [clappr/clappr#703]
var playerElement = document.getElementById("player-wrapper");
var player = new Clappr.Player({
  source: 'http://live.xmcdn.com/192.168.3.138/live/112/24.m3u8',
  height: 360,
  width: 640
});

player.attachTo(playerElement);

(index):1 XMLHttpRequest cannot load http://live.xmcdn.com/192.168.3.138/live/112/24.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.25.194:2000' is therefore not allowed access.

**Comment by leandromoreira** [comment]
Hi @tanchun , [cors](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) is a mechanism that allows restricted resources (e.g. playlists, media, json, fonts...) on a web page to be requested from another domain outside the domain from which the resource originated. You need to [enable it on your server.](http://enable-cors.org/server.html)

Here's an nginx example:

```nginx
location / {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        #
        # Om nom nom cookies
        #
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
}
```

Very often we run servers locally (http://localhost:8000) and try to consume media from a different domain (http://example.com), what we can do is: either edit `vim /etc/hosts` or to enable cors on server side.

**Comment by tanchun** [comment]
I got it, thanks

**Comment by chovy** [comment]
I don't control the stream I'm trying play with clappr and I'm getting this error about `Access-Control-Allow-Origin` header missing. Is there any work around?

**Comment by leandromoreira** [comment]
@chovy you can't circumvent cors at the player, you can use Flashls instead of hlsjs:
```javascript
({
plugins: {playback: [Clappr.Clappr.Flashls]}
})
```

**Comment by chovy** [comment]
Is there a library js file I need to load for this to work?

**Comment by towerz** [comment]
@chovy There's no way to circumvent CORS in the browser. You have to fix that directly in your server.

Using flash doesn't mean it won't work on mobile, the player always try to use native HTML5 playback, even though you are forcing Flash. Since Flash isn't present on mobile platforms, the HTML5 playback will get called instead.

**Comment by chovy** [comment]
> @chovy There's no way to circumvent CORS in the browser. You have to fix that directly in your server.

I'm not sure what you mean "fix on my server" -- I don't have access to the server hosting the stream and the key file.

**Comment by leandromoreira** [comment]
@chovy try to ask to the server people to add the [needed headers](http://enable-cors.org/) but if you can't then there is no way, this is a security thing imposed by the browsers.

**Comment by alwayzgame** [comment]
@leandromoreira where shud we place this cors or which folder on nginx server?

location / {
  add_header 'Access-Control-Allow-Origin' '*';
  add_header 'Access-Control-Allow-Credentials' 'true';
  add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
}

**Comment by kslimani** [comment]
@alwayzgame : [read this](https://enable-cors.org/server.html).
