### ISSUE TITLE
clappr flasHLS flash component mxmlc build options

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr#704]
Hello!

Is any special reason for defining -target-player="14.0" in Clappr flashls build sctipt?
https://github.com/clappr/flashls/blob/clappr/build/build_clappr.sh#L24
https://github.com/clappr/flashls/blob/clappr/build/build_clappr.sh#L36

May be 14 is a swf file format version not a player version?

FlasHLS main build script (https://github.com/clappr/flashls/blob/clappr/build/build.sh) uses -target-player="11.1" and -target-player="10.1" for different players.
 
For Flex 4.6, the default value of swf-version is 14 (and the default Player version is 11.1).
http://help.adobe.com/en_US/flex/using/WS2db454920e96a9e51e63e3d11c0bf69084-7a92.html
http://help.adobe.com/en_US/flex/using/WS2db454920e96a9e51e63e3d11c0bf69084-7ee0.html
http://sleepydesign.blogspot.com/2012/04/flash-swf-version-meaning.html

You can find these defaults in flex_sdk_4.6/frameworks/flex-config.xml config file
```
<flex-config>
    <!-- Specifies the minimum player version that will run the compiled SWF. -->
   <target-player>11.1</target-player>

    <!-- Specifies the version of the compiled SWF -->
    <swf-version>14</swf-version>
```

**Comment by towerz** [comment]
@me-vlad I don't think there's a particular reason for using target-player=14.0. As far as I can remember, we don't need any specific feature from this version. Are you having any problems with this?

**Comment by me-vlad** [comment]
@towerz I see 2 reasons to change target player

1 latest supported NPAPI flash plugin version for linux systems is 11.2.202.548  
http://www.adobe.com/software/flash/about/

2 With default settings in flex_sdk_4.6 clappr build fails with error
```
FLEXPATH=/home/vlad/Work/flex_sdk_4.6 ./build_clappr.sh 
Compiling bin/release/HLSPlayer.swf
Loading configuration file /home/vlad/Work/flex_sdk_4.6/frameworks/flex-config.xml
Adobe Flex Compiler (mxmlc)
Version 4.6.0 build 23201
Copyright (c) 2004-2011 Adobe Systems, Inc. All rights reserved.

/home/vlad/Work/flex_sdk_4.6/frameworks/flex-config.xml(56): Error: unable to open 'libs/player/14.0/playerglobal.swc'

      </external-library-path>

Compiling bin/debug/HLSPlayer.swf
Loading configuration file /home/vlad/Work/flex_sdk_4.6/frameworks/flex-config.xml
Adobe Flex Compiler (mxmlc)
Version 4.6.0 build 23201
Copyright (c) 2004-2011 Adobe Systems, Inc. All rights reserved.

/home/vlad/Work/flex_sdk_4.6/frameworks/flex-config.xml(56): Error: unable to open 'libs/player/14.0/playerglobal.swc'

      </external-library-path>
```

flex_sdk_4.6/frameworks/libs/player directory listing:
 
```
ll -R ~/Work/flex_sdk_4.6/frameworks/libs/player
/home/vlad/Work/flex_sdk_4.6/frameworks/libs/player:
total 4
drwxrwx---. 2 vlad vlad 4096 Nov 10  2011 11.1

/home/vlad/Work/flex_sdk_4.6/frameworks/libs/player/11.1:
total 332
-rwxrwx---. 1 vlad vlad 337288 Nov 10  2011 playerglobal.swc
```

**Comment by towerz** [comment]
No problem, I was just checking if this was a real issue, since I don't know the reason why we used that. I believe the build script was created from a template and perhaps whoever wrote it forgot a hardcoded value for the target player.

I'll change that and make a new version, then. Thanks a lot.

**Comment by towerz** [comment]
@me-vlad thanks for your PRs, they're already added to the flashls playback on master.
