### ISSUE TITLE
HLS not working in Chrome/Chromium

### ISSUE THREAD

**Issue by philcrump** [clappr/clappr#705]
The code I'm using is:

```
var player = new Clappr.Player({
	source: "http://hls.batc.tv/test/index.m3u8",
	autoPlay: true,
});
player.on(Clappr.Events.PLAYER_ERROR, function(e)
{
	console.log("caught error");
	console.log(e);
});
var playerElement = document.getElementById("player");
player.attachTo(playerElement);
```

Also reproducible on http://cdn.clappr.io/ The HLS source is streaming Sintel in a loop on that URL for others to try. (h264 main 3.1 + aac)

**Browser:**  Chrome for Android
**OS:** Android 5.0
**Clappr Version:** 0.2.23

Works.

**Browser:**  Firefox 42
**OS:** Ubuntu 15.10
**Clappr Version:** 0.2.23

Works.

**Browser:**  Chromium 45
**OS:** Ubuntu 15.10
**Clappr Version:** 0.2.23

Fails to play. Playing icon disappears but I just get a black screen and video+audio never load. Network inspector shows that it loads the first two TS fragments, but then just continually reloads the m3u8 playlist.

Console:
> caught error
> (index):17 Object {error: MediaError, container: t}
>   container: t
>   error: MediaErrorcode: 3
>   __proto__: MediaError
>   MEDIA_ERR_ABORTED: 1
>   MEDIA_ERR_DECODE: 3
>   MEDIA_ERR_NETWORK: 2
>   MEDIA_ERR_SRC_NOT_SUPPORTED: 4
>   code: (...)get code: ()constructor: MediaError()__proto__: Object__proto__: Object

**Browser:**  Chrome 46
**OS:** Windows 7
**Clappr Version:** 0.2.23

Fails to play. Same behaviour+console as on ubuntu/chromium.

**Comment by philcrump** [comment]
**Browser:**  IE 11
**OS:** Windows 7
**Clappr Version:** 0.2.23

Works.

**Browser:**  Chrome 47
**OS:** Windows 7
**Clappr Version:** 0.2.23

Fails to play. Same behaviour+console as on ubuntu.

**Comment by leandromoreira** [comment]
Hey @philcrump can you test with this url http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 it may be related to your hls streaming

**Comment by philcrump** [comment]
Hmm yes that works on my page in Ubuntu+Chromium.

Do you have any idea what the issue with my TS fragments could be such that they don't play in only Chrome?

I'm currently using the ffmpeg line below to live transcode the incoming feed, before nginx-rtmp serves it as HLS, and Clappr plays it.

> ffmpeg -i rtmp://[rtmp nginx-rtmp stream]/ -c:a libfdk_aac -b:a 64k -c:v libx264 -b:v 1024k -maxrate 1024k -bufsize 2048k -profile:v main -level 3.1 -tune zerolatency -preset ultrafast -f flv rtmp://[hls nginx-rtmp stream];

**Comment by leandromoreira** [comment]
@philcrump we were using [this config](https://github.com/brocaar/nginx-rtmp-dockerfile/blob/master/nginx.conf#L12) a long time ago, it may work for you.

**Comment by philcrump** [comment]
After stripping the multi-bitrate out of your example due to cpu restrictions, I'm now using the config below, still no luck.

My test page is at http://hls.batc.tv/ and still works in firefox, doesn't work in chrome. (But worked in both using your hls stream)

```
rtmp {
    server {
        listen 1935;
        chunk_size 4000;

        application hls {
            live on;

            hls on;
            hls_fragment_naming system;
            hls_fragment 5s;
            hls_path /usr/local/nginx/html;
            hls_nested on;
        }
        application in-hls {
            live on;
            exec /usr/local/nginx/ff/ffmpeg -i rtmp://127.0.0.1/in-hls/$name -c:a libfdk_aac -b:a 64k -c:v libx264 -b:v 1000k -f flv -g 30 -r 30 -s 720x540 -preset superfast -profile:v baseline rtmp://127.0.0.1/hls/$name;
        }
    }
}
```

**Comment by leandromoreira** [comment]
I don't know how to help you, I think it's related to ffmpeg version. Try this one.

```nginx
daemon  off;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4000;

        application encoder {
            live on;
            exec /usr/local/nginx/ff/ffmpeg -i rtmp://localhost:1935/encoder/$name 
              -c:a libfdk_aac -b:a 64k -c:v libx264 -b:v 200k -f flv -g 15 -r 15 -s 426x240 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_240p264kbs;
        }

        application hls {
            live on;
            hls on;
            hls_fragment_naming system;
            hls_fragment 5s;
            hls_path /usr/local/nginx/html;
            hls_nested on;
        }
    }
}

```

**Comment by philcrump** [comment]
Haha, tried poking another RTMP source into it, and it works! It appears my trusty copy of Sintel was the issue all along. How, as it gets fully transcoded before reaching the browser, I have no idea...

Thank you **very** much for your help!

**Comment by philcrump** [comment]
As a further note, the cause of this issue was that the source sample rate of the audio stream was not being changed during transcoding, and Chrome did not like 22050Hz or 48000Hz AAC. Either using a 44100Hz source, or transcoding to 44100Hz, fixed the problem.
