### ISSUE TITLE
Add public interface to control fullscreen state

### ISSUE THREAD

**Issue by towerz** [clappr/clappr#708]
One of the most common requests we receive is to provide a way to enter fullscreen externally, either with a `setFullscreen/toggleFullscreen` call or entering fullscreen when the user starts a video (#527, #659, #706 - apparently).

I think we could add methods to the public API of the `Player` object, as well as an embed parameter to control whether the player should enter fullscreen when starting playback (after the user clicks the poster, or play button, for example).

**Comment by thiagopnts** [comment]
IIRC, to enter in fullscreen we first need a user interaction, I think we should keep that in mind when designing this API. It would also be worth to take a look at the browser's fullscreen API again, I remember it was a pain so things might be evolved somehow now

**Comment by towerz** [comment]
@thiagopnts yes, I'm aware of that, but I think we should offer a cleaner way of handling fullscreen than handling the click event on poster and calling the fullscreen API, for example. Another thing we should consider is receiving the event as a parameter and checking whether or not the event is user-initiated. This way we can warn the caller when the fullscreen call is invalid. I'm not sure this solution could be cross-browser, but it's worth a try.

**Comment by joaopaulovieira** [comment]
Closing this issue as it's not possible to control the fullscreen state without a user action.
