### ISSUE TITLE
HLS format does not work properly on Android system.

### ISSUE THREAD

**Issue by sxh615** [clappr/clappr#710]
I change following code,
var player = new Clappr.Player({
    source: "http://your.video/here.mp4",
  });
http://your.video/here.mp4 --> http://your.video/here.m3u8
On Android system(4.4.4),  i will get error info "Uncaught TypeError: this.el.globoPlayerLoad is not a function". Is it because the flash plugin is not installed?

**Comment by leandromoreira** [comment]
@sxh615 what device are you using? what browser are you using? what clappr version? did you try http://cdn.clappr.io/ with http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 ?

**Comment by sxh615** [comment]
I try "http://cdn.clappr.io/ with http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8". It works fine.

I'm so sorry that I have made mistake. I tested p2p hls using bemtv("clappr": "0.0.62") on Android system, I comments followwing code ,  error still exist so that I think clapper don't support android.
//plugins: {playback: [P2PHLS], container: [P2PHLSStats]},

**Comment by leandromoreira** [comment]
@sxh615 can I close this one? people are using clappr mostly with firefox or chrome on android > 4 and they seem fine. If you still are facing errors please gives us more details about it.

**Comment by sxh615** [comment]
@leandromoreira Certainly you can. Thanks a lot for your help.
