### ISSUE TITLE
Video freezes in the first buffering on iPhone using Safari

### ISSUE THREAD

**Issue by flavioschuindt** [clappr/clappr#718]
Hi, guys.

I'm using this [VoD playlist] (http://ensineme.com/media/videos/4/4/4/ts/b3ede8f98dd94520801262bcceedb1c6.m3u8) with **latest** clappr version from cdn and it's working fine on chrome and other browsers. But when I try to watch the video in my **iPhone 5c** running **Safari** on **iOS 9.1** the video simply freezes in the first buffering and nothing happens after. Sometimes it shows clappr loading animation, sometimes not, just freezed and nothing more. 

I tried to test this same playlist in http://cdn.clappr.io/ and I observed the same behavior.

One interesting point here is about the connection: All of the stuff explained above happens when I'm connected through WiFi (ADSL 5Mbps link). When I do the same test using 4G, the loading is so fast that the video doesn't need to stop and buffering and then it works without any kind of problems.

Thank you, guys!

**Comment by flavioschuindt** [comment]
Adding more info: Just downloaded firefox and chrome for iOS and observed the same problem,

**Comment by leandromoreira** [comment]
Thanks @flavioschuindt :), we need to take a look at these problems.

If you can, it'd help to remote debug a chrome but before you start the media, turn on the logger, go to console and type: `Clappr.Log.setLevel(0)` and then start the video and copy and paste the log here and also any error you found on console.

**Comment by leandromoreira** [comment]
can you test it against this [build](https://gist.github.com/leandromoreira/61436e5e31d48818df7c/archive/fff2444cb675c75ec2baea46938c19a22ad61986.zip) ?

**Comment by flavioschuindt** [comment]
@leandromoreira just tested and the proble persists :( On my ADSL 5Mbps link, it freezes on the first buffering. When I test it on 4G, it doesn't need to buffering and the video works well.

What I've done to install this build that you mentioned: Downloaded the .zip, extracted the .js from it and added it on my static folder served by nginx. After, I downloaded the **dist** folder from clappr repo to get the fonts, etc., added it to my static folder and finally changed baseUrl when creating the player in my code to point to the dist folder.

**Comment by leandromoreira** [comment]
You've done right! I've tested this build using my ADSL but using Android =/ It was working. I'll try to find an iphone to test it.

**Comment by flavioschuindt** [comment]
Ok, @leandromoreira. I changed my master playlist to serve 8 different bitrates, instead of just one as before. Now, it's working fine on iPhone!

But I think there is something weird related to the case where I serve only one bitrate: Shouldn't clappr try to play this only bitrate no matter what happens? Or clappr implements some timeout? In my mind, clappr should think: "Ok, this guy doesn't have a good internet connection, this is a high quality video, but I will try my best to play this video. No matter what happens.". The behaviour in this case is always the same: Video freezes in the first buffering. If I immediately change to the 8 bitrates playlists, everything works fine!

**Comment by leandromoreira** [comment]
> But I think there is something weird related to the case where I serve only one bitrate: Shouldn't clappr try to play this only bitrate no matter what happens? 

Clappr delegates this responsibility to the vide tag, I'm almost 100% sure that you need to offer audio-only track (plus alternatives video tracks) always on iOS. Clappr doesn't chose what level you should be, this is done by the tag video (in ios and android's case).

For iOS we usually offers at the minimum 3 bitrates + audio-only tracks. Can we close this issue or do you still think it's relevant to further investigations?
