### ISSUE TITLE
Player HLS problem in Safari and IE

### ISSUE THREAD

**Issue by floriano12** [clappr/clappr#725]
I receive a page color in my player.

Which is my mistake ?

![player_safari](https://cloud.githubusercontent.com/assets/14894216/11700737/d6ab513a-9ecb-11e5-9d87-782a9a7afc73.png)

Another error:
![error_player](https://cloud.githubusercontent.com/assets/14894216/11700740/e18e8e50-9ecb-11e5-88e8-84a713a8b446.png)

This is my code:
```
    <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
```

``` 
var MyPlayer = Clappr.UIContainerPlugin.extend({
        bindEvents() {
          this.listenTo(this.container, Clappr.Events.CONTAINER_PLAY, this.render)
        },
        render: function() {
          
          this.$el.html('')
          this.$el.css('font-size', '15px')
          this.$el.css('color', 'red')
          this.$el.css('background-color', 'white')
          this.$el.css('position', 'relative')

          this.container.$el.append(this.$el)
          return this
        }
      });

         var player = new Clappr.Player({
    source: "<?php echo $row['path_http']; ?>/<?php echo $_GET['v'];?>/index.m3u8",
    parentId: '#player',
    autoPlay: true,
    hideMediaControl: true,
    width: 535, height: 428,
    debug: true,
    actualLiveServerTime: true, # this current time is correctly here ?
    poster: "<?php echo $link_url; ?>templates/assets/images/img.png",
    plugins: {container: [MyPlayer]},
    mediacontrol: {seekbar: "#E113D3", buttons: "#66B2FF"}
   });
    ```
But in Chrome and Mozilla work fine!

Thanks in advance for any help!

**Comment by leandromoreira** [comment]
@floriano12 there is no error happening, the messages you're seeing are warnings. Clappr is working fine, please test on 

http://cdn.clappr.io/

**Comment by floriano12** [comment]
@leandromoreira thanks for your reply!

which is my mistake on clappr player, in code script ?

I make live stream, why not work player ? why receive color player ?

I tested my script with another player and work fine.

Please, tell me how can include current time in my code script!
Regards,
Florin

**Comment by leandromoreira** [comment]
Please try to read the readme, if you're using RTMP you also need to add rtmp plugin:

```javascript
<script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"> </script>
<script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js"></script> 

<script> 
var player = new Clappr.Player({ 
source: "rtmp://phpstreaming.com:1935/live?user=QXY9snfYNU", 
plugins: {'playback': [RTMP]}, 
rtmpConfig: { swfPath: 'dist/assets/RTMP.swf', scaling:'stretch', playbackType: 'live', bufferTime: 1, startLevel: 0, autoSwitch: true, }, parentId: "#player" }); 
</script>
```

**Comment by floriano12** [comment]
@leandromoreira , thanks so much for your help!
I have two servers, one with RTMP and in second use HLS. 

sorry, but this RTMP don't work for me ! I try with another player and work my script.

Which is my mistake in HLS clappr player ?

you can put a code script which work live stream in Safari and IE 
please include in this code current time.

Thanks in advance!

**Comment by leandromoreira** [comment]
@floriano12 this is the code :package: that works with RTMP.

```javascript
<script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"> </script>
<script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js"></script> 

<script> 
var player = new Clappr.Player({ 
source: "rtmp://phpstreaming.com:1935/live?user=QXY9snfYNU", 
plugins: {'playback': [RTMP]}, 
rtmpConfig: { swfPath: 'dist/assets/RTMP.swf', scaling:'stretch', playbackType: 'live', bufferTime: 1, startLevel: 0, autoSwitch: true, }, parentId: "#player" }); 
</script>
```
