### ISSUE TITLE
HD indicator not appearing in clappr 0.2.24

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr#726]
Hello,
HD indicator not appearing on media control bar when HD stream is playing.
Tested on latest clappr build and on cdn.clappr.io
Теst stream:  http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8

**Comment by leandromoreira** [comment]
@me-vlad we need to [rework the way we override the settings](https://github.com/clappr/clappr/issues/684) I

**Comment by leandromoreira** [comment]
still a problem?

**Comment by me-vlad** [comment]
HD indicator works with latest clappr on  cdn.clappr.io
