### ISSUE TITLE
Abstract plugin type during player instantiation

### ISSUE THREAD

**Issue by thiagopnts** [clappr/clappr#735]
Right now, the one using the plugin needs to say to the player that it is a `core` plugin. Being Core/Container/Playback/etc plugins are the type of detail that we can hide from people _using_ plugins, this is just relevant to people _developing_ plugins and to the player:

```javascript
var player = new Clappr.Player({
    source: "foo.mp4",
    parentId: "#player-wrapper",
    plugins: {core: [ClapprThumbnailsPlugin]},
});
```
 So we could add a way to the plugin's developer say the type of the plugin to the player, so the one using the plugin can just:

```javascript
var player = new Clappr.Player({
    source: "foo.mp4",
    parentId: "#player-wrapper",
    plugins: [ClapprThumbnailsPlugin],
});
```

Then Clappr figures out the plugin type and uses it in the right way.

What you guys think?

**Comment by leandromoreira** [comment]
I agree with you and @flavioribeiro already introduced the [`type`](https://github.com/clappr/clappr/blob/master/src/base/ui_container_plugin.js#L57) so if you develop a `UICorePlugin` we can infer its type.

**Comment by leandromoreira** [comment]
Man Towers is unstoppable and he's still playing

![a](http://i.kinja-img.com/gawker-media/image/upload/buqaadxkqhge1okhd3ij.gif) 
![b](http://image.noelshack.com/fichiers/2013/24/1371147315-cours.gif)
