### ISSUE TITLE
HLS playback triggering PLAYBACK_LEVELS_AVAILABLE repeatedly

### ISSUE THREAD

**Issue by gfronza** [clappr/clappr#750]
I noticed that using the HLS playback, the event PLAYBACK_LEVELS_AVAILABLE gets triggered repeatedly (non-stop), causing the level-selector plugin to reinitialize and re-render. I believe the plugins should only trigger this event when the levels actually changed, what you guys think? RTMP plugin works that way.

We could check on level-selector plugin if the levels changed every time the callback of PLAYBACK_LEVELS_AVAILABLE gets called, but it doesn't seem right to me.

**Comment by NicholasAsimov** [comment]
Would you like a PR for this? I fixed it, but used an outside dependency (lodash.isequal) to compare levels.

**Comment by leandromoreira** [comment]
@NicholasAsimov @thiagopnts is working hard to remove external dependencies but we're always happy to merge PRs 😄
