### ISSUE TITLE
HLS nginx live stream not working on Chrome

### ISSUE THREAD

**Issue by canhlinh** [clappr/clappr#752]
Chrome version : Version 47.0.2526.106 (64-bit) Ubunt 14.04 can not play HLS live with nginx hls module.
Firefox is ok.
![screenshot from 2015-12-25 23 13 46](https://cloud.githubusercontent.com/assets/2246996/12003692/2e96c620-ab5d-11e5-82b4-653ef4b0eb64.png)

**Comment by leandromoreira** [comment]
@canhlinh we're using it with no further problem, can you test with another hls stream? also is there any problems popping up on console?

**Comment by canhlinh** [comment]
@leandromoreira  Thank for reply. I will be test it again, report test result as soon as possible.

**Comment by canhlinh** [comment]
I tested it againt. It's work well. Thanks.
