### ISSUE TITLE
HLS freeze issue in Chrome

### ISSUE THREAD

**Issue by croepha** [clappr/clappr#757]
This is my test code (that runs on cdn.clappr.io):

```
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'https://s3.amazonaws.com/tng-local-prod-6/tests/269/PL-HLSv3.m3u8',
  baseUrl: '/latest',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

On Chrome it freezes at every 15 second interval.

It works in Safari and Firefox.  There is probably something different about this particular video, not sure what it is, but the combination of this video, with Chrome seem to not work.

Any ideas?

**Comment by leandromoreira** [comment]
Hi @croepha I think this might be related to your hls stream, just try with this stream instead.

```
"http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8"
```

Apple has a tool to validate hls stream, try to validate yours.
https://developer.apple.com/library/ios/technotes/tn2235/_index.html

**Comment by croepha** [comment]
I ran the apple validation tool on both streams:

My video: 
Error: Measured peak bitrate compared to master playlist declared value exceeds error tolerance
--> Detail:  Measured: 3054.41 kb/s, Master playlist: 3469.00 kb/s, Error: 13.57%
--> Source:  https://s3.amazonaws.com/tng-local-prod-6/tests/269/PL-HLSv3.m3u8
--> Compare: tng-v4-HLS-auto-540-.m3u8

Error: Interlaced video detected
--> Detail:  Track ID 551
--> Source:  tng-v4-HLS-auto-720-.m3u8 - tng-v4-HLS-auto-720-00000.ts

--> Detail:  Track ID 551
--> Source:  tng-v4-HLS-auto-720-.m3u8 - tng-v4-HLS-auto-720-00001.ts
 ...

Warning: #EXT-X-ALLOW-CACHE has been deprecated
--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  tng-v4-HLS-auto-720-.m3u8
...


And the big buck bunny video:
Error: Measured peak bitrate compared to master playlist declared value exceeds error tolerance
--> Detail:  Measured: 490.30 kb/s, Master playlist: 246.44 kb/s, Error: 49.74%
--> Source:  http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8
--> Compare: url_2/193039199_mp4_h264_aac_ld_7.m3u8
...
Error: Format change without discontinuity tag detected
--> Detail:  (null)
--> Source:  url_2/193039199_mp4_h264_aac_ld_7.m3u8 - url_566/193039199_mp4_h264_aac_ld_7.ts
...

Error: Different target durations detected
--> Detail:  Target duration: 11 vs Target duration: 10
--> Source:  url_4/193039199_mp4_h264_aac_7.m3u8
--> Compare: url_2/193039199_mp4_h264_aac_ld_7.m3u8
...

My video actually had less validation issues ...

The reference stream url plays perfectly in Chrome. its got to be something with my specific video.  (although my video plays fine in Safari and Firefox)

I am going to try to see if I can re-transcode to see if there was some sort of fluke problem, also, i might try to force de-interlacing to see if that fixes it...

We can close it if you don't think its a bug, I don't know enough about how the player works to troubleshoot it.  Do you know where in the code I would start looking to try to see where it might be hanging up?

**Comment by croepha** [comment]
Actually im having the same issue at the hls.js demo page, im closing here and going to try on hls.js, Thanks for the help troubleshooting

**Comment by leandromoreira** [comment]
@croepha one thing you can do is to force clappr to use Flashls instead.
