### ISSUE TITLE
How to forbid fullscreen playing on safari？

### ISSUE THREAD

**Issue by zczcyc0201** [clappr/clappr#758]
Hi,When I click play button in safari,the play window is auto fullscreen,how to fobid that?
thanks,I love clapps.

**Comment by leandromoreira** [comment]
@zczcyc0201 did you try [play at demo page](http://cdn.clappr.io/)? For me it's not going to fullscreen.

**Comment by towerz** [comment]
@leandromoreira it seems like @zczcyc0201 is having this problem on iOS, more specifically on an iPhone. Is that correct?

If this is the case, there's nothing we can do, the Safari browser on iOS plays videos in fullscreen automatically, with no API to prevent this behavior. Some custom browsers which use UIWebView or WKWebView could allow inline playback, but in Safari there's no way to do it. The iPad version of Safari allows inline playback normally, this behavior is specific to the iPhone.

**Comment by sjlu** [comment]
#572 

On the other hand, for apps that are inline and/or part of a UIWebView, can we have an option to append `webkit-playsinline="true"` to the video?

**Comment by me-vlad** [comment]
Option for `webkit-playsinline `  looks useful

Also (not related to this issue) may ne we can add parameter to the video tag that allows AirPlay for older iOS devices
`x-webkit-airplay="allow"`
https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/AirPlayGuide/OptingInorOutofAirPlay/OptingInorOutofAirPlay.html

**Comment by sjlu** [comment]
ping @towerz 

With support from iOS Safari 10, can we add this in?

https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html

**Comment by towerz** [comment]
@me-vlad @sjlu about AirPlay, I'm developing this as a [standalone plugin](https://github.com/towerz/clappr-airplay-plugin). I'm still lacking an icon for enabling this, but it's nearly done.

**Comment by rgaufman** [comment]
When I open http://cdn.clappr.io/ and press play on my iPhone XS running iOS12.1.2 it is switching to the name full screen player :( - any ideas?
