### ISSUE TITLE
What is the proper way to force FlasHLS?

### ISSUE THREAD

**Issue by croepha** [clappr/clappr#762]
I have tried this:
```
window.player = new Clappr.Player({
    ....
    plugins: {
        playback: [Clappr.Flash]
    }
});
```

and this:

```
window.player = new Clappr.Player({
    ....
    plugins: {
        playback: [Clappr.FlasHLS]
    }
});
```

But I still seem to be using the HTML5 player, (I right click the video and it doesn't say anything about flash)
Thanks, sorry if i'm missing something obvious

**Comment by leandromoreira** [comment]
@croepha 

Your second snippet should work, although I recommend you to use the later form:

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  plugins: [Clappr.FlasHLS],
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

```

Also, we introduce divs in from of the player so the right way to check if you're using Flash is not by right clicking. :) You can either look for an tag <object on dom or:

```javascript
console.log(player.core.getCurrentPlayback().name);  // it should print the playback being used
```

**Comment by croepha** [comment]
Ok, Thanks!

**Comment by msinghms001** [comment]
flasHLS plugin (with aes-128 encrypted hls ) working great on PC but not working on mobile (i tested on android) . Please help on this!

**Comment by towerz** [comment]
@msinghms001 Flash is not supported on mobile, so FlasHLS shouldn't work. 

If you want to use some implementation other than the default HTML5Video, you could use the HLS playback (which uses hls.js). Please note that it will only work on MSE capable browsers.
