### ISSUE TITLE
Mediacontrol color for buttons does not change poster-icon color

### ISSUE THREAD

**Issue by hounvs** [clappr/clappr#763]
Large play button (poster-icon) is white even though button has a color set to it. Just seems unintuitive that the first and largest button doesn't match the rest

<img width="492" alt="button color" src="https://cloud.githubusercontent.com/assets/6434904/12307382/eb236006-ba0c-11e5-8875-d87f6fdd3e2a.PNG">

This seems intentional but should be an easy change to allow more options for the users.

It is explicitly set to "color: white;" and instead could use the entered value.

Very similar to clappr#224

**Comment by flavioribeiro** [comment]
yep, I'm +1 for this. Mind sending a PR, @hounvs ?
