### ISSUE TITLE
Uncaught TypeError: this.hls.attachMedia is not a function

### ISSUE THREAD

**Issue by 569934390** [clappr/clappr#775]
the line 'this.hls.attachMedia(this.el)' in the file hls.js report the error as title

**Comment by leandromoreira** [comment]
@569934390 how can we reproduce this error? what OS/Browser/Stream/Steps?

**Comment by 569934390** [comment]
@leandromoreira  thank you !
I solve it by myself .
it's because i use the old version of hls.js npm modules,after upgrade to the newest version,it's ok now!

**Comment by leandromoreira** [comment]
thanks
