### ISSUE TITLE
Accept poster url as querystring parameter

### ISSUE THREAD

**Issue by deedos** [clappr/clappr#776]
Related to #604 but for poster image parameter. Would that be possible ?
thanks

**Comment by joaopaulovieira** [comment]
If you refer to this page https://github.com/clappr/clappr/blob/master/public/index.html, it's already possible to pass the URL via querystring.

* Go to `http://clappr.io/demo/` with the poster param on the URL: http://clappr.io/demo/?src=http://clappr.io/highline.mp4&poster=http://clappr.io/poster.png
* Run the code below on editor:
```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: urlParams.src,
  poster: urlParams.poster,
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

**Comment by leandromoreira** [comment]
@joaopaulovieira I tried but I couldn't ;/ the source has changed but the poster remains the same.

http://clappr.io/demo/?src=https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8&poster=https://icdn9.digitaltrends.com/image/donkey-kong-country-tropical-freeze-screenshot-7-800x450-c.jpg?ver=1

**Comment by towerz** [comment]
@leandromoreira apparently the demo page hasn't been updated in a long time. I just deployed it, so it's now fixed. Thanks!
