### ISSUE TITLE
CONTAINER_PLAY event : Called at the end of a content

### ISSUE THREAD

**Issue by cacciato** [clappr/clappr#782]
Hi,
I'm using clappr to read some HLS streams.

At the end of a stream, the event CONTAINER_PLAY is called. Is it a normal behaviour ?

**Comment by leandromoreira** [comment]
Hi @cacciato can you set log level to debug (go to console -> `Clappr.Log.setLevel(0)` before you start to play) and copy here the final part where `CONTAINER_PLAY` is called alongside with a couple of log line.
