### ISSUE TITLE
A PIP - Picture in Picture plugin

### ISSUE THREAD

**Issue by LagaV** [clappr/clappr#791]
Excuse my ignorance, but I'm looking for any kind of documentation on how to implement the PIP functionality. For know I can find some closed issues here, but nothing more.

Thanks, 
LagaV

**Comment by leandromoreira** [comment]
@LagaV you could start by learning the basics behind [clappr's architecture](https://github.com/clappr/clappr/wiki/Architecture) and then jump into the [building your first plugin](https://github.com/clappr/clappr/wiki/Our-first-plugin) and finally get yourself [inspired by existent plugins](https://github.com/clappr/clappr#external-plugins).

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
