### ISSUE TITLE
Where to find "Channels" plugin ?

### ISSUE THREAD

**Issue by LagaV** [clappr/clappr#792]
Sorry for asking here, but I can't find any other location where to file questions.

I'm currently searching for a multi-stream (channel) solution.
 
* I understand that there is a destinction between the "source" and "sources" option, but can't find any way how to display / access multiple "sources".
* I can find a plugin to [clappr-channels](https://github.com/irongomme/clappr-channels), but this plugin seems to be no longer updated. Using it with 0.2.30 get me a "Cannot find module 'ui_core_plugin'"
* In this [post](http://leandromoreira.com.br/2015/04/26/fifa-2014-world-cup-live-stream-architecture/) I see, that there seems to be something in the direction of "channels" already available. ![Image of "Channels" solution](http://blog.flavioribeiro.com/content/images/2014/Nov/06_player_multicamera-1.jpg)

So where should I look to understand how to implement a "Channels" selection into a player.

Thanks for your support
LagaV

**Comment by leandromoreira** [comment]
@LagaV can I close this one since this is the same as https://github.com/clappr/clappr/issues/791 ?

This picture shows a PiP that we (globo.com) did internally.

**Comment by LagaV** [comment]
@leandromoreira, the image is the same source of inspiration, but my question is different.

This question is about the "channel" selector on the left side.

Probably I need to phrase my question differently: I'm struggiling to understand what to do with the "sources" option. How do I select a source out of a list of provided sources? 

This somewhat relates to the discussion [Set default behavior for multiple sources](https://github.com/clappr/clappr/issues/550)

**Comment by leandromoreira** [comment]
I see, well, you could add an option for your plugin:

```javascript
new Clappr.Player({ channels: [ {thumb: "x", source: "y"}, ...]  }
```

And then based on click you could switch the `container` :). Now about the default behavior for multiple sources it works like [fallback options](https://github.com/clappr/clappr/commit/155bbcc458d4f8cbaa4f57d755d05e6b3e636e27).

**Comment by flavioribeiro** [comment]
A similar plugin:

https://github.com/irongomme/clappr-channels
