### ISSUE TITLE
can you please release a new version with the updated Hls.js?

### ISSUE THREAD

**Issue by shaharmor** [clappr/clappr#796]
We're stuck with the audio sync bug until you do

**Comment by leandromoreira** [comment]
@shaharmor we just released one last 8 days but we're preparing a new one too.

**Comment by shaharmor** [comment]
yeah i know about the one 8 days ago, but yesterday you fixed a bug by updating hls.js, which i need :)

**Comment by leandromoreira** [comment]
It'd be nice if we update also the flahls pllugin @me-vlad do you have any pr for this?

**Comment by me-vlad** [comment]
@leandromoreira sure
https://github.com/clappr/clappr/pull/797

**Comment by leandromoreira** [comment]
Thanks @me-vlad  :)

**Comment by leandromoreira** [comment]
Closed since https://github.com/clappr/clappr/releases/tag/0.2.31
