### ISSUE TITLE
Autoplay isn't working with 0.2.31 and HLS

### ISSUE THREAD

**Issue by shaharmor** [clappr/clappr#799]
Title says it all :)

**Comment by me-vlad** [comment]
I can confirm this issue for hlsjs playback

**Comment by me-vlad** [comment]
Same issue with dash_shaka_playback 
https://github.com/clappr/dash-shaka-playback/issues/2

**Comment by chakree30584** [comment]
0.2.31 seem to make  autoplay not working for me too.

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/pull/803
