### ISSUE TITLE
Issue with discontinuity hls on desktop.

### ISSUE THREAD

**Issue by GeorgySerga** [clappr/clappr#802]
The same video plays nicely on Android. Chrome and Firefox freeze, but play the stream for 6 seconds. Chrome shows no errors in the console, but I don't know if this log is quite normal (one file is downloaded two times):
```
XHR finished loading: GET "http://10.1.0.119/vod/3/d.m3u8?expires=2000000000&md5=D0DO62JT3n6CDprCKBZuHQ".

XHR finished loading: GET "http://10.1.0.119/vod/3/d.m3u8?expires=2000000000&md5=D0DO62JT3n6CDprCKBZuHQ".

XHR finished loading: GET "http://10.1.0.119/vod/3/playlist229.ts?expires=2000000000&md5=J1qT-1CPyx-LbJAdN3neUQ".

XHR finished loading: GET "http://10.1.0.119/vod/3/playlist219.ts?expires=2000000000&md5=g2LTqPEaRuAQoAD9lDVpVg".

XHR finished loading: GET "http://10.1.0.119/vod/3/playlist229.ts?expires=2000000000&md5=J1qT-1CPyx-LbJAdN3neUQ".

XHR finished loading: GET "http://10.1.0.119/vod/3/playlist219.ts?expires=2000000000&md5=g2LTqPEaRuAQoAD9lDVpVg".
```
Firefox's console:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create clappr.js:2007:416

ReferenceError: event is not defined
 clappr.js:19149:16
```
Also I can skip this fragment and play video further (firefox wouldn't show the error too).

I'm on Ubuntu 14.04, clappr 0.2.31.

**Comment by GeorgySerga** [comment]
Found info about extra logging with `Clappr.Log.setLevel(0)`. Here are the logs. I must admit that it seems like the playback stops on different fragments, this time chrome played the stream till 0:17.

[chrome_firefox_logs.zip](https://github.com/clappr/clappr/files/105188/chrome_firefox_logs.zip)

**Comment by leandromoreira** [comment]
@GeorgySerga maybe this is something related to your stream ([the generation](https://developer.apple.com/library/ios/technotes/tn2224/_index.html#//apple_ref/doc/uid/DTS40009745-CH1-BITRATERECOMMENDATIONS) or other issue) , try this:

* With this stream `http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8` ?
* At [hls.js demo page](http://dailymotion.github.io/hls.js/demo/) ?
* Did you try chrome on other platform? (like OS or Windows)
* Using FlasHLS ? (a.k.a `plugins: [Clappr.FlasHLS]`)

**Comment by GeorgySerga** [comment]
Well, 
- The `http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8` is working.
- I can't play my media right at the demo page (CORs thing), but I have cloned their repo and - my video freezes. Right at the same fragments. Chrome demo shows `Frag Loop Loading Error,cannot recover, last media error recovery failed ...` Firefox console has two errors at the end: 
```
[error] > cannot recover fragLoopLoadingError error hls.js:6846:7
ReferenceError: event is not defined hls.js:692:15
```
- I've tried this stream on my Android phone. It has some lags, but plays the stream from the start till the end.
- It works with `plugins: [Clappr.FlasHLS]`. Though I must admit that the right click action doesn't show me the flash menu, console shows `INFO:FlasHLS Clappr (version: 0.4.11 - flashls: 0.4.4.18, id: o12)`. I'm confused a little. 

Thank you.

**Comment by leandromoreira** [comment]
@GeorgySerga if you still think this is not something related to your input stream and it's working under `FlasHLS` you might open an issue at [hls.js](https://github.com/dailymotion/hls.js) passing all the details there( @mangui ).

> Though I must admit that the right click action doesn't show me the flash menu, console shows

This happens because we cover the flash "stage" with an html div (a wrapper container).

**Comment by GeorgySerga** [comment]
>  if you still think this is not something related to your input stream
Well, at some point of course it's stream related, but I can play it with flashls, on my phone, in the vlc, etc, so it seems rather working )

Ok, thanks a lot for your help, one way or another, the issue is fixed with flashls. I'll open an issue at hls.js. Good luck!

**Comment by leandromoreira** [comment]
@GeorgySerga please link the new issue at hls.js here too :)

**Comment by GeorgySerga** [comment]
@leandromoreira don't understand, the link to hls.js is right above your comment, in the reference. In case it isn't displayed: daylymotion/hls.js#205 . Or maybe you did want something else...

> the same guy that did flashls did hls.js so this might be easy.

That was extremely easy :) You two answer super quickly!

**Comment by leandromoreira** [comment]
my mistake, I didn't see the link. :) @mangui is an awesome person and amazing developer.
