### ISSUE TITLE
lower edge blur on playback

### ISSUE THREAD

**Issue by ibreakstuff93** [clappr/clappr#804]
Has anyone noticed a HLS video blur at the bottom of the player?

We have this as our current clappr implementation:

    <script>
    
         var player = new Clappr.Player({
	     	    source: "",
		    autoPlay: true,
		    height: 404, width: 720,
		    parentId: "#player-wrapper",
		
	     	mediacontrol: {seekbar: "#FF0000", buttons: "#FFFFFF"},
             plugins: {
               'playback': [Clappr.FlasHLS],
	     	  'core': [LevelSelector],
          
		     	}
     	});
     </script>

      <div id="player-wrapper" class="player-wrapper"></div>

FlasHLS Clappr (version: 0.4.5 - flashls: 0.4.4.5, id: o19)

It seems to produce these visible effects, when viewed in a desktop browser (Chrome, Firefox etc)

![issue](https://cloud.githubusercontent.com/assets/16917874/12613794/d839d14a-c4f3-11e5-9901-f9595ec52a99.png)

Has this been seen before?

NOTE: The streams themselves playback without blur in other players such as VLC, mplayer, videojs and natively on apple devices so am happy to rule that out its something to do with the vdeo source.

Thanks in advance

**Comment by me-vlad** [comment]
@ibreakstuff93 your clappr varsion looks very outdated.
Can you reproduce this issue on recent clappr (f.e. on http://cdn.clappr.io/)?

**Comment by ibreakstuff93** [comment]
You're right, it's better with the CDN version. I'll update my local copy :+1: Thanks!

**Comment by leandromoreira** [comment]
if the issue is still happening I'll be happy to reopen.
