### ISSUE TITLE
pass config to hls.js 

### ISSUE THREAD

**Issue by ghaith-bash-imam** [clappr/clappr#806]
is there any way to pass config to hls.js  such as 

 xhrSetup: function(xhr, url) {
    xhr.withCredentials = true; // do send cookies
  }

i cant play my VOD+token without this config 

ref from hls.js https://github.com/dailymotion/hls.js/issues/209

**Comment by flavioribeiro** [comment]
yep, pass `hlsjsConfig` object on embed parameters: https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L43
