### ISSUE TITLE
Fullscreen back button event on Android.

### ISSUE THREAD

**Issue by GeorgySerga** [clappr/clappr#809]
Is there any event for `backbutton` when exit full screen on Android?
`Clappr.Events.CONTAINER_FULLSCREEN` doesn't fire this way. Thank you.

**Comment by GeorgySerga** [comment]
As a hotfix I started to watch `fullscreen` class with `setInterval()`. Checked the clappr.js file and it looks like there is method `enableResizeObserver` with `setInterval()` too, so no sign of the proper listener here too.

**Comment by flavioribeiro** [comment]
hey @GeorgySerga I think it makes sense to have a EXIT_FULLSCREEN event, do you mind submitting a PR with it?

**Comment by GeorgySerga** [comment]
Sure @flavioribeiro , I wanna try. I'll think of the way to do it and write my thoughts/questions here, or submit a PR itself to judge. Thank you.

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
