### ISSUE TITLE
Automatic HLS recover

### ISSUE THREAD

**Issue by cowai** [clappr/clappr#813]
Hi,
There should be an automatic recover media option to Clappr.
There is too many things that can go wrong with hls.js and forcing a recover when the browser wont play a fragment would temporarily solve many issues until hls.js is 100% ready.

Any thoughts?

**Comment by leandromoreira** [comment]
@cowai aren't we able to instrument that by only using its [config](https://github.com/dailymotion/hls.js/blob/master/API.md#fine-tuning) like `fragLoadingMaxRetry`?

**Comment by cowai** [comment]
@leandromoreira 
On the demo page of hls.js there is a Auto Media Recover option which triggers hls.RecoverMediaError().
I dont think fragLoadingMaxRetry covers every corner case. RecoverMediaError() is kind of a last resort for all types of errors.

**Comment by leandromoreira** [comment]
:) I get it! @cowai it makes sense

**Comment by leandromoreira** [comment]
http://dailymotion.github.io/hls.js/demo/

**Comment by me-vlad** [comment]
@cowai , @leandromoreira  good idea, I think it will be nice to get recovery option idependent from playback type (hlsjs, flashls, dash, etc)

**Comment by shaharmor** [comment]
The way its done in hls.js is:

1. listen to the error even on the video tag:

```javascript
videotag.addEventListener('error', function(e) {
    var mediaError = e.currentTarget.error;

    if (mediaError.code === mediaError.MEDIA_ERR_DECODE) {
        recover();
    }
});
```

And also to hlsjs errors:

```javascript
hls.on(Hls.Events.ERROR, function(event, data) {
    if (data.fatal) {
        switch (data.type) {
            case Hls.ErrorTypes.NETWORK_ERROR:
                hls.startLoad();
                break;
            case Hls.ErrorTypes.MEDIA_ERROR:
                recover();
                break;
            default:
                // cannot recover
                break;
        }
    }
});
```

where the `recover()` function is:

```javascript
function recover() {
    if (!_recoveredDecodingError) {
        _recoveredDecodingError = true;
        hls.recoverMediaError();
    } else if (!_recoveredAudioCodecError) {
        _recoveredAudioCodecError = true;
        hls.swapAudioCodec();
        hls.recoverMediaError();
    } else {
        // failed recovery
    }
}
```

and `_recoveredDecodingError` & `_recoveredAudioCodecError` are instance members.

Any chance to get this implemented?

**Comment by ronag** [comment]
@shaharmor: Where did you find the code you posted? Somewhere the `_recoveredDecodingError` and `_recoveredAudioCodecError` needs to be reset when it should try again or if it successfully recovered...

**Comment by shaharmor** [comment]
You can look at an example here: https://github.com/dailymotion/hls.js/blob/master/demo/index.html#L623-L642

**Comment by paunadeu** [comment]
Why this ticket is clossed? Not interesting? Implemented?

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/issues/890 @paunadeu
