### ISSUE TITLE
Is there a way to query which HLS segment is being played at the moment?

### ISSUE THREAD

**Issue by arikkrol1** [clappr/clappr#819]
Or subscribe to an event (something like Hls.js event -  Hls.Events.FRAG_CHANGED)?

**Comment by flavioribeiro** [comment]
Is there a not common way by binding to hls events. I was able to catch segments by doing:
```js
var onHlsFragChanged = function(e, data) { console.log(data.frag.url) };
player.core.getCurrentPlayback().hls.on('hlsFragChanged', onHlsFragChanged);
```
I agree it's weird to do that, we should expose `Hls.events` consts to make the binding easier.

**Comment by arikkrol1** [comment]
Thanks. 
This works.

**Comment by mattwa1sh** [comment]
Hi-- 

I'm not seeing this work for me. Very simple setup:

http://admin.blivenyc.com/public/examples/clappr_test.html

for which the relevant code is 
```
var playerElement = document.getElementById("player-wrapper");
			
			var player = new Clappr.Player({
			  source: 'http://admin.blivenyc.com/clip-conversion/v3-blive-public-us-east-1/video/001600-005788-pr_9ki4/desktop-playlist.m3u8',
			  poster: 'http://clappr.io/poster.png',
			  mute: true,
			  height: 360,
			  width: 640
			});
			
			player.attachTo(playerElement);
			
			var onHlsFragChanged = function(e, data) { console.log(data.frag.url) };
			player.core.getCurrentPlayback().hls.on('hlsFragChanged', onHlsFragChanged);
```

Error is : 

TypeError: Cannot read property 'on' of undefined

Any thoughts?

Thanks,
Matt

**Comment by bikegriffith** [comment]
@mattwa1sh It's `player.core.getCurrentPlayback()._hls` rather than `player.core.getCurrentPlayback().hls`

**Comment by mattwa1sh** [comment]
Yes! Thanks I just noticed that error. While we're on the topic, does anyone know how to get the current position of that play head *within* the segment? Like, we're 4.2 second into segment-0432.ts?

**Comment by bikegriffith** [comment]
@mattwa1sh Yes, you can do that, but it's a little tricky.  You have to monitor `hlsLevelLoaded` and wait for the 1st firing of that event (2nd mutates start to be startPTS) and then keep track of the level fragments.  Then, if you know video.currentTime, you can loop through each fragment to find the one containing currentTime (based on start+duration) and compute the currentTime - start to get the offset.

**Comment by bikegriffith** [comment]
And of course remember that it only works for hls.js playback (e.g. not native video in safari)

**Comment by mattwa1sh** [comment]
Right. Okay, I think I have a similar approach, but it takes into account a certain timing-related wonkiness I've noticed. On frag change I am recording the playheadTime along with data associated with the fragment, like so:
```
SOURCE: http://admin.blivenyc.com/clip-conversion/v3-blive-public-us-east-1/video/001600-005788-pr_9ki4/desktop-playlist.m3u8
5788:208 SEGMENT : https://video.blivenyc.com/001600-005788-pr_9ki4/file-4628k-00001.ts
5788:209 SEG START : 8.017733333333334
5788:210 PLAYHEAD : 7.653262
5788:208 SEGMENT : https://video.blivenyc.com/001600-005788-pr_9ki4/file-4628k-00002.ts
5788:209 SEG START : 16.0054
5788:210 PLAYHEAD : 15.649625
5788:208 SEGMENT : https://video.blivenyc.com/001600-005788-pr_9ki4/file-4628k-00003.ts
5788:209 SEG START : 24.016277777777777
5788:210 PLAYHEAD : 23.653374
```
Now, the first crazy thing is that the playhead time is *ahead* of the segment start recorded in the fragment data. If I fire the event on frag changed, and map the playhead to segment start differential, I can query the playhead time later in the fragment and know my "offset". I think this will give me what I want just by using the fragment data and playhead time.

M

**Comment by mattwa1sh** [comment]
So in this case, if the playhead is 27,  position in fragment would be:

27 - 24.016 - (offset = -.34) = 3.324

I think thats right.... Possibly.
