### ISSUE TITLE
Firefox raises InvalidStateError when trying to destroy player

### ISSUE THREAD

**Issue by bikegriffith** [clappr/clappr#826]
See jsfiddle here:
https://jsfiddle.net/d4hwuzwm/
(this loads a video, waits for it to start playing, then calls `destroy` 5 seconds later)

Calling `destroy` on a player instance in Firefox raises `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`

This works fine in Chrome/Safari.

**Comment by bikegriffith** [comment]
It looks like if you wait for the playback to stop, it won't raise the exception, but unfortunately, I don't have that luxury because I need to destroy the player immediately.

```
      console.log('Attempting to destroy player...');
      player.stop();
      player.core.getCurrentPlayback().once('playback:stop', function() {
 	     player.destroy();
      });
```

**Comment by flavioribeiro** [comment]
reproduced here
