### ISSUE TITLE
How to remove mediaControlBar?

### ISSUE THREAD

**Issue by sc0rp10** [clappr/clappr#827]
Hello!
Sorry for possible question duplicate, but i coulndt find a similar questions.
How can I completely disable all mediaControlBar and see only player?
May I do it only with config?
Thanks!

**Comment by me-vlad** [comment]
@sc0rp10 chromeless: true

**Comment by sc0rp10** [comment]
ohh, sorry for stupid question. i tried `chromeless: true`, but in my test setup auotoplay has been disabled  and without autoplay chromeless Clappr won't play =/

**Comment by leandromoreira** [comment]
@sc0rp10 autoPlay should work with chromless unless you're in a mobile, I tested at http://cdn.clappr.io

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  autoPlay: true,
  chromeless: true,
  source: 'http://clappr.io/highline.mp4',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

```

**Comment by Det20** [comment]
What can i do in mobile mode? AutoStart doesn't work. If i set Chromeless to true the Player never start. Set useHardwareVideoDecoder to true or false doesn't change this. What can i do remove Controlbar?

**Comment by leandromoreira** [comment]
@Det20 

you can't do anything for this particular "issue" on [mobile](https://www.aerserv.com/why-does-video-autoplay-on-mobile-devices-not-work/) you can't use `autoStart` neither `player.play()` on your js **it must be an user gesture**.  Unless you put a button or something then on the `click` event you trigger `player.play()`
