### ISSUE TITLE
DRM'ed HLS - LiveStream - Pulls 1st .ts File but not the rest.

### ISSUE THREAD

**Issue by PreDeToR** [clappr/clappr#834]
Browser: Firefox 43.0.4
OS: Ubuntu 15.10
Clappr Version: https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

Steps to reproduce:
http://smartvideo.cointelvas.co.za/test_live.cgi    (This creates a session what is used to decode the files)
Click Play on the Sole Player.
Then looking at the network logs.
you pull the m3u8 files.
get the drm key correctly and successfully.
pull the 1st .ts from the list
and then just loop calling the m3u8 file as per attached image.

I have a normal VOD working without any issues using the exact same process, its just the livestreaming that seems to complain.

Any help will be greatly appreciated.

![snapshot3](https://cloud.githubusercontent.com/assets/17157144/12943223/807227e6-cfe8-11e5-814e-00c321d812cd.png)

**Comment by leandromoreira** [comment]
@PreDeToR can you [test your stream over here](flashls.org/latest/examples/chromeless/)? I think [FlasHLS](https://github.com/mangui/flashls) (the playback we use) doesn't support DRM.

**Comment by PreDeToR** [comment]
Hi Leondromoreira

I tried is on the above player and in the console I got the following errors.
Don't know if this helps, I had the DRM playback working on a single machine, but moving it to my live architecture is where the problem seems to happen, since the servers are split.

![snapshot4](https://cloud.githubusercontent.com/assets/17157144/12948742/b0c4d29e-d00c-11e5-9722-9230f07c3b8a.png)

**Comment by PreDeToR** [comment]
also, I can play VOD & Live Stream with DRM on my test system

**Comment by towerz** [comment]
@leandromoreira is right. The FlasHLS playback that we use for playing HLS does not include DRM support at all. It is based on the chromeless player, which is simply a barebones video object fed with data from FlasHLS HLS implementation.

If you want DRM support for HLS, you should use a OSMF based playback. Perhaps you could use the FlasHLS OSMF plugin with some OSMF based playback to make this work. AFAIK there's no Clappr playback implemented using this, so you would need to implement it yourself.

**Comment by PreDeToR** [comment]
Hi Guys

I have disabled the DRM on the live stream, tested the the LIVE Stream using ffplay and vlc and they both work, yet the player is still causing issues, with the live stream.

Please have a look at this url:
http://danievtest3.dedicated.co.za/test.html

**Comment by PreDeToR** [comment]
Hi Guys

I think I have narrowed down the problem. On the same machine (Ubuntu 15.10 (x86_64; KDE) ) my Opera(30.0.1835.125 ) plays fine yet Firefox(43.0.4 Mozilla Firefox for Ubuntu Cononical - 1.0)  does not.

**Comment by PreDeToR** [comment]
Hi Guys

Any idea, live streaming hls without DRM does not seem to work on FireFox or IE, yet opera seems to work fine.

**Comment by leandromoreira** [comment]
> I have disabled the DRM on the live stream, tested the the LIVE Stream using ffplay and vlc and they both work, yet the player is still causing issues, with the live stream.

What issues? can you share the log?

**Comment by PreDeToR** [comment]
@leandromoreira 

It just seems to loop calling files but not displaying anything

I am using ffmpeg to generate the hls files, I even checked them using Apples mediastreamvalidator and the file formats are correct.

![snapshot5](https://cloud.githubusercontent.com/assets/17157144/13007044/fa1a6262-d195-11e5-9c45-b9c7f1fc8d0a.png)
![snapshot6](https://cloud.githubusercontent.com/assets/17157144/13007045/fa1dfb98-d195-11e5-9566-0c7949384e16.png)

**Comment by leandromoreira** [comment]
@PreDeToR can you try to run the same stream [here](http://www.flashls.org/latest/examples/chromeless/)? if the issue still persists I think we'll need to create [an issue at mangui/flashls](https://github.com/mangui/flashls).

**Comment by PreDeToR** [comment]
@leandromoreira I made a couple of changes to my livestream formats and durations and its working fine without DRM now.

Is there any way I can support DRM for livestreams ? I have DRM working with VOD's already.

**Comment by leandromoreira** [comment]
thanks @PreDeToR :)
