### ISSUE TITLE
How to listen to events?

### ISSUE THREAD

**Issue by matthias-k** [clappr/clappr#848]
Hi,

I am trying to figure out how I can listen to events. I am interested in most of the usual HTML5-`<video>` events like `timeUpdate` etc. However I was not able to bind to any events for clappr. Also I didn't find anything in the documentation on this (except for the plugin-example, but is writing a custom plugin the only way to listen to events?).

Thankyou for your help!

**Comment by flavioribeiro** [comment]
Hey @matthias-k if you want to listen to timeupdate events, just bind to it:

```
player.on(Clappr.Events.PLAYER_TIMEUPDATE, function(e) { console.log("time update", e); });
Player {uniqueId: "o1", options: Object, coreFactory: CoreFactory, playerInfo: PlayerInfo, _loader: Loader…}
VM790:2 time update Object {current: 4.289638, total: 36.44}
VM790:2 time update Object {current: 4.788395, total: 36.44}
VM790:2 time update Object {current: 5.038311, total: 36.44}
VM790:2 time update Object {current: 5.288214, total: 36.44}
VM790:2 time update Object {current: 5.788668, total: 36.44}
VM790:2 time update Object {current: 6.043675, total: 36.44}
VM790:2 time update Object {current: 6.481978, total: 36.44}
```

You can find the full list of events [here](https://github.com/clappr/clappr/blob/master/src/base/events.js#L204).
