### ISSUE TITLE
HLS video seek has no effect in Safari

### ISSUE THREAD

**Issue by cmagnuson** [clappr/clappr#854]
**Browser**: Safari 9.0.3

**OS**: Mac OS 10.9.5

**Clappr Version**: 2.3.5

**Steps to reproduce**:
I use the following code to load an HLS stream and seek to a point partway in the stream once I'm able to.  This seems to work fine in other browsers and devices, only failing with Safari where it plays from the beginning and the player.seek() seems to have no effect.

```
var player = new Clappr.Player({
	source: "http://finishvideo.s3.amazonaws.com/sigma_top_cam_16/sigma_top_cam-playlist.m3u8", 
	baseUrl: "/js/clappr-2.3.5",
    poster: "http://finishvideo.s3.amazonaws.com/sigma_top_cam_16/sigma_top_cam-00137.png",
    parentId: "#player0",
    maxBufferLength:16,
     hlsjsConfig: {
    	maxMaxBufferLength: 16
  	},
  	height:"100%",
  	width:"100%", 	
  });	

player.core.mediaControl.container.on(Clappr.Events.CONTAINER_LOADEDMETADATA, function(e) {
	console.log("ready",e);
	player.seek(120);
 });
```

However if I reference the HTML5 video element that Clappr creates and set the time it does succeed:
`$("#vid1").get(0).currentTime = 120;`

Because Safari isn't dependent on hls.js to handle the video, is the seek() not being passed on to Safari's native player?

**Comment by cmagnuson** [comment]
Sorry, after more testing this may be an issue with the Safari video player.  I see that setting currentTime = x on it only works some of the time, and it looks like Clappr is using the same method to update the time.

I'm not sure why Safari isn't respecting the seek, but might not be a Clappr/HLS issue after all.

**Comment by leandromoreira** [comment]
Thanks @cmagnuson
