### ISSUE TITLE
first player.seek() call does not work on ios 9

### ISSUE THREAD

**Issue by lordcris** [clappr/clappr#860]
Hello guys,
I'm trying to control my clapper player using javascript.
When I call

```
 player.seek(100);
 player.play();
```

everything works as expected on PC and Android, 
but on IOS (chrome and safari) the player starts from the beginning (not from the 100th second). 
If I pause and execute the function again - it works.
Am I doing something wrong?
Thanks

**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)

Safari and Chrome (latest available)
**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
ios 9.2.1

**Clappr Version**: 0.2.25
latest

**Comment by lordcris** [comment]
Here is my test url:
http://goo.gl/94CGqv

**Comment by leandromoreira** [comment]
@lordcris it's working fine, I tested with:

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  autoPlay:true
});

player.attachTo(playerElement);

setTimeout(function(){player.seek(25)},4000)
```

Are you still facing this issue?

**Comment by lordcris** [comment]
Yes I do.
It works with mp4 files, but it doesn't with m3u8 (hls stream)

**Comment by leandromoreira** [comment]
@lordcris I just tested at http://cdn.clappr.io/ with hls and it worked too:

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  autoPlay:true
});

player.attachTo(playerElement);

setTimeout(function(){player.seek(25)},6000)
```

**Comment by lordcris** [comment]
Are you testing on an Iphone?

go here:
http://testing.atanassov.net/

click one of the buttons on the bottom ex "page 1"
it starts playing frome sec 0 instead from 15.
if you exit the video and press it again it goes to 15.
but the first time it always start from 0.

**Comment by leandromoreira** [comment]
sorry @lordcris I tested on desktop.

**Comment by towerz** [comment]
@leandromoreira AFAIK there's no parameter for setting a startup time, but there's a parameter called `autoSeekFromUrl` which enables parsing the query string for the parameter `t` you mentioned.

**Comment by lordcris** [comment]
can I use "autoSeekFromUrl" for different times, without reloading the page?
I'm using player.seek(X) to create time markers to different points in the video.
It works well on Desktop and Android, but on iOS it goes to sec 0 the first time.

**Comment by leandromoreira** [comment]
@lordcris IMO the `player.seek(x)` should work.
