### ISSUE TITLE
hls can not be played 

### ISSUE THREAD

**Issue by ghost** [clappr/clappr#868]
**Browser**: Chrome Version 47.0.2526.111 (64-bit)
**OS**:Linux  4.3.3-300.fc23.x86_64 #1 SMP Tue Jan 5 23:31:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Clappr Version**: 0.2.25

1) download http://bugger.ieparse.com:8080/app/hls/1.avi
2) convert it to ts stream with ffmpeg, I wrote the ffmpeg in a shell scrit like this:
# !/bin/sh

function ffmpeg_hlsEncode() {

IN="1.avi"
VCODEC="libx264"
WIDTH=920
HEIGHT=540
VBITRATE="500k"
FRAMES="15"
ACODEC="libfaac"
ABITRATE="128k"

ffmpeg -i $IN \
-map 0 \
-vcodec $VCODEC \
-s ${WIDTH}x${HEIGHT} \
-b:v $VBITRATE \
-r $FRAMES \
-acodec $ACODEC \
-b:a $ABITRATE \
-bsf:v "h264_mp4toannexb" \
-hls_time 30 \
-hls_list_size 0 \
-bf 0 \
-f hls \
XXXX.m3u8 
}

ffmpeg_hlsEncode

3) then set the clappr source as http://bugger.ieparse.com:8080/app/hls/XXXX.m3u8 ,the clappr only load two ts segments ,and can not play !

ps:
![selection_021](https://cloud.githubusercontent.com/assets/8401057/13656938/2ea4b152-e6a6-11e5-8fdb-4c950aa32b78.png)

**Comment by ieworks** [comment]
This issue is caused by the audio sample rate . The audio sample rate is 22050 Hz, It seems like that the video element can not support this rate. When I resample the audio as 44100 Hz or 38000 Hz , The clappr play the stream fluently.

**Comment by leandromoreira** [comment]
@ieworks hi can you try to run this here http://dailymotion.github.io/hls.js/demo/ ? it might be a restriction of hls.js

**Comment by leandromoreira** [comment]
ping @ieworks
