### ISSUE TITLE
Flashing White Square

### ISSUE THREAD

**Issue by ronag** [clappr/clappr#885]
Sometimes when changing sources for the player one can see a flashing white square.

**Comment by leandromoreira** [comment]
@ronag how are you changing sources? (through `load` or ...)

**Comment by ronag** [comment]
`load`

**Comment by leandromoreira** [comment]
@ronag I did that on cdn.clappr.io (using Chrome) with both mp4 and hls and it seems nice, [here's the example](https://sendvid.com/vbra9ay9)

**Comment by towerz** [comment]
@ronag from your code snippet I could assume you are using React. Is that right?

If so, how did you wrap the player to work inside React virtual DOM rendering? Could you share more info about this?

I'm asking this because I believe the white square you are referring to is the poster play button when it renders and perhaps the icon font is still not ready or its font-face has been removed from DOM somehow.

**Comment by ronag** [comment]
@towerz: I'm using virtual-dom widgets:

```javascript
class Player {

  constructor(state) {
    this.type = 'Widget'
    this.state = state
  }

  init() {
    const div = document.createElement('div')
    div.classList.add('video')

    this.player = new clappr.Player({
      parent: div,
      width: '100%',
      height: '100%',
      hlsMinimumDvrSize: 10,
    })
    this.player.core.$el[0].style.position = 'absolute'
    this._updatePoster()
    this._updateSource()

    return div
  }

  update(prev, el) {
    this.player = prev.player

    if (this.state.poster !== prev.state.poster) {
      this._updatePoster()
    }

    if (this.state.source !== prev.state.source) {
      this._updateSource()
    }

    return null
  }

  destroy(el) {
    this._cleanUp()
  }

  _cleanUp() {
    if (!this.player) {
      return
    }
    if (this.unbindEventListenersTimeout) {
      clearTimeout(this.unbindEventListenersTimeout)
      this.unbindEventListenersTimeout = null
    }
    this.player.load('')
    this.player.destroy()
  }

  _updatePoster() {
  }

  _updateSource() {
    this.player.load(this.state.source || '')
    this.player.play()
    this.unbindEventListenersTimeout = setTimeout(() => {
      this.player.core.mediaControl.kibo.off(['left', 'right'])
    }, 500)
  }

}
```javascript

**Comment by cowai** [comment]
I get the same thing _sometimes_ in firefox. It's the animation "bubbles" which sometimes are square. (A simple page refresh can fix it sometimes.)

**Comment by leandromoreira** [comment]
can we @clappr/core do anything?
