### ISSUE TITLE
hlsjs retry manifest get

### ISSUE THREAD

**Issue by ronag** [clappr/clappr#887]
Not sure if this is in clappr or hlsjs. But if it takes the server a long time to respond to the manifest (m3u8) request then the request gets cancelled and is never re-tried.

I would like to automatically retry the requests after a timeout. Any advice on how to achieve this?

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/issues/813

**Comment by ronag** [comment]
Closing in favour of PR.
