### ISSUE TITLE
How to disable loading animation?

### ISSUE THREAD

**Issue by ronag** [clappr/clappr#893]
How to disable loading animation?

**Comment by leandromoreira** [comment]
You can provide a spinner with no code at all, this will replace the current [spinner](https://github.com/clappr/clappr/blob/master/src/plugins/spinner_three_bounce/spinner_three_bounce.js).

```javascript
export default class NoSpinner extends UIContainerPlugin {
  get name() { return 'spinner' }
}
new Clappr.Player({ plugins: [NoSpinner]})
```
