### ISSUE TITLE
Cannot read property 'start' of undefined when playing HLS stream

### ISSUE THREAD

**Issue by juiyout** [clappr/clappr#907]
**Browser**: Chrome 49.0.2623.87 (64-bit)

**OS**: Mac OS 10.11.3

**Clappr Version**: 0.2.40

**Steps to reproduce**:
A-1. Go to http://dailymotion.github.io/hls.js/demo/

A-2. Load http://104.199.166.147:15922/cameras/56e1aff06b570587043404ef/streams/0/playlist.m3u8

A-3. The HLS stream plays correctly.

B-1. Go to cdn.clappr.io

B-2. Paste the following code
```js
var playerElement = document.getElementById("player-wrapper");
var player = new Clappr.Player({
  source: 'http://104.199.166.147:15922/cameras/56e1aff06b570587043404ef/streams/0/playlist.m3u8',
});
player.attachTo(playerElement);
```

B-3. The UI would be stuck at loading animation. After a minute or two,
`level-helper.js:61 Uncaught TypeError: Cannot read property 'start' of undefined`
would appear on console.

I will leave the stream url online as long as I can. Could someone please reproduce and see if it's just my computer that is insane.

**Comment by me-vlad** [comment]
@juiyout  I think something wrong with your stream
Try to turn on debug in clappr adding to your player config
Clappr.Log.setLevel(0);
I see in console lots of messages like 
```
GET http://104.199.166.147:15922/cameras/56e1aff06b570587043404ef/streams/0/playlist.m3u8 net::ERR_INSUFFICIENT_RESOURCES
GET http://104.199.166.147:15922/cameras/56e1aff06b570587043404ef/streams/0/playlist.m3u8 net::ERR_INSUFFICIENT_RESOURCES
GET http://104.199.166.147:15922/cameras/56e1aff06b570587043404ef/streams/0/playlist.m3u8 net::ERR_INSUFFICIENT_RESOURCES
```

While playing you stream with ffplay I see repeating messages like
```
skipping 3 segments ahead, expired from playlists
```

**Comment by juiyout** [comment]
@me-vlad 
You are right! Interestingly, hls.js ignores the occasional missing files and plays the streams through even though some gaps here and there. Wonders why clappr wouldn't replicate this behavior.

Thank you so much for giving me this pointer. Closing now.
