### ISSUE TITLE
Fullscreen event not fired on ExitFullscreen?

### ISSUE THREAD

**Issue by Marcin666** [clappr/clappr#911]
**Browser**: Firefox 45

**OS**: Win 10 x64

**Clappr Version**: 0.2.40

Player config:

```
var playerElement = document.getElementById("player");
			let player = new Clappr.Player({
			  source: 'hls/playlist.m3u8',
			  width: '728px',
			  height: '411px',
			  hideMediaControl: false,
			  autoPlay: true,
			  chromeless: true,
			  poster: 'poster.jpg',
			});
player.attachTo(playerElement);
```
Next i try to bind an event when user enters FS:

```
 var container = player.core.getCurrentContainer();
			 container.on(Clappr.Events.CONTAINER_FULLSCREEN, function() { 
				console.log('text');
			 });
```
This is fired only on EnterFullscreen.

Then i try to bind an event to get info on exit fullscreen mode:

It tried:

```
player.listenTo(player.core, Events.CORE_FULLSCREEN, function() {
				console.log('text2');
			 });
```
or many more approches from this Git - nothing get's fired when i exit fullscreen.

**Comment by towerz** [comment]
@Marcin666 actually, you should use the `PLAYER_FULLSCREEN` event. The fullscreen event on the container will be deprecated soon, and it isn't included in the docs anymore.

Try this:
```javascript
player.on(Clappr.Events.PLAYER_FULLSCREEN, function(isFullscreen) { 
  console.log('isFullscreen', isFullscreen);
});
```

**Comment by Marcin666** [comment]
Still nothing. This event is not fired at all even on going fullscreen.

**Comment by leandromoreira** [comment]
cool @Marcin666 can we close this one?
