### ISSUE TITLE
VoD stream not playing from start (iframe)

### ISSUE THREAD

**Issue by mikeevstropov** [clappr/clappr#912]
**Browser**: Chrome 49.0.2623.87 (64-bit)
**OS**: Linux Mint 17.1 x64, Win7 x64
**Clappr Version**: 0.2.38 - 0.2.40

I put my clappr to iframe with a link bar.
When i load the url from a link bar inside iframe the clappr is starts from random segment.
How to force playing from start?
<a href="http://www.zimagez.com/zimage/2016-03-3020-51-56.php">
  <img src="http://www.zimagez.com/miniature/2016-03-3020-51-56.php" />
</a>

**Comment by leandromoreira** [comment]
@mikeevstropov did you tried to use the master/head version? @towerz did solve this problem, I think.

**Comment by towerz** [comment]
@leandromoreira it was fixed in a local branch only. I'll push the fix to master.

**Comment by mikeevstropov** [comment]
@towerz Sorry, what i can do now?

**Comment by towerz** [comment]
@mikeevstropov actually this is a bug on the query string parser, which reads a timestamp like `?t=5m10s` from the query string and automatically seeks to the corresponding position.

There was a problem with some of its checks, that wouldn't limit to check only the query string portion of the url. So if your iframe url contains a string in this format, it would try to parse it as well. Another problem is that it wasn't limiting to a named parameter "t", so any parameter ending with "t" would parse as a seek string as well. I'd safely bet the player is using your "host" parameter as a seek string.

I just pushed these fixes to master. Could you please test it to see if it will fix your problem?

**Comment by mikeevstropov** [comment]
@leandromoreira @towerz Thank you all!!! I will try it now.
And yes, i have «host» parameter for query...

**Comment by leandromoreira** [comment]
please @mikeevstropov if you see it's fixed tell us or close it here :)

**Comment by mikeevstropov** [comment]
@leandromoreira Ok.

**Comment by mikeevstropov** [comment]
@leandromoreira @towerz Issue was solved =) You saved my life!!!

p.s. For build i just write "npm install" and "webpack". What happend with icons?
<a href="http://www.zimagez.com/zimage/2016-03-3102-45-16.php">
  <img src="http://www.zimagez.com/miniature/2016-03-3102-45-16.php" />
</a>

**Comment by towerz** [comment]
@mikeevstropov glad to know =]

About the icons, we moved from a icon font based solution to rendering the icons directly using SVG. There were some issues related to using icon fonts that we wanted to get rid of, such as blurry icons when using a number of browsers in Windows, with either font smoothing enabled or not. Sometimes the icons would disappear completely, requiring to perform a forced layout on the player.

I'm not sure what's wrong with the size of your icons, but perhaps you should just change the font-size style to an explicit height.

**Comment by mikeevstropov** [comment]
@towerz Ok.
But i do it right? Just download master-zip -> 'npm install' -> 'webpack'.
``` console
mike@intel ~/WEB/nodejs/github/clappr $ webpack
Hash: 831330a6526e447f3e9c
Version: webpack 1.12.14
Time: 23211ms
                               Asset       Size  Chunks             Chunk Names
a8c874b93b3d848f39a71260c57e3863.cur  326 bytes          [emitted]  
4b76590b32dab62bc95c1b7951efae78.swf     3.2 kB          [emitted]  
d218edf766218c19b416107bfb05ef0f.swf      63 kB          [emitted]  
38861cba61c66739c1452c3a71e39852.ttf    32.7 kB          [emitted]  
                           clappr.js     904 kB       0  [emitted]  main
    + 157 hidden modules

```

**Comment by towerz** [comment]
@mikeevstropov yes, you can do it that way.
