### ISSUE TITLE
Seek bar not selectable for hls on android

### ISSUE THREAD

**Issue by alouane** [clappr/clappr#918]
Is there a problem with hls streams(dvr type- 6hours of storage) when using android webview?
The progress bar is not selectable, I c'ant go back, it works well on web desktop

**Comment by leandromoreira** [comment]
@alouane we use pure video tag for android therefore if can or can not offer support for DVR.

@clappr/core 

I think hls.js (video tag + MediaSource) supports that, I'm in favor of rolling hls.js before than HtmlVideo5, what do you think?

**Comment by alouane** [comment]
Ok, can you specify the link of your hls.js, so i can test it.
Is there a way to force use of capprl hls plugin on Android instead of native HLS of Android devices?

**Comment by towerz** [comment]
@alouane you can force clappr to try using hls.js instead of a simple html5 video tag. It's not guaranteed it will work or be activated at all, it depends on browser/webview support for MSE.

To try using hls.js for android you can try this:
```javascript
var player = new Clappr.Player({
  source: 'some/video.m3u8',
  // ...
  plugins: [Clappr.HLS]
});
```

**Comment by towerz** [comment]
@leandromoreira I agree, we can change the default playback priority to include hls.js before the default html5 video playback.

**Comment by alouane** [comment]
@towerz PERFECT! it's working, very smooth! Thanks

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/commit/295acc7ad28571fe24cf7268baf40c56c593c16c
