### ISSUE TITLE
Display Frame Number

### ISSUE THREAD

**Issue by ronag** [clappr/clappr#926]
In the player we currently see time as MM:SS. We would like to be able to see the frames as well. E.g MM:SS:FF.

Is this even possible?

**Comment by leandromoreira** [comment]
did you mean like the FPS?

**Comment by ronag** [comment]
@leandromoreira: I mean fractional seconds converted into frame numbers, e.g. 0.4 @ 25fps = 00:00:01

**Comment by iongion** [comment]
@leandromoreira - This should be implemented using a timer and using the normal Clappr events for playback to know when to suspend/resume the timer. You start the timer and then you read the current timestamp from the video - with this and knowing the framerate(you need it, it cannot be guessed from the video easily, for example in HLS streams you cannot, so to have a generic solution, find a way to pass this from outside) you can roughly estimate the current frame number. But it is not absolutely precise(no SLA, but can be precise enough for your use case) due format limitations of current browsers supported media types.

I do not think this should be part of Clappr Core, unknown framerate is really a show stopper. Start  a plugin and I will gladly contribute @ronag

**Comment by leandromoreira** [comment]
@iongion I'm doing a [stats plugin for clappr](https://github.com/leandromoreira/clappr-stats/blob/master/index.js#L133) which will inform the FPS by X seconds, is that helpful?

**Comment by iongion** [comment]
@leandromoreira allow milliseconds update rate - seconds is too much in many cases

**Comment by iongion** [comment]
@leandromoreira I saw you try to perform some framerate detection, please also allow it to be passed from outside for a better more imperative control, especially in the m3u8 playback

**Comment by leandromoreira** [comment]
@iongion you're right, thanks!

**Comment by leandromoreira** [comment]
>  I saw you try to perform some framerate detection, please also allow it to be passed from outside for a better more imperative control, especially in the m3u8 playback

I couldn't understand =/ can you provide an example?

**Comment by iongion** [comment]
@leandromoreira - `_fetchExtras` at line 120, while it works, if browsers support it, it would be nice to allow users to pass the frame rate as configuration option to the plugin and use that instead of the detection's - in this case you would also cover the cases when frame rate cannot be detected. Because there are a lot of of stats that can be computed on the frame-rate, a better control would be awesome, and is a good design choice too, no ? :+1:

**Comment by leandromoreira** [comment]
Yes, how about something more "dynamic"?

```javascript
{
 overrideMetrics: function(metrics) {
     metrics.counters.fps = 10;
 }
}
```

I think this could let users to update certain values instead of passing it statically at initialization, what do you think?

**Comment by iongion** [comment]
@leandromoreira absolutely much better :dancer:

**Comment by leandromoreira** [comment]
done https://github.com/leandromoreira/clappr-stats/blob/master/index.js#L119 feedbacks are welcome

**Comment by leandromoreira** [comment]
@iongion I'm thinking now that both functions can offer you the same final result, ins't? I mean, you also use `onReport` callback to change/add metrics. Maybe, we should have only one.

```javascript
        onReport: (metrics) => {console.log(metrics)}, //not mandatory: callback function
        overrideMetrics: (metrics) => {metrics.counter.fps = 30} 
```

**Comment by rgaufman** [comment]
Any solution to this? - I want to show the elapsed time in greater granularity, e.g. currently it shows seconds, e.g. 00:02 / 00:30 - but what I want is 00:02.78 / 00:30.12. Anyone knows how to achieve this?
