### ISSUE TITLE
Question: custom MediaControl and custom Playback communication

### ISSUE THREAD

**Issue by 3dd13** [clappr/clappr#927]
### What I want to do

add a button to MyMediaControl which should trigger a method in MyHtml5Video

### Current Way

right now, inside MyMedieControl I can do this by

    this.container.playback.myPlaybackMethod()

### Question

is it the best practice way ?
should I also add a custom MyPlayer which builds an interface in between instead ?
or should I actually add a listenTo (and trigger) mechanism to MyHtml5Video and MyPlayer

thank you in advance !

**Comment by leandromoreira** [comment]
@3dd13 you could provide your own media control.

```javascript
MyMC extends { get overrideSomething(){return 1} }
new Clappr.Player({external: {mediaControl: MyMC}})
```

Or you could do a plugin like [Level selector](https://github.com/clappr/clappr-level-selector-plugin) which [includes itself within the existent media control](https://github.com/clappr/clappr-level-selector-plugin/blob/master/src/main.js#L83).

@clappr/core We need to provide examples about how to write your own media control.. anyway, do you agree with my advices above?

**Comment by towerz** [comment]
@3dd13, your call to `this.container.playback.myPlaybackMethod()` is correct. 

In Clappr, data flow is defined this way: components that broadcast data or inform conditions to unknown receivers should trigger events, and components that must interact with other elements within their own scope should call methods. Calling methods for known references to other components is the recommended way.

About the media control, you don't really need to implement a player instance, unless you have to change the player bootstrap logic in some way. If you only need to change the media control and playbacks, you can do it like @leandromoreira mentioned.

**Comment by 3dd13** [comment]
thanks guys ~
