### ISSUE TITLE
Several typos in Architecture wiki page

### ISSUE THREAD

**Issue by gamtiq** [clappr/clappr#932]
There are the following typos in [Architecture wiki page](https://github.com/clappr/clappr/wiki/Architecture):
> *Usualy* the player will talk with other components through core.

> an abstraction that *actualy play* the media, it might use

> which makes your program less coupling *in in* your plugin level

**Comment by leandromoreira** [comment]
Thank you @gamtiq  :smile: . You can directly (while logged in in github) edit and create PR to solve this issue.

**Comment by gamtiq** [comment]
Fixed.

**Comment by leandromoreira** [comment]
Thank you so much @gamtiq :)
