### ISSUE TITLE
Clappr integration with ionic issue

### ISSUE THREAD

**Issue by alouane** [clappr/clappr#933]
I have an issue with running clappr video player inside an ionic app (android):
Adding this line:
 `<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js">`
triggers this error: 

> Uncaught TypeError: Cannot read property 'srcEvent' of undefined

This error happens also on a web browser
Any help?

**Comment by leandromoreira** [comment]
Try to test using http://cdn.clappr.io/latest/clappr.js instead of jsdelivr

**Comment by alouane** [comment]
Didn't work, I have got the same problem. As you know, ionic is using angularjs, so I'm wondering if there is some incompatibility between clappr and angular
I had a similar problem with videojs + angular, but fortunately I found a working directive to run videojs.
Now I'm trying to get a solution for crappl. 
Our clients prefer Clappr than any other video player

**Comment by leandromoreira** [comment]
Thanks @alouane can you provide more info? (like the line where this error occurs) Because I couldn't find any place on clappr which has `srcEvent`

**Comment by towerz** [comment]
@alouane are you using any external plugins? Can you provide any test URL so we can try to reproduce the problem on a web browser?

**Comment by alouane** [comment]
Hi, after some debugging I found the source of the problem (It's not an angular incompatibility problem, but it's related to an ionic tag, somethings happens when I add this tag ` **<ion-side-menu-content>**)`.
See bellow my test: 
1- I install a fresh ionic app by taping: `ionic start ClapprTest tabs`
2- I add this script : `<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>` at the bottom of www/index.html, before `</body>` tag
3- I add this lines in www/templates/tabs.html : 
 `<ion-side-menus enable-menu-with-back-views="false">
 **<ion-side-menu-content> **
........
**</ion-side-menu-content>** 
</ion-side-menus>`

I think, probably this issue `Uncaught TypeError: Cannot read property 'srcEvent' of undefined` is related to the **<ion-side-menu-content>** tag
I thinks it's better to create a new issue at ionic project, I'm gonna close this issue right now

**Comment by Hezhenli** [comment]
Thanks @alouane can you provide more info? I also encountered this problem.

**Comment by alouane** [comment]
Well, as I said, the error comes out when you add this tag `<ion-side-menu-content>`.
Juste delete it, and everything should work properly
But in may case, I didn't delete this tag, since that error is not blocking the app, and I needed this tag
Cheers

**Comment by Hezhenli** [comment]
Thanks @alouane， I needed this tag too. But I found the when add tag <ion-side-menu-content>. The onContentTap function in ionic.bundle.min.js will execute more than one time. And at the first time,it is right. Can we do something to stop it?

**Comment by alouane** [comment]
I'm afraid no, are you getting some consequences with that error?

**Comment by Hezhenli** [comment]
HI @alouane，I think I found another way to solve this problem. I used another component instead `<ion-side-menu-content>`. [angular-snap](http://jtrussell.github.io/angular-snap.js/) working well. And the error never comes out. The example is follow [Left and right side drawers](http://plnkr.co/edit/iB8VfD?p=preview)

**Comment by Hezhenli** [comment]
HI @alouane, My page code is as follows
```
<snap-drawers>
    <snap-drawer>
        <ion-header-bar class="bar-stable" no-tap-scroll="true" align-title="center">
            <h1 class="title">Left Menu</h1>
        </ion-header-bar>
        <ion-content>
            <ion-list>
                <ion-item>
                    News
                </ion-item>
                <ion-item>
                    Visit
                </ion-item>
            </ion-list>
        </ion-content>
    </snap-drawer>
</snap-drawers>
<snap-content>
    <ion-view ng-controller="homeCtrl">
        <ion-header-bar class="bar-dark" no-tap-scroll="true" align-title="center">
            <div class="buttons">
                <a class="button button-icon icon ion-navicon" snap-toggle></a>
            </div>
            <h1 class="title">APP</h1>
            <div class="buttons">
                <a class="button button-icon icon ion-ios-search" href="#/search"></a>
            </div>
        </ion-header-bar>
        <ion-content lazy-scroll class="has-header" delegate-handle="homeScroll">
            <ion-refresher on-refresh="doRefresh()" spinner="android"></ion-refresher>
                   MyContent
            <ion-infinite-scroll ng-if="hasMore" on-infinite="loadMore()" spinner="spiral"
                                 distance="1%"></ion-infinite-scroll>
        </ion-content>
    </ion-view>
</snap-content>
```

**Comment by alouane** [comment]
nice work! glad that you made it. Here's a useful directive for clappr integration with angular: [https://github.com/Defina-se/angular-clappr](url)
