### ISSUE TITLE
How to detect FlasHLS?

### ISSUE THREAD

**Issue by mikeevstropov** [clappr/clappr#935]
**Browser**: Yandex Browser 16.4.0.6115 beta (64-bit)
**OS**: Linux Mint 17.1
**Clappr Version**: 0.2.47

I want to know when FlasHLS automatically activated.
Can someone show me method or property?
Thank you.

p.s. And this browser always throwing exception with FlasHLS.
``` console
[.PPAPIContext]GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions.
```

**Comment by towerz** [comment]
@mikeevstropov you can check whether the FlasHLS supports your source by using the static `canPlay` method. It's used when loading the most suited playback for a given source.
```javascript
Clappr.FlasHLS.canPlay('http://your/source.m3u8')
```
This will check whether flash is installed, etc. One detail is that in Clappr, the default HLS priority is using hls.js (with MSE), the native video tag, and when all else failed, FlasHLS.

About this error, it's an error within the PPAPI flash implementation. There seems to be a bug in Chromium related to rendering surfaces on some Linux implementations. I don't remember the details, but there's an open bug for Chromium for that error.

**Comment by mikeevstropov** [comment]
@towerz Thank you for answer!
Maybe we have other(dirty) way without query on server?

**Comment by mikeevstropov** [comment]
I found! It's so simple...
``` javascript
player.getPlugin('flashls') && console.log("Browser can't playing without FlasHLS");
```

**Comment by towerz** [comment]
@mikeevstropov I didn't understand what you really wanted at first, you want to check whether or not the player loaded the media source using FlasHLS, not if it would load using it prior to initializing the player. Yes, this check you discovered is actually right, and will work if you need to check for other types of playback as well.

About the static check I mentioned (`canPlay`), it doesn't make a round trip to the server, it only tries to check the URL pattern or mime type passed as parameters, as well as MSE/Flash support on the browser.

**Comment by mikeevstropov** [comment]
@towerz Okay. I understood about `canPlay`.
The main reason for the search is the problem with buffering.
I placed a banner to the player. It's look like a preroll. When user clicks to "play" the player has start buffering and show ad. Second click on the "close ad" the player will hide banner and starts playing.
``` javascript
function startBufferingAndShowAd (e) {
     e.stopPropagation();
     player.play(); player.pause();
     playerContainer.removeEventListener('click', startBufferingAndShowAd, true);
     showBanner();
}
playerContainer.addEventListener('click', startBufferingAndShowAd, true)
```
But `player.pause();` is not working when the Clappr uses FlasHLS plugin.

**Comment by towerz** [comment]
@mikeevstropov I see, but there's one detail about pausing HLS streams. Is it a live stream or VoD?

With live streams, Clappr will only support pausing when the stream has DVR support. This means that your stream needs to have a duration longer than a given threshold set. The default threshold for minimum duration needed to be considered supporting DVR is 1 minute. You can configure this setting the option `hlsMinimumDvrSize` (in seconds) when instantiating the player.

**Comment by mikeevstropov** [comment]
@towerz 
I use VoD stream. And trouble with `pause()` only on FlasHLS plugin.

**Comment by towerz** [comment]
No, it can't. It seems to be a bug on the FlasHLS playback, or FlasHLS itself. I'll open another issue related to this problem so we can sort this out. Thanks, @mikeevstropov

**Comment by mikeevstropov** [comment]
@towerz Ok. Thank you too! Now I can catch the error.
