### ISSUE TITLE
SmoothSetLevel on HLS playback raising GL_INVALID_VALUE

### ISSUE THREAD

**Issue by flavioribeiro** [clappr/clappr#95]
When playerSmoothSetLevel(), Google Chrome raises
`[.PPAPIContext]GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions.`
Chrome version: 33.0.1750.152

Reading on forums, it seems that it's a bug on opengl+gpu+chrome+MacOS integration. Need to test on other browsers and SO's and if not reproducible, close this issue as wontfix.

**Comment by slash851** [comment]
@flavioribeiro it can be reproduced here:
http://video.consilium.europa.eu/en/webcast/0174310a-ff8b-4a48-8619-45eb4a66095f

Chrome 48 / win7 64bit
