### ISSUE TITLE
Visualizing Sound

### ISSUE THREAD

**Issue by alouane** [clappr/clappr#952]
Is there a way to visualize hls audio streaming equalizer when playing the audio, something like: https://dzone.com/articles/exploring-html5-web-audio ?

**Comment by leandromoreira** [comment]
I think @flavioribeiro has already opened one issue for this.

**Comment by alouane** [comment]
Hi, I'm trying to create a simple canvas with animation, but I have this problem, can you help me? How I can get a HTMLMediaElement from clappr object?
I have this code:
 `audio = document.getElementById('Clappr_ID');
canvas = document.getElementById('EquializerAnimation');
	ctx = canvas.getContext('2d');
	source = context.createMediaElementSource(audio); `
And I'm getting this error: `Failed to execute 'createMediaElementSource' on 'AudioContext': parameter 1 is not of type 'HTMLMediaElement'.`
this problem should be fixed if I do something like `<audio id='Clappr_ID'></audio>` but the problem is Clappr doesn't work with audio tag

**Comment by towerz** [comment]
@alouane actually Clappr does work with the audio tag. There's a playback used for audio, but the Clappr element is not the playback tag. Instead, it wraps around the playback tag.

You could try something like this:
```javascript
player = new Clappr.Player(...)  
audio = player.core.getCurrentPlayback().el; // assuming that your source is an audio file
// ... audio will be the <audio> tag you expect
```

**Comment by alouane** [comment]
Hi thanks for you answer, but I got this error:
`Cannot read property 'getCurrentPlayback' of undefined`
probably getCurrentPlayback() is called when the player object is steal undefined
Is there a way to call getCurrentPlayback after Clappr/player is initiated

**Comment by alouane** [comment]
Ok, I fixed the problem, I was calling `var player = new Clappr.Player(..)` right after `<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>`, So I moved the player initialization to the bottom right after <body> tag and it worked! Thanks again +1
