### ISSUE TITLE
[FlasHLS] error on event playback:bitrate trigger  w/ level selector plugin enabled

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr#958]
**Browser**: All (tested on Chrome and Firefox)

**Clappr Version**: 0.2.48

**Steps to reproduce**:

* open http://cdn.clappr.io/ with Firefox browser and change source to http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8
* enable Level Selector Plugin http://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js
* click play, open browser console
* you can see a message:
**[error][flashls]** error on event playback:bitrate trigger

Reproduced on http://cdn.clappr.io/

config tested with cdn.clappr.io:

``` javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640,
  plugins: [LevelSelector, Clappr.FlasHLS]
});

player.attachTo(playerElement);
```

![2016-04-21 03-00-17](https://cloud.githubusercontent.com/assets/222185/14694219/f337b6de-076e-11e6-8b7e-6af736c7b5c6.png)
![2016-04-21 03-00-55](https://cloud.githubusercontent.com/assets/222185/14694220/f33adcce-076e-11e6-9608-f72a195d606f.png)

**Comment by leandromoreira** [comment]
Thanks @me-vlad

**Comment by leandromoreira** [comment]
It seems that is an issue with LevelSelector

**Comment by leandromoreira** [comment]
For some odd reason the `levelchanged` is being called before `fragmentloaded`

**Comment by leandromoreira** [comment]
I'll fix but I think we should investigate this further maybe it's something new with FlashHLS.

**Comment by me-vlad** [comment]
FlasHLS was updated to 0.4.4.21 before Clappr 0.2.48 was released 
https://github.com/clappr/clappr/commit/2ae87904020f885c0fffa5c26fc23e731e9f8979

**Comment by leandromoreira** [comment]
Yeah , maybe we were doing wrong.
> HLSEvent.MANIFEST_LOADED - when this event is received, main manifest and start level has been retrieved (playlist duration is available)
