### ISSUE TITLE
How to get AudioBufferSourceNode from Clappr Element

### ISSUE THREAD

**Issue by alouane** [clappr/clappr#963]
As you know if you want to decode Audio Data, createMediaElementSource() is not working on mobile devices, However createBufferSource() method is working properly. So I'm asking how we can get an AudioBufferSourceNode from Clappr Player.

I can do something like:
 `player = new Clappr.Player(..);
audioSource = player.core.getCurrentPlayback().el; // here I get a MediaElementAudioSourceNode
source = context.createMediaElementSource(audioSource); `
But it will not work in mobile devices, I'm looking for a way to create source audio by createBufferSource() method
Any help?

**Comment by leandromoreira** [comment]
@alouane do you want to use the video tag element?

**Comment by alouane** [comment]
Hi @leandromoreira, thanks for asking, this bug actually comes from chromimum browser: [link](https://bugs.chromium.org/p/chromium/issues/detail?id=419446) Besides, after I read many articles, I understood that it's impossible to convert a MediaElementAudioSourceNode (not working on chromimum ) to an AudioBufferSourceNode to fix this bug [link](https://groups.google.com/a/chromium.org/forum/?fromgroups#!topic/chromium-html5/HkX1sP8ONKs)
(I posted this issue on [StackOverflow](http://stackoverflow.com/questions/36800909/convert-mediaelementaudiosourcenode-to-audiobuffersourcenode)

But what I want to know @leandromoreira, is it possible to view the equalizer when playing audio files inside clappr like this [example](https://dzone.com/articles/exploring-html5-web-audio)?

**Comment by leandromoreira** [comment]
ohh @alouane that depends on the playback, if you want to dig that info you can try to https://github.com/dailymotion/hls.js

**Comment by alouane** [comment]
Yeah, I want to get/see the equalizer when playing an hls streaming (like a radio streaming), but in your example, it juste read streaming inputs, Clappr does it, and works fine in mobile devices (android chrome and chromium) but the problem is even if I use this hls.js, it want get the byte frequency in order to draw the equalizer by canvas for android, I guess it is impossible!, I think I will juste wait until chromium fix this issue (A lot of people are complaining about it!)
Anyway Thanks @leandromoreira for your time ;) cheers

**Comment by leandromoreira** [comment]
I see for that level of information I also guess it's impossible. :) thank you !!!!
