### ISSUE TITLE
Volume mobile display

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#964]
When player width is below 320px, the volume control in the mediacontrol bar is just an single ugly bar.

This is visible on cdn.clappr.io by setting width to 240 for example.

**Comment by leandromoreira** [comment]
We didn't develop the UX and UI for mobile but it's in the plans.

**Comment by towerz** [comment]
@leandromoreira actually, there's a small bug on the volume control style. When the volume control is hidden, there's still a single bar from the segmented control which is still visible, but stretched vertically.
![screenshot 2016-04-26 23 56 41](https://cloud.githubusercontent.com/assets/989801/14840450/cf8057be-0c0a-11e6-987f-31f6a07ef849.png)

When hovering on the icon and displaying the controls, the appearance seems fine:
![screenshot 2016-04-26 23 56 52](https://cloud.githubusercontent.com/assets/989801/14840492/1801ba64-0c0b-11e6-9de1-7f56bb45f12c.png)

@irongomme when the player width is smaller than 320px the volume control is collapsed into the volume icon, only becoming visible when hovering on it. The "ugly bar" is indeed a bug, but collapsing the volume control isn't.
