### ISSUE TITLE
Google Analytics - does anyone have more details about what metrics clappr can provide via GA?

### ISSUE THREAD

**Issue by ibreakstuff93** [clappr/clappr#988]
Seeking more information around the Google Analytics integration and what metrics you can actually get from Clappr in to Google?

If anyone has a GA guide specifically for use with Clappr that would be a big help, or some example reports produced in google to show the kind of things that can be done. 

Thanks.

**Comment by leandromoreira** [comment]
I think the [GA plugin provided on Clappr is not working good](https://github.com/clappr/clappr/blob/master/src/plugins/google_analytics/google_analytics.js), we should create an external plugin for it.

Follow the (readme to configure it.)[https://github.com/clappr/clappr#google-analytics-plugin]

In theory we're sending events: ["{macro dimension ex:Video}", "{Event ex: Play}", "{video source ex: http://example.com/myvideosrouce.hls}"]

```javascript
      this.listenTo(this.container, Events.CONTAINER_READY, this.onReady)
      this.listenTo(this.container, Events.CONTAINER_PLAY, this.onPlay)
      this.listenTo(this.container, Events.CONTAINER_STOP, this.onStop)
      this.listenTo(this.container, Events.CONTAINER_PAUSE, this.onPause)
      this.listenTo(this.container, Events.CONTAINER_ENDED, this.onEnded)
      this.listenTo(this.container, Events.CONTAINER_STATE_BUFFERING, this.onBuffering)
      this.listenTo(this.container, Events.CONTAINER_STATE_BUFFERFULL, this.onBufferFull)
      this.listenTo(this.container, Events.CONTAINER_ENDED, this.onEnded)
      this.listenTo(this.container, Events.CONTAINER_ERROR, this.onError)
      this.listenTo(this.container, Events.CONTAINER_PLAYBACKSTATE, this.onPlaybackChanged)
      this.listenTo(this.container, Events.CONTAINER_VOLUME, (event) => this.onVolumeChanged(event))
      this.listenTo(this.container, Events.CONTAINER_SEEK, (event) => this.onSeek(event))
      this.listenTo(this.container, Events.CONTAINER_FULL_SCREEN, this.onFullscreen)
      this.listenTo(this.container, Events.CONTAINER_HIGHDEFINITIONUPDATE, this.onHD)
      this.listenTo(this.container, Events.CONTAINER_PLAYBACKDVRSTATECHANGED, this.onDVR)
```

does this help?

**Comment by ibreakstuff93** [comment]
That's great. Thank you!

**Comment by mattLummus** [comment]
@leandromoreira regarding this statement: "we should create an external plugin for it." Do you have an status on this idea? I would also point out that we are using Mixpanel to track play data and it would be nice to be able to at the least fork an external plugin and swap out the consumer

**Comment by leandromoreira** [comment]
@mattLummus I'm planing to do that (GA plugin) my first step was to do a [stats plugin](https://github.com/leandromoreira/clappr-stats) so we can have data to send out.

> it would be nice to be able to at the least fork an external plugin and swap out the consumer (i.e. send data to mixpanel instead of GA).

Are GA and Mixpanel using the same API? if yes, it's okay otherwise I'd say to create two different plugins.

> I would be happy to help contribute this but wanted to see if any progress had been started yet that I am not aware of

I didn't start it yet mostly because I'm struggling with the usage of GA for sending video metrics, I'm trying to see a better, flexible and feasible way to send data.

For instance we could consider two events: hit and view, being `hit` for when you click on play and `view` for when you watched at least 30s of the video (or in the end of the video). We also need to be open for multi dimension. By the way how do you use GA in your case? and what do you need from it? Do you use it to measure UX? views?

**Comment by mattLummus** [comment]
@leandromoreira Their API's are fairly similar. For example, via [Mixpanel's documentation](https://mixpanel.com/help/reference/tracking-an-event):
```mixpanel.track("Video played", {
        "Video length": 213,
        "id": "hY7gQr0"
    });```

For our case we want to capture basic play stats: play started, 50% playthrough, etc. as well as errors. So I like the idea of separating 'hit' and 'view', but I'd also like to have a little more control on how much of the video they've watched, so not necessarily just 30s but also 25,50,75, and 100% of the video being watched. I see in your stats-plugin that you can fetch these periodically, so thats something we could make work even if it wasn't completely baked in

Later on we would want to use some more of the events such as seeking, pausing, etc. and possibly buffer events as well to measure performance, but the basic stats get us going.

**Comment by leandromoreira** [comment]
> not necessarily just 30s but also 25,50,75, and 100%

It'd be nicer to have them as an array of percentages `[25,50,75,100]` and then convert them to GA events `['view_25p', 'view_50p']`.

> Later on we would want to use some more of the events such as seeking, pausing, etc. and possibly buffer events as well to measure performance, but the basic stats get us going.

We could send buffer time, how many seeks, pauses (and pause times) using the `stats plugin` but this also could lead you to overuse your GA account. How would you expect to use this data? (an event, hit... or use it as a multi dimension) Because you can send a single metric at time for GA (with multi-dimensions, for instance `'view_75p', {bufferTime: 9023, pauses: 1}`)

I'm looking a reasonable way to use GA to send metrics (mostly timers and counters), I [read the documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/pages) to see what we can do and basically I saw:

```javascript
// page tracking
ga('send', 'pageview', [page], [fieldsObject]); // does it makes sense to use this?

// event tracking - this we could use this to track view_10p, view_25p ...
ga('send', {   
  hitType: 'event',
  eventCategory: 'Videos',
  eventAction: 'play',
  eventLabel: 'Fall Campaign'
});
// timing tracking - the problem here is WHEN because the buffering increases.. :(
ga('send', {
  hitType: 'timing',
  timingCategory: 'buffering',
  timingVar: 'buffering',
  timingValue: 3549
});
//exception handler
ga('send', 'exception', {
  'exDescription': err.message,
  'exFatal': false
});
```

I mean, I want to offer a way use it in a proper way, without generating lots of costs ($$$) but adding value (aka sending valuable metrics). It's hard. 

If we send lots of events it'll increase the costs and how about the other metrics (counters and timers)? I really appreciate you help 😄

**Comment by mattLummus** [comment]
@leandromoreira So getting back to work on our analytics integration today I feel like I have a little more clarity. To me events triggering the report probably seems more helpful than setting an interval.

I.e., instead of reporting every 5 seconds or so,  I want to generate the report at appropriate times. Notably, when a video ends on a full playthrough, the source is changed, or when the player is removed by the user changing pages, closing their browser, erroring, etc. And I definitely like the playthrough percentages being triggered as events themselves, but it would be simpler to get one 100% playthrough stat, vs 4 (one for each 25% of the playthrough)

That way I can send off the completed stats for that play "session" without flooding our analytics channels.

**Comment by leandromoreira** [comment]
Now I'm thinking about the API. The way people are going to use this plugin. I think the plugin implementation will be easier than the stats.

WIP \/ (I'm working on it)
```javascript
container: {
   ga: {
       // https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet
       bootstrapJS: 'var j=1;...', // default: latest
       trackerName: '', // mandatory
       progressPercentage: [50,74], // default: [] - sends hitType: 'event',  eventCategory: 'Videos',  eventAction: 'progress_30p'
       progressSeconds: [30], // default: [] - sends hitType: 'event',  eventCategory: 'Videos',  eventAction: 'progress_30s',
       eventsToTrack: [
                'seek', 'end', 'play', 'pause', 'buffering', 
                'fullscreen', 'volume', 'error', 'stop', '...'
       ] // default: [] - sends   hitType: 'event',  eventCategory: 'Videos',  eventAction: 'x',
    }
}
```

> the source is changed, or when the player is removed by the user changing pages,

Do you mean to track the `load`? (changing source) and `destroy` ? (playing being removed)

**Comment by towerz** [comment]
I'd suggest some small changes to the proposed options:
```javascript
// It's recommended to always use the plugin name for plugin-specific options, but there's no need for scoping it under `core` or `container`
   ga: {
       // https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet
       // Perhaps it's better to use a funcion instead of evaluating a JS string
       bootstrapJS: function() { var j=1;... }, // default: latest
       trackingId: 'UA-XXXXX-Y', // *mandatory  - the tracking ID / web property ID.mandatory
       cookieDomain: 'auto', // default : 'auto' - document.location.hostname (normalized)
       name: 'myTracker',   // default: undefined -Naming a tracker is necessary in cases where you need to create more than one tracker for the same page,  if presents it'll send ga('myTracker.send', 'x', 'y');
       userId: '12345', // default: Randomly Generated & persisted in cookie
       progressPercentage: [50,74], // default: [] - sends hitType: 'event',  eventCategory: 'Videos',  eventAction: 'progress_30p'
       progressSeconds: [30], // default: [] - sends hitType: 'event',  eventCategory: 'Videos',  eventAction: 'progress_30s',
       eventsToTrack: [
                'seek', 'end', 'play', 'pause', 'buffering', 
                'bufferfull', 'fullscreen', 'volume', 'error', 'stop', '...'
       ] // default: [] - sends   hitType: 'event',  eventCategory: 'Videos',  eventAction: 'x',
    }

// custom dimension and metric!
ga('send', 'pageview', {
  'dimension15':  'My Custom Dimension'
});
ga('send', 'event', 'category', 'action', {
  'metric18': 8000
});
```

**Comment by kslimani** [comment]
i'd suggest additional parameters to be able to customise event category names and label :

```
// It's recommended to always use the plugin name for plugin-specific options, but there's no need for scoping it under `core` or `container`
   ga: {
       // https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet
       // Perhaps it's better to use a funcion instead of evaluating a JS string
       bootstrapJS: function() { var j=1;... }, // default: latest
       trackingId: 'UA-XXXXX-Y', // *mandatory  - the tracking ID / web property ID.mandatory
       cookieDomain: 'auto', // default : 'auto' - document.location.hostname (normalized)
       name: 'myTracker',   // default: undefined -Naming a tracker is necessary in cases where you need to create more than one tracker for the same page,  if presents it'll send ga('myTracker.send', 'x', 'y');
       userId: '12345', // default: Randomly Generated & persisted in cookie
       progressPercentage: [50,74], // default: [] - sends hitType: 'event',  eventCategory: 'Videos',  eventAction: 'progress_30p'
       progressSeconds: [30], // default: [] - sends hitType: 'event',  eventCategory: 'Videos',  eventAction: 'progress_30s',
       eventsToTrack: [
                'seek', 'end', 'play', 'pause', 'buffering', 
                'bufferfull', 'fullscreen', 'volume', 'error', 'stop', '...'
       ] // default: [] - sends   hitType: 'event',  eventCategory: 'Videos',  eventAction: 'x',
       eventCategories: {
         'videoEvent': 'Video',
         'interactionEvent': 'Interaction',
         // more can be added in future if required/missed
       },
       eventLabel: 'My video title', // optional, default to this.container.playback.src
    }

// custom dimension and metric!
ga('send', 'pageview', {
  'dimension15':  'My Custom Dimension'
});
ga('send', 'event', 'category', 'action', {
  'metric18': 8000
});
```

**Comment by leandromoreira** [comment]
@kslimani thanks, so your idea is to customize eventCategory:
`hitType: 'event',  eventCategory: 'Videos or defined by user',  eventAction: '[one from the list]',`

What would be an `interactionEvent`?

**Comment by kslimani** [comment]
@leandromoreira the "interaction" comes from the [current core ga plugin](https://github.com/clappr/clappr/blob/master/src/plugins/google_analytics/google_analytics.js#L100). But it is obsolete if new ga plugin use the same category for all events. (and therefore an  eventCategory string property is enough)

**Comment by leandromoreira** [comment]
@kslimani my idea is to use `eventAction` = some of the bellow list.

```
 eventsToTrack: [
                'seek', 'end', 'play', 'pause', 'buffering', 
                'bufferfull', 'fullscreen', 'volume', 'error', 'stop', '...'
       ]
```

**Comment by kslimani** [comment]
@leandromoreira for event names imo a list of event to track seems enough.
if you want to go deeper in customization you could also provide an object with the event name as key and the event action value to use.

```
eventsToTrack: {
    'seek': 'videoSeek', // default is 'seek'
    'end': 'videoEnd',    // default is 'end'
    'play': 'videoStart',  // default is 'play'
    // etc...
}
```

This could be usefull for someone who wants to migrate to Clappr player but need to reproduce the GA event action used by previous player tracking library.

But the cons is it complicate the option format.

**Comment by towerz** [comment]
Perhaps we could add another parameter for these event mappings instead of changing the `eventsToTrack` parameter. Something like:
```javascript
eventsToTrack: [ 'seek', 'end', 'play', ... ], // this will only control what kind of events should be tracked
eventMapping: { // these mappings will change the values to be used instead of the event keys themselves
  seek: 'videoSeek',
  end: 'videoEnd',
  play: 'videoStart',
  ...
}
```

**Comment by kslimani** [comment]
In the meantime, i started one here : https://github.com/playmedia/clappr-ga-events-plugin
I am stuck on how to implement "progress" events, especially for progression in seconds, i am not sure how to handle live streams and also what to do if user seek video for VOD.

**Comment by leandromoreira** [comment]
Cool @kslimani about the progress for live events I think you can start a timer and then from time to time you sent "Xs" ... I mean this process must be done outside the events (but considering them too). This project might give you some hints https://github.com/leandromoreira/clappr-stats

**Comment by kslimani** [comment]
@leandromoreira i agree for live events, i was also thinking for pooling system.

Do you have any thoughts about what to do if user "seek" video ?

**Comment by leandromoreira** [comment]
In live events you can count DVRusage (being a counter and a timer, a counter for the times a given user have used DVR feature and timer to measure how many time he/she spent while on DVR).... this is one thought.

**Comment by kslimani** [comment]
@leandromoreira thank you. I will take a closer look at this feature.
