### ISSUE TITLE
Stream playing on Firefox not working

### ISSUE THREAD

**Issue by Luc3as** [clappr/clappr#990]
**Browser**: Firefox 46.0.1

**OS**: Windows 7/8/8.1/10

**Clappr Version**: 0.2.25  latest from https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

**Steps to reproduce**:

when opening our stream from camera in firefox http://vps.tntel.sk/nemsova.html  nothing happens I just get black screen and loading gif in the middle 
![image](https://cloud.githubusercontent.com/assets/6381468/15180236/9939051c-1780-11e6-86c0-2c764f417307.png)

when playing in chrome or on android there is no problem, stream just works. 
![image](https://cloud.githubusercontent.com/assets/6381468/15180299/f8ba9bc2-1780-11e6-8419-de4927202e1c.png)

I tried to reproduce error at http://cdn.clappr.io/   even with other stream 
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://vps.tntel.sk/hls/fsh/playlist.m3u8',
  baseUrl: '/latest',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

however results are still the same.

**Comment by leandromoreira** [comment]
Hi @Luc3as it seems that this problem could be:

1. A problem in your HLS generation (or even the source of it, your camera, your rtmp stream...), I downloaded a single .ts file and ran a checking tool (mediainfo single.ts) it printed lots of errors `E: File read error`
2. A problem with [hls.js](http://dailymotion.github.io/hls.js/demo/) (which is the playback we use to play hls) but I hardly believe this.

I'd say double check the number 1.

**Comment by Luc3as** [comment]
there were some bug in the hls.js 
https://github.com/dailymotion/hls.js/issues/439#issuecomment-218720232

how soon is possible to implement new hls.js version in latest clapper from cdn ?

**Comment by leandromoreira** [comment]
@Luc3as it really depends on delivr cdn also we need to wait an official hls.js release to include it on clappr.

**Comment by leandromoreira** [comment]
https://github.com/dailymotion/hls.js/issues/439

**Comment by anoopksreyas** [comment]
Guy's need a help.

I'm trying to seek clappr player like below.
player.seek(time);

Here time is a variable that holds value in seconds. Strangely its not working with the 'time' variable. It is working if i hardcode the value like player.seek(50.8888); .

Any quick replies??

**Comment by leandromoreira** [comment]
@anoopksreyas did you check the value of time? (if it's integer/string or null )

**Comment by anoopksreyas** [comment]
Thanks leanleandromoreira. 

typeof(time) returns number.

**Comment by anoopksreyas** [comment]
Sorry guys. Mistake was from side. I was triggering play.seek(time) on OnSeek event where time = player.getCurrentTime (). Its only giving me the time where seek start.  So as a work around now im calling seek inside OnPlay event.  

Thanks.
