### ISSUE TITLE
Cannot receive metadata without playing

### ISSUE THREAD

**Issue by iongion** [clappr/clappr#995]
In my use cases I need to process the metadata before considering the player "usable".
So, I do the following, with `autoplay=false`:
```
player.core.on(Clappr.Events.CORE_CONTAINERS_CREATED, () => {
  const playback = player.core.getCurrentPlayback();
  playback.on(
    Clappr.Events.PLAYBACK_LOADEDMETADATA,
    (em) => {
      player.pause();
    }
  );
});
player.load(source);
player.play();
```

But then the browser shows an exception:
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```

And further investigating this error shows everytime one does:
```
player.pause();
player.seek(targetTime);
player.play();
```

Then how should the proper handling be done, with proper event handling ?
```
playback.once(Clappr.Events.PLAYBACK_PAUSE, () => {
  player.once(Clappr.Events.PLAYER_SEEK, () => {
    if (wasPlaying) {
      console.debug('must play - seek done');
      player.play();
    }
  });
  player.seek(targetTime);
});
player.pause();
```

But it manifests with the same error:
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```

How can I do it correctly ?
I want to have the metadata received, but without autoplay

**Comment by leandromoreira** [comment]
@iongion this error `...The play() request was interrupted by a call to pause().` is [related to chrome >= 50](https://bugs.chromium.org/p/chromium/issues/detail?id=593273) but this exception usually doesn't stop the playback.

**Comment by leandromoreira** [comment]
> I want to have the metadata received, but without autoplay.

We rely on [video tag loadedmetadata event](https://developer.mozilla.org/en-US/docs/Web/Events/loadedmetadata). I don't know if I clearly understood you but you could:

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

player.core.getCurrentPlayback().on(Clappr.Events.PLAYBACK_LOADEDMETADATA, function(e) {
  console.log('here', e)
})

player.on(Clappr.Events.PLAYER_PLAY, function() {player.pause()})
```

**Comment by iongion** [comment]
Yes, you are right, it was an m3u8, hence no metadata due to how hls.js works
